import { resolveProductUiLanguageOrDefault } from "@/i18n/config";

/**
 * Patient-facing Spanish Registration Packet legal copy.
 *
 * The packet chrome was translated previously while the legal summaries/bodies were
 * intentionally held in source language pending legal review. That produced mixed
 * English/Spanish packets. These translations preserve the existing legal meaning,
 * status, URLs and workflow; they do not change acknowledgments or persistence.
 */
const ES_REGISTRATION_PACKET: Record<string, string> = {
  "packetWizard.legalPendingNotice": "El contenido de este paquete de inscripción es un marco configurable por el establecimiento, pendiente de aprobación legal final, y no constituye asesoramiento legal.",
  "packetWizard.sectionAcknowledge": "Reconozco que he leído esta sección.",
  "packetWizard.insuranceAcknowledge": "Confirmo que la información del seguro y de otras coberturas indicada anteriormente es correcta según mi leal saber y entender.",

  "packetWizard.demographicsSummary": "Confirme su nombre legal, fecha de nacimiento, información de contacto y dirección para que podamos identificarle de forma segura y comunicarnos sobre su atención.",
  "packetWizard.demographicsFull": "Revise la información de identificación del paciente incluida en este paquete. Informe inmediatamente al personal si algún dato es incorrecto. Los campos demográficos opcionales, como nombre preferido, identidad de género, pronombres, idioma preferido o necesidad de intérprete, solo aparecen cuando el establecimiento los habilita. Los campos sensibles, como número de Seguro Social, raza, origen étnico, religión o empleador, nunca son obligatorios de forma universal y solo aparecen conforme a una política aprobada por el establecimiento.",

  "packetWizard.emergencyContactSummary": "Proporcione un contacto de emergencia y, cuando corresponda, una parte responsable o representante legal que pueda ayudar con decisiones de atención o comunicaciones de facturación.",
  "packetWizard.emergencyContactFull": "La información del contacto de emergencia y de la parte responsable ayuda al establecimiento a comunicarse con alguien si usted no puede hacerlo. Para menores o pacientes con tutor legal o representante de atención médica, identifique la relación del representante. Esta sección no designa a un representante para apelaciones de seguro ni autoriza la divulgación de expedientes más allá de lo necesario para tratamiento, pago y operaciones de atención médica, salvo que se complete una autorización separada.",

  "packetWizard.insuranceSummary": "Confirme la información de cobertura primaria y secundaria para que los beneficios disponibles puedan facturarse correctamente. Infórmenos sobre cualquier otra cobertura aplicable.",
  "packetWizard.insuranceFull": "Reconozco que la información del seguro proporcionada es correcta según mi leal saber y entender. Entiendo que las reglas de coordinación de beneficios pueden determinar qué plan paga primero. Si tengo Medicare, Medicaid, compensación laboral, cobertura de vehículo motorizado o de responsabilidad civil, informaré al personal. La información de beneficios de farmacia solo se recopila cuando lo requiere el flujo de trabajo de este establecimiento. Proporcionar información del seguro no garantiza cobertura ni montos de pago.",

  "packetWizard.consentSummary": "Autorizo al establecimiento y a sus profesionales clínicos a evaluarme y tratarme, incluidos exámenes médicamente apropiados, pruebas diagnósticas, medicamentos, procedimientos y otros servicios discutidos conmigo.",
  "packetWizard.consentFull": "Doy mi consentimiento para ser evaluado y tratado por este establecimiento y por sus clínicos empleados o acreditados, incluidos exámenes médicamente apropiados, estudios de laboratorio e imagen, medicamentos e intervenciones terapéuticas discutidas conmigo. Entiendo que la medicina no es una ciencia exacta y que no se garantiza ningún resultado específico. Puedo hacer preguntas y, cuando sea legal y clínicamente permitido, rechazar o retirar mi consentimiento. Las emergencias pueden requerir atención antes de que sea posible una conversación completa. Se requiere un consentimiento informado separado para los procedimientos que este establecimiento determine que necesitan consentimiento específico. Este consentimiento no autoriza investigación, fotografías con fines de mercadeo ni autorizaciones opcionales no relacionadas.",

  "packetWizard.aobSummary": "Autorizo la facturación de la cobertura disponible y entiendo que puedo ser responsable de deducibles, copagos, coseguro y cargos no cubiertos, sujeto a la ley aplicable.",
  "packetWizard.aobFull": "Cedo a este establecimiento los beneficios médicos pagaderos y autorizo el pago directo de los servicios cubiertos cuando esté permitido. Autorizo la divulgación de la información mínima necesaria para facturación y pago. Entiendo que sigo siendo financieramente responsable de deducibles, copagos, coseguro y cargos no cubiertos en la medida permitida por las leyes federales y estatales, incluidas las protecciones contra facturación sorpresa cuando correspondan. Pueden emitirse facturas separadas de profesionales, laboratorio, radiología, patología o proveedores cuando así esté configurado para este establecimiento. Las estimaciones no son garantías. Esta sección no renuncia a las protecciones de la Ley contra Facturas Sorpresa ni sustituye un aviso o documento de consentimiento separado cuando sea requerido.",

  "packetWizard.facilityDisclosureSummary": "Este paquete utiliza el nombre del establecimiento activo y las divulgaciones aprobadas por el establecimiento sobre el entorno de atención, afiliación, entidades de facturación y contactos.",
  "packetWizard.facilityDisclosureFull": "La identidad del establecimiento, el tipo de entorno de atención, la afiliación hospitalaria, la participación en redes, la propiedad médica, el estado de contratistas independientes, la participación en Medicare/Medicaid, los cargos del establecimiento o de observación, las capacidades de traslado, los contactos para reclamaciones y los recursos de transparencia de precios se muestran únicamente desde la configuración aprobada por el establecimiento. No se utilizan marcas de terceros codificadas, rangos de tarifas obsoletos ni afirmaciones de participación no configuradas. Solicite al personal el tarifario o la estimación vigente cuando correspondan montos. Los datos de contacto para privacidad, facturación y reclamaciones son los configurados para este establecimiento.",

  "packetWizard.privacySummary": "Reconozco que se me ha ofrecido el Aviso de prácticas de privacidad, que describe cómo puede utilizarse y divulgarse la información de salud y cómo puedo ejercer mis derechos de privacidad.",
  "packetWizard.privacyFull": "AVISO DE PRÁCTICAS DE PRIVACIDAD — ACUSE DE RECIBO Y RESUMEN (marco basado en el modelo del HHS para proveedores de atención médica; los contactos y la fecha de vigencia específicos provienen de la configuración del establecimiento).\n\nEste establecimiento puede usar y divulgar información de salud protegida para tratamiento, pago y operaciones de atención médica según lo permitido por HIPAA. Otros usos y divulgaciones pueden incluir actividades de salud pública y seguridad, supervisión sanitaria, compensación laboral, donación de órganos, médicos forenses, determinados fines de las fuerzas del orden, procedimientos judiciales y administrativos y otros fines exigidos o permitidos por la ley. Usted tiene derecho a acceder y obtener una copia de sus expedientes, solicitar enmiendas, solicitar restricciones, pedir comunicaciones confidenciales, recibir un informe de determinadas divulgaciones y presentar una queja ante el contacto de privacidad del establecimiento o la Oficina de Derechos Civiles del HHS. Puede solicitar una copia impresa del Aviso completo. Abrir o ampliar esta sección registra que el texto completo estuvo disponible; por sí solo no demuestra que haya leído cada palabra. Los datos de contacto del responsable de privacidad son los configurados para este establecimiento, no los de una marca de terceros.\n\nGuía completa del modelo del HHS: https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/privacy-practices-health-care-provider/",

  "packetWizard.rightsSummary": "Usted tiene derecho a una atención respetuosa, informada y privada, y la responsabilidad de proporcionar información correcta y tratar a los demás con respeto.",
  "packetWizard.rightsFull": "Los derechos pueden incluir: atención respetuosa y no discriminatoria; participación en las decisiones; información comprensible; consentimiento informado; rechazo del tratamiento cuando la ley lo permita; privacidad y confidencialidad; acceso a los expedientes; asistencia para la comunicación y servicios de intérprete; información sobre directivas anticipadas cuando corresponda; atención segura y libre de abuso; procesos de quejas y reclamaciones; información sobre cargos; derechos de visita o de persona de apoyo cuando correspondan; información sobre traslados; y elección respecto a la participación en investigaciones. Las responsabilidades pueden incluir proporcionar información correcta, hacer preguntas, seguir los planes de atención acordados cuando sea posible, respetar al personal y a otras personas, cumplir las políticas de seguridad, proporcionar información de seguro/pago, informar al personal sobre cambios y cumplir las responsabilidades financieras conforme a la ley aplicable. Prevalecen las políticas de derechos específicas del establecimiento; este texto es un marco pendiente de aprobación legal y no constituye la adopción automática de una carta de derechos de terceros.",

  "packetWizard.advanceDirectivesSummary": "Infórmenos si tiene una directiva anticipada y si desea recibir información o proporcionar una copia.",
  "packetWizard.advanceDirectivesFull": "Una directiva anticipada expresa sus preferencias sobre futuras decisiones de atención médica y puede designar a un representante de atención médica. Informe al personal si tiene una directiva anticipada, desea información o quiere proporcionar una copia. Los entornos de urgencias y establecimientos independientes pueden tener límites operativos diferentes de los hospitales con internación; este aviso no afirma obligaciones idénticas de hospitalización sin confirmación legal del establecimiento. Si usted no puede responder, el personal documentará esa situación.",

  "packetWizard.personalBelongingsSummary": "Proteja sus objetos de valor. Pregunte al personal por cualquier proceso de custodia disponible en el establecimiento.",
  "packetWizard.personalBelongingsFull": "Se recomienda a los pacientes conservar únicamente los artículos esenciales y proteger los objetos de valor. Cuando este establecimiento ofrezca custodia, el personal documentará el inventario conforme a la política del establecimiento. Este aviso no crea una renuncia general e ilegal de responsabilidad; prevalecen la ley aplicable y la política del establecimiento.",

  "packetWizard.communicationsSummary": "Elija cómo podemos comunicarnos con usted sobre atención, citas y facturación. El consentimiento para mercadeo es separado y opcional.",
  "packetWizard.communicationsFull": "Puede consentir llamadas telefónicas, correo de voz, SMS, correo electrónico y/o mensajes del portal del paciente para coordinación de atención, citas/seguimiento y comunicaciones de facturación según lo ofrezca este establecimiento. Las comunicaciones electrónicas no cifradas conllevan riesgos de privacidad. Puede retirar sus preferencias de comunicación para el futuro. Esta sección no autoriza comunicaciones de mercadeo; el mercadeo requiere una autorización opcional separada cuando se ofrezca.",

  "packetWizard.safetyPolicySummary": "No se permiten armas ni artículos prohibidos. Los controles de seguridad y la participación de las fuerzas del orden se rigen por la política del establecimiento y la ley aplicable.",
  "packetWizard.safetyPolicyFull": "Para la seguridad de pacientes, visitantes y personal, no se permiten armas ni otros artículos prohibidos en las instalaciones, salvo cuando la ley disponga lo contrario. El personal puede implementar controles de seguridad conforme a la política del establecimiento. La disposición de artículos prohibidos y cualquier participación de las fuerzas del orden se rigen por la ley aplicable y la política del establecimiento. Este reconocimiento es configurable por el establecimiento y no se ha copiado de ningún paquete histórico de terceros.",

  "packetWizard.grievanceSummary": "Puede presentar una queja ante el establecimiento y, cuando corresponda, ante organismos estatales o federales. Los contactos provienen de la configuración del establecimiento.",
  "packetWizard.grievanceFull": "Puede plantear inquietudes a la dirección del establecimiento, a un defensor del paciente, al área de cumplimiento o al responsable de privacidad utilizando la información de contacto configurada para el establecimiento. Las quejas de privacidad también pueden presentarse ante la Oficina de Derechos Civiles del HHS. Los establecimientos de Texas pueden proporcionar información para quejas ante HHSC cuando corresponda. Los contactos de CMS u otros organismos estatales solo aparecen cuando están configurados para este establecimiento. Los datos de contacto se versionan mediante la configuración del establecimiento y nunca se toman de un paquete de una marca de terceros.",

  "packetWizard.nondiscriminationSummary": "Este establecimiento no discrimina y proporciona asistencia lingüística y adaptaciones por discapacidad según lo requerido y configurado.",
  "packetWizard.nondiscriminationFull": "Cuando la Sección 1557 u otros requisitos de no discriminación se apliquen a este establecimiento según su configuración, el establecimiento proporcionará un aviso de no discriminación, adaptaciones por discapacidad y asistencia lingüística, incluido el acceso a intérpretes. Los contactos de accesibilidad y asistencia lingüística son los configurados para este establecimiento. La aplicabilidad es configurable por el establecimiento y está sujeta a revisión legal.",

  "packetWizard.medicareMedicaidSummary": "La participación de este establecimiento en Medicare y Medicaid se indica únicamente según la configuración aprobada por el establecimiento; nunca se presume.",
  "packetWizard.medicareMedicaidFull": "El estado de participación en Medicare y/o Medicaid se determina exclusivamente mediante la configuración aprobada de divulgación de inscripción de este establecimiento. Si la participación está configurada como DOES_NOT_PARTICIPATE, usted puede ser responsable de los cargos en la medida permitida por la ley y debe preguntar por alternativas hospitalarias que puedan aceptar estos programas. Si está configurada como PARTICIPATES, la facturación sigue las reglas aplicables del programa. Si el estado es NOT_CONFIGURED, el personal no debe afirmar que el establecimiento no participa; solicite el estado escrito vigente antes de confiar en cualquier afirmación sobre participación. No se incluyen montos de tarifas obsoletos de formularios históricos.",

  "packetWizard.emtalaSummary": "Cuando EMTALA se aplica a la configuración de este establecimiento, usted tiene derecho a un examen médico de detección y a tratamiento estabilizador de las condiciones médicas de emergencia dentro de la capacidad del establecimiento.",
  "packetWizard.emtalaFull": "Cuando la configuración EmtalaApplicability de este establecimiento sea HOSPITAL_EMERGENCY_DEPARTMENT o HOSPITAL_AFFILIATED_OFF_CAMPUS_ED, o esté configurada de otro modo como aplicable a EMTALA, las normas federales de EMTALA pueden exigir un examen médico de detección y tratamiento estabilizador de las condiciones médicas de emergencia dentro de la capacidad del establecimiento, independientemente de la capacidad de pago. Los establecimientos de urgencias independientes no se consideran automáticamente hospitales sujetos a EMTALA; el texto se selecciona únicamente mediante una configuración aprobada del establecimiento. Fuente: guía de CMS sobre EMTALA.",

  "esignature.patientAttestation": "Certifico que la firma anterior es mía o que estoy autorizado legalmente para firmar en nombre del paciente, y que la información y los reconocimientos de este paquete son correctos según mi leal saber y entender.",
  "esignature.staffAttestation": "Certifico que presencié o verifiqué el proceso de firma o rechazo documentado anteriormente y que este registro refleja lo ocurrido según mi leal saber y entender.",
};

export function resolveRegistrationPacketSpanishOverride(
  language: string,
  key: string,
): string | undefined {
  if (resolveProductUiLanguageOrDefault(language) !== "es") return undefined;
  return ES_REGISTRATION_PACKET[key];
}
