/** Phase 19G — PHI-safe audit entity types for controlled runtime activation. */

export const MEDICATION_FORMULARY_APPROVED_AUDIT = "MEDICATION_FORMULARY_APPROVED_INACTIVE";
export const MEDICATION_ORDER_SEARCH_ENABLED_AUDIT = "MEDICATION_ORDER_SEARCH_ENABLED";
export const MEDICATION_MAR_ENABLED_AUDIT = "MEDICATION_MAR_ENABLED";
export const MEDICATION_BILLING_REVIEW_REQUESTED_AUDIT = "MEDICATION_BILLING_REVIEW_REQUESTED";
export const MEDICATION_BILLING_ENABLED_AUDIT = "MEDICATION_BILLING_ENABLED";
export const MEDICATION_RUNTIME_DISABLED_AUDIT = "MEDICATION_RUNTIME_DISABLED";

export type MedicationActivationAuditAction =
  | "APPROVE_FORMULARY_INACTIVE"
  | "ENABLE_ORDER_SEARCH"
  | "ENABLE_MAR"
  | "REQUEST_BILLING_REVIEW"
  | "ENABLE_BILLING"
  | "DISABLE_RUNTIME";
