"use client";
import{useI18n}from"@/i18n/I18nProvider";import{useEffect,useMemo,useState}from"react";import{useParams}from"next/navigation";import{isRecentMfaError,platformCapabilitiesApi,platformPrivilegedActionsApi,platformStaffApi}from"@/lib/platform/api";import{Page,Badge}from"@/features/platform/PlatformUi";import{usePlatformStepUp}from"@/features/platform/PlatformStepUp";import{usePlatform}from"@/features/platform/PlatformContext";import{can}from"@/features/platform/access";import{MEDORA_STAFF_PERSONA_OPTIONS,parseMedoraStaffPersonaCode}from"@/lib/platform/staffPersona";

type AccessGroup={title:string;description:string;includes:string;icon:string;codes:string[]};
const IT_ACCESS_GROUPS:AccessGroup[]=[
 {title:"Patient Access & Registration",description:"Patient search, registration, demographics, and chart access.",includes:"Patient records, chart viewer",icon:"♙",codes:["IT_CARE_PATIENT_RECORDS"]},
 {title:"Clinical Care",description:"Clinic, urgent care, observation, inpatient, and encounter workflows.",includes:"Encounters, clinical documentation",icon:"⚕",codes:["IT_CARE_CLINIC","IT_CARE_URGENT_CARE","IT_CARE_OBSERVATION"]},
 {title:"Orders & Results",description:"Medication orders, lab orders, radiology orders, and results.",includes:"Orders, results, imaging reports",icon:"⌬",codes:["IT_CARE_ORDERS"]},
 {title:"Medications & Pharmacy",description:"Medication management and pharmacy modules.",includes:"eRx, MAR, pharmacy, formulary",icon:"◇",codes:["IT_CARE_PHARMACY"]},
 {title:"Laboratory",description:"Lab ordering, results, and laboratory configuration.",includes:"Lab test catalog, results, interfaces",icon:"△",codes:["IT_CARE_LABORATORY"]},
 {title:"Radiology & Imaging",description:"Imaging orders, results, and radiology workflows.",includes:"Radiology orders, imaging viewer",icon:"▣",codes:["IT_CARE_RADIOLOGY"]},
 {title:"Hospital Operations",description:"Emergency, inpatient, bed management, and hospital workflows.",includes:"ED, inpatient, transfer, discharge",icon:"▥",codes:["IT_CARE_EMERGENCY","IT_CARE_INPATIENT_HOSPITAL"]},
 {title:"Scheduling & Appointments",description:"Scheduling, resource management, and visit workflows.",includes:"Scheduling, visit types, resources",icon:"▦",codes:["IT_CARE_SCHEDULING"]},
 {title:"Telemedicine & Digital Care",description:"Virtual visits, patient messaging, and digital care tools.",includes:"Telemedicine, Digital Care, patient portal",icon:"◫",codes:["IT_CARE_TELEMEDICINE","IT_CARE_DIGITAL_CARE","IT_CARE_PATIENT_PORTAL"]},
 {title:"Billing / RCM",description:"Facility billing workflows and revenue-cycle troubleshooting.",includes:"Facility billing support",icon:"$",codes:["IT_CARE_BILLING"]},
 {title:"Facility & Configuration",description:"Facility settings, modules, workflows, and system configuration.",includes:"Facility configuration and platform operations",icon:"⚙",codes:["FACILITY_CONFIGURE","CATALOG_CONFIG_VIEW","CATALOG_CONFIG_MANAGE"]},
 {title:"AI & Advanced Tools",description:"AI tools and advanced platform features.",includes:"AI workflows and platform tools",icon:"✣",codes:["IT_CARE_AI"]},
];

export default function StaffDetail(){
 const{formatDate,t}=useI18n();const{id}=useParams<{id:string}>(),step=usePlatformStepUp(),{context}=usePlatform();
 const[row,setRow]=useState<any>(),[capabilities,setCapabilities]=useState<any[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<string|null>(null),[showAdvanced,setShowAdvanced]=useState(false);
 const load=async()=>{try{setRow(await platformStaffApi.detail(id));if(can(context,"STAFF_GRANT_CAPABILITIES"))setCapabilities(await platformCapabilitiesApi.list())}catch(e){if(isRecentMfaError(e))await step(load);else setError(e instanceof Error?e.message:"Unable to load")}};
 useEffect(()=>{void load()},[id,context]);
 async function secured(run:()=>Promise<unknown>){try{setError("");await run();await load()}catch(e){if(isRecentMfaError(e))await step(async()=>{await run();await load()});else throw e}}
 const activeCodes=useMemo(()=>new Set((row?.grants??[]).filter((g:any)=>g.isActive).map((g:any)=>g.capability.code)),[row]);
 const isGroupOn=(g:AccessGroup)=>g.codes.every(c=>activeCodes.has(c));
 async function grantCode(code:string,reason:string){const selected=capabilities.find(c=>c.code===code);if(!selected)throw new Error(`Capability catalog is missing ${code}`);if(selected.riskLevel==="CRITICAL"&&!context?.platformPrincipal)return platformPrivilegedActionsApi.create({operationType:"STAFF_GRANT_CAPABILITY",targetUserId:id,capabilityCode:code,reason});return platformStaffApi.grant(id,{code,reason})}
 async function setGroup(g:AccessGroup,on:boolean){setBusy(g.title);setMessage("");try{await secured(async()=>{for(const code of g.codes){if(on&&!activeCodes.has(code))await grantCode(code,`Technology / IT access: enable ${g.title}`);if(!on&&activeCodes.has(code))await platformStaffApi.revoke(id,code,`Technology / IT access: disable ${g.title}`)}});setMessage(`${g.title} ${on?"enabled":"disabled"}.`)}catch(e){setError(e instanceof Error?e.message:"Access update failed")}finally{setBusy(null)}}
 async function setAll(on:boolean){setBusy("all");setMessage("");try{await secured(async()=>{for(const g of IT_ACCESS_GROUPS)for(const code of g.codes){if(on&&!activeCodes.has(code))await grantCode(code,"Technology / IT access: enable all selected areas");if(!on&&activeCodes.has(code))await platformStaffApi.revoke(id,code,"Technology / IT access: disable all areas")}});setMessage(on?"All Technology / IT access areas enabled.":"All Technology / IT access areas disabled.")}catch(e){setError(e instanceof Error?e.message:"Bulk access update failed")}finally{setBusy(null)}}
 async function lifecycle(kind:"activate"|"deactivate"){const reason=window.prompt(`${kind} reason`)?.trim();if(reason)await secured(()=>platformStaffApi[kind](id,reason))}
 async function grant(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),code=String(f.get("capabilityCode")),reason=String(f.get("reason"));try{await secured(()=>grantCode(code,reason));setMessage("Capability updated.")}catch(e){setError(e instanceof Error?e.message:"Grant denied")}}
 async function persona(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await secured(()=>platformStaffApi.persona(id,parseMedoraStaffPersonaCode(f.get("persona")),String(f.get("reason"))))}
 const allOn=IT_ACCESS_GROUPS.every(isGroupOn);
 return <Page area="staff" title={row?`${row.user.firstName} ${row.user.lastName}`:t("staff.profileFallback")} subtitle={t("staff.profileSubtitle")}>
  {error&&<p className="platform-error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
  {row&&<div className="staff-access-page">
   <section className="staff-profile-summary"><div><div className="staff-meta-line"><span>User ID <code>{row.userId}</code></span><Badge value={row.persona||"UNASSIGNED"}/></div><div className="staff-status-row"><span><i/>User {row.user.isActive?"active":"inactive"}</span><span><i/>Staff {row.isActive?"active":"inactive"}</span><span className={row.user.mfaEnabled?"":"status-warning"}><i/>MFA {row.user.mfaEnabled?"enabled":"not enabled"}</span></div></div><div>{row.isActive&&can(context,"STAFF_PROVISION")&&<button className="button secondary-button" onClick={()=>void lifecycle("deactivate")}>Deactivate staff</button>}</div></section>
   {row.isActive&&can(context,"STAFF_GRANT_CAPABILITIES")&&<section className="platform-panel it-access-panel"><div className="it-access-heading"><div><h2>Technology / IT Administration</h2><p>Select the areas this Technology / IT staff member can access for support and troubleshooting. You control each area independently.</p></div><div className="it-bulk-actions"><button type="button" className="outline-button" disabled={busy!==null||allOn} onClick={()=>void setAll(true)}>Enable all</button><button type="button" className="outline-button" disabled={busy!==null||!IT_ACCESS_GROUPS.some(isGroupOn)} onClick={()=>void setAll(false)}>Disable all</button></div></div>
    <div className="it-access-grid">{IT_ACCESS_GROUPS.map((g,i)=>{const on=isGroupOn(g),working=busy===g.title||busy==="all";return <article className={`it-access-card tone-${i%6}`} key={g.title}><div className="it-access-icon" aria-hidden>{g.icon}</div><div className="it-access-copy"><h3>{g.title}</h3><p>{g.description}</p><small>Includes: {g.includes}</small></div><button type="button" role="switch" aria-checked={on} aria-label={`${on?"Disable":"Enable"} ${g.title}`} className={`access-switch ${on?"on":""}`} disabled={working} onClick={()=>void setGroup(g,!on)}><span/></button></article>})}</div>
    <aside className="it-access-important"><b>ⓘ &nbsp; Important</b><ul><li>Technology/IT staff can be granted broad or limited access based on your organization&apos;s needs.</li><li>Unselected areas remain restricted.</li><li>Changes take effect after the access update completes.</li><li>All access remains audited and subject to Medora security, compliance, and privacy policies.</li></ul></aside>
   </section>}
   <section className="platform-panel advanced-access"><button className="advanced-toggle" type="button" onClick={()=>setShowAdvanced(v=>!v)} aria-expanded={showAdvanced}><span><b>Advanced capability management</b><small>Review individual grants, provenance, risk levels, and exceptional permissions.</small></span><span>{showAdvanced?"Hide":"Show"} ▾</span></button>{showAdvanced&&<div className="advanced-access-body"><div className="grant-chip-grid">{row.grants.map((g:any)=><article className={g.isActive?"active":"revoked"} key={g.id}><div><Badge value={g.capability.code}/><small>{g.capability.riskLevel} · {g.provenance}</small></div>{g.isActive&&can(context,"STAFF_REVOKE_CAPABILITIES")&&<button className="text-button" onClick={()=>{const reason=window.prompt("Revocation reason")?.trim();if(reason)void secured(()=>platformStaffApi.revoke(id,g.capability.code,reason))}}>Revoke</button>}</article>)}</div>{can(context,"STAFF_GRANT_CAPABILITIES")&&<form className="platform-form advanced-grant-form" onSubmit={grant}><h3>Grant individual capability</h3><label>Capability<select name="capabilityCode">{capabilities.map(c=><option key={c.code} value={c.code}>{c.name||c.code} — {c.riskLevel}</option>)}</select></label><label>Business reason<textarea name="reason" required minLength={3}/></label><button className="button high-risk">Grant access</button></form>}</div>}</section>
   {context?.platformPrincipal&&<section className="platform-panel advanced-access"><button className="advanced-toggle" type="button" onClick={()=>setShowAdvanced(true)}><span><b>Persona & lifecycle administration</b><small>Owner-only identity classification and historical evidence.</small></span></button>{showAdvanced&&<><form className="platform-form persona-form" onSubmit={persona}><label>Persona<select name="persona" defaultValue={row.persona}>{MEDORA_STAFF_PERSONA_OPTIONS.map(option=><option key={option.value} value={option.value}>{t(option.labelKey)}</option>)}</select></label><label>Reason<textarea name="reason" required minLength={3}/></label><button className="button high-risk">Change persona</button></form><div className="lifecycle-list">{row.lifecycle.map((x:any,i:number)=><p key={i}><b>{x.eventType}</b><span>{formatDate(x.createdAt)}</span><small>{x.reason}</small></p>)}</div></>}</section>}
  </div>}
 </Page>
}
