/**
 * MEDUI.ED.DISCHARGE.TEMPLATE_FAMILY_COVERAGE.2 — Tier 2 ED families (conservative routing).
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";

export const TIER2_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] = [
  {
    id: "chf_exacerbation",
    label: "CHF Exacerbation",
    templateId: "cardio_heart_failure_symptoms_v1",
    clinicalDomain: "Cardiac",
    icdExact: ["I50.9", "I50.23"],
    icdPrefixes: ["I50"],
    keywords: ["heart failure", "chf", "congestive heart failure"],
    guardrails: {
      safety: {
        highRiskEscalation: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Heart failure symptoms with cardiology follow-up and weight/fluid precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Heart failure"],
  },
  {
    id: "copd_exacerbation",
    label: "COPD Exacerbation",
    templateId: "copd_exacerbation_v1",
    clinicalDomain: "Respiratory",
    icdPrefixes: ["J44"],
    excludeIcdPrefixes: ["J45"],
    keywords: ["copd", "copd exacerbation", "chronic obstructive pulmonary disease"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "pulmonology",
    riskCategory: "moderate",
    clinicalRationale: "COPD exacerbation distinct from asthma J45 family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — COPD"],
  },
  {
    id: "asthma_exacerbation_tier2",
    label: "Asthma Exacerbation",
    templateId: "asthma_exacerbation_v1",
    clinicalDomain: "Respiratory",
    icdExact: ["J45.901", "J45.909"],
    icdPrefixes: ["J45.9"],
    keywords: ["asthma exacerbation"],
    specialtyCategory: "pulmonology",
    riskCategory: "moderate",
    clinicalRationale: "Tier-2 explicit asthma exacerbation ICD routing; complements asthma_wheezing family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Asthma"],
  },
  {
    id: "palpitations",
    label: "Palpitations",
    templateId: "palpitations_v1",
    additionalTemplateIds: ["cardio_afib_rate_controlled_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R00.2"],
    icdPrefixes: ["R00", "I48"],
    keywords: ["palpitations", "heart racing", "irregular heartbeat"],
    guardrails: {
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Palpitations with cardiac return precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Palpitations"],
  },
  {
    id: "vertigo_tier2",
    label: "Vertigo (explicit)",
    templateId: "vertigo_dizziness_v1",
    clinicalDomain: "Neurologic",
    icdExact: ["H81.10", "H81.11"],
    icdPrefixes: ["H81.1"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["benign vertigo", "bppv"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Peripheral vertigo codes; excludes stroke/TIA prefixes.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dizziness and vertigo"],
  },
  {
    id: "concussion",
    label: "Concussion",
    templateId: "concussion_mild_tbi_v1",
    additionalTemplateIds: ["pediatric_concussion_v1"],
    clinicalDomain: "Neurologic",
    icdExact: ["S06.0X0A", "S06.0X1A"],
    icdPrefixes: ["S06.0"],
    keywords: ["concussion", "mild traumatic brain injury"],
    guardrails: {
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "neurology",
    riskCategory: "moderate",
    clinicalRationale: "Concussion return-to-activity precautions (Phase 10 — dedicated concussion_mild_tbi_v1 template, distinct from generic minor head injury).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Concussion"],
  },
  {
    id: "minor_head_injury",
    label: "Minor Head Injury",
    templateId: "minor_head_injury_v1",
    additionalTemplateIds: ["pediatric_minor_head_injury_v1"],
    clinicalDomain: "Trauma",
    icdPrefixes: ["S09", "S00"],
    excludeIcdPrefixes: ["S06.0"],
    icdExactTemplateOverrides: {
      "S00.93XA": "pediatric_minor_head_injury_v1",
    },
    keywords: ["minor head injury", "head injury", "scalp laceration"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Minor head trauma without documented concussion code.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Head injuries"],
  },
  {
    id: "seizure_tier2",
    label: "Seizure (explicit)",
    templateId: "seizure_v1",
    clinicalDomain: "Neurologic",
    icdExact: ["G40.909", "R56.9"],
    icdPrefixes: ["R56.9"],
    keywords: ["first seizure", "new onset seizure"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "neurology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Explicit seizure codes with neurology follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Seizures"],
  },
  {
    id: "dvt_evaluation",
    label: "DVT Evaluation",
    templateId: "high_risk_medical_leg_swelling_v1",
    clinicalDomain: "Cardiac",
    icdPrefixes: ["I82"],
    keywords: ["dvt evaluation", "leg swelling dvt", "deep vein thrombosis follow-up"],
    guardrails: {
      safety: {
        highRiskEscalation: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "hematology",
    riskCategory: "high",
    clinicalRationale:
      "Conservative high-risk leg-swelling template for DVT evaluation discharge; confirmed DVT uses escalation template, not low-risk routing. PE remains UNSAFE_DO_NOT_MAP.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Deep vein thrombosis"],
  },
  {
    id: "pe_evaluation_discharge",
    label: "PE Evaluation Discharge",
    templateId: "high_risk_medical_leg_swelling_v1",
    clinicalDomain: "Cardiac",
    icdPrefixes: ["I26"],
    keywords: ["pe evaluation", "pulmonary embolism follow-up"],
    guardrails: {
      safety: {
        highRiskEscalation: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "pulmonology",
    riskCategory: "high",
    clinicalRationale:
      "UNSAFE for low-risk template routing — audit-only family; production resolver unchanged.",
    reviewStatus: "draft",
    routingStatus: "UNSAFE_DO_NOT_MAP",
    sourceReferenceLabels: ["MedlinePlus — Pulmonary embolism"],
  },
  {
    id: "hypertensive_urgency_followup",
    label: "Hypertensive Urgency Follow-Up",
    templateId: "cardio_hypertension_elevated_bp_v1",
    clinicalDomain: "Cardiac",
    icdExact: ["I16.0", "I16.9"],
    icdPrefixes: ["I16"],
    keywords: ["hypertensive urgency", "elevated bp urgency"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Hypertensive urgency with BP recheck and return precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood pressure"],
  },
  {
    id: "hyperglycemia_tier2",
    label: "Hyperglycemia",
    templateId: "hyperglycemia_v1",
    clinicalDomain: "Endocrine",
    icdExact: ["R73.9", "E11.65"],
    icdPrefixes: ["R73"],
    excludeIcdExact: ["E11.9"],
    keywords: ["hyperglycemia", "elevated glucose"],
    specialtyCategory: "endocrinology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Acute hyperglycemia; excludes stable E11.9 type 2 family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood sugar"],
  },
  {
    id: "hypoglycemia",
    label: "Hypoglycemia",
    templateId: "hypoglycemia_v1",
    clinicalDomain: "Endocrine",
    icdExact: ["E16.2", "E16.1"],
    icdPrefixes: ["E16"],
    keywords: ["hypoglycemia", "low blood sugar"],
    guardrails: {
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "endocrinology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Hypoglycemia with glucose monitoring and return precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Low blood sugar"],
  },
  {
    id: "aki_followup",
    label: "Acute Kidney Injury Follow-Up",
    templateId: "renal_aki_followup_v1",
    additionalTemplateIds: [
      "renal_electrolyte_abnormality_followup_v1",
      "urology_pyelonephritis_followup_v1",
    ],
    clinicalDomain: "Genitourinary",
    icdExact: ["N17.9", "N17.0"],
    icdPrefixes: ["N17"],
    keywords: ["aki follow-up", "acute kidney injury"],
    guardrails: {
      safety: {
        requiresSpecialistFollowUp: true,
        requiresEdReturnPrecautions: true,
      },
    },
    specialtyCategory: "nephrology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "AKI outpatient follow-up with nephrology precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Kidney disease"],
  },
] as const;
