/**
 * MEDUI.ED.DISCHARGE.TEMPLATE_FAMILY_COVERAGE.2 — Tier 1 high-volume ED families.
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";

export const TIER1_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] = [
  {
    id: "pediatric_fever",
    label: "Pediatric Fever",
    templateId: "pediatric_fever_v1",
    clinicalDomain: "General Medical",
    icdExact: ["R50.9", "R50.81"],
    icdPrefixes: ["R50"],
    excludeIcdExact: ["R50.2"],
    guardrails: {
      age: { maxAgeYears: 18 },
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "pediatrics",
    riskCategory: "moderate",
    clinicalRationale: "Pediatric fever with age guardrail.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fever"],
  },
  {
    id: "fever",
    label: "Fever",
    templateId: "infectious_fever_unknown_source_v1",
    additionalTemplateIds: ["sepsis_risk_return_precautions_v1"],
    clinicalDomain: "General Medical",
    icdExact: ["R50.9", "R50.81"],
    icdPrefixes: ["R50"],
    excludeIcdExact: ["R50.2"],
    guardrails: {
      age: { minAgeYears: 18 },
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale:
      "Pediatric fever uses age-guarded override; adult fever uses unknown-source infectious precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fever"],
  },
  {
    id: "generalized_weakness",
    label: "Generalized Weakness",
    templateId: "high_risk_medical_general_weakness_v1",
    additionalTemplateIds: ["high_risk_medical_fatigue_v1"],
    clinicalDomain: "General Medical",
    icdExact: ["R53.1", "R53.83"],
    icdPrefixes: ["R53"],
    excludeIcdExact: ["R55"],
    keywords: ["generalized weakness", "weakness", "asthenia"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Non-syncope weakness with high-risk return precautions; excludes R55 syncope family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fatigue"],
  },
  {
    id: "dehydration",
    label: "Dehydration",
    templateId: "dehydration_v1",
    additionalTemplateIds: [
      "renal_dehydration_followup_v1",
      "pediatric_mild_dehydration_v1",
      "pediatric_dehydration_escalation_v1",
    ],
    clinicalDomain: "General Medical",
    icdExact: ["E86.0", "E86.1"],
    icdPrefixes: ["E86"],
    keywords: ["dehydration", "volume depletion"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Volume depletion with hydration escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dehydration"],
  },
  {
    id: "pediatric_otitis_media",
    label: "Pediatric Otitis Media",
    templateId: "pediatric_otitis_media_v1",
    clinicalDomain: "ENT",
    icdExact: ["H66.9", "H66.90"],
    icdPrefixes: ["H66"],
    excludeIcdPrefixes: ["J02", "J03"],
    keywords: ["pediatric otitis", "child ear infection"],
    guardrails: { age: { maxAgeYears: 18 } },
    specialtyCategory: "pediatrics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Pediatric otitis media with age guardrail.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Ear infections"],
  },
  {
    id: "otitis_media",
    label: "Otitis Media",
    templateId: "otitis_pharyngitis_v1",
    clinicalDomain: "ENT",
    icdExact: ["H66.9", "H66.90"],
    icdPrefixes: ["H66"],
    excludeIcdPrefixes: ["J02", "J03"],
    keywords: ["otitis media", "ear infection"],
    guardrails: { age: { minAgeYears: 18 } },
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Adult otitis media; pediatric otitis uses separate age-guarded family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Ear infections"],
  },
  {
    id: "pharyngitis_tonsillitis",
    label: "Pharyngitis / Tonsillitis",
    templateId: "otitis_pharyngitis_v1",
    additionalTemplateIds: ["infectious_pharyngitis_v1"],
    clinicalDomain: "ENT",
    icdExact: ["J02.9", "J03.90"],
    icdPrefixes: ["J02", "J03"],
    excludeIcdPrefixes: ["H66"],
    keywords: ["pharyngitis", "tonsillitis", "sore throat", "strept throat"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Upper airway pharyngeal infection distinct from otitis media routing.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sore throat"],
  },
  {
    id: "dental_pain",
    label: "Dental Pain",
    templateId: "dental_pain_v1",
    clinicalDomain: "Dental",
    icdPrefixes: ["K08", "K04", "K05"],
    keywords: ["dental pain", "toothache", "tooth pain"],
    specialtyCategory: "dentistry",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Dental source pain with dental follow-up guidance.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Tooth disorders"],
  },
  {
    id: "sinusitis",
    label: "Sinusitis",
    templateId: "infectious_sinusitis_v1",
    clinicalDomain: "ENT",
    icdExact: ["J01.90", "J01.91"],
    icdPrefixes: ["J01"],
    keywords: ["sinusitis", "sinus infection"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Acute sinusitis with conservative antibiotic stewardship language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sinusitis"],
  },
  {
    id: "bronchitis",
    label: "Bronchitis",
    templateId: "bronchitis_v1",
    clinicalDomain: "Respiratory",
    icdPrefixes: ["J20", "J40"],
    keywords: ["bronchitis", "acute bronchitis"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Acute bronchitis outpatient care; distinct from pneumonia family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Bronchitis"],
  },
  {
    id: "influenza",
    label: "Influenza",
    templateId: "pediatric_influenza_like_illness_v1",
    clinicalDomain: "Respiratory",
    icdExact: ["J10.1", "J11.1"],
    icdPrefixes: ["J09", "J10", "J11"],
    keywords: ["influenza", "flu", "influenza-like illness"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Influenza-like illness with return precautions; uses established ILI template.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Flu"],
  },
  {
    id: "covid19",
    label: "COVID-19",
    templateId: "infectious_covid_like_illness_v1",
    clinicalDomain: "Respiratory",
    icdExact: ["U07.1", "J12.82"],
    icdPrefixes: ["U07"],
    keywords: ["covid", "covid-19", "coronavirus"],
    guardrails: {
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "COVID-19 / COVID-like illness with respiratory escalation precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — COVID-19"],
  },
  {
    id: "cutaneous_abscess",
    label: "Abscess",
    templateId: "abscess_without_drainage_v1",
    additionalTemplateIds: ["post_abscess_drainage_v1"],
    clinicalDomain: "Skin/Infection",
    icdPrefixes: ["L02"],
    keywords: ["abscess", "cutaneous abscess", "skin abscess"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale:
      "Phase 13: L02 cutaneous abscess routes to purulent abscess discharge text (not nonpurulent cellulitis_v1).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Abscess"],
  },
  {
    id: "kidney_stone",
    label: "Kidney Stone",
    templateId: "kidney_stone_v1",
    additionalTemplateIds: ["urology_renal_colic_followup_v1"],
    clinicalDomain: "Genitourinary",
    icdExact: ["N20.0", "N20.1"],
    icdPrefixes: ["N20"],
    keywords: ["kidney stone", "renal colic", "nephrolithiasis"],
    specialtyCategory: "urology",
    riskCategory: "moderate",
    clinicalRationale: "Renal colic / nephrolithiasis with urology follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Kidney stones"],
  },
  {
    id: "hematuria",
    label: "Hematuria",
    templateId: "urology_hematuria_followup_v1",
    clinicalDomain: "Genitourinary",
    icdExact: ["R31.9", "R31.0"],
    icdPrefixes: ["R31"],
    keywords: ["hematuria", "blood in urine"],
    specialtyCategory: "urology",
    riskCategory: "moderate",
    clinicalRationale: "Hematuria follow-up with urology precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Urinary tract infections"],
  },
  {
    id: "urinary_retention",
    label: "Urinary Retention",
    templateId: "urology_urinary_retention_followup_v1",
    clinicalDomain: "Genitourinary",
    icdExact: ["R33.9", "R33.8"],
    icdPrefixes: ["R33"],
    keywords: ["urinary retention", "unable to urinate"],
    specialtyCategory: "urology",
    riskCategory: "moderate",
    clinicalRationale: "Urinary retention with obstruction escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Urinary retention"],
  },
  {
    id: "viral_syndrome",
    label: "Viral Syndrome",
    templateId: "infectious_viral_syndrome_v1",
    additionalTemplateIds: ["pediatric_viral_syndrome_v1"],
    clinicalDomain: "General Medical",
    icdPrefixes: ["B34", "B97"],
    keywords: ["viral syndrome", "viral illness"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Undifferentiated viral illness with supportive care guidance.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Viral infections"],
  },
  {
    id: "allergic_reaction",
    label: "Allergic Reaction",
    templateId: "allergic_reaction_v1",
    additionalTemplateIds: ["pediatric_allergic_reaction_v1"],
    clinicalDomain: "Skin/Infection",
    icdPrefixes: ["T78.40", "L50", "T78.1"],
    keywords: ["allergic reaction", "hives", "urticaria"],
    guardrails: {
      safety: { requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "allergy_immunology",
    riskCategory: "moderate",
    clinicalRationale: "Non-anaphylaxis allergic reaction with return precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Allergy"],
  },
  {
    id: "pediatric_rash",
    label: "Pediatric Rash",
    templateId: "pediatric_rash_v1",
    clinicalDomain: "Skin/Infection",
    icdPrefixes: ["L30", "L20", "L21"],
    excludeIcdPrefixes: ["L50"],
    keywords: ["pediatric rash", "child rash"],
    guardrails: { age: { maxAgeYears: 18 } },
    specialtyCategory: "pediatrics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Pediatric rash with age guardrail.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Rashes"],
  },
  {
    id: "rash_dermatitis",
    label: "Rash / Dermatitis",
    templateId: "allergic_reaction_v1",
    additionalTemplateIds: ["pediatric_rash_v1"],
    clinicalDomain: "Skin/Infection",
    icdPrefixes: ["L30", "L20", "L21"],
    excludeIcdPrefixes: ["L50"],
    keywords: ["rash", "dermatitis", "eczema flare"],
    guardrails: { age: { minAgeYears: 18 } },
    specialtyCategory: "dermatology",
    riskCategory: "low_to_moderate",
    clinicalRationale:
      "Adult dermatitis/rash uses allergic reaction template conservatively; pediatric uses separate family.",
    reviewStatus: "reviewed",
    routingStatus: "NEEDS_REVIEW",
    sourceReferenceLabels: ["MedlinePlus — Rashes"],
  },
  {
    id: "constipation",
    label: "Constipation",
    templateId: "constipation_v1",
    additionalTemplateIds: ["pediatric_constipation_v1"],
    clinicalDomain: "Gastrointestinal",
    icdExact: ["K59.00"],
    icdPrefixes: ["K59.0"],
    excludeIcdExact: ["K59.1"],
    keywords: ["constipation"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Functional constipation distinct from diarrhea/gastroenteritis family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Constipation"],
  },
  {
    id: "nausea_vomiting_with_dehydration",
    label: "Nausea/Vomiting with Dehydration",
    templateId: "dehydration_v1",
    additionalTemplateIds: ["pediatric_vomiting_v1"],
    clinicalDomain: "Gastrointestinal",
    icdExact: ["E86.0"],
    keywords: ["nausea with dehydration", "vomiting dehydration"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale:
      "When dehydration code present, hydration template takes precedence over nausea-only family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dehydration"],
  },
  {
    id: "medication_refill_low_risk",
    label: "Medication Refill / Low-Risk Medication Issue",
    templateId: "wellness_visit_v1",
    clinicalDomain: "General Medical",
    icdExact: ["Z76.0", "Z53.09"],
    icdPrefixes: ["Z76"],
    keywords: ["medication refill", "prescription refill", "medication issue"],
    specialtyCategory: "primary_care",
    riskCategory: "low",
    clinicalRationale:
      "Low-risk medication administrative encounters; uses wellness template conservatively.",
    reviewStatus: "draft",
    routingStatus: "NEEDS_REVIEW",
    sourceReferenceLabels: ["MedlinePlus — Medicines"],
  },
] as const;
