/**
 * Phase 1 clinical condition families (21) — migrated with domain + routing status fields.
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";

export const PHASE1_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] = [
  {
    id: "nausea_vomiting",
    label: "Nausea / Vomiting",
    templateId: "nausea_vomiting_v1",
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R11.0", "R11.1", "R11.2", "R11.10"],
    icdPrefixes: ["R11"],
    excludeIcdExact: ["E86.0"],
    keywords: ["nausea", "vomiting", "emesis"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shared ED discharge guidance for nausea with or without vomiting.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Nausea and vomiting"],
  },
  {
    id: "cellulitis_skin_infection",
    label: "Cellulitis / Skin Infection",
    templateId: "cellulitis_v1",
    additionalTemplateIds: ["infectious_cellulitis_followup_v1"],
    clinicalDomain: "Skin/Infection",
    icdExact: ["L08.9", "L03.90", "L03.115", "L03.116"],
    icdPrefixes: ["L03", "L08"],
    excludeIcdPrefixes: ["L08.0", "L02"],
    keywords: ["cellulitis", "skin infection"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Soft-tissue infection discharge instructions; distinct from wound/laceration trauma care.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Cellulitis"],
  },
  {
    id: "uri_cough",
    label: "URI / Cough",
    templateId: "uri_cough_v1",
    additionalTemplateIds: ["infectious_upper_respiratory_infection_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["J00", "J06.9"],
    icdPrefixes: ["J06", "R05"],
    keywords: ["upper respiratory infection", "uri", "cough", "common cold", "rhinopharyngitis"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Age-neutral URI/cough template; pediatric URI uses separate guarded family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "pediatric_uri",
    label: "Pediatric URI",
    templateId: "pediatric_uri_v1",
    clinicalDomain: "Respiratory",
    keywords: ["pediatric uri", "pediatric upper respiratory", "child cold", "rhume enfant"],
    guardrails: { age: { maxAgeYears: 18 } },
    specialtyCategory: "pediatrics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Pediatric-only URI wording; requires pediatric age context or explicit pediatric keyword.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "chest_pain",
    label: "Chest Pain",
    templateId: "chest_pain_v1",
    additionalTemplateIds: ["cardio_chest_pain_low_risk_v1", "chest_wall_pain_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R07.9"],
    icdPrefixes: ["R07"],
    keywords: ["chest pain", "chest discomfort", "douleur thoracique"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Cardiac-safe return precautions for undifferentiated chest pain discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Chest pain"],
  },
  {
    id: "abdominal_pain",
    label: "Abdominal Pain",
    templateId: "abdominal_pain_v1",
    additionalTemplateIds: ["pediatric_abdominal_pain_v1"],
    clinicalDomain: "Gastrointestinal",
    icdPrefixes: ["R10"],
    excludeIcdExact: ["R10.2"],
    keywords: ["abdominal pain", "belly pain", "douleur abdominale"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "General abdominal pain; pelvic pain routed to OB/GYN family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Abdominal pain"],
  },
  {
    id: "headache",
    label: "Headache",
    templateId: "headache_v1",
    additionalTemplateIds: ["high_risk_medical_headache_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["R51", "G44"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["headache", "migraine", "cephalalgia", "céphalée"],
    specialtyCategory: "neurology",
    riskCategory: "moderate",
    clinicalRationale: "Primary headache discharge; excludes stroke/TIA red-flag templates.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Headache"],
  },
  {
    id: "uti_urinary_symptoms",
    label: "UTI / Urinary Symptoms",
    templateId: "uti_v1",
    additionalTemplateIds: ["urology_uti_followup_v1", "obgyn_uti_pregnancy_precautions_v1"],
    clinicalDomain: "Genitourinary",
    icdExact: ["N39.0"],
    icdPrefixes: ["R30", "N39"],
    keywords: ["urinary tract infection", "uti", "dysuria", "burning urination"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Uncomplicated urinary symptoms and UTI outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Urinary tract infections"],
  },
  {
    id: "gastroenteritis_diarrhea",
    label: "Gastroenteritis / Diarrhea",
    templateId: "gastroenteritis_v1",
    additionalTemplateIds: [
      "gi_infectious_gastroenteritis_v1",
      "pediatric_gastroenteritis_v1",
    ],
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R19.7", "A09", "K59.1"],
    icdPrefixes: ["R19", "A08"],
    keywords: ["diarrhea", "gastroenteritis", "loose stool"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Acute diarrheal illness; distinct from constipation family (K59.0*).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Gastroenteritis"],
  },
  {
    id: "back_pain",
    label: "Back Pain",
    templateId: "back_pain_v1",
    additionalTemplateIds: ["trauma_msk_back_strain_v1"],
    clinicalDomain: "Musculoskeletal",
    icdPrefixes: ["M54"],
    keywords: ["back pain", "low back pain", "sciatica"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Musculoskeletal back pain without acute neuro deficit documentation.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back pain"],
  },
  {
    id: "asthma_wheezing",
    label: "Asthma / Wheezing",
    templateId: "asthma_exacerbation_v1",
    additionalTemplateIds: ["pediatric_asthma_exacerbation_v1", "pediatric_wheezing_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["R06.2"],
    icdPrefixes: ["J45"],
    icdExactTemplateOverrides: {
      "R06.2": "pediatric_wheezing_v1",
    },
    keywords: ["asthma", "wheezing", "asthma exacerbation"],
    specialtyCategory: "pulmonology",
    riskCategory: "moderate",
    clinicalRationale: "Reactive airway disease discharge with inhaler safety language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Asthma"],
  },
  {
    id: "pneumonia_lower_respiratory",
    label: "Pneumonia / Lower Respiratory Infection",
    templateId: "pneumonia_v1",
    additionalTemplateIds: ["infectious_pneumonia_followup_v1"],
    clinicalDomain: "Respiratory",
    icdPrefixes: ["J18", "J15", "J16", "J17"],
    keywords: ["pneumonia"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Lower respiratory infection requiring outpatient reassessment.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Pneumonia"],
  },
  {
    id: "hypertension_elevated_bp",
    label: "Hypertension / Elevated BP",
    templateId: "hypertension_v1",
    additionalTemplateIds: ["cardio_hypertension_elevated_bp_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["I10", "R03.0"],
    icdPrefixes: ["I10"],
    keywords: ["hypertension", "elevated blood pressure", "high blood pressure"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Blood pressure chief complaint or known HTN management at discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood pressure"],
  },
  {
    id: "diabetes_hyperglycemia",
    label: "Diabetes / Hyperglycemia (acute)",
    templateId: "hyperglycemia_v1",
    clinicalDomain: "Endocrine",
    icdExact: ["E11.65"],
    icdPrefixes: ["R73"],
    excludeIcdExact: ["E11.9"],
    keywords: ["hyperglycemia", "high blood sugar"],
    specialtyCategory: "endocrinology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Acute hyperglycemia symptoms — not stable type 2 outpatient management.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood sugar"],
  },
  {
    id: "type_2_diabetes_non_acute",
    label: "Type 2 Diabetes (non-acute)",
    templateId: "type_2_diabetes_v1",
    additionalTemplateIds: ["diabetes_sick_day_precautions_v1"],
    clinicalDomain: "Endocrine",
    icdExact: ["E11.9"],
    icdPrefixes: ["E11"],
    excludeIcdExact: ["E11.65"],
    keywords: ["type 2 diabetes", "diabetes type 2", "diabète de type 2"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Stable type 2 diabetes outpatient instructions without implying acute hyperglycemia crisis.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Diabetes type 2"],
  },
  {
    id: "trauma_wound_laceration",
    label: "Trauma / Wound / Laceration",
    templateId: "wound_laceration_v1",
    clinicalDomain: "Trauma",
    icdExact: ["S01.01", "T14.1"],
    icdPrefixes: ["S01", "S41", "S51", "S61", "S71", "S81", "S91", "T14"],
    excludeIcdPrefixes: ["L03", "L08"],
    keywords: ["laceration", "wound", "cut", "abrasion", "plaie", "suture"],
    specialtyCategory: "wound_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Traumatic wound care; excludes soft-tissue infection family prefixes.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "dizziness_vertigo",
    label: "Dizziness / Vertigo",
    templateId: "vertigo_dizziness_v1",
    additionalTemplateIds: ["high_risk_medical_dizziness_v1"],
    clinicalDomain: "Neurologic",
    icdExact: ["R42"],
    icdPrefixes: ["H81"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["dizziness", "vertigo", "lightheaded"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Peripheral or undifferentiated dizziness discharge instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dizziness and vertigo"],
  },
  {
    id: "syncope",
    label: "Syncope",
    templateId: "syncope_v1",
    additionalTemplateIds: ["cardio_syncope_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R55"],
    excludeIcdPrefixes: ["R53"],
    keywords: ["syncope", "fainting", "passed out"],
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Transient loss of consciousness outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fainting"],
  },
  {
    id: "seizure",
    label: "Seizure",
    templateId: "seizure_v1",
    additionalTemplateIds: ["pediatric_febrile_seizure_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["G40", "R56"],
    keywords: ["seizure", "convulsion", "epilepsy"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "neurology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Post-seizure return precautions and neurology follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Seizures"],
  },
  {
    id: "behavioral_health_crisis",
    label: "Behavioral Health Crisis",
    templateId: "behavioral_health_suicidal_ideation_precautions_v1",
    additionalTemplateIds: [
      "behavioral_health_anxiety_panic_symptoms_v1",
      "behavioral_health_depression_crisis_precautions_v1",
      "behavioral_health_crisis_follow_up_v1",
      "behavioral_health_alcohol_intoxication_follow_up_v1",
      "behavioral_health_alcohol_withdrawal_precautions_v1",
      "behavioral_health_substance_use_resources_v1",
      "behavioral_health_opioid_overdose_aftercare_v1",
      "behavioral_health_insomnia_stress_reaction_v1",
      "behavioral_health_grief_adjustment_v1",
      "anxiety_panic_v1",
      "alcohol_intoxication_v1",
    ],
    clinicalDomain: "Behavioral Health",
    icdExact: ["R45.851", "F41.0", "F41.9", "F32.9", "F10.239", "T40.2X5A"],
    icdPrefixes: ["F32"],
    keywords: [
      "bh suicidal ideation",
      "suicidal ideation",
      "bh depression crisis",
      "behavioral health crisis",
      "bh alcohol withdrawal",
      "bh opioid overdose",
      "behavioral health crisis follow-up",
    ],
    icdExactTemplateOverrides: {
      "F41.0": "behavioral_health_anxiety_panic_symptoms_v1",
      "F41.9": "behavioral_health_anxiety_panic_symptoms_v1",
      "F32.9": "behavioral_health_depression_crisis_precautions_v1",
      "R45.851": "behavioral_health_suicidal_ideation_precautions_v1",
      "F10.239": "behavioral_health_alcohol_withdrawal_precautions_v1",
      "T40.2X5A": "behavioral_health_opioid_overdose_aftercare_v1",
    },
    guardrails: {
      safety: {
        requiresCrisisReturnPrecautions: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale:
      "Crisis safety planning with exact-code overrides; withdrawal and opioid aftercare separated from intoxication routing.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide", "MedlinePlus — Depression"],
  },
  {
    id: "obgyn_bleeding_pelvic_pain",
    label: "OB/GYN Bleeding / Pelvic Pain",
    templateId: "obgyn_vaginal_bleeding_v1",
    additionalTemplateIds: [
      "obgyn_pelvic_pain_v1",
      "obgyn_dysmenorrhea_v1",
      "obgyn_hyperemesis_v1",
      "obgyn_early_pregnancy_symptoms_v1",
      "obgyn_threatened_miscarriage_precautions_v1",
      "obgyn_vaginitis_v1",
      "obgyn_round_ligament_pain_v1",
      "obgyn_postpartum_warning_v1",
    ],
    clinicalDomain: "OB/GYN",
    icdExact: ["N93.9", "R10.2", "N94.6", "O21.9"],
    icdPrefixes: ["N93", "O20", "O21", "O26", "O90", "N76"],
    icdExactTemplateOverrides: {
      "R10.2": "obgyn_pelvic_pain_v1",
      "N94.6": "obgyn_dysmenorrhea_v1",
      "O21.9": "obgyn_hyperemesis_v1",
      "O20.9": "obgyn_early_pregnancy_symptoms_v1",
      "O20.0": "obgyn_threatened_miscarriage_precautions_v1",
      "N76.0": "obgyn_vaginitis_v1",
      "O26.89": "obgyn_round_ligament_pain_v1",
      "O90.89": "obgyn_postpartum_warning_v1",
      "Z39.9": "obgyn_postpartum_warning_v1",
    },
    keywords: ["obgyn vaginal bleeding", "obgyn pelvic pain", "gynecologic bleeding"],
    guardrails: {
      sex: { sex: "female" },
      safety: { requiresEdReturnPrecautions: true, requiresSpecialistFollowUp: true },
    },
    specialtyCategory: "obgyn",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Gynecologic bleeding and pelvic pain with female sex guardrail and pregnancy-sensitive template overrides.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Vaginal bleeding", "MedlinePlus — Pelvic pain"],
  },
] as const;
