/**
 * Phase 1 clinical condition families (21) — migrated with domain + routing status fields.
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";
import {
  FOREIGN_BODY_FOOT_TOE_ICD_PREFIXES,
  FOREIGN_BODY_HAND_FINGER_ICD_PREFIXES,
  FOREIGN_BODY_SKIN_SOFT_TISSUE_OPEN_ICD_PREFIXES,
  FOREIGN_BODY_SKIN_SOFT_TISSUE_SUPERFICIAL_ICD_PREFIXES,
} from "./icd10ForeignBodyRoutingPrefixes";

export const PHASE1_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] = [
  {
    id: "nausea_vomiting",
    label: "Nausea / Vomiting",
    templateId: "nausea_vomiting_v1",
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R11.0", "R11.1", "R11.2", "R11.10"],
    icdPrefixes: ["R11"],
    excludeIcdExact: ["E86.0"],
    keywords: ["nausea", "vomiting", "emesis"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shared ED discharge guidance for nausea with or without vomiting.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Nausea and vomiting"],
  },
  {
    id: "cellulitis_skin_infection",
    label: "Cellulitis / Skin Infection",
    templateId: "cellulitis_v1",
    additionalTemplateIds: ["infectious_cellulitis_followup_v1"],
    clinicalDomain: "Skin/Infection",
    icdExact: ["L08.9", "L03.90", "L03.115", "L03.116"],
    icdPrefixes: ["L03", "L08"],
    excludeIcdPrefixes: ["L08.0", "L02"],
    keywords: ["cellulitis", "skin infection"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Soft-tissue infection discharge instructions; distinct from wound/laceration trauma care.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Cellulitis"],
  },
  {
    id: "uri_cough",
    label: "URI / Cough",
    templateId: "uri_cough_v1",
    additionalTemplateIds: ["infectious_upper_respiratory_infection_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["J00", "J06.9"],
    icdPrefixes: ["J06", "R05"],
    keywords: ["upper respiratory infection", "uri", "cough", "common cold", "rhinopharyngitis"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Age-neutral URI/cough template; pediatric URI uses separate guarded family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "pediatric_uri",
    label: "Pediatric URI",
    templateId: "pediatric_uri_v1",
    clinicalDomain: "Respiratory",
    keywords: ["pediatric uri", "pediatric upper respiratory", "child cold", "rhume enfant"],
    guardrails: { age: { maxAgeYears: 18 } },
    specialtyCategory: "pediatrics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Pediatric-only URI wording; requires pediatric age context or explicit pediatric keyword.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "chest_pain",
    label: "Chest Pain",
    templateId: "chest_pain_v1",
    additionalTemplateIds: ["cardio_chest_pain_low_risk_v1", "chest_wall_pain_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R07.9"],
    icdPrefixes: ["R07"],
    keywords: ["chest pain", "chest discomfort", "douleur thoracique"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Cardiac-safe return precautions for undifferentiated chest pain discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Chest pain"],
  },
  {
    id: "abdominal_pain",
    label: "Abdominal Pain",
    templateId: "abdominal_pain_v1",
    additionalTemplateIds: ["pediatric_abdominal_pain_v1"],
    clinicalDomain: "Gastrointestinal",
    icdPrefixes: ["R10"],
    excludeIcdExact: ["R10.2"],
    keywords: ["abdominal pain", "belly pain", "douleur abdominale"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "General abdominal pain; pelvic pain routed to OB/GYN family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Abdominal pain"],
  },
  {
    id: "headache",
    label: "Headache",
    templateId: "headache_v1",
    additionalTemplateIds: ["high_risk_medical_headache_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["R51", "G44"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["headache", "migraine", "cephalalgia", "céphalée"],
    specialtyCategory: "neurology",
    riskCategory: "moderate",
    clinicalRationale: "Primary headache discharge; excludes stroke/TIA red-flag templates.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Headache"],
  },
  {
    id: "uti_urinary_symptoms",
    label: "UTI / Urinary Symptoms",
    templateId: "uti_v1",
    additionalTemplateIds: ["urology_uti_followup_v1", "obgyn_uti_pregnancy_precautions_v1"],
    clinicalDomain: "Genitourinary",
    icdExact: ["N39.0"],
    icdPrefixes: ["R30", "N39"],
    keywords: ["urinary tract infection", "uti", "dysuria", "burning urination"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Uncomplicated urinary symptoms and UTI outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Urinary tract infections"],
  },
  {
    id: "gastroenteritis_diarrhea",
    label: "Gastroenteritis / Diarrhea",
    templateId: "gastroenteritis_v1",
    additionalTemplateIds: [
      "gi_infectious_gastroenteritis_v1",
      "pediatric_gastroenteritis_v1",
    ],
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R19.7", "A09", "K59.1"],
    icdPrefixes: ["R19", "A08"],
    keywords: ["diarrhea", "gastroenteritis", "loose stool"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Acute diarrheal illness; distinct from constipation family (K59.0*).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Gastroenteritis"],
  },
  {
    id: "back_pain",
    label: "Back Pain",
    templateId: "back_pain_v1",
    additionalTemplateIds: ["trauma_msk_back_strain_v1"],
    clinicalDomain: "Musculoskeletal",
    icdPrefixes: ["M54"],
    keywords: ["back pain", "low back pain", "sciatica"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Musculoskeletal back pain without acute neuro deficit documentation.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back pain"],
  },
  {
    id: "asthma_wheezing",
    label: "Asthma / Wheezing",
    templateId: "asthma_exacerbation_v1",
    additionalTemplateIds: ["pediatric_asthma_exacerbation_v1", "pediatric_wheezing_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["R06.2"],
    icdPrefixes: ["J45"],
    icdExactTemplateOverrides: {
      "R06.2": "pediatric_wheezing_v1",
    },
    keywords: ["asthma", "wheezing", "asthma exacerbation"],
    specialtyCategory: "pulmonology",
    riskCategory: "moderate",
    clinicalRationale: "Reactive airway disease discharge with inhaler safety language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Asthma"],
  },
  {
    id: "pneumonia_lower_respiratory",
    label: "Pneumonia / Lower Respiratory Infection",
    templateId: "pneumonia_v1",
    additionalTemplateIds: ["infectious_pneumonia_followup_v1"],
    clinicalDomain: "Respiratory",
    icdPrefixes: ["J18", "J15", "J16", "J17"],
    keywords: ["pneumonia"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Lower respiratory infection requiring outpatient reassessment.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Pneumonia"],
  },
  {
    id: "hypertension_elevated_bp",
    label: "Hypertension / Elevated BP",
    templateId: "hypertension_v1",
    additionalTemplateIds: ["cardio_hypertension_elevated_bp_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["I10", "R03.0"],
    icdPrefixes: ["I10"],
    keywords: ["hypertension", "elevated blood pressure", "high blood pressure"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Blood pressure chief complaint or known HTN management at discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood pressure"],
  },
  {
    id: "diabetes_hyperglycemia",
    label: "Diabetes / Hyperglycemia (acute)",
    templateId: "hyperglycemia_v1",
    clinicalDomain: "Endocrine",
    icdExact: ["E11.65"],
    icdPrefixes: ["R73"],
    excludeIcdExact: ["E11.9"],
    keywords: ["hyperglycemia", "high blood sugar"],
    specialtyCategory: "endocrinology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Acute hyperglycemia symptoms — not stable type 2 outpatient management.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood sugar"],
  },
  {
    id: "type_2_diabetes_non_acute",
    label: "Type 2 Diabetes (non-acute)",
    templateId: "type_2_diabetes_v1",
    additionalTemplateIds: ["diabetes_sick_day_precautions_v1"],
    clinicalDomain: "Endocrine",
    icdExact: ["E11.9"],
    icdPrefixes: ["E11"],
    excludeIcdExact: ["E11.65"],
    keywords: ["type 2 diabetes", "diabetes type 2", "diabète de type 2"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Stable type 2 diabetes outpatient instructions without implying acute hyperglycemia crisis.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Diabetes type 2"],
  },
  {
    id: "trauma_wound_laceration",
    label: "Trauma / Wound / Laceration",
    templateId: "wound_laceration_v1",
    clinicalDomain: "Trauma",
    icdExact: ["S01.01", "T14.1"],
    icdPrefixes: ["S01", "S41", "S51", "S61", "S71", "S81", "S91", "T14"],
    excludeIcdPrefixes: [
      "L03",
      "L08",
      "W54",
      "W55",
      "W50.3",
      "S01.05",
      "S01.15",
      "S01.25",
      "S01.35",
      "S01.45",
      "S01.55",
      "S11.95",
      "S41.15",
      "S51.85",
      "S61.45",
      "S71.15",
      "S81.85",
      "S91.15",
      "S67",
      "S68",
      "S48",
      "S58",
      "S78",
      "S88",
      "S98",
      "S47",
      "S57",
      "S77",
      "S87",
      "S97",
      "S28",
      "S38",
      "S07",
      "T15",
      "T16",
      "T17",
      "T18",
      "T19",
      "T79.6",
      "S61.4",
      "S17",
      "S08.1",
      "S08.8",
    ],
    keywords: ["laceration", "wound", "cut", "abrasion", "plaie", "suture"],
    specialtyCategory: "wound_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Traumatic wound care; excludes soft-tissue infection and animal-bite open-bite families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_animal_bite",
    label: "Trauma / Animal Bite",
    templateId: "animal_bite_v1",
    clinicalDomain: "Trauma",
    icdExact: [
      "W54.0XXA",
      "W55.01XA",
      "W55.03XA",
      "W55.81XA",
      "S61.459A",
      "S01.05XA",
    ],
    icdPrefixes: [
      "W54",
      "W55",
      "S01.05",
      "S01.15",
      "S01.25",
      "S01.35",
      "S01.45",
      "S01.55",
      "S11.95",
      "S41.15",
      "S51.85",
      "S61.45",
      "S71.15",
      "S81.85",
      "S91.15",
    ],
    keywords: [
      "animal bite",
      "dog bite",
      "cat bite",
      "mammal bite",
      "bite wound",
      "open bite",
      "bitten by dog",
      "bitten by cat",
      "morsure animale",
      "morsure de chien",
      "morsure de chat",
      "plaie par morsure",
    ],
    specialtyCategory: "wound_care",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Animal bite wound care with infection, tetanus, and rabies-focused discharge instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Animal bites"],
  },
  {
    id: "trauma_human_bite",
    label: "Trauma / Human Bite",
    templateId: "human_bite_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["W50.3", "Y04.1"],
    keywords: ["human bite", "morsure humaine"],
    specialtyCategory: "wound_care",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Human-bite wound care with infection, tetanus, and hand/joint follow-up precautions; no animal-exposure pathway.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_fight_bite", label: "Trauma / Fight Bite", templateId: "fight_bite_v1", clinicalDomain: "Trauma",
    keywords: ["fight bite", "clenched fist", "knuckle bite", "morsure du poing"], specialtyCategory: "hand_surgery", riskCategory: "high",
    clinicalRationale: "Clenched-fist wound with hand and joint infection precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_high_risk_hand_wound", label: "Trauma / High-Risk Hand Wound", templateId: "high_risk_hand_wound_v1", clinicalDomain: "Trauma",
    keywords: ["high risk hand wound", "hand bite"], specialtyCategory: "hand_surgery", riskCategory: "high",
    clinicalRationale: "Keyword-only high-risk hand wound instructions; anatomic open-bite codes remain delegated to animal bite.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Hand injuries"],
  },
  {
    id: "trauma_contaminated_wound", label: "Trauma / Contaminated Wound", templateId: "contaminated_wound_v1", clinicalDomain: "Trauma",
    keywords: ["contaminated wound", "dirty wound", "plaie contaminée", "plaie sale"], specialtyCategory: "wound_care", riskCategory: "moderate_to_high",
    clinicalRationale: "Contaminated wound instructions with infection and tetanus precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_water_exposed_wound", label: "Trauma / Water-Exposed Wound", templateId: "water_exposed_wound_v1", clinicalDomain: "Trauma",
    keywords: ["freshwater", "saltwater", "lake", "river", "ocean", "aquarium"], specialtyCategory: "wound_care", riskCategory: "moderate_to_high",
    clinicalRationale: "Water-exposed wound instructions with infection and follow-up precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_delayed_wound", label: "Trauma / Delayed Wound", templateId: "delayed_wound_v1", clinicalDomain: "Trauma",
    keywords: ["delayed wound", "delayed presentation wound"], specialtyCategory: "wound_care", riskCategory: "moderate",
    clinicalRationale: "Delayed wound presentation instructions with infection reassessment precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_deep_contaminated_wound", label: "Trauma / Deep Contaminated Wound", templateId: "deep_contaminated_wound_v1", clinicalDomain: "Trauma",
    keywords: ["deep contaminated", "sewage", "farm contamination"], specialtyCategory: "wound_care", riskCategory: "high",
    clinicalRationale: "Deep or unusually contaminated wound instructions with urgent infection precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "dizziness_vertigo",
    label: "Dizziness / Vertigo",
    templateId: "vertigo_dizziness_v1",
    additionalTemplateIds: ["high_risk_medical_dizziness_v1"],
    clinicalDomain: "Neurologic",
    icdExact: ["R42"],
    icdPrefixes: ["H81"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["dizziness", "vertigo", "lightheaded"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Peripheral or undifferentiated dizziness discharge instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dizziness and vertigo"],
  },
  {
    id: "syncope",
    label: "Syncope",
    templateId: "syncope_v1",
    additionalTemplateIds: ["cardio_syncope_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R55"],
    excludeIcdPrefixes: ["R53"],
    keywords: ["syncope", "fainting", "passed out"],
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Transient loss of consciousness outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fainting"],
  },
  {
    id: "seizure",
    label: "Seizure",
    templateId: "seizure_v1",
    additionalTemplateIds: ["pediatric_febrile_seizure_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["G40", "R56"],
    keywords: ["seizure", "convulsion", "epilepsy"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "neurology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Post-seizure return precautions and neurology follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Seizures"],
  },
  {
    id: "behavioral_health_crisis",
    label: "Behavioral Health Crisis",
    templateId: "behavioral_health_suicidal_ideation_precautions_v1",
    additionalTemplateIds: [
      "behavioral_health_anxiety_panic_symptoms_v1",
      "behavioral_health_depression_crisis_precautions_v1",
      "behavioral_health_crisis_follow_up_v1",
      "behavioral_health_alcohol_intoxication_follow_up_v1",
      "behavioral_health_alcohol_withdrawal_precautions_v1",
      "behavioral_health_substance_use_resources_v1",
      "behavioral_health_opioid_overdose_aftercare_v1",
      "behavioral_health_insomnia_stress_reaction_v1",
      "behavioral_health_grief_adjustment_v1",
      "anxiety_panic_v1",
      "alcohol_intoxication_v1",
    ],
    clinicalDomain: "Behavioral Health",
    icdExact: ["R45.851", "F41.0", "F41.9", "F32.9", "F10.239", "T40.2X5A"],
    icdPrefixes: ["F32"],
    keywords: [
      "bh suicidal ideation",
      "suicidal ideation",
      "bh depression crisis",
      "behavioral health crisis",
      "bh alcohol withdrawal",
      "bh opioid overdose",
      "behavioral health crisis follow-up",
    ],
    icdExactTemplateOverrides: {
      "F41.0": "behavioral_health_anxiety_panic_symptoms_v1",
      "F41.9": "behavioral_health_anxiety_panic_symptoms_v1",
      "F32.9": "behavioral_health_depression_crisis_precautions_v1",
      "R45.851": "behavioral_health_suicidal_ideation_precautions_v1",
      "F10.239": "behavioral_health_alcohol_withdrawal_precautions_v1",
      "T40.2X5A": "behavioral_health_opioid_overdose_aftercare_v1",
    },
    guardrails: {
      safety: {
        requiresCrisisReturnPrecautions: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale:
      "Crisis safety planning with exact-code overrides; withdrawal and opioid aftercare separated from intoxication routing.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide", "MedlinePlus — Depression"],
  },
  {
    id: "obgyn_bleeding_pelvic_pain",
    label: "OB/GYN Bleeding / Pelvic Pain",
    templateId: "obgyn_vaginal_bleeding_v1",
    additionalTemplateIds: [
      "obgyn_pelvic_pain_v1",
      "obgyn_dysmenorrhea_v1",
      "obgyn_hyperemesis_v1",
      "obgyn_early_pregnancy_symptoms_v1",
      "obgyn_threatened_miscarriage_precautions_v1",
      "obgyn_vaginitis_v1",
      "obgyn_round_ligament_pain_v1",
      "obgyn_postpartum_warning_v1",
    ],
    clinicalDomain: "OB/GYN",
    icdExact: ["N93.9", "R10.2", "N94.6", "O21.9"],
    icdPrefixes: ["N93", "O20", "O21", "O26", "O90", "N76"],
    icdExactTemplateOverrides: {
      "R10.2": "obgyn_pelvic_pain_v1",
      "N94.6": "obgyn_dysmenorrhea_v1",
      "O21.9": "obgyn_hyperemesis_v1",
      "O20.9": "obgyn_early_pregnancy_symptoms_v1",
      "O20.0": "obgyn_threatened_miscarriage_precautions_v1",
      "N76.0": "obgyn_vaginitis_v1",
      "O26.89": "obgyn_round_ligament_pain_v1",
      "O90.89": "obgyn_postpartum_warning_v1",
      "Z39.9": "obgyn_postpartum_warning_v1",
    },
    keywords: ["obgyn vaginal bleeding", "obgyn pelvic pain", "gynecologic bleeding"],
    guardrails: {
      sex: { sex: "female" },
      safety: { requiresEdReturnPrecautions: true, requiresSpecialistFollowUp: true },
    },
    specialtyCategory: "obgyn",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Gynecologic bleeding and pelvic pain with female sex guardrail and pregnancy-sensitive template overrides.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Vaginal bleeding", "MedlinePlus — Pelvic pain"],
  },
  {
    id: "trauma_fracture_upper_extremity",
    label: "Fracture — Upper Extremity",
    templateId: "trauma_msk_minor_fracture_precautions_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S42", "S52"],
    keywords: ["broken arm", "broken wrist", "broken collarbone", "broken shoulder", "fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Closed shoulder-girdle, humerus, and forearm/wrist fractures managed with splinting and outpatient orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Fractures"],
  },
  {
    id: "trauma_fracture_lower_extremity",
    label: "Fracture — Lower Extremity",
    templateId: "trauma_msk_minor_fracture_precautions_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S72", "S82", "S92", "M84", "S32.1", "S32.2", "S32.3", "S32.4", "S32.5", "S32.6", "S32.8", "S32.9"],
    excludeIcdPrefixes: ["S72.0", "S72.1", "S72.2"],
    keywords: [
      "broken leg",
      "broken ankle",
      "broken foot",
      "broken toe",
      "stress fracture",
      "pathologic fracture",
      "pelvic fracture",
      "pelvis fracture",
      "broken pelvis",
    ],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Closed femoral shaft, tibia/fibula, ankle, and foot fractures (excluding proximal-femur hip fractures) managed with splinting/casting and outpatient orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Fractures"],
  },
  {
    id: "trauma_fracture_hip",
    label: "Fracture — Hip",
    templateId: "trauma_msk_fracture_hip_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S72.0", "S72.1", "S72.2"],
    keywords: ["hip fracture", "broken hip", "fractured hip", "femoral neck fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Proximal femur (femoral neck, trochanteric, subtrochanteric) fractures usually require orthopedic surgery and often hospital admission.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hip fractures", "OrthoInfo — Hip fractures"],
  },
  {
    id: "trauma_fracture_hand",
    label: "Fracture — Hand / Finger / Wrist Bones",
    templateId: "trauma_msk_fracture_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S62"],
    keywords: ["hand fracture", "finger fracture", "broken finger", "metacarpal fracture", "phalanx fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Hand, finger, and carpal (wrist-bone) fractures with splinting, elevation, and hand surgery or orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hand injuries and disorders", "OrthoInfo — Hand fractures"],
  },
  {
    id: "trauma_fracture_facial",
    label: "Fracture — Facial / Nasal / Orbital / Mandible",
    templateId: "trauma_msk_fracture_facial_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S02"],
    keywords: ["facial fracture", "broken jaw", "broken nose", "orbital fracture", "mandible fracture"],
    specialtyCategory: "ent",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Facial, nasal, orbital, and mandible fractures with vision/malocclusion escalation language and ENT or maxillofacial follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Facial injuries and disorders"],
  },
  {
    id: "trauma_fracture_spinal",
    label: "Fracture — Spinal (Vertebral)",
    templateId: "trauma_msk_fracture_spine_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S12", "S22.0", "S22.1", "S32.0"],
    keywords: ["spinal fracture", "vertebral fracture", "compression fracture spine", "cervical spine fracture", "lumbar spine fracture"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Cervical, thoracic, and lumbar vertebral fractures with head/neck/spine escalation language and neurosurgery/spine surgery advisory follow-up when cord or nerve root signs are present. Pelvic ring codes remain on the lower-extremity fracture family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back injuries", "OrthoInfo — Spinal fractures"],
  },
  {
    id: "trauma_fracture_open",
    label: "Fracture — Open (Compound)",
    templateId: "trauma_msk_fracture_open_v1",
    clinicalDomain: "Trauma",
    icdExact: ["S82.201B", "S52.531B", "S72.001B"],
    keywords: ["open fracture", "compound fracture", "open bone fracture"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Open fractures with skin breakdown typically require surgical debridement and IV antibiotics; differentiated from closed fractures by exact 7th-character codes rather than a shared ICD prefix.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Open fractures"],
  },
  {
    id: "trauma_fracture_rib",
    label: "Fracture — Rib",
    templateId: "trauma_msk_rib_injury_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S22.3", "S22.4", "S22.5"],
    keywords: ["rib fracture", "broken rib", "multiple rib fractures", "flail chest"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Single, multiple, and flail-chest rib fractures share the existing rib/chest-wall injury discharge template with pulmonary escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Rib injuries"],
  },
  {
    id: "trauma_dislocation_shoulder",
    label: "Dislocation — Shoulder / AC / SC",
    templateId: "trauma_msk_dislocation_shoulder_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S43.0", "S43.1", "S43.2"],
    keywords: ["shoulder dislocation", "dislocated shoulder", "ac separation", "acromioclavicular"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Shoulder girdle dislocations and AC/SC injuries with immobilization and orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Shoulder injuries", "OrthoInfo — Shoulder dislocation"],
  },
  {
    id: "trauma_dislocation_elbow",
    label: "Dislocation — Elbow / Nursemaid",
    templateId: "trauma_msk_dislocation_elbow_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S53.0", "S53.1"],
    keywords: ["elbow dislocation", "nursemaid elbow", "pulled elbow", "radial head subluxation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Elbow dislocation and pediatric nursemaid elbow with reduction and neurovascular precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Elbow injuries", "OrthoInfo — Nursemaid's elbow"],
  },
  {
    id: "trauma_dislocation_hip",
    label: "Dislocation — Hip",
    templateId: "trauma_msk_dislocation_hip_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S73.0"],
    keywords: ["hip dislocation", "dislocated hip"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale: "Hip dislocation typically requires urgent reduction and orthopedic management.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hip injuries", "OrthoInfo — Hip dislocation"],
  },
  {
    id: "trauma_dislocation_patella",
    label: "Dislocation — Patella / Knee",
    templateId: "trauma_msk_dislocation_patella_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S83.0", "S83.1"],
    keywords: ["patella dislocation", "dislocated kneecap", "knee dislocation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Patellar and tibiofemoral dislocations with immobilization and orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Kneecap dislocation", "OrthoInfo — Patellar dislocation"],
  },
  {
    id: "trauma_dislocation_hand",
    label: "Dislocation — Hand / Finger / Wrist",
    templateId: "trauma_msk_dislocation_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.0", "S63.1", "S63.2"],
    keywords: ["finger dislocation", "thumb dislocation", "wrist dislocation", "dislocated finger"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Hand, finger, thumb, and wrist dislocations with splinting and hand surgery or orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Finger injuries", "OrthoInfo — Finger dislocation"],
  },
  {
    id: "trauma_dislocation_jaw",
    label: "Dislocation — Jaw / TMJ",
    templateId: "trauma_msk_dislocation_jaw_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S03.0"],
    keywords: ["jaw dislocation", "tmj dislocation", "dislocated jaw"],
    specialtyCategory: "ent",
    riskCategory: "moderate",
    clinicalRationale: "TMJ/jaw dislocation with soft-diet guidance and maxillofacial or ENT follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Jaw injuries"],
  },
  {
    id: "trauma_dislocation_generic",
    label: "Dislocation — Other Extremity",
    templateId: "trauma_msk_dislocation_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S93.0", "S93.1", "S93.3"],
    keywords: ["ankle dislocation", "foot dislocation", "toe dislocation", "dislocation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Other extremity dislocations not covered by joint-specific families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dislocations"],
  },
  {
    id: "trauma_sprain_ankle",
    label: "Sprain — Ankle",
    templateId: "trauma_msk_ankle_sprain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S93.4"],
    keywords: ["ankle sprain", "twisted ankle", "entorse cheville"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Ankle sprain with RICE, bracing, and orthopedic follow-up as needed.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Ankle injuries and sprains", "OrthoInfo — Ankle sprain"],
  },
  {
    id: "trauma_sprain_wrist",
    label: "Sprain — Wrist",
    templateId: "trauma_msk_wrist_sprain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.5"],
    keywords: ["wrist sprain", "entorse poignet"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Wrist sprain with immobilization and orthopedic follow-up as needed.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wrist injuries", "OrthoInfo — Wrist sprains"],
  },
  {
    id: "trauma_sprain_knee",
    label: "Sprain — Knee",
    templateId: "trauma_msk_knee_injury_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S83.2", "S83.3", "S83.6", "S83.9"],
    keywords: ["knee sprain", "entorse genou"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Generic knee sprain excluding dedicated ACL/PCL/MCL/LCL ligament families and patellar dislocation.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Knee injuries", "OrthoInfo — Knee sprains"],
  },
  {
    id: "trauma_sprain_shoulder",
    label: "Sprain / Strain — Shoulder",
    templateId: "trauma_msk_shoulder_pain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S43.4", "S43.5"],
    keywords: ["shoulder sprain", "shoulder strain", "entorse épaule"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shoulder sprain/strain excluding dedicated rotator-cuff tendon and dislocation families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Shoulder injuries", "OrthoInfo — Shoulder pain"],
  },
  {
    id: "trauma_strain_neck",
    label: "Strain — Neck / Cervical",
    templateId: "trauma_msk_neck_strain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S13.4", "S16"],
    keywords: ["neck strain", "cervical strain", "whiplash", "entorse cervicale"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Neck strain with head/neck/spine escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Neck injuries"],
  },
  {
    id: "trauma_strain_back",
    label: "Strain — Back / Lumbar",
    templateId: "trauma_msk_back_strain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S39.01"],
    icdExact: ["S39.012A", "S39.012"],
    keywords: ["back strain", "lumbar strain", "entorse lombaire", "entorse dos"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Back/lumbar strain with spine escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back pain"],
  },
  {
    id: "trauma_sprain_generic",
    label: "Sprain / Strain — Other Sites",
    templateId: "trauma_msk_sprain_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S53.3", "S63.4", "S73.1", "S93.5", "S93.6", "S23.3", "S29"],
    keywords: ["sprain", "strain", "hamstring strain", "groin strain", "entorse", "élongation", "claquage"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Other sprain/strain sites not covered by ankle/wrist/knee/shoulder/neck/back or dedicated tendon/ligament families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sprains and strains"],
  },
  {
    id: "trauma_tendon_achilles",
    label: "Tendon — Achilles",
    templateId: "trauma_msk_tendon_achilles_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S86.0"],
    keywords: ["achilles", "achille", "tendon d'achille"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Achilles tendon injury/rupture with immobilization and orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Achilles tendon rupture", "MedlinePlus — Achilles tendon"],
  },
  {
    id: "trauma_tendon_extensor_mechanism",
    label: "Tendon — Extensor Mechanism",
    templateId: "trauma_msk_tendon_extensor_mechanism_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S76.1"],
    keywords: ["quadriceps tendon", "patellar tendon", "tendon rotulien"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Quadriceps/patellar tendon injury with immobilization and urgent orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Quadriceps tendon rupture"],
  },
  {
    id: "trauma_tendon_shoulder",
    label: "Tendon — Shoulder",
    templateId: "trauma_msk_tendon_shoulder_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S46.0", "S46.1", "S46.2", "S46.3", "M75.1"],
    keywords: ["rotator cuff", "biceps tendon", "triceps tendon", "coiffe des rotateurs"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Shoulder tendon injury including rotator cuff and biceps/triceps tendon.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Rotator cuff tears", "MedlinePlus — Shoulder injuries"],
  },
  {
    id: "trauma_tendon_hand",
    label: "Tendon — Hand / Finger",
    templateId: "trauma_msk_tendon_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S66.1", "S66.2", "S66.3", "S66.5", "M66.2", "M66.3"],
    keywords: ["flexor tendon", "extensor tendon", "mallet finger", "tendon extenseur", "tendon fléchisseur"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Hand/finger flexor or extensor tendon injury with splint protocol and hand-surgery follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Flexor tendon injuries", "OrthoInfo — Mallet finger"],
  },
  {
    id: "trauma_tendon_generic",
    label: "Tendon — Other Sites",
    templateId: "trauma_msk_tendon_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S76.0", "S76.2", "S76.3", "S86.3", "S86.8", "S56", "S96"],
    keywords: ["tendon injury", "tendon rupture", "hamstring tendon", "lésion tendineuse"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Other tendon injuries not covered by Achilles/shoulder/hand/extensor-mechanism families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Tendon injuries"],
  },
  {
    id: "trauma_ligament_knee",
    label: "Ligament — Knee",
    templateId: "trauma_msk_ligament_knee_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S83.41", "S83.42", "S83.51", "S83.52", "S83.4", "S83.5"],
    keywords: ["acl", "pcl", "mcl", "lcl", "knee ligament", "lca", "croisé"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Knee ligament tear/sprain with bracing and orthopedic/sports-medicine follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — ACL injury", "MedlinePlus — Knee injuries"],
  },
  {
    id: "trauma_ligament_ankle",
    label: "Ligament — Ankle / Syndesmosis",
    templateId: "trauma_msk_ligament_ankle_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S93.41", "S93.42", "S93.43"],
    keywords: ["syndesmosis", "high ankle", "deltoid ligament", "ankle ligament", "entorse haute"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Ankle ligament and syndesmotic injuries with protected weight-bearing guidance.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — High ankle sprain", "MedlinePlus — Ankle injuries"],
  },
  {
    id: "trauma_ligament_hand",
    label: "Ligament — Hand / Thumb UCL",
    templateId: "trauma_msk_ligament_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.64", "S63.61", "S63.62", "S63.3"],
    keywords: ["thumb ucl", "skier", "gamekeeper", "finger collateral", "pouce du skieur"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Thumb UCL and finger collateral ligament injuries with hand-surgery follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Thumb sprains"],
  },
  {
    id: "trauma_ligament_upper_extremity",
    label: "Ligament — Wrist / Elbow",
    templateId: "trauma_msk_ligament_upper_extremity_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.51", "S53.4"],
    keywords: ["scapholunate", "wrist ligament", "elbow collateral"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Wrist and elbow ligament injuries; longer prefixes beat generic wrist sprain.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Wrist sprains"],
  },
  {
    id: "trauma_ligament_shoulder",
    label: "Ligament — Shoulder / AC",
    templateId: "trauma_msk_ligament_shoulder_v1",
    clinicalDomain: "Trauma",
    keywords: ["ac ligament", "acromioclavicular ligament", "shoulder ligament", "ligament acromio-claviculaire"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shoulder/AC ligament injury via keyword routing; ICD S43.4 remains on shoulder sprain family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Shoulder separation"],
  },
  {
    id: "trauma_ligament_generic",
    label: "Ligament — Other Sites",
    templateId: "trauma_msk_ligament_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S13.1", "S33.4", "S33.5"],
    keywords: ["ligament tear", "ligament injury", "lésion ligamentaire", "déchirure ligamentaire"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Other ligament injuries including cervical/pelvic/lumbar ligament sprain codes.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sprains and strains"],
  },
  {
    id: "trauma_crush_hand_finger",
    label: "Crush — Hand / Finger",
    templateId: "trauma_msk_crush_hand_finger_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S67.1", "S67.2", "S67"],
    keywords: ["crush injury hand", "crushed hand", "crushed finger", "écrasement main", "écrasement doigt"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Hand/finger crush injury with wound care, elevation, and compartment precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_crush_upper_extremity",
    label: "Crush — Upper Extremity",
    templateId: "trauma_msk_crush_upper_extremity_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S47", "S57"],
    keywords: ["crush injury arm", "crushing injury forearm", "écrasement bras"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Upper-extremity crush injury with neurovascular and compartment monitoring guidance.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_crush_lower_extremity",
    label: "Crush — Lower Extremity",
    templateId: "trauma_msk_crush_lower_extremity_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S77", "S87"],
    keywords: ["crush injury leg", "crushed thigh", "écrasement jambe"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Lower-extremity crush injury with weight-bearing and compartment precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_crush_foot_toe",
    label: "Crush — Foot / Toe",
    templateId: "trauma_msk_crush_foot_toe_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S97"],
    keywords: ["crush injury foot", "crushed foot", "crushed toe", "écrasement pied"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Foot/toe crush injury with elevation and specialty follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_crush_chest_abdomen_pelvis",
    label: "Crush — Chest / Abdomen / Pelvis",
    templateId: "trauma_msk_crush_chest_abdomen_pelvis_v1",
    clinicalDomain: "Trauma",
    /** Crush-only torso prefixes — excludes traumatic amputation under S28.1/S28.2/S38.2. */
    icdPrefixes: ["S28.0", "S38.00", "S38.01", "S38.02", "S38.03", "S38.1"],
    keywords: ["crushed chest", "crush abdomen", "crush pelvis", "écrasement thorax"],
    specialtyCategory: "trauma_surgery",
    riskCategory: "high",
    clinicalRationale: "Torso crush injury — discharge-only language avoided when admission/transfer indicated.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_crush_prolonged_compression",
    label: "Crush — Prolonged Compression",
    templateId: "trauma_msk_crush_prolonged_compression_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T79.6"],
    keywords: ["prolonged compression", "crush syndrome", "traumatic ischemia", "compression prolongée"],
    specialtyCategory: "trauma_surgery",
    riskCategory: "high",
    clinicalRationale: "Prolonged compression / traumatic ischemia with rhabdomyolysis precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Rhabdomyolysis"],
  },
  {
    id: "trauma_crush_degloving",
    label: "Crush — Degloving",
    templateId: "trauma_msk_crush_degloving_v1",
    clinicalDomain: "Trauma",
    keywords: ["degloving", "degloving injury", "avulsion cutanée", "dégantage"],
    specialtyCategory: "plastic_surgery",
    riskCategory: "high",
    clinicalRationale: "Degloving injury needs reconstructive pathway and wound precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_crush_compartment_risk",
    label: "Crush — Compartment Risk",
    templateId: "trauma_msk_crush_compartment_risk_v1",
    clinicalDomain: "Trauma",
    keywords: ["compartment syndrome concern", "syndrome des loges", "compartment risk after crush"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale: "Crush with compartment concern — urgent precautions and specialty follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Compartment syndrome"],
  },
  {
    id: "trauma_crush_generic",
    label: "Crush — Other Sites",
    templateId: "trauma_msk_crush_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S07", "S17"],
    keywords: ["crush injury", "crushing injury", "écrasement", "industrial crush"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Other crush injuries not mapped to site-specific families (head/face/neck).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Crush injuries"],
  },
  {
    id: "trauma_amputation_finger_thumb",
    label: "Amputation — Finger / Thumb",
    templateId: "trauma_msk_amputation_finger_thumb_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S68.1", "S68.0", "S68"],
    keywords: ["traumatic amputation finger", "severed finger", "thumb cut off", "amputation doigt"],
    specialtyCategory: "hand_surgery",
    riskCategory: "high",
    clinicalRationale: "Digit amputation with hemorrhage control and replantation pathway considerations.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_hand_upper_extremity",
    label: "Amputation — Hand / Upper Extremity",
    templateId: "trauma_msk_amputation_hand_upper_extremity_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S48", "S58"],
    keywords: ["hand amputation", "arm amputation", "amputation main", "amputation bras"],
    specialtyCategory: "hand_surgery",
    riskCategory: "high",
    clinicalRationale: "Proximal upper-extremity amputation needs urgent specialty/transfer consideration.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_toe",
    label: "Amputation — Toe",
    templateId: "trauma_msk_amputation_toe_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S98.1", "S98.2"],
    keywords: ["traumatic amputation toe", "severed toe", "toe cut off", "amputation orteil"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Toe amputation stump care and specialty follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_foot_lower_extremity",
    label: "Amputation — Foot / Lower Extremity",
    templateId: "trauma_msk_amputation_foot_lower_extremity_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S78", "S88", "S98.0", "S98.3", "S98.9"],
    keywords: ["foot amputation", "leg amputation", "amputation pied", "amputation jambe"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale: "Lower-extremity amputation with hemorrhage and transfer considerations.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_partial",
    label: "Amputation — Partial",
    templateId: "trauma_msk_amputation_partial_v1",
    clinicalDomain: "Trauma",
    keywords: ["partial amputation", "partial traumatic amputation", "amputation partielle"],
    specialtyCategory: "hand_surgery",
    riskCategory: "high",
    clinicalRationale: "Partial amputation with tissue bridge — not generic laceration content.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_complete",
    label: "Amputation — Complete",
    templateId: "trauma_msk_amputation_complete_v1",
    clinicalDomain: "Trauma",
    keywords: ["complete amputation", "complete traumatic amputation", "amputation complète"],
    specialtyCategory: "hand_surgery",
    riskCategory: "high",
    clinicalRationale: "Complete traumatic amputation with amputated-part preservation guidance when relevant.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_amputation_postoperative_or_followup",
    label: "Amputation — Postoperative / Follow-up",
    templateId: "trauma_msk_amputation_postoperative_or_followup_v1",
    clinicalDomain: "Trauma",
    keywords: ["amputation followup", "stump care", "soins de moignon"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Postoperative or subsequent amputation encounter stump-care instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Amputation"],
  },
  {
    id: "trauma_amputation_generic",
    label: "Amputation — Other",
    templateId: "trauma_msk_amputation_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S08.1", "S08.8", "S28.1", "S28.2", "S38.2"],
    keywords: ["traumatic amputation", "amputation traumatique", "severed digit"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "high",
    clinicalRationale: "Head/trunk traumatic amputation not mapped to limb-specific families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["OrthoInfo — Amputations"],
  },
  {
    id: "trauma_foreign_body_eye",
    label: "Foreign Body — Eye",
    templateId: "trauma_msk_foreign_body_eye_v1",
    clinicalDomain: "Trauma",
    // Penetrating ocular S05.5x is owned by trauma_penetrating_eye (Phase 6).
    // Keep T15 for true external ocular foreign-body discharge routing.
    icdPrefixes: ["T15"],
    keywords: ["foreign body eye", "corneal foreign body", "corps étranger oeil"],
    specialtyCategory: "ophthalmology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Ocular foreign body with eye-specific precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Eye injuries"],
  },
  {
    id: "trauma_foreign_body_ear_nose",
    label: "Foreign Body — Ear / Nose",
    templateId: "trauma_msk_foreign_body_ear_nose_v1",
    clinicalDomain: "Trauma",
    /** Nose/nasal sinus FB lives under T17.0 / T17.1 — longer than aspirated T17. */
    icdPrefixes: ["T16", "T17.0", "T17.1"],
    keywords: ["foreign body ear", "foreign body nose", "corps étranger oreille", "corps étranger nez"],
    specialtyCategory: "ent",
    riskCategory: "moderate",
    clinicalRationale: "Ear/nose foreign body with ENT-oriented precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Ear disorders"],
  },
  {
    id: "trauma_foreign_body_skin_soft_tissue",
    label: "Foreign Body — Skin / Soft Tissue",
    templateId: "trauma_msk_foreign_body_skin_soft_tissue_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: [
      ...FOREIGN_BODY_SKIN_SOFT_TISSUE_OPEN_ICD_PREFIXES,
      ...FOREIGN_BODY_SKIN_SOFT_TISSUE_SUPERFICIAL_ICD_PREFIXES,
    ],
    keywords: ["foreign body skin", "retained foreign body", "splinter", "glass in skin", "écharde"],
    specialtyCategory: "wound_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Soft-tissue foreign body with residual-fragment and infection monitoring.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_foreign_body_hand_finger",
    label: "Foreign Body — Hand / Finger",
    templateId: "trauma_msk_foreign_body_hand_finger_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: [...FOREIGN_BODY_HAND_FINGER_ICD_PREFIXES],
    keywords: ["foreign body hand", "foreign body finger", "splinter hand", "corps étranger main"],
    specialtyCategory: "hand_surgery",
    riskCategory: "moderate",
    clinicalRationale: "Hand foreign body — outranks generic puncture/laceration when FB present.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_foreign_body_foot_toe",
    label: "Foreign Body — Foot / Toe",
    templateId: "trauma_msk_foreign_body_foot_toe_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: [...FOREIGN_BODY_FOOT_TOE_ICD_PREFIXES],
    keywords: ["foreign body foot", "splinter in foot", "corps étranger pied"],
    specialtyCategory: "wound_care",
    riskCategory: "moderate",
    clinicalRationale: "Foot/toe foreign body with wound and activity precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_foreign_body_fishhook",
    label: "Foreign Body — Fishhook",
    templateId: "trauma_msk_foreign_body_fishhook_v1",
    clinicalDomain: "Trauma",
    keywords: ["fishhook", "hameçon", "hamecon"],
    specialtyCategory: "wound_care",
    riskCategory: "moderate",
    clinicalRationale: "Fishhook injury with removal-completeness and tetanus considerations.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_foreign_body_ingested",
    label: "Foreign Body — Ingested",
    templateId: "trauma_msk_foreign_body_ingested_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T18"],
    keywords: ["swallowed foreign body", "ingested foreign body", "corps étranger avalé"],
    specialtyCategory: "gastroenterology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Ingested foreign body — not simple wound discharge content.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Foreign object in esophagus"],
  },
  {
    id: "trauma_foreign_body_aspirated",
    label: "Foreign Body — Aspirated",
    templateId: "trauma_msk_foreign_body_aspirated_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T17"],
    keywords: ["aspirated foreign body", "airway foreign body", "corps étranger inhalé"],
    specialtyCategory: "pulmonology",
    riskCategory: "high",
    clinicalRationale: "Aspirated foreign body needs urgent airway-capable evaluation.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Choking"],
  },
  {
    id: "trauma_foreign_body_retained_fragment",
    label: "Foreign Body — Retained Fragment",
    templateId: "trauma_msk_foreign_body_retained_fragment_v1",
    clinicalDomain: "Trauma",
    keywords: ["retained fragment", "retained foreign body", "fragment retenu"],
    specialtyCategory: "wound_care",
    riskCategory: "moderate",
    clinicalRationale: "Retained fragment warning and specialty follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_foreign_body_generic",
    label: "Foreign Body — Other",
    templateId: "trauma_msk_foreign_body_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T19"],
    keywords: ["foreign body", "foreign object", "corps étranger"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Other foreign-body injuries including genitourinary tract codes.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_burn_frostbite",
    label: "Frostbite / Cold Injury",
    templateId: "frostbite_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T33", "T34", "T35"],
    keywords: ["frostbite", "gelure", "cold injury"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Cold injury requires tissue protection and reassessment for evolving perfusion injury.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Frostbite"],
  },
  {
    id: "trauma_burn_inhalation",
    label: "Inhalation Injury",
    templateId: "burn_inhalation_aftercare_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T27"],
    keywords: ["smoke inhalation", "inhalation injury", "airway burn", "inhalation de fumée"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "high",
    clinicalRationale: "Airway symptoms after smoke or thermal exposure may worsen after discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Smoke inhalation"],
  },
  {
    id: "trauma_burn_eye",
    label: "Burn — Eye",
    templateId: "burn_eye_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T26"],
    keywords: ["burn eye", "ocular burn", "brûlure oeil"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "high",
    clinicalRationale: "Ocular burns require vision-specific return precautions and timely reassessment.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Eye injuries"],
  },
  {
    id: "trauma_burn_chemical",
    label: "Burn — Chemical / Corrosion",
    templateId: "burn_chemical_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T20.4", "T20.5", "T20.6", "T20.7", "T21.4", "T21.5", "T21.6", "T21.7", "T22.4", "T22.5", "T22.6", "T22.7", "T23.4", "T23.5", "T23.6", "T23.7", "T24.4", "T24.5", "T24.6", "T24.7", "T25.4", "T25.5", "T25.6", "T25.7", "T26.4", "T26.5", "T26.6", "T26.7", "T27.4", "T27.5", "T27.6", "T27.7", "T28.4", "T28.5", "T28.6", "T28.7", "T32"],
    keywords: ["chemical burn", "corrosion", "acid burn", "alkali", "brûlure chimique"],
    specialtyCategory: "burn_surgery",
    riskCategory: "high",
    clinicalRationale: "Chemical injuries can progress despite initial decontamination and need burn-specialty review.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Chemical burns"],
  },
  {
    id: "trauma_burn_electrical",
    label: "Burn — Electrical / Lightning",
    templateId: "burn_electrical_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T75.0", "T75.4"],
    keywords: ["electrical burn", "lightning", "brûlure électrique", "foudre"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "high",
    clinicalRationale: "Electrical injury may have occult cardiac, neurologic, or deep-tissue effects.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Electrical injuries"],
  },
  {
    id: "trauma_burn_sunburn",
    label: "Sunburn",
    templateId: "sunburn_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["L55"],
    keywords: ["sunburn", "coup de soleil"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Sunburn care includes hydration, skin protection, and escalation for severe blistering or systemic symptoms.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sunburn"],
  },
  {
    id: "trauma_burn_face",
    label: "Burn — Face",
    templateId: "burn_face_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T20.0", "T20.1", "T20.2", "T20.3"],
    keywords: ["facial burn", "burn face", "brûlure du visage"],
    specialtyCategory: "burn_surgery",
    riskCategory: "high",
    clinicalRationale: "Facial burns require airway and eye escalation precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_hand",
    label: "Burn — Hand",
    templateId: "burn_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T23.0", "T23.1", "T23.2", "T23.3"],
    keywords: ["hand burn", "burn hand", "brûlure de la main"],
    specialtyCategory: "burn_surgery",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Hand burns need neurovascular monitoring and functional follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_foot",
    label: "Burn — Foot",
    templateId: "burn_foot_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T25.0", "T25.1", "T25.2", "T25.3"],
    keywords: ["foot burn", "burn foot", "brûlure du pied"],
    specialtyCategory: "burn_surgery",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Foot burns need neurovascular monitoring, protected ambulation, and wound follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_full_thickness",
    label: "Burn — Full Thickness",
    templateId: "burn_full_thickness_followup_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T21.3", "T22.3", "T24.3", "T28.3", "T30.3"],
    keywords: ["full-thickness burn", "third-degree burn", "brûlure profonde"],
    specialtyCategory: "burn_surgery",
    riskCategory: "high",
    clinicalRationale: "Full-thickness burns require urgent burn-specialty follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_partial_thickness",
    label: "Burn — Partial Thickness",
    templateId: "burn_partial_thickness_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T21.2", "T22.2", "T24.2", "T30.2"],
    keywords: ["partial-thickness burn", "second-degree burn", "brûlure partielle"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Partial-thickness burns require dressing care and early wound reassessment.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_superficial",
    label: "Burn — Superficial",
    templateId: "burn_superficial_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T21.1", "T22.1", "T24.1", "T30.0", "T30.1"],
    keywords: ["superficial burn", "first-degree burn", "brûlure superficielle"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Superficial burns require protective skin care and infection return precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_burn_generic",
    label: "Burn — Other / Unspecified",
    templateId: "burn_partial_thickness_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["T21", "T22", "T24", "T28", "T30", "T31"],
    keywords: ["burn", "thermal burn", "brûlure", "scald", "ébouillantage"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "Fallback for thermal burns not captured by site, depth, or mechanism-specific families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Burns"],
  },
  {
    id: "trauma_penetrating_eye", label: "Penetrating injury — Eye", templateId: "penetrating_eye_followup_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S05.4", "S05.50", "S05.51", "S05.52", "S05.5", "S05.6"], keywords: ["penetrating eye", "ocular penetration", "plaie pénétrante oeil", "plaie pénétrante de l'œil"],
    specialtyCategory: "ophthalmology", riskCategory: "high", clinicalRationale: "Penetrating ocular trauma needs urgent specialist-directed reassessment.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Eye injuries"],
  },
  {
    id: "trauma_penetrating_chest", label: "Penetrating injury — Chest", templateId: "penetrating_chest_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S21.1", "S21.2", "S21.3", "S21.4", "S25", "S26", "S27"], keywords: ["penetrating chest", "gunshot chest", "stab chest"],
    specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Thoracic penetrating injury must not use minor-wound instructions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Chest injuries"],
  },
  {
    id: "trauma_penetrating_abdomen", label: "Penetrating injury — Abdomen", templateId: "penetrating_abdomen_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S31.0", "S31.1", "S31.5", "S31.6", "S31.8", "S35", "S36", "S37"], keywords: ["penetrating abdomen", "gunshot abdomen", "stab abdomen"],
    specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Abdominal or organ penetrating injury requires strong escalation precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Abdominal injuries"],
  },
  {
    id: "trauma_penetrating_neck", label: "Penetrating injury — Neck", templateId: "penetrating_neck_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S11.0", "S11.1", "S11.2", "S11.8", "S11.9", "S15"], keywords: ["penetrating neck", "gunshot neck", "stab neck", "plaie ouverte du cou"],
    specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Neck penetrating injury needs airway and bleeding escalation language.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Neck injuries"],
  },
  {
    id: "trauma_penetrating_head", label: "Penetrating injury — Head", templateId: "penetrating_head_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S01.0", "S01.1", "S01.2", "S01.3", "S01.4", "S01.5", "S01.8", "S01.9"], keywords: ["penetrating head", "gunshot head", "stab head"],
    specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Head penetrating injury must not route to generic laceration content.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Head injuries"],
  },
  {
    id: "trauma_penetrating_hand", label: "Penetrating injury — Hand", templateId: "penetrating_hand_injury_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S61.0", "S61.1", "S61.2", "S61.3", "S61.4", "S61.5", "S65"], keywords: ["penetrating hand", "puncture hand", "plaie pénétrante main"],
    specialtyCategory: "hand_surgery", riskCategory: "moderate_to_high", clinicalRationale: "Hand puncture and vascular injury require neurovascular precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Hand injuries"],
  },
  {
    id: "trauma_penetrating_foot", label: "Penetrating injury — Foot", templateId: "penetrating_foot_injury_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S91.0", "S91.1", "S91.2", "S91.3", "S95"], keywords: ["penetrating foot", "puncture foot", "plaie pénétrante pied"],
    specialtyCategory: "orthopedics", riskCategory: "moderate_to_high", clinicalRationale: "Foot puncture and vascular injury require protected ambulation and reassessment.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Foot injuries"],
  },
  {
    id: "trauma_penetrating_face", label: "Penetrating injury — Face", templateId: "penetrating_face_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S01.1", "S01.2", "S01.4", "S01.5", "S01.8", "S01.9"], keywords: ["penetrating face", "facial penetrating", "plaie pénétrante visage"],
    specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Facial penetrating injury needs airway and vision return precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Facial injuries"],
  },
  {
    id: "trauma_penetrating_gsw_extremity", label: "Gunshot wound — Extremity", templateId: "gunshot_wound_extremity_v1", clinicalDomain: "Trauma",
    keywords: ["gunshot", "firearm", "bullet", "blessure par balle"], specialtyCategory: "orthopedics", riskCategory: "high", clinicalRationale: "Gunshot extremity discharge requires bleeding and neurovascular precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_penetrating_stab_minor", label: "Stab wound — Minor", templateId: "stab_wound_minor_v1", clinicalDomain: "Trauma",
    keywords: ["stab", "knife", "arme blanche", "couteau"], specialtyCategory: "emergency_medicine", riskCategory: "moderate", clinicalRationale: "Minor evaluated stab wound instructions remain distinct from torso penetrating trauma.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_penetrating_retained_projectile", label: "Retained projectile", templateId: "retained_projectile_v1", clinicalDomain: "Trauma",
    keywords: ["retained bullet", "retained projectile", "projectile retained", "balle retenue", "projectile retenu"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Retained projectiles must not be manipulated or removed outside the planned care path.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_penetrating_minor", label: "Penetrating wound — Minor", templateId: "penetrating_wound_minor_v1", clinicalDomain: "Trauma",
    icdPrefixes: ["S11", "S21", "S31"], keywords: ["penetrating wound", "puncture wound", "plaie pénétrante", "plaie perforante"], specialtyCategory: "emergency_medicine", riskCategory: "moderate", clinicalRationale: "Fallback only after longer anatomic penetrating families are considered.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  { id: "trauma_blast_ear", label: "Blast injury — Ear", templateId: "blast_ear_injury_v1", clinicalDomain: "Trauma", icdPrefixes: ["S09.2", "T70.0", "H83.3"], keywords: ["blast ear", "otitic barotrauma", "explosion ear"], specialtyCategory: "ent", riskCategory: "moderate_to_high", clinicalRationale: "Blast ear injury needs hearing and delayed-symptom precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Ear injuries"] },
  { id: "trauma_blast_lung", label: "Blast injury — Lung", templateId: "blast_lung_aftercare_v1", clinicalDomain: "Trauma", icdPrefixes: ["T70.1", "T70.8", "T70.9"], keywords: ["blast lung", "pulmonary barotrauma", "pressure effects"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Pressure-effect discharge is reserved for evaluated cases and preserves penetrating thoracic ownership.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Lung injuries"] },
  { id: "trauma_blast_abdomen", label: "Blast injury — Abdomen", templateId: "blast_abdominal_observation_v1", clinicalDomain: "Trauma", keywords: ["blast abdomen", "abdominal blast", "explosion abdominal"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Keyword-only guidance does not take penetrating abdominal injury codes.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Abdominal injuries"] },
  { id: "trauma_blast_mild_tbi", label: "Blast injury — Mild TBI", templateId: "blast_mild_tbi_v1", clinicalDomain: "Trauma", keywords: ["blast concussion", "blast head injury"], specialtyCategory: "neurology", riskCategory: "high", clinicalRationale: "Blast-related neurologic symptoms require reassessment precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Head injuries"] },
  { id: "trauma_blast_fragment", label: "Blast injury — Fragment", templateId: "blast_fragment_wound_v1", clinicalDomain: "Trauma", keywords: ["fragment", "shrapnel", "explosion fragment"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Keyword-only fragment instructions preserve wound-family code ownership.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"] },
  { id: "trauma_blast_burn", label: "Blast injury — Burn", templateId: "blast_burn_aftercare_v1", clinicalDomain: "Trauma", keywords: ["explosion burn", "blast burn"], specialtyCategory: "emergency_medicine", riskCategory: "moderate_to_high", clinicalRationale: "Keyword-only blast burn aftercare preserves T20–T32 burn ownership.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Burns"] },
  { id: "trauma_blast_crush", label: "Blast injury — Crush", templateId: "blast_crush_aftercare_v1", clinicalDomain: "Trauma", keywords: ["blast crush", "explosion crush", "entrapment"], specialtyCategory: "orthopedics", riskCategory: "high", clinicalRationale: "Keyword-only blast crush aftercare preserves specific crush injury codes.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Crush injuries"] },
  { id: "trauma_blast_collapse", label: "Blast injury — Structural collapse", templateId: "post_structural_collapse_v1", clinicalDomain: "Trauma", icdPrefixes: ["T71.21"], keywords: ["building collapse", "cave-in", "ensevelissement"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Collapse-associated asphyxiation requires high-risk precautions.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Injuries"] },
  { id: "trauma_polytrauma", label: "Polytrauma", templateId: "polytrauma_followup_v1", clinicalDomain: "Trauma", icdPrefixes: ["T07", "T79.4"], keywords: ["polytrauma", "multiple trauma", "multisystem"], specialtyCategory: "emergency_medicine", riskCategory: "high", clinicalRationale: "Multiple injury and traumatic shock follow-up remain trauma-directed.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Injuries"] },
  { id: "trauma_blast_minor", label: "Blast injury — Minor/external cause", templateId: "blast_injury_minor_v1", clinicalDomain: "Trauma", icdPrefixes: ["W35", "W36", "W37", "W38", "W39", "W40", "X75", "X96", "Y25", "Y35", "Y36", "Y37", "Y38", "V"], keywords: ["explosion", "firework", "blasting material"], specialtyCategory: "emergency_medicine", riskCategory: "moderate", clinicalRationale: "External-cause context never replaces anatomic primary injury coding.", reviewStatus: "reviewed", routingStatus: "READY", sourceReferenceLabels: ["MedlinePlus — Injuries"] },

] as const;
