/**
 * Phase 1 clinical condition families (21) — migrated with domain + routing status fields.
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";

export const PHASE1_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] = [
  {
    id: "nausea_vomiting",
    label: "Nausea / Vomiting",
    templateId: "nausea_vomiting_v1",
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R11.0", "R11.1", "R11.2", "R11.10"],
    icdPrefixes: ["R11"],
    excludeIcdExact: ["E86.0"],
    keywords: ["nausea", "vomiting", "emesis"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shared ED discharge guidance for nausea with or without vomiting.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Nausea and vomiting"],
  },
  {
    id: "cellulitis_skin_infection",
    label: "Cellulitis / Skin Infection",
    templateId: "cellulitis_v1",
    additionalTemplateIds: ["infectious_cellulitis_followup_v1"],
    clinicalDomain: "Skin/Infection",
    icdExact: ["L08.9", "L03.90", "L03.115", "L03.116"],
    icdPrefixes: ["L03", "L08"],
    excludeIcdPrefixes: ["L08.0", "L02"],
    keywords: ["cellulitis", "skin infection"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Soft-tissue infection discharge instructions; distinct from wound/laceration trauma care.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Cellulitis"],
  },
  {
    id: "uri_cough",
    label: "URI / Cough",
    templateId: "uri_cough_v1",
    additionalTemplateIds: ["infectious_upper_respiratory_infection_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["J00", "J06.9"],
    icdPrefixes: ["J06", "R05"],
    keywords: ["upper respiratory infection", "uri", "cough", "common cold", "rhinopharyngitis"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Age-neutral URI/cough template; pediatric URI uses separate guarded family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "pediatric_uri",
    label: "Pediatric URI",
    templateId: "pediatric_uri_v1",
    clinicalDomain: "Respiratory",
    keywords: ["pediatric uri", "pediatric upper respiratory", "child cold", "rhume enfant"],
    guardrails: { age: { maxAgeYears: 18 } },
    specialtyCategory: "pediatrics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Pediatric-only URI wording; requires pediatric age context or explicit pediatric keyword.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Common cold"],
  },
  {
    id: "chest_pain",
    label: "Chest Pain",
    templateId: "chest_pain_v1",
    additionalTemplateIds: ["cardio_chest_pain_low_risk_v1", "chest_wall_pain_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R07.9"],
    icdPrefixes: ["R07"],
    keywords: ["chest pain", "chest discomfort", "douleur thoracique"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Cardiac-safe return precautions for undifferentiated chest pain discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Chest pain"],
  },
  {
    id: "abdominal_pain",
    label: "Abdominal Pain",
    templateId: "abdominal_pain_v1",
    additionalTemplateIds: ["pediatric_abdominal_pain_v1"],
    clinicalDomain: "Gastrointestinal",
    icdPrefixes: ["R10"],
    excludeIcdExact: ["R10.2"],
    keywords: ["abdominal pain", "belly pain", "douleur abdominale"],
    specialtyCategory: "emergency_medicine",
    riskCategory: "moderate",
    clinicalRationale: "General abdominal pain; pelvic pain routed to OB/GYN family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Abdominal pain"],
  },
  {
    id: "headache",
    label: "Headache",
    templateId: "headache_v1",
    additionalTemplateIds: ["high_risk_medical_headache_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["R51", "G44"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["headache", "migraine", "cephalalgia", "céphalée"],
    specialtyCategory: "neurology",
    riskCategory: "moderate",
    clinicalRationale: "Primary headache discharge; excludes stroke/TIA red-flag templates.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Headache"],
  },
  {
    id: "uti_urinary_symptoms",
    label: "UTI / Urinary Symptoms",
    templateId: "uti_v1",
    additionalTemplateIds: ["urology_uti_followup_v1", "obgyn_uti_pregnancy_precautions_v1"],
    clinicalDomain: "Genitourinary",
    icdExact: ["N39.0"],
    icdPrefixes: ["R30", "N39"],
    keywords: ["urinary tract infection", "uti", "dysuria", "burning urination"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Uncomplicated urinary symptoms and UTI outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Urinary tract infections"],
  },
  {
    id: "gastroenteritis_diarrhea",
    label: "Gastroenteritis / Diarrhea",
    templateId: "gastroenteritis_v1",
    additionalTemplateIds: [
      "gi_infectious_gastroenteritis_v1",
      "pediatric_gastroenteritis_v1",
    ],
    clinicalDomain: "Gastrointestinal",
    icdExact: ["R19.7", "A09", "K59.1"],
    icdPrefixes: ["R19", "A08"],
    keywords: ["diarrhea", "gastroenteritis", "loose stool"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Acute diarrheal illness; distinct from constipation family (K59.0*).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Gastroenteritis"],
  },
  {
    id: "back_pain",
    label: "Back Pain",
    templateId: "back_pain_v1",
    additionalTemplateIds: ["trauma_msk_back_strain_v1"],
    clinicalDomain: "Musculoskeletal",
    icdPrefixes: ["M54"],
    keywords: ["back pain", "low back pain", "sciatica"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Musculoskeletal back pain without acute neuro deficit documentation.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back pain"],
  },
  {
    id: "asthma_wheezing",
    label: "Asthma / Wheezing",
    templateId: "asthma_exacerbation_v1",
    additionalTemplateIds: ["pediatric_asthma_exacerbation_v1", "pediatric_wheezing_v1"],
    clinicalDomain: "Respiratory",
    icdExact: ["R06.2"],
    icdPrefixes: ["J45"],
    icdExactTemplateOverrides: {
      "R06.2": "pediatric_wheezing_v1",
    },
    keywords: ["asthma", "wheezing", "asthma exacerbation"],
    specialtyCategory: "pulmonology",
    riskCategory: "moderate",
    clinicalRationale: "Reactive airway disease discharge with inhaler safety language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Asthma"],
  },
  {
    id: "pneumonia_lower_respiratory",
    label: "Pneumonia / Lower Respiratory Infection",
    templateId: "pneumonia_v1",
    additionalTemplateIds: ["infectious_pneumonia_followup_v1"],
    clinicalDomain: "Respiratory",
    icdPrefixes: ["J18", "J15", "J16", "J17"],
    keywords: ["pneumonia"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Lower respiratory infection requiring outpatient reassessment.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Pneumonia"],
  },
  {
    id: "hypertension_elevated_bp",
    label: "Hypertension / Elevated BP",
    templateId: "hypertension_v1",
    additionalTemplateIds: ["cardio_hypertension_elevated_bp_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["I10", "R03.0"],
    icdPrefixes: ["I10"],
    keywords: ["hypertension", "elevated blood pressure", "high blood pressure"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Blood pressure chief complaint or known HTN management at discharge.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood pressure"],
  },
  {
    id: "diabetes_hyperglycemia",
    label: "Diabetes / Hyperglycemia (acute)",
    templateId: "hyperglycemia_v1",
    clinicalDomain: "Endocrine",
    icdExact: ["E11.65"],
    icdPrefixes: ["R73"],
    excludeIcdExact: ["E11.9"],
    keywords: ["hyperglycemia", "high blood sugar"],
    specialtyCategory: "endocrinology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Acute hyperglycemia symptoms — not stable type 2 outpatient management.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — High blood sugar"],
  },
  {
    id: "type_2_diabetes_non_acute",
    label: "Type 2 Diabetes (non-acute)",
    templateId: "type_2_diabetes_v1",
    additionalTemplateIds: ["diabetes_sick_day_precautions_v1"],
    clinicalDomain: "Endocrine",
    icdExact: ["E11.9"],
    icdPrefixes: ["E11"],
    excludeIcdExact: ["E11.65"],
    keywords: ["type 2 diabetes", "diabetes type 2", "diabète de type 2"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Stable type 2 diabetes outpatient instructions without implying acute hyperglycemia crisis.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Diabetes type 2"],
  },
  {
    id: "trauma_wound_laceration",
    label: "Trauma / Wound / Laceration",
    templateId: "wound_laceration_v1",
    clinicalDomain: "Trauma",
    icdExact: ["S01.01", "T14.1"],
    icdPrefixes: ["S01", "S41", "S51", "S61", "S71", "S81", "S91", "T14"],
    excludeIcdPrefixes: [
      "L03",
      "L08",
      "W54",
      "W55",
      "W50.3",
      "S01.05",
      "S01.15",
      "S01.25",
      "S01.35",
      "S01.45",
      "S01.55",
      "S11.95",
      "S41.15",
      "S51.85",
      "S61.45",
      "S71.15",
      "S81.85",
      "S91.15",
    ],
    keywords: ["laceration", "wound", "cut", "abrasion", "plaie", "suture"],
    specialtyCategory: "wound_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Traumatic wound care; excludes soft-tissue infection and animal-bite open-bite families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wounds and injuries"],
  },
  {
    id: "trauma_animal_bite",
    label: "Trauma / Animal Bite",
    templateId: "animal_bite_v1",
    clinicalDomain: "Trauma",
    icdExact: [
      "W54.0XXA",
      "W55.01XA",
      "W55.03XA",
      "W55.81XA",
      "W50.3XXA",
      "S61.459A",
      "S01.05XA",
    ],
    icdPrefixes: [
      "W54",
      "W55",
      "W50.3",
      "S01.05",
      "S01.15",
      "S01.25",
      "S01.35",
      "S01.45",
      "S01.55",
      "S11.95",
      "S41.15",
      "S51.85",
      "S61.45",
      "S71.15",
      "S81.85",
      "S91.15",
    ],
    keywords: [
      "animal bite",
      "dog bite",
      "cat bite",
      "human bite",
      "mammal bite",
      "bite wound",
      "open bite",
      "bitten by dog",
      "bitten by cat",
      "morsure animale",
      "morsure de chien",
      "morsure de chat",
      "morsure humaine",
      "plaie par morsure",
    ],
    specialtyCategory: "wound_care",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Animal/human bite wound care with infection, tetanus, and rabies-focused discharge instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Animal bites"],
  },
  {
    id: "dizziness_vertigo",
    label: "Dizziness / Vertigo",
    templateId: "vertigo_dizziness_v1",
    additionalTemplateIds: ["high_risk_medical_dizziness_v1"],
    clinicalDomain: "Neurologic",
    icdExact: ["R42"],
    icdPrefixes: ["H81"],
    excludeIcdPrefixes: ["I63", "G45"],
    keywords: ["dizziness", "vertigo", "lightheaded"],
    specialtyCategory: "primary_care",
    riskCategory: "moderate",
    clinicalRationale: "Peripheral or undifferentiated dizziness discharge instructions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dizziness and vertigo"],
  },
  {
    id: "syncope",
    label: "Syncope",
    templateId: "syncope_v1",
    additionalTemplateIds: ["cardio_syncope_v1"],
    clinicalDomain: "Cardiac",
    icdExact: ["R55"],
    excludeIcdPrefixes: ["R53"],
    keywords: ["syncope", "fainting", "passed out"],
    specialtyCategory: "cardiology",
    riskCategory: "moderate",
    clinicalRationale: "Transient loss of consciousness outpatient follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fainting"],
  },
  {
    id: "seizure",
    label: "Seizure",
    templateId: "seizure_v1",
    additionalTemplateIds: ["pediatric_febrile_seizure_v1"],
    clinicalDomain: "Neurologic",
    icdPrefixes: ["G40", "R56"],
    keywords: ["seizure", "convulsion", "epilepsy"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "neurology",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Post-seizure return precautions and neurology follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Seizures"],
  },
  {
    id: "behavioral_health_crisis",
    label: "Behavioral Health Crisis",
    templateId: "behavioral_health_suicidal_ideation_precautions_v1",
    additionalTemplateIds: [
      "behavioral_health_anxiety_panic_symptoms_v1",
      "behavioral_health_depression_crisis_precautions_v1",
      "behavioral_health_crisis_follow_up_v1",
      "behavioral_health_alcohol_intoxication_follow_up_v1",
      "behavioral_health_alcohol_withdrawal_precautions_v1",
      "behavioral_health_substance_use_resources_v1",
      "behavioral_health_opioid_overdose_aftercare_v1",
      "behavioral_health_insomnia_stress_reaction_v1",
      "behavioral_health_grief_adjustment_v1",
      "anxiety_panic_v1",
      "alcohol_intoxication_v1",
    ],
    clinicalDomain: "Behavioral Health",
    icdExact: ["R45.851", "F41.0", "F41.9", "F32.9", "F10.239", "T40.2X5A"],
    icdPrefixes: ["F32"],
    keywords: [
      "bh suicidal ideation",
      "suicidal ideation",
      "bh depression crisis",
      "behavioral health crisis",
      "bh alcohol withdrawal",
      "bh opioid overdose",
      "behavioral health crisis follow-up",
    ],
    icdExactTemplateOverrides: {
      "F41.0": "behavioral_health_anxiety_panic_symptoms_v1",
      "F41.9": "behavioral_health_anxiety_panic_symptoms_v1",
      "F32.9": "behavioral_health_depression_crisis_precautions_v1",
      "R45.851": "behavioral_health_suicidal_ideation_precautions_v1",
      "F10.239": "behavioral_health_alcohol_withdrawal_precautions_v1",
      "T40.2X5A": "behavioral_health_opioid_overdose_aftercare_v1",
    },
    guardrails: {
      safety: {
        requiresCrisisReturnPrecautions: true,
        requiresEdReturnPrecautions: true,
        requiresSpecialistFollowUp: true,
      },
    },
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale:
      "Crisis safety planning with exact-code overrides; withdrawal and opioid aftercare separated from intoxication routing.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide", "MedlinePlus — Depression"],
  },
  {
    id: "obgyn_bleeding_pelvic_pain",
    label: "OB/GYN Bleeding / Pelvic Pain",
    templateId: "obgyn_vaginal_bleeding_v1",
    additionalTemplateIds: [
      "obgyn_pelvic_pain_v1",
      "obgyn_dysmenorrhea_v1",
      "obgyn_hyperemesis_v1",
      "obgyn_early_pregnancy_symptoms_v1",
      "obgyn_threatened_miscarriage_precautions_v1",
      "obgyn_vaginitis_v1",
      "obgyn_round_ligament_pain_v1",
      "obgyn_postpartum_warning_v1",
    ],
    clinicalDomain: "OB/GYN",
    icdExact: ["N93.9", "R10.2", "N94.6", "O21.9"],
    icdPrefixes: ["N93", "O20", "O21", "O26", "O90", "N76"],
    icdExactTemplateOverrides: {
      "R10.2": "obgyn_pelvic_pain_v1",
      "N94.6": "obgyn_dysmenorrhea_v1",
      "O21.9": "obgyn_hyperemesis_v1",
      "O20.9": "obgyn_early_pregnancy_symptoms_v1",
      "O20.0": "obgyn_threatened_miscarriage_precautions_v1",
      "N76.0": "obgyn_vaginitis_v1",
      "O26.89": "obgyn_round_ligament_pain_v1",
      "O90.89": "obgyn_postpartum_warning_v1",
      "Z39.9": "obgyn_postpartum_warning_v1",
    },
    keywords: ["obgyn vaginal bleeding", "obgyn pelvic pain", "gynecologic bleeding"],
    guardrails: {
      sex: { sex: "female" },
      safety: { requiresEdReturnPrecautions: true, requiresSpecialistFollowUp: true },
    },
    specialtyCategory: "obgyn",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Gynecologic bleeding and pelvic pain with female sex guardrail and pregnancy-sensitive template overrides.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Vaginal bleeding", "MedlinePlus — Pelvic pain"],
  },
  {
    id: "trauma_fracture_upper_extremity",
    label: "Fracture — Upper Extremity",
    templateId: "trauma_msk_minor_fracture_precautions_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S42", "S52"],
    keywords: ["broken arm", "broken wrist", "broken collarbone", "broken shoulder", "fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Closed shoulder-girdle, humerus, and forearm/wrist fractures managed with splinting and outpatient orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Fractures"],
  },
  {
    id: "trauma_fracture_lower_extremity",
    label: "Fracture — Lower Extremity",
    templateId: "trauma_msk_minor_fracture_precautions_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S72", "S82", "S92", "M84", "S32.1", "S32.2", "S32.3", "S32.4", "S32.5", "S32.6", "S32.8", "S32.9"],
    excludeIcdPrefixes: ["S72.0", "S72.1", "S72.2"],
    keywords: [
      "broken leg",
      "broken ankle",
      "broken foot",
      "broken toe",
      "stress fracture",
      "pathologic fracture",
      "pelvic fracture",
      "pelvis fracture",
      "broken pelvis",
    ],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Closed femoral shaft, tibia/fibula, ankle, and foot fractures (excluding proximal-femur hip fractures) managed with splinting/casting and outpatient orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Fractures"],
  },
  {
    id: "trauma_fracture_hip",
    label: "Fracture — Hip",
    templateId: "trauma_msk_fracture_hip_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S72.0", "S72.1", "S72.2"],
    keywords: ["hip fracture", "broken hip", "fractured hip", "femoral neck fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Proximal femur (femoral neck, trochanteric, subtrochanteric) fractures usually require orthopedic surgery and often hospital admission.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hip fractures", "OrthoInfo — Hip fractures"],
  },
  {
    id: "trauma_fracture_hand",
    label: "Fracture — Hand / Finger / Wrist Bones",
    templateId: "trauma_msk_fracture_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S62"],
    keywords: ["hand fracture", "finger fracture", "broken finger", "metacarpal fracture", "phalanx fracture"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Hand, finger, and carpal (wrist-bone) fractures with splinting, elevation, and hand surgery or orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hand injuries and disorders", "OrthoInfo — Hand fractures"],
  },
  {
    id: "trauma_fracture_facial",
    label: "Fracture — Facial / Nasal / Orbital / Mandible",
    templateId: "trauma_msk_fracture_facial_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S02"],
    keywords: ["facial fracture", "broken jaw", "broken nose", "orbital fracture", "mandible fracture"],
    specialtyCategory: "ent",
    riskCategory: "moderate_to_high",
    clinicalRationale:
      "Facial, nasal, orbital, and mandible fractures with vision/malocclusion escalation language and ENT or maxillofacial follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Facial injuries and disorders"],
  },
  {
    id: "trauma_fracture_spinal",
    label: "Fracture — Spinal (Vertebral)",
    templateId: "trauma_msk_fracture_spine_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S12", "S22.0", "S22.1", "S32.0"],
    keywords: ["spinal fracture", "vertebral fracture", "compression fracture spine", "cervical spine fracture", "lumbar spine fracture"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Cervical, thoracic, and lumbar vertebral fractures with head/neck/spine escalation language and neurosurgery/spine surgery advisory follow-up when cord or nerve root signs are present. Pelvic ring codes remain on the lower-extremity fracture family.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back injuries", "OrthoInfo — Spinal fractures"],
  },
  {
    id: "trauma_fracture_open",
    label: "Fracture — Open (Compound)",
    templateId: "trauma_msk_fracture_open_v1",
    clinicalDomain: "Trauma",
    icdExact: ["S82.201B", "S52.531B", "S72.001B"],
    keywords: ["open fracture", "compound fracture", "open bone fracture"],
    guardrails: {
      safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
    },
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale:
      "Open fractures with skin breakdown typically require surgical debridement and IV antibiotics; differentiated from closed fractures by exact 7th-character codes rather than a shared ICD prefix.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Fractures", "OrthoInfo — Open fractures"],
  },
  {
    id: "trauma_fracture_rib",
    label: "Fracture — Rib",
    templateId: "trauma_msk_rib_injury_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S22.3", "S22.4", "S22.5"],
    keywords: ["rib fracture", "broken rib", "multiple rib fractures", "flail chest"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale:
      "Single, multiple, and flail-chest rib fractures share the existing rib/chest-wall injury discharge template with pulmonary escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Rib injuries"],
  },
  {
    id: "trauma_dislocation_shoulder",
    label: "Dislocation — Shoulder / AC / SC",
    templateId: "trauma_msk_dislocation_shoulder_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S43.0", "S43.1", "S43.2"],
    keywords: ["shoulder dislocation", "dislocated shoulder", "ac separation", "acromioclavicular"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Shoulder girdle dislocations and AC/SC injuries with immobilization and orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Shoulder injuries", "OrthoInfo — Shoulder dislocation"],
  },
  {
    id: "trauma_dislocation_elbow",
    label: "Dislocation — Elbow / Nursemaid",
    templateId: "trauma_msk_dislocation_elbow_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S53.0", "S53.1"],
    keywords: ["elbow dislocation", "nursemaid elbow", "pulled elbow", "radial head subluxation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Elbow dislocation and pediatric nursemaid elbow with reduction and neurovascular precautions.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Elbow injuries", "OrthoInfo — Nursemaid's elbow"],
  },
  {
    id: "trauma_dislocation_hip",
    label: "Dislocation — Hip",
    templateId: "trauma_msk_dislocation_hip_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S73.0"],
    keywords: ["hip dislocation", "dislocated hip"],
    specialtyCategory: "orthopedics",
    riskCategory: "high",
    clinicalRationale: "Hip dislocation typically requires urgent reduction and orthopedic management.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Hip injuries", "OrthoInfo — Hip dislocation"],
  },
  {
    id: "trauma_dislocation_patella",
    label: "Dislocation — Patella / Knee",
    templateId: "trauma_msk_dislocation_patella_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S83.0", "S83.1"],
    keywords: ["patella dislocation", "dislocated kneecap", "knee dislocation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate_to_high",
    clinicalRationale: "Patellar and tibiofemoral dislocations with immobilization and orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Kneecap dislocation", "OrthoInfo — Patellar dislocation"],
  },
  {
    id: "trauma_dislocation_hand",
    label: "Dislocation — Hand / Finger / Wrist",
    templateId: "trauma_msk_dislocation_hand_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.0", "S63.1", "S63.2"],
    keywords: ["finger dislocation", "thumb dislocation", "wrist dislocation", "dislocated finger"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Hand, finger, thumb, and wrist dislocations with splinting and hand surgery or orthopedic follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Finger injuries", "OrthoInfo — Finger dislocation"],
  },
  {
    id: "trauma_dislocation_jaw",
    label: "Dislocation — Jaw / TMJ",
    templateId: "trauma_msk_dislocation_jaw_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S03.0"],
    keywords: ["jaw dislocation", "tmj dislocation", "dislocated jaw"],
    specialtyCategory: "ent",
    riskCategory: "moderate",
    clinicalRationale: "TMJ/jaw dislocation with soft-diet guidance and maxillofacial or ENT follow-up.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Jaw injuries"],
  },
  {
    id: "trauma_dislocation_generic",
    label: "Dislocation — Other Extremity",
    templateId: "trauma_msk_dislocation_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S93.0", "S93.1", "S93.3"],
    keywords: ["ankle dislocation", "foot dislocation", "toe dislocation", "dislocation"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Other extremity dislocations not covered by joint-specific families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Dislocations"],
  },
  {
    id: "trauma_sprain_ankle",
    label: "Sprain — Ankle",
    templateId: "trauma_msk_ankle_sprain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S93.4"],
    keywords: ["ankle sprain", "twisted ankle", "entorse cheville"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Ankle sprain with RICE, bracing, and orthopedic follow-up as needed.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Ankle injuries and sprains", "OrthoInfo — Ankle sprain"],
  },
  {
    id: "trauma_sprain_wrist",
    label: "Sprain — Wrist",
    templateId: "trauma_msk_wrist_sprain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S63.5"],
    keywords: ["wrist sprain", "entorse poignet"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Wrist sprain with immobilization and orthopedic follow-up as needed.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Wrist injuries", "OrthoInfo — Wrist sprains"],
  },
  {
    id: "trauma_sprain_knee",
    label: "Sprain — Knee / Ligament",
    templateId: "trauma_msk_knee_injury_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S83.2", "S83.3", "S83.4", "S83.5", "S83.6", "S83.9"],
    keywords: ["knee sprain", "ligament injury", "acl sprain", "mcl sprain", "entorse genou"],
    specialtyCategory: "orthopedics",
    riskCategory: "moderate",
    clinicalRationale: "Knee sprain and ligament injuries excluding patellar dislocation codes.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Knee injuries", "OrthoInfo — Knee sprains"],
  },
  {
    id: "trauma_sprain_shoulder",
    label: "Sprain / Strain — Shoulder / Rotator Cuff",
    templateId: "trauma_msk_shoulder_pain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S43.4", "S43.5", "S46"],
    keywords: ["shoulder sprain", "shoulder strain", "rotator cuff", "entorse épaule"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Shoulder sprain/strain and rotator-cuff soft-tissue injury (not shoulder dislocation).",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Shoulder injuries", "OrthoInfo — Shoulder pain"],
  },
  {
    id: "trauma_strain_neck",
    label: "Strain — Neck / Cervical",
    templateId: "trauma_msk_neck_strain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S13.4", "S16"],
    keywords: ["neck strain", "cervical strain", "whiplash", "entorse cervicale"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Neck strain with head/neck/spine escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Neck injuries"],
  },
  {
    id: "trauma_strain_back",
    label: "Strain — Back / Lumbar",
    templateId: "trauma_msk_back_strain_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S33.5", "S39.01"],
    icdExact: ["S39.012A", "S39.012"],
    keywords: ["back strain", "lumbar strain", "entorse lombaire", "entorse dos"],
    specialtyCategory: "primary_care",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Back/lumbar strain with spine escalation language.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Back pain"],
  },
  {
    id: "trauma_sprain_generic",
    label: "Sprain / Strain — Other Sites",
    templateId: "trauma_msk_sprain_generic_v1",
    clinicalDomain: "Trauma",
    icdPrefixes: ["S53.3", "S53.4", "S63.3", "S63.4", "S63.6", "S73.1", "S76", "S93.5", "S93.6", "S23.3", "S29"],
    keywords: ["sprain", "strain", "hamstring strain", "groin strain", "entorse", "élongation", "claquage"],
    specialtyCategory: "orthopedics",
    riskCategory: "low_to_moderate",
    clinicalRationale: "Other sprain/strain sites not covered by ankle/wrist/knee/shoulder/neck/back families.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Sprains and strains"],
  },
] as const;
