/**
 * Domain extension families — assign remaining high-volume registry templates for coverage metrics.
 */

import type { ClinicalConditionFamilyDefinition } from "./providerDischargeConditionFamilyTypes";

export const DOMAIN_EXTENSION_CLINICAL_CONDITION_FAMILIES: readonly ClinicalConditionFamilyDefinition[] =
  [
    {
      id: "shortness_of_breath",
      label: "Shortness of Breath",
      templateId: "shortness_of_breath_v1",
      clinicalDomain: "Respiratory",
      icdExact: ["R06.02", "R06.00"],
      icdPrefixes: ["R06"],
      excludeIcdExact: ["R06.2"],
      keywords: ["shortness of breath", "dyspnea", "breathlessness"],
      guardrails: {
        safety: { highRiskEscalation: true, requiresEdReturnPrecautions: true },
      },
      specialtyCategory: "pulmonology",
      riskCategory: "moderate_to_high",
      clinicalRationale: "Dyspnea with respiratory escalation precautions.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Breathing problems"],
    },
    {
      id: "ent_epistaxis",
      label: "Epistaxis",
      templateId: "epistaxis_v1",
      clinicalDomain: "ENT",
      icdExact: ["R04.0"],
      icdPrefixes: ["R04"],
      keywords: ["epistaxis", "nosebleed"],
      specialtyCategory: "primary_care",
      riskCategory: "low_to_moderate",
      clinicalRationale: "Nosebleed discharge and return precautions.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Nosebleed"],
    },
    {
      id: "pediatric_respiratory",
      label: "Pediatric Respiratory (RSV/Croup)",
      templateId: "pediatric_rsv_bronchiolitis_v1",
      additionalTemplateIds: ["pediatric_croup_v1"],
      clinicalDomain: "Respiratory",
      icdPrefixes: ["J21", "J05"],
      keywords: ["pediatric rsv", "pediatric croup", "bronchiolitis"],
      guardrails: { age: { maxAgeYears: 18 } },
      specialtyCategory: "pediatrics",
      riskCategory: "moderate",
      clinicalRationale: "Pediatric lower-airway viral illness with age guardrail.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Bronchiolitis"],
    },
    {
      id: "trauma_msk_sprain_injury",
      label: "Trauma / MSK Soft-Tissue Contusion Fallback",
      templateId: "trauma_msk_contusion_v1",
      additionalTemplateIds: ["trauma_msk_mvc_soreness_v1"],
      clinicalDomain: "Musculoskeletal",
      icdPrefixes: ["S60", "S20"],
      keywords: ["contusion", "bruise", "mvc soreness"],
      specialtyCategory: "orthopedics",
      riskCategory: "low_to_moderate",
      clinicalRationale:
        "Narrow soft-tissue fallback only. Sprain/strain and dislocation routing live in Phase-1 trauma_sprain_* / trauma_dislocation_* families; fracture templates are not mapped here.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Bruises"],
    },
    {
      id: "neurology_stroke_tia",
      label: "Stroke / TIA",
      templateId: "tia_stroke_like_v1",
      clinicalDomain: "Neurologic",
      icdPrefixes: ["G45", "I63"],
      keywords: ["tia", "stroke-like", "transient ischemic attack"],
      guardrails: {
        safety: {
          highRiskEscalation: true,
          requiresEdReturnPrecautions: true,
          requiresSpecialistFollowUp: true,
        },
      },
      specialtyCategory: "neurology",
      riskCategory: "high",
      clinicalRationale:
        "Stroke/TIA high-risk template; excludes R42 vertigo and R51 headache families via prefix exclusions.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Stroke"],
    },
    {
      id: "toxicology_alcohol",
      label: "Toxicology / Alcohol",
      templateId: "alcohol_intoxication_v1",
      clinicalDomain: "Toxicology",
      icdPrefixes: ["F10", "Y91"],
      excludeIcdExact: ["F10.239"],
      excludeIcdPrefixes: ["F10.23"],
      keywords: ["alcohol intoxication", "intoxication"],
      guardrails: {
        safety: { requiresEdReturnPrecautions: true },
      },
      specialtyCategory: "behavioral_health",
      riskCategory: "moderate",
      clinicalRationale:
        "Alcohol intoxication only; withdrawal codes excluded and routed to behavioral health withdrawal template.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Alcohol use disorder"],
    },
    {
      id: "wellness_vaccination",
      label: "Wellness / Vaccination",
      templateId: "wellness_visit_v1",
      additionalTemplateIds: ["vaccination_visit_v1"],
      clinicalDomain: "General Medical",
      icdExact: ["Z00.0", "Z23"],
      icdPrefixes: ["Z00", "Z23"],
      keywords: ["wellness visit", "vaccination", "immunization"],
      specialtyCategory: "primary_care",
      riskCategory: "low",
      clinicalRationale: "Routine wellness and vaccination encounters.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Health checkup"],
    },
    {
      id: "spine_cervical_strain",
      label: "Cervical Strain",
      templateId: "cervical_strain_v1",
      clinicalDomain: "Musculoskeletal",
      // Do not claim S16.1 — trauma_msk_neck_strain_v1 / trauma_strain_neck owns traumatic cervical strain codes.
      keywords: ["cervical muscle strain", "cervical strain"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "low_to_moderate",
      clinicalRationale: "Cervical strain discharge after red-flag screening; does not steal S16.1 neck-strain trauma ownership.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Neck pain"],
    },
    {
      id: "spine_thoracic_strain",
      label: "Thoracic Strain",
      templateId: "thoracic_strain_v1",
      clinicalDomain: "Musculoskeletal",
      keywords: ["thoracic strain"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "low_to_moderate",
      clinicalRationale: "Thoracic strain discharge after red-flag screening.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Back pain"],
    },
    {
      id: "spine_lumbar_strain",
      label: "Lumbar Strain",
      templateId: "lumbar_strain_v1",
      clinicalDomain: "Musculoskeletal",
      // Do not claim S39.012 — trauma back-strain families own traumatic lumbar strain codes.
      keywords: ["lumbar muscle strain", "lumbar strain"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "low_to_moderate",
      clinicalRationale: "Lumbar strain discharge after red-flag screening; does not steal traumatic lumbar strain ownership.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Back pain"],
    },
    {
      id: "spine_mechanical_back_pain",
      label: "Acute Mechanical Back Pain",
      templateId: "acute_mechanical_back_pain_v1",
      clinicalDomain: "Musculoskeletal",
      keywords: ["mechanical back pain"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "low_to_moderate",
      clinicalRationale: "Mechanical back pain without radiculopathy or emergency ownership.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Back pain"],
    },
    {
      id: "spine_cervical_radiculopathy",
      label: "Cervical Radiculopathy",
      templateId: "cervical_radiculopathy_v1",
      clinicalDomain: "Neurologic",
      icdPrefixes: ["M54.12"],
      keywords: ["cervical radiculopathy"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate",
      clinicalRationale: "Cervical radiculopathy guidance with neurologic return precautions.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Neck pain"],
    },
    {
      id: "spine_lumbar_radiculopathy_sciatica",
      label: "Lumbar Radiculopathy / Sciatica",
      templateId: "lumbar_radiculopathy_sciatica_v1",
      clinicalDomain: "Neurologic",
      icdPrefixes: ["M54.1", "M54.3", "M54.4"],
      keywords: ["lumbar radiculopathy", "sciatica"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate",
      clinicalRationale: "Owns sciatica/radiculopathy so generic M54 back-pain families do not steal routing.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Sciatica"],
    },
    {
      id: "spine_disc_herniation",
      label: "Disc Herniation (Conservative)",
      templateId: "disc_herniation_conservative_v1",
      clinicalDomain: "Musculoskeletal",
      icdPrefixes: ["M50", "M51"],
      keywords: ["disc herniation", "herniated disc"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate",
      clinicalRationale: "Conservative disc-related symptom guidance after clinician evaluation.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Herniated disk"],
    },
    {
      id: "spine_spinal_stenosis",
      label: "Spinal Stenosis",
      templateId: "spinal_stenosis_v1",
      clinicalDomain: "Musculoskeletal",
      icdPrefixes: ["M48"],
      keywords: ["spinal stenosis"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate",
      clinicalRationale: "Spinal stenosis symptom guidance with neurologic precautions.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Spinal stenosis"],
    },
    {
      id: "spine_vertebral_compression_fracture",
      label: "Vertebral Compression Fracture",
      templateId: "vertebral_compression_fracture_v1",
      clinicalDomain: "Musculoskeletal",
      keywords: ["vertebral compression fracture"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate_to_high",
      clinicalRationale: "Compression-fracture follow-up after clinician-selected discharge.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Compression fractures"],
    },
    {
      id: "spine_stable_vertebral_fracture",
      label: "Stable Vertebral Fracture Follow-up",
      templateId: "stable_vertebral_fracture_followup_v1",
      clinicalDomain: "Musculoskeletal",
      keywords: ["stable vertebral fracture"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "moderate",
      clinicalRationale: "Stable vertebral fracture follow-up when discharge is explicitly selected.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Compression fractures"],
    },
    {
      id: "spine_post_spinal_trauma",
      label: "Post Spinal Trauma Evaluation",
      templateId: "post_spinal_trauma_evaluation_v1",
      clinicalDomain: "Trauma",
      icdPrefixes: ["S14", "S24", "S34"],
      keywords: ["spinal trauma", "spinal cord injury"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "high",
      clinicalRationale: "Post-evaluation spinal trauma guidance; not routine outpatient SCI discharge.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Spinal cord trauma"],
    },
    {
      id: "spine_post_cauda_red_flag",
      label: "Post Cauda Red-Flag Evaluation",
      templateId: "post_caudal_red_flag_evaluation_v1",
      clinicalDomain: "Neurologic",
      icdExact: ["G83.4"],
      keywords: ["cauda equina"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "high",
      clinicalRationale: "High-visibility cauda red-flag precautions after completed evaluation and provider review.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Cauda equina"],
    },
    {
      id: "spine_infection_followup",
      label: "Spinal Infection Follow-up",
      templateId: "spinal_infection_followup_v1",
      clinicalDomain: "Skin/Infection",
      icdExact: ["G06.1"],
      icdPrefixes: ["M46"],
      keywords: ["spinal infection", "epidural abscess", "discitis", "vertebral osteomyelitis"],
      specialtyCategory: "emergency_medicine",
      riskCategory: "high",
      clinicalRationale: "Used only when the clinician explicitly selects discharge after spinal-infection evaluation; overrides generic back-pain families.",
      reviewStatus: "reviewed",
      routingStatus: "READY",
      sourceReferenceLabels: ["MedlinePlus — Spinal infections"],
    },
  ] as const;

/**
 * Explicit template → family assignments for keyword-only registry templates (coverage metrics).
 */
export const EXPLICIT_REGISTRY_TEMPLATE_FAMILY_MAP: Readonly<Record<string, string>> = {
  shortness_of_breath_v1: "shortness_of_breath",
  epistaxis_v1: "ent_epistaxis",
  pediatric_rsv_bronchiolitis_v1: "pediatric_respiratory",
  pediatric_croup_v1: "pediatric_respiratory",
  trauma_msk_ankle_sprain_v1: "trauma_sprain_ankle",
  trauma_msk_wrist_sprain_v1: "trauma_sprain_wrist",
  trauma_msk_knee_injury_v1: "trauma_sprain_knee",
  trauma_msk_shoulder_pain_v1: "trauma_sprain_shoulder",
  trauma_msk_back_strain_v1: "trauma_strain_back",
  trauma_msk_neck_strain_v1: "trauma_strain_neck",
  trauma_msk_contusion_v1: "trauma_msk_sprain_injury",
  trauma_msk_mvc_soreness_v1: "trauma_msk_sprain_injury",
  trauma_msk_dislocation_shoulder_v1: "trauma_dislocation_shoulder",
  trauma_msk_dislocation_elbow_v1: "trauma_dislocation_elbow",
  trauma_msk_dislocation_hip_v1: "trauma_dislocation_hip",
  trauma_msk_dislocation_patella_v1: "trauma_dislocation_patella",
  trauma_msk_dislocation_hand_v1: "trauma_dislocation_hand",
  trauma_msk_dislocation_jaw_v1: "trauma_dislocation_jaw",
  trauma_msk_dislocation_generic_v1: "trauma_dislocation_generic",
  trauma_msk_sprain_generic_v1: "trauma_sprain_generic",
  trauma_msk_tendon_achilles_v1: "trauma_tendon_achilles",
  trauma_msk_tendon_extensor_mechanism_v1: "trauma_tendon_extensor_mechanism",
  trauma_msk_tendon_shoulder_v1: "trauma_tendon_shoulder",
  trauma_msk_tendon_hand_v1: "trauma_tendon_hand",
  trauma_msk_tendon_generic_v1: "trauma_tendon_generic",
  trauma_msk_ligament_knee_v1: "trauma_ligament_knee",
  trauma_msk_ligament_ankle_v1: "trauma_ligament_ankle",
  trauma_msk_ligament_hand_v1: "trauma_ligament_hand",
  trauma_msk_ligament_upper_extremity_v1: "trauma_ligament_upper_extremity",
  trauma_msk_ligament_shoulder_v1: "trauma_ligament_shoulder",
  trauma_msk_ligament_generic_v1: "trauma_ligament_generic",
  trauma_msk_crush_hand_finger_v1: "trauma_crush_hand_finger",
  trauma_msk_crush_upper_extremity_v1: "trauma_crush_upper_extremity",
  trauma_msk_crush_lower_extremity_v1: "trauma_crush_lower_extremity",
  trauma_msk_crush_foot_toe_v1: "trauma_crush_foot_toe",
  trauma_msk_crush_chest_abdomen_pelvis_v1: "trauma_crush_chest_abdomen_pelvis",
  trauma_msk_crush_prolonged_compression_v1: "trauma_crush_prolonged_compression",
  trauma_msk_crush_degloving_v1: "trauma_crush_degloving",
  trauma_msk_crush_compartment_risk_v1: "trauma_crush_compartment_risk",
  trauma_msk_crush_generic_v1: "trauma_crush_generic",
  trauma_msk_amputation_finger_thumb_v1: "trauma_amputation_finger_thumb",
  trauma_msk_amputation_hand_upper_extremity_v1: "trauma_amputation_hand_upper_extremity",
  trauma_msk_amputation_toe_v1: "trauma_amputation_toe",
  trauma_msk_amputation_foot_lower_extremity_v1: "trauma_amputation_foot_lower_extremity",
  trauma_msk_amputation_partial_v1: "trauma_amputation_partial",
  trauma_msk_amputation_complete_v1: "trauma_amputation_complete",
  trauma_msk_amputation_postoperative_or_followup_v1: "trauma_amputation_postoperative_or_followup",
  trauma_msk_amputation_generic_v1: "trauma_amputation_generic",
  trauma_msk_foreign_body_eye_v1: "trauma_foreign_body_eye",
  trauma_msk_foreign_body_ear_nose_v1: "trauma_foreign_body_ear_nose",
  trauma_msk_foreign_body_skin_soft_tissue_v1: "trauma_foreign_body_skin_soft_tissue",
  trauma_msk_foreign_body_hand_finger_v1: "trauma_foreign_body_hand_finger",
  trauma_msk_foreign_body_foot_toe_v1: "trauma_foreign_body_foot_toe",
  trauma_msk_foreign_body_fishhook_v1: "trauma_foreign_body_fishhook",
  trauma_msk_foreign_body_ingested_v1: "trauma_foreign_body_ingested",
  trauma_msk_foreign_body_aspirated_v1: "trauma_foreign_body_aspirated",
  trauma_msk_foreign_body_retained_fragment_v1: "trauma_foreign_body_retained_fragment",
  trauma_msk_foreign_body_generic_v1: "trauma_foreign_body_generic",
  frostbite_v1: "trauma_burn_frostbite",
  burn_inhalation_aftercare_v1: "trauma_burn_inhalation",
  burn_eye_v1: "trauma_burn_eye",
  burn_chemical_v1: "trauma_burn_chemical",
  burn_electrical_v1: "trauma_burn_electrical",
  sunburn_v1: "trauma_burn_sunburn",
  burn_face_v1: "trauma_burn_face",
  burn_hand_v1: "trauma_burn_hand",
  burn_foot_v1: "trauma_burn_foot",
  burn_full_thickness_followup_v1: "trauma_burn_full_thickness",
  burn_partial_thickness_v1: "trauma_burn_partial_thickness",
  burn_superficial_v1: "trauma_burn_superficial",
  penetrating_wound_minor_v1: "trauma_penetrating_minor",
  gunshot_wound_extremity_v1: "trauma_penetrating_gsw_extremity",
  stab_wound_minor_v1: "trauma_penetrating_stab_minor",
  retained_projectile_v1: "trauma_penetrating_retained_projectile",
  penetrating_hand_injury_v1: "trauma_penetrating_hand",
  penetrating_foot_injury_v1: "trauma_penetrating_foot",
  penetrating_face_v1: "trauma_penetrating_face",
  penetrating_eye_followup_v1: "trauma_penetrating_eye",
  penetrating_chest_v1: "trauma_penetrating_chest",
  penetrating_abdomen_v1: "trauma_penetrating_abdomen",
  penetrating_neck_v1: "trauma_penetrating_neck",
  penetrating_head_v1: "trauma_penetrating_head",
  post_wound_exploration_v1: "trauma_penetrating_minor",
  post_foreign_body_removal_v1: "trauma_penetrating_retained_projectile",
  post_tourniquet_extremity_v1: "trauma_penetrating_gsw_extremity",
  human_bite_v1: "trauma_human_bite",
  fight_bite_v1: "trauma_fight_bite",
  high_risk_hand_wound_v1: "trauma_high_risk_hand_wound",
  contaminated_wound_v1: "trauma_contaminated_wound",
  water_exposed_wound_v1: "trauma_water_exposed_wound",
  delayed_wound_v1: "trauma_delayed_wound",
  deep_contaminated_wound_v1: "trauma_deep_contaminated_wound",
  animal_bite_rabies_followup_v1: "trauma_animal_bite_rabies_followup",
  infected_traumatic_wound_v1: "trauma_infected_traumatic_wound",
  bite_cellulitis_v1: "trauma_bite_cellulitis",
  post_bite_abscess_drainage_v1: "trauma_post_bite_abscess_drainage",
  tetanus_followup_v1: "trauma_tetanus_followup",
  blast_ear_injury_v1: "trauma_blast_ear",
  blast_lung_aftercare_v1: "trauma_blast_lung",
  blast_abdominal_observation_v1: "trauma_blast_abdomen",
  blast_mild_tbi_v1: "trauma_blast_mild_tbi",
  blast_fragment_wound_v1: "trauma_blast_fragment",
  blast_burn_aftercare_v1: "trauma_blast_burn",
  blast_crush_aftercare_v1: "trauma_blast_crush",
  post_structural_collapse_v1: "trauma_blast_collapse",
  polytrauma_followup_v1: "trauma_polytrauma",
  blast_injury_minor_v1: "trauma_blast_minor",
  tia_stroke_like_v1: "neurology_stroke_tia",
  high_risk_medical_fatigue_v1: "generalized_weakness",
  high_risk_medical_dizziness_v1: "dizziness_vertigo",
  high_risk_medical_headache_v1: "headache",
  high_risk_medical_leg_swelling_v1: "dvt_evaluation",
  chest_wall_pain_v1: "chest_pain",
  cardio_chest_pain_low_risk_v1: "chest_pain",
  cardio_afib_rate_controlled_v1: "palpitations",
  cardio_syncope_v1: "syncope",
  cardio_hypertension_elevated_bp_v1: "hypertensive_urgency_followup",
  cardio_heart_failure_symptoms_v1: "chf_exacerbation",
  infectious_fever_unknown_source_v1: "fever",
  infectious_upper_respiratory_infection_v1: "uri_cough",
  infectious_viral_syndrome_v1: "viral_syndrome",
  infectious_pharyngitis_v1: "pharyngitis_tonsillitis",
  infectious_sinusitis_v1: "sinusitis",
  infectious_pneumonia_followup_v1: "pneumonia_lower_respiratory",
  infectious_covid_like_illness_v1: "covid19",
  gi_infectious_gastroenteritis_v1: "gastroenteritis_diarrhea",
  infectious_cellulitis_followup_v1: "cellulitis_skin_infection",
  sepsis_risk_return_precautions_v1: "fever",
  renal_aki_followup_v1: "aki_followup",
  renal_dehydration_followup_v1: "dehydration",
  renal_electrolyte_abnormality_followup_v1: "aki_followup",
  urology_renal_colic_followup_v1: "kidney_stone",
  urology_uti_followup_v1: "uti_urinary_symptoms",
  urology_pyelonephritis_followup_v1: "aki_followup",
  urology_hematuria_followup_v1: "hematuria",
  urology_urinary_retention_followup_v1: "urinary_retention",
  diabetes_sick_day_precautions_v1: "type_2_diabetes_non_acute",
  vaccination_visit_v1: "wellness_vaccination",
  wellness_visit_v1: "wellness_vaccination",
  pediatric_fever_v1: "pediatric_fever",
  pediatric_otitis_media_v1: "pediatric_otitis_media",
  pediatric_viral_syndrome_v1: "viral_syndrome",
  pediatric_uri_v1: "pediatric_uri",
  pediatric_gastroenteritis_v1: "gastroenteritis_diarrhea",
  pediatric_mild_dehydration_v1: "dehydration",
  pediatric_constipation_v1: "constipation",
  pediatric_asthma_exacerbation_v1: "asthma_wheezing",
  pediatric_rash_v1: "pediatric_rash",
  pediatric_minor_head_injury_v1: "minor_head_injury",
  pediatric_febrile_seizure_v1: "seizure",
  pediatric_abdominal_pain_v1: "abdominal_pain",
  pediatric_vomiting_v1: "nausea_vomiting_with_dehydration",
  pediatric_dehydration_escalation_v1: "dehydration",
  pediatric_allergic_reaction_v1: "allergic_reaction",
  pediatric_concussion_v1: "concussion",
  pediatric_wheezing_v1: "asthma_wheezing",
  pediatric_influenza_like_illness_v1: "influenza",
  obgyn_vaginal_bleeding_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_pelvic_pain_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_dysmenorrhea_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_hyperemesis_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_early_pregnancy_symptoms_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_threatened_miscarriage_precautions_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_vaginitis_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_uti_pregnancy_precautions_v1: "uti_urinary_symptoms",
  obgyn_round_ligament_pain_v1: "obgyn_bleeding_pelvic_pain",
  obgyn_postpartum_warning_v1: "obgyn_bleeding_pelvic_pain",
  behavioral_health_anxiety_panic_symptoms_v1: "behavioral_health_crisis",
  behavioral_health_depression_crisis_precautions_v1: "behavioral_health_crisis",
  behavioral_health_suicidal_ideation_precautions_v1: "behavioral_health_crisis",
  behavioral_health_alcohol_intoxication_follow_up_v1: "behavioral_health_crisis",
  behavioral_health_alcohol_withdrawal_precautions_v1: "behavioral_health_crisis",
  behavioral_health_substance_use_resources_v1: "behavioral_health_crisis",
  behavioral_health_opioid_overdose_aftercare_v1: "behavioral_health_crisis",
  behavioral_health_crisis_follow_up_v1: "behavioral_health_crisis",
  behavioral_health_insomnia_stress_reaction_v1: "behavioral_health_crisis",
  behavioral_health_grief_adjustment_v1: "behavioral_health_crisis",
  anxiety_panic_v1: "behavioral_health_crisis",
  alcohol_intoxication_v1: "toxicology_alcohol",
  cervical_strain_v1: "spine_cervical_strain",
  thoracic_strain_v1: "spine_thoracic_strain",
  lumbar_strain_v1: "spine_lumbar_strain",
  acute_mechanical_back_pain_v1: "spine_mechanical_back_pain",
  cervical_radiculopathy_v1: "spine_cervical_radiculopathy",
  lumbar_radiculopathy_sciatica_v1: "spine_lumbar_radiculopathy_sciatica",
  disc_herniation_conservative_v1: "spine_disc_herniation",
  spinal_stenosis_v1: "spine_spinal_stenosis",
  vertebral_compression_fracture_v1: "spine_vertebral_compression_fracture",
  stable_vertebral_fracture_followup_v1: "spine_stable_vertebral_fracture",
  post_spinal_trauma_evaluation_v1: "spine_post_spinal_trauma",
  post_caudal_red_flag_evaluation_v1: "spine_post_cauda_red_flag",
  spinal_infection_followup_v1: "spine_infection_followup",
};
