/** Phase 18 — psychiatric / behavioral condition family domain extensions (Commit 2). */
export const PSYCHIATRIC_BEHAVIORAL_DOMAIN_EXTENSIONS = [
  {
    id: "suicidal_ideation_post_assessment",
    label: "Suicidal ideation post-assessment",
    templateId: "suicidal_ideation_post_assessment_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["R45.851"],
    keywords: ["suicidal ideation post-assessment", "passive suicidal ideation"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for suicidal_ideation_post_assessment_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide"],
  },
  {
    id: "self_harm_post_assessment",
    label: "Self-harm post-assessment",
    templateId: "self_harm_post_assessment_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["Z91.51", "Z91.52"],
    icdPrefixes: ["Z91.51", "Z91.52"],
    keywords: ["NSSI", "non-suicidal self-injury"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for self_harm_post_assessment_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "suicide_attempt_post_acute",
    label: "Suicide attempt post-acute",
    templateId: "suicide_attempt_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["T14.91", "T14.91XA"],
    icdPrefixes: ["T14.91"],
    keywords: ["suicide attempt post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for suicide_attempt_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide"],
  },
  {
    id: "depression_crisis",
    label: "Depression crisis",
    templateId: "depression_crisis_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F32", "F33", "F34", "F39"],
    keywords: ["depression crisis"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for depression_crisis_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Depression"],
  },
  {
    id: "anxiety_panic_crisis",
    label: "Anxiety / panic crisis",
    templateId: "anxiety_panic_crisis_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F40", "F41"],
    keywords: ["panic attack", "anxiety panic crisis"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for anxiety_panic_crisis_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Anxiety"],
  },
  {
    id: "acute_stress_reaction",
    label: "Acute stress reaction",
    templateId: "acute_stress_reaction_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F43"],
    keywords: ["acute stress reaction"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for acute_stress_reaction_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "psychosis_post_acute",
    label: "Psychosis post-acute",
    templateId: "psychosis_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F20", "F21", "F22", "F23", "F24", "F25", "F28", "F29"],
    keywords: ["acute psychosis post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for psychosis_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "mania_post_acute",
    label: "Mania post-acute",
    templateId: "mania_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F30", "F31"],
    keywords: ["mania post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for mania_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "behavioral_agitation_post_acute",
    label: "Behavioral agitation post-acute",
    templateId: "behavioral_agitation_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["R45.1"],
    keywords: ["severe agitation post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for behavioral_agitation_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "substance_induced_behavioral_crisis",
    label: "Substance-induced behavioral crisis",
    templateId: "substance_induced_behavioral_crisis_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F10.15", "F10.25", "F19.15", "F19.25", "F19.95"],
    keywords: ["substance-induced psychosis"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for substance_induced_behavioral_crisis_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Substance use"],
  },
  {
    id: "delirium_post_acute",
    label: "Delirium post-acute",
    templateId: "delirium_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F05", "R41.0", "R41.82"],
    keywords: ["delirium post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for delirium_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "dementia_behavior_change",
    label: "Dementia with behavioral change",
    templateId: "dementia_behavior_change_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F01", "F02", "F03", "R41.3"],
    keywords: ["dementia behavioral change"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for dementia_behavior_change_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "catatonia_post_acute",
    label: "Catatonia post-acute",
    templateId: "catatonia_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["F06.1", "F20.2"],
    keywords: ["catatonia post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for catatonia_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "eating_disorder_medical_followup",
    label: "Eating disorder medical follow-up",
    templateId: "eating_disorder_medical_followup_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F50"],
    keywords: ["anorexia nervosa follow-up"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for eating_disorder_medical_followup_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "pediatric_behavioral_crisis",
    label: "Pediatric behavioral crisis",
    templateId: "pediatric_behavioral_crisis_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F84", "F90", "F91", "F98"],
    keywords: ["autism behavioral crisis", "pediatric behavioral crisis"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for pediatric_behavioral_crisis_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "postpartum_psychiatric_crisis_post_acute",
    label: "Postpartum psychiatric crisis post-acute",
    templateId: "postpartum_psychiatric_crisis_post_acute_v1",
    clinicalDomain: "Behavioral Health",
    icdPrefixes: ["F53"],
    keywords: ["postpartum psychosis post-acute"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for postpartum_psychiatric_crisis_post_acute_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "informed_refusal",
    label: "Informed refusal",
    templateId: "informed_refusal_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["Z53.20", "Z53.2"],
    keywords: ["refusal of treatment", "informed refusal"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for informed_refusal_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "against_medical_advice",
    label: "Against medical advice",
    templateId: "against_medical_advice_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["Z53.9", "Z91.19"],
    keywords: ["against medical advice", "AMA"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for against_medical_advice_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
  {
    id: "behavioral_health_safety_plan",
    label: "Behavioral health safety plan",
    templateId: "behavioral_health_safety_plan_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["Z04.6"],
    keywords: ["behavioral health safety plan"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for behavioral_health_safety_plan_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Suicide"],
  },
  {
    id: "crisis_resource_followup",
    label: "Crisis resource follow-up",
    templateId: "crisis_resource_followup_v1",
    clinicalDomain: "Behavioral Health",
    icdExact: ["Z03.89"],
    icdPrefixes: ["Z75"],
    keywords: ["crisis resource follow-up"],
    specialtyCategory: "behavioral_health",
    riskCategory: "high",
    clinicalRationale: "Phase 18 ownership for crisis_resource_followup_v1.",
    reviewStatus: "reviewed",
    routingStatus: "READY",
    sourceReferenceLabels: ["MedlinePlus — Mental Health"],
  },
] as const;

export const PSYCHIATRIC_BEHAVIORAL_EXPLICIT_TEMPLATE_FAMILY_MAP: Readonly<Record<string, string>> = {
  suicidal_ideation_post_assessment_v1: "suicidal_ideation_post_assessment",
  self_harm_post_assessment_v1: "self_harm_post_assessment",
  suicide_attempt_post_acute_v1: "suicide_attempt_post_acute",
  depression_crisis_v1: "depression_crisis",
  anxiety_panic_crisis_v1: "anxiety_panic_crisis",
  acute_stress_reaction_v1: "acute_stress_reaction",
  psychosis_post_acute_v1: "psychosis_post_acute",
  mania_post_acute_v1: "mania_post_acute",
  behavioral_agitation_post_acute_v1: "behavioral_agitation_post_acute",
  substance_induced_behavioral_crisis_v1: "substance_induced_behavioral_crisis",
  delirium_post_acute_v1: "delirium_post_acute",
  dementia_behavior_change_v1: "dementia_behavior_change",
  catatonia_post_acute_v1: "catatonia_post_acute",
  eating_disorder_medical_followup_v1: "eating_disorder_medical_followup",
  pediatric_behavioral_crisis_v1: "pediatric_behavioral_crisis",
  postpartum_psychiatric_crisis_post_acute_v1: "postpartum_psychiatric_crisis_post_acute",
  informed_refusal_v1: "informed_refusal",
  against_medical_advice_v1: "against_medical_advice",
  behavioral_health_safety_plan_v1: "behavioral_health_safety_plan",
  crisis_resource_followup_v1: "crisis_resource_followup",
};
