import { FhirClinicalService } from "./fhir-clinical.service";

describe("FHIR core clinical projections", () => {
  const refs = { reference: (type:string,id:string) => ({ reference:`${type}/${id}` }), assertVisible: jest.fn().mockResolvedValue(undefined) };
  const search = { parse: jest.fn(), baseUrl: () => "https://fhir.example.test/fhir" };
  const prisma:any = { diagnosis:{findFirst:jest.fn(),findMany:jest.fn()}, orderItem:{findFirst:jest.fn(),findMany:jest.fn()}, result:{findFirst:jest.fn(),findMany:jest.fn()}, encounterCarePlan:{findFirst:jest.fn(),findMany:jest.fn()}, userRole:{findFirst:jest.fn()} };
  const service = new FhirClinicalService(prisma, search as any, refs as any);
  beforeEach(() => jest.clearAllMocks());

  it("scopes Condition read in the database query", async () => { prisma.diagnosis.findFirst.mockResolvedValue(null); await expect(service.read("Condition","facility-a","missing")).rejects.toThrow("Condition not found"); expect(prisma.diagnosis.findFirst).toHaveBeenCalledWith({where:{id:"missing",facilityId:"facility-a"}}); });
  it("does not expose manual diagnosis codes as ICD-10", async () => { prisma.diagnosis.findFirst.mockResolvedValue({id:"d",facilityId:"f",patientId:"p",encounterId:"e",status:"ACTIVE",code:"free",description:null,codeSource:"MANUAL_DECLARED",createdAt:new Date("2026-01-01Z")}); const r:any=await service.read("Condition","f","d"); expect(r.code.coding).toBeUndefined(); expect(r.code.text).toBe("free"); });
  it("exposes catalog diagnoses with the canonical ICD system", async () => { prisma.diagnosis.findFirst.mockResolvedValue({id:"d",patientId:"p",encounterId:"e",status:"ACTIVE",code:"A00",description:"Cholera",codeSource:"ICD10_CATALOG",createdAt:new Date("2026-01-01Z")}); const r:any=await service.read("Condition","f","d"); expect(r.code.coding[0]).toMatchObject({system:"http://hl7.org/fhir/sid/icd-10-cm",code:"A00"}); });
  it("excludes medication items from ServiceRequest reads", async () => { prisma.orderItem.findFirst.mockResolvedValue(null); await expect(service.read("ServiceRequest","f","med")).rejects.toThrow(); expect(prisma.orderItem.findFirst.mock.calls[0][0].where).toMatchObject({catalogItemType:{in:["LAB_TEST","IMAGING_STUDY"]},order:{facilityId:"f"}}); });
  it("never serializes diagnostic resultData or attachment URLs", async () => { prisma.result.findFirst.mockResolvedValue({id:"r",facilityId:"f",orderItemId:"i",resultText:"Normal",resultData:{attachments:[{url:"s3://secret"}]},createdAt:new Date("2026-01-01Z"),verifiedAt:new Date("2026-01-02Z"),orderItem:{id:"i",status:"COMPLETED",catalogItemType:"IMAGING_STUDY",catalogItemId:null,manualLabel:"Chest",order:{patientId:"p",encounterId:"e"}}}); const r:any=await service.read("DiagnosticReport","f","r"); expect(JSON.stringify(r)).not.toContain("s3://"); expect(r.basedOn).toEqual([{reference:"ServiceRequest/i"}]); });
  it("uses only a verified same-facility membership for CarePlan author", async () => { prisma.encounterCarePlan.findFirst.mockResolvedValue({id:"c",patientId:"p",encounterId:"e",activatedByUserId:"u",title:"Plan",status:"ACTIVE",activatedAt:new Date("2026-01-01Z"),createdAt:new Date("2026-01-01Z"),components:[]}); prisma.userRole.findFirst.mockResolvedValue(null); const r:any=await service.read("CarePlan","f","c"); expect(r.author).toBeUndefined(); expect(prisma.userRole.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({facilityId:"f",userId:"u",isActive:true})})); });
  it("filters confirmed Conditions canonically before pagination", async () => { search.parse.mockReturnValue({count:1,values:{"verification-status":"confirmed"}}); prisma.diagnosis.findMany.mockResolvedValue([]); await service.find("Condition","f",{"verification-status":"confirmed",_count:"1"}); expect(prisma.diagnosis.findMany.mock.calls[0][0].where.status).toEqual({in:["ACTIVE","RESOLVED"]}); });
  it("filters DiagnosticReport status in Prisma before pagination", async () => { search.parse.mockReturnValue({count:1,values:{status:"final"}}); prisma.result.findMany.mockResolvedValue([]); await service.find("DiagnosticReport","f",{status:"final",_count:"1"}); expect(prisma.result.findMany.mock.calls[0][0].where).toMatchObject({verifiedAt:{not:null},orderItem:{status:{not:"CANCELLED"}}}); });
});
