import { INestApplication } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import { CarePlanStatus, DiagnosisCodeSource, EncounterStatus, EncounterType, OrderStatus, RoleCode } from "@prisma/client";
import * as argon2 from "argon2";
import { randomBytes } from "crypto";
import * as request from "supertest";
import { AppModule } from "../app.module";
import { PrismaService } from "../prisma/prisma.service";
import { closeE2eApp, createE2eApp } from "../test-utils/e2e-app";
import { applyE2eAuthTestEnv, assertE2eLoginAccessToken } from "../test-utils/e2e-auth-env";

jest.setTimeout(120_000);

type ResourceFixture = { observation: string; condition: string; lab: string; imaging: string; report: string; carePlan: string };

describe("P0.3C FHIR PostgreSQL clinical tenant and role security (e2e)", () => {
  let app: INestApplication; let moduleRef: TestingModule; let prisma: PrismaService;
  const suffix = randomBytes(5).toString("hex"); const password = "Test123!";
  let facilityA = ""; let facilityB = ""; let patientA = ""; let patientB = ""; let encounterA = ""; let encounterB = "";
  let triageA = ""; let triageB = ""; let medicationItemA = ""; let noteA = "";
  const users: Record<string,string> = {}; const userRoles: string[] = []; const tokens: Partial<Record<RoleCode,string>> = {};
  const a = {} as ResourceFixture; const b = {} as ResourceFixture;
  const auth = (role: RoleCode = RoleCode.PROVIDER) => ({ Authorization: `Bearer ${tokens[role]}`, "x-facility-id": facilityA, Accept: "application/fhir+json" });
  const resources = () => ([
    ["Observation", a.observation, b.observation, `?subject=Patient/${patientA}`],
    ["Condition", a.condition, b.condition, `?patient=Patient/${patientA}`],
    ["ServiceRequest", a.lab, b.lab, `?patient=Patient/${patientA}`],
    ["DiagnosticReport", a.report, b.report, `?patient=Patient/${patientA}`],
    ["CarePlan", a.carePlan, b.carePlan, `?patient=Patient/${patientA}`],
  ] as const);

  beforeAll(async () => {
    applyE2eAuthTestEnv(); process.env.MEDORA_INTEROP_ENABLED = "true"; process.env.FHIR_PUBLIC_BASE_URL = "https://fhir.test.example/fhir";
    moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile(); app = await createE2eApp(moduleRef); prisma = moduleRef.get(PrismaService);
    const [fa,fb] = await Promise.all([prisma.facility.create({data:{code:`C-A-${suffix}`,name:"Clinical A",country:"US",timezone:"UTC"}}),prisma.facility.create({data:{code:`C-B-${suffix}`,name:"Clinical B",country:"US",timezone:"UTC"}})]); facilityA=fa.id;facilityB=fb.id;
    for (const roleCode of [RoleCode.FRONT_DESK,RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN]) {
      const role=await prisma.role.upsert({where:{code:roleCode},update:{},create:{code:roleCode,name:roleCode}});
      const user=await prisma.user.create({data:{email:`${roleCode.toLowerCase()}+${suffix}@clinical.test`,firstName:roleCode,lastName:"Tester",passwordHash:await argon2.hash(password)}}); users[roleCode]=user.id;
      const membership=await prisma.userRole.create({data:{userId:user.id,roleId:role.id,facilityId:facilityA,professionCode:roleCode==="PROVIDER"?"PROVIDER_UNSPECIFIED":roleCode}}); userRoles.push(membership.id);
      const login=await request(app.getHttpServer()).post("/auth/login").send({username:user.email,password}).expect(201); tokens[roleCode]=assertE2eLoginAccessToken(login.body,user.email);
    }
    const providerRole=await prisma.role.findUniqueOrThrow({where:{code:RoleCode.PROVIDER}}); const foreign=await prisma.user.create({data:{email:`foreign+${suffix}@clinical.test`,firstName:"Foreign",lastName:"Provider",passwordHash:await argon2.hash(password)}}); users.foreign=foreign.id;
    userRoles.push((await prisma.userRole.create({data:{userId:foreign.id,roleId:providerRole.id,facilityId:facilityB,professionCode:"PROVIDER_UNSPECIFIED"}})).id);
    const [pa,pb]=await Promise.all([prisma.patient.create({data:{facilityId:facilityA,registeredAtFacilityId:facilityA,firstName:"Alpha",lastName:"Patient",globalMrn:`CGA-${suffix}`,mrn:`CA-${suffix}`}}),prisma.patient.create({data:{facilityId:facilityB,registeredAtFacilityId:facilityB,firstName:"Beta",lastName:"Patient",globalMrn:`CGB-${suffix}`,mrn:`CB-${suffix}`}})]);patientA=pa.id;patientB=pb.id;
    const [ea,eb]=await Promise.all([prisma.encounter.create({data:{facilityId:facilityA,patientId:patientA,type:EncounterType.OUTPATIENT,status:EncounterStatus.OPEN}}),prisma.encounter.create({data:{facilityId:facilityB,patientId:patientB,type:EncounterType.OUTPATIENT,status:EncounterStatus.OPEN}})]);encounterA=ea.id;encounterB=eb.id;
    const [ta,tb]=await Promise.all([prisma.triage.create({data:{facilityId:facilityA,encounterId:encounterA}}),prisma.triage.create({data:{facilityId:facilityB,encounterId:encounterB}})]);triageA=ta.id;triageB=tb.id;
    const measuredA=new Date("2026-08-01T10:11:12.000Z"); const [va,vb]=await Promise.all([prisma.triageVitalsReading.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,triageId:triageA,vitalsJson:{tempC:37.2,hr:81},measuredAt:measuredA}}),prisma.triageVitalsReading.create({data:{facilityId:facilityB,patientId:patientB,encounterId:encounterB,triageId:triageB,vitalsJson:{tempC:39.1},measuredAt:new Date("2026-08-02T10:11:12.000Z")}})]);a.observation=`reading-${va.id}-8310-5`;b.observation=`reading-${vb.id}-8310-5`;
    const [da,db]=await Promise.all([prisma.diagnosis.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,code:"A00",description:"Cholera",codeSource:DiagnosisCodeSource.ICD10_CATALOG}}),prisma.diagnosis.create({data:{facilityId:facilityB,patientId:patientB,encounterId:encounterB,code:"B00",description:"Foreign diagnosis",codeSource:DiagnosisCodeSource.MANUAL_DECLARED}})]);a.condition=da.id;b.condition=db.id;
    const oa=await prisma.order.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,type:"LAB",status:OrderStatus.PENDING,orderedBy:users.PROVIDER,items:{create:[{catalogItemType:"LAB_TEST",manualLabel:"CBC"},{catalogItemType:"IMAGING_STUDY",manualLabel:"Chest X-ray"},{catalogItemType:"MEDICATION",manualLabel:"Not a service request"}]}} ,include:{items:true}});
    const ob=await prisma.order.create({data:{facilityId:facilityB,patientId:patientB,encounterId:encounterB,type:"LAB",status:OrderStatus.PENDING,orderedBy:users.foreign,items:{create:[{catalogItemType:"LAB_TEST",manualLabel:"Foreign CBC"},{catalogItemType:"IMAGING_STUDY",manualLabel:"Foreign image"}]}} ,include:{items:true}});
    a.lab=oa.items[0]!.id;a.imaging=oa.items[1]!.id;medicationItemA=oa.items[2]!.id;b.lab=ob.items[0]!.id;b.imaging=ob.items[1]!.id;
    const [ra,rb]=await Promise.all([prisma.result.create({data:{facilityId:facilityA,orderItemId:a.lab,resultText:"Normal",resultData:{attachments:[{url:"s3://internal-secret"}],structured:{value:12}},verifiedAt:new Date("2026-08-03T10:00:00Z")}}),prisma.result.create({data:{facilityId:facilityB,orderItemId:b.lab,resultText:"Foreign",resultData:{url:"s3://foreign-secret"}}})]);a.report=ra.id;b.report=rb.id;
    const [ca,cb]=await Promise.all([prisma.encounterCarePlan.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,templateId:"fixture",templateVersion:"1",templateSnapshotJson:{version:1},title:"Canonical plan",status:CarePlanStatus.ACTIVE,activatedByUserId:users.PROVIDER}}),prisma.encounterCarePlan.create({data:{facilityId:facilityB,patientId:patientB,encounterId:encounterB,templateId:"fixture",templateVersion:"1",templateSnapshotJson:{version:1},title:"Foreign plan",status:CarePlanStatus.ACTIVE,activatedByUserId:users.foreign}})]);a.carePlan=ca.id;b.carePlan=cb.id;
    noteA=(await prisma.encounterNote.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,noteType:"OTHER",body:"Not a care plan",authorUserId:users.PROVIDER,authorDisplayNameSnapshot:"Provider",authorRoleSnapshot:"PROVIDER"}})).id;
  });

  afterAll(async()=>{try{if(prisma){await prisma.auditLog.deleteMany({where:{facilityId:{in:[facilityA,facilityB]}}});await prisma.encounterNote.deleteMany({where:{id:noteA}});await prisma.encounterCarePlan.deleteMany({where:{id:{in:[a.carePlan,b.carePlan]}}});await prisma.result.deleteMany({where:{id:{in:[a.report,b.report]}}});await prisma.order.deleteMany({where:{facilityId:{in:[facilityA,facilityB]},createdAt:{gte:new Date("2026-01-01")}}});await prisma.diagnosis.deleteMany({where:{id:{in:[a.condition,b.condition]}}});await prisma.triageVitalsReading.deleteMany({where:{triageId:{in:[triageA,triageB]}}});await prisma.triage.deleteMany({where:{id:{in:[triageA,triageB]}}});await prisma.encounter.deleteMany({where:{id:{in:[encounterA,encounterB]}}});await prisma.patient.deleteMany({where:{id:{in:[patientA,patientB]}}});await prisma.userRole.deleteMany({where:{id:{in:userRoles}}});await prisma.user.deleteMany({where:{id:{in:Object.values(users)}}});await prisma.facility.deleteMany({where:{id:{in:[facilityA,facilityB]}}})}}finally{await closeE2eApp({app,moduleRef,prisma})}});

  it("C-E2E-01 tenant-scopes every clinical read/search and references",async()=>{const missing="00000000-0000-4000-8000-000000000000";for(const [type,idA,idB,search] of resources()){const own=await request(app.getHttpServer()).get(`/fhir/${type}/${idA}`).set(auth()).expect(200);expect(JSON.stringify(own.body)).not.toContain(patientB);const foreign=await request(app.getHttpServer()).get(`/fhir/${type}/${idB}`).set(auth()).expect(404);const absent=await request(app.getHttpServer()).get(`/fhir/${type}/${type==="Observation"?`reading-${missing}-8310-5`:missing}`).set(auth()).expect(404);expect(foreign.body).toEqual(absent.body);const bundle=await request(app.getHttpServer()).get(`/fhir/${type}${search}`).set(auth()).expect(200);const wire=JSON.stringify(bundle.body);expect(wire).toContain(idA);expect(wire).not.toMatch(new RegExp([idB,patientB,encounterB].join("|")));expect(bundle.body).not.toHaveProperty("total");expect(bundle.body.link?.find((l:any)=>l.relation==="self")?.url).toMatch(/^https:\/\/fhir\.test\.example\/fhir\//)}});
  it("C-E2E-02 uses stable measured Observation identity and tenant-safe pagination",async()=>{const read=await request(app.getHttpServer()).get(`/fhir/Observation/${a.observation}`).set(auth()).expect(200);expect(read.body.id).toBe(a.observation);expect(read.body.effectiveDateTime).toBe("2026-08-01T10:11:12.000Z");const page=await request(app.getHttpServer()).get(`/fhir/Observation?patient=Patient/${patientA}&_count=1`).set(auth()).expect(200);const next=page.body.link.find((l:any)=>l.relation==="next")?.url;expect(next).toBeTruthy();expect(next).not.toContain(patientB);const cursor=new URL(next).searchParams.get("_cursor");const page2=await request(app.getHttpServer()).get(`/fhir/Observation?patient=Patient/${patientA}&_count=1&_cursor=${cursor}`).set(auth()).expect(200);expect(JSON.stringify(page2.body)).not.toContain(patientB)});
  it("C-E2E-03 excludes medication and storage payloads and maps only real CarePlan",async()=>{await request(app.getHttpServer()).get(`/fhir/ServiceRequest/${medicationItemA}`).set(auth()).expect(404);const requests=await request(app.getHttpServer()).get(`/fhir/ServiceRequest?patient=Patient/${patientA}`).set(auth()).expect(200);expect(JSON.stringify(requests.body)).not.toContain(medicationItemA);expect(requests.body.entry.every((entry:any)=>entry.resource.requester.reference===`Practitioner/${users.PROVIDER}`)).toBe(true);const report=await request(app.getHttpServer()).get(`/fhir/DiagnosticReport/${a.report}`).set(auth()).expect(200);expect(JSON.stringify(report.body)).not.toMatch(/resultData|s3:\/\/|internal-secret/);const plans=await request(app.getHttpServer()).get(`/fhir/CarePlan?patient=Patient/${patientA}`).set(auth()).expect(200);expect(JSON.stringify(plans.body)).toContain(a.carePlan);expect(JSON.stringify(plans.body)).not.toContain(noteA)});
  it("C-E2E-04 returns sanitized errors, 405 writes, and no-store",async()=>{for(const type of ["Observation","Condition","ServiceRequest","DiagnosticReport","CarePlan"]){const bad=await request(app.getHttpServer()).get(`/fhir/${type}?patient=Organization/${facilityA}`).set(auth()).expect(400);expect(bad.body).toEqual(expect.objectContaining({resourceType:"OperationOutcome",issue:[expect.objectContaining({diagnostics:"Invalid FHIR request"})]}));for(const method of ["post","put","patch","delete"] as const){const write=await request(app.getHttpServer())[method](`/fhir/${type}/${(a as any)[type==="Observation"?"observation":type==="Condition"?"condition":type==="ServiceRequest"?"lab":type==="DiagnosticReport"?"report":"carePlan"]}`).set(auth()).send({}).expect(405);expect(write.body.resourceType).toBe("OperationOutcome")}const read=await request(app.getHttpServer()).get(`/fhir/${type}/${(a as any)[type==="Observation"?"observation":type==="Condition"?"condition":type==="ServiceRequest"?"lab":type==="DiagnosticReport"?"report":"carePlan"]}`).set(auth()).expect(200);expect(read.headers["cache-control"]).toBe("no-store")}});
  it("C-E2E-05 enforces FRONT_DESK denial and RN/PROVIDER/ADMIN access",async()=>{for(const [type,id] of resources().map(([t,id])=>[t,id] as const)){await request(app.getHttpServer()).get(`/fhir/${type}/${id}`).set(auth(RoleCode.FRONT_DESK)).expect(403);for(const role of [RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN])await request(app.getHttpServer()).get(`/fhir/${type}/${id}`).set(auth(role)).expect(200)}});
  it("C-E2E-06 keeps registry, metadata, routes, and allergy/no-write capabilities aligned",async()=>{const metadata=await request(app.getHttpServer()).get("/fhir/metadata").set("Accept","application/fhir+json").expect(200);const entries=metadata.body.rest[0].resource;for(const type of ["Observation","Condition","ServiceRequest","DiagnosticReport","CarePlan"]){const resource=entries.find((r:any)=>r.type===type);expect(resource.interaction.map((i:any)=>i.code).sort()).toEqual(["read","search-type"]);await request(app.getHttpServer()).get(`/fhir/${type}`).set(auth()).expect(type==="Observation"?400:200)}expect(entries.find((r:any)=>r.type==="AllergyIntolerance")).toBeUndefined();await request(app.getHttpServer()).get("/fhir/AllergyIntolerance").set(auth()).expect(404)});
  it("C-E2E-07 filters logical pages before cursors and audits only successful same-tenant Observation access",async()=>{
    const ids=Array.from({length:55},(_,i)=>`10000000-0000-4000-8000-${String(i).padStart(12,"0")}`); const measuredAt=new Date("2026-08-04T10:00:00Z");
    await prisma.triageVitalsReading.createMany({data:ids.map((id,i)=>({id,facilityId:facilityA,patientId:patientA,encounterId:encounterA,triageId:triageA,vitalsJson:i>=53?{weightKg:72}:{tempC:36.5},measuredAt}))});
    try {
      const page=await request(app.getHttpServer()).get(`/fhir/Observation?patient=Patient/${patientA}&code=29463-7&_count=1`).set(auth()).expect(200); expect(page.body.entry).toHaveLength(1); expect(page.body.entry[0].resource.id).toBe(`reading-${ids[53]}-29463-7`);
      const next=page.body.link.find((link:any)=>link.relation==="next").url; expect(next).not.toContain(facilityB); const cursor=new URL(next).searchParams.get("_cursor");
      const page2=await request(app.getHttpServer()).get(`/fhir/Observation?patient=Patient/${patientA}&code=29463-7&_count=1&_cursor=${cursor}`).set(auth()).expect(200); expect(page2.body.entry.map((entry:any)=>entry.resource.id)).toEqual([`reading-${ids[54]}-29463-7`]);
      await request(app.getHttpServer()).get(`/fhir/Observation/reading-${ids[54]}-29463-7`).set({...auth(),"user-agent":"p03c-audit-test"}).expect(200); const readAudit=await prisma.auditLog.findFirst({where:{facilityId:facilityA,userId:users.PROVIDER,entityId:ids[54],entityType:"TRIAGE_VITALS_READING"},orderBy:{createdAt:"desc"}}); expect(readAudit).toMatchObject({patientId:patientA,encounterId:encounterA,userAgent:"p03c-audit-test",metadata:expect.objectContaining({interaction:"read",resourceType:"Observation"})});
      const audit=await prisma.auditLog.findFirst({where:{facilityId:facilityA,userId:users.PROVIDER,entityId:ids[53],entityType:"TRIAGE_VITALS_READING"},orderBy:{createdAt:"desc"}}); expect(audit).toMatchObject({patientId:patientA,encounterId:encounterA,ip:expect.any(String)}); expect(audit?.metadata).not.toEqual(expect.objectContaining({weightKg:expect.anything(),value:expect.anything()}));
      const before=await prisma.auditLog.count({where:{facilityId:facilityA,entityType:"TRIAGE_VITALS_READING"}}); await request(app.getHttpServer()).get(`/fhir/Observation/${b.observation}`).set(auth()).expect(404); expect(await prisma.auditLog.count({where:{facilityId:facilityA,entityType:"TRIAGE_VITALS_READING"}})).toBe(before);
    } finally { await prisma.triageVitalsReading.deleteMany({where:{id:{in:ids}}}); }
  });
  it("C-E2E-08 applies Condition verification and DiagnosticReport status before logical pagination",async()=>{
    const conditions=await Promise.all(["ACTIVE","RESOLVED","REMOVED"].map((status,i)=>prisma.diagnosis.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,code:`VERIFY-${i}`,codeSource:DiagnosisCodeSource.MANUAL_DECLARED,status:status as any}})));
    const order=await prisma.order.create({data:{facilityId:facilityA,patientId:patientA,encounterId:encounterA,type:"LAB",status:OrderStatus.PENDING,orderedBy:users.PROVIDER,items:{create:Array.from({length:55},()=>({catalogItemType:"LAB_TEST",manualLabel:"Pagination test"}))}},include:{items:true}});
    const resultIds=Array.from({length:55},(_,i)=>`20000000-0000-4000-8000-${String(i).padStart(12,"0")}`); await prisma.result.createMany({data:resultIds.map((id,i)=>({id,facilityId:facilityA,orderItemId:order.items[i]!.id,resultText:"pagination",createdAt:new Date("2026-08-05T10:00:00Z"),verifiedAt:i===54?new Date("2026-08-05T10:00:00Z"):null}))});
    try { const confirmed=await request(app.getHttpServer()).get(`/fhir/Condition?patient=Patient/${patientA}&verification-status=confirmed&_count=50`).set(auth()).expect(200); const ids=confirmed.body.entry.map((entry:any)=>entry.resource.id); expect(ids).toEqual(expect.arrayContaining([conditions[0].id,conditions[1].id])); expect(ids).not.toContain(conditions[2].id);
      const reports=await request(app.getHttpServer()).get(`/fhir/DiagnosticReport?patient=Patient/${patientA}&date=2026-08-05&status=final&_count=1`).set(auth()).expect(200); expect(reports.body.entry.map((entry:any)=>entry.resource.id)).toEqual([resultIds[54]]);
    } finally { await prisma.result.deleteMany({where:{id:{in:resultIds}}}); await prisma.order.delete({where:{id:order.id}}); await prisma.diagnosis.deleteMany({where:{id:{in:conditions.map(c=>c.id)}}}); }
  });
});
