import { Controller, Get, Header, Param, Query, Req, UseFilters, UseGuards, UseInterceptors } from "@nestjs/common";
import { AuthGuard } from "@nestjs/passport";
import { RoleCode } from "@prisma/client";
import { RequireRoles, RolesGuard } from "../common/guards/roles.guard";
import { FhirCapabilityGuard, RequireFhirCapability } from "./fhir-capability.guard";
import { FhirContextGuard, FhirDeploymentGuard, FhirRequestContext } from "./fhir-context.guard";
import { FhirMediaInterceptor } from "./fhir-media.interceptor";
import { FhirOperationOutcomeFilter } from "./fhir-operation-outcome.filter";
import { ClinicalResourceType, FhirClinicalService } from "./fhir-clinical.service";
type Request = { fhirContext: FhirRequestContext };
const guards = [FhirDeploymentGuard, AuthGuard("jwt"), RolesGuard, FhirContextGuard, FhirCapabilityGuard];
abstract class ClinicalController { abstract readonly resourceType: ClinicalResourceType; constructor(protected readonly clinical:FhirClinicalService){} search(q:Record<string,unknown>,r:Request){return this.clinical.find(this.resourceType,r.fhirContext.facilityId,q)} read(id:string,r:Request){return this.clinical.read(this.resourceType,r.fhirContext.facilityId,id)} }
function secure(target:Function){UseGuards(...guards)(target);UseFilters(FhirOperationOutcomeFilter)(target);UseInterceptors(FhirMediaInterceptor)(target)}
@Controller("fhir/Condition") export class FhirConditionController extends ClinicalController {readonly resourceType="Condition" as const; @Get() @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("Condition","search-type") find(@Query()q:Record<string,unknown>,@Req()r:Request){return this.search(q,r)} @Get(":id") @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("Condition","read") get(@Param("id")id:string,@Req()r:Request){return this.read(id,r)}} secure(FhirConditionController);
@Controller("fhir/ServiceRequest") export class FhirServiceRequestController extends ClinicalController {readonly resourceType="ServiceRequest" as const; @Get() @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("ServiceRequest","search-type") find(@Query()q:Record<string,unknown>,@Req()r:Request){return this.search(q,r)} @Get(":id") @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("ServiceRequest","read") get(@Param("id")id:string,@Req()r:Request){return this.read(id,r)}} secure(FhirServiceRequestController);
@Controller("fhir/DiagnosticReport") export class FhirDiagnosticReportController extends ClinicalController {readonly resourceType="DiagnosticReport" as const; @Get() @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("DiagnosticReport","search-type") find(@Query()q:Record<string,unknown>,@Req()r:Request){return this.search(q,r)} @Get(":id") @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("DiagnosticReport","read") get(@Param("id")id:string,@Req()r:Request){return this.read(id,r)}} secure(FhirDiagnosticReportController);
@Controller("fhir/CarePlan") export class FhirCarePlanController extends ClinicalController {readonly resourceType="CarePlan" as const; @Get() @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("CarePlan","search-type") find(@Query()q:Record<string,unknown>,@Req()r:Request){return this.search(q,r)} @Get(":id") @Header("Content-Type","application/fhir+json; charset=utf-8") @RequireRoles(RoleCode.RN,RoleCode.PROVIDER,RoleCode.ADMIN) @RequireFhirCapability("CarePlan","read") get(@Param("id")id:string,@Req()r:Request){return this.read(id,r)}} secure(FhirCarePlanController);
