export const DIGITAL_CARE_PERMISSIONS = [
  "portal.self.read",
  "portal.self.manage",
  "portal.operational.read",
  "communication.self.read",
  "communication.self.write",
  "communication.assigned.read",
  "communication.assigned.write",
  "notifications.self.read",
  "notifications.self.manage",
  "telemedicine.self.join",
  "telemedicine.assigned.manage",
  "education.self.read",
  "education.assigned.manage",
  "questionnaires.self.read",
  "questionnaires.self.submit",
  "questionnaires.assigned.manage",
  "monitoring.self.read",
  "monitoring.assigned.read",
  "monitoring.assigned.manage",
  "consent.self.read",
  "consent.self.sign",
  "consent.assigned.manage",
  "proxy.self.read",
  "proxy.self.manage",
  "proxy.patient.act",
  "ai.self.use",
  "ai.assigned.assist",
  "quality.metadata.read",
  "digital-care.configure",
  "digital-care.cross-scope",
] as const;

export type DigitalCarePermission =
  (typeof DIGITAL_CARE_PERMISSIONS)[number];
