/** MEDUI.ES.1K — Display-only Spanish for clinical documentation hub cards. Not stored. */
export const CLINICAL_DOCUMENTATION_CARD_DISPLAY_ES: Record<string, { title: string; description: string }> = {
  "flow_cpr_record": { title: "Registro de RCP", description: "Registro de RCP" },
  "flow_procedural_sedation": { title: "Sedación para procedimientos", description: "Sedación para procedimientos" },
  "flow_restraint_monitoring": { title: "Vigilancia de sujeción", description: "Vigilancia de sujeción" },
  "flow_respiratory_therapy": { title: "Registro de terapia respiratoria", description: "Registro de terapia respiratoria" },
  "flow_blood_product_administration": { title: "Administración de hemoderivados", description: "Administración de hemoderivados" },
  "flow_thrombolytic_stroke": { title: "Terapia trombolítica — ACV", description: "Terapia trombolítica — ACV" },
  "flow_thrombolytic_mi": { title: "Terapia trombolítica — IAM", description: "Terapia trombolítica — IAM" },
  "flow_neuro_checks": { title: "Controles neurológicos", description: "Controles neurológicos" },
  "flow_telemetry_monitoring": { title: "Vigilancia de telemetría", description: "Vigilancia de telemetría" },
  "flow_cardiac_monitoring": { title: "Vigilancia cardíaca", description: "Vigilancia cardíaca" },
  "flow_sepsis_monitoring": { title: "Vigilancia de sepsis", description: "Vigilancia de sepsis" },
  "flow_observation_monitoring": { title: "Vigilancia de observación", description: "Vigilancia de observación" },
  "score_nihss": { title: "NIHSS", description: "NIH Stroke Scale." },
  "score_cincinnati_stroke": { title: "Escala de ACV de Cincinnati", description: "Escala de ACV de Cincinnati" },
  "score_van": { title: "Evaluación VAN", description: "Evaluación VAN" },
  "score_abcd2": { title: "Puntuación ABCD2", description: "Puntuación ABCD2" },
  "score_qsofa": { title: "qSOFA", description: "qSOFA" },
  "score_sirs": { title: "SIRS", description: "SIRS" },
  "score_sepsis_screen": { title: "Cribado de sepsis", description: "Institutional sepsis screening." },
  "score_ciwa_ar": { title: "CIWA-Ar", description: "CIWA-Ar" },
  "score_cows": { title: "COWS", description: "Clinical Opiate Withdrawal Scale." },
  "score_cssrs": { title: "C-SSRS / Riesgo de suicidio", description: "C-SSRS / Riesgo de suicidio" },
  "score_phq9": { title: "PHQ-9", description: "Paciente Health Questionnaire-9." },
  "score_gad7": { title: "GAD-7", description: "Generalized Anxiety Disorder-7." },
  "score_gcs": { title: "Escala de coma de Glasgow", description: "Escala de coma de Glasgow." },
  "score_rts": { title: "Puntuación de trauma revisada", description: "Puntuación de trauma revisada." },
  "score_heart": { title: "Puntuación HEART", description: "HEART pathway chest pain risk." },
  "score_wells_pe": { title: "Wells EP", description: "Wells criteria for pulmonary embolism." },
  "score_perc": { title: "PERC", description: "PERC rule for PE." },
  "score_geneva": { title: "Puntuación de Ginebra", description: "Puntuación de Ginebra" },
  "score_fall_risk": { title: "Cribado de riesgo de caída", description: "Fall risk screening tool." },
  "score_abuse": { title: "Cribado de maltrato", description: "Abuse / IPV screening." },
  "score_human_trafficking": { title: "Cribado de trata de personas", description: "Human trafficking screening." },
  "score_sdoh": { title: "Determinantes sociales de la salud", description: "SDOH screening." },
  "io_intake_output": { title: "Ingresos y egresos", description: "Ingresos y egresos" },
  "io_fluid_intake": { title: "Ingreso de líquidos", description: "Ingreso de líquidos" },
  "io_po_intake": { title: "Ingreso VO", description: "Ingreso VO" },
  "io_iv_intake": { title: "Ingreso IV", description: "Intravenous fluid intake." },
  "io_blood_product_intake": { title: "Ingreso de hemoderivados", description: "Blood product volume as intake." },
  "io_urine_output": { title: "Egreso urinario", description: "Urine output measurement." },
  "io_stool_output": { title: "Egreso de heces", description: "Egreso de heces" },
  "io_emesis_output": { title: "Egreso por vómito", description: "Egreso por vómito" },
  "io_ng_output": { title: "Egreso NG", description: "Nasogastric drainage output." },
  "io_drain_output": { title: "Egreso por drenaje", description: "Surgical drain output." },
  "belongings_inventory": { title: "Inventario de pertenencias", description: "Inventario de pertenencias" },
  "valuables_inventory": { title: "Inventario de objetos de valor", description: "Inventario de objetos de valor" },
  "belongings_secured_bagged": { title: "Pertenencias aseguradas / embolsadas", description: "Pertenencias aseguradas / embolsadas" },
  "belongings_transfer_security": { title: "Traslado a seguridad", description: "Traslado a seguridad" },
  "belongings_release_representative": { title: "Entrega a familia / representante", description: "Entrega a familia / representante" },
  "belongings_return_patient": { title: "Devolución al paciente", description: "Devolución al paciente" },
  "belongings_altered_patient": { title: "Pertenencias — paciente inconsciente / alterado", description: "Two-staff inventory for patients unable to participate." },
  "safety_restraint_initial": { title: "Inicio de sujeción", description: "Inicio de sujeción" },
  "safety_restraint_reassessment": { title: "Reevaluación de sujeción", description: "Reevaluación de sujeción" },
  "restraint_face_to_face": { title: "Evaluación presencial", description: "Provider face-to-face evaluation for behavioral/violent restraints." },
  "restraint_renewal": { title: "Renovación de sujeción", description: "Provider renewal of restraint order." },
  "restraint_discontinuation": { title: "Suspensión de sujeción", description: "Suspensión de sujeción" },
  "safety_fall_precautions": { title: "Precauciones de caída", description: "Fall precaution checklist." },
  "safety_suicide_precautions": { title: "Precauciones de suicidio", description: "Precauciones de suicidio" },
  "safety_elopement_risk": { title: "Riesgo de fuga", description: "Riesgo de fuga" },
  "safety_behavioral_observation": { title: "Observación conductual", description: "Behavioral / psychiatric observation log." },
  "safety_belongings_checklist": { title: "Paciente Belongings Lista de verificación", description: "Paciente belongings inventory." },
  "suicide_precautions_documentation": { title: "Precauciones de suicidio Documentación", description: "Precauciones de suicidio Documentación" },
  "suicide_risk_monitoring": { title: "Riesgo de suicidio Vigilancia", description: "Riesgo de suicidio Vigilancia" },
  "elopement_risk_assessment": { title: "Riesgo de fuga Evaluación", description: "Riesgo de fuga Evaluación" },
  "elopement_monitoring": { title: "Vigilancia de fuga", description: "Vigilancia de fuga" },
  "behavioral_observation": { title: "Observación conductual", description: "Observación conductual" },
  "agitation_violence_risk_assessment": { title: "Riesgo de agitación / violencia Evaluación", description: "Riesgo de agitación / violencia Evaluación" },
  "one_to_one_observation_check": { title: "Observación 1:1 / verificación de acompañante", description: "Observación 1:1 / verificación de acompañante" },
  "environmental_safety_check": { title: "Verificación de seguridad ambiental", description: "Verificación de seguridad ambiental" },
  "behavioral_escalation_event": { title: "Escalada conductual Evento", description: "Escalada conductual Evento" },
  "peripheral_iv_assessment": { title: "IV periférica Evaluación", description: "IV periférica Evaluación" },
  "central_line_assessment": { title: "Línea central Evaluación", description: "Línea central Evaluación" },
  "picc_midline_assessment": { title: "PICC / línea media Evaluación", description: "PICC / línea media Evaluación" },
  "foley_catheter_monitoring": { title: "Sonda Foley Vigilancia", description: "Sonda Foley Vigilancia" },
  "external_urinary_device_monitoring": { title: "Dispositivo urinario externo Vigilancia", description: "Dispositivo urinario externo Vigilancia" },
  "ng_og_tube_monitoring": { title: "Sonda NG / OG Vigilancia", description: "Sonda NG / OG Vigilancia" },
  "chest_tube_monitoring": { title: "Drenaje torácico Vigilancia", description: "Drenaje torácico Vigilancia" },
  "surgical_drain_monitoring": { title: "Drenaje quirúrgico Vigilancia", description: "Drenaje quirúrgico Vigilancia" },
  "endotracheal_tube_monitoring": { title: "Tubo endotraqueal Vigilancia", description: "Tubo endotraqueal Vigilancia" },
  "tracheostomy_monitoring": { title: "Traqueostomía Vigilancia", description: "Traqueostomía Vigilancia" },
  "sepsis_screening": { title: "Cribado de sepsising", description: "Cribado de sepsising" },
  "sirs_assessment": { title: "Evaluación SIRS", description: "Evaluación SIRS" },
  "qsofa_assessment": { title: "Evaluación qSOFA", description: "Evaluación qSOFA" },
  "suspected_infection_assessment": { title: "Infección sospechada Evaluación", description: "Infección sospechada Evaluación" },
  "sepsis_bundle_tracking": { title: "Seguimiento del paquete de sepsis", description: "Seguimiento del paquete de sepsis" },
  "lactate_monitoring": { title: "Lactato Vigilancia", description: "Lactato value reference — lab remains source of truth." },
  "blood_culture_documentation": { title: "Hemocultivo Documentación", description: "Blood culture collection reference — lab/specimen source of truth." },
  "antibiotic_timing_reference": { title: "Tiempos de antibióticos Referencia", description: "Antibiotic timing MAR reference — MAR remains source of truth." },
  "fluid_resuscitation_monitoring": { title: "Reanimación con líquidos Vigilancia", description: "Reanimación con líquidos Vigilancia" },
  "septic_shock_reassessment": { title: "Choque séptico Reevaluación", description: "Choque séptico Reevaluación" },
  "sepsis_escalation_event": { title: "Sepsis Escalada Evento", description: "Sepsis Escalada Evento" },
  "nursing_admission_assessment": { title: "Enfermería Admisión Evaluación", description: "Enfermería Admisión Evaluación" },
  "nursing_shift_assessment": { title: "Enfermería Evaluación de turno", description: "Enfermería Evaluación de turno" },
  "head_to_toe_assessment": { title: "De cabeza a pies Evaluación", description: "De cabeza a pies Evaluación" },
  "systems_assessment": { title: "Por sistemas Evaluación", description: "Por sistemas Evaluación" },
  "nursing_care_plan_initiation": { title: "Plan de cuidados Inicio", description: "Plan de cuidados Inicio" },
  "nursing_care_plan_update": { title: "Plan de cuidados Actualización", description: "Plan de cuidados Actualización" },
  "nursing_patient_goals_outcomes": { title: "Objetivos / resultados del paciente", description: "Objetivos / resultados del paciente" },
  "nursing_problem_list": { title: "Lista de problemas de enfermería", description: "Lista de problemas de enfermería" },
  "nursing_handoff_shift_report": { title: "Traspaso / reporte de turno", description: "Traspaso / reporte de turno" },
  "nursing_discharge_readiness_review": { title: "Revisión de enfermería de aptitud para el alta", description: "Revisión de enfermería de aptitud para el alta" },
  "skin_integrity_assessment": { title: "Integridad cutánea Evaluación", description: "Integridad cutánea Evaluación" },
  "braden_risk_assessment": { title: "Riesgo Braden Evaluación", description: "Riesgo Braden Evaluación" },
  "pressure_injury_assessment": { title: "Lesión por presión Evaluación", description: "Lesión por presión Evaluación" },
  "pressure_injury_reassessment": { title: "Lesión por presión Reevaluación", description: "Seguimiento reassessment of existing pressure injury." },
  "surgical_wound_assessment": { title: "Herida quirúrgica Evaluación", description: "Herida quirúrgica Evaluación" },
  "traumatic_wound_assessment": { title: "Herida traumática Evaluación", description: "Herida traumática Evaluación" },
  "skin_tear_assessment": { title: "Desgarro cutáneo Evaluación", description: "Desgarro cutáneo Evaluación" },
  "masd_assessment": { title: "MASD Evaluación", description: "MASD Evaluación" },
  "ostomy_assessment": { title: "Estoma Evaluación", description: "Estoma Evaluación" },
  "wound_treatment_documentation": { title: "Tratamiento de herida Documentación", description: "Tratamiento de herida Documentación" },
  "wound_photo_reference": { title: "Foto de herida Referencia", description: "Wound photography reference ID only — no image storage." },
  "wound_reassessment": { title: "Wound Reevaluación", description: "Wound Reevaluación" },
  "dialysis_access_assessment": { title: "Acceso de diálisis Evaluación", description: "Acceso de diálisis Evaluación" },
  "hemodialysis_monitoring_reference": { title: "Hemodiálisis Vigilancia Referencia", description: "Hemodiálisis Vigilancia Referencia" },
  "peritoneal_dialysis_monitoring_reference": { title: "Diálisis peritoneal Vigilancia Referencia", description: "Diálisis peritoneal Vigilancia Referencia" },
  "crrt_monitoring_reference": { title: "TRRC Vigilancia Referencia", description: "TRRC Vigilancia Referencia" },
  "renal_intake_output_review": { title: "Ingresos/egresos renales Revisión", description: "Ingresos/egresos renales Revisión" },
  "fluid_restriction_monitoring": { title: "Restricción hídrica Vigilancia", description: "Restricción hídrica Vigilancia" },
  "daily_weight_edema_monitoring": { title: "Peso diario y edema Vigilancia", description: "Peso diario y edema Vigilancia" },
  "urine_output_concern": { title: "Egreso urinario Preocupación", description: "Egreso urinario Preocupación" },
  "renal_medication_safety_review": { title: "Seguridad medicamentosa renal Revisión", description: "Seguridad medicamentosa renal Revisión" },
  "renal_escalation_event": { title: "Escalada renal Evento", description: "Escalada renal Evento" },
  "patient_education_session": { title: "Paciente Educación Sesión", description: "Paciente Educación Sesión" },
  "caregiver_education_session": { title: "Cuidador Educación Sesión", description: "Cuidador Educación Sesión" },
  "medication_education_review": { title: "Medicación Educación Revisión", description: "Medicación Educación Revisión" },
  "discharge_instruction_review": { title: "Alta Indicación Revisión", description: "Alta Indicación Revisión" },
  "teach_back_verification": { title: "Teach-back Verificación", description: "Teach-back Verificación" },
  "follow_up_review": { title: "Seguimiento Revisión", description: "Seguimiento Revisión" },
  "equipment_education": { title: "Equipo Educación", description: "Equipo Educación" },
  "disease_specific_education": { title: "Específica de la enfermedad Educación", description: "Específica de la enfermedad Educación" },
  "learning_barrier_assessment": { title: "Barrera de aprendizaje Evaluación", description: "Barrera de aprendizaje Evaluación" },
  "education_refusal_or_inability": { title: "Educación Rechazo o imposibilidad", description: "Educación Rechazo o imposibilidad" },
  "resp_oxygen_therapy": { title: "Oxigenoterapia", description: "Legacy oxygen delivery card (superseded by initiation/titration cards)." },
  "resp_nebulizer": { title: "Tratamiento con nebulizador", description: "Legacy nebulizer card (superseded by nebulizer reassessment)." },
  "resp_assessment": { title: "Evaluación respiratoria", description: "Evaluación respiratoria" },
  "oxygen_therapy_initiation": { title: "Oxigenoterapia Inicio", description: "Oxigenoterapia Inicio" },
  "oxygen_titration": { title: "Titulación de oxígeno / cambio de dispositivo", description: "Titulación de oxígeno / cambio de dispositivo" },
  "nebulizer_reassessment": { title: "Tratamiento con nebulizador Reevaluación", description: "Post-nebulizer reassessment (MAR reference only, not administration)." },
  "resp_cpap_bipap": { title: "CPAP / BiPAP Vigilancia", description: "CPAP / BiPAP Vigilancia" },
  "respiratory_distress_reassessment": { title: "Respiratory Distress Reevaluación", description: "Respiratory Distress Reevaluación" },
  "resp_ventilator": { title: "Observación de ventilador", description: "Foundation ventilator observation (not full ventilator flowsheet)." },
  "resp_peak_flow": { title: "Peak Flow Documentación", description: "Peak Flow Documentación" },
  "resp_incentive_spirometry": { title: "Espirometría incentivada", description: "Espirometría incentivada" },
  "pain_initial_assessment": { title: "Initial Pain Evaluación", description: "Initial Pain Evaluación" },
  "pain_reassessment": { title: "Pain Reevaluación", description: "Pain Reevaluación" },
  "pain_post_intervention_reassessment": { title: "Post-Intervention Pain Reevaluación", description: "Post-Intervention Pain Reevaluación" },
  "chronic_pain_assessment": { title: "Chronic Pain Evaluación", description: "Chronic Pain Evaluación" },
  "adult_nonverbal_pain_assessment": { title: "Adult Non-Verbal Pain Evaluación", description: "Adult Non-Verbal Pain Evaluación" },
  "pediatric_pain_assessment": { title: "Pediatric Pain Evaluación (FLACC)", description: "Pediatric Pain Evaluación (FLACC)" },
  "pain_escalation_event": { title: "Pain Escalada Evento", description: "Pain Escalada Evento" },
  "morse_fall_risk_assessment": { title: "Morse Fall Risk Evaluación", description: "Morse Fall Risk Evaluación" },
  "fall_risk_reassessment": { title: "Fall Risk Reevaluación", description: "Fall Risk Reevaluación" },
  "safety_precautions_documentation": { title: "Safety Precauciones Documentación", description: "Safety Precauciones Documentación" },
  "mobility_ambulation_assessment": { title: "Mobility & Ambulation Evaluación", description: "Mobility & Ambulation Evaluación" },
  "near_fall_event": { title: "Near-Fall Evento", description: "Near-Fall Evento" },
  "fall_event_documentation": { title: "Fall Evento Documentación", description: "Fall Evento Documentación" },
  "post_fall_assessment": { title: "Post-Fall Evaluación", description: "Post-Fall Evaluación" },
  "fall_escalation_event": { title: "Fall Escalada Evento", description: "Fall Escalada Evento" },
  "neurological_initial_assessment": { title: "Initial Neurological Evaluación", description: "Initial Neurological Evaluación" },
  "neurological_reassessment": { title: "Neurological Reevaluación", description: "Neurological Reevaluación" },
  "glasgow_coma_scale_assessment": { title: "Escala de coma de Glasgow Evaluación", description: "Escala de coma de Glasgow Evaluación" },
  "stroke_alert_event": { title: "Stroke Alert Evento", description: "Stroke Alert Evento" },
  "nihss_assessment": { title: "NIH Stroke Scale Evaluación", description: "NIH Stroke Scale Evaluación" },
  "seizure_event_documentation": { title: "Seizure Evento Documentación", description: "Seizure Evento Documentación" },
  "neurological_post_thrombolytic_monitoring": { title: "Post-Thrombolytic Vigilancia", description: "Post-Thrombolytic Vigilancia" },
  "neurological_escalation_event": { title: "Neurological Escalada Evento", description: "Neurological Escalada Evento" },
  "blood_product_verification": { title: "Blood Product Verificación", description: "Blood Product Verificación" },
  "blood_product_initiation": { title: "Blood Product Inicio", description: "Blood Product Inicio" },
  "blood_product_pre_assessment": { title: "Blood Product Pre-Evaluación", description: "Blood Product Pre-Evaluación" },
  "blood_product_reassessment": { title: "Blood Product Reevaluación (15-Minute Verificación)", description: "Blood Product Reevaluación (15-Minute Verificación)" },
  "blood_product_reaction": { title: "Transfusion Reaction Evaluación", description: "Transfusion Reaction Evaluación" },
  "blood_product_completion": { title: "Finalización de hemoderivado", description: "Finalización de hemoderivado" },
  "massive_transfusion_protocol_event": { title: "Massive Transfusion Protocol Evento", description: "Massive Transfusion Protocol Evento" },
  "high_alert_infusion_verification": { title: "High-Alert Infusion Verificación", description: "High-Alert Infusion Verificación" },
  "high_alert_infusion_initiation": { title: "High-Alert Infusion Inicio", description: "" },
  "high_alert_infusion_titration": { title: "Infusion Titration Verificación", description: "Infusion Titration Verificación" },
  "high_alert_infusion_reassessment": { title: "High-Alert Infusion Reevaluación", description: "High-Alert Infusion Reevaluación" },
  "high_alert_infusion_hold": { title: "Pausa / suspensión de infusión", description: "Pausa / suspensión de infusión" },
  "high_alert_infusion_completion": { title: "Finalización de infusión de alta alerta", description: "Finalización de infusión de alta alerta" },
  "stroke_nihss": { title: "NIHSS", description: "NIHSS within stroke pathway." },
  "stroke_swallow_screen": { title: "Swallow Cribado", description: "Bedside swallow screening." },
  "stroke_cincinnati": { title: "Escala de ACV de Cincinnati", description: "Cincinnati Prehospital Stroke Scale." },
  "stroke_van_assessment": { title: "Evaluación VAN", description: "VAN large-vessel occlusion screening." },
  "stroke_abcd2": { title: "Puntuación ABCD2", description: "Puntuación ABCD2" },
  "stroke_tnk": { title: "Administración de TNK", description: "Administración de TNK" },
  "stroke_tpa": { title: "Administración de tPA", description: "Administración de tPA" },
  "stroke_reassessment": { title: "Stroke Reevaluación", description: "Interval stroke reassessment." },
  "stroke_neuro_checks": { title: "Controles neurológicos", description: "Stroke-specific neuro checks." },
  "stroke_timeline": { title: "Línea de tiempo de ACV", description: "Stroke pathway timeline milestones." },
  "nihss_reassessment": { title: "NIHSS Reevaluación", description: "NIHSS Reevaluación" },
  "neuro_checks": { title: "Controles neurológicos", description: "Structured repeatable neuro checks (LOC, orientation, speech, sensation)." },
  "glasgow_coma_scale": { title: "Escala de coma de Glasgow", description: "Escala de coma de Glasgow" },
  "pupillary_assessment": { title: "Pupillary Evaluación", description: "Pupillary Evaluación" },
  "motor_strength_assessment": { title: "Motor Strength Evaluación", description: "Motor Strength Evaluación" },
  "neuro_escalation_event": { title: "Neuro Escalada Evento", description: "Neuro Escalada Evento" },
  "post_thrombolytic_monitoring": { title: "Post-Thrombolytic Vigilancia", description: "Post-Thrombolytic Vigilancia" },
  "frequent_neuro_reassessment": { title: "Frequent Reevaluación Hoja de registro", description: "Scheduled neuro reassessment flowsheet (q15–q2h)." },
  "cardiac_ekg_12_lead": { title: "ECG de 12 derivaciones", description: "ECG de 12 derivaciones" },
  "cardiac_rhythm_strip": { title: "Tira de ritmo ECG", description: "Tira de ritmo ECG" },
  "cardiac_continuous_monitoring": { title: "Continuous Vigilancia cardíaca", description: "Continuous Vigilancia cardíaca" },
  "cardiac_telemetry_initiation": { title: "Telemetry Inicio", description: "Telemetry initiation checklist." },
  "cardiac_telemetry_discontinuation": { title: "Telemetry Suspensión", description: "Telemetry Suspensión" },
  "continuous_cardiac_monitoring": { title: "Continuous Vigilancia cardíaca", description: "Continuous Vigilancia cardíaca" },
  "telemetry_reassessment": { title: "Telemetry Reevaluación", description: "Telemetry Reevaluación" },
  "arrhythmia_event": { title: "Arrhythmia Evento", description: "Arrhythmia Evento" },
  "rhythm_strip_documentation": { title: "Rhythm Strip Documentación", description: "Rhythm Strip Documentación" },
  "ecg_12_lead_documentation": { title: "ECG 12-Lead Documentación", description: "ECG 12-Lead Documentación" },
  "chest_pain_reassessment": { title: "Chest Pain Reevaluación", description: "Chest Pain Reevaluación" },
  "stemi_alert_event": { title: "STEMI Alert Evento", description: "STEMI Alert Evento" },
  "cardiac_escalation_event": { title: "Cardiac Escalada Evento", description: "Cardiac Escalada Evento" },
  "pacemaker_monitoring": { title: "Pacemaker Vigilancia", description: "Pacemaker Vigilancia" },
  "qtc_monitoring": { title: "QTc Vigilancia", description: "QTc Vigilancia" },
  "edoc_basic_structured_v1": { title: "Registro estructurado — básico", description: "Registro estructurado — básico" },
  "obs_po_challenge": { title: "Prueba de tolerancia VO", description: "Prueba de tolerancia VO" },
  "obs_ambulation_trial": { title: "Prueba de deambulación", description: "Ambulation trial for discharge readiness." },
  "obs_reassessment": { title: "Observation Reevaluación", description: "Structured observation reassessment." },
  "obs_discharge_readiness": { title: "Alta Readiness", description: "Observation discharge readiness checklist." },
  "obs_boarding": { title: "Boarding Documentación", description: "Boarding Documentación" },
  "proc_foley_monitoring": { title: "Foley Vigilancia", description: "Foley Vigilancia" },
  "proc_chest_tube": { title: "Drenaje torácico Vigilancia", description: "Drenaje torácico Vigilancia" },
  "proc_central_line": { title: "Línea central Vigilancia", description: "Línea central Vigilancia" },
  "proc_lumbar_puncture": { title: "Lumbar Puncture Vigilancia", description: "Lumbar Puncture Vigilancia" },
  "proc_sedation_monitoring": { title: "Sedación para procedimientos Vigilancia", description: "Sedación para procedimientos Vigilancia" },
  "proc_intubation_monitoring": { title: "Intubation Vigilancia", description: "Intubation Vigilancia" },
  "proc_timeout": { title: "Time-out de procedimiento", description: "Universal protocol procedure timeout." },
  "sedation_pre_assessment": { title: "Pre-Sedation Evaluación", description: "Pre-Sedation Evaluación" },
  "sedation_timeout": { title: "Time-out de sedación", description: "Time-out de sedación" },
  "sedation_initiation": { title: "Sedation Inicio", description: "Sedation Inicio" },
  "sedation_monitoring": { title: "Sedation Vigilancia", description: "Sedation Vigilancia" },
  "sedation_reassessment": { title: "Sedation Reevaluación", description: "Structured sedation reassessment." },
  "sedation_recovery_score": { title: "Puntuación de recuperación de sedación", description: "Aldrete-style structured recovery scoring." },
  "sedation_recovery_monitoring": { title: "Sedation Recovery Vigilancia", description: "Sedation Recovery Vigilancia" },
  "sedation_discharge_readiness": { title: "Post-Sedation Alta Readiness", description: "Post-Sedation Alta Readiness" },
};

export const CLINICAL_DOCUMENTATION_CATEGORY_DISPLAY_ES: Record<string, { title: string; description: string }> = {
  "FLOWSHEETS": { title: "Hojas de registro", description: "Hojas de registro" },
  "SCORES_AND_SCREENS": { title: "Puntuaciones y cribados", description: "Puntuaciones y cribados" },
  "INTAKE_OUTPUT": { title: "Ingresos y egresos", description: "Ingresos y egresos" },
  "SAFETY_DOCUMENTATION": { title: "Documentación de seguridad", description: "" },
  "BEHAVIORAL_HEALTH_DOCUMENTATION": { title: "Documentación de salud conductual", description: "Oxygen, nebulizers, ventilator, CPAP/BiPAP." },
  "RESPIRATORY_DOCUMENTATION": { title: "Documentación respiratoria", description: "Oxygen, nebulizers, ventilator, CPAP/BiPAP." },
  "BLOOD_PRODUCT_DOCUMENTATION": { title: "Documentación de hemoderivados", description: "Documentación de hemoderivados" },
  "HIGH_ALERT_INFUSION_DOCUMENTATION": { title: "Documentación de infusión de alta alerta", description: "Documentación de infusión de alta alerta" },
  "STROKE_DOCUMENTATION": { title: "Documentación de ACV", description: "Documentación de ACV" },
  "CARDIAC_MONITORING_DOCUMENTATION": { title: "Documentación de vigilancia cardíaca", description: "Documentación de vigilancia cardíaca" },
  "OBSERVATION_DOCUMENTATION": { title: "Documentación de observación", description: "Short-stay observation workflows (PO challenge, ambulation, readiness)." },
  "RESTRAINT_DOCUMENTATION": { title: "Documentación de sujeción", description: "Restraint initiation, face-to-face, reassessment, renewal, discontinuation." },
  "BELONGINGS_VALUABLES_DOCUMENTATION": { title: "Pertenencias y objetos de valor del paciente", description: "Pertenencias y objetos de valor del paciente" },
  "PROCEDURE_MONITORING": { title: "Vigilancia de procedimientos", description: "Vigilancia de procedimientos" },
  "PAIN_DOCUMENTATION": { title: "Documentación del dolor", description: "Documentación del dolor" },
  "NEUROLOGICAL_DOCUMENTATION": { title: "Documentación neurológica", description: "Documentación neurológica" },
  "FALL_RISK_AND_SAFETY": { title: "Riesgo de caída y seguridad", description: "Riesgo de caída y seguridad" },
  "DEVICE_LINE_TUBE_DRAIN_MONITORING": { title: "Vigilancia de dispositivos, líneas, sondas y drenajes", description: "Vigilancia de dispositivos, líneas, sondas y drenajes" },
  "SEPSIS_MONITORING_DOCUMENTATION": { title: "Documentación de vigilancia de sepsis", description: "" },
  "NURSING_ADMISSION_AND_CARE_PLAN": { title: "Admisión de enfermería y plan de cuidados", description: "" },
  "SKIN_WOUND_PRESSURE_INJURY": { title: "Integridad cutánea, cuidado de heridas y lesión por presión", description: "" },
  "DIALYSIS_RENAL_FLUID_MANAGEMENT": { title: "Diálisis, vigilancia renal y manejo de líquidos", description: "" },
  "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING": { title: "Educación del paciente e indicaciones de alta", description: "" },
};
