import type {
  ClinicalDocumentationCard,
  ClinicalDocumentationCategory,
  ClinicalDocumentationCategoryMeta,
  ClinicalDocumentationCareSetting,
  ClinicalDocumentationImplementationStatus,
  ClinicalDocumentationRole,
} from "./clinicalDocumentationTypes.js";

export {
  CLINICAL_DOCUMENTATION_CATEGORIES,
  CLINICAL_DOCUMENTATION_CARE_SETTINGS,
  CLINICAL_DOCUMENTATION_ROLES,
  CLINICAL_DOCUMENTATION_IMPLEMENTATION_STATUSES,
  CLINICAL_DOCUMENTATION_CARD_STATUSES,
} from "./clinicalDocumentationTypes.js";

export type {
  ClinicalDocumentationCard,
  ClinicalDocumentationCategory,
  ClinicalDocumentationCategoryMeta,
  ClinicalDocumentationCareSetting,
  ClinicalDocumentationRole,
  ClinicalDocumentationImplementationStatus,
  ClinicalDocumentationCardStatus,
} from "./clinicalDocumentationTypes.js";

const ED_OBS: ClinicalDocumentationCareSetting[] = ["ED", "OBSERVATION"];
const ED_INPATIENT: ClinicalDocumentationCareSetting[] = ["ED", "OBSERVATION", "INPATIENT", "ICU", "TELEMETRY"];
const ALL_SETTINGS: ClinicalDocumentationCareSetting[] = [
  "ED",
  "OBSERVATION",
  "INPATIENT",
  "ICU",
  "TELEMETRY",
  "CLINIC",
  "URGENT_CARE",
];

function card(
  input: Omit<ClinicalDocumentationCard, "status" | "implementationStatus"> & {
    implementationStatus?: ClinicalDocumentationImplementationStatus;
    status?: ClinicalDocumentationCard["status"];
  }
): ClinicalDocumentationCard {
  return {
    status: input.status ?? "PLACEHOLDER",
    implementationStatus: input.implementationStatus ?? "FOUNDATION_ONLY",
    ...input,
  };
}

export const CLINICAL_DOCUMENTATION_CATEGORY_META: readonly ClinicalDocumentationCategoryMeta[] = [
  {
    id: "FLOWSHEETS",
    titleEn: "Flowsheets",
    titleFr: "Feuilles de suivi",
    descriptionEn: "Time-series clinical flowsheets (CPR, sedation, restraints, monitoring).",
    descriptionFr: "Feuilles de suivi clinique (RCP, sédation, contention, surveillance).",
  },
  {
    id: "SCORES_AND_SCREENS",
    titleEn: "Scores & Screens",
    titleFr: "Scores et dépistages",
    descriptionEn: "Validated scores and screening tools.",
    descriptionFr: "Scores validés et outils de dépistage.",
  },
  {
    id: "INTAKE_OUTPUT",
    titleEn: "Intake & Output",
    titleFr: "Entrées et sorties",
    descriptionEn: "Fluid balance and intake/output documentation.",
    descriptionFr: "Bilan hydrique et documentation entrées / sorties.",
  },
  {
    id: "SAFETY_DOCUMENTATION",
    titleEn: "Safety Documentation",
    titleFr: "Documentation sécurité",
    descriptionEn: "Restraints, falls, suicide precautions, belongings.",
    descriptionFr: "Contention, chutes, précautions suicide, effets personnels.",
  },
  {
    id: "RESPIRATORY_DOCUMENTATION",
    titleEn: "Respiratory Documentation",
    titleFr: "Documentation respiratoire",
    descriptionEn: "Oxygen, nebulizers, ventilator, CPAP/BiPAP.",
    descriptionFr: "Oxygène, nébulisations, ventilation, CPAP/BiPAP.",
  },
  {
    id: "BLOOD_PRODUCT_DOCUMENTATION",
    titleEn: "Blood Product Documentation",
    titleFr: "Documentation produits sanguins",
    descriptionEn: "Transfusion and blood product administration.",
    descriptionFr: "Transfusion et administration de produits sanguins.",
  },
  {
    id: "STROKE_DOCUMENTATION",
    titleEn: "Stroke Documentation",
    titleFr: "Documentation AVC",
    descriptionEn: "Stroke pathway scores, thrombolytics, neuro checks.",
    descriptionFr: "Scores voie AVC, thrombolyse, contrôles neurologiques.",
  },
  {
    id: "CARDIAC_MONITORING_DOCUMENTATION",
    titleEn: "Cardiac Monitoring Documentation",
    titleFr: "Documentation surveillance cardiaque",
    descriptionEn: "EKG, rhythm strips, telemetry, continuous monitoring.",
    descriptionFr: "ECG, bandes rythmiques, télémétrie, surveillance continue.",
  },
  {
    id: "OBSERVATION_DOCUMENTATION",
    titleEn: "Observation Documentation",
    titleFr: "Documentation observation",
    descriptionEn: "Short-stay observation workflows (PO challenge, ambulation, readiness).",
    descriptionFr: "Parcours observation courte (épreuve PO, marche, aptitude sortie).",
  },
  {
    id: "PROCEDURE_MONITORING",
    titleEn: "Procedure Monitoring",
    titleFr: "Surveillance procédure",
    descriptionEn: "Post-procedure and device monitoring flows.",
    descriptionFr: "Surveillance post-procédure et dispositifs.",
  },
];

const FLOWSHEET_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "flow_cpr_record",
    titleEn: "CPR Record",
    titleFr: "Feuille RCP",
    category: "FLOWSHEETS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.cpr",
    repeatable: true,
    tags: ["resuscitation", "code"],
    searchAliases: ["CPR", "code blue", "RCP", "réanimation"],
    descriptionEn: "Cardiopulmonary resuscitation flow record.",
    descriptionFr: "Feuille de réanimation cardio-pulmonaire.",
  }),
  card({
    id: "flow_procedural_sedation",
    titleEn: "Procedural Sedation",
    titleFr: "Sédation procédurale",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.proceduralSedation",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["sedation"],
    searchAliases: ["procedural sedation", "sédation procédurale"],
    descriptionEn: "Sedation monitoring during procedures.",
    descriptionFr: "Surveillance sédation pendant procédures.",
  }),
  card({
    id: "flow_restraint_monitoring",
    titleEn: "Restraint Monitoring",
    titleFr: "Surveillance contention",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.restraintMonitoring",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["restraint", "safety"],
    searchAliases: ["restraint", "contention"],
    descriptionEn: "Ongoing restraint reassessment flow.",
    descriptionFr: "Feuille de réévaluation contention.",
  }),
  card({
    id: "flow_respiratory_therapy",
    titleEn: "Respiratory Therapy Record",
    titleFr: "Feuille thérapie respiratoire",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RT",
    legalChartSection: "clinicalDocumentation.flowsheets.respiratoryTherapy",
    repeatable: true,
    tags: ["respiratory", "RT"],
    searchAliases: ["respiratory therapy", "RT record", "thérapie respiratoire"],
    descriptionEn: "Respiratory therapy treatment flow.",
    descriptionFr: "Suivi des traitements de thérapie respiratoire.",
  }),
  card({
    id: "flow_blood_product_administration",
    titleEn: "Blood Product Administration",
    titleFr: "Administration produit sanguin",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.bloodProduct",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["transfusion", "blood"],
    searchAliases: ["blood product", "transfusion", "produit sanguin"],
    descriptionEn: "Blood product administration flow.",
    descriptionFr: "Feuille d'administration produit sanguin.",
  }),
  card({
    id: "flow_thrombolytic_stroke",
    titleEn: "Thrombolytic Therapy — Stroke",
    titleFr: "Thrombolyse — AVC",
    category: "FLOWSHEETS",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.thrombolyticStroke",
    repeatable: false,
    tags: ["stroke", "tPA", "TNK"],
    searchAliases: ["stroke thrombolytic", "tPA stroke", "AVC thrombolyse"],
    descriptionEn: "Stroke thrombolytic administration flow.",
    descriptionFr: "Feuille thrombolyse AVC.",
  }),
  card({
    id: "flow_thrombolytic_mi",
    titleEn: "Thrombolytic Therapy — MI",
    titleFr: "Thrombolyse — IDM",
    category: "FLOWSHEETS",
    careSettings: ["ED", "INPATIENT", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.thrombolyticMi",
    repeatable: false,
    tags: ["STEMI", "MI"],
    searchAliases: ["MI thrombolytic", "STEMI", "IDM thrombolyse"],
    descriptionEn: "Myocardial infarction thrombolytic flow.",
    descriptionFr: "Feuille thrombolyse infarctus.",
  }),
  card({
    id: "flow_neuro_checks",
    titleEn: "Neuro Checks",
    titleFr: "Contrôles neurologiques",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.neuroChecks",
    repeatable: true,
    tags: ["neuro"],
    searchAliases: ["neuro checks", "neurologique"],
    descriptionEn: "Scheduled neuro assessment flow.",
    descriptionFr: "Feuille de contrôles neurologiques.",
  }),
  card({
    id: "flow_telemetry_monitoring",
    titleEn: "Telemetry Monitoring",
    titleFr: "Surveillance télémétrie",
    category: "FLOWSHEETS",
    careSettings: ["OBSERVATION", "INPATIENT", "TELEMETRY"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.telemetry",
    repeatable: true,
    tags: ["telemetry"],
    searchAliases: ["telemetry", "télémétrie"],
    descriptionEn: "Telemetry monitoring flow.",
    descriptionFr: "Feuille surveillance télémétrie.",
  }),
  card({
    id: "flow_cardiac_monitoring",
    titleEn: "Cardiac Monitoring",
    titleFr: "Surveillance cardiaque",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.cardiacMonitoring",
    repeatable: true,
    tags: ["cardiac", "monitor"],
    searchAliases: ["cardiac monitoring", "surveillance cardiaque"],
    descriptionEn: "Continuous cardiac monitoring flow.",
    descriptionFr: "Feuille surveillance cardiaque.",
  }),
  card({
    id: "flow_sepsis_monitoring",
    titleEn: "Sepsis Monitoring",
    titleFr: "Surveillance sepsis",
    category: "FLOWSHEETS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.sepsisMonitoring",
    repeatable: true,
    tags: ["sepsis"],
    searchAliases: ["sepsis monitoring", "sepsis bundle"],
    descriptionEn: "Sepsis bundle / reassessment flow.",
    descriptionFr: "Feuille surveillance sepsis.",
  }),
  card({
    id: "flow_observation_monitoring",
    titleEn: "Observation Monitoring",
    titleFr: "Surveillance observation",
    category: "FLOWSHEETS",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.flowsheets.observationMonitoring",
    repeatable: true,
    tags: ["observation"],
    searchAliases: ["observation monitoring", "surveillance observation"],
    descriptionEn: "Observation unit monitoring flow.",
    descriptionFr: "Feuille surveillance unité d'observation.",
  }),
];

const SCORES_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "score_nihss",
    titleEn: "NIHSS",
    titleFr: "NIHSS",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.nihss",
    repeatable: true,
    tags: ["stroke", "neuro"],
    searchAliases: ["NIHSS", "stroke scale", "échelle NIHSS"],
    descriptionEn: "NIH Stroke Scale.",
    descriptionFr: "Échelle neurologique NIHSS.",
  }),
  card({
    id: "score_cincinnati_stroke",
    titleEn: "Cincinnati Stroke Scale",
    titleFr: "Échelle de Cincinnati (AVC)",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED", "URGENT_CARE"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.cincinnatiStroke",
    repeatable: true,
    tags: ["stroke"],
    searchAliases: ["Cincinnati", "CPSS", "AVC Cincinnati"],
    descriptionEn: "Prehospital / ED stroke screen.",
    descriptionFr: "Dépistage AVC Cincinnati.",
  }),
  card({
    id: "score_van",
    titleEn: "VAN Assessment",
    titleFr: "Évaluation VAN",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.van",
    repeatable: true,
    tags: ["stroke", "LVO"],
    searchAliases: ["VAN", "large vessel"],
    descriptionEn: "Vision, aphasia, neglect screen for LVO.",
    descriptionFr: "Dépistage VAN (gros vaisseau).",
  }),
  card({
    id: "score_abcd2",
    titleEn: "ABCD2 Score",
    titleFr: "Score ABCD2",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.abcd2",
    repeatable: true,
    tags: ["TIA"],
    searchAliases: ["ABCD2", "TIA"],
    descriptionEn: "TIA stroke risk score.",
    descriptionFr: "Score de risque AVC post-AIT.",
  }),
  card({
    id: "score_qsofa",
    titleEn: "qSOFA",
    titleFr: "qSOFA",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.qsofa",
    repeatable: true,
    tags: ["sepsis"],
    searchAliases: ["qSOFA", "quick SOFA"],
    descriptionEn: "Quick SOFA sepsis screen.",
    descriptionFr: "Dépistage sepsis qSOFA.",
  }),
  card({
    id: "score_sirs",
    titleEn: "SIRS",
    titleFr: "SIRS",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.sirs",
    repeatable: true,
    tags: ["sepsis"],
    searchAliases: ["SIRS", "systemic inflammatory"],
    descriptionEn: "SIRS criteria documentation.",
    descriptionFr: "Critères SIRS.",
  }),
  card({
    id: "score_sepsis_screen",
    titleEn: "Sepsis Screen",
    titleFr: "Dépistage sepsis",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.sepsisScreen",
    repeatable: true,
    tags: ["sepsis"],
    searchAliases: ["sepsis screen", "dépistage sepsis"],
    descriptionEn: "Institutional sepsis screening.",
    descriptionFr: "Dépistage sepsis institutionnel.",
  }),
  card({
    id: "score_ciwa_ar",
    titleEn: "CIWA-Ar",
    titleFr: "CIWA-Ar",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.ciwa",
    repeatable: true,
    tags: ["withdrawal", "alcohol"],
    searchAliases: ["CIWA", "alcohol withdrawal"],
    descriptionEn: "Alcohol withdrawal assessment.",
    descriptionFr: "Échelle sevrage alcool (CIWA-Ar).",
  }),
  card({
    id: "score_cows",
    titleEn: "COWS",
    titleFr: "COWS",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.cows",
    repeatable: true,
    tags: ["withdrawal", "opioid"],
    searchAliases: ["COWS", "opioid withdrawal"],
    descriptionEn: "Clinical Opiate Withdrawal Scale.",
    descriptionFr: "Échelle sevrage opioïdes (COWS).",
  }),
  card({
    id: "score_cssrs",
    titleEn: "C-SSRS / Suicide Risk",
    titleFr: "C-SSRS / Risque suicidaire",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.cssrs",
    repeatable: true,
    tags: ["mental health", "safety"],
    searchAliases: ["C-SSRS", "suicide", "suicidaire"],
    descriptionEn: "Columbia suicide severity screen.",
    descriptionFr: "Dépistage risque suicidaire C-SSRS.",
  }),
  card({
    id: "score_phq9",
    titleEn: "PHQ-9",
    titleFr: "PHQ-9",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.phq9",
    repeatable: true,
    tags: ["mental health"],
    searchAliases: ["PHQ-9", "depression"],
    descriptionEn: "Patient Health Questionnaire-9.",
    descriptionFr: "Questionnaire PHQ-9 (dépression).",
  }),
  card({
    id: "score_gad7",
    titleEn: "GAD-7",
    titleFr: "GAD-7",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.gad7",
    repeatable: true,
    tags: ["mental health", "anxiety"],
    searchAliases: ["GAD-7", "anxiety", "anxiété"],
    descriptionEn: "Generalized Anxiety Disorder-7.",
    descriptionFr: "Échelle anxiété GAD-7.",
  }),
  card({
    id: "score_gcs",
    titleEn: "Glasgow Coma Scale",
    titleFr: "Échelle de Glasgow",
    category: "SCORES_AND_SCREENS",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.gcs",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["trauma", "neuro", "altered_consciousness"],
    searchAliases: ["GCS", "Glasgow", "Glasgow Coma"],
    descriptionEn: "Glasgow Coma Scale.",
    descriptionFr: "Score de Glasgow (GCS).",
  }),
  card({
    id: "score_rts",
    titleEn: "Revised Trauma Score",
    titleFr: "Score traumatologique révisé",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.rts",
    repeatable: true,
    tags: ["trauma"],
    searchAliases: ["RTS", "trauma score"],
    descriptionEn: "Revised Trauma Score.",
    descriptionFr: "Score traumatologique révisé (RTS).",
  }),
  card({
    id: "score_heart",
    titleEn: "HEART Score",
    titleFr: "Score HEART",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.heart",
    repeatable: true,
    tags: ["cardiology", "chest pain"],
    searchAliases: ["HEART", "chest pain risk"],
    descriptionEn: "HEART pathway chest pain risk.",
    descriptionFr: "Score HEART (douleur thoracique).",
  }),
  card({
    id: "score_wells_pe",
    titleEn: "Wells PE",
    titleFr: "Score de Wells (EP)",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.wellsPe",
    repeatable: true,
    tags: ["PE", "pulmonary"],
    searchAliases: ["Wells PE", "pulmonary embolism", "embolie"],
    descriptionEn: "Wells criteria for pulmonary embolism.",
    descriptionFr: "Critères de Wells (embolie pulmonaire).",
  }),
  card({
    id: "score_perc",
    titleEn: "PERC",
    titleFr: "PERC",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.perc",
    repeatable: true,
    tags: ["PE"],
    searchAliases: ["PERC", "pulmonary embolism rule-out"],
    descriptionEn: "PERC rule for PE.",
    descriptionFr: "Règle PERC (EP).",
  }),
  card({
    id: "score_geneva",
    titleEn: "Geneva Score",
    titleFr: "Score de Genève",
    category: "SCORES_AND_SCREENS",
    careSettings: ["ED"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.scores.geneva",
    repeatable: true,
    tags: ["PE"],
    searchAliases: ["Geneva", "Genève", "PE score"],
    descriptionEn: "Geneva pulmonary embolism score.",
    descriptionFr: "Score de Genève (EP).",
  }),
  card({
    id: "score_fall_risk",
    titleEn: "Fall Risk Screen",
    titleFr: "Dépistage risque de chute",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.fallRisk",
    repeatable: true,
    tags: ["safety", "falls"],
    searchAliases: ["fall risk", "chute", "Morse"],
    descriptionEn: "Fall risk screening tool.",
    descriptionFr: "Dépistage du risque de chute.",
  }),
  card({
    id: "score_abuse",
    titleEn: "Abuse Screen",
    titleFr: "Dépistage maltraitance",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.abuse",
    repeatable: true,
    tags: ["safety"],
    searchAliases: ["abuse", "domestic violence", "maltraitance"],
    descriptionEn: "Abuse / IPV screening.",
    descriptionFr: "Dépistage maltraitance / violence.",
  }),
  card({
    id: "score_human_trafficking",
    titleEn: "Human Trafficking Screen",
    titleFr: "Dépistage traite humaine",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.humanTrafficking",
    repeatable: true,
    tags: ["safety"],
    searchAliases: ["trafficking", "traite"],
    descriptionEn: "Human trafficking screening.",
    descriptionFr: "Dépistage traite des êtres humains.",
  }),
  card({
    id: "score_sdoh",
    titleEn: "Social Determinants of Health",
    titleFr: "Déterminants sociaux de la santé",
    category: "SCORES_AND_SCREENS",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.scores.sdoh",
    repeatable: true,
    tags: ["SDOH", "social"],
    searchAliases: ["SDOH", "social determinants", "déterminants sociaux"],
    descriptionEn: "SDOH screening.",
    descriptionFr: "Dépistage des déterminants sociaux.",
  }),
];

const INTAKE_OUTPUT_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "io_intake_output",
    titleEn: "Intake & Output",
    titleFr: "Entrées et sorties",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.summary",
    repeatable: true,
    tags: ["I&O", "fluid"],
    searchAliases: ["I&O", "intake output", "entrées sorties", "fluid balance"],
    descriptionEn: "Comprehensive intake and output record.",
    descriptionFr: "Bilan entrées / sorties global.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_fluid_intake",
    titleEn: "Fluid Intake",
    titleFr: "Apports hydriques",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.fluidIntake",
    repeatable: true,
    tags: ["intake"],
    searchAliases: ["fluid intake", "apports"],
    descriptionEn: "IV and other fluid intake.",
    descriptionFr: "Apports hydriques (IV et autres).",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_po_intake",
    titleEn: "PO Intake",
    titleFr: "Apports per os",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.poIntake",
    repeatable: true,
    tags: ["PO"],
    searchAliases: ["PO intake", "oral intake", "per os"],
    descriptionEn: "Oral intake documentation.",
    descriptionFr: "Apports par voie orale.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_iv_intake",
    titleEn: "IV Intake",
    titleFr: "Apports IV",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.ivIntake",
    repeatable: true,
    tags: ["IV"],
    searchAliases: ["IV intake", "intravenous"],
    descriptionEn: "Intravenous fluid intake.",
    descriptionFr: "Apports intraveineux.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_blood_product_intake",
    titleEn: "Blood Product Intake",
    titleFr: "Apports produit sanguin",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.bloodProductIntake",
    repeatable: true,
    tags: ["blood"],
    searchAliases: ["blood intake", "transfusion volume"],
    descriptionEn: "Blood product volume as intake.",
    descriptionFr: "Volume produit sanguin (apport).",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_urine_output",
    titleEn: "Urine Output",
    titleFr: "Diurèse",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.urine",
    repeatable: true,
    tags: ["output", "urine"],
    searchAliases: ["urine output", "diurèse"],
    descriptionEn: "Urine output measurement.",
    descriptionFr: "Mesure de la diurèse.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_stool_output",
    titleEn: "Stool Output",
    titleFr: "Selles",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.stool",
    repeatable: true,
    tags: ["output", "GI"],
    searchAliases: ["stool", "selles", "bowel"],
    descriptionEn: "Stool output documentation.",
    descriptionFr: "Documentation selles.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_emesis_output",
    titleEn: "Emesis Output",
    titleFr: "Vomissements",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.emesis",
    repeatable: true,
    tags: ["output", "emesis"],
    searchAliases: ["emesis", "vomit", "vomissements"],
    descriptionEn: "Emesis output documentation.",
    descriptionFr: "Documentation vomissements.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_ng_output",
    titleEn: "NG Output",
    titleFr: "Sondage NG (sorties)",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.ng",
    repeatable: true,
    tags: ["NG"],
    searchAliases: ["NG output", "nasogastric"],
    descriptionEn: "Nasogastric drainage output.",
    descriptionFr: "Sorties par sonde nasogastrique.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
  card({
    id: "io_drain_output",
    titleEn: "Drain Output",
    titleFr: "Drains",
    category: "INTAKE_OUTPUT",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.intakeOutput.drain",
    repeatable: true,
    tags: ["drain"],
    searchAliases: ["drain output", "JP drain", "drain"],
    descriptionEn: "Surgical drain output.",
    descriptionFr: "Sorties de drains chirurgicaux.",
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
  }),
];

const SAFETY_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "safety_restraint_initial",
    titleEn: "Restraint Initial Assessment",
    titleFr: "Évaluation initiale contention",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.restraintInitial",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["restraint"],
    searchAliases: ["restraint initial", "contention initiale"],
    descriptionEn: "Initial restraint assessment and order alignment.",
    descriptionFr: "Évaluation initiale de contention.",
  }),
  card({
    id: "safety_restraint_reassessment",
    titleEn: "Restraint Reassessment",
    titleFr: "Réévaluation contention",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.restraintReassessment",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["restraint"],
    searchAliases: ["restraint reassessment", "réévaluation contention"],
    descriptionEn: "Scheduled restraint reassessment.",
    descriptionFr: "Réévaluation périodique de contention.",
  }),
  card({
    id: "safety_fall_precautions",
    titleEn: "Fall Precautions",
    titleFr: "Précautions chute",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.fallPrecautions",
    repeatable: true,
    tags: ["falls"],
    searchAliases: ["fall precautions", "précautions chute"],
    descriptionEn: "Fall precaution checklist.",
    descriptionFr: "Liste des précautions anti-chute.",
  }),
  card({
    id: "safety_suicide_precautions",
    titleEn: "Suicide Precautions",
    titleFr: "Précautions suicide",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.suicidePrecautions",
    repeatable: true,
    tags: ["mental health"],
    searchAliases: ["suicide precautions", "précautions suicide", "1:1"],
    descriptionEn: "Suicide precaution and observation orders.",
    descriptionFr: "Précautions et surveillance suicide.",
  }),
  card({
    id: "safety_elopement_risk",
    titleEn: "Elopement Risk",
    titleFr: "Risque de fugue",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.elopement",
    repeatable: true,
    tags: ["safety"],
    searchAliases: ["elopement", "fugue", "AWOL"],
    descriptionEn: "Elopement risk documentation.",
    descriptionFr: "Documentation risque de fugue.",
  }),
  card({
    id: "safety_behavioral_observation",
    titleEn: "Behavioral Observation",
    titleFr: "Observation comportementale",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.behavioralObservation",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["behavioral", "altered_consciousness"],
    searchAliases: ["behavioral observation", "psych observation"],
    descriptionEn: "Behavioral / psychiatric observation log.",
    descriptionFr: "Journal d'observation comportementale.",
  }),
  card({
    id: "safety_belongings_checklist",
    titleEn: "Patient Belongings Checklist",
    titleFr: "Liste effets personnels",
    category: "SAFETY_DOCUMENTATION",
    careSettings: ALL_SETTINGS,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.safety.belongings",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["belongings"],
    searchAliases: ["belongings", "effets personnels", "valuables"],
    descriptionEn: "Patient belongings inventory.",
    descriptionFr: "Inventaire des effets personnels.",
  }),
];

const RESPIRATORY_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "resp_oxygen_therapy",
    titleEn: "Oxygen Therapy",
    titleFr: "Oxygénothérapie",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RT",
    legalChartSection: "clinicalDocumentation.respiratory.oxygen",
    repeatable: true,
    tags: ["oxygen"],
    searchAliases: ["oxygen therapy", "O2", "oxygène"],
    descriptionEn: "Oxygen delivery and titration.",
    descriptionFr: "Administration et titration d'oxygène.",
  }),
  card({
    id: "resp_nebulizer",
    titleEn: "Nebulizer Treatment",
    titleFr: "Nébulisation",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RT",
    legalChartSection: "clinicalDocumentation.respiratory.nebulizer",
    repeatable: true,
    tags: ["nebulizer"],
    searchAliases: ["nebulizer", "nébulisation", "bronchodilator"],
    descriptionEn: "Nebulized medication administration.",
    descriptionFr: "Traitement par nébulisation.",
  }),
  card({
    id: "resp_assessment",
    titleEn: "Respiratory Assessment",
    titleFr: "Évaluation respiratoire",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.respiratory.assessment",
    repeatable: true,
    tags: ["assessment"],
    searchAliases: ["respiratory assessment", "évaluation respiratoire"],
    descriptionEn: "Structured respiratory assessment.",
    descriptionFr: "Évaluation respiratoire structurée.",
  }),
  card({
    id: "resp_ventilator",
    titleEn: "Ventilator Documentation",
    titleFr: "Documentation ventilateur",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ["ED", "INPATIENT", "ICU"],
    primaryRole: "RT",
    legalChartSection: "clinicalDocumentation.respiratory.ventilator",
    repeatable: true,
    tags: ["ventilator", "critical care"],
    searchAliases: ["ventilator", "ventilation", "mechanical ventilation"],
    descriptionEn: "Mechanical ventilation parameters and checks.",
    descriptionFr: "Paramètres et contrôles du ventilateur.",
  }),
  card({
    id: "resp_cpap_bipap",
    titleEn: "CPAP / BiPAP Documentation",
    titleFr: "Documentation CPAP / BiPAP",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RT",
    legalChartSection: "clinicalDocumentation.respiratory.cpapBipap",
    repeatable: true,
    tags: ["NIV"],
    searchAliases: ["CPAP", "BiPAP", "NIV"],
    descriptionEn: "Non-invasive positive pressure ventilation.",
    descriptionFr: "Ventilation non invasive (CPAP / BiPAP).",
  }),
  card({
    id: "resp_peak_flow",
    titleEn: "Peak Flow Documentation",
    titleFr: "Documentation débit de pointe",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ["ED", "CLINIC", "URGENT_CARE"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.respiratory.peakFlow",
    repeatable: true,
    tags: ["asthma"],
    searchAliases: ["peak flow", "débit de pointe"],
    descriptionEn: "Peak expiratory flow measurements.",
    descriptionFr: "Mesures du débit de pointe.",
  }),
  card({
    id: "resp_incentive_spirometry",
    titleEn: "Incentive Spirometry",
    titleFr: "Spirométrie d'incitation",
    category: "RESPIRATORY_DOCUMENTATION",
    careSettings: ["INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.respiratory.incentiveSpirometry",
    repeatable: true,
    tags: ["IS"],
    searchAliases: ["incentive spirometry", "IS"],
    descriptionEn: "Incentive spirometry use and tolerance.",
    descriptionFr: "Spirométrie d'incitation et tolérance.",
  }),
];

const BLOOD_PRODUCT_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "blood_transfusion",
    titleEn: "Blood Transfusion",
    titleFr: "Transfusion sanguine",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.transfusion",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["transfusion"],
    searchAliases: ["blood transfusion", "transfusion", "packed red cells"],
    descriptionEn: "Standard blood transfusion documentation.",
    descriptionFr: "Documentation transfusion sanguine.",
  }),
  card({
    id: "blood_massive_transfusion",
    titleEn: "Massive Transfusion Protocol",
    titleFr: "Protocole transfusion massive",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ["ED", "INPATIENT", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.mtp",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["MTP", "trauma"],
    searchAliases: ["MTP", "massive transfusion", "transfusion massive"],
    descriptionEn: "Massive transfusion protocol flow.",
    descriptionFr: "Protocole de transfusion massive.",
  }),
  card({
    id: "blood_ffp",
    titleEn: "FFP Administration",
    titleFr: "Administration PFC",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.ffp",
    repeatable: true,
    tags: ["FFP"],
    searchAliases: ["FFP", "fresh frozen plasma", "PFC"],
    descriptionEn: "Fresh frozen plasma administration.",
    descriptionFr: "Administration de plasma frais congelé.",
  }),
  card({
    id: "blood_platelets",
    titleEn: "Platelet Administration",
    titleFr: "Administration plaquettes",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.platelets",
    repeatable: true,
    tags: ["platelets"],
    searchAliases: ["platelets", "plaquettes"],
    descriptionEn: "Platelet transfusion documentation.",
    descriptionFr: "Documentation transfusion plaquettaire.",
  }),
  card({
    id: "blood_cryoprecipitate",
    titleEn: "Cryoprecipitate Administration",
    titleFr: "Administration cryoprécipité",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.cryo",
    repeatable: true,
    tags: ["cryo"],
    searchAliases: ["cryoprecipitate", "cryo"],
    descriptionEn: "Cryoprecipitate administration.",
    descriptionFr: "Administration de cryoprécipité.",
  }),
  card({
    id: "blood_transfusion_reaction",
    titleEn: "Transfusion Reaction Documentation",
    titleFr: "Réaction transfusionnelle",
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.bloodProduct.reaction",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["reaction"],
    searchAliases: ["transfusion reaction", "réaction transfusionnelle"],
    descriptionEn: "Suspected transfusion reaction workup.",
    descriptionFr: "Documentation réaction transfusionnelle.",
  }),
];

const STROKE_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "stroke_nihss",
    titleEn: "NIHSS",
    titleFr: "NIHSS",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.nihss",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["stroke"],
    searchAliases: ["NIHSS stroke", "AVC NIHSS"],
    descriptionEn: "NIHSS within stroke pathway.",
    descriptionFr: "NIHSS dans le parcours AVC.",
  }),
  card({
    id: "stroke_swallow_screen",
    titleEn: "Swallow Screen",
    titleFr: "Dépistage déglutition",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.swallow",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["dysphagia"],
    searchAliases: ["swallow screen", "dysphagia", "déglutition"],
    descriptionEn: "Bedside swallow screening.",
    descriptionFr: "Dépistage de la déglutition au chevet.",
  }),
  card({
    id: "stroke_cincinnati",
    titleEn: "Cincinnati Stroke Scale",
    titleFr: "Échelle de Cincinnati",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.cincinnati",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["stroke", "screening"],
    searchAliases: ["Cincinnati", "CPSS", "Cincinnati stroke scale"],
    descriptionEn: "Cincinnati Prehospital Stroke Scale.",
    descriptionFr: "Échelle de Cincinnati (dépistage AVC).",
  }),
  card({
    id: "stroke_van_assessment",
    titleEn: "VAN Assessment",
    titleFr: "Évaluation VAN",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.van",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["stroke", "screening", "LVO"],
    searchAliases: ["VAN", "VAN assessment", "large vessel"],
    descriptionEn: "VAN large-vessel occlusion screening.",
    descriptionFr: "Dépistage VAN (occlusion gros vaisseau).",
  }),
  card({
    id: "stroke_abcd2",
    titleEn: "ABCD2 Score",
    titleFr: "Score ABCD2",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "PROVIDER",
    legalChartSection: "clinicalDocumentation.stroke.abcd2",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["stroke", "TIA"],
    searchAliases: ["ABCD2", "TIA risk"],
    descriptionEn: "ABCD2 TIA stroke risk score.",
    descriptionFr: "Score ABCD2 (risque AVC post-AIT).",
  }),
  card({
    id: "stroke_tnk",
    titleEn: "TNK Administration",
    titleFr: "Administration TNK",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.tnk",
    repeatable: false,
    tags: ["thrombolytic"],
    searchAliases: ["TNK", "tenecteplase"],
    descriptionEn: "Tenecteplase stroke administration.",
    descriptionFr: "Administration de ténécéplase (AVC).",
  }),
  card({
    id: "stroke_tpa",
    titleEn: "tPA Administration",
    titleFr: "Administration tPA",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.tpa",
    repeatable: false,
    tags: ["thrombolytic"],
    searchAliases: ["tPA", "alteplase"],
    descriptionEn: "Alteplase stroke administration.",
    descriptionFr: "Administration d'altéplase (AVC).",
  }),
  card({
    id: "stroke_reassessment",
    titleEn: "Stroke Reassessment",
    titleFr: "Réévaluation AVC",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.reassessment",
    repeatable: true,
    tags: ["stroke"],
    searchAliases: ["stroke reassessment", "réévaluation AVC"],
    descriptionEn: "Interval stroke reassessment.",
    descriptionFr: "Réévaluation intervalle AVC.",
  }),
  card({
    id: "stroke_neuro_checks",
    titleEn: "Neuro Checks",
    titleFr: "Contrôles neurologiques",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.stroke.neuroChecks",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["neuro"],
    searchAliases: ["stroke neuro checks", "neuro checks AVC"],
    descriptionEn: "Stroke-specific neuro checks.",
    descriptionFr: "Contrôles neuro spécifiques AVC.",
  }),
  card({
    id: "stroke_timeline",
    titleEn: "Stroke Timeline",
    titleFr: "Chronologie AVC",
    category: "STROKE_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT", "ICU"],
    primaryRole: "MULTI_ROLE",
    legalChartSection: "clinicalDocumentation.stroke.timeline",
    repeatable: false,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["stroke", "timeline"],
    searchAliases: ["stroke timeline", "last known well", "LKW", "chronologie AVC"],
    descriptionEn: "Stroke pathway timeline milestones.",
    descriptionFr: "Jalons chronologiques du parcours AVC.",
  }),
];

const CARDIAC_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "cardiac_ekg_12_lead",
    titleEn: "EKG / ECG 12-Lead",
    titleFr: "ECG 12 dérivations",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "TECHNICIAN",
    legalChartSection: "clinicalDocumentation.cardiac.ekg12Lead",
    repeatable: true,
    tags: ["EKG", "ECG"],
    searchAliases: ["EKG", "ECG", "12-lead", "12 derivations"],
    descriptionEn: "12-lead ECG acquisition documentation.",
    descriptionFr: "Documentation ECG 12 dérivations.",
  }),
  card({
    id: "cardiac_rhythm_strip",
    titleEn: "EKG Rhythm Strip",
    titleFr: "Bande rythmique ECG",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.cardiac.rhythmStrip",
    repeatable: true,
    tags: ["rhythm"],
    searchAliases: ["rhythm strip", "bande rythmique"],
    descriptionEn: "Rhythm strip monitoring.",
    descriptionFr: "Surveillance par bande rythmique.",
  }),
  card({
    id: "cardiac_continuous_monitoring",
    titleEn: "Continuous Cardiac Monitoring",
    titleFr: "Surveillance cardiaque continue",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.cardiac.continuous",
    repeatable: true,
    tags: ["monitor"],
    searchAliases: ["continuous cardiac monitoring", "cardiac monitor"],
    descriptionEn: "Continuous cardiac monitor documentation.",
    descriptionFr: "Surveillance cardiaque continue.",
  }),
  card({
    id: "cardiac_telemetry_initiation",
    titleEn: "Telemetry Initiation",
    titleFr: "Mise en télémétrie",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    careSettings: ["OBSERVATION", "INPATIENT", "TELEMETRY"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.cardiac.telemetryStart",
    repeatable: true,
    tags: ["telemetry"],
    searchAliases: ["telemetry initiation", "start telemetry", "mise en télémétrie"],
    descriptionEn: "Telemetry initiation checklist.",
    descriptionFr: "Liste de mise en télémétrie.",
  }),
  card({
    id: "cardiac_telemetry_discontinuation",
    titleEn: "Telemetry Discontinuation",
    titleFr: "Arrêt télémétrie",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    careSettings: ["OBSERVATION", "INPATIENT", "TELEMETRY"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.cardiac.telemetryStop",
    repeatable: true,
    tags: ["telemetry"],
    searchAliases: ["telemetry discontinuation", "stop telemetry", "arrêt télémétrie"],
    descriptionEn: "Telemetry discontinuation documentation.",
    descriptionFr: "Documentation d'arrêt de télémétrie.",
  }),
];

const OBSERVATION_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "edoc_basic_structured_v1",
    titleEn: "Structured Entry — Basic",
    titleFr: "Saisie structurée — de base",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.basicStructured",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["structured", "basic"],
    searchAliases: ["structured entry", "basic entry", "saisie structurée"],
    descriptionEn: "Minimal structured key/value clinical documentation entry (EDOC.2).",
    descriptionFr: "Saisie structurée minimale clé/valeur (EDOC.2).",
  }),
  card({
    id: "obs_po_challenge",
    titleEn: "PO Challenge",
    titleFr: "Épreuve per os",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.poChallenge",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["observation", "PO"],
    searchAliases: ["PO challenge", "oral challenge", "épreuve PO"],
    descriptionEn: "Oral intake challenge during observation.",
    descriptionFr: "Épreuve de tolérance per os.",
  }),
  card({
    id: "obs_ambulation_trial",
    titleEn: "Ambulation Trial",
    titleFr: "Essai de marche",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.ambulationTrial",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["observation", "ambulation"],
    searchAliases: ["ambulation trial", "walk trial", "essai de marche"],
    descriptionEn: "Ambulation trial for discharge readiness.",
    descriptionFr: "Essai de marche (aptitude sortie).",
  }),
  card({
    id: "obs_reassessment",
    titleEn: "Observation Reassessment",
    titleFr: "Réévaluation observation",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.reassessment",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["observation"],
    searchAliases: ["observation reassessment", "réévaluation observation"],
    descriptionEn: "Structured observation reassessment.",
    descriptionFr: "Réévaluation structurée en observation.",
  }),
  card({
    id: "obs_discharge_readiness",
    titleEn: "Discharge Readiness",
    titleFr: "Aptitude à la sortie",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["OBSERVATION", "ED", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.dischargeReadiness",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["discharge"],
    searchAliases: ["discharge readiness", "aptitude sortie"],
    descriptionEn: "Observation discharge readiness checklist.",
    descriptionFr: "Liste d'aptitude à la sortie (observation).",
  }),
  card({
    id: "obs_boarding",
    titleEn: "Boarding Documentation",
    titleFr: "Documentation attente",
    category: "OBSERVATION_DOCUMENTATION",
    careSettings: ["ED", "OBSERVATION", "INPATIENT"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.observation.boarding",
    repeatable: true,
    implementationStatus: "AVAILABLE",
    status: "ACTIVE",
    tags: ["boarding", "capacity"],
    searchAliases: ["boarding", "ED boarding", "attente"],
    descriptionEn: "ED boarding / capacity documentation.",
    descriptionFr: "Documentation attente aux urgences.",
  }),
];

const PROCEDURE_MONITORING_CARDS: ClinicalDocumentationCard[] = [
  card({
    id: "proc_foley_monitoring",
    titleEn: "Foley Monitoring",
    titleFr: "Surveillance sonde urinaire",
    category: "PROCEDURE_MONITORING",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.foley",
    repeatable: true,
    tags: ["foley", "GU"],
    searchAliases: ["Foley", "urinary catheter"],
    descriptionEn: "Urinary catheter monitoring.",
    descriptionFr: "Surveillance de sonde urinaire.",
  }),
  card({
    id: "proc_chest_tube",
    titleEn: "Chest Tube Monitoring",
    titleFr: "Surveillance drain thoracique",
    category: "PROCEDURE_MONITORING",
    careSettings: ["ED", "INPATIENT", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.chestTube",
    repeatable: true,
    tags: ["chest tube"],
    searchAliases: ["chest tube", "thoracostomy", "drain thoracique"],
    descriptionEn: "Chest tube monitoring flow.",
    descriptionFr: "Surveillance drain thoracique.",
  }),
  card({
    id: "proc_central_line",
    titleEn: "Central Line Monitoring",
    titleFr: "Surveillance voie centrale",
    category: "PROCEDURE_MONITORING",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.centralLine",
    repeatable: true,
    tags: ["central line"],
    searchAliases: ["central line", "CVC", "voie centrale"],
    descriptionEn: "Central venous catheter monitoring.",
    descriptionFr: "Surveillance cathéter veineux central.",
  }),
  card({
    id: "proc_lumbar_puncture",
    titleEn: "Lumbar Puncture Monitoring",
    titleFr: "Surveillance ponction lombaire",
    category: "PROCEDURE_MONITORING",
    careSettings: ["ED"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.lp",
    repeatable: true,
    tags: ["LP"],
    searchAliases: ["lumbar puncture", "ponction lombaire", "LP"],
    descriptionEn: "Post–lumbar puncture monitoring.",
    descriptionFr: "Surveillance post-ponction lombaire.",
  }),
  card({
    id: "proc_sedation_monitoring",
    titleEn: "Procedural Sedation Monitoring",
    titleFr: "Surveillance sédation procédurale",
    category: "PROCEDURE_MONITORING",
    careSettings: ED_INPATIENT,
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.sedation",
    repeatable: true,
    requiresWitnessSignature: true,
    tags: ["sedation"],
    searchAliases: ["procedural sedation monitoring", "sédation procédurale"],
    descriptionEn: "Peri-procedural sedation monitoring.",
    descriptionFr: "Surveillance peri-procédurale sous sédation.",
  }),
  card({
    id: "proc_intubation_monitoring",
    titleEn: "Intubation Monitoring",
    titleFr: "Surveillance intubation",
    category: "PROCEDURE_MONITORING",
    careSettings: ["ED", "ICU"],
    primaryRole: "RN",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.intubation",
    repeatable: true,
    tags: ["airway"],
    searchAliases: ["intubation monitoring", "post intubation"],
    descriptionEn: "Post-intubation monitoring.",
    descriptionFr: "Surveillance post-intubation.",
  }),
  card({
    id: "proc_timeout",
    titleEn: "Procedure Timeout",
    titleFr: "Time-out procédure",
    category: "PROCEDURE_MONITORING",
    careSettings: ALL_SETTINGS,
    primaryRole: "MULTI_ROLE",
    legalChartSection: "clinicalDocumentation.procedureMonitoring.timeout",
    repeatable: true,
    tags: ["timeout", "safety"],
    searchAliases: ["timeout", "surgical pause", "time-out"],
    descriptionEn: "Universal protocol procedure timeout.",
    descriptionFr: "Time-out sécurité procédure.",
  }),
];

export const CLINICAL_DOCUMENTATION_CARDS: readonly ClinicalDocumentationCard[] = [
  ...FLOWSHEET_CARDS,
  ...SCORES_CARDS,
  ...INTAKE_OUTPUT_CARDS,
  ...SAFETY_CARDS,
  ...RESPIRATORY_CARDS,
  ...BLOOD_PRODUCT_CARDS,
  ...STROKE_CARDS,
  ...CARDIAC_CARDS,
  ...OBSERVATION_CARDS,
  ...PROCEDURE_MONITORING_CARDS,
];

const CARD_BY_ID = new Map(CLINICAL_DOCUMENTATION_CARDS.map((c) => [c.id, c]));

export function getClinicalDocumentationCardById(id: string): ClinicalDocumentationCard | undefined {
  return CARD_BY_ID.get(id);
}

export function listClinicalDocumentationCardsByCategory(
  category: ClinicalDocumentationCategory
): ClinicalDocumentationCard[] {
  return CLINICAL_DOCUMENTATION_CARDS.filter((c) => c.category === category);
}

export function listClinicalDocumentationCardsForCareSetting(
  careSetting: ClinicalDocumentationCareSetting
): ClinicalDocumentationCard[] {
  return CLINICAL_DOCUMENTATION_CARDS.filter((c) => c.careSettings.includes(careSetting));
}

export function searchClinicalDocumentationCards(
  query: string,
  locale: "en" | "fr" = "en"
): ClinicalDocumentationCard[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...CLINICAL_DOCUMENTATION_CARDS];
  return CLINICAL_DOCUMENTATION_CARDS.filter((c) => {
    const title = locale === "fr" ? c.titleFr : c.titleEn;
    const desc = locale === "fr" ? c.descriptionFr : c.descriptionEn;
    const haystack = [title, desc, c.id, ...c.tags, ...c.searchAliases].join(" ").toLowerCase();
    return haystack.includes(q);
  });
}

export function assertClinicalDocumentationRegistryIntegrity(): void {
  const ids = new Set<string>();
  for (const c of CLINICAL_DOCUMENTATION_CARDS) {
    if (ids.has(c.id)) {
      throw new Error(`Duplicate clinical documentation card id: ${c.id}`);
    }
    ids.add(c.id);
    if (!c.titleEn.trim() || !c.titleFr.trim()) {
      throw new Error(`Missing title for card ${c.id}`);
    }
  }
  for (const cat of CLINICAL_DOCUMENTATION_CATEGORY_META) {
    if (!CLINICAL_DOCUMENTATION_CARDS.some((c) => c.category === cat.id)) {
      throw new Error(`Category ${cat.id} has no cards`);
    }
  }
}

assertClinicalDocumentationRegistryIntegrity();
