/** MEDUI.ES.1K — Spanish display labels for clinical documentation payload summaries. */
export const CLINICAL_DOC_SUMMARY_LABEL_ES: Record<string, string> = {
  "ADL impact": "Repercusión en las AVQ",
  "ADLs": "AVQ",
  "Abdominal pain": "Dolor abdominal",
  "Abnormal elements": "Elementos anormales",
  "Abnormal findings": "Hallazgos anormales",
  "Access issue": "Problema de acceso",
  "Access status": "Estado del acceso",
  "Access type": "Tipo de acceso",
  "Activation reason": "Motivo de activación",
  "Additional education required": "Se requiere educación adicional",
  "Administration started": "Administración iniciada",
  "Adverse effect": "Efecto adverso",
  "Adverse effects": "Efectos adversos",
  "Adverse event": "Evento adverso",
  "After": "Después",
  "Agent": "Agente",
  "Air leak": "Fuga de aire",
  "Airway": "Vía aérea",
  "Airway patent": "Vía aérea permeable",
  "Airway stable": "Vía aérea estable",
  "Alarm": "Alarma",
  "Alternatives attempted": "Alternativas intentadas",
  "Amount": "Cantidad",
  "Antibiotics in MAR": "Antibióticos en el MAR",
  "Appearance": "Aspecto",
  "Appointment needed": "Cita necesaria",
  "Appointment scheduled": "Cita programada",
  "Approximation": "Aproximación",
  "Assessed": "Evaluado",
  "Assessed at": "Evaluado el",
  "Assessment time": "Hora de la evaluación",
  "Assistance": "Asistencia",
  "Audience": "Destinatarios",
  "BP concern": "Preocupación por la PA",
  "BP response": "Respuesta de la PA",
  "BP within parameters": "PA dentro de parámetros",
  "Bag ID": "ID de la bolsa",
  "Barrier type": "Tipo de barrera",
  "Barriers": "Barreras",
  "Barriers identified": "Barreras identificadas",
  "Baseline": "Basal",
  "Baseline mental status": "Estado mental basal",
  "Baseline temperature": "Temperatura basal",
  "Bed alarm": "Alarma de cama",
  "Before": "Antes",
  "Before antibiotics": "Antes de antibióticos",
  "Behavior": "Conducta",
  "Belongings bagged": "Pertenencias embolsadas",
  "Belongings secured": "Pertenencias aseguradas",
  "Bladder scan": "Ecografía vesical",
  "Bleeding concern": "Preocupación por sangrado",
  "Bleeding observed": "Sangrado observado",
  "Blood bank notified": "Banco de sangre notificado",
  "Blood pressure": "Presión arterial",
  "Blood product intake": "Ingreso de hemoderivados",
  "Blood product type": "Tipo de hemoderivado",
  "Blood type": "Grupo sanguíneo",
  "Boarding reason": "Motivo de espera de cama",
  "Bolus dose (mg)": "Dosis en bolo (mg)",
  "Breath sounds": "Ruidos respiratorios",
  "Bruit": "Soplo",
  "Bundle type": "Tipo de paquete",
  "CSF leak concern": "Preocupación por fuga de LCR",
  "CT completed": "TC completada",
  "CT reviewed": "TC revisada",
  "Capture present": "Captura presente",
  "Cardiac": "Cardíaco",
  "Cardiology notified": "Cardiología notificada",
  "Caregiver involved": "Cuidador involucrado",
  "Cash present": "Efectivo presente",
  "Category": "Categoría",
  "Cath lab activated": "Sala de hemodinamia activada",
  "Change": "Cambio",
  "Change vs prior": "Cambio vs anterior",
  "Checklist": "Lista de verificación",
  "Chest pain": "Dolor torácico",
  "Circulation": "Circulación",
  "Clothing items": "Prendas de vestir",
  "Comfort offered": "Confort ofrecido",
  "Completion status": "Estado de finalización",
  "Completion time": "Hora de finalización",
  "Compliance concern": "Preocupación por cumplimiento",
  "Concern type": "Tipo de preocupación",
  "Condition": "Estado",
  "Consent": "Consentimiento",
  "Consent verified": "Consentimiento verificado",
  "Continued administration": "Administración continuada",
  "Continued infusion": "Infusión continuada",
  "Continued need": "Necesidad continua",
  "Cortical signs": "Signos corticales",
  "Criteria count": "Número de criterios",
  "Criteria met": "Criterios cumplidos",
  "Critical finding": "Hallazgo crítico",
  "Crossmatch": "Prueba cruzada",
  "Cultures before antibiotics": "Cultivos antes de antibióticos",
  "Cultures collected": "Cultivos extraídos",
  "Current": "Actual",
  "Current level": "Nivel actual",
  "Current score": "Puntuación actual",
  "Danger to others": "Peligro para terceros",
  "Danger to self": "Peligro para sí mismo",
  "De-escalation used": "Desescalada utilizada",
  "Delay/variance": "Retraso/variación",
  "Device / flow": "Dispositivo / flujo",
  "Discontinued": "Suspendido",
  "Discrepancy": "Discrepancia",
  "Dislodgement concern": "Preocupación por desplazamiento",
  "Displacement concern": "Preocupación por desplazamiento",
  "Distance": "Distancia",
  "Dizziness": "Mareo",
  "Documented": "Documentado",
  "Documented in MAR": "Documentado en el MAR",
  "Dose (mg)": "Dosis (mg)",
  "Double check": "Doble verificación",
  "Drain": "Drenaje",
  "Drain type": "Tipo de drenaje",
  "Drainage": "Drenaje",
  "Drainage amount": "Cantidad de drenaje",
  "Drainage appearance": "Aspecto del drenaje",
  "Dressing": "Apósito",
  "Duration": "Duración",
  "Edema": "Edema",
  "Education provided": "Educación proporcionada",
  "Effluent appearance": "Aspecto del efluente",
  "Effort quality": "Calidad del esfuerzo",
  "Electronics present": "Electrónicos presentes",
  "End time": "Hora de fin",
  "Equipment": "Equipo",
  "Equipment ready": "Equipo listo",
  "Estimated fluid removed": "Líquido retirado estimado",
  "Estimated volume": "Volumen estimado",
  "Evaluator": "Evaluador",
  "Event": "Evento",
  "Event time": "Hora del evento",
  "Event type": "Tipo de evento",
  "Expiration": "Vencimiento",
  "FLACC total": "Total FLACC",
  "Face-to-face evaluation": "Evaluación presencial",
  "Fall risk reviewed": "Riesgo de caída revisado",
  "Family educated": "Familia educada",
  "Final rate": "Ritmo final",
  "Fluid overload concern": "Preocupación por sobrecarga hídrica",
  "Fluid removal goal": "Objetivo de extracción de líquidos",
  "Follow-up reviewed": "Seguimiento revisado",
  "Frequency": "Frecuencia",
  "Functioning properly": "Funcionamiento correcto",
  "GCS severity": "Gravedad GCS",
  "GCS total": "Total GCS",
  "Gait stability": "Estabilidad de la marcha",
  "Geneva score": "Puntuación de Ginebra",
  "Goal": "Objetivo",
  "Goal type": "Tipo de objetivo",
  "HEART score": "Puntuación HEART",
  "HR": "FC",
  "Handoff completed": "Traspaso completado",
  "Handoff type": "Tipo de traspaso",
  "Hazards cleared": "Peligros retirados",
  "Headache": "Cefalea",
  "Heart rate": "Frecuencia cardíaca",
  "Hemodynamic instability": "Inestabilidad hemodinámica",
  "High-risk concerns": "Preocupaciones de alto riesgo",
  "High-risk medication": "Medicamento de alto riesgo",
  "Hold time": "Hora de suspensión",
  "ID checked": "Identidad verificada",
  "IV intake": "Ingreso IV",
  "Ideation status": "Estado de ideación",
  "Improved": "Mejorado",
  "Improvement reported": "Mejoría referida",
  "Infection concern": "Preocupación por infección",
  "Infection signs": "Signos de infección",
  "Infusion dose (mg)": "Dosis de infusión (mg)",
  "Infusion interrupted": "Infusión interrumpida",
  "Initiated by": "Iniciado por",
  "Initiation status": "Estado de inicio",
  "Injury identified": "Lesión identificada",
  "Injury observed": "Lesión observada",
  "Inner cannula checked": "Cánula interna verificada",
  "Instructions reviewed": "Indicaciones revisadas",
  "Intake": "Ingresos",
  "Intake this shift": "Ingresos en este turno",
  "Interpretation": "Interpretación",
  "Interpreter needed": "Se necesita intérprete",
  "Intervention": "Intervención",
  "Intervention required": "Intervención requerida",
  "Interventions": "Intervenciones",
  "Issues found": "Problemas identificados",
  "Jewelry present": "Joyas presentes",
  "Kept with patient": "Con el paciente",
  "LOC": "Estado de conciencia",
  "Label applied": "Etiqueta aplicada",
  "Lactate": "Lactato",
  "Lactate value": "Valor de lactato",
  "Left pupil": "Pupila izquierda",
  "Line type": "Tipo de línea",
  "Location": "Ubicación",
  "Location confirmed": "Ubicación confirmada",
  "MAR documented": "Documentado en el MAR",
  "MTP status": "Estado de PTM",
  "Medication": "Medicamento",
  "Medication administered": "Medicamento administrado",
  "Medication referenced": "Medicamento referenciado",
  "Medication type": "Tipo de medicamento",
  "Medications reviewed": "Medicamentos revisados",
  "Mental status": "Estado mental",
  "Mental status baseline": "Estado mental basal",
  "Mental status changed": "Estado mental modificado",
  "Method": "Método",
  "Mobility": "Movilidad",
  "Mobility level": "Nivel de movilidad",
  "Mobility safe": "Movilidad segura",
  "Mode": "Modo",
  "Mode / settings": "Modo / ajustes",
  "Monitoring started": "Vigilancia iniciada",
  "Morse score": "Puntuación Morse",
  "N/A": "N/D",
  "NG output": "Egreso NG",
  "NIHSS": "NIHSS",
  "NIHSS severity": "Gravedad NIHSS",
  "NIHSS severity band": "Banda de gravedad NIHSS",
  "NIHSS total": "Total NIHSS",
  "NIHSS total score": "Puntuación total NIHSS",
  "NPO recommended": "NPO recomendado",
  "NPO status": "Estado NPO",
  "Nausea": "Náuseas",
  "Nausea/vomiting": "Náuseas/vómitos",
  "Need identified": "Necesidad identificada",
  "Nephrology notification": "Notificación a nefrología",
  "Nephrotoxic medication concern": "Preocupación por medicamento nefrotóxico",
  "Net balance": "Balance neto",
  "Neuro change": "Cambio neurológico",
  "Neuro stable": "Neuroestable",
  "Neuro status": "Estado neurológico",
  "Neurologic status": "Estado neurológico",
  "New deficit": "Nuevo déficit",
  "New flow": "Nuevo flujo",
  "No": "No",
  "Nutrition offered": "Nutrición ofrecida",
  "Obstruction concern": "Preocupación por obstrucción",
  "Occurrences": "Ocurrencias",
  "Open tasks reviewed": "Tareas abiertas revisadas",
  "Ordered": "Prescrito",
  "Ordered dose": "Dosis prescrita",
  "Ordered rate": "Ritmo prescrito",
  "Ordering provider": "Profesional prescriptor",
  "Orientation": "Orientación",
  "Outcome": "Resultado",
  "Output": "Egresos",
  "Oxygen": "Oxígeno",
  "Oxygen delivery": "Administración de oxígeno",
  "Oxygen desaturation": "Desaturación de oxígeno",
  "PERC negative": "PERC negativo",
  "Paced rhythm": "Ritmo estimulado",
  "Pain": "Dolor",
  "Pain (0-10)": "Dolor (0-10)",
  "Pain assessment": "Evaluación del dolor",
  "Pain controlled": "Dolor controlado",
  "Pain improved": "Dolor mejorado",
  "Pain score": "Puntuación del dolor",
  "Parameters": "Parámetros",
  "Partial": "Parcial",
  "Patient authorized": "Paciente autorizó",
  "Patient condition": "Estado del paciente",
  "Patient confirmed": "Paciente confirmado",
  "Patient disposition": "Disposición del paciente",
  "Patient educated": "Paciente educado",
  "Patient identity": "Identidad del paciente",
  "Patient participated": "El paciente participó",
  "Patient received": "Recibido por el paciente",
  "Patient safe": "Paciente en seguridad",
  "Patient stable": "Paciente estable",
  "Patient status": "Estado del paciente",
  "Patient tolerated": "Tolerado por el paciente",
  "Patient visible": "Paciente visible",
  "Pending": "Pendiente",
  "Pending results": "Resultados pendientes",
  "Persistent hypotension": "Hipotensión persistente",
  "Personal best": "Mejor personal",
  "Pharmacy notified": "Farmacia notificada",
  "Photo obtained": "Foto obtenida",
  "Physician order verified": "Orden médica verificada",
  "Placement verified": "Colocación verificada",
  "Planned level": "Nivel planificado",
  "Position": "Posición",
  "Post SpO₂": "SpO₂ posterior",
  "Post blood pressure": "PA posterior",
  "Post heart rate": "FC posterior",
  "Post temperature": "Temperatura posterior",
  "Post-treatment": "Postratamiento",
  "Pre-treatment": "Pretratamiento",
  "Precaution level": "Nivel de precaución",
  "Pressure injury present": "Lesión por presión presente",
  "Previous level": "Nivel anterior",
  "Previous score": "Puntuación anterior",
  "Previous → new": "Anterior → nuevo",
  "Primary signer": "Firmante primario",
  "Problem": "Problema",
  "Problem addressed": "Problema abordado",
  "Procedure confirmed": "Procedimiento confirmado",
  "Procedure held": "Procedimiento suspendido",
  "Procedure type": "Tipo de procedimiento",
  "Product": "Producto",
  "Programmed rate": "Ritmo programado",
  "Progress": "Progreso",
  "Provider approved": "Aprobado por el profesional clínico",
  "Provider evaluated": "Evaluado por el profesional clínico",
  "Provider notification": "Notificación al profesional clínico",
  "Provider notified": "Profesional clínico notificado",
  "Provider order verified": "Orden del profesional verificada",
  "Provider reviewed": "Revisado por el profesional clínico",
  "Provider updated": "Profesional clínico informado",
  "Pump verified": "Bomba verificada",
  "QTc": "QTc",
  "Quality": "Calidad",
  "ROSC achieved": "RCE logrado",
  "RR / SpO₂": "FR / SpO₂",
  "RT notified": "TR notificado",
  "Rapid response": "Respuesta rápida",
  "Rate": "Frecuencia",
  "Reaction observed": "Reacción observada",
  "Reaction outcome": "Resultado de la reacción",
  "Reaction status": "Estado de la reacción",
  "Reaction type": "Tipo de reacción",
  "Reason": "Motivo",
  "Reassessment": "Reevaluación",
  "Receipt number": "Número de recibo",
  "Received by security": "Recibido por seguridad",
  "Recipient": "Destinatario",
  "Recorded": "Registrado",
  "Recovery criteria met": "Criterios de recuperación cumplidos",
  "Relationship": "Relación",
  "Renal function concern": "Preocupación por función renal",
  "Renewal": "Renovación",
  "Repeat needed": "Repetición necesaria",
  "Resources offered": "Recursos ofrecidos",
  "Respiratory": "Respiratorio",
  "Respiratory rate": "Frecuencia respiratoria",
  "Response": "Respuesta",
  "Response received": "Respuesta recibida",
  "Responsible adult": "Adulto responsable",
  "Restart planned": "Reinicio planificado",
  "Restriction amount": "Cantidad de restricción",
  "Result": "Resultado",
  "Rhythm": "Ritmo",
  "Right pupil": "Pupila derecha",
  "Risk": "Riesgo",
  "Risk level": "Nivel de riesgo",
  "Room safety completed": "Seguridad de la habitación completada",
  "Route": "Vía",
  "SIRS criteria met": "Criterios SIRS cumplidos",
  "Safety": "Seguridad",
  "Safety check": "Verificación de seguridad",
  "Safety concern present": "Preocupación de seguridad presente",
  "Safety precautions initiated": "Precauciones de seguridad iniciadas",
  "Score": "Puntuación",
  "Scored": "Puntuado",
  "Screen performed": "Cribado realizado",
  "Screen positive": "Cribado positivo",
  "Sealed": "Sellado",
  "Second checker required": "Se requiere segundo verificador",
  "Secure area required": "Área segura requerida",
  "Securement": "Fijación",
  "Security bag ID": "ID de bolsa de seguridad",
  "Security notified": "Seguridad notificada",
  "Sedation level": "Nivel de sedación",
  "Seizure duration": "Duración de la convulsión",
  "Sets": "Series",
  "Severity": "Gravedad",
  "Shift": "Turno",
  "Shortness of breath": "Disnea",
  "Site": "Sitio",
  "Site confirmed": "Sitio confirmado",
  "Site status": "Estado del sitio",
  "Skin assessment": "Evaluación de la piel",
  "Skin intact": "Piel intacta",
  "Skin integrity": "Integridad cutánea",
  "Skin status": "Estado de la piel",
  "Sleep": "Sueño",
  "Source": "Origen",
  "SpO₂": "SpO₂",
  "SpO₂ after": "SpO₂ después",
  "SpO₂ before": "SpO₂ antes",
  "SpO₂ before / after": "SpO₂ antes / después",
  "Special requirements": "Requisitos especiales",
  "Stable vitals": "Signos vitales estables",
  "Stage": "Estadio",
  "Start": "Inicio",
  "Start time": "Hora de inicio",
  "Status": "Estado",
  "Steady gait": "Marcha estable",
  "Stoma appearance": "Aspecto del estoma",
  "Storage location": "Lugar de almacenamiento",
  "Stroke alert activated": "Alerta de ACV activada",
  "Substance": "Sustancia",
  "Successful": "Exitoso",
  "Suction": "Aspiración",
  "Suction active": "Aspiración activa",
  "Suspected infection": "Infección sospechada",
  "Suspected source": "Origen sospechado",
  "Symptomatic": "Sintomático",
  "Symptoms": "Síntomas",
  "Symptoms present": "Síntomas presentes",
  "System": "Sistema",
  "TNK administered": "TNK administrada",
  "Target level": "Nivel objetivo",
  "Teach-back completed": "Teach-back completado",
  "Temperature": "Temperatura",
  "Therapy": "Terapia",
  "Threat to others": "Amenaza para terceros",
  "Threat to self": "Amenaza para sí mismo",
  "Thrill": "Thrill",
  "Thrombolytic decision": "Decisión de trombólisis",
  "Thrombolytic given": "Trombólisis administrada",
  "Time": "Hora",
  "Timeout": "Time-out",
  "Timeout completed": "Time-out completado",
  "Titration": "Titulación",
  "Toileting offered": "Asistencia para ir al baño ofrecida",
  "Tolerance": "Tolerancia",
  "Tolerated": "Tolerado",
  "Topic": "Tema",
  "Total dose (mg)": "Dosis total (mg)",
  "Total score": "Puntuación total",
  "Transfusion completed": "Transfusión completada",
  "Transfusion link": "Vínculo de transfusión",
  "Transfusion stopped": "Transfusión detenida",
  "Transportation concern": "Preocupación por transporte",
  "Treatment": "Tratamiento",
  "Tube secure": "Tubo asegurado",
  "Tube type": "Tipo de sonda",
  "Two-staff inventory": "Inventario a dos personas",
  "Type": "Tipo",
  "Unable to assess reason": "Motivo de no evaluación",
  "Understanding demonstrated": "Comprensión demostrada",
  "Unit ID": "ID de unidad",
  "Unit volume (mL)": "Volumen de unidad (mL)",
  "Urine flow present": "Flujo urinario presente",
  "Valuables secured": "Objetos de valor asegurados",
  "Variance": "Variación",
  "Verification status": "Estado de verificación",
  "Violence risk": "Riesgo de violencia",
  "Vitals reviewed": "Signos vitales revisados",
  "Vitals stable": "Signos vitales estables",
  "Volume": "Volumen",
  "Volume (mL)": "Volumen (mL)",
  "Volume infused (mL)": "Volumen infundido (mL)",
  "Vomiting": "Vómitos",
  "Wallet / purse": "Cartera / bolso",
  "Weight": "Peso",
  "Weight (kg)": "Peso (kg)",
  "Wells PE score": "Puntuación Wells EP",
  "Witness": "Testigo",
  "Witness signer": "Firmante testigo",
  "Witnessed": "Presenciado",
  "Work of breathing": "Trabajo respiratorio",
  "Yes": "Sí",
  "qSOFA positive": "qSOFA positivo",
  "tPA administered": "tPA administrada",
  "Verified": "Verificado",
  "Draft": "Borrador",
  "Pending witness": "Testigo pendiente",
  "None reported": "Ninguno referido",
  "None": "Ninguno",
  "Suicidal ideation item positive": "Ítem de ideación suicida positivo",
  "facial asymmetry": "asimetría facial",
  "arm drift": "caída del brazo",
  "speech": "habla",
  "visual disturbance": "alteración visual",
  "aphasia": "afasia",
  "neglect": "negligencia",
  "Instructions": "Indicaciones",
  "Medications": "Medicamentos",
  "Follow-up": "Seguimiento",
  "Return precautions": "Precauciones de reconsulta",
  "Transportation": "Transporte",
  "Patient understanding": "Comprensión del paciente",
  "Changed": "Modificado",
  "No items checked": "Ningún elemento marcado",
  "Documentation type": "Tipo de documentación",
  "Structured payload saved": "Datos estructurados guardados",
  "Payload fields": "Campos del formulario",
  "Neuro Checks": "Controles neurológicos",
  "Motor Strength": "Fuerza motora",
  "Pupillary Assessment": "Evaluación pupilar",
  "RR": "FR",
  "Device": "Dispositivo",
  "Flow": "Flujo",
  "GCS": "GCS",
  "Geneva Score": "Puntuación de Ginebra",
  "HEART Score": "Puntuación HEART",
  "Revised Trauma Score": "Puntuación de trauma revisada",
  "Wells PE Score": "Puntuación Wells EP",
  "PERC Rule": "Regla PERC",
  "Suicide Screen": "Cribado de suicidio",
  "Behavioral Observation": "Observación conductual",
  "Respiratory Assessment": "Evaluación respiratoria",
  "Oxygen Therapy": "Oxigenoterapia",
  "Oxygen Titration": "Titulación de oxígeno",
  "CPAP / BiPAP": "CPAP / BiPAP",
  "Ventilator": "Ventilador",
  "Telemetry": "Telemetría",
  "Rhythm Strip": "Tira de ritmo",
  "ECG": "ECG",
  "QTc Monitoring": "Vigilancia de QTc",
  "Chest Pain": "Dolor torácico",
  "Elopement Assessment": "Evaluación de fuga",
  "Suicide Monitoring": "Vigilancia de suicidio",
  "1:1 Observation": "Observación 1:1",
  "Agitation Assessment": "Evaluación de agitación",
  "Behavioral Escalation": "Escalada conductual",
};
