/** MEDUI.ES.1K — Display-only Spanish for clinical documentation field options. */
export const CLINICAL_DOC_OPTION_LABEL_ES: Record<string, string> = {
  "10–59 min": "10–59 min",
  "< 10 min": "< 10 min",
  "Abnormal": "Anormal",
  "Absent": "Ausente",
  "Activated": "Activado",
  "Acute hemolytic": "Hemolítica aguda",
  "Adverse event": "Evento adverso",
  "Alert": "Alerta",
  "Alert; keenly responsive": "Alerta; respuesta viva",
  "Allergic": "Alérgica",
  "Altered mental status": "Estado mental alterado",
  "Anaphylactic": "Anafiláctica",
  "Answers both questions correctly": "Responde ambas preguntas correctamente",
  "Answers neither question correctly": "No responde ninguna pregunta correctamente",
  "Answers one question correctly": "Responde una pregunta correctamente",
  "Antiarrhythmic": "Antiarrítmico",
  "Aphasia": "Afasia",
  "Assistive device": "Dispositivo de asistencia",
  "Back pain": "Dolor de espalda",
  "Bedpan": "Chata",
  "Behavioral": "Conductual",
  "Bilateral hemianopia": "Hemianopsia bilateral",
  "Bilious": "Biliar",
  "Black/tarry": "Negra/alquitranada",
  "Bloody": "Sangrante",
  "Bradycardia": "Bradicardia",
  "CMV negative": "CMV negativo",
  "Calm": "Calmado",
  "Central line": "Línea central",
  "Chemotherapy": "Quimioterapia",
  "Chest pain": "Dolor torácico",
  "Chills": "Escalofríos",
  "Clamped": "Pinzado",
  "Clear": "Claro",
  "Clinical response": "Respuesta clínica",
  "Coffee ground": "Posos de café",
  "Complete hemianopia": "Hemianopsia completa",
  "Complete paralysis of one or both sides": "Parálisis completa de uno o ambos lados",
  "Confirmed": "Confirmado",
  "Continued": "Continuado",
  "Cryo": "Crioprecipitado",
  "Cryoprecipitate": "Crioprecipitado",
  "Deactivated": "Desactivado",
  "Decreased": "Disminuido",
  "Deferred": "Diferido",
  "Disoriented": "Desorientado",
  "Drift": "Caída",
  "Drowsy": "Somnoliento",
  "Dysarthria": "Disartria",
  "Dyspnea": "Disnea",
  "Enteral": "Enteral",
  "Environmental modification": "Modificación ambiental",
  "Equal and reactive": "Iguales y reactivas",
  "Escalated": "Escalado",
  "FFP": "PFC",
  "Failed": "Fallido",
  "Fall risk": "Riesgo de caída",
  "Family presence": "Presencia familiar",
  "Febrile non-hemolytic": "Febril no hemolítica",
  "Feet": "Pies",
  "Fever": "Fiebre",
  "Foley": "Foley",
  "Follows commands": "Sigue órdenes",
  "Food content": "Contenido alimentario",
  "Forced deviation": "Desviación forzada",
  "Formed": "Formada",
  "Gravity": "Gravedad",
  "Hemoglobinuria": "Hemoglobinuria",
  "Heparin": "Heparina",
  "High-dose magnesium": "Magnesio a dosis alta",
  "High-dose potassium": "Potasio a dosis alta",
  "Hypoglycemia": "Hipoglucemia",
  "Hypotension": "Hipotensión",
  "IV": "IV",
  "Improved": "Mejorado",
  "Insulin": "Insulina",
  "Intact": "Integro",
  "Interference with care": "Interfiere con la atención",
  "Irradiated": "Irradiado",
  "L": "L",
  "Leukoreduced": "Leucorreducido",
  "Line issue": "Problema de línea",
  "Loose": "Suelta",
  "Low continuous": "Baja continua",
  "Low intermittent": "Baja intermitente",
  "Medical": "Médica",
  "Medical devices secure": "Dispositivos médicos asegurados",
  "Medication": "Medicamento",
  "Meters": "Metros",
  "Mild to moderate aphasia": "Afasia leve a moderada",
  "Mild to moderate dysarthria": "Disartria leve a moderada",
  "Mild-to-moderate sensory loss": "Pérdida sensitiva leve a moderada",
  "Minor paralysis": "Parálisis menor",
  "Mute; global aphasia": "Mudez; afasia global",
  "Nausea": "Náuseas",
  "No": "No",
  "No abnormality": "Sin anomalía",
  "No aphasia; normal": "Sin afasia; normal",
  "No drift": "Sin caída",
  "No effort against gravity; limb falls": "Sin esfuerzo contra gravedad; la extremidad cae",
  "No longer a danger": "Ya no representa peligro",
  "No movement": "Sin movimiento",
  "No reaction": "Sin reacción",
  "No visual loss": "Sin pérdida visual",
  "Non-reactive": "No reactivo",
  "None": "Ninguno",
  "Normal": "Normal",
  "Normal strength": "Fuerza normal",
  "Normal symmetric movements": "Movimientos simétricos normales",
  "Normal; no sensory loss": "Normal; sin pérdida sensitiva",
  "Not alert; arousable by minor stimulation": "No alerta; despertable con estímulo menor",
  "Not alert; requires repeated stimulation": "No alerta; requiere estímulo repetido",
  "One person": "Una persona",
  "Oral": "Oral",
  "Oriented ×1": "Orientado ×1",
  "Oriented ×2": "Orientado ×2",
  "Oriented ×3": "Orientado ×3",
  "Oriented ×4": "Orientado ×4",
  "Other": "Otro",
  "Other high-alert": "Otra alta alerta",
  "PCA": "PCA",
  "PRBC": "GRC",
  "Paralysis": "Parálisis",
  "Partial": "Parcial",
  "Partial gaze palsy": "Parálisis de la mirada parcial",
  "Partial hemianopia": "Hemianopsia parcial",
  "Partial paralysis": "Parálisis parcial",
  "Passed": "Aprobado",
  "Performs both tasks correctly": "Realiza ambas tareas correctamente",
  "Performs neither task correctly": "No realiza ninguna tarea correctamente",
  "Performs one task correctly": "Realiza una tarea correctamente",
  "Physical": "Física",
  "Platelets": "Plaquetas",
  "Present in one limb": "Presente en una extremidad",
  "Present in two limbs": "Presente en dos extremidades",
  "Profound hemi-inattention or extinction": "Hemi-inatención o extinción profunda",
  "Protocol": "Protocolo",
  "Provider order": "Orden del profesional",
  "Pruritus": "Prurito",
  "Pulling lines": "Tira de las líneas",
  "Pulling tubes": "Tira de las sondas",
  "Purulent": "Purulento",
  "Rash": "Erupción",
  "Redirection": "Redirección",
  "Reorientation": "Reorientación",
  "Sanguineous": "Sanguinolento",
  "Seclusion": "Aislamiento",
  "Sedative": "Sedante",
  "Self-destructive": "Autodestructivo",
  "Serosanguineous": "Serosanguinolento",
  "Serous": "Seroso",
  "Severe aphasia": "Afasia grave",
  "Severe dysarthria": "Disartria grave",
  "Severe to total sensory loss": "Pérdida sensitiva grave o total",
  "Sitter": "Acompañante",
  "Some effort against gravity": "Algún esfuerzo contra gravedad",
  "Speech without weakness": "Habla sin debilidad",
  "Standby": "En espera",
  "Steps": "Pasos",
  "Stopped": "Detenido",
  "Straight cath": "Sondaje intermitente",
  "Stuporous": "Estuporoso",
  "Subcutaneous": "Subcutáneo",
  "Suspected": "Sospechado",
  "TACO": "TACO",
  "TRALI": "TRALI",
  "Two people": "Dos personas",
  "Unable to assess": "No evaluable",
  "Unchanged": "Sin cambios",
  "Unequal": "Desiguales",
  "Unilateral weakness": "Debilidad unilateral",
  "Unknown": "Desconocido",
  "Unresponsive": "Sin respuesta",
  "Unresponsive or reflex response only": "Sin respuesta o solo reflejos",
  "Urinal": "Orinal",
  "Urticaria": "Urticaria",
  "Vasopressor": "Vasopresor",
  "Verbal de-escalation": "Desescalada verbal",
  "Violent behavior": "Conducta violenta",
  "Visual, tactile, auditory, spatial, or personal inattention": "Inatención visual, táctil, auditiva, espacial o personal",
  "Voided": "Micción espontánea",
  "Washed": "Lavado",
  "Watery": "Acuosa",
  "Weak": "Débil",
  "Weakness": "Debilidad",
  "Wheezing": "Sibilancias",
  "Whole blood": "Sangre total",
  "Worsened": "Empeorado",
  "Yes": "Sí",
  "cc": "cc",
  "mL": "mL",
  "oz": "oz",
  "≥ 60 min": "≥ 60 min",
};
