/** MEDUI.CP.1F.1 — canonical Care Plan template clinical text (FR). */
export const enterpriseCarePlanTemplateClinicalTextFr = {
    fallRisk: {
      title: "Risque de chute",
      description:
        "Prévenir les chutes et blessures par précautions au lit, soutien à la mobilité et éducation.",
      focus: "Focus — risque de chute",
      focusBody: "Le patient présente un risque élevé de chute pendant cette rencontre.",
      goal: "Objectif — aucune chute avec blessure",
      goalBody: "Le patient restera sans chute avec blessure durant le séjour.",
      outcome: "Résultat — mobilité sécuritaire",
      outcomeBody: "Transferts et marche sécuritaires avec aide appropriée.",
      intervention: "Intervention — précautions anti-chute",
      interventionBody:
        "Sonnette à portée ; aide aux transferts ; chaussures antidérapantes ; lit bas.",
      monitoring: "Surveillance — réévaluation du risque de chute",
      monitoringBody: "Réévaluer le risque de chute à chaque quart et après changement d’état.",
      education: "Éducation — appeler avant de se lever",
      educationBody: "Enseigner au patient/famille d’appeler avant de se lever.",
      safety: "Recommandation de sécurité — précautions anti-chute",
      safetyBody:
        "Recommander des précautions anti-chute. N’autorise pas indépendamment contention ou isolement.",
    },
    aspirationRisk: {
      title: "Risque d’aspiration",
      description:
        "Réduire le risque d’aspiration avec dépistage, précautions alimentaires et collaboration orthophonie.",
      focus: "Focus — risque d’aspiration",
      focusBody:
        "Le patient est à risque d’aspiration lié à une déglutition altérée ou à une conscience altérée.",
      goal: "Objectif — aucun événement d’aspiration",
      goalBody: "Le patient restera sans aspiration observée pendant la rencontre.",
      outcome: "Résultat — prise orale sécuritaire si indiquée",
      outcomeBody: "Prise orale seulement lorsque le dépistage/évaluation le permet.",
      intervention: "Intervention — précautions alimentaires",
      interventionBody:
        "Position semi-assise ; supervision des repas si indiqué ; suivre le dépistage de déglutition.",
      monitoring: "Surveillance — signes respiratoires aux repas",
      monitoringBody: "Surveiller toux, désaturation ou changement de voix à la prise orale.",
      education: "Éducation — précautions d’aspiration",
      educationBody: "Enseigner le positionnement et quand interrompre la prise orale.",
      safety: "Recommandation de sécurité — précautions d’aspiration",
      safetyBody:
        "Recommander des précautions d’aspiration. N’active pas l’isolement et ne change pas le régime.",
    },
    acutePain: {
      title: "Douleur aiguë",
      description:
        "Évaluer, réévaluer et soutenir le confort sans prescrire ni administrer via le plan.",
      focus: "Focus — douleur aiguë",
      focusBody:
        "Le patient signale ou présente des signes de douleur aiguë nécessitant un plan infirmier structuré.",
      goal: "Objectif — confort acceptable",
      goalBody: "Le patient rapporte une douleur acceptable pour l’activité et le repos.",
      outcome: "Résultat — fonction avec confort",
      outcomeBody: "Le patient participe aux soins nécessaires avec un inconfort tolérable.",
      intervention: "Intervention — confort non pharmacologique",
      interventionBody:
        "Positionnement, froid/chaleur si prescrit ailleurs, environnement calme. Le plan ne prescrit ni n’administre de médicaments.",
      monitoring: "Surveillance — réévaluation de la douleur",
      monitoringBody:
        "Réévaluer la douleur après interventions selon la pratique.",
      education: "Éducation — signaler la douleur tôt",
      educationBody: "Enseigner au patient de signaler la douleur avant qu’elle ne devienne sévère.",
    },
    pneumonia: {
      title: "Pneumonie",
      description:
        "Soutenir la récupération respiratoire avec surveillance, mobilisation et collaboration RT — soins respiratoires de soutien.",
      focus: "Focus — soins de pneumonie",
      focusBody:
        "Le patient a une pneumonie ou une infection respiratoire basse suspectée nécessitant un soutien interdisciplinaire.",
      goal: "Objectif — meilleure oxygénation et clairance",
      goalBody:
        "Le patient montrera une amélioration de l’effort respiratoire et de la clairance des sécrétions selon le contexte clinique.",
      outcome: "Résultat — état respiratoire stable",
      outcomeBody: "SpO2 stable et détresse réduite par rapport au début de cette maladie.",
      intervention: "Intervention — hygiène pulmonaire",
      interventionBody:
        "Encourager la respiration profonde, la mobilité selon tolérance, et la collaboration RT.",
      monitoring: "Surveillance — signes vitaux et effort respiratoire",
      monitoringBody: "Surveiller fréquence respiratoire, SpO2 et effort selon le protocole.",
      education: "Éducation — respiration et récupération",
      educationBody: "Enseigner les techniques respiratoires et quand signaler une dyspnée aggravée.",
    },
    chf: {
      title: "Insuffisance cardiaque (IC)",
      description:
        "Surveillance liquidienne et symptomatique avec éducation de soutien.",
      focus: "Focus — insuffisance cardiaque",
      focusBody:
        "Le patient présente une exacerbation d’insuffisance cardiaque ou un risque de décompensation.",
      goal: "Objectif — euvolemie vers le baseline",
      goalBody:
        "Le patient progressera vers son état liquidien de base sans signes évitables de surcharge.",
      outcome: "Résultat — contrôle des symptômes",
      outcomeBody: "Dyspnée et œdème réduits par rapport à l’admission lorsque cliniquement attendu.",
      intervention: "Intervention — poids quotidiens et positionnement",
      interventionBody:
        "Poids quotidiens, tête de lit élevée, et activité selon tolérance.",
      monitoring: "Surveillance — poids, entrées/sorties, respiration",
      monitoringBody: "Suivre la tendance du poids, les E/S et les symptômes respiratoires à chaque quart.",
      education: "Éducation — poids et sodium",
      educationBody:
        "Enseigner le suivi du poids quotidien et quand signaler une prise rapide ou une dyspnée aggravée.",
    },
    impairedMobility: {
      title: "Mobilité altérée",
      description:
        "Coordonner soins infirmiers, PT/OT et aide technicien pour une mobilité sécuritaire sans fusionner les disciplines.",
      focus: "Focus — mobilité altérée",
      focusBody: "Le patient a une mobilité limitée nécessitant un soutien interdisciplinaire structuré.",
      goal: "Objectif — mobilité progressive sécuritaire",
      goalBody: "Le patient augmentera sa mobilité sécuritaire avec le niveau d’aide approprié.",
      outcome: "Résultat — progrès des transferts et de la marche",
      outcomeBody: "Progrès documentés des transferts/marche sans chute avec blessure.",
      intervention: "Intervention — mobilité assistée",
      interventionBody:
        "Aider selon les consignes PT/OT et l’évaluation infirmière. Les recommandations d’équipement ne sont pas un achat.",
      monitoring: "Surveillance — tolérance à l’activité",
      monitoringBody: "Surveiller fatigue, étourdissements et intégrité cutanée lors des essais de mobilité.",
      education: "Éducation — techniques de transfert sécuritaires",
      educationBody: "Enseigner au patient/famille les transferts sécuritaires et l’usage d’aides techniques.",
    },
    pressureInjuryRisk: {
      title: "Risque d’escarre",
      description:
        "Protection cutanée et sensibilisation au changement de position — les évaluations de plaies restent infirmières.",
      focus: "Focus — risque d’escarre",
      focusBody: "Le patient est à risque d’escarre lié à l’immobilité ou à une vulnérabilité cutanée.",
      goal: "Objectif — peau intacte",
      goalBody:
        "Le patient conservera une peau intacte ou n’aura pas de nouvelles escarres liées à des lacunes de soins.",
      outcome: "Résultat — points de pression protégés",
      outcomeBody: "Les points de pression restent sans nouvelle lésion de stade 2 ou plus.",
      intervention: "Intervention — repositionnement et décharge",
      interventionBody:
        "Repositionner selon l’horaire ; décharger les talons ; peau propre et sèche.",
      monitoring: "Surveillance — inspection cutanée",
      monitoringBody: "Inspecter les points de pression à chaque quart ; escalader les nouveautés à l’évaluation infirmière.",
      education: "Éducation — importance du repositionnement",
      educationBody: "Enseigner pourquoi le repositionnement fréquent est important.",
      safety: "Recommandation de sécurité — protection cutanée",
      safetyBody: "Recommander des précautions anti-escarre. N’autorise pas la contention.",
    },
    dischargeReadiness: {
      title: "Préparation à la sortie (partiel)",
      description:
        "Liste de contrôle et éducation vers la préparation ( CM/TS/UR).",
      focus: "Focus — préparation à la sortie",
      focusBody: "Le patient nécessite une préparation structurée pour une transition de soins sécuritaire.",
      goal: "Objectif — enseignement et obstacles identifiés",
      goalBody:
        "Enseignements clés complétés et obstacles à une sortie sécuritaire identifiés pour l’équipe.",
      outcome: "Résultat — documentation de préparation",
      outcomeBody:
        "Statut de préparation documenté pour la transmission à la planification de sortie — ce n’est pas une autorisation.",
      intervention: "Intervention — teach-back et revue des obstacles",
      interventionBody:
        "Compléter le teach-back sur médicaments, suivi et signes d’alerte. Identifier les freins à une transition sûre.",
      monitoring: "Surveillance — obstacles restants",
      monitoringBody:
        "Suivre les obstacles d’éducation, d’équipement ou sociaux comme recommandations seulement.",
      education: "Éducation — essentiels après les soins",
      educationBody: "Revoir les essentiels après les soins avec teach-back.",
    },
    seizurePrecautions: {
      title: "Précautions convulsives",
      description: "Documentation de sécurité de soutien pour le risque convulsif.",
      focus: "Focus clinique",
      focusBody: "Documentation de sécurité de soutien pour le risque convulsif.",
      goal: "Objectif",
      goalBody: "Le patient reste sans blessure liée à une activité convulsive.",
      outcome: "Résultats attendus",
      outcomeBody: "L’activité convulsive et les réponses de sécurité sont documentées rapidement.\nAucune blessure imprévue liée à une crise, ou les événements sont rapidement escaladés.",
      intervention: "Interventions",
      interventionBody: "Maintenir un environnement sûr ; protéger les barrières si approprié ; garder aspiration/oxygène disponibles selon ordonnances séparées ; escalader immédiatement.",
      monitoring: "Surveillance",
      monitoringBody: "Surveiller aura, activité convulsive, blessures et état post-critique.",
      education: "Éducation",
      educationBody: "Enseigner les premiers secours en cas de crise et quand appeler à l’aide.",
      safety: "Recommandations de sécurité",
      safetyBody: "Maintenir les précautions convulsives et escalader rapidement une activité convulsive.",
    },
    bleedingRisk: {
      title: "Risque hémorragique",
      description: "Surveillance de soutien pour un risque hémorragique élevé.",
      focus: "Focus clinique",
      focusBody: "Surveillance de soutien pour un risque hémorragique élevé.",
      goal: "Objectif",
      goalBody: "Les signes précoces de saignement sont reconnus et signalés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les sites de saignement et les tendances des constantes sont documentés à chaque quart.\nLes saignements majeurs sont rapidement escaladés.",
      intervention: "Interventions",
      interventionBody: "Inspecter les sites ; soins doux ; éviter les traumatismes inutiles ; coordonner avec le médecin pour laboratoires ou produits séparément.",
      monitoring: "Surveillance",
      monitoringBody: "Surveiller constantes, sites de saignement, tendances d’hémoglobine si disponibles, et symptômes d’hypovolémie.",
      education: "Éducation",
      educationBody: "Enseigner les précautions et signes d’alerte à signaler.",
      safety: "Recommandations de sécurité",
      safetyBody: "Escalader rapidement un saignement et coordonner avec l’équipe.",
    },
    infectionPrevention: {
      title: "Prévention des infections",
      description: "Soins de soutien pour la prévention des infections.",
      focus: "Focus clinique",
      focusBody: "Soins de soutien pour la prévention des infections.",
      goal: "Objectif",
      goalBody: "Les risques de transmission sont minimisés par des pratiques documentées.",
      outcome: "Résultats attendus",
      outcomeBody: "L’hygiène des mains et les soins des dispositifs sont renforcés à chaque quart.",
      intervention: "Interventions",
      interventionBody: "Renforcer l’hygiène des mains, l’asepsie des dispositifs et la reconnaissance précoce des signes d’infection.",
      monitoring: "Surveillance",
      monitoringBody: "Surveiller température, nouveaux écoulements, sites de dispositifs et symptômes systémiques.",
      education: "Éducation",
      educationBody: "Éduquer patient/visiteurs sur l’hygiène et l’étiquette de toux.",
      safety: "Recommandations de sécurité",
      safetyBody: "Suivre les pratiques d’isolement déjà en vigueur.",
    },
    deliriumSafety: {
      title: "Sécurité délire / confusion",
      description: "Soutiens de sécurité pour délire ou confusion aiguë.",
      focus: "Focus clinique",
      focusBody: "Soutiens de sécurité pour délire ou confusion aiguë.",
      goal: "Objectif",
      goalBody: "Le patient reste sans blessure liée à la confusion.",
      outcome: "Résultats attendus",
      outcomeBody: "La réorientation et les mesures de sécurité sont documentées à chaque quart.",
      intervention: "Interventions",
      interventionBody: "Fournir une réorientation calme, des repères familiers, coordonner les précautions de chute et escalader l’agitation tôt.",
      monitoring: "Surveillance",
      monitoringBody: "Surveiller orientation, rythme veille-sommeil, agitation et événements de sécurité.",
      education: "Éducation",
      educationBody: "Enseigner à la famille comment aider à la réorientation sans surstimulation.",
      safety: "Recommandations de sécurité",
      safetyBody: "Protéger la sécurité ; escalader l’agitation tôt.",
    },
    impairedGasExchange: {
      title: "Échanges gazeux altérés",
      description: "Documentation de soutien pour les préoccupations d’oxygénation.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les préoccupations d’oxygénation.",
      goal: "Objectif",
      goalBody: "Le patient maintient l’oxygénation dans la cible définie cliniquement.",
      outcome: "Résultats attendus",
      outcomeBody: "La saturation reste dans la cible propre au patient.\nLa détresse respiratoire ne s’aggrave pas.\nLe travail respiratoire s’améliore lorsque applicable.",
      intervention: "Interventions",
      interventionBody: "Évaluer le statut respiratoire à intervalles appropriés ; positionner pour optimiser la ventilation ; renforcer l’hygiène pulmonaire ; coordonner avec la RT si indiqué.",
      monitoring: "Surveillance",
      monitoringBody: "Saturation, fréquence respiratoire, travail respiratoire et changements de l’état mental.",
      education: "Éducation",
      educationBody: "Expliquer les mesures d’oxygène/sécurité et renforcer les exercices respiratoires si approprié.",
    },
    ineffectiveAirwayClearance: {
      title: "Clairance des voies aériennes inefficace",
      description: "Soutien pour la gestion des sécrétions et la clairance des voies aériennes.",
      focus: "Focus clinique",
      focusBody: "Soutien pour la gestion des sécrétions et la clairance des voies aériennes.",
      goal: "Objectif",
      goalBody: "Les voies aériennes restent libres avec une clairance efficace des sécrétions.",
      outcome: "Résultats attendus",
      outcomeBody: "L’efficacité de la toux et les caractéristiques des sécrétions sont documentées.",
      intervention: "Interventions",
      interventionBody: "Encourager toux/respiration profonde ; aider au positionnement ; coordonner aspiration/RT selon ordonnances séparées.",
      monitoring: "Surveillance",
      monitoringBody: "Bruits respiratoires, expectorations, SpO2 et détresse.",
      education: "Éducation",
      educationBody: "Enseigner une toux efficace et quand demander de l’aide.",
    },
    copdExacerbation: {
      title: "Exacerbation de BPCO",
      description: "Documentation de soins de soutien pendant une exacerbation de BPCO.",
      focus: "Focus clinique",
      focusBody: "Documentation de soins de soutien pendant une exacerbation de BPCO.",
      goal: "Objectif",
      goalBody: "La détresse respiratoire s’améliore ou se stabilise avec les soins de soutien.",
      outcome: "Résultats attendus",
      outcomeBody: "Le schéma respiratoire et les tendances d’oxygénation sont suivis à chaque quart.",
      intervention: "Interventions",
      interventionBody: "Évaluer la détresse ; optimiser le positionnement ; renforcer les techniques respiratoires ; collaborer avec RT/médecin.",
      monitoring: "Surveillance",
      monitoringBody: "Fréquence respiratoire, SpO2, muscles accessoires et état mental.",
      education: "Éducation",
      educationBody: "Renforcer l’éducation inhalateur/respiration sans modifier les prescriptions.",
    },
    asthmaExacerbation: {
      title: "Exacerbation d’asthme",
      description: "Documentation de soutien pour une exacerbation d’asthme.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour une exacerbation d’asthme.",
      goal: "Objectif",
      goalBody: "Sibilances et travail respiratoire s’améliorent vers le niveau de base.",
      outcome: "Résultats attendus",
      outcomeBody: "Les symptômes de pic et la réponse aux thérapies ordonnées sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller la détresse ; soutenir une respiration calme ; escalader l’aggravation.",
      monitoring: "Surveillance",
      monitoringBody: "Sibilances, SpO2, fréquence respiratoire et capacité à parler.",
      education: "Éducation",
      educationBody: "Revoir l’évitement des déclencheurs et l’éducation au plan d’action.",
    },
    oxygenTherapySupport: {
      title: "Soutien à l’oxygénothérapie",
      description: "Documentation autour de l’oxygénothérapie ordonnée.",
      focus: "Focus clinique",
      focusBody: "Documentation autour de l’oxygénothérapie ordonnée.",
      goal: "Objectif",
      goalBody: "L’administration d’oxygène correspond à la cible ordonnée et est tolérée.",
      outcome: "Résultats attendus",
      outcomeBody: "L’ajustement du dispositif, SpO2 et la peau sous le dispositif sont vérifiés.",
      intervention: "Interventions",
      interventionBody: "Vérifier dispositif/débit ordonnés ; évaluer confort et peau ; escalader la désaturation. Escalader rapidement la désaturation.",
      monitoring: "Surveillance",
      monitoringBody: "SpO2, intégrité du dispositif et peau nasale/oreilles.",
      education: "Éducation",
      educationBody: "Enseigner la sécurité de l’oxygène (pas de tabac, vigilance aux tubulures).",
    },
    pulmonaryHygiene: {
      title: "Hygiène pulmonaire / spirométrie incitative",
      description: "Soutien à l’éducation et l’accompagnement d’hygiène pulmonaire.",
      focus: "Focus clinique",
      focusBody: "Soutien à l’éducation et l’accompagnement d’hygiène pulmonaire.",
      goal: "Objectif",
      goalBody: "Le patient réalise l’hygiène pulmonaire autant que possible à chaque quart.",
      outcome: "Résultats attendus",
      outcomeBody: "La spirométrie incitative ou efforts équivalents sont documentés.",
      intervention: "Interventions",
      interventionBody: "Accompagner respiration profonde/IS ; mobiliser si approprié ; coordonner RT si indiqué.",
      monitoring: "Surveillance",
      monitoringBody: "Tolérance à l’effort, SpO2 et symptômes pulmonaires.",
      education: "Éducation",
      educationBody: "Enseigner la technique et la fréquence attendue.",
    },
    decreasedCardiacOutput: {
      title: "Débit cardiaque diminué",
      description: "Surveillance de soutien pour les signes de débit cardiaque réduit.",
      focus: "Focus clinique",
      focusBody: "Surveillance de soutien pour les signes de débit cardiaque réduit.",
      goal: "Objectif",
      goalBody: "Une perfusion tissulaire adéquate est soutenue et la détérioration est reconnue tôt.",
      outcome: "Résultats attendus",
      outcomeBody: "Les tendances des constantes et de la perfusion sont documentées et escaladées en cas d’aggravation.",
      intervention: "Interventions",
      interventionBody: "Évaluer perfusion, œdème et tolérance à l’activité ; escalader les signes de choc.",
      monitoring: "Surveillance",
      monitoringBody: "Fréquence cardiaque, tension, état mental, diurèse si disponible, et perfusion cutanée.",
      education: "Éducation",
      educationBody: "Enseigner le rythme d’activité et les signes d’alerte à signaler.",
    },
    acsChestPainSupport: {
      title: "SCA / soutien douleur thoracique",
      description: "Documentation de soins de soutien pour douleur thoracique.",
      focus: "Focus clinique",
      focusBody: "Documentation de soins de soutien pour douleur thoracique.",
      goal: "Objectif",
      goalBody: "Les épisodes de douleur thoracique sont rapidement reconnus, documentés et escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Caractéristiques de la douleur, constantes et réponse aux thérapies ordonnées sont enregistrées.",
      intervention: "Interventions",
      interventionBody: "Maintenir le repos pendant la douleur ; prendre les constantes ; escalader immédiatement ; escalader immédiatement.",
      monitoring: "Surveillance",
      monitoringBody: "Intensité de la douleur, préoccupations ECG si ordonnées, constantes et récurrence des symptômes.",
      education: "Éducation",
      educationBody: "Enseigner quand signaler une douleur thoracique ou de nouveaux symptômes.",
    },
    hypertensionMonitoring: {
      title: "Surveillance de l’hypertension",
      description: "Documentation de soutien pour la surveillance de la tension artérielle.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la surveillance de la tension artérielle.",
      goal: "Objectif",
      goalBody: "Les tendances de tension sont suivies et les changements significatifs escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les mesures de TA et symptômes associés sont documentés à chaque quart selon indication.",
      intervention: "Interventions",
      interventionBody: "Mesurer la TA selon la pratique clinique ; noter les symptômes ; escalader les signes d’urgence hypertensive.",
      monitoring: "Surveillance",
      monitoringBody: "Tension, fréquence cardiaque, céphalées, changements visuels et symptômes thoraciques.",
      education: "Éducation",
      educationBody: "Renforcer l’éducation mode de vie et observance sans modifier les prescriptions.",
    },
    fluidVolumeExcess: {
      title: "Excès de volume liquidien",
      description: "Documentation de soutien pour les préoccupations de surcharge volémique.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les préoccupations de surcharge volémique.",
      goal: "Objectif",
      goalBody: "L’équilibre liquidien et le confort respiratoire sont soutenus.",
      outcome: "Résultats attendus",
      outcomeBody: "Poids, œdème et tendances respiratoires sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller entrées/sorties et œdème ; surélever les jambes si approprié ; escalader la détresse respiratoire.",
      monitoring: "Surveillance",
      monitoringBody: "Poids quotidien si ordonné, œdème, bruits pulmonaires et SpO2.",
      education: "Éducation",
      educationBody: "Enseigner la vigilance liquides/sodium selon le plan de l’équipe.",
    },
    strokeSupportive: {
      title: "Soins de soutien AVC aigu",
      description: "Documentation de soutien après AVC.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien après AVC.",
      goal: "Objectif",
      goalBody: "Les changements neurologiques sont détectés tôt et escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les examens neuro et déficits fonctionnels sont documentés selon ordonnance/indication.",
      intervention: "Interventions",
      interventionBody: "Réaliser les évaluations neuro ordonnées ; protéger voies aériennes/déglutition ; coordonner la rééducation.",
      monitoring: "Surveillance",
      monitoringBody: "Statut neuro, paramètres tensionnels si ordonnés, sécurité de déglutition et nouveaux déficits.",
      education: "Éducation",
      educationBody: "Enseigner à la famille les signes d’alerte et le plan de collaboration thérapeutique.",
    },
    alteredMentalStatus: {
      title: "État mental altéré",
      description: "Documentation de soutien pour un changement aigu de l’état mental.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour un changement aigu de l’état mental.",
      goal: "Objectif",
      goalBody: "L’état mental de base est clarifié et la détérioration est escaladée.",
      outcome: "Résultats attendus",
      outcomeBody: "Les changements d’orientation et de comportement sont documentés à chaque quart.",
      intervention: "Interventions",
      interventionBody: "Réorienter calmement ; protéger la sécurité ; escalader un déclin soudain.",
      monitoring: "Surveillance",
      monitoringBody: "Orientation, agitation, constantes et préoccupations glycémiques si disponibles.",
      education: "Éducation",
      educationBody: "Informer la famille des besoins d’observation et de sécurité.",
    },
    neurologicMonitoring: {
      title: "Surveillance neurologique",
      description: "Documentation d’observation neurologique de soutien structurée.",
      focus: "Focus clinique",
      focusBody: "Documentation d’observation neurologique de soutien structurée.",
      goal: "Objectif",
      goalBody: "Les tendances neurologiques sont suivies et les changements aigus escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les examens neuro ordonnés sont réalisés et enregistrés.",
      intervention: "Interventions",
      interventionBody: "Réaliser les évaluations neuro aux intervalles indiqués ; escalader immédiatement tout nouveau signe focal.",
      monitoring: "Surveillance",
      monitoringBody: "Niveau de conscience, force motrice, parole et pupilles lorsque évalués.",
      education: "Éducation",
      educationBody: "Expliquer le but des examens neuro fréquents au patient/famille.",
    },
    deliriumPrevention: {
      title: "Prévention du délire",
      description: "Documentation de soutien non pharmacologique pour la prévention du délire.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien non pharmacologique pour la prévention du délire.",
      goal: "Objectif",
      goalBody: "Les risques modifiables de délire sont abordés à chaque quart.",
      outcome: "Résultats attendus",
      outcomeBody: "Sommeil, orientation, mobilité et aides sensorielles sont soutenus autant que possible.",
      intervention: "Interventions",
      interventionBody: "Promouvoir les repères jour/nuit, la mobilisation précoce si approprié, aides auditives/visuelles et présence familiale si utile.",
      monitoring: "Surveillance",
      monitoringBody: "Schéma de sommeil, orientation et nouvelle confusion.",
      education: "Éducation",
      educationBody: "Enseigner à la famille les stratégies de réorientation.",
    },
    nauseaVomiting: {
      title: "Nausées / vomissements",
      description: "Documentation symptomatique de soutien pour nausées et vomissements.",
      focus: "Focus clinique",
      focusBody: "Documentation symptomatique de soutien pour nausées et vomissements.",
      goal: "Objectif",
      goalBody: "Les nausées sont réduites et l’hydratation/confort sont soutenus.",
      outcome: "Résultats attendus",
      outcomeBody: "Les épisodes d’émèse, les apports et la réponse symptomatique sont documentés.",
      intervention: "Interventions",
      interventionBody: "Offrir des soins buccaux ; positionner pour le confort ; escalader les vomissements incoercibles.",
      monitoring: "Surveillance",
      monitoringBody: "Score/symptômes de nausée, quantité/caractère des vomissements et tolérance alimentaire.",
      education: "Éducation",
      educationBody: "Enseigner les petites gorgées et les signes d’alerte.",
    },
    diarrhea: {
      title: "Diarrhée",
      description: "Documentation de soutien pour la diarrhée et risques associés.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la diarrhée et risques associés.",
      goal: "Objectif",
      goalBody: "Les pertes liquidiennes et l’intégrité cutanée périnéale sont gérées de façon supportive.",
      outcome: "Résultats attendus",
      outcomeBody: "Fréquence/caractère des selles et statut d’hydratation sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller les selles ; protéger la peau ; escalader selles sanglantes ou signes de déshydratation sévère.",
      monitoring: "Surveillance",
      monitoringBody: "Fréquence des selles, hydratation et peau périnéale.",
      education: "Éducation",
      educationBody: "Enseigner l’hygiène des mains et la vigilance sur le remplacement liquidien.",
    },
    constipation: {
      title: "Constipation",
      description: "Documentation de soutien pour la gestion intestinale.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la gestion intestinale.",
      goal: "Objectif",
      goalBody: "Le transit revient vers le niveau de base sans complications évitables.",
      outcome: "Résultats attendus",
      outcomeBody: "Dernière selle et symptômes sont documentés.",
      intervention: "Interventions",
      interventionBody: "Encourager mobilité/liquides si approprié ; escalader une douleur abdominale sévère.",
      monitoring: "Surveillance",
      monitoringBody: "Selles, inconfort abdominal et ballonnements.",
      education: "Éducation",
      educationBody: "Enseigner la routine de toilette et les symptômes à signaler.",
    },
    nutritionDeficit: {
      title: "Déficit nutritionnel / apport insuffisant",
      description: "Documentation de soutien pour un mauvais apport.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour un mauvais apport.",
      goal: "Objectif",
      goalBody: "Les apports nutritionnels s’améliorent vers les cibles de l’équipe.",
      outcome: "Résultats attendus",
      outcomeBody: "Le pourcentage des repas pris et les freins à l’alimentation sont documentés.",
      intervention: "Interventions",
      interventionBody: "Aider aux repas ; offrir des aliments préférés si autorisés ; coordonner une consultation nutrition si indiqué.",
      monitoring: "Surveillance",
      monitoringBody: "Pourcentage d’apport, tendances de poids si disponibles, et préoccupations de déglutition.",
      education: "Éducation",
      educationBody: "Enseigner l’importance des apports et impliquer les aidants.",
    },
    dysphagia: {
      title: "Dysphagie",
      description: "Documentation de soutien pour la sécurité de déglutition — complète les précautions d’aspiration.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la sécurité de déglutition — complète les précautions d’aspiration.",
      goal: "Objectif",
      goalBody: "Les apports oraux sûrs sont soutenus selon les recommandations de déglutition.",
      outcome: "Résultats attendus",
      outcomeBody: "Toux/fausse route pendant l’apport et respect des textures sont documentés.",
      intervention: "Interventions",
      interventionBody: "Respecter la consistance ordonnée ; position assise ; escalader les signes d’aspiration. Coordonner Orthophonie.",
      monitoring: "Surveillance",
      monitoringBody: "Tolérance de déglutition, toux à l’alimentation et SpO2 pendant les repas si indiqué.",
      education: "Éducation",
      educationBody: "Enseigner les techniques d’alimentation sûres aux aidants.",
    },
    akiSupport: {
      title: "Soins de soutien IRA",
      description: "Surveillance de soutien pour l’IRA.",
      focus: "Focus clinique",
      focusBody: "Surveillance de soutien pour l’IRA.",
      goal: "Objectif",
      goalBody: "Les préoccupations liquidiennes et électrolytiques sont reconnues et escaladées tôt.",
      outcome: "Résultats attendus",
      outcomeBody: "Les tendances de diurèse et de volume sont documentées.",
      intervention: "Interventions",
      interventionBody: "Surveiller entrées/sorties et poids si ordonné ; pratiques de protection rénale ; escalader l’oligurie.",
      monitoring: "Surveillance",
      monitoringBody: "Diurèse, œdème et état mental lié aux préoccupations urémiques.",
      education: "Éducation",
      educationBody: "Enseigner la vigilance liquidienne selon le plan de l’équipe.",
    },
    urinaryRetention: {
      title: "Rétention urinaire",
      description: "Documentation de soutien pour les préoccupations de rétention urinaire.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les préoccupations de rétention urinaire.",
      goal: "Objectif",
      goalBody: "La vidange vésicale est rétablie ou escaladée de façon appropriée.",
      outcome: "Résultats attendus",
      outcomeBody: "Le schéma mictionnel, l’inconfort vésical et les préoccupations post-miction sont documentés.",
      intervention: "Interventions",
      interventionBody: "Aider à la toilette ; escalader l’incapacité à uriner ; escalader l’incapacité à uriner.",
      monitoring: "Surveillance",
      monitoringBody: "Volumes urinés, inconfort hypogastrique et signes de trop-plein.",
      education: "Éducation",
      educationBody: "Enseigner la miction programmée si approprié.",
    },
    indwellingCatheterCare: {
      title: "Soins de sonde urinaire à demeure",
      description: "Documentation de soutien pour les soins de sonde urinaire.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les soins de sonde urinaire.",
      goal: "Objectif",
      goalBody: "La sonde reste sécurisée avec des pratiques de prévention d’infection.",
      outcome: "Résultats attendus",
      outcomeBody: "Soins du méat, position du sac et caractère des urines sont documentés.",
      intervention: "Interventions",
      interventionBody: "Maintenir un système clos ; garder le sac sous la vessie ; escalader signes d’infection ou d’obstruction.",
      monitoring: "Surveillance",
      monitoringBody: "Diurèse/caractère, peau du méat et fièvre.",
      education: "Éducation",
      educationBody: "Enseigner les bases des soins de sonde aux aidants en cas de retour à domicile avec sonde.",
      safety: "Recommandations de sécurité",
      safetyBody: "Escalader rapidement les complications de sonde.",
    },
    diabetesSupport: {
      title: "Soutien à la prise en charge du diabète",
      description: "Documentation de soutien diabète.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien diabète.",
      goal: "Objectif",
      goalBody: "Les symptômes liés au glucose sont reconnus et escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les contrôles glycémiques ordonnés et tendances symptomatiques sont documentés.",
      intervention: "Interventions",
      interventionBody: "Soutenir la surveillance ordonnée ; escalader les symptômes d’hypo/hyperglycémie.",
      monitoring: "Surveillance",
      monitoringBody: "Résultats glycémiques si disponibles, apports alimentaires et symptômes d’hypo/hyper.",
      education: "Éducation",
      educationBody: "Renforcer l’éducation jours de maladie et reconnaissance de l’hypoglycémie.",
    },
    hyperglycemiaMonitoring: {
      title: "Surveillance de l’hyperglycémie",
      description: "Surveillance de soutien pour une glycémie élevée.",
      focus: "Focus clinique",
      focusBody: "Surveillance de soutien pour une glycémie élevée.",
      goal: "Objectif",
      goalBody: "Les symptômes d’hyperglycémie sont reconnus et escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Tendances glycémiques et symptômes de polyurie/polydipsie sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller les glycémies ordonnées ; escalader les symptômes sévères.",
      monitoring: "Surveillance",
      monitoringBody: "Valeurs glycémiques si disponibles, hydratation et état mental.",
      education: "Éducation",
      educationBody: "Enseigner les signes d’alerte d’hyperglycémie.",
    },
    hypoglycemiaRisk: {
      title: "Risque d’hypoglycémie",
      description: "Documentation de sécurité de soutien pour le risque d’hypoglycémie.",
      focus: "Focus clinique",
      focusBody: "Documentation de sécurité de soutien pour le risque d’hypoglycémie.",
      goal: "Objectif",
      goalBody: "L’hypoglycémie est reconnue tôt et traitée selon protocoles ordonnés / autorité séparée.",
      outcome: "Résultats attendus",
      outcomeBody: "Les épisodes d’hypoglycémie et la réponse sont documentés.",
      intervention: "Interventions",
      interventionBody: "Connaître le timing des repas ; escalader rapidement sueurs/confusion/tremblements.",
      monitoring: "Surveillance",
      monitoringBody: "Symptômes d’hypoglycémie et résultats glycémiques si disponibles.",
      education: "Éducation",
      educationBody: "Enseigner la reconnaissance et quand appeler à l’aide.",
      safety: "Recommandations de sécurité",
      safetyBody: "Escalader rapidement les symptômes d’hypoglycémie selon la pratique clinique.",
    },
    activityIntolerance: {
      title: "Intolérance à l’activité",
      description: "Documentation de soutien pour une tolérance limitée à l’activité.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour une tolérance limitée à l’activité.",
      goal: "Objectif",
      goalBody: "L’activité est rythmée selon la tolérance avec moins de dyspnée/fatigue sévère.",
      outcome: "Résultats attendus",
      outcomeBody: "La tolérance aux AVQ et tentatives de marche est documentée.",
      intervention: "Interventions",
      interventionBody: "Rythmer l’activité ; permettre le repos ; escalader douleur thoracique ou dyspnée sévère.",
      monitoring: "Surveillance",
      monitoringBody: "Réponse FC/respiratoire à l’activité et temps de récupération.",
      education: "Éducation",
      educationBody: "Enseigner la conservation d’énergie.",
    },
    deconditioning: {
      title: "Déconditionnement",
      description: "Documentation de soutien pour la récupération de mobilité après inactivité.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la récupération de mobilité après inactivité.",
      goal: "Objectif",
      goalBody: "La mobilisation progressive se fait dans des limites sûres.",
      outcome: "Résultats attendus",
      outcomeBody: "Fréquence hors lit et niveau d’assistance sont documentés.",
      intervention: "Interventions",
      interventionBody: "Encourager la mobilité progressive ; coordonner PT/OT si indiqué ; prévenir le lit prolongé lorsque sûr.",
      monitoring: "Surveillance",
      monitoringBody: "Niveau d’assistance, distance marchée et symptômes orthostatiques.",
      education: "Éducation",
      educationBody: "Enseigner l’importance de la mobilité précoce.",
    },
    transferAssistance: {
      title: "Aide aux transferts",
      description: "Documentation de soutien pour une aide sécuritaire aux transferts.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour une aide sécuritaire aux transferts.",
      goal: "Objectif",
      goalBody: "Les transferts se font sans chute ni blessure.",
      outcome: "Résultats attendus",
      outcomeBody: "La méthode d’assistance et la participation du patient sont documentées.",
      intervention: "Interventions",
      interventionBody: "Utiliser l’assistance/équipement approprié selon l’évaluation ; utiliser une assistance appropriée.",
      monitoring: "Surveillance",
      monitoringBody: "Réussite du transfert, vertiges et événements de sécurité.",
      education: "Éducation",
      educationBody: "Enseigner aux aidants les bases d’un transfert sûr si approprié.",
    },
    adlDeficit: {
      title: "Déficit des AVQ",
      description: "Documentation de soutien pour les déficits d’autonomie.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les déficits d’autonomie.",
      goal: "Objectif",
      goalBody: "Le patient réalise les AVQ prioritaires avec une assistance appropriée.",
      outcome: "Résultats attendus",
      outcomeBody: "Le niveau d’assistance pour toilette, habillage et élimination est documenté.",
      intervention: "Interventions",
      interventionBody: "Fournir une assistance adaptée ; favoriser l’indépendance ; coordonner l’OT si indiqué.",
      monitoring: "Surveillance",
      monitoringBody: "Niveau d’assistance et fatigue pendant les AVQ.",
      education: "Éducation",
      educationBody: "Enseigner des stratégies d’autonomie économes en énergie.",
    },
    existingPressureInjury: {
      title: "Lésion de pression existante",
      description: "Documentation de plan de soins de soutien pour une lésion de pression existante.",
      focus: "Focus clinique",
      focusBody: "Documentation de plan de soins de soutien pour une lésion de pression existante.",
      goal: "Objectif",
      goalBody: "L’état de la plaie ne se détériore pas du fait d’une pression évitable.",
      outcome: "Résultats attendus",
      outcomeBody: "Décharge et observations de pansement sont documentées ; les constats détaillés restent dans la documentation des plaies.",
      intervention: "Interventions",
      interventionBody: "Décharger la zone ; soutenir les soins de pansement ordonnés ; escalader la détérioration.",
      monitoring: "Surveillance",
      monitoringBody: "Peau environnante, douleur et intégrité du pansement.",
      education: "Éducation",
      educationBody: "Enseigner l’importance du soulagement de pression.",
    },
    surgicalWoundCare: {
      title: "Soins de plaie chirurgicale",
      description: "Documentation de soutien pour les soins d’incision/plaie.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les soins d’incision/plaie.",
      goal: "Objectif",
      goalBody: "L’incision reste propre et cicatrise sans complications évitables.",
      outcome: "Résultats attendus",
      outcomeBody: "État du pansement et signes précoces d’infection sont documentés.",
      intervention: "Interventions",
      interventionBody: "Soutenir les soins de plaie ordonnés ; garder l’incision propre/sèche selon consignes ; escalader fièvre/rougeur/changements d’écoulement.",
      monitoring: "Surveillance",
      monitoringBody: "Intégrité du pansement, écoulement et douleur au site.",
      education: "Éducation",
      educationBody: "Enseigner les soins d’incision et signes à signaler.",
    },
    chronicPain: {
      title: "Douleur chronique",
      description: "Documentation de soutien pour la douleur chronique pendant la rencontre.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la douleur chronique pendant la rencontre.",
      goal: "Objectif",
      goalBody: "La douleur est réduite à un niveau acceptable pour le patient lorsque possible.",
      outcome: "Résultats attendus",
      outcomeBody: "Scores de douleur et impact fonctionnel sont documentés.",
      intervention: "Interventions",
      interventionBody: "Utiliser des mesures de confort non pharmacologiques ; soutenir les antalgiques ordonnés.",
      monitoring: "Surveillance",
      monitoringBody: "Intensité de la douleur, fonction et préoccupations d’effets indésirables.",
      education: "Éducation",
      educationBody: "Enseigner le rythme d’activité et stratégies de confort non médicamenteuses.",
    },
    postoperativePain: {
      title: "Douleur postopératoire",
      description: "Documentation de soutien pour la douleur postopératoire.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la douleur postopératoire.",
      goal: "Objectif",
      goalBody: "La douleur permet repos, respiration profonde et mobilisation autant que possible.",
      outcome: "Résultats attendus",
      outcomeBody: "Scores de douleur au repos et à l’activité sont documentés.",
      intervention: "Interventions",
      interventionBody: "Encourager le soutien abdominal à la toux ; soutenir l’analgésie ordonnée ; escalader une douleur non contrôlée.",
      monitoring: "Surveillance",
      monitoringBody: "Douleur au repos/activité et réponse à la thérapie ordonnée.",
      education: "Éducation",
      educationBody: "Enseigner le soutien à la toux et quand demander de l’aide.",
    },
    infectionMonitoring: {
      title: "Surveillance d’infection",
      description: "Surveillance de soutien pour une infection suspectée ou connue.",
      focus: "Focus clinique",
      focusBody: "Surveillance de soutien pour une infection suspectée ou connue.",
      goal: "Objectif",
      goalBody: "Les signes d’alerte d’infection sont reconnus et escaladés.",
      outcome: "Résultats attendus",
      outcomeBody: "Tendances de température et signes locaux/systémiques sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller fièvre et symptômes de site ; escalader les signes d’alerte de sepsis.",
      monitoring: "Surveillance",
      monitoringBody: "Température, fréquence cardiaque, rougeur/écoulement local et état mental.",
      education: "Éducation",
      educationBody: "Enseigner l’hygiène et les symptômes de fièvre à signaler.",
    },
    sepsisSupportive: {
      title: "Plan de soins de soutien sepsis",
      description: "Documentation de soutien lorsque le sepsis est une préoccupation clinique.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien lorsque le sepsis est une préoccupation clinique.",
      goal: "Objectif",
      goalBody: "La détérioration précoce est reconnue et escaladée immédiatement.",
      outcome: "Résultats attendus",
      outcomeBody: "L’instabilité des constantes et les changements d’état mental sont documentés et escaladés.",
      intervention: "Interventions",
      interventionBody: "Renforcer la surveillance ; escalader hypotension/altération mentale/préoccupations de lactate à l’équipe.",
      monitoring: "Surveillance",
      monitoringBody: "Constantes, état mental, tendances de diurèse et fièvre/hypothermie.",
      education: "Éducation",
      educationBody: "Informer la famille de l’intensité de surveillance sans promettre de résultats.",
    },
    postoperativeRecovery: {
      title: "Récupération postopératoire",
      description: "Documentation de soutien pour la récupération postopératoire.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la récupération postopératoire.",
      goal: "Objectif",
      goalBody: "Les jalons de récupération (voies aériennes, douleur, mobilisation, apports) progressent en sécurité.",
      outcome: "Résultats attendus",
      outcomeBody: "Constantes, douleur, plaie et statut de mobilisation sont documentés.",
      intervention: "Interventions",
      interventionBody: "Surveiller le statut postop ; encourager l’hygiène pulmonaire et la mobilisation si approprié ; escalader l’instabilité.",
      monitoring: "Surveillance",
      monitoringBody: "Constantes, douleur, incision et préoccupations urinaires/sorties.",
      education: "Éducation",
      educationBody: "Enseigner les étapes attendues de récupération et signes d’alerte.",
    },
    dvtPreventionSupport: {
      title: "Prévention MTEV / mobilité de soutien",
      description: "Documentation de soutien pour la prévention MTEV.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la prévention MTEV.",
      goal: "Objectif",
      goalBody: "Mobilité et soutiens mécaniques de prévention sont maintenus selon ordonnance.",
      outcome: "Résultats attendus",
      outcomeBody: "Fréquence de marche et observance des dispositifs sont documentées.",
      intervention: "Interventions",
      interventionBody: "Encourager la mobilisation ; soutenir les dispositifs mécaniques ordonnés ; escalader douleur/gonflement du mollet.",
      monitoring: "Surveillance",
      monitoringBody: "Symptômes de mollet, usage des dispositifs et fréquence de mobilité.",
      education: "Éducation",
      educationBody: "Enseigner l’importance de la marche et des exercices de mollet si approprié.",
    },
    anxiety: {
      title: "Anxiété",
      description: "Documentation psychosociale de soutien pour l’anxiété.",
      focus: "Focus clinique",
      focusBody: "Documentation psychosociale de soutien pour l’anxiété.",
      goal: "Objectif",
      goalBody: "Le patient rapporte une anxiété réduite et peut participer aux soins.",
      outcome: "Résultats attendus",
      outcomeBody: "Déclencheurs d’anxiété et stratégies apaisantes utilisées sont documentés.",
      intervention: "Interventions",
      interventionBody: "Offrir une présence calme ; expliquer les procédures ; escalader panique sévère ou préoccupations de sécurité.",
      monitoring: "Surveillance",
      monitoringBody: "Niveau d’anxiété, sommeil et capacité à s’engager dans les soins.",
      education: "Éducation",
      educationBody: "Enseigner des stratégies simples d’ancrage/respiration.",
    },
    knowledgeDeficit: {
      title: "Déficit de connaissances",
      description: "Documentation d’enseignement de soutien pour les lacunes liées aux soins.",
      focus: "Focus clinique",
      focusBody: "Documentation d’enseignement de soutien pour les lacunes liées aux soins.",
      goal: "Objectif",
      goalBody: "Le patient/aidant verbalise la compréhension des points d’enseignement prioritaires.",
      outcome: "Résultats attendus",
      outcomeBody: "Les résultats de reformulation (teach-back) pour les sujets clés sont documentés.",
      intervention: "Interventions",
      interventionBody: "Fournir une éducation ciblée ; utiliser la reformulation ; escalader les besoins de langue/barrières.",
      monitoring: "Surveillance",
      monitoringBody: "Compréhension via reformulation et questions restantes.",
      education: "Éducation",
      educationBody: "Fournir des documents écrits lorsque disponibles et appropriés.",
    },
    familyCaregiverSupport: {
      title: "Soutien famille / aidant",
      description: "Documentation de soutien pour les besoins d’engagement des aidants.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour les besoins d’engagement des aidants.",
      goal: "Objectif",
      goalBody: "Les aidants comprennent les tâches de soins prioritaires et se sentent soutenus.",
      outcome: "Résultats attendus",
      outcomeBody: "Enseignement aux aidants et préoccupations sont documentés.",
      intervention: "Interventions",
      interventionBody: "Inclure les aidants dans l’enseignement ; aborder les signes d’épuisement ; coordonner les soutiens sociaux si disponibles.",
      monitoring: "Surveillance",
      monitoringBody: "Questions des aidants, stress et readiness à aider.",
      education: "Éducation",
      educationBody: "Fournir des attentes de rôle claires pour les aidants.",
    },
    patientEducation: {
      title: "Éducation du patient",
      description: "Documentation d’enseignement orientée sortie.",
      focus: "Focus clinique",
      focusBody: "Documentation d’enseignement orientée sortie.",
      goal: "Objectif",
      goalBody: "Le patient verbalise la compréhension des sujets d’éducation prioritaires.",
      outcome: "Résultats attendus",
      outcomeBody: "La reformulation pour diagnostic, médicaments et signes d’alerte est documentée lorsque enseignée.",
      intervention: "Interventions",
      interventionBody: "Fournir un enseignement ciblé ; utiliser la reformulation ; documenter les freins.",
      monitoring: "Surveillance",
      monitoringBody: "Compréhension et besoins d’apprentissage restants.",
      education: "Éducation",
      educationBody: "Offrir des consignes écrites lorsque disponibles.",
    },
    medicationEducation: {
      title: "Éducation médicamenteuse",
      description: "Enseignement médicamenteux de soutien.",
      focus: "Focus clinique",
      focusBody: "Enseignement médicamenteux de soutien.",
      goal: "Objectif",
      goalBody: "Le patient/aidant peut énoncer le but et les points de vigilance des médicaments enseignés.",
      outcome: "Résultats attendus",
      outcomeBody: "Les résultats de reformulation médicamenteuse sont documentés.",
      intervention: "Interventions",
      interventionBody: "Revoir les médicaments de sortie ordonnés lorsqu’ils sont connus ; escalader les écarts au médecin/pharmacie.",
      monitoring: "Surveillance",
      monitoringBody: "Compréhension du timing, du but et des effets indésirables enseignés.",
      education: "Éducation",
      educationBody: "Fournir l’éducation de liste médicamenteuse selon le conseil pharmacie/médecin.",
    },
    homeSafetyPreparation: {
      title: "Préparation sécurité à domicile",
      description: "Documentation de soutien pour la readiness de sécurité à domicile.",
      focus: "Focus clinique",
      focusBody: "Documentation de soutien pour la readiness de sécurité à domicile.",
      goal: "Objectif",
      goalBody: "Les freins clés de sécurité à domicile sont identifiés et abordés dans l’enseignement.",
      outcome: "Résultats attendus",
      outcomeBody: "Risques à domicile discutés et plans d’atténuation sont documentés.",
      intervention: "Interventions",
      interventionBody: "Revoir éclairage, passages, aides techniques et plans d’appel à l’aide.",
      monitoring: "Surveillance",
      monitoringBody: "Freins identifiés et disponibilité des aidants.",
      education: "Éducation",
      educationBody: "Enseigner les bases de prévention des chutes à domicile.",
    },

    deferred: {
      copd: {
        title: "Exacerbation BPCO (complet) — reporté",
        description: "Parcours BPCO complet reporté en attendant la qualité du contenu et les limites d’ordonnances RT.",
      },
      sepsis: {
        title: "Parcours sepsis (complet) — reporté",
        description: "Parcours sepsis complet reporté — ne doit pas auto-commander des bundles depuis le plan.",
      },
      diabetes: {
        title: "Diabète endocrinien (complet) — reporté",
        description: "Processus diabète complet reporté ; les changements médicamenteux restent sous prescription / MAR.",
      },
      stroke: {
        title: "Parcours AVC (complet) — reporté",
        description: "Parcours AVC complet reporté au-delà des starters aspiration/mobilité.",
      },
      behavioral: {
        title: "Santé comportementale (complet) — reporté",
        description: "Protocoles comportementaux complets reportés ; l’autorisation de contention reste hors périmètre.",
      },
    },
} as const;
