/**
 * Phase 4 ED — gastroenterology order sets.
 */
import { care, imaging, lab, providerRoles, type EnterpriseOrderSetDefinition } from "../types.js";

export const GASTRO_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_abdominal_pain_v1",
    displayNameEn: "Abdominal Pain",
    displayNameFr: "Douleur abdominale",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "gastro_abdominal_pain",
    descriptionEn: "Acute abdominal pain evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour douleur abdominale aiguë.",
    indicationKeywords: ["abdominal pain", "abd pain", "belly pain"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("npoStatus", "NPO status", "Statut NPO", "npo_status"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    optionalItems: [
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
      lab("lipase", "Lipase", "Lipase", "LIPASE"),
      lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA"),
      imaging("ctAbdomenPelvis", "CT abdomen/pelvis", "TDM abdomen/pelvis", "CT_ABDOMEN_PELVIS", ["CT_ABD"]),
      imaging("usAbdomen", "Ultrasound abdomen", "Échographie abdominale", "US_ABD", ["US_ABDOMEN"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_flank_pain_v1",
    displayNameEn: "Flank Pain",
    displayNameFr: "Douleur lombaire latérale",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "gastro_flank_pain",
    descriptionEn: "Flank pain evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour douleur lombaire latérale.",
    indicationKeywords: ["flank pain", "side pain", "renal colic"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA"),
    ],
    optionalItems: [
      imaging("ctAbdomenPelvis", "CT abdomen/pelvis", "TDM abdomen/pelvis", "CT_ABDOMEN_PELVIS", ["CT_ABD"]),
      imaging("usRenal", "Renal ultrasound", "Échographie rénale", "US_RENAL"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_renal_colic_v1",
    displayNameEn: "Renal Colic",
    displayNameFr: "Colique néphrétique",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "gastro_renal_colic",
    descriptionEn: "Renal colic evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour colique néphrétique.",
    indicationKeywords: ["renal colic", "kidney stone", "nephrolithiasis"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA"),
    ],
    optionalItems: [
      imaging("ctAbdomenPelvis", "CT abdomen/pelvis", "TDM abdomen/pelvis", "CT_ABDOMEN_PELVIS", ["CT_ABD"]),
      imaging("usRenal", "Renal ultrasound", "Échographie rénale", "US_RENAL"),
      care("peripheralIv", "Peripheral IV placement", "Pose de VVP", "peripheral_iv_placement", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_upper_gi_bleeding_v1",
    displayNameEn: "Upper GI Bleeding",
    displayNameFr: "Hémorragie digestive haute",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "gastro_upper_gi_bleed",
    descriptionEn: "Upper GI bleeding stabilization bundle.",
    descriptionFr: "Ensemble de stabilisation pour hémorragie digestive haute.",
    indicationKeywords: ["upper gi bleed", "hematemesis", "melena"],
    requiredItems: [
      care(
        "continuousCardiacMonitoring",
        "Continuous cardiac monitoring",
        "Surveillance cardiaque continue",
        "continuous_cardiac_monitoring"
      ),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("npoStatus", "NPO status", "Statut NPO", "npo_status"),
      care("peripheralIv", "Peripheral IV placement", "Pose de VVP", "peripheral_iv_placement"),
    ],
    optionalItems: [
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
      lab("inr", "INR", "INR", "INR", ["PT_INR"]),
      care("ngTube", "NG tube placement", "Pose de sonde nasogastrique", "ng_tube_placement", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_lower_gi_bleeding_v1",
    displayNameEn: "Lower GI Bleeding",
    displayNameFr: "Hémorragie digestive basse",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "gastro_lower_gi_bleed",
    descriptionEn: "Lower GI bleeding evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour hémorragie digestive basse.",
    indicationKeywords: ["lower gi bleed", "hematochezia", "rectal bleeding"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("peripheralIv", "Peripheral IV placement", "Pose de VVP", "peripheral_iv_placement"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    optionalItems: [
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
      lab("inr", "INR", "INR", "INR", ["PT_INR"]),
      imaging("ctAbdomenPelvis", "CT abdomen/pelvis", "TDM abdomen/pelvis", "CT_ABDOMEN_PELVIS", ["CT_ABD"]),
      care("rectalExamAssist", "Rectal exam assist", "Aide à l'examen rectal", "rectal_exam_assist", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
];
