/**
 * Phase 4 ED — infection and general medicine order sets.
 */
import { care, imaging, lab, providerRoles, type EnterpriseOrderSetDefinition } from "../types.js";

export const INFECTION_GENERAL_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_cellulitis_v1",
    displayNameEn: "Cellulitis",
    displayNameFr: "Cellulite",
    category: "INFECTION",
    department: "ED",
    clinicalDomain: "infection_cellulitis",
    descriptionEn: "Cellulitis evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour cellulite.",
    indicationKeywords: ["cellulitis", "skin infection", "erythema"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    optionalItems: [
      lab("crp", "CRP", "CRP", "CRP"),
      care("woundCare", "Wound care", "Soins de plaie", "wound_care", { deferIfMissing: true }),
      care("peripheralIv", "Peripheral IV placement", "Pose de VVP", "peripheral_iv_placement", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_fever_adult_v1",
    displayNameEn: "Fever — Adult",
    displayNameFr: "Fièvre — adulte",
    category: "GENERAL",
    department: "ED",
    clinicalDomain: "general_fever_adult",
    descriptionEn: "Adult fever evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour fièvre chez l'adulte.",
    indicationKeywords: ["fever", "pyrexia", "febrile"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    optionalItems: [
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
      lab("bloodCulture", "Blood culture", "Hémoculture", "BLOOD_CULTURE", ["ER_BC"]),
      lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA"),
      imaging("chestXray", "Chest X-ray", "Radiographie thoracique", "XR_CHEST"),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_fever_pediatric_v1",
    displayNameEn: "Fever — Pediatric",
    displayNameFr: "Fièvre — pédiatrique",
    category: "GENERAL",
    department: "ED",
    clinicalDomain: "general_fever_pediatric",
    descriptionEn: "Pediatric fever evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour fièvre pédiatrique.",
    indicationKeywords: ["pediatric fever", "child fever", "infant fever"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    optionalItems: [
      lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA"),
      lab("bloodCulture", "Blood culture", "Hémoculture", "BLOOD_CULTURE", ["ER_BC"]),
      imaging("chestXray", "Chest X-ray", "Radiographie thoracique", "XR_CHEST"),
      care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "PEDIATRIC",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_sore_throat_v1",
    displayNameEn: "Sore Throat",
    displayNameFr: "Mal de gorge",
    category: "ENT",
    department: "ED",
    clinicalDomain: "ent_sore_throat",
    descriptionEn: "Sore throat evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour mal de gorge.",
    indicationKeywords: ["sore throat", "pharyngitis", "strep"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      lab("rapidStrep", "Rapid strep", "Streptocoque rapide", "RAPID_STREP"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      care("pocStrepScreen", "POC strep screen", "Dépistage strepto POC", "poc_strep_screen", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
];
