/**
 * Phase 4 ED — neuro order sets.
 */
import { care, imaging, lab, providerRoles, type EnterpriseOrderSetDefinition } from "../types.js";

export const NEURO_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_tia_v1",
    displayNameEn: "TIA",
    displayNameFr: "AIT",
    category: "NEURO",
    department: "ED",
    clinicalDomain: "neuro_tia",
    descriptionEn: "Transient ischemic attack evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour accident ischémique transitoire.",
    indicationKeywords: ["tia", "transient", "neuro deficit resolved"],
    requiredItems: [
      care("ekg12Lead", "EKG 12-Lead", "ECG 12 dérivations", "ekg_ecg"),
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      imaging("ctHead", "CT head", "TDM tête", "CT_HEAD_WO_CONTRAST", ["CT_HEAD"]),
      imaging("ctaHeadNeck", "CTA head/neck", "Angio-TDM tête/cou", "CTA_HEAD_NECK"),
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      care("neurologyConsult", "Neurology consult", "Consultation neurologie", "neurology_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_headache_v1",
    displayNameEn: "Headache",
    displayNameFr: "Céphalée",
    category: "NEURO",
    department: "ED",
    clinicalDomain: "neuro_headache",
    descriptionEn: "Acute headache evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour céphalée aiguë.",
    indicationKeywords: ["headache", "migraine", "thunderclap"],
    requiredItems: [
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      imaging("ctHead", "CT head", "TDM tête", "CT_HEAD_WO_CONTRAST", ["CT_HEAD"]),
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      care("neurologyConsult", "Neurology consult", "Consultation neurologie", "neurology_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_altered_mental_status_v1",
    displayNameEn: "Altered Mental Status",
    displayNameFr: "Altération de l'état mental",
    category: "NEURO",
    department: "ED",
    clinicalDomain: "neuro_ams",
    descriptionEn: "Altered mental status evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour altération de l'état mental.",
    indicationKeywords: ["ams", "confusion", "lethargy", "unresponsive"],
    requiredItems: [
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check"),
      care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
    ],
    optionalItems: [
      imaging("ctHead", "CT head", "TDM tête", "CT_HEAD_WO_CONTRAST", ["CT_HEAD"]),
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      care("constantObservation", "Constant observation", "Surveillance constante", "constant_observation", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_seizure_v1",
    displayNameEn: "Seizure",
    displayNameFr: "Crise convulsive",
    category: "NEURO",
    department: "ED",
    clinicalDomain: "neuro_seizure",
    descriptionEn: "Post-seizure monitoring and evaluation bundle.",
    descriptionFr: "Ensemble de surveillance et évaluation post-crise convulsive.",
    indicationKeywords: ["seizure", "convulsion", "epilepsy"],
    requiredItems: [
      care("seizurePrecautions", "Seizure precautions", "Précautions convulsives", "seizure_precautions"),
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry"),
    ],
    optionalItems: [
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      imaging("ctHead", "CT head", "TDM tête", "CT_HEAD_WO_CONTRAST", ["CT_HEAD"]),
      care("neurologyConsult", "Neurology consult", "Consultation neurologie", "neurology_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
];
