/**
 * Phase 6 ED — RN standing order protocols (conservative nursing-safe items only).
 */
import {
  care,
  lab,
  rnStandingRoles,
  type EnterpriseOrderSetDefinition,
} from "../types.js";

const vitalsAndPulse = [
  care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
  care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry"),
];

export const RN_STANDING_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_rn_chest_pain_v1",
    displayNameEn: "Chest Pain (RN Standing)",
    displayNameFr: "Douleur thoracique (ordre permanent infirmier)",
    category: "CARDIAC",
    department: "ED",
    clinicalDomain: "rn_cardiac_chest_pain",
    descriptionEn: "RN standing orders for chest pain monitoring and initial workup.",
    descriptionFr: "Ordres permanents infirmiers pour surveillance et bilan initial de douleur thoracique.",
    indicationKeywords: ["chest pain", "rn standing", "acs screen"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [...vitalsAndPulse],
    optionalItems: [
      care("ekg12Lead", "EKG 12-Lead", "ECG 12 dérivations", "ekg_ecg", { deferIfMissing: true }),
      lab("troponin", "Troponin", "Troponine", "TROPONIN", ["TROP", "ER_TROP"]),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_respiratory_distress_v1",
    displayNameEn: "Respiratory Distress (RN Standing)",
    displayNameFr: "Détresse respiratoire (ordre permanent infirmier)",
    category: "RESPIRATORY",
    department: "ED",
    clinicalDomain: "rn_respiratory",
    descriptionEn: "RN standing orders for respiratory distress monitoring.",
    descriptionFr: "Ordres permanents infirmiers pour surveillance de détresse respiratoire.",
    indicationKeywords: ["respiratory distress", "dyspnea", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [...vitalsAndPulse],
    optionalItems: [
      care("respiratoryTherapy", "Respiratory therapy request", "Demande de kinésithérapie respiratoire", "respiratory_treatment", {
        deferIfMissing: true,
      }),
      care("nebulizerTreatment", "Nebulizer treatment", "Nébulisation", "nebulizer_treatment", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_general_injury_v1",
    displayNameEn: "General Injury (RN Standing)",
    displayNameFr: "Traumatisme général (ordre permanent infirmier)",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "rn_general_injury",
    descriptionEn: "RN standing orders for general injury support.",
    descriptionFr: "Ordres permanents infirmiers pour prise en charge de traumatisme général.",
    indicationKeywords: ["injury", "trauma minor", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      care("icePack", "Ice pack", "Compresse froide", "ice_pack", { deferIfMissing: true }),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
      care("fallPrecautions", "Fall precautions", "Précautions contre les chutes", "fall_precautions", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_upper_extremity_injury_v1",
    displayNameEn: "Upper Extremity Injury (RN Standing)",
    displayNameFr: "Blessure membre supérieur (ordre permanent infirmier)",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "rn_upper_extremity",
    descriptionEn: "RN standing orders for upper extremity injury.",
    descriptionFr: "Ordres permanents infirmiers pour blessure du membre supérieur.",
    indicationKeywords: ["arm injury", "upper extremity", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      care("icePack", "Ice pack", "Compresse froide", "ice_pack", { deferIfMissing: true }),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_lower_extremity_injury_v1",
    displayNameEn: "Lower Extremity Injury (RN Standing)",
    displayNameFr: "Blessure membre inférieur (ordre permanent infirmier)",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "rn_lower_extremity",
    descriptionEn: "RN standing orders for lower extremity injury.",
    descriptionFr: "Ordres permanents infirmiers pour blessure du membre inférieur.",
    indicationKeywords: ["leg injury", "lower extremity", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      care("icePack", "Ice pack", "Compresse froide", "ice_pack", { deferIfMissing: true }),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_back_flank_pain_v1",
    displayNameEn: "Back / Flank Pain (RN Standing)",
    displayNameFr: "Douleur dorsale / lombaire latérale (ordre permanent infirmier)",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "rn_back_flank_pain",
    descriptionEn: "RN standing orders for back or flank pain.",
    descriptionFr: "Ordres permanents infirmiers pour douleur dorsale ou lombaire latérale.",
    indicationKeywords: ["back pain", "flank pain", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [lab("urinalysis", "Urinalysis", "Analyse d'urine", "UA")],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_fever_pediatric_v1",
    displayNameEn: "Fever — Pediatric (RN Standing)",
    displayNameFr: "Fièvre pédiatrique (ordre permanent infirmier)",
    category: "GENERAL",
    department: "ED",
    clinicalDomain: "rn_fever_pediatric",
    descriptionEn: "RN standing orders for pediatric fever.",
    descriptionFr: "Ordres permanents infirmiers pour fièvre pédiatrique.",
    indicationKeywords: ["pediatric fever", "child fever", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [...vitalsAndPulse],
    optionalItems: [lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"])],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "PEDIATRIC",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_syncope_v1",
    displayNameEn: "Syncope / Near Syncope (RN Standing)",
    displayNameFr: "Syncope / présyncope (ordre permanent infirmier)",
    category: "CARDIAC",
    department: "ED",
    clinicalDomain: "rn_syncope",
    descriptionEn: "RN standing orders for syncope evaluation.",
    descriptionFr: "Ordres permanents infirmiers pour évaluation de syncope.",
    indicationKeywords: ["syncope", "presyncope", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [
      ...vitalsAndPulse,
      care("orthostaticVitals", "Orthostatic vital signs", "Signes vitaux orthostatiques", "orthostatic_vital_signs"),
    ],
    optionalItems: [
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      care("glucoseCheck", "Glucose check", "Contrôle glycémique", "glucose_check", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_eye_complaint_v1",
    displayNameEn: "Eye Complaint (RN Standing)",
    displayNameFr: "Plainte oculaire (ordre permanent infirmier)",
    category: "ENT",
    department: "ED",
    clinicalDomain: "rn_eye",
    descriptionEn: "RN standing orders for eye complaint.",
    descriptionFr: "Ordres permanents infirmiers pour plainte oculaire.",
    indicationKeywords: ["eye pain", "red eye", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [
      care("visualAcuity", "Visual acuity", "Acuité visuelle", "visual_acuity"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_neuro_complaint_v1",
    displayNameEn: "Neuro Complaint (RN Standing)",
    displayNameFr: "Plainte neurologique (ordre permanent infirmier)",
    category: "NEURO",
    department: "ED",
    clinicalDomain: "rn_neuro",
    descriptionEn: "RN standing orders for neurologic complaint monitoring.",
    descriptionFr: "Ordres permanents infirmiers pour surveillance de plainte neurologique.",
    indicationKeywords: ["neuro complaint", "weakness", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"])],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_nausea_vomiting_diarrhea_v1",
    displayNameEn: "Nausea / Vomiting / Diarrhea (RN Standing)",
    displayNameFr: "Nausées / vomissements / diarrhée (ordre permanent infirmier)",
    category: "GASTRO",
    department: "ED",
    clinicalDomain: "rn_gi_symptoms",
    descriptionEn: "RN standing orders for GI symptom support.",
    descriptionFr: "Ordres permanents infirmiers pour symptômes gastro-intestinaux.",
    indicationKeywords: ["nausea", "vomiting", "diarrhea", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      care("npoStatus", "NPO status", "Statut NPO", "npo_status", { deferIfMissing: true }),
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
  {
    code: "ed_rn_allergic_reaction_v1",
    displayNameEn: "Allergic Reaction (RN Standing)",
    displayNameFr: "Réaction allergique (ordre permanent infirmier)",
    category: "GENERAL",
    department: "ED",
    clinicalDomain: "rn_allergic_reaction",
    descriptionEn: "RN standing orders for allergic reaction monitoring.",
    descriptionFr: "Ordres permanents infirmiers pour surveillance de réaction allergique.",
    indicationKeywords: ["allergic reaction", "urticaria", "rn standing"],
    orderSetAuthority: "RN_STANDING_ORDER",
    requiredItems: [...vitalsAndPulse],
    optionalItems: [
      care("fallPrecautions", "Fall precautions", "Précautions contre les chutes", "fall_precautions", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: rnStandingRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_6_RN_STANDING",
  },
] as const;
