/**
 * Phase 4 ED — trauma and musculoskeletal order sets.
 */
import { care, imaging, lab, providerRoles, type EnterpriseOrderSetDefinition } from "../types.js";

const traumaMonitoring = [
  care(
    "continuousCardiacMonitoring",
    "Continuous cardiac monitoring",
    "Surveillance cardiaque continue",
    "continuous_cardiac_monitoring"
  ),
  care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
  care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry"),
];

export const TRAUMA_MSK_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_chest_trauma_v1",
    displayNameEn: "Chest Trauma",
    displayNameFr: "Traumatisme thoracique",
    category: "TRAUMA",
    department: "ED",
    clinicalDomain: "trauma_chest",
    descriptionEn: "Chest trauma evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour traumatisme thoracique.",
    indicationKeywords: ["chest trauma", "rib fracture", "blunt chest"],
    requiredItems: [
      ...traumaMonitoring,
      imaging("chestXray", "Chest X-ray", "Radiographie thoracique", "XR_CHEST"),
    ],
    optionalItems: [
      imaging("ctChest", "CT chest", "TDM thorax", "CT_CHEST"),
      imaging("fastExam", "FAST ultrasound", "Échographie FAST", "US_FAST"),
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_abdominal_trauma_v1",
    displayNameEn: "Abdominal Trauma",
    displayNameFr: "Traumatisme abdominal",
    category: "TRAUMA",
    department: "ED",
    clinicalDomain: "trauma_abdominal",
    descriptionEn: "Abdominal trauma evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour traumatisme abdominal.",
    indicationKeywords: ["abdominal trauma", "blunt abdomen", "penetrating abdomen"],
    requiredItems: [
      ...traumaMonitoring,
      care("npoStatus", "NPO status", "Statut NPO", "npo_status"),
      imaging("fastExam", "FAST ultrasound", "Échographie FAST", "US_FAST"),
    ],
    optionalItems: [
      imaging("ctAbdomenPelvis", "CT abdomen/pelvis", "TDM abdomen/pelvis", "CT_ABDOMEN_PELVIS", ["CT_ABD"]),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_facial_trauma_v1",
    displayNameEn: "Facial Trauma",
    displayNameFr: "Traumatisme facial",
    category: "TRAUMA",
    department: "ED",
    clinicalDomain: "trauma_facial",
    descriptionEn: "Facial trauma evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour traumatisme facial.",
    indicationKeywords: ["facial trauma", "facial fracture", "jaw injury"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("cervicalCollar", "Cervical collar", "Collier cervical", "cervical_collar", { deferIfMissing: true }),
    ],
    optionalItems: [
      imaging("ctHead", "CT head", "TDM tête", "CT_HEAD_WO_CONTRAST", ["CT_HEAD"]),
      imaging("ctCervicalSpine", "CT cervical spine", "TDM rachis cervical", "CT_CERVICAL_SPINE"),
      care("woundSetup", "Wound setup", "Préparation plaie", "wound_setup", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_shoulder_injury_v1",
    displayNameEn: "Shoulder Injury",
    displayNameFr: "Blessure à l'épaule",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_shoulder",
    descriptionEn: "Shoulder injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure à l'épaule.",
    indicationKeywords: ["shoulder injury", "shoulder pain", "dislocation"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrShoulder", "Shoulder X-ray", "Radiographie épaule", "XR_SHOULDER"),
      care("sling", "Sling", "Écharpe", "sling", { deferIfMissing: true }),
      care("orthopedicsConsult", "Orthopedics consult", "Consultation orthopédie", "orthopedics_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_upper_extremity_injury_v1",
    displayNameEn: "Upper Extremity Injury",
    displayNameFr: "Blessure membre supérieur",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_upper_extremity",
    descriptionEn: "Upper extremity injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure du membre supérieur.",
    indicationKeywords: ["arm injury", "elbow injury", "forearm injury"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrHumerus", "Humerus X-ray", "Radiographie humérus", "XR_HUMERUS"),
      imaging("xrElbow", "Elbow X-ray", "Radiographie coude", "XR_ELBOW"),
      imaging("xrForearm", "Forearm X-ray", "Radiographie avant-bras", "XR_FOREARM"),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_lower_extremity_injury_v1",
    displayNameEn: "Lower Extremity Injury",
    displayNameFr: "Blessure membre inférieur",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_lower_extremity",
    descriptionEn: "Lower extremity injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure du membre inférieur.",
    indicationKeywords: ["leg injury", "femur injury", "tibia fibula"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrFemur", "Femur X-ray", "Radiographie fémur", "XR_FEMUR"),
      imaging("xrTibFib", "Tibia/fibula X-ray", "Radiographie tibia/péroné", "XR_TIB_FIB"),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_hip_pain_v1",
    displayNameEn: "Hip Pain",
    displayNameFr: "Douleur de hanche",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_hip",
    descriptionEn: "Hip pain evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour douleur de hanche.",
    indicationKeywords: ["hip pain", "hip fracture", "trochanteric pain"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrHip", "Hip X-ray", "Radiographie hanche", "XR_HIP"),
      imaging("xrPelvis", "Pelvis X-ray", "Radiographie bassin", "XR_PELVIS"),
      care("orthopedicsConsult", "Orthopedics consult", "Consultation orthopédie", "orthopedics_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_ankle_injury_v1",
    displayNameEn: "Ankle Injury",
    displayNameFr: "Blessure à la cheville",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_ankle",
    descriptionEn: "Ankle injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure à la cheville.",
    indicationKeywords: ["ankle injury", "ankle sprain", "ankle fracture"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrAnkle", "Ankle X-ray", "Radiographie cheville", "XR_ANKLE"),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
      care("crutches", "Crutches", "Béquilles", "crutches", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_foot_injury_v1",
    displayNameEn: "Foot Injury",
    displayNameFr: "Blessure au pied",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_foot",
    descriptionEn: "Foot injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure au pied.",
    indicationKeywords: ["foot injury", "foot pain", "metatarsal"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrFoot", "Foot X-ray", "Radiographie pied", "XR_FOOT"),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_hand_injury_v1",
    displayNameEn: "Hand Injury",
    displayNameFr: "Blessure à la main",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_hand",
    descriptionEn: "Hand injury evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour blessure à la main.",
    indicationKeywords: ["hand injury", "finger injury", "hand fracture"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("xrHand", "Hand X-ray", "Radiographie main", "XR_HAND"),
      imaging("xrWrist", "Wrist X-ray", "Radiographie poignet", "XR_WRIST"),
      care("splint", "Splint application", "Pose d'attelle", "splint_application", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_back_pain_v1",
    displayNameEn: "Back Pain",
    displayNameFr: "Douleur dorsale",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_back",
    descriptionEn: "Acute back pain evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour douleur dorsale aiguë.",
    indicationKeywords: ["back pain", "lumbar pain", "sciatica"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("ctSpineLumbar", "CT lumbar spine", "TDM rachis lombaire", "CT_SPINE_LUMBAR"),
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_neck_pain_v1",
    displayNameEn: "Neck Pain",
    displayNameFr: "Douleur cervicale",
    category: "ORTHOPEDICS",
    department: "ED",
    clinicalDomain: "msk_neck",
    descriptionEn: "Neck pain evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour douleur cervicale.",
    indicationKeywords: ["neck pain", "cervical pain", "whiplash"],
    requiredItems: [care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document")],
    optionalItems: [
      imaging("ctCervicalSpine", "CT cervical spine", "TDM rachis cervical", "CT_CERVICAL_SPINE"),
      care("cervicalCollar", "Cervical collar", "Collier cervical", "cervical_collar", { deferIfMissing: true }),
      care("neuroChecks", "Neuro checks", "Surveillance neurologique", "neuro_check", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
];
