/**
 * Phase 4 ED — wound, OB/GYN, ENT, and metabolic order sets.
 */
import { care, imaging, lab, providerRoles, type EnterpriseOrderSetDefinition } from "../types.js";

export const WOUND_OB_ENT_METABOLIC_ED_ORDER_SETS: readonly EnterpriseOrderSetDefinition[] = [
  {
    code: "ed_laceration_v1",
    displayNameEn: "Laceration",
    displayNameFr: "Lacération",
    category: "WOUND",
    department: "ED",
    clinicalDomain: "wound_laceration",
    descriptionEn: "Laceration repair preparation bundle.",
    descriptionFr: "Ensemble de préparation pour lacération.",
    indicationKeywords: ["laceration", "cut", "wound repair"],
    requiredItems: [
      care("woundSetup", "Wound setup", "Préparation plaie", "wound_setup"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      care("lacerationRepair", "Laceration repair", "Suture de lacération", "laceration_repair", {
        deferIfMissing: true,
      }),
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_burn_v1",
    displayNameEn: "Burn",
    displayNameFr: "Brûlure",
    category: "WOUND",
    department: "ED",
    clinicalDomain: "wound_burn",
    descriptionEn: "Burn care and monitoring bundle.",
    descriptionFr: "Ensemble de soins et surveillance pour brûlure.",
    indicationKeywords: ["burn", "thermal injury", "scald"],
    requiredItems: [
      care("burnCare", "Burn care", "Soins de brûlure", "burn_care"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      care("pulseOximetry", "Pulse oximetry", "Oxymétrie de pouls", "pulse_oximetry"),
    ],
    optionalItems: [
      care("consultBurnCenter", "Burn center consult", "Consultation centre des brûlés", "consult_burn_center", {
        deferIfMissing: true,
      }),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      care("ivFluids", "IV fluids setup", "Pose de perfusion", "iv_fluids_setup", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_animal_bite_v1",
    displayNameEn: "Animal Bite",
    displayNameFr: "Morsure d'animal",
    category: "WOUND",
    department: "ED",
    clinicalDomain: "wound_animal_bite",
    descriptionEn: "Animal bite wound care bundle.",
    descriptionFr: "Ensemble de soins pour morsure d'animal.",
    indicationKeywords: ["animal bite", "dog bite", "cat bite"],
    requiredItems: [
      care("woundCare", "Wound care", "Soins de plaie", "wound_care"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      care("woundIrrigation", "Wound irrigation", "Irrigation de plaie", "wound_irrigation", {
        deferIfMissing: true,
      }),
      lab("woundCulture", "Wound culture", "Culture de plaie", "WOUND_CULTURE"),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_human_bite_v1",
    displayNameEn: "Human Bite",
    displayNameFr: "Morsure humaine",
    category: "WOUND",
    department: "ED",
    clinicalDomain: "wound_human_bite",
    descriptionEn: "Human bite wound care bundle.",
    descriptionFr: "Ensemble de soins pour morsure humaine.",
    indicationKeywords: ["human bite", "fight bite", "hand bite"],
    requiredItems: [
      care("woundCare", "Wound care", "Soins de plaie", "wound_care"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      care("woundIrrigation", "Wound irrigation", "Irrigation de plaie", "wound_irrigation", {
        deferIfMissing: true,
      }),
      imaging("xrHand", "Hand X-ray", "Radiographie main", "XR_HAND"),
      lab("woundCulture", "Wound culture", "Culture de plaie", "WOUND_CULTURE"),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_needlestick_v1",
    displayNameEn: "Needlestick / Body Fluid Exposure",
    displayNameFr: "Piqûre / exposition liquide biologique",
    category: "WOUND",
    department: "ED",
    clinicalDomain: "wound_needlestick",
    descriptionEn: "Occupational exposure evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour exposition professionnelle.",
    indicationKeywords: ["needlestick", "body fluid exposure", "occupational exposure"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("hiv", "HIV test", "Test VIH", "HIV"),
    ],
    optionalItems: [
      lab("hepB", "Hepatitis B rapid", "Hépatite B rapide", "HEP_B_RAPID"),
      lab("hepC", "Hepatitis C antibody", "Anticorps hépatite C", "HEP_C_AB"),
      care("socialWorkConsult", "Social work consult", "Consultation travailleur social", "social_work_consult", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_eye_complaint_v1",
    displayNameEn: "Eye Complaint",
    displayNameFr: "Plainte oculaire",
    category: "ENT",
    department: "ED",
    clinicalDomain: "ent_eye",
    descriptionEn: "Eye complaint evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour plainte oculaire.",
    indicationKeywords: ["eye pain", "red eye", "vision change"],
    requiredItems: [
      care("visualAcuity", "Visual acuity", "Acuité visuelle", "visual_acuity"),
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
    ],
    optionalItems: [
      care("eyeIrrigation", "Eye irrigation", "Irrigation oculaire", "eye_irrigation", { deferIfMissing: true }),
      care("eyePh", "Eye pH", "pH oculaire", "eye_ph", { deferIfMissing: true }),
      care("eyeTray", "Eye tray", "Plateau oculaire", "eye_tray", { deferIfMissing: true }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_vaginal_bleeding_v1",
    displayNameEn: "Vaginal Bleeding",
    displayNameFr: "Saignement vaginal",
    category: "OB_GYN",
    department: "ED",
    clinicalDomain: "ob_gyn_vaginal_bleeding",
    descriptionEn: "Vaginal bleeding evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour saignement vaginal.",
    indicationKeywords: ["vaginal bleeding", "abnormal uterine bleeding"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
      lab("hCG", "Beta hCG", "Beta-hCG", "HCG_BETA", ["SERUM_HCG", "HCG_URINE"]),
    ],
    optionalItems: [
      imaging("usPelvis", "Pelvic ultrasound", "Échographie pelvienne", "US_PELVIS"),
      care("pelvicExamSetup", "Pelvic exam setup", "Préparation examen pelvien", "pelvic_exam_setup", {
        deferIfMissing: true,
      }),
      lab("typeScreen", "Type and screen", "Groupe sanguin et RAI", "TYPE_SCREEN", ["ER_BLOOD_TYPE"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_pregnancy_evaluation_v1",
    displayNameEn: "Pregnancy Evaluation",
    displayNameFr: "Évaluation de grossesse",
    category: "OB_GYN",
    department: "ED",
    clinicalDomain: "ob_gyn_pregnancy",
    descriptionEn: "Early pregnancy evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour grossesse précoce.",
    indicationKeywords: ["pregnancy", "pregnant", "first trimester"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("hCG", "Beta hCG", "Beta-hCG", "HCG_BETA", ["SERUM_HCG", "HCG_URINE"]),
    ],
    optionalItems: [
      imaging("usOb", "Obstetric ultrasound", "Échographie obstétricale", "US_OB", ["US_OB_FIRST"]),
      care("pregnancyTest", "Pregnancy test", "Test de grossesse", "pregnancy_test", { deferIfMissing: true }),
      lab("cbc", "CBC", "NFS", "CBC", ["ER_CBC"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "ADULT",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_hyperglycemia_v1",
    displayNameEn: "Hyperglycemia",
    displayNameFr: "Hyperglycémie",
    category: "METABOLIC",
    department: "ED",
    clinicalDomain: "metabolic_hyperglycemia",
    descriptionEn: "Hyperglycemia evaluation bundle.",
    descriptionFr: "Ensemble d'évaluation pour hyperglycémie.",
    indicationKeywords: ["hyperglycemia", "dka", "high blood sugar"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
    ],
    optionalItems: [
      care("glucoseCheck", "Glucose check", "Contrôle glycémique", "glucose_check", { deferIfMissing: true }),
      lab("hba1c", "HbA1c", "HbA1c", "HBA1C"),
      care("peripheralIv", "Peripheral IV placement", "Pose de VVP", "peripheral_iv_placement", {
        deferIfMissing: true,
      }),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
  {
    code: "ed_hypoglycemia_v1",
    displayNameEn: "Hypoglycemia",
    displayNameFr: "Hypoglycémie",
    category: "METABOLIC",
    department: "ED",
    clinicalDomain: "metabolic_hypoglycemia",
    descriptionEn: "Hypoglycemia evaluation and monitoring bundle.",
    descriptionFr: "Ensemble d'évaluation et surveillance pour hypoglycémie.",
    indicationKeywords: ["hypoglycemia", "low blood sugar"],
    requiredItems: [
      care("vitalsQ15", "Vital signs q15", "Signes vitaux q15", "vitals_q15_document"),
      lab("glucose", "Glucose", "Glycémie", "GLU", ["ER_GLU"]),
      care("glucoseCheck", "Glucose check", "Contrôle glycémique", "glucose_check"),
    ],
    optionalItems: [
      care("constantObservation", "Constant observation", "Surveillance constante", "constant_observation", {
        deferIfMissing: true,
      }),
      lab("cmp", "CMP", "Bilan métabolique complet", "CMP", ["ER_CMP"]),
    ],
    warnings: [],
    rolesAllowed: providerRoles,
    ageGroup: "BOTH",
    version: "1.0.0",
    isActive: true,
    governanceLevel: "PHASE_4_ED",
  },
];
