#!/usr/bin/env bash
#
# Medora S — Cloud Agent install / one-time setup.
#
# Runs once when the Cloud Agent environment is prepared (or at environment-build
# time). It provisions a DISPOSABLE, LOCAL-ONLY PostgreSQL database and prepares
# the monorepo so that the API (:3001) and Web (:3002) dev servers can be started.
#
# Safe to re-run: every step is idempotent. It NEVER talks to a production
# database, NEVER authors migrations, and NEVER runs `prisma migrate dev`.
#
# Package manager: pnpm (pinned via package.json "packageManager"). npm is NOT
# used for install because the workspaces declare `workspace:*` dependencies.
set -euo pipefail

log() { printf '\n\033[1;36m[medora-install]\033[0m %s\n' "$*"; }

# Resolve repo root (two levels up from .cursor/scripts/).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# ---------------------------------------------------------------------------
# Disposable local PostgreSQL configuration (LOCAL-ONLY — no production data).
# ---------------------------------------------------------------------------
PG_MAJOR="${MEDORA_PG_MAJOR:-16}"
DB_NAME="${MEDORA_DB_NAME:-medora}"
DB_USER="${MEDORA_DB_USER:-medora}"
DB_PASSWORD="${MEDORA_DB_PASSWORD:-medora}"
LOCAL_DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}?schema=public"

# ---------------------------------------------------------------------------
# 1. Ensure PostgreSQL 16 is installed and the cluster is running.
# ---------------------------------------------------------------------------
log "Ensuring PostgreSQL ${PG_MAJOR} is installed…"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    "postgresql-${PG_MAJOR}" postgresql-contrib >/dev/null
fi

log "Ensuring the PostgreSQL cluster is running…"
sudo pg_ctlcluster "${PG_MAJOR}" main start 2>/dev/null || true
# Wait until the server accepts connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

# ---------------------------------------------------------------------------
# 2. Ensure the disposable role + database exist (idempotent).
# ---------------------------------------------------------------------------
log "Ensuring disposable database role '${DB_USER}' and database '${DB_NAME}'…"
sudo -u postgres psql -v ON_ERROR_STOP=1 -tAc \
  "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 || \
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
  "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}' CREATEDB;"

sudo -u postgres psql -v ON_ERROR_STOP=1 -tAc \
  "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
  "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

# ---------------------------------------------------------------------------
# 3. Ensure local env files (created only if missing; secrets never committed).
# ---------------------------------------------------------------------------
log "Ensuring apps/api/.env…"
# A stray apps/api/prisma/.env would shadow apps/api/.env for Prisma — remove it.
rm -f apps/api/prisma/.env
if [ ! -f apps/api/.env ]; then
  DB_URL="${DATABASE_URL:-$LOCAL_DATABASE_URL}"
  JWT_A="${JWT_ACCESS_SECRET:-$(openssl rand -hex 32)}"
  JWT_R="${JWT_REFRESH_SECRET:-$(openssl rand -hex 32)}"
  cat > apps/api/.env <<EOF
# Local Cloud Agent dev env — generated by .cursor/scripts/cloud-agent-install.sh
# DISPOSABLE local database only. Do not point this at production.
DATABASE_URL="${DB_URL}"
PORT=3001
JWT_ACCESS_SECRET=${JWT_A}
JWT_REFRESH_SECRET=${JWT_R}
JWT_ACCESS_TTL=8h
JWT_REFRESH_TTL=14d
TOKEN_ISSUER=medora-s
RESET_PASSWORD_BASE_URL=http://localhost:3002
EOF
fi

log "Ensuring apps/web/.env…"
if [ ! -f apps/web/.env ]; then
  cat > apps/web/.env <<EOF
# Local Cloud Agent dev env — generated by .cursor/scripts/cloud-agent-install.sh
API_URL=http://localhost:3001
JWT_ACCESS_TTL=8h
EOF
fi

# ---------------------------------------------------------------------------
# 4. Activate the repo-pinned pnpm and install dependencies.
# ---------------------------------------------------------------------------
log "Activating pnpm (from package.json packageManager)…"
PM="$(node -e "process.stdout.write(require('./package.json').packageManager || '')")"
if [ -n "$PM" ] && command -v corepack >/dev/null 2>&1; then
  corepack prepare "$PM" --activate
fi

log "Installing dependencies (pnpm install)…"
if ! pnpm install --frozen-lockfile; then
  log "Frozen install failed; retrying without --frozen-lockfile…"
  pnpm install --no-frozen-lockfile
fi

# ---------------------------------------------------------------------------
# 5. Build shared package + generate Prisma client.
# ---------------------------------------------------------------------------
log "Building @medora/shared…"
pnpm --filter @medora/shared build

log "Generating Prisma client…"
pnpm --filter @medora/api prisma:generate

# ---------------------------------------------------------------------------
# 6. Apply existing migrations to the disposable DB (NEVER migrate dev).
# ---------------------------------------------------------------------------
log "Applying migrations (prisma migrate deploy)…"
pnpm --filter @medora/api migrate:deploy

# ---------------------------------------------------------------------------
# 7. Seed the minimum required bootstrap data (idempotent, non-destructive).
#    core  = roles + geo reference; bootstrap-facilities = DR/HT facilities + depts.
# ---------------------------------------------------------------------------
log "Seeding core roles + geo…"
pnpm --filter @medora/api prisma:seed:core

log "Bootstrapping facilities + departments…"
pnpm --filter @medora/api seed:bootstrap-facilities

# ---------------------------------------------------------------------------
# 8. Create the synthetic development admin (idempotent; dev-only, guarded).
# ---------------------------------------------------------------------------
log "Ensuring development admin account…"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@medora.local}" \
ADMIN_PASSWORD="${ADMIN_PASSWORD:-Admin123!}" \
  pnpm --filter @medora/api create-admin

log "Install complete. Start services with .cursor/scripts/cloud-agent-start.sh (or the configured terminals)."
