/**
 * M1.6B — Enterprise Wave 1 formulary manifest (anticoagulation, vaccines, chronic care core).
 */

import { deriveMedicationCatalogCode } from "./medicationCatalogCodeDerive.js";
import type { EnterpriseWave1FormularyEntry } from "./enterpriseWave1Types.js";

function row(
  partial: Omit<EnterpriseWave1FormularyEntry, "catalogCode"> & { catalogCode?: string }
): EnterpriseWave1FormularyEntry {
  const catalogCode =
    partial.catalogCode ??
    deriveMedicationCatalogCode({
      genericName: partial.genericName,
      strength: partial.strength,
      dosageForm: partial.dosageForm,
      route: partial.route,
    });
  return { ...partial, catalogCode };
}

const oral = (g: string, fr: string, en: string, strength: string, tc: string, aliases: string[]) =>
  row({
    genericName: g,
    displayNameFr: fr,
    displayNameEn: en,
    strength,
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: tc,
    bucket: "CHRONIC_CARE",
    mode: "CREATE",
    aliases,
    searchTerms: [g.toLowerCase(), ...aliases.map((a) => a.toLowerCase())],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  });

const anticoagOral = (
  g: string,
  en: string,
  strength: string,
  aliases: string[],
  gov: Partial<EnterpriseWave1FormularyEntry["governance"]> = {}
) =>
  row({
    genericName: g,
    displayNameFr: g,
    displayNameEn: en,
    strength,
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Anticoagulant",
    bucket: "ANTICOAGULATION",
    mode: "CREATE",
    aliases,
    searchTerms: [g.toLowerCase(), ...aliases.map((a) => a.toLowerCase())],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: true,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
      ...gov,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  });

const vaccine = (
  g: string,
  en: string,
  strength: string,
  aliases: string[],
  cvxSearch: string[]
) =>
  row({
    genericName: g,
    displayNameFr: g,
    displayNameEn: en,
    strength,
    dosageForm: "injectable",
    route: "injectable-intramuscular",
    therapeuticClass: "Vaccine",
    bucket: "VACCINE",
    mode: "CREATE",
    aliases,
    searchTerms: [g.toLowerCase(), ...aliases.map((a) => a.toLowerCase()), ...cvxSearch],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
    },
    isEssential: true,
    administrationType: "IM",
    billingClass: "DRUG_SUPPLY",
  });

/** Wave 1 formulary rows (CREATE + ENRICH). */
export const ENTERPRISE_WAVE1_FORMULARY_MANIFEST: EnterpriseWave1FormularyEntry[] = [
  // --- Anticoagulation (CREATE) ---
  anticoagOral("Warfarin", "Warfarin", "5 mg", ["Coumadin", "Jantoven"], {
    isHighAlert: true,
    requiresWitness: true,
    requiresDoubleSign: true,
  }),
  row({
    catalogCode: "ENOXAPARIN_40_MG_PER_0.4_ML_INJECTABLE_INJECTION",
    genericName: "Enoxaparin",
    displayNameFr: "Énoxaparine",
    displayNameEn: "Enoxaparin",
    strength: "40 mg/0.4 mL",
    dosageForm: "injectable",
    route: "injectable",
    therapeuticClass: "Anticoagulant",
    bucket: "ANTICOAGULATION",
    mode: "CREATE",
    aliases: ["Lovenox", "lovenox"],
    searchTerms: ["enoxaparin", "lovenox"],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: true,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
    },
    isEssential: true,
    administrationType: "INJECTION",
    billingClass: "DRUG_SUPPLY",
  }),
  anticoagOral("Apixaban", "Apixaban", "5 mg", ["Eliquis", "eliquis"]),
  anticoagOral("Rivaroxaban", "Rivaroxaban", "20 mg", ["Xarelto", "xarelto"]),
  anticoagOral("Dabigatran", "Dabigatran", "150 mg", ["Pradaxa", "pradaxa"]),
  anticoagOral("Edoxaban", "Edoxaban", "60 mg", ["Savaysa", "savaysa"]),
  // Heparin — ENRICH existing Haiti row
  row({
    catalogCode: "HEPARIN_5000UI_ML_INJECTABLE",
    genericName: "Heparin",
    displayNameFr: "Héparine",
    displayNameEn: "Heparin",
    strength: "5,000 UI/mL",
    dosageForm: "injectable",
    route: "injectable",
    therapeuticClass: "Anticoagulant",
    bucket: "ANTICOAGULATION",
    mode: "ENRICH",
    aliases: ["heparin sodium", "Hep-Lock"],
    searchTerms: ["heparin", "héparine"],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: true,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
    },
    isEssential: true,
    administrationType: "SQ",
    billingClass: "DRUG_SUPPLY",
  }),

  // --- Vaccines (CREATE) ---
  vaccine("Influenza vaccine", "Influenza vaccine", "0.5 mL", ["flu shot", "Fluzone"], ["influenza", "flu"]),
  vaccine("COVID-19 vaccine", "COVID-19 vaccine", "0.3 mL", ["COVID vaccine", "Comirnaty"], ["covid", "covid-19"]),
  vaccine("Tdap vaccine", "Tdap vaccine", "0.5 mL", ["Adacel", "Boostrix"], ["tdap", "pertussis"]),
  vaccine("Td vaccine", "Td vaccine", "0.5 mL", ["tetanus diphtheria", "Tenivac"], ["td vaccine"]),
  vaccine("MMR vaccine", "MMR vaccine", "0.5 mL", ["M-M-R II", "Priorix"], ["mmr", "measles"]),
  vaccine("Varicella vaccine", "Varicella vaccine", "0.5 mL", ["Varivax"], ["varicella", "chickenpox"]),
  vaccine("Zoster vaccine", "Shingrix", "0.5 mL", ["Shingrix", "zoster", "shingles"], ["shingrix", "zoster"]),
  vaccine("Pneumococcal vaccine", "Pneumococcal vaccine", "0.5 mL", ["Prevnar", "Pneumovax"], ["pneumococcal", "pneumonia vaccine"]),
  vaccine("Hepatitis A vaccine", "Hepatitis A vaccine", "1 mL", ["Havrix", "Vaqta"], ["hepatitis a", "hep a"]),
  vaccine("Hepatitis B vaccine", "Hepatitis B vaccine", "1 mL", ["Engerix-B", "Recombivax"], ["hepatitis b", "hep b"]),
  vaccine("HPV vaccine", "HPV vaccine", "0.5 mL", ["Gardasil 9"], ["hpv", "human papillomavirus"]),
  vaccine("Meningococcal vaccine", "Meningococcal vaccine", "0.5 mL", ["Menveo", "Menactra"], ["meningococcal", "meningitis vaccine"]),
  vaccine("RSV vaccine", "RSV vaccine", "0.5 mL", ["Abrysvo", "Arexvy"], ["rsv", "respiratory syncytial"]),

  // --- Chronic care — CREATE (net-new) ---
  oral("Atorvastatin", "Atorvastatine", "Atorvastatin", "20 mg", "Hypolipémiant", ["Lipitor", "lipitor"]),
  oral("Rosuvastatin", "Rosuvastatine", "Rosuvastatin", "10 mg", "Hypolipémiant", ["Crestor", "crestor"]),
  oral("Glipizide", "Glipizide", "Glipizide", "5 mg", "Antidiabétique", ["Glucotrol"]),
  oral("Empagliflozin", "Empagliflozine", "Empagliflozin", "10 mg", "Antidiabétique", ["Jardiance", "jardiance"]),
  oral("Dapagliflozin", "Dapagliflozine", "Dapagliflozin", "10 mg", "Antidiabétique", ["Farxiga", "farxiga"]),
  row({
    genericName: "Semaglutide",
    displayNameFr: "Sémaglutide",
    displayNameEn: "Semaglutide",
    strength: "0.25 mg",
    dosageForm: "injectable",
    route: "sous-cutanée",
    therapeuticClass: "Antidiabétique",
    bucket: "CHRONIC_CARE",
    mode: "CREATE",
    aliases: ["Ozempic", "Wegovy", "ozempic"],
    searchTerms: ["semaglutide", "ozempic"],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
    },
    isEssential: false,
    administrationType: "SUBCUTANEOUS",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    genericName: "Tirzepatide",
    displayNameFr: "Tirzépatide",
    displayNameEn: "Tirzepatide",
    strength: "2.5 mg",
    dosageForm: "injectable",
    route: "sous-cutanée",
    therapeuticClass: "Antidiabétique",
    bucket: "CHRONIC_CARE",
    mode: "CREATE",
    aliases: ["Mounjaro", "Zepbound", "mounjaro"],
    searchTerms: ["tirzepatide", "mounjaro"],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: true,
    },
    isEssential: false,
    administrationType: "SUBCUTANEOUS",
    billingClass: "DRUG_SUPPLY",
  }),
  oral("Sertraline", "Sertraline", "Sertraline", "50 mg", "Psychiatrie", ["Zoloft", "zoloft"]),
  oral("Escitalopram", "Escitalopram", "Escitalopram", "10 mg", "Psychiatrie", ["Lexapro", "lexapro"]),
  oral("Fluoxetine", "Fluoxétine", "Fluoxetine", "20 mg", "Psychiatrie", ["Prozac", "prozac"]),
  oral("Bupropion", "Bupropion", "Bupropion", "150 mg", "Psychiatrie", ["Wellbutrin", "wellbutrin"]),
  oral("Finasteride", "Finastéride", "Finasteride", "5 mg", "Urologie", ["Proscar", "proscar"]),
  oral("Tamsulosin", "Tamsulosine", "Tamsulosin", "0.4 mg", "Urologie", ["Flomax", "flomax"]),
  oral("Famotidine", "Famotidine", "Famotidine", "20 mg", "IPP", ["Pepcid", "pepcid"]),
  oral("Metoprolol", "Métoprolol", "Metoprolol", "25 mg", "Bêta-bloquant", ["Lopressor", "Toprol", "toprol"]),

  // --- Chronic care — ENRICH (Haiti existing; aliases + billing fixup) ---
  row({
    catalogCode: "METFORMIN_500",
    genericName: "Metformin",
    displayNameFr: "Metformine",
    displayNameEn: "Metformin",
    strength: "500 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Antidiabétique",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["glucophage"],
    searchTerms: ["metformin"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "AMLODIPINE_5_MG_COMPRIME_ORAL",
    genericName: "Amlodipine",
    displayNameFr: "Amlodipine",
    displayNameEn: "Amlodipine",
    strength: "5 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Antihypertenseur",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["norvasc"],
    searchTerms: ["amlodipine"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "LISINOPRIL_10",
    genericName: "Lisinopril",
    displayNameFr: "Lisinopril",
    displayNameEn: "Lisinopril",
    strength: "10 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Antihypertenseur",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["zestril", "prinivil"],
    searchTerms: ["lisinopril"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "LOSARTAN_50",
    genericName: "Losartan",
    displayNameFr: "Losartan",
    displayNameEn: "Losartan",
    strength: "50 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Antihypertenseur",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["cozaar"],
    searchTerms: ["losartan"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "HYDROCHLOROTHIAZIDE_25",
    genericName: "Hydrochlorothiazide",
    displayNameFr: "Hydrochlorothiazide",
    displayNameEn: "Hydrochlorothiazide",
    strength: "25 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Diurétique",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["hctz", "microzide"],
    searchTerms: ["hydrochlorothiazide", "hctz"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "CARVEDILOL_6.25_MG_COMPRIME_ORAL",
    genericName: "Carvedilol",
    displayNameFr: "Carvédilol",
    displayNameEn: "Carvedilol",
    strength: "6.25 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Bêta-bloquant",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["coreg"],
    searchTerms: ["carvedilol"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: false,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "SIMVASTATIN_20_MG_COMPRIME_ORAL",
    genericName: "Simvastatin",
    displayNameFr: "Simvastatine",
    displayNameEn: "Simvastatin",
    strength: "20 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Hypolipémiant",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["zocor"],
    searchTerms: ["simvastatin"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "LEVOTHYROXINE_50_MCG_COMPRIME_ORAL",
    genericName: "Levothyroxine",
    displayNameFr: "Lévothyroxine",
    displayNameEn: "Levothyroxine",
    strength: "50 mcg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "Thyroïde",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["synthroid", "levoxyl"],
    searchTerms: ["levothyroxine", "synthroid"],
    governance: {
      isControlled: false,
      isHighAlert: true,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "OMEPRAZOLE_20",
    genericName: "Omeprazole",
    displayNameFr: "Oméprazole",
    displayNameEn: "Omeprazole",
    strength: "20 mg",
    dosageForm: "gélule",
    route: "orale",
    therapeuticClass: "IPP",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["losec", "prilosec"],
    searchTerms: ["omeprazole"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
  row({
    catalogCode: "PANTOPRAZOLE_40_MG_COMPRIME_ORAL",
    genericName: "Pantoprazole",
    displayNameFr: "Pantoprazole",
    displayNameEn: "Pantoprazole",
    strength: "40 mg",
    dosageForm: "comprimé",
    route: "orale",
    therapeuticClass: "IPP",
    bucket: "CHRONIC_CARE",
    mode: "ENRICH",
    aliases: ["protonix", "pantozol"],
    searchTerms: ["pantoprazole"],
    governance: {
      isControlled: false,
      isHighAlert: false,
      requiresWitness: false,
      requiresDoubleSign: false,
      requiresPharmacyVerification: false,
    },
    isEssential: true,
    administrationType: "ORAL",
    billingClass: "DRUG_SUPPLY",
  }),
];

export const ENTERPRISE_WAVE1_FORMULARY_BY_CODE: Record<string, EnterpriseWave1FormularyEntry> =
  Object.fromEntries(ENTERPRISE_WAVE1_FORMULARY_MANIFEST.map((e) => [e.catalogCode, e]));

export const ENTERPRISE_WAVE1_FORMULARY_VERSION = "M1.6B" as const;
