/**
 * Broad clinical medication validation corpus for provider-facing availability.
 * Hundreds of high-frequency brand/generic families across specialties.
 */

export type ProviderClinicalCorpusFamily = {
  id: string;
  specialty: string;
  brandQueries: readonly string[];
  genericQueries: readonly string[];
  requiredStrengthSubstrings?: readonly string[];
  hardAcceptance?: boolean;
};

const HIV: ProviderClinicalCorpusFamily[] = [
  {
    id: "biktarvy",
    specialty: "HIV",
    brandQueries: ["Biktarvy", "bikt"],
    genericQueries: [
      "bictegravir",
      "emtricitabine",
      "tenofovir alafenamide",
      "bictegravir emtricitabine tenofovir alafenamide",
    ],
    requiredStrengthSubstrings: ["50 mg", "200 mg", "25 mg"],
    hardAcceptance: true,
  },
  {
    id: "triumeq",
    specialty: "HIV",
    brandQueries: ["Triumeq"],
    genericQueries: ["dolutegravir", "abacavir", "lamivudine"],
  },
  {
    id: "dovato",
    specialty: "HIV",
    brandQueries: ["Dovato"],
    genericQueries: ["dolutegravir", "lamivudine"],
  },
  {
    id: "genvoya",
    specialty: "HIV",
    brandQueries: ["Genvoya"],
    genericQueries: ["elvitegravir", "cobicistat", "emtricitabine"],
  },
  {
    id: "descovy",
    specialty: "HIV",
    brandQueries: ["Descovy"],
    genericQueries: ["emtricitabine", "tenofovir alafenamide"],
  },
  {
    id: "truvada",
    specialty: "HIV",
    brandQueries: ["Truvada"],
    genericQueries: ["emtricitabine", "tenofovir"],
  },
];

const ENDOCRINE: ProviderClinicalCorpusFamily[] = [
  {
    id: "jardiance",
    specialty: "ENDOCRINE",
    brandQueries: ["Jardiance", "jard", "jar"],
    genericQueries: ["Empagliflozin", "empagliflozin"],
    requiredStrengthSubstrings: ["10 mg", "25 mg"],
    hardAcceptance: true,
  },
  {
    id: "farxiga",
    specialty: "ENDOCRINE",
    brandQueries: ["Farxiga"],
    genericQueries: ["dapagliflozin"],
  },
  {
    id: "invokana",
    specialty: "ENDOCRINE",
    brandQueries: ["Invokana"],
    genericQueries: ["canagliflozin"],
  },
  {
    id: "ozempic",
    specialty: "ENDOCRINE",
    brandQueries: ["Ozempic"],
    genericQueries: ["semaglutide"],
  },
  {
    id: "wegovy",
    specialty: "ENDOCRINE",
    brandQueries: ["Wegovy"],
    genericQueries: ["semaglutide"],
  },
  {
    id: "rybelsus",
    specialty: "ENDOCRINE",
    brandQueries: ["Rybelsus"],
    genericQueries: ["semaglutide"],
  },
  {
    id: "mounjaro",
    specialty: "ENDOCRINE",
    brandQueries: ["Mounjaro"],
    genericQueries: ["tirzepatide"],
  },
  {
    id: "zepbound",
    specialty: "ENDOCRINE",
    brandQueries: ["Zepbound"],
    genericQueries: ["tirzepatide"],
  },
  {
    id: "trulicity",
    specialty: "ENDOCRINE",
    brandQueries: ["Trulicity"],
    genericQueries: ["dulaglutide"],
  },
  {
    id: "lantus",
    specialty: "ENDOCRINE",
    brandQueries: ["Lantus"],
    genericQueries: ["insulin glargine"],
    requiredStrengthSubstrings: ["100"],
  },
  {
    id: "humalog",
    specialty: "ENDOCRINE",
    brandQueries: ["Humalog"],
    genericQueries: ["insulin lispro"],
  },
  {
    id: "novolog",
    specialty: "ENDOCRINE",
    brandQueries: ["NovoLog", "Novolog"],
    genericQueries: ["insulin aspart"],
  },
  {
    id: "tresiba",
    specialty: "ENDOCRINE",
    brandQueries: ["Tresiba"],
    genericQueries: ["insulin degludec"],
  },
  {
    id: "metformin",
    specialty: "ENDOCRINE",
    brandQueries: ["Glucophage"],
    genericQueries: ["Metformin"],
    requiredStrengthSubstrings: ["500 mg"],
  },
];

const CARDIO: ProviderClinicalCorpusFamily[] = [
  {
    id: "eliquis",
    specialty: "CARDIOLOGY",
    brandQueries: ["Eliquis"],
    genericQueries: ["apixaban"],
    requiredStrengthSubstrings: ["5 mg"],
  },
  {
    id: "xarelto",
    specialty: "CARDIOLOGY",
    brandQueries: ["Xarelto"],
    genericQueries: ["rivaroxaban"],
  },
  {
    id: "pradaxa",
    specialty: "CARDIOLOGY",
    brandQueries: ["Pradaxa"],
    genericQueries: ["dabigatran"],
  },
  {
    id: "entresto",
    specialty: "CARDIOLOGY",
    brandQueries: ["Entresto"],
    genericQueries: ["sacubitril", "valsartan"],
  },
  {
    id: "furosemide",
    specialty: "CARDIOLOGY",
    brandQueries: ["Lasix"],
    genericQueries: ["Furosemide"],
    requiredStrengthSubstrings: ["40 mg"],
  },
  {
    id: "atorvastatin",
    specialty: "CARDIOLOGY",
    brandQueries: ["Lipitor"],
    genericQueries: ["atorvastatin"],
  },
  {
    id: "amlodipine",
    specialty: "CARDIOLOGY",
    brandQueries: ["Norvasc"],
    genericQueries: ["amlodipine"],
  },
  {
    id: "lisinopril",
    specialty: "CARDIOLOGY",
    brandQueries: ["Zestril", "Prinivil"],
    genericQueries: ["lisinopril"],
  },
  {
    id: "metoprolol",
    specialty: "CARDIOLOGY",
    brandQueries: ["Lopressor", "Toprol"],
    genericQueries: ["metoprolol"],
  },
  {
    id: "clopidogrel",
    specialty: "CARDIOLOGY",
    brandQueries: ["Plavix"],
    genericQueries: ["clopidogrel"],
  },
];

const ID_EM: ProviderClinicalCorpusFamily[] = [
  {
    id: "ceftriaxone",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: ["Rocephin"],
    genericQueries: ["Ceftriaxone"],
    requiredStrengthSubstrings: ["1 g", "2 g"],
  },
  {
    id: "vancomycin",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: [],
    genericQueries: ["Vancomycin"],
  },
  {
    id: "pip-tazo",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: ["Zosyn"],
    genericQueries: ["piperacillin", "tazobactam"],
  },
  {
    id: "azithromycin",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: ["Zithromax"],
    genericQueries: ["azithromycin"],
  },
  {
    id: "cefepime",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: ["Maxipime"],
    genericQueries: ["cefepime"],
  },
  {
    id: "meropenem",
    specialty: "INFECTIOUS_DISEASE",
    brandQueries: ["Merrem"],
    genericQueries: ["meropenem"],
  },
];

const COMMON: ProviderClinicalCorpusFamily[] = [
  {
    id: "acetaminophen",
    specialty: "PAIN_OTC",
    brandQueries: ["Tylenol"],
    genericQueries: ["Acetaminophen", "Paracetamol"],
    requiredStrengthSubstrings: ["500 mg"],
  },
  {
    id: "ibuprofen",
    specialty: "PAIN_OTC",
    brandQueries: ["Advil", "Motrin"],
    genericQueries: ["Ibuprofen"],
    requiredStrengthSubstrings: ["200 mg", "400 mg"],
  },
  {
    id: "ondansetron",
    specialty: "GI",
    brandQueries: ["Zofran"],
    genericQueries: ["Ondansetron"],
    requiredStrengthSubstrings: ["4 mg", "8 mg"],
  },
  {
    id: "albuterol",
    specialty: "PULMONARY",
    brandQueries: ["Ventolin", "ProAir"],
    genericQueries: ["Albuterol", "Salbutamol"],
    requiredStrengthSubstrings: ["2.5 mg"],
  },
  {
    id: "pantoprazole",
    specialty: "GI",
    brandQueries: ["Protonix"],
    genericQueries: ["Pantoprazole"],
    requiredStrengthSubstrings: ["40 mg"],
  },
  {
    id: "normal-saline",
    specialty: "CRITICAL_CARE",
    brandQueries: [],
    genericQueries: ["Normal Saline", "sodium chloride"],
    requiredStrengthSubstrings: ["0.9"],
  },
  {
    id: "lr",
    specialty: "CRITICAL_CARE",
    brandQueries: [],
    genericQueries: ["Lactated Ringer", "Lactated Ringers"],
    requiredStrengthSubstrings: ["500"],
  },
  {
    id: "kcl",
    specialty: "ELECTROLYTES",
    brandQueries: [],
    genericQueries: ["Potassium chloride", "KCL"],
  },
  {
    id: "mag-sulfate",
    specialty: "ELECTROLYTES",
    brandQueries: [],
    genericQueries: ["Magnesium sulfate"],
  },
  {
    id: "amoxicillin",
    specialty: "PRIMARY_CARE",
    brandQueries: ["Amoxil"],
    genericQueries: ["Amoxicillin"],
    requiredStrengthSubstrings: ["500 mg"],
  },
];

/** Generate additional high-frequency families from common INN/brand pairs. */
function buildExtendedCorpus(): ProviderClinicalCorpusFamily[] {
  const pairs: Array<[string, string, string]> = [
    ["PRIMARY_CARE", "omeprazole", "Prilosec"],
    ["PRIMARY_CARE", "amlodipine", "Norvasc"],
    ["PRIMARY_CARE", "losartan", "Cozaar"],
    ["PRIMARY_CARE", "hydrochlorothiazide", "Microzide"],
    ["PRIMARY_CARE", "sertraline", "Zoloft"],
    ["PSYCHIATRY", "escitalopram", "Lexapro"],
    ["PSYCHIATRY", "fluoxetine", "Prozac"],
    ["PSYCHIATRY", "quetiapine", "Seroquel"],
    ["PSYCHIATRY", "olanzapine", "Zyprexa"],
    ["PSYCHIATRY", "aripiprazole", "Abilify"],
    ["PSYCHIATRY", "lorazepam", "Ativan"],
    ["PSYCHIATRY", "alprazolam", "Xanax"],
    ["NEUROLOGY", "levetiracetam", "Keppra"],
    ["NEUROLOGY", "gabapentin", "Neurontin"],
    ["NEUROLOGY", "pregabalin", "Lyrica"],
    ["NEUROLOGY", "sumatriptan", "Imitrex"],
    ["NEPHROLOGY", "sevelamer", "Renvela"],
    ["RHEUMATOLOGY", "methotrexate", "Trexall"],
    ["RHEUMATOLOGY", "prednisone", "Deltasone"],
    ["DERMATOLOGY", "hydrocortisone", "Cortef"],
    ["OPHTHALMOLOGY", "latanoprost", "Xalatan"],
    ["ENT", "fluticasone", "Flonase"],
    ["PEDIATRICS", "amoxicillin", "Amoxil"],
    ["OBGYN", "misoprostol", "Cytotec"],
    ["GI", "ondansetron", "Zofran"],
    ["GI", "metoclopramide", "Reglan"],
    ["GI", "sucralfate", "Carafate"],
    ["UROLOGY", "tamsulosin", "Flomax"],
    ["ONCOLOGY_SUPPORT", "ondansetron", "Zofran"],
    ["ONCOLOGY_SUPPORT", "dexamethasone", "Decadron"],
    ["CRITICAL_CARE", "norepinephrine", "Levophed"],
    ["CRITICAL_CARE", "epinephrine", "Adrenalin"],
    ["CRITICAL_CARE", "propofol", "Diprivan"],
    ["CRITICAL_CARE", "fentanyl", "Sublimaze"],
    ["PAIN", "morphine", "MS Contin"],
    ["PAIN", "oxycodone", "OxyContin"],
    ["PAIN", "hydromorphone", "Dilaudid"],
    ["ANTICOAGULATION", "enoxaparin", "Lovenox"],
    ["ANTICOAGULATION", "heparin", "Heparin"],
    ["ANTICOAGULATION", "warfarin", "Coumadin"],
    ["VACCINES", "influenza vaccine", "Fluzone"],
    ["VACCINES", "tdap", "Adacel"],
    ["PULMONARY", "budesonide", "Pulmicort"],
    ["PULMONARY", "ipratropium", "Atrovent"],
    ["INFECTIOUS_DISEASE", "doxycycline", "Vibramycin"],
    ["INFECTIOUS_DISEASE", "levofloxacin", "Levaquin"],
    ["INFECTIOUS_DISEASE", "ciprofloxacin", "Cipro"],
    ["INFECTIOUS_DISEASE", "metronidazole", "Flagyl"],
    ["INFECTIOUS_DISEASE", "fluconazole", "Diflucan"],
    ["CARDIOLOGY", "carvedilol", "Coreg"],
    ["CARDIOLOGY", "spironolactone", "Aldactone"],
    ["CARDIOLOGY", "digoxin", "Lanoxin"],
    ["CARDIOLOGY", "amiodarone", "Pacerone"],
    ["ENDOCRINE", "levothyroxine", "Synthroid"],
    ["ENDOCRINE", "glipizide", "Glucotrol"],
    ["ENDOCRINE", "sitagliptin", "Januvia"],
    ["ER", "naloxone", "Narcan"],
    ["ER", "flumazenil", "Romazicon"],
    ["ER", "atropine", "Atropine"],
    ["ER", "adenosine", "Adenocard"],
    ["ER", "diltiazem", "Cardizem"],
    ["ER", "haloperidol", "Haldol"],
    ["ER", "ketamine", "Ketalar"],
    ["ER", "midazolam", "Versed"],
    ["ER", "etomidate", "Amidate"],
    ["ER", "succinylcholine", "Anectine"],
    ["ER", "rocuronium", "Zemuron"],
    ["FLUIDS", "dextrose", "D5W"],
    ["FLUIDS", "albumin", "Albumin"],
    ["ELECTROLYTES", "calcium gluconate", "Calcium gluconate"],
    ["ELECTROLYTES", "sodium bicarbonate", "Sodium bicarbonate"],
    ["PRIMARY_CARE", "cetirizine", "Zyrtec"],
    ["PRIMARY_CARE", "loratadine", "Claritin"],
    ["PRIMARY_CARE", "diphenhydramine", "Benadryl"],
    ["PRIMARY_CARE", "acetaminophen", "Tylenol"],
    ["PRIMARY_CARE", "naproxen", "Aleve"],
    ["PRIMARY_CARE", "aspirin", "Aspirin"],
    ["GI", "loperamide", "Imodium"],
    ["GI", "docusate", "Colace"],
    ["GI", "polyethylene glycol", "Miralax"],
    ["PSYCHIATRY", "trazodone", "Desyrel"],
    ["PSYCHIATRY", "mirtazapine", "Remeron"],
    ["PSYCHIATRY", "bupropion", "Wellbutrin"],
    ["NEUROLOGY", "topiramate", "Topamax"],
    ["NEUROLOGY", "carbamazepine", "Tegretol"],
    ["NEUROLOGY", "valproate", "Depakote"],
    ["RHEUMATOLOGY", "allopurinol", "Zyloprim"],
    ["RHEUMATOLOGY", "colchicine", "Colcrys"],
    ["DERMATOLOGY", "triamcinolone", "Kenalog"],
    ["OPHTHALMOLOGY", "timolol", "Timoptic"],
    ["ENT", "amoxicillin clavulanate", "Augmentin"],
    ["OBGYN", "medroxyprogesterone", "Provera"],
    ["UROLOGY", "finasteride", "Proscar"],
    ["ONCOLOGY_SUPPORT", "filgrastim", "Neupogen"],
    ["ONCOLOGY_SUPPORT", "olanzapine", "Zyprexa"],
    ["VACCINES", "hepatitis b vaccine", "Engerix"],
    ["VACCINES", "pneumococcal vaccine", "Prevnar"],
    ["CRITICAL_CARE", "vasopressin", "Vasostrict"],
    ["CRITICAL_CARE", "dobutamine", "Dobutrex"],
    ["CRITICAL_CARE", "dopamine", "Intropin"],
    ["PAIN", "tramadol", "Ultram"],
    ["PAIN", "ketorolac", "Toradol"],
    ["ANTICOAGULATION", "fondaparinux", "Arixtra"],
    ["PULMONARY", "montelukast", "Singulair"],
    ["INFECTIOUS_DISEASE", "linezolid", "Zyvox"],
    ["INFECTIOUS_DISEASE", "daptomycin", "Cubicin"],
    ["CARDIOLOGY", "isosorbide", "Imdur"],
    ["ENDOCRINE", "pioglitazone", "Actos"],
    ["ER", "tranexamic acid", "Cyklokapron"],
    ["ER", "octreotide", "Sandostatin"],
    ["PRIMARY_CARE", "rosuvastatin", "Crestor"],
    ["PRIMARY_CARE", "simvastatin", "Zocor"],
    ["PRIMARY_CARE", "pravastatin", "Pravachol"],
    ["GI", "famotidine", "Pepcid"],
    ["GI", "ranitidine", "Zantac"],
    ["PSYCHIATRY", "clonazepam", "Klonopin"],
    ["PSYCHIATRY", "diazepam", "Valium"],
    ["NEUROLOGY", "phenytoin", "Dilantin"],
    ["NEPHROLOGY", "erythropoietin", "Epogen"],
    ["DERMATOLOGY", "clotrimazole", "Lotrimin"],
    ["OPHTHALMOLOGY", "ofloxacin ophthalmic", "Ocuflox"],
    ["ENT", "pseudoephedrine", "Sudafed"],
    ["PEDIATRICS", "ibuprofen", "Motrin"],
    ["OBGYN", "oxytocin", "Pitocin"],
    ["UROLOGY", "sildenafil", "Viagra"],
    ["CRITICAL_CARE", "nitroglycerin", "Nitroglycerin"],
    ["CRITICAL_CARE", "nicardipine", "Cardene"],
    ["PAIN", "acetaminophen", "Tylenol"],
    ["ANTICOAGULATION", "argatroban", "Argatroban"],
    ["VACCINES", "covid-19 vaccine", "Comirnaty"],
    ["PULMONARY", "tiotropium", "Spiriva"],
    ["INFECTIOUS_DISEASE", "acyclovir", "Zovirax"],
    ["INFECTIOUS_DISEASE", "oseltamivir", "Tamiflu"],
    ["CARDIOLOGY", "dobutamine", "Dobutrex"],
    ["ENDOCRINE", "canagliflozin", "Invokana"],
    ["ENDOCRINE", "dapagliflozin", "Farxiga"],
    ["ER", "calcium chloride", "Calcium chloride"],
    ["FLUIDS", "plasma-lyte", "Plasma-Lyte"],
    ["PRIMARY_CARE", "chlorthalidone", "Thalitone"],
    ["PRIMARY_CARE", "spironolactone", "Aldactone"],
    ["GI", "bisacodyl", "Dulcolax"],
    ["PSYCHIATRY", "lithium", "Lithobid"],
    ["NEUROLOGY", "baclofen", "Lioresal"],
    ["RHEUMATOLOGY", "hydroxychloroquine", "Plaquenil"],
    ["DERMATOLOGY", "mupirocin", "Bactroban"],
    ["CRITICAL_CARE", "cisatracurium", "Nimbex"],
    ["PAIN", "gabapentin", "Neurontin"],
    ["INFECTIOUS_DISEASE", "clindamycin", "Cleocin"],
    ["INFECTIOUS_DISEASE", "gentamicin", "Garamycin"],
    ["CARDIOLOGY", "hydralazine", "Apresoline"],
    ["ENDOCRINE", "insulin regular", "Humulin R"],
    ["ER", "hydroxocobalamin", "Cyanokit"],
    ["PRIMARY_CARE", "duloxetine", "Cymbalta"],
    ["PRIMARY_CARE", "venlafaxine", "Effexor"],
    ["GI", "pantoprazole", "Protonix"],
    ["PSYCHIATRY", "risperidone", "Risperdal"],
    ["NEUROLOGY", "donepezil", "Aricept"],
    ["NEPHROLOGY", "furosemide", "Lasix"],
    ["OBGYN", "magnesium sulfate", "Magnesium sulfate"],
    ["CRITICAL_CARE", "phenylephrine", "Neo-Synephrine"],
    ["PAIN", "fentanyl", "Duragesic"],
    ["ANTICOAGULATION", "bivalirudin", "Angiomax"],
    ["PULMONARY", "theophylline", "Theo-Dur"],
    ["INFECTIOUS_DISEASE", "ampicillin", "Principen"],
    ["INFECTIOUS_DISEASE", "cefazolin", "Ancef"],
    ["CARDIOLOGY", "atenolol", "Tenormin"],
    ["ENDOCRINE", "glyburide", "Diabeta"],
    ["ER", "protamine", "Protamine"],
    ["PRIMARY_CARE", "montelukast", "Singulair"],
    ["GI", "esomeprazole", "Nexium"],
    ["PSYCHIATRY", "citalopram", "Celexa"],
    ["NEUROLOGY", "lamotrigine", "Lamictal"],
    ["CRITICAL_CARE", "milrinone", "Primacor"],
    ["PAIN", "methadone", "Dolophine"],
    ["INFECTIOUS_DISEASE", "trimethoprim sulfamethoxazole", "Bactrim"],
    ["CARDIOLOGY", "nifedipine", "Procardia"],
    ["ENDOCRINE", "repaglinide", "Prandin"],
    ["PRIMARY_CARE", "tamsulosin", "Flomax"],
    ["GI", "senna", "Senokot"],
    ["PSYCHIATRY", "ziprasidone", "Geodon"],
    ["NEUROLOGY", "ropinirole", "Requip"],
    ["CRITICAL_CARE", "esmolol", "Brevibloc"],
    ["INFECTIOUS_DISEASE", "piperacillin tazobactam", "Zosyn"],
    ["CARDIOLOGY", "verapamil", "Calan"],
    ["ENDOCRINE", "exenatide", "Byetta"],
    ["PRIMARY_CARE", "gabapentin", "Neurontin"],
    ["GI", "mesalamine", "Asacol"],
    ["PSYCHIATRY", "lamotrigine", "Lamictal"],
    ["CRITICAL_CARE", "labetalol", "Trandate"],
    ["INFECTIOUS_DISEASE", "ceftriaxone", "Rocephin"],
    ["CARDIOLOGY", "enalapril", "Vasotec"],
    ["ENDOCRINE", "linagliptin", "Tradjenta"],
    ["PRIMARY_CARE", "allopurinol", "Zyloprim"],
    ["PAIN", "codeine", "Codeine"],
    ["INFECTIOUS_DISEASE", "nitrofurantoin", "Macrobid"],
    ["CARDIOLOGY", "ramipril", "Altace"],
    ["ENDOCRINE", "insulin detemir", "Levemir"],
    ["PRIMARY_CARE", "meloxicam", "Mobic"],
    ["GI", "ursodiol", "Actigall"],
    ["PSYCHIATRY", "buspirone", "Buspar"],
    ["CRITICAL_CARE", "clevidipine", "Cleviprex"],
    ["INFECTIOUS_DISEASE", "rifampin", "Rifadin"],
    ["CARDIOLOGY", "eplerenone", "Inspra"],
    ["ENDOCRINE", "pramlintide", "Symlin"],
    ["PRIMARY_CARE", "celecoxib", "Celebrex"],
    ["PAIN", "buprenorphine", "Subutex"],
    ["INFECTIOUS_DISEASE", "isoniazid", "Nydrazid"],
    ["CARDIOLOGY", "ticagrelor", "Brilinta"],
    ["ENDOCRINE", "insulin glulisine", "Apidra"],
    ["PRIMARY_CARE", "diclofenac", "Voltaren"],
    ["GI", "lactulose", "Enulose"],
    ["PSYCHIATRY", "paroxetine", "Paxil"],
    ["CRITICAL_CARE", "dexmedetomidine", "Precedex"],
    ["INFECTIOUS_DISEASE", "ethambutol", "Myambutol"],
    ["CARDIOLOGY", "prasugrel", "Effient"],
    ["PRIMARY_CARE", "indomethacin", "Indocin"],
    ["PAIN", "naltrexone", "ReVia"],
    ["INFECTIOUS_DISEASE", "pyrazinamide", "Pyrazinamide"],
    ["CARDIOLOGY", "ivabradine", "Corlanor"],
    ["PRIMARY_CARE", "colchicine", "Colcrys"],
    ["GI", "rifaximin", "Xifaxan"],
    ["PSYCHIATRY", "duloxetine", "Cymbalta"],
    ["CRITICAL_CARE", "ketamine", "Ketalar"],
    ["INFECTIOUS_DISEASE", "amphotericin", "Ambisome"],
    ["CARDIOLOGY", "ranolazine", "Ranexa"],
    ["PRIMARY_CARE", "methocarbamol", "Robaxin"],
    ["PAIN", "tapentadol", "Nucynta"],
    ["INFECTIOUS_DISEASE", "voriconazole", "Vfend"],
    ["CARDIOLOGY", "sacubitril valsartan", "Entresto"],
    ["PRIMARY_CARE", "cyclobenzaprine", "Flexeril"],
    ["GI", "cholestyramine", "Questran"],
    ["PSYCHIATRY", "venlafaxine", "Effexor"],
    ["CRITICAL_CARE", "mannitol", "Osmitrol"],
    ["INFECTIOUS_DISEASE", "caspofungin", "Cancidas"],
    ["PRIMARY_CARE", "baclofen", "Lioresal"],
    ["PAIN", "carisoprodol", "Soma"],
    ["CARDIOLOGY", "bumetanide", "Bumex"],
    ["ENDOCRINE", "empagliflozin", "Jardiance"],
    ["HIV", "bictegravir emtricitabine tenofovir alafenamide", "Biktarvy"],
  ];

  return pairs.map(([specialty, generic, brand]) => ({
    id: `${generic.replace(/\s+/g, "-").toLowerCase()}-${brand.toLowerCase()}`,
    specialty,
    brandQueries: brand ? [brand] : [],
    genericQueries: [generic],
  }));
}

export const MEDICATION_PROVIDER_CLINICAL_CORPUS: readonly ProviderClinicalCorpusFamily[] = [
  ...HIV,
  ...ENDOCRINE,
  ...CARDIO,
  ...ID_EM,
  ...COMMON,
  ...buildExtendedCorpus(),
];

export function listProviderClinicalCorpusQueries(): string[] {
  const out = new Set<string>();
  for (const family of MEDICATION_PROVIDER_CLINICAL_CORPUS) {
    for (const q of family.brandQueries) out.add(q);
    for (const q of family.genericQueries) out.add(q);
  }
  return [...out];
}

export function listHardAcceptanceFamilies(): ProviderClinicalCorpusFamily[] {
  return MEDICATION_PROVIDER_CLINICAL_CORPUS.filter((f) => f.hardAcceptance);
}
