/**
 * Plain-language clinical synonyms for ICD-10-CM catalog search.
 * Does not invent codes — only expands queries to official description phrases.
 */

export type Icd10QueryExpansion = {
  /** Normalized lowercase query key (trimmed). */
  query: string;
  /** Additional description phrases OR'd into search (any match). */
  anyOf?: string[];
  /** Phrases that must all appear in short/long/searchText (AND). */
  allOf?: string[];
};

/** Exact-phrase expansions for common ED tendon/ligament searches. */
export const ICD10_CLINICAL_QUERY_EXPANSIONS: Icd10QueryExpansion[] = [
  // Spine/back emergency (Phase 9): official-description query expansion only.
  // Prefer exact official short-description phrases. Avoid broad tokens like "cervical"
  // or "fracture of" alone — they pull abbreviated S-code rows (e.g. "cervcal", "fx")
  // and extremity fractures ahead of the intended spine diagnoses.
  { query: "neck pain", anyOf: ["Cervicalgia", "cervicalgia"] },
  { query: "douleur cervicale", anyOf: ["Cervicalgia", "cervicalgia"] },
  { query: "cervical strain", anyOf: ["strain of muscle", "fascia and tendon at neck level"] },
  { query: "entorse cervicale", anyOf: ["strain of muscle", "fascia and tendon at neck level"] },
  { query: "thoracic strain", anyOf: ["sprain of ligaments of thoracic spine", "pain in thoracic spine"] },
  { query: "douleur thoracique rachidienne", anyOf: ["pain in thoracic spine"] },
  { query: "lumbar strain", anyOf: ["strain of muscle", "fascia and tendon of lower back"] },
  { query: "entorse lombaire", anyOf: ["strain of muscle", "fascia and tendon of lower back"] },
  { query: "low back pain", anyOf: ["low back pain", "lumbago"] },
  { query: "lombalgie", anyOf: ["low back pain", "lumbago"] },
  { query: "herniated disc", anyOf: ["disc disorder", "displacement", "intervertebral disc"] },
  { query: "hernie discale", anyOf: ["disc disorder", "displacement", "intervertebral disc"] },
  { query: "cervical disc herniation", anyOf: ["cervical disc", "Other cervical disc displacement", "disc disorders w radiculopathy, cervical"] },
  // Avoid bare "lumbar" — it steals vertebral fracture S32 rows ahead of M51 disc codes.
  { query: "lumbar disc herniation", anyOf: ["Other intervertebral disc displacement, lumbar region", "intervertebral disc displacement, lumbar", "disc disorders w radiculopathy, lumbar region"] },
  { query: "sciatica", anyOf: ["sciatica", "lumbago with sciatica"] },
  { query: "sciatique", anyOf: ["sciatica", "lumbago with sciatica"] },
  { query: "radiculopathy", anyOf: ["radiculopathy"] },
  { query: "radiculopathie", anyOf: ["radiculopathy"] },
  { query: "cervical radiculopathy", anyOf: ["radiculopathy, cervical"] },
  { query: "radiculopathie cervicale", anyOf: ["radiculopathy, cervical"] },
  { query: "thoracic radiculopathy", anyOf: ["radiculopathy, thoracic"] },
  { query: "lumbar radiculopathy", anyOf: ["radiculopathy, lumbar"] },
  { query: "radiculopathie lombaire", anyOf: ["radiculopathy, lumbar"] },
  { query: "spinal stenosis", anyOf: ["spinal stenosis"] },
  { query: "sténose rachidienne", anyOf: ["spinal stenosis"] },
  { query: "cervical myelopathy", anyOf: ["myelopathy"] },
  { query: "myélopathie cervicale", anyOf: ["myelopathy"] },
  { query: "thoracic myelopathy", anyOf: ["myelopathy"] },
  { query: "cauda equina", anyOf: ["cauda equina syndrome"] },
  { query: "cauda equina syndrome", anyOf: ["cauda equina syndrome"] },
  { query: "queue de cheval", anyOf: ["cauda equina syndrome"] },
  { query: "syndrome de la queue de cheval", anyOf: ["cauda equina syndrome"] },
  { query: "conus medullaris syndrome", anyOf: ["conus medullaris"] },
  { query: "syndrome du cône médullaire", anyOf: ["conus medullaris"] },
  { query: "spinal epidural abscess", anyOf: ["intraspinal abscess and granuloma", "extradural and subdural abscess"] },
  { query: "epidural abscess", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "abcès épidural", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "abcès épidural rachidien", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "vertebral osteomyelitis", anyOf: ["osteomyelitis of vertebra", "osteomyelitis"] },
  { query: "ostéomyélite vertébrale", anyOf: ["osteomyelitis of vertebra", "osteomyelitis"] },
  { query: "discitis", anyOf: ["discitis"] },
  { query: "discite", anyOf: ["discitis"] },
  { query: "spinal cord compression", anyOf: ["cord compression", "myelopathy"] },
  { query: "compression médullaire", anyOf: ["cord compression", "myelopathy"] },
  { query: "metastatic spinal cord compression", anyOf: ["cord compression", "secondary malignant"] },
  { query: "compression médullaire métastatique", anyOf: ["cord compression", "secondary malignant"] },
  { query: "vertebral compression fracture", anyOf: ["wedge compression fracture", "compression fracture"] },
  { query: "fracture vertébrale par compression", anyOf: ["wedge compression fracture", "compression fracture"] },
  // Prefer long-form "burst fracture" shortDescriptions (not abbreviated "burst fx").
  { query: "burst fracture", anyOf: ["burst fracture"] },
  { query: "fracture éclatement", anyOf: ["burst fracture"] },
  // Official text uses "cervical vertebra" / abbreviated "cervcal" / "lum vertebra" / "thor vertebra".
  { query: "cervical spine fracture", anyOf: ["cervical vertebra", "cervcal vertebra"] },
  { query: "fracture cervicale", anyOf: ["cervical vertebra", "cervcal vertebra"] },
  { query: "thoracic spine fracture", anyOf: ["thoracic vertebra", "thor vertebra"] },
  { query: "fracture thoracique", anyOf: ["thoracic vertebra", "thor vertebra"] },
  { query: "lumbar spine fracture", anyOf: ["lumbar vertebra", "lum vertebra"] },
  { query: "fracture lombaire", anyOf: ["lumbar vertebra", "lum vertebra"] },
  // Official short text includes "… spinal cord" (e.g. "Unsp injury at unsp level of cervical spinal cord").
  // Prefer phrases that appear in shortDescription so search certification sees "spinal cord".
  { query: "spinal cord injury", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord", "edema of thoracic spinal cord"] },
  { query: "lésion médullaire", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord", "edema of thoracic spinal cord"] },
  { query: "central cord syndrome", anyOf: ["central cord syndrome"] },
  { query: "syndrome centromédullaire", anyOf: ["central cord syndrome"] },
  { query: "anterior cord syndrome", anyOf: ["anterior cord syndrome"] },
  { query: "syndrome médullaire antérieur", anyOf: ["anterior cord syndrome"] },
  { query: "posterior cord syndrome", anyOf: ["posterior cord syndrome"] },
  { query: "Brown-Sequard syndrome", anyOf: ["brown-sequard syndrome"] },
  { query: "syndrome de Brown-Séquard", anyOf: ["brown-sequard syndrome"] },
  // No dedicated "neurogenic/spinal shock" ICD phrase — map to official shock + cord injury text.
  { query: "neurogenic shock", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "choc neurogène", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "spinal shock", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "choc spinal", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  // SCIWORA is a clinical descriptor; search surfaces official cord-injury codes only.
  { query: "SCIWORA", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord"] },
  // Human bite / high-risk contaminated wound (Phase 8). These map only to official description text.
  { query: "human bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "morsure humaine", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "fight bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "clenched fist", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "knuckle bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "morsure du poing", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "contaminated wound", anyOf: ["open wound", "puncture wound"] },
  { query: "bat bite", anyOf: ["bitten by bat", "bat"] },
  { query: "farm wound", anyOf: ["open wound", "puncture wound"] },
  { query: "flexor tenosynovitis", anyOf: ["Other infective (teno)synovitis", "infective (teno)synovitis"] },
  { query: "bite cellulitis", anyOf: ["cellulitis"] },
  { query: "deep-space hand infection", anyOf: ["Cellulitis of right hand", "Cellulitis of left hand", "Cutaneous abscess of right hand", "Cutaneous abscess of left hand"] },
  { query: "plaie contaminée", anyOf: ["open wound", "puncture wound"] },
  { query: "dirty wound", anyOf: ["open wound", "puncture wound"] },
  { query: "plaie sale", anyOf: ["open wound", "puncture wound"] },
  { query: "achilles tendon rupture", anyOf: ["achilles tendon", "injury of achilles"] },
  { query: "achilles laceration", anyOf: ["laceration of achilles", "achilles tendon"] },
  { query: "rotator cuff tear", anyOf: ["rotator cuff", "rotatr-cuff", "rotatr cuff"] },
  { query: "biceps tendon rupture", anyOf: ["biceps tendon", "long head of biceps"] },
  { query: "triceps tendon rupture", anyOf: ["triceps", "musc/fasc/tend triceps"] },
  { query: "quadriceps tendon rupture", anyOf: ["quadriceps musc/fasc/tend", "quadriceps"] },
  // Official FY2026 text uses quadriceps musc/fasc/tend for traumatic patellar-tendon-region injuries.
  { query: "patellar tendon rupture", anyOf: ["quadriceps musc/fasc/tend", "patellar tendinitis"] },
  { query: "hamstring tendon injury", anyOf: ["post grp at thi lev", "msl/fasc/tnd post grp"] },
  { query: "flexor tendon laceration", anyOf: ["laceration of flexor"] },
  { query: "extensor tendon laceration", anyOf: ["laceration of extensor"] },
  { query: "mallet finger", anyOf: ["mallet finger"] },
  { query: "acl tear", anyOf: ["anterior cruciate ligament"] },
  { query: "acl", anyOf: ["anterior cruciate ligament"] },
  { query: "pcl tear", anyOf: ["posterior cruciate ligament"] },
  { query: "pcl", anyOf: ["posterior cruciate ligament"] },
  { query: "mcl tear", anyOf: ["medial collateral ligament"] },
  { query: "mcl", anyOf: ["medial collateral ligament"] },
  { query: "lcl tear", anyOf: ["lateral collateral ligament"] },
  { query: "lcl", anyOf: ["lateral collateral ligament"] },
  { query: "high ankle sprain", anyOf: ["tibiofibular ligament"] },
  { query: "syndesmotic ligament injury", anyOf: ["tibiofibular ligament"] },
  { query: "syndesmosis", anyOf: ["tibiofibular ligament"] },
  { query: "thumb ucl tear", allOf: ["metacarpophalangeal joint of", "thumb"] },
  { query: "thumb ucl", allOf: ["metacarpophalangeal joint of", "thumb"] },
  { query: "skier's thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "skiers thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "gamekeeper's thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "gamekeepers thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  // Official FY2026 order file does not name “scapholunate”; map to wrist ligament / carpal sprain families.
  {
    query: "scapholunate ligament injury",
    anyOf: ["sprain of carpal joint", "traumatic rupture of unsp ligament of right wrist", "traumatic rupture of unsp ligament of left wrist"],
  },
  { query: "elbow ucl injury", allOf: ["ulnar collateral ligament", "elbow"] },
  { query: "elbow ucl", allOf: ["ulnar collateral ligament", "elbow"] },
  { query: "crush injury", anyOf: ["crushing injury", "crushed"] },
  { query: "crushing injury", anyOf: ["crushing injury", "crushed"] },
  { query: "crushed hand", allOf: ["crushing injury", "hand"] },
  { query: "crushed finger", allOf: ["crushing injury", "finger"] },
  { query: "crushed foot", allOf: ["crushing injury", "foot"] },
  { query: "industrial crush injury", anyOf: ["crushing injury", "crushed"] },
  { query: "prolonged compression", anyOf: ["traumatic ischemia of muscle"] },
  { query: "degloving injury", anyOf: ["crushing injury"] },
  { query: "compartment syndrome after crush", anyOf: ["traumatic ischemia of muscle"] },
  { query: "rhabdomyolysis after crush", anyOf: ["traumatic ischemia of muscle"] },
  { query: "traumatic amputation", anyOf: ["traumatic amputation"] },
  { query: "partial amputation", anyOf: ["partial traumatic amputation"] },
  { query: "complete amputation", anyOf: ["complete traumatic amputation"] },
  // Prefer amputation-specific phrases (avoid bare “fngr”, which also hits fracture shorts).
  { query: "severed finger", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "severed toe",
    anyOf: [
      "traumatic amputation of right great toe",
      "traumatic amputation of left great toe",
      "traumatic amp of right great toe",
      "traumatic amp of left great toe",
    ],
  },
  { query: "finger cut off", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "thumb cut off",
    anyOf: [
      "MCP amputation of thmb",
      "MCP amputation of right thumb",
      "MCP amputation of left thumb",
      "traumatic amputation of right thumb",
      "traumatic amputation of left thumb",
      "traumatic amp of right thumb",
      "traumatic amp of left thumb",
    ],
  },
  {
    query: "toe cut off",
    anyOf: [
      "traumatic amputation of right great toe",
      "traumatic amputation of left great toe",
      "traumatic amp of right great toe",
      "traumatic amp of left great toe",
    ],
  },
  { query: "avulsed digit", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "hand amputation",
    anyOf: [
      "traumatic amp of left hand at wrist",
      "traumatic amp of right hand at wrist",
      "traumatic amputation of left hand",
      "traumatic amputation of right hand",
      "hand at wrist level",
    ],
  },
  {
    query: "foot amputation",
    anyOf: [
      "traumatic amp of right foot",
      "traumatic amp of left foot",
      "traumatic amputation of right foot",
      "traumatic amputation of left foot",
      "foot at ankle level",
    ],
  },
  { query: "foreign body", anyOf: ["foreign body"] },
  { query: "retained foreign body", anyOf: ["with foreign body", "w fb", "w foreign body"] },
  { query: "foreign body eye", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "foreign body ear", anyOf: ["foreign body in right ear", "foreign body in left ear", "foreign body in ear"] },
  { query: "foreign body nose", anyOf: ["foreign body in nasal", "foreign body in nostril"] },
  {
    query: "foreign body hand",
    anyOf: [
      "foreign body of right hand",
      "foreign body of left hand",
      "foreign body of unsp hand",
      "superficial foreign body of right hand",
      "superficial foreign body of left hand",
      "with foreign body of right hand",
      "with foreign body of left hand",
    ],
  },
  {
    query: "foreign body foot",
    anyOf: [
      "foreign body, right foot",
      "foreign body, left foot",
      "foreign body, unspecified foot",
      "superficial foreign body, right foot",
      "superficial foreign body, left foot",
      "with foreign body of right foot",
      "with foreign body of left foot",
    ],
  },
  { query: "glass in skin", anyOf: ["superficial foreign body", "with foreign body"] },
  { query: "metal fragment", anyOf: ["with foreign body", "superficial foreign body"] },
  { query: "needle fragment", anyOf: ["with foreign body", "superficial foreign body"] },
  {
    query: "splinter in foot",
    anyOf: [
      "superficial foreign body, right foot",
      "superficial foreign body, left foot",
      "with foreign body of right foot",
      "with foreign body of left foot",
    ],
  },
  { query: "splinter", anyOf: ["superficial foreign body", "puncture wound with foreign body"] },
  { query: "fishhook", anyOf: ["puncture wound with foreign body"] },
  { query: "swallowed foreign body", anyOf: ["foreign body in esophagus", "foreign body in stomach"] },
  { query: "aspirated foreign body", anyOf: ["foreign body in pharynx", "foreign body in larynx", "foreign body in bronchus"] },
  // Burn / corrosion / inhalation / frostbite / electrical (Phase 5)
  { query: "burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "thermal burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "first-degree burn", anyOf: ["Burn of first degree", "Sunburn of first degree"] },
  { query: "first degree burn", anyOf: ["Burn of first degree", "Sunburn of first degree"] },
  { query: "second-degree burn", anyOf: ["Burn of second degree"] },
  { query: "second degree burn", anyOf: ["Burn of second degree"] },
  { query: "third-degree burn", anyOf: ["Burn of third degree"] },
  { query: "third degree burn", anyOf: ["Burn of third degree"] },
  { query: "superficial burn", anyOf: ["Burn of first degree", "Superficial frostbite"] },
  { query: "partial-thickness burn", anyOf: ["Burn of second degree"] },
  { query: "partial thickness burn", anyOf: ["Burn of second degree"] },
  { query: "full-thickness burn", anyOf: ["Burn of third degree"] },
  { query: "full thickness burn", anyOf: ["Burn of third degree"] },
  { query: "facial burn", anyOf: ["Burn of first degree of head, face, and neck", "Burn of second degree of head, face, and neck", "Burn of third degree of head, face, and neck", "head, face, and neck"] },
  { query: "hand burn", allOf: ["Burn of", "hand"] },
  { query: "foot burn", allOf: ["Burn of", "foot"] },
  { query: "genital burn", anyOf: ["genital region"] },
  { query: "circumferential burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "chemical burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "acid burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "alkali burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "electrical burn", anyOf: ["Electrocution", "Effects of lightning"] },
  { query: "lightning injury", anyOf: ["Effects of lightning", "lightning"] },
  { query: "smoke inhalation", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract", "respiratory tract"] },
  { query: "inhalation injury", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract"] },
  { query: "airway burn", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract"] },
  { query: "frostbite", anyOf: ["Frostbite", "Superficial frostbite"] },
  { query: "cold injury", anyOf: ["Frostbite", "Superficial frostbite"] },
  { query: "sunburn", anyOf: ["Sunburn"] },
  { query: "scald", anyOf: ["Burn of", "Burn of second degree"] },
  { query: "grease burn", anyOf: ["Burn of", "Burn of second degree"] },
  { query: "steam burn", anyOf: ["Burn of", "Burn of respiratory tract"] },
  // Penetrating trauma (Phase 6): descriptions use "open wound" and often omit mechanism terms.
  { query: "penetrating wound", anyOf: ["open wound", "puncture wound", "penetrating wound"] },
  { query: "penetrating trauma", anyOf: ["open wound", "puncture wound", "penetrating wound"] },
  { query: "gunshot wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "gunshot", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "firearm injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "firearm", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "bullet wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "bullet", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "shotgun injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "pellet wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "BB gun injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "stab wound", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "stab", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "knife wound", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "knife", anyOf: ["stab wound", "open wound", "puncture wound"] },
  // Official FY2026 short descriptions often abbreviate puncture/open-wound phrases (Pnctr, abd, etc.).
  { query: "puncture wound", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "impalement", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "through-and-through wound", anyOf: ["Pnctr", "penet", "open wound"] },
  { query: "retained projectile", anyOf: ["foreign body", "with foreign body", "w fb", "w/o fb"] },
  { query: "retained bullet", anyOf: ["foreign body", "with foreign body", "w fb"] },
  { query: "penetrating chest wound", anyOf: ["wl of thorax", "thorax w penet", "Pnctr w/o fb of r frnt wl of thorax", "opn wnd of thorax"] },
  { query: "penetrating abdominal wound", anyOf: ["abd wall", "penet perit cav", "opn wnd abd"] },
  { query: "penetrating neck wound", anyOf: ["unsp part of neck", "pharynx and cervical esophagus", "Pnctr w/o foreign body of unsp part of neck"] },
  { query: "penetrating head wound", anyOf: ["open wound of scalp", "laceration without foreign body of scalp", "Pnctr of scalp"] },
  { query: "penetrating hand wound", anyOf: ["Puncture wound with foreign body of right hand", "Puncture wound of right hand", "Pnctr of right hand", "opn wnd of right hand", "open wound of right hand"] },
  { query: "penetrating eye injury", anyOf: ["Penetrating wound w foreign body of", "Penetrating wound of eyeball", "eyeball"] },
  { query: "blessure par balle", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "plaie par balle", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "blessure par arme à feu", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "projectile retenu", anyOf: ["foreign body", "with foreign body", "w fb"] },
  { query: "plaie par arme blanche", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "coup de couteau", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "traumatisme pénétrant", anyOf: ["Pnctr", "open wound", "penet"] },
  { query: "plaie pénétrante", anyOf: ["Pnctr", "open wound", "penet"] },
  { query: "empalement", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "blessure thoracique pénétrante", anyOf: ["wl of thorax", "thorax w penet", "opn wnd of thorax"] },
  { query: "blessure abdominale pénétrante", anyOf: ["abd wall", "penet perit cav", "opn wnd abd"] },
  { query: "blessure cervicale pénétrante", anyOf: ["unsp part of neck", "pharynx and cervical esophagus", "Pnctr w/o foreign body of unsp part of neck"] },
  { query: "blessure oculaire pénétrante", anyOf: ["Penetrating wound w foreign body of", "Penetrating wound of eyeball", "eyeball"] },
  // Blast injury / polytrauma (Phase 7): expansion text remains anchored to official descriptions.
  { query: "unspecified multiple injuries", anyOf: ["Unspecified multiple injuries"] },
  { query: "traumatic shock", anyOf: ["Traumatic shock"] },
  { query: "traumatic rupture ear drum", anyOf: ["Traumatic rupture of unspecified ear drum", "Traumatic rupture of ear drum", "ear drum"] },
  { query: "otitic barotrauma", anyOf: ["Otitic barotrauma"] },
  { query: "explosion of blasting material", anyOf: ["Explosion of blasting material"] },
  { query: "discharge of firework", anyOf: ["Discharge of firework"] },
  { query: "asphyxiation due to cave-in", anyOf: ["Asphyxiation due to cave-in"] },
  { query: "blessures multiples non précisées", anyOf: ["Unspecified multiple injuries"] },
  { query: "choc traumatique", anyOf: ["Traumatic shock"] },
  { query: "barotraumatisme otitique", anyOf: ["Otitic barotrauma"] },
  { query: "explosion de matériau de dynamitage", anyOf: ["Explosion of blasting material"] },
  { query: "décharge de feu d'artifice", anyOf: ["Discharge of firework"] },
  // Head / facial trauma (Phase 10): official FY2026 text never uses "hematoma" for
  // traumatic intracranial/skull findings — it uses "hemorrhage". Prefer the traumatic
  // phrase explicitly so spontaneous (I62.*) codes are never surfaced ahead of S06.*.
  { query: "head injury", anyOf: ["intracranial injury", "unspecified injury of head"] },
  { query: "traumatisme crânien", anyOf: ["intracranial injury", "unspecified injury of head"] },
  { query: "concussion", anyOf: ["Concussion"] },
  { query: "commotion cérébrale", anyOf: ["Concussion"] },
  { query: "mild tbi", anyOf: ["Concussion"] },
  { query: "mild traumatic brain injury", anyOf: ["Concussion"] },
  { query: "tcc léger", anyOf: ["Concussion"] },
  { query: "traumatisme crânien léger", anyOf: ["Concussion"] },
  { query: "epidural hematoma", anyOf: ["Epidural hemorrhage"] },
  { query: "hématome épidural", anyOf: ["Epidural hemorrhage"] },
  { query: "subdural hematoma", anyOf: ["Traumatic subdural hemorrhage"] },
  { query: "hématome sous-dural", anyOf: ["Traumatic subdural hemorrhage"] },
  { query: "hématome sous-dural traumatique", anyOf: ["Traumatic subdural hemorrhage"] },
  // Prefer the abbreviated shortDescription phrase ("Traum subrac hem") for ranking — the
  // unabbreviated "Traumatic subarachnoid hemorrhage" only appears in longDescription, so
  // without it the unrelated but unabbreviated "Other nontraumatic subarachnoid hemorrhage"
  // (I60.8) wins the shortDescription rank boost and outranks the traumatic S06.6 codes.
  { query: "traumatic sah", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "traumatic subarachnoid hemorrhage", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "hémorragie sous-arachnoïdienne traumatique", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "skull fracture", anyOf: ["fracture of vault of skull", "fracture of base of skull"] },
  { query: "fracture du crâne", anyOf: ["fracture of vault of skull", "fracture of base of skull"] },
  { query: "basilar skull fracture", anyOf: ["fracture of base of skull"] },
  { query: "fracture de la base du crâne", anyOf: ["fracture of base of skull"] },
  { query: "nasal fracture", anyOf: ["fracture of nasal bones"] },
  { query: "fracture nasale", anyOf: ["fracture of nasal bones"] },
  { query: "orbital fracture", anyOf: ["fracture of orbital floor", "fracture of orbit"] },
  { query: "fracture orbitaire", anyOf: ["fracture of orbital floor", "fracture of orbit"] },
  // Official FY2026 text uses "malar" (not "zygomatic") for the malar/maxillary/zygoma family.
  { query: "zygomatic fracture", anyOf: ["Malar fracture"] },
  { query: "fracture zygomatique", anyOf: ["Malar fracture"] },
  { query: "maxillary fracture", anyOf: ["Malar fracture", "LeFort fracture"] },
  { query: "fracture maxillaire", anyOf: ["Malar fracture", "LeFort fracture"] },
  { query: "mandibular fracture", anyOf: ["fracture of mandible"] },
  { query: "fracture mandibulaire", anyOf: ["fracture of mandible"] },
  { query: "le fort fracture", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "lefort fracture", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "fracture de le fort", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "dental trauma", anyOf: ["Fracture of tooth", "Dislocation of tooth"] },
  { query: "traumatisme dentaire", anyOf: ["Fracture of tooth", "Dislocation of tooth"] },
  { query: "tooth avulsion", anyOf: ["Dislocation of tooth"] },
  { query: "avulsion dentaire", anyOf: ["Dislocation of tooth"] },
  { query: "jaw dislocation", anyOf: ["Dislocation of jaw"] },
  { query: "luxation de la mâchoire", anyOf: ["Dislocation of jaw"] },
  // No dedicated "hematoma" code for auricular/septal contusion — map to the official contusion
  // text. Ear contusion is lateralized ("Contusion of right/left/unspecified ear"), so list each.
  {
    query: "auricular hematoma",
    anyOf: ["Contusion of right ear", "Contusion of left ear", "Contusion of unspecified ear"],
  },
  {
    query: "hématome auriculaire",
    anyOf: ["Contusion of right ear", "Contusion of left ear", "Contusion of unspecified ear"],
  },
  { query: "septal hematoma", anyOf: ["Contusion of nose"] },
  { query: "hématome septal", anyOf: ["Contusion of nose"] },
  // No traumatic-specific CSF leak code — G96.08 is the only non-spontaneous cranial CSF leak code.
  { query: "csf leak after trauma", anyOf: ["Other cranial cerebrospinal fluid leak"] },
  { query: "fuite de lcr post-traumatique", anyOf: ["Other cranial cerebrospinal fluid leak"] },
  // Eye emergencies (Phase 11). Official FY2026 text is used verbatim wherever possible —
  // "corneal abrasion", "corneal ulcer", "photokeratitis", "hyphema", "acute angle-closure
  // glaucoma", "retinal detachment", "vitreous hemorrhage", and "central retinal artery
  // occlusion" already appear literally in official descriptions and need no expansion for
  // the English query, but French queries and a few English terms not used verbatim by CMS
  // (e.g. "corneal foreign body" -> "foreign body in cornea") require explicit expansion.
  { query: "corneal abrasion", anyOf: ["corneal abrasion"] },
  { query: "abrasion cornéenne", anyOf: ["corneal abrasion"] },
  { query: "corneal foreign body", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "corps étranger cornéen", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "corneal ulcer", anyOf: ["corneal ulcer"] },
  { query: "ulcère cornéen", anyOf: ["corneal ulcer"] },
  { query: "photokeratitis", anyOf: ["Photokeratitis"] },
  { query: "photokératite", anyOf: ["Photokeratitis"] },
  { query: "chemical eye injury", anyOf: ["Corrosion of cornea and conjunctival sac", "Corrosion of unspecified eyelid and periocular area"] },
  { query: "brûlure chimique de l'oeil", anyOf: ["Corrosion of cornea and conjunctival sac", "Corrosion of unspecified eyelid and periocular area"] },
  { query: "open globe", anyOf: ["Ocular laceration and rupture", "prolapse or loss of intraocular tissue"] },
  { query: "globe oculaire ouvert", anyOf: ["Ocular laceration and rupture", "prolapse or loss of intraocular tissue"] },
  { query: "hyphema", anyOf: ["Hyphema"] },
  { query: "hyphéma", anyOf: ["Hyphema"] },
  { query: "acute angle-closure glaucoma", anyOf: ["Acute angle-closure glaucoma"] },
  { query: "glaucome aigu", anyOf: ["Acute angle-closure glaucoma"] },
  { query: "retinal detachment", anyOf: ["retinal detachment"] },
  { query: "décollement de la rétine", anyOf: ["retinal detachment"] },
  { query: "vitreous hemorrhage", anyOf: ["Vitreous hemorrhage"] },
  { query: "hémorragie du vitré", anyOf: ["Vitreous hemorrhage"] },
  { query: "central retinal artery occlusion", anyOf: ["Central retinal artery occlusion"] },
  { query: "occlusion de l'artère rétinienne", anyOf: ["Central retinal artery occlusion"] },
  { query: "orbital cellulitis", anyOf: ["Cellulitis of right orbit", "Cellulitis of left orbit", "Cellulitis of unspecified orbit"] },
  { query: "cellulite orbitaire", anyOf: ["Cellulitis of right orbit", "Cellulitis of left orbit", "Cellulitis of unspecified orbit"] },
  { query: "preseptal cellulitis", anyOf: ["Periorbital cellulitis"] },
  { query: "cellulite préseptale", anyOf: ["Periorbital cellulitis"] },
  { query: "uveitis", anyOf: ["iridocyclitis"] },
  { query: "uvéite", anyOf: ["iridocyclitis"] },
  { query: "scleritis", anyOf: ["scleritis"] },
  { query: "sclérite", anyOf: ["scleritis"] },
  {
    query: "eyelid laceration",
    anyOf: [
      "Laceration without foreign body of right eyelid",
      "Laceration without foreign body of left eyelid",
      "Laceration without foreign body of unspecified eyelid",
      "Laceration with foreign body of right eyelid",
      "Laceration with foreign body of left eyelid",
      "Laceration with foreign body of unspecified eyelid",
    ],
  },
  {
    query: "lacération de la paupière",
    anyOf: [
      "Laceration without foreign body of right eyelid",
      "Laceration without foreign body of left eyelid",
      "Laceration without foreign body of unspecified eyelid",
      "Laceration with foreign body of right eyelid",
      "Laceration with foreign body of left eyelid",
      "Laceration with foreign body of unspecified eyelid",
    ],
  },
  { query: "endophthalmitis", anyOf: ["endophthalmitis"] },
  { query: "endophtalmie", anyOf: ["endophthalmitis"] },
  { query: "eye trauma", anyOf: ["Injury of eye and orbit", "eyeball"] },
  { query: "traumatisme oculaire", anyOf: ["Injury of eye and orbit", "eyeball"] },
  // ENT emergencies (Phase 12). Official FY2026 category text is used verbatim wherever possible.
  { query: "ear pain", anyOf: ["Otalgia"] },
  { query: "douleur de l'oreille", anyOf: ["Otalgia"] },
  { query: "otitis externa", anyOf: ["Otitis externa"] },
  { query: "otite externe", anyOf: ["Otitis externa"] },
  { query: "otitis media", anyOf: ["Otitis media"] },
  { query: "otite moyenne", anyOf: ["Otitis media"] },
  { query: "perforation tympanique", anyOf: ["Perforation of tympanic membrane"] },
  { query: "surdité neurosensorielle soudaine", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "meniere disease", anyOf: ["Meniere's disease"] },
  { query: "meniere's disease", anyOf: ["Meniere's disease"] },
  { query: "maladie de ménière", anyOf: ["Meniere's disease"] },
  { query: "bell palsy", anyOf: ["Bell's palsy"] },
  { query: "epistaxis", anyOf: ["Epistaxis"] },
  { query: "épistaxis", anyOf: ["Epistaxis"] },
  { query: "posterior nosebleed", anyOf: ["Epistaxis"] },
  { query: "saignement nasal postérieur", anyOf: ["Epistaxis"] },
  { query: "infection profonde du cou", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "abcès parapharyngé", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "deep neck infection", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "supraglottitis", anyOf: ["Acute epiglottitis"] },
  { query: "supraglottite", anyOf: ["Acute epiglottitis"] },
  { query: "airway foreign body", anyOf: ["foreign body in pharynx", "foreign body in larynx", "foreign body in trachea"] },
  { query: "corps étranger des voies aériennes", anyOf: ["foreign body in pharynx", "foreign body in larynx", "foreign body in trachea"] },
  { query: "corps étranger de la gorge", anyOf: ["foreign body in pharynx", "foreign body in esophagus"] },
  { query: "obstruction du canal salivaire", anyOf: ["Sialolithiasis"] },
  { query: "swimmer's ear", anyOf: ["Otitis externa", "infective otitis externa"] },
  { query: "oreille du baigneur", anyOf: ["Otitis externa", "infective otitis externa"] },
  { query: "malignant otitis externa", anyOf: ["Malignant otitis externa"] },
  { query: "necrotizing otitis externa", anyOf: ["Malignant otitis externa"] },
  { query: "otite externe maligne", anyOf: ["Malignant otitis externa"] },
  { query: "otite externe nécrosante", anyOf: ["Malignant otitis externa"] },
  { query: "mastoiditis", anyOf: ["Mastoiditis"] },
  { query: "mastoïdite", anyOf: ["Mastoiditis"] },
  { query: "tympanic membrane perforation", anyOf: ["Perforation of tympanic membrane"] },
  { query: "perforated eardrum", anyOf: ["Perforation of tympanic membrane"] },
  { query: "perforation du tympan", anyOf: ["Perforation of tympanic membrane"] },
  { query: "tympan perforé", anyOf: ["Perforation of tympanic membrane"] },
  { query: "sudden sensorineural hearing loss", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "ssnhl", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "sudden hearing loss", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "surdité brusque", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "surdité soudaine", anyOf: ["Sudden idiopathic hearing loss"] },
  { query: "vertigo", anyOf: ["Benign paroxysmal vertigo", "Meniere's disease", "Vestibular neuronitis", "vertigo"] },
  { query: "vertige", anyOf: ["Benign paroxysmal vertigo", "Meniere's disease", "Vestibular neuronitis", "vertigo"] },
  { query: "bppv", anyOf: ["Benign paroxysmal vertigo"] },
  { query: "benign paroxysmal positional vertigo", anyOf: ["Benign paroxysmal vertigo"] },
  { query: "vertige positionnel paroxystique bénin", anyOf: ["Benign paroxysmal vertigo"] },
  { query: "vppb", anyOf: ["Benign paroxysmal vertigo"] },
  { query: "vestibular neuritis", anyOf: ["Vestibular neuronitis"] },
  { query: "acute unilateral vestibulopathy", anyOf: ["Vestibular neuronitis"] },
  { query: "névrite vestibulaire", anyOf: ["Vestibular neuronitis"] },
  { query: "labyrinthitis", anyOf: ["Labyrinthitis"] },
  { query: "labyrinthite", anyOf: ["Labyrinthitis"] },
  { query: "bell's palsy", anyOf: ["Bell's palsy"] },
  { query: "facial nerve palsy", anyOf: ["Bell's palsy"] },
  { query: "facial droop", anyOf: ["Bell's palsy"] },
  { query: "paralysie de bell", anyOf: ["Bell's palsy"] },
  { query: "paralysie faciale", anyOf: ["Bell's palsy"] },
  { query: "ramsay hunt", anyOf: ["Postherpetic geniculate ganglionitis"] },
  { query: "ramsay hunt syndrome", anyOf: ["Postherpetic geniculate ganglionitis"] },
  { query: "herpes zoster oticus", anyOf: ["Postherpetic geniculate ganglionitis"] },
  { query: "syndrome de ramsay hunt", anyOf: ["Postherpetic geniculate ganglionitis"] },
  { query: "posterior epistaxis", anyOf: ["Epistaxis"] },
  { query: "épistaxis postérieure", anyOf: ["Epistaxis"] },
  { query: "nasal foreign body", anyOf: ["foreign body in nasal", "foreign body in nostril"] },
  { query: "corps étranger nasal", anyOf: ["foreign body in nasal", "foreign body in nostril"] },
  { query: "peritonsillar abscess", anyOf: ["Peritonsillar abscess"] },
  { query: "quinsy", anyOf: ["Peritonsillar abscess"] },
  { query: "abcès périamygdalien", anyOf: ["Peritonsillar abscess"] },
  { query: "phlegmon péritonsillaire", anyOf: ["Peritonsillar abscess"] },
  { query: "retropharyngeal abscess", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "parapharyngeal abscess", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "deep neck space infection", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "abcès rétropharyngé", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "infection profonde de l'espace du cou", anyOf: ["Retropharyngeal and parapharyngeal abscess"] },
  { query: "ludwig's angina", anyOf: ["Cellulitis and abscess of mouth", "Ludwig"] },
  { query: "ludwig angina", anyOf: ["Cellulitis and abscess of mouth", "Ludwig"] },
  { query: "angine de ludwig", anyOf: ["Cellulitis and abscess of mouth", "Ludwig"] },
  { query: "epiglottitis", anyOf: ["Acute epiglottitis"] },
  { query: "épiglottite", anyOf: ["Acute epiglottitis"] },
  { query: "sialadenitis", anyOf: ["Sialoadenitis"] },
  { query: "salivary gland infection", anyOf: ["Sialoadenitis"] },
  { query: "sialadénite", anyOf: ["Sialoadenitis"] },
  { query: "sialolithiasis", anyOf: ["Sialolithiasis"] },
  { query: "salivary duct obstruction", anyOf: ["Sialolithiasis"] },
  { query: "salivary stone", anyOf: ["Sialolithiasis"] },
  { query: "sialolithiase", anyOf: ["Sialolithiasis"] },
  { query: "calcul salivaire", anyOf: ["Sialolithiasis"] },
  { query: "throat foreign body", anyOf: ["foreign body in pharynx", "foreign body in esophagus"] },
  { query: "corps étranger dans la gorge", anyOf: ["foreign body in pharynx", "foreign body in esophagus"] },
  // Soft tissue / wound infection (Phase 13)
  { query: "cellulitis", anyOf: ["Cellulitis"] },
  { query: "cellulite", anyOf: ["Cellulitis"] },
  { query: "erysipelas", anyOf: ["Erysipelas"] },
  { query: "érysipèle", anyOf: ["Erysipelas"] },
  { query: "facial cellulitis", anyOf: ["Cellulitis of face"] },
  { query: "cellulite faciale", anyOf: ["Cellulitis of face"] },
  { query: "hand cellulitis", anyOf: ["Cellulitis of", "hand"] },
  { query: "cellulite de la main", anyOf: ["Cellulitis of", "hand"] },
  { query: "leg cellulitis", anyOf: ["Cellulitis of", "lower limb"] },
  { query: "cellulite de la jambe", anyOf: ["Cellulitis of", "lower limb"] },
  { query: "foot cellulitis", anyOf: ["Cellulitis of", "foot", "toe"] },
  { query: "cellulite du pied", anyOf: ["Cellulitis of", "foot", "toe"] },
  { query: "skin abscess", anyOf: ["Cutaneous abscess"] },
  { query: "cutaneous abscess", anyOf: ["Cutaneous abscess"] },
  { query: "abcès cutané", anyOf: ["Cutaneous abscess"] },
  { query: "furuncle", anyOf: ["Furuncle"] },
  { query: "furoncle", anyOf: ["Furuncle"] },
  { query: "carbuncle", anyOf: ["Carbuncle"] },
  { query: "anthrax cutané", anyOf: ["Carbuncle"] },
  { query: "felon", anyOf: ["Cellulitis of right finger", "Cellulitis of left finger", "Cellulitis of unspecified finger"] },
  { query: "panaris pulpaire", anyOf: ["Cellulitis of right finger", "Cellulitis of left finger", "Cellulitis of unspecified finger"] },
  { query: "paronychia", anyOf: ["Cellulitis of right finger", "Cellulitis of left finger", "Cellulitis of unspecified finger"] },
  { query: "paronychie", anyOf: ["Cellulitis of right finger", "Cellulitis of left finger", "Cellulitis of unspecified finger"] },
  { query: "pilonidal abscess", anyOf: ["Pilonidal cyst with abscess", "Pilonidal sinus with abscess"] },
  { query: "abcès pilonidal", anyOf: ["Pilonidal cyst with abscess", "Pilonidal sinus with abscess"] },
  { query: "hidradenitis abscess", anyOf: ["Hidradenitis suppurativa"] },
  { query: "abcès d'hidradénite", anyOf: ["Hidradenitis suppurativa"] },
  { query: "infected wound", anyOf: ["Infection following a procedure", "Cellulitis"] },
  { query: "plaie infectée", anyOf: ["Infection following a procedure", "Cellulitis"] },
  { query: "infected traumatic wound", anyOf: ["Cellulitis", "Cutaneous abscess"] },
  { query: "plaie traumatique infectée", anyOf: ["Cellulitis", "Cutaneous abscess"] },
  { query: "surgical site infection", anyOf: ["Infection following a procedure"] },
  { query: "infection du site opératoire", anyOf: ["Infection following a procedure"] },
  { query: "postoperative wound infection", anyOf: ["Infection following a procedure"] },
  { query: "infection postopératoire de plaie", anyOf: ["Infection following a procedure"] },
  { query: "wound dehiscence", anyOf: ["Disruption of wound", "Disruption of external operation"] },
  { query: "déhiscence de plaie", anyOf: ["Disruption of wound", "Disruption of external operation"] },
  { query: "necrotizing fasciitis", anyOf: ["Necrotizing fasciitis"] },
  { query: "fasciite nécrosante", anyOf: ["Necrotizing fasciitis"] },
  { query: "necrotizing soft tissue infection", anyOf: ["Necrotizing fasciitis"] },
  { query: "infection nécrosante des tissus mous", anyOf: ["Necrotizing fasciitis"] },
  { query: "gas gangrene", anyOf: ["Gas gangrene"] },
  { query: "gangrène gazeuse", anyOf: ["Gas gangrene"] },
  { query: "fournier gangrene", anyOf: ["Fournier gangrene"] },
  { query: "gangrène de fournier", anyOf: ["Fournier gangrene"] },
  { query: "pyomyositis", anyOf: ["Infective myositis"] },
  { query: "pyomyosite", anyOf: ["Infective myositis"] },
  { query: "infectious myositis", anyOf: ["Infective myositis"] },
  { query: "myosite infectieuse", anyOf: ["Infective myositis"] },
  { query: "ténosynovite infectieuse des fléchisseurs", anyOf: ["Other infective (teno)synovitis", "infective (teno)synovitis"] },
  { query: "deep space hand infection", anyOf: ["Cellulitis of right hand", "Cellulitis of left hand", "Cutaneous abscess of right hand", "Cutaneous abscess of left hand"] },
  { query: "infection profonde de la main", anyOf: ["Cellulitis of right hand", "Cellulitis of left hand", "Cutaneous abscess of right hand", "Cutaneous abscess of left hand"] },
  { query: "septic bursitis", anyOf: ["Infective bursitis"] },
  { query: "bursite septique", anyOf: ["Infective bursitis"] },
  { query: "diabetic foot infection", anyOf: ["Type 2 diabetes mellitus with foot ulcer"] },
  { query: "infection du pied diabétique", anyOf: ["Type 2 diabetes mellitus with foot ulcer"] },
  { query: "infected diabetic foot ulcer", anyOf: ["Type 2 diabetes mellitus with foot ulcer"] },
  { query: "ulcère diabétique infecté", anyOf: ["Type 2 diabetes mellitus with foot ulcer"] },
  { query: "infected pressure ulcer", anyOf: ["Pressure ulcer of"] },
  { query: "escarre infectée", anyOf: ["Pressure ulcer of"] },
  { query: "infected venous ulcer", anyOf: ["Non-pressure chronic ulcer"] },
  { query: "ulcère veineux infecté", anyOf: ["Non-pressure chronic ulcer"] },
  { query: "osteomyelitis from wound", anyOf: ["Osteomyelitis"] },
  { query: "ostéomyélite liée à une plaie", anyOf: ["Osteomyelitis"] },
  { query: "septic arthritis from wound", anyOf: ["Pyogenic arthritis", "Infective arthritis"] },
  { query: "arthrite septique liée à une plaie", anyOf: ["Pyogenic arthritis", "Infective arthritis"] },
  { query: "water exposed wound infection", anyOf: ["Cellulitis", "Cutaneous abscess"] },
  { query: "infection de plaie exposée à l'eau", anyOf: ["Cellulitis", "Cutaneous abscess"] },
  { query: "bite wound infection", anyOf: ["Cellulitis"] },
  { query: "infection après morsure", anyOf: ["Cellulitis"] },
  { query: "foreign body wound infection", anyOf: ["foreign body"] },
  { query: "infection associée à un corps étranger", anyOf: ["foreign body"] },
  // Dermatology (Phase 14). Official FY2026 text used verbatim wherever possible;
  // French queries and terms not used verbatim by CMS require explicit expansion.
  { query: "impetigo", anyOf: ["Impetigo"] },
  { query: "impétigo", anyOf: ["Impetigo"] },
  { query: "cold sore", anyOf: ["Herpesviral vesicular dermatitis", "Herpesviral [herpes simplex] infections"] },
  { query: "fever blister", anyOf: ["Herpesviral vesicular dermatitis"] },
  { query: "herpès labial", anyOf: ["Herpesviral vesicular dermatitis"] },
  { query: "cutaneous herpes simplex", anyOf: ["Herpesviral [herpes simplex] infections", "Herpesviral vesicular dermatitis"] },
  { query: "herpès cutané", anyOf: ["Herpesviral [herpes simplex] infections", "Herpesviral vesicular dermatitis"] },
  { query: "shingles", anyOf: ["Zoster [herpes zoster]", "Zoster without complications"] },
  { query: "zona", anyOf: ["Zoster [herpes zoster]", "Zoster without complications"] },
  // "Varicella [chickenpox]" is a non-selectable category header — expand to leaf phrases.
  { query: "chickenpox", anyOf: ["Varicella without complication", "Varicella pneumonia", "Varicella"] },
  { query: "varicelle", anyOf: ["Varicella without complication", "Varicella pneumonia", "Varicella"] },
  { query: "molluscum contagiosum", anyOf: ["Molluscum contagiosum"] },
  { query: "molluscum", anyOf: ["Molluscum contagiosum"] },
  { query: "viral warts", anyOf: ["Viral warts"] },
  { query: "verrues virales", anyOf: ["Viral warts"] },
  { query: "hand foot and mouth disease", anyOf: ["Enteroviral vesicular stomatitis with exanthem"] },
  { query: "syndrome pieds-mains-bouche", anyOf: ["Enteroviral vesicular stomatitis with exanthem"] },
  { query: "ringworm", anyOf: ["Dermatophytosis", "Tinea corporis"] },
  { query: "teigne", anyOf: ["Dermatophytosis", "Tinea corporis"] },
  { query: "athlete's foot", anyOf: ["Tinea pedis"] },
  { query: "athletes foot", anyOf: ["Tinea pedis"] },
  { query: "pied d'athlète", anyOf: ["Tinea pedis"] },
  { query: "jock itch", anyOf: ["Tinea cruris"] },
  { query: "mycose de l'aine", anyOf: ["Tinea cruris"] },
  { query: "cutaneous candidiasis", anyOf: ["Candidiasis of skin and nail"] },
  { query: "candidose cutanée", anyOf: ["Candidiasis of skin and nail"] },
  { query: "scabies", anyOf: ["Scabies"] },
  // "gale" alone collides with the "Galeazzi fracture" S52.3 eponym family on the shared
  // shortDescription-prefix ranking tier (dozens of Galeazzi variants outrank the single
  // Scabies row within the result page). "scabiose" is the unambiguous French clinical
  // synonym used for certification; "gale" is still resolvable (Scabies is returned, just
  // not top-ranked) pending a shared search-ranking improvement outside this phase's scope.
  { query: "gale", anyOf: ["Scabies"] },
  { query: "scabiose", anyOf: ["Scabies"] },
  { query: "head lice", anyOf: ["Pediculosis due to Pediculus humanus capitis"] },
  { query: "poux de tête", anyOf: ["Pediculosis due to Pediculus humanus capitis"] },
  { query: "atopic dermatitis", anyOf: ["Atopic dermatitis"] },
  { query: "eczema", anyOf: ["Atopic dermatitis"] },
  { query: "dermatite atopique", anyOf: ["Atopic dermatitis"] },
  { query: "eczéma", anyOf: ["Atopic dermatitis"] },
  { query: "seborrheic dermatitis", anyOf: ["Seborrheic dermatitis"] },
  { query: "dermatite séborrhéique", anyOf: ["Seborrheic dermatitis"] },
  { query: "allergic contact dermatitis", anyOf: ["Allergic contact dermatitis"] },
  { query: "dermite de contact allergique", anyOf: ["Allergic contact dermatitis"] },
  { query: "irritant contact dermatitis", anyOf: ["Irritant contact dermatitis"] },
  { query: "dermite de contact irritative", anyOf: ["Irritant contact dermatitis"] },
  { query: "intertrigo", anyOf: ["Erythema intertrigo"] },
  { query: "psoriasis", anyOf: ["Psoriasis"] },
  { query: "lichen planus", anyOf: ["Lichen planus"] },
  { query: "lichen plan", anyOf: ["Lichen planus"] },
  { query: "hives", anyOf: ["Urticaria"] },
  { query: "urticaria", anyOf: ["Urticaria"] },
  { query: "urticaire", anyOf: ["Urticaria"] },
  { query: "rosacea", anyOf: ["Rosacea"] },
  { query: "rosacée", anyOf: ["Rosacea"] },
  { query: "stevens-johnson syndrome", anyOf: ["Stevens-Johnson syndrome"] },
  { query: "syndrome de stevens-johnson", anyOf: ["Stevens-Johnson syndrome"] },
  { query: "toxic epidermal necrolysis", anyOf: ["Toxic epidermal necrolysis"] },
  { query: "nécrolyse épidermique toxique", anyOf: ["Toxic epidermal necrolysis"] },
  { query: "dress syndrome", anyOf: ["Drug rash with eosinophilia and systemic symptoms syndrome"] },
  { query: "syndrome dress", anyOf: ["Drug rash with eosinophilia and systemic symptoms syndrome"] },
  { query: "pemphigus", anyOf: ["Pemphigus"] },
  { query: "bullous pemphigoid", anyOf: ["Pemphigoid"] },
  { query: "pemphigoïde bulleuse", anyOf: ["Pemphigoid"] },
  { query: "melanoma", anyOf: ["Malignant melanoma of skin"] },
  { query: "mélanome", anyOf: ["Malignant melanoma of skin"] },
  { query: "basal cell carcinoma", anyOf: ["Basal cell carcinoma of skin"] },
  { query: "skin cancer", anyOf: ["malignant neoplasm of skin", "Malignant melanoma of skin"] },
  { query: "carcinome basocellulaire", anyOf: ["Basal cell carcinoma of skin"] },
  { query: "cancer de la peau", anyOf: ["malignant neoplasm of skin", "Malignant melanoma of skin"] },
  { query: "actinic keratosis", anyOf: ["Actinic keratosis"] },
  { query: "kératose actinique", anyOf: ["Actinic keratosis"] },
  { query: "seborrheic keratosis", anyOf: ["Seborrheic keratosis"] },
  { query: "kératose séborrhéique", anyOf: ["Seborrheic keratosis"] },
  { query: "pyoderma gangrenosum", anyOf: ["Pyoderma gangrenosum"] },
  { query: "erythema nodosum", anyOf: ["Erythema nodosum"] },
  { query: "érythème noueux", anyOf: ["Erythema nodosum"] },
  { query: "cutaneous lupus", anyOf: ["lupus erythematosus"] },
  { query: "lupus cutané", anyOf: ["lupus erythematosus"] },
  { query: "vasculitis limited to skin", anyOf: ["Vasculitis limited to skin", "Vasculitis limited to the skin"] },
  { query: "vascularite limitée à la peau", anyOf: ["Vasculitis limited to skin", "Vasculitis limited to the skin"] },
  { query: "ophthalmic zoster", anyOf: ["Zoster ocular disease"] },
  { query: "zona ophtalmique", anyOf: ["Zoster ocular disease"] },
  { query: "folliculitis", anyOf: ["Follicular disorder"] },
  { query: "folliculite", anyOf: ["Follicular disorder"] },
  { query: "erythema multiforme", anyOf: ["Erythema multiforme"] },
  { query: "érythème polymorphe", anyOf: ["Erythema multiforme"] },
  { query: "drug eruption", anyOf: ["skin eruption due to drugs", "Gen skin eruption due to drugs"] },
  { query: "drug rash", anyOf: ["skin eruption due to drugs", "Gen skin eruption due to drugs"] },
  { query: "éruption médicamenteuse", anyOf: ["skin eruption due to drugs", "Gen skin eruption due to drugs"] },
  { query: "pityriasis rosea", anyOf: ["Pityriasis rosea"] },
  { query: "pityriasis rosé", anyOf: ["Pityriasis rosea"] },
  { query: "tinea versicolor", anyOf: ["Pityriasis versicolor"] },
  { query: "pityriasis versicolor", anyOf: ["Pityriasis versicolor"] },
  { query: "body lice", anyOf: ["Pediculosis due to Pediculus humanus corporis"] },
  { query: "poux du corps", anyOf: ["Pediculosis due to Pediculus humanus corporis"] },
  { query: "pediculosis", anyOf: ["Pediculosis due to Pediculus humanus", "Pediculosis, unspecified"] },
  { query: "pédiculose", anyOf: ["Pediculosis due to Pediculus humanus", "Pediculosis, unspecified"] },
  { query: "pemphigus vulgaris", anyOf: ["Pemphigus vulgaris"] },
  { query: "pemphigus vulgaire", anyOf: ["Pemphigus vulgaris"] },
  { query: "bullous disorder", anyOf: ["Pemphigus", "Pemphigoid"] },
  { query: "maladie bulleuse auto-immune", anyOf: ["Pemphigus", "Pemphigoid"] },
  { query: "suspicious skin lesion", anyOf: ["Neoplasm of uncertain behavior of skin"] },
  { query: "suspicious pigmented lesion", anyOf: ["Neoplasm of uncertain behavior of skin"] },
  { query: "lésion cutanée suspecte", anyOf: ["Neoplasm of uncertain behavior of skin"] },
  { query: "chronic hidradenitis suppurativa", anyOf: ["Hidradenitis suppurativa"] },
  { query: "hidrosadénite suppurée chronique", anyOf: ["Hidradenitis suppurativa"] },
  // Environmental exposure (Phase 15). Official FY2026 text used verbatim wherever possible.
  // T33-T35 (frostbite), T75.0/T75.4 (lightning/electrocution), and T70.0/T70.1/T70.8/T70.9
  // (barotrauma) are deliberate cross-phase dual-lists (see icd10-environmental-exposure-scope.ts
  // header note) — expansions here reuse the same official phrases as the burn/blast phases.
  { query: "heat stroke", anyOf: ["Heatstroke and sunstroke"] },
  { query: "heatstroke", anyOf: ["Heatstroke and sunstroke"] },
  { query: "coup de chaleur", anyOf: ["Heatstroke and sunstroke"] },
  { query: "exertional heatstroke", anyOf: ["Exertional heatstroke"] },
  { query: "coup de chaleur d'exercice", anyOf: ["Exertional heatstroke"] },
  { query: "heat exhaustion", anyOf: ["Heat exhaustion"] },
  { query: "épuisement par la chaleur", anyOf: ["Heat exhaustion"] },
  { query: "heat cramps", anyOf: ["Heat cramp"] },
  { query: "crampes de chaleur", anyOf: ["Heat cramp"] },
  { query: "heat syncope", anyOf: ["Heat syncope"] },
  { query: "syncope de chaleur", anyOf: ["Heat syncope"] },
  { query: "heat edema", anyOf: ["Heat edema"] },
  { query: "oedème de chaleur", anyOf: ["Heat edema"] },
  { query: "hypothermia", anyOf: ["Hypothermia"] },
  { query: "hypothermie", anyOf: ["Hypothermia"] },
  { query: "immersion foot", anyOf: ["Immersion foot"] },
  { query: "trench foot", anyOf: ["Immersion foot"] },
  { query: "pied d'immersion", anyOf: ["Immersion foot"] },
  { query: "immersion hand", anyOf: ["Immersion hand"] },
  { query: "main d'immersion", anyOf: ["Immersion hand"] },
  { query: "chilblains", anyOf: ["Chilblains"] },
  { query: "engelures", anyOf: ["Chilblains"] },
  // Frostnip has no dedicated ICD-10-CM code (only frostbite T33/T34 does). Map to the
  // official "other/unspecified effects of reduced temperature" phrases (T69.8/T69.9).
  {
    query: "frostnip",
    anyOf: ["Other specified effects of reduced temperature", "Effect of reduced temperature, unspecified"],
  },
  {
    query: "engelure superficielle",
    anyOf: ["Other specified effects of reduced temperature", "Effect of reduced temperature, unspecified"],
  },
  { query: "drowning", anyOf: ["drowning and nonfatal submersion", "Accidental drowning and submersion"] },
  { query: "noyade", anyOf: ["drowning and nonfatal submersion", "Accidental drowning and submersion"] },
  { query: "near drowning", anyOf: ["drowning and nonfatal submersion"] },
  { query: "quasi-noyade", anyOf: ["drowning and nonfatal submersion"] },
  { query: "submersion injury", anyOf: ["drowning and nonfatal submersion"] },
  { query: "lésion de submersion", anyOf: ["drowning and nonfatal submersion"] },
  { query: "bathtub drowning", anyOf: ["drowning and submersion while in bath-tub"] },
  { query: "noyade en baignoire", anyOf: ["drowning and submersion while in bath-tub"] },
  { query: "swimming pool drowning", anyOf: ["drowning and submersion while in swimming-pool"] },
  { query: "noyade en piscine", anyOf: ["drowning and submersion while in swimming-pool"] },
  { query: "freshwater drowning", anyOf: ["drowning and submersion while in natural water"] },
  { query: "natural water drowning", anyOf: ["drowning and submersion while in natural water"] },
  { query: "noyade en eau douce", anyOf: ["drowning and submersion while in natural water"] },
  { query: "lightning strike", anyOf: ["Effects of lightning", "Shock due to being struck by lightning"] },
  { query: "struck by lightning", anyOf: ["Shock due to being struck by lightning", "Effects of lightning"] },
  { query: "frappé par la foudre", anyOf: ["Shock due to being struck by lightning", "Effects of lightning"] },
  { query: "electrocution", anyOf: ["Electrocution"] },
  { query: "électrocution", anyOf: ["Electrocution"] },
  { query: "electric shock", anyOf: ["Electrocution", "Exposure to electric transmission lines"] },
  { query: "choc électrique", anyOf: ["Electrocution", "Exposure to electric transmission lines"] },
  { query: "high voltage injury", anyOf: ["Exposure to electric transmission lines"] },
  { query: "exposition aux lignes électriques", anyOf: ["Exposure to electric transmission lines"] },
  { query: "household electrical exposure", anyOf: ["Exposure to domestic wiring and appliances"] },
  { query: "exposition au câblage domestique", anyOf: ["Exposure to domestic wiring and appliances"] },
  { query: "high altitude sickness", anyOf: ["effects of high altitude"] },
  { query: "altitude sickness", anyOf: ["effects of high altitude"] },
  { query: "acute mountain sickness", anyOf: ["effects of high altitude"] },
  { query: "mal aigu des montagnes", anyOf: ["effects of high altitude"] },
  { query: "mal des montagnes", anyOf: ["effects of high altitude"] },
  // HACE/HAPE have no dedicated ICD-10-CM code — map to the official
  // "other/unspecified effects of high altitude" phrase (T70.2), per ticket policy of
  // never inventing codes.
  { query: "hace", anyOf: ["effects of high altitude"] },
  { query: "hape", anyOf: ["effects of high altitude"] },
  { query: "high altitude cerebral edema", anyOf: ["effects of high altitude"] },
  { query: "high altitude pulmonary edema", anyOf: ["effects of high altitude"] },
  { query: "oedème cérébral de haute altitude", anyOf: ["effects of high altitude"] },
  { query: "oedème pulmonaire de haute altitude", anyOf: ["effects of high altitude"] },
  { query: "decompression sickness", anyOf: ["Caisson disease"] },
  { query: "the bends", anyOf: ["Caisson disease"] },
  { query: "caisson disease", anyOf: ["Caisson disease"] },
  { query: "maladie de décompression", anyOf: ["Caisson disease"] },
  { query: "maladie des caissons", anyOf: ["Caisson disease"] },
  { query: "diver's ear", anyOf: ["Otitic barotrauma"] },
  { query: "barotraumatisme de l'oreille du plongeur", anyOf: ["Otitic barotrauma"] },
  { query: "sinus barotrauma", anyOf: ["Sinus barotrauma"] },
  { query: "barotraumatisme sinusien", anyOf: ["Sinus barotrauma"] },
  { query: "diving injury", anyOf: ["Effects of high-pressure fluids"] },
  { query: "blessure de plongée", anyOf: ["Effects of high-pressure fluids"] },
  { query: "radiation sickness", anyOf: ["Radiation sickness"] },
  { query: "acute radiation syndrome", anyOf: ["Radiation sickness"] },
  { query: "mal des rayons", anyOf: ["Radiation sickness"] },
  { query: "syndrome d'irradiation aiguë", anyOf: ["Radiation sickness"] },
  { query: "radiation exposure", anyOf: ["ionizing radiation"] },
  { query: "exposition aux radiations ionisantes", anyOf: ["ionizing radiation"] },
  { query: "x-ray exposure", anyOf: ["Exposure to X-rays"] },
  { query: "exposition aux rayons x", anyOf: ["Exposure to X-rays"] },
  // Welding-light exposure is external-cause context only — it must not steal
  // photokeratitis (H16.13) ownership from the Phase 11 eye emergencies certifier.
  { query: "welding flash", anyOf: ["Exposure to welding light"] },
  { query: "arc eye exposure", anyOf: ["Exposure to welding light"] },
  { query: "exposition à la lumière de soudure", anyOf: ["Exposure to welding light"] },
  { query: "tanning bed exposure", anyOf: ["Exposure to tanning bed"] },
  { query: "exposition au lit de bronzage", anyOf: ["Exposure to tanning bed"] },
  { query: "excessive heat exposure", anyOf: ["Exposure to excessive natural heat", "Exposure to excessive heat of man-made origin"] },
  { query: "exposition à la chaleur excessive", anyOf: ["Exposure to excessive natural heat", "Exposure to excessive heat of man-made origin"] },
  { query: "excessive cold exposure", anyOf: ["Exposure to excessive natural cold", "Exposure to excessive cold of man-made origin"] },
  { query: "exposition au froid excessif", anyOf: ["Exposure to excessive natural cold", "Exposure to excessive cold of man-made origin"] },
  { query: "sun exposure", anyOf: ["Exposure to sunlight"] },
  { query: "exposition au soleil", anyOf: ["Exposure to sunlight"] },
  { query: "dry ice exposure", anyOf: ["dry ice"] },
  { query: "exposition à la glace sèche", anyOf: ["dry ice"] },

  // Toxicology / envenomation (Phase 16). Official FY2026 phrases only.
  { query: "acetaminophen overdose", anyOf: ["4-Aminophenol derivatives"] },
  { query: "acetaminophen poisoning", anyOf: ["4-Aminophenol derivatives"] },
  { query: "surdosage au paracétamol", anyOf: ["4-Aminophenol derivatives"] },
  { query: "intoxication au paracétamol", anyOf: ["4-Aminophenol derivatives"] },
  { query: "salicylate toxicity", anyOf: ["salicylates"] },
  { query: "aspirin overdose", anyOf: ["salicylates"] },
  { query: "toxicité aux salicylates", anyOf: ["salicylates"] },
  { query: "surdosage d'aspirine", anyOf: ["salicylates"] },
  { query: "opioid overdose", anyOf: ["Poisoning by", "opioids"] },
  { query: "fentanyl overdose", anyOf: ["synthetic narcotics", "fentanyl"] },
  { query: "methadone overdose", anyOf: ["methadone"] },
  { query: "surdosage d'opioïde", anyOf: ["Poisoning by", "opioids"] },
  { query: "benzodiazepine overdose", anyOf: ["benzodiazepines"] },
  { query: "sedative overdose", anyOf: ["sedative-hypnotic", "benzodiazepines"] },
  { query: "surdosage de benzodiazépine", anyOf: ["benzodiazepines"] },
  { query: "alcohol intoxication", anyOf: ["Alcohol abuse with intoxication", "Alcohol dependence with intoxication", "Alcohol use, unspecified with intoxication"] },
  { query: "intoxication alcoolique", anyOf: ["Alcohol abuse with intoxication", "Alcohol dependence with intoxication", "Alcohol use, unspecified with intoxication"] },
  { query: "alcohol withdrawal", anyOf: ["Alcohol dependence with withdrawal", "Alcohol abuse with withdrawal"] },
  { query: "sevrage alcoolique", anyOf: ["Alcohol dependence with withdrawal", "Alcohol abuse with withdrawal"] },
  { query: "delirium tremens", anyOf: ["Alcohol dependence with withdrawal delirium", "with withdrawal delirium"] },
  { query: "toxic alcohol poisoning", anyOf: ["Toxic effect of alcohol", "Toxic effect of methanol"] },
  { query: "methanol poisoning", anyOf: ["Toxic effect of methanol"] },
  { query: "intoxication au méthanol", anyOf: ["Toxic effect of methanol"] },
  { query: "ethylene glycol poisoning", anyOf: ["Toxic effect of glycols"] },
  { query: "intoxication à l'éthylène glycol", anyOf: ["Toxic effect of glycols"] },
  { query: "cocaine toxicity", anyOf: ["Cocaine"] },
  { query: "toxicité à la cocaïne", anyOf: ["Cocaine"] },
  { query: "methamphetamine intoxication", anyOf: ["Other stimulant", "stimulant"] },
  { query: "intoxication à la méthamphétamine", anyOf: ["Other stimulant", "stimulant"] },
  { query: "stimulant overdose", anyOf: ["Other stimulant", "stimulant"] },
  { query: "cannabis intoxication", anyOf: ["Cannabis"] },
  { query: "intoxication au cannabis", anyOf: ["Cannabis"] },
  { query: "synthetic cannabinoid intoxication", anyOf: ["synthetic cannabinoids", "Cannabis"] },
  { query: "serotonin syndrome", anyOf: ["Serotonin syndrome"] },
  { query: "syndrome sérotoninergique", anyOf: ["Serotonin syndrome"] },
  { query: "neuroleptic malignant syndrome", anyOf: ["Malignant neuroleptic syndrome"] },
  { query: "syndrome malin des neuroleptiques", anyOf: ["Malignant neuroleptic syndrome"] },
  { query: "anticholinergic poisoning", anyOf: ["parasympatholytics [anticholinergics and antimuscarinics]"] },
  { query: "organophosphate poisoning", anyOf: ["organophosphate and carbamate"] },
  { query: "intoxication aux organophosphorés", anyOf: ["organophosphate and carbamate"] },
  { query: "cholinergic toxidrome", anyOf: ["organophosphate and carbamate"] },
  { query: "beta blocker overdose", anyOf: ["beta-adrenoreceptor antagonists"] },
  { query: "surdosage de bêta-bloquant", anyOf: ["beta-adrenoreceptor antagonists"] },
  { query: "calcium channel blocker overdose", anyOf: ["calcium-channel blockers"] },
  { query: "surdosage d'inhibiteur calcique", anyOf: ["calcium-channel blockers"] },
  { query: "digoxin toxicity", anyOf: ["cardiac-stimulant glycosides"] },
  { query: "toxicité à la digoxine", anyOf: ["cardiac-stimulant glycosides"] },
  { query: "lithium toxicity", anyOf: ["Toxic effect of other metals"] },
  { query: "toxicité au lithium", anyOf: ["Toxic effect of other metals"] },
  { query: "iron poisoning", anyOf: ["iron and its compounds"] },
  { query: "intoxication au fer", anyOf: ["iron and its compounds"] },
  { query: "carbon monoxide poisoning", anyOf: ["Toxic effect of carbon monoxide"] },
  { query: "intoxication au monoxyde de carbone", anyOf: ["Toxic effect of carbon monoxide"] },
  { query: "cyanide poisoning", anyOf: ["hydrogen cyanide", "cyanides"] },
  { query: "intoxication au cyanure", anyOf: ["hydrogen cyanide", "cyanides"] },
  { query: "hydrogen sulfide exposure", anyOf: ["hydrogen sulfide"] },
  { query: "exposition à l'hydrogène sulfuré", anyOf: ["hydrogen sulfide"] },
  { query: "methemoglobinemia", anyOf: ["Methemoglobinemia", "Other methemoglobinemias"] },
  { query: "méthémoglobinémie", anyOf: ["Methemoglobinemia", "Other methemoglobinemias"] },
  { query: "caustic ingestion", anyOf: ["Toxic effect of corrosive", "Toxic effect of other corrosive", "Toxic effect of unspecified corrosive"] },
  { query: "ingestion caustique", anyOf: ["Toxic effect of corrosive", "Toxic effect of other corrosive", "Toxic effect of unspecified corrosive"] },
  { query: "hydrocarbon ingestion", anyOf: ["Toxic effect of petroleum products", "Toxic effect of", "hydrocarbons"] },
  { query: "ingestion d'hydrocarbures", anyOf: ["Toxic effect of petroleum products", "hydrocarbons"] },
  { query: "pesticide poisoning", anyOf: ["Toxic effect of pesticides", "organophosphate"] },
  { query: "intoxication par pesticide", anyOf: ["Toxic effect of pesticides", "organophosphate"] },
  { query: "mushroom poisoning", anyOf: ["Toxic effect of ingested mushrooms"] },
  { query: "intoxication par champignons", anyOf: ["Toxic effect of ingested mushrooms"] },
  { query: "plant poisoning", anyOf: ["Toxic effect of other ingested (parts of) plant(s)"] },
  { query: "intoxication par plantes", anyOf: ["Toxic effect of other ingested (parts of) plant(s)"] },
  { query: "snake envenomation", anyOf: ["snake venom"] },
  { query: "venomous snake bite", anyOf: ["snake venom"] },
  { query: "envenimation par serpent", anyOf: ["snake venom"] },
  { query: "spider envenomation", anyOf: ["venom of other spider", "venom of black widow", "venom of brown recluse"] },
  { query: "black widow bite", anyOf: ["venom of black widow"] },
  { query: "brown recluse bite", anyOf: ["venom of brown recluse"] },
  { query: "envenimation par araignée", anyOf: ["venom of other spider", "venom of black widow"] },
  { query: "scorpion sting", anyOf: ["venom of scorpion"] },
  { query: "piqûre de scorpion", anyOf: ["venom of scorpion"] },
  { query: "marine envenomation", anyOf: ["venomous marine animals", "contact with other venomous marine animals", "Portuguese Man-o-war", "stingray"] },
  { query: "envenimation marine", anyOf: ["venomous marine animals", "contact with other venomous marine animals", "Portuguese Man-o-war", "stingray"] },
  { query: "unknown ingestion", anyOf: ["Poisoning by unspecified drugs, medicaments and biological substances"] },
  { query: "ingestion inconnue", anyOf: ["Poisoning by unspecified drugs, medicaments and biological substances"] },
  { query: "mixed overdose", anyOf: ["Poisoning by unspecified drugs, medicaments and biological substances"] },
  { query: "surdosage mixte", anyOf: ["Poisoning by unspecified drugs, medicaments and biological substances"] },
  { query: "intentional overdose", anyOf: ["intentional self-harm"] },
  { query: "surdosage intentionnel", anyOf: ["intentional self-harm"] },

  // OB/GYN / urology (Phase 17). Official FY2026 phrases only.
  // Clinical "pregnancy of unknown location" maps to official O02.81 hCG description (Index concept).
  {
    query: "pregnancy of unknown location",
    anyOf: [
      "Inapprop chg quantitav hCG in early pregnancy",
      "Inappropriate change in quantitative human chorionic gonadotropin",
    ],
  },
  {
    query: "grossesse de localisation inconnue",
    anyOf: [
      "Inapprop chg quantitav hCG in early pregnancy",
      "Inappropriate change in quantitative human chorionic gonadotropin",
    ],
  },
  { query: "threatened abortion", anyOf: ["Threatened abortion"] },
  { query: "threatened miscarriage", anyOf: ["Threatened abortion"] },
  { query: "menace d'avortement", anyOf: ["Threatened abortion"] },
  { query: "spontaneous abortion", anyOf: ["Spontaneous abortion"] },
  { query: "avortement spontané", anyOf: ["Spontaneous abortion"] },
  { query: "ectopic pregnancy", anyOf: ["Ectopic pregnancy"] },
  { query: "grossesse ectopique", anyOf: ["Ectopic pregnancy"] },
  // Prefer billable hyperemesis phrases (O21 header "Excessive vomiting..." is non-selectable).
  { query: "hyperemesis gravidarum", anyOf: ["Hyperemesis gravidarum", "Mild hyperemesis gravidarum"] },
  { query: "hyperémèse gravidique", anyOf: ["Hyperemesis gravidarum", "Mild hyperemesis gravidarum"] },
  { query: "preeclampsia", anyOf: ["Pre-eclampsia", "Preeclampsia"] },
  { query: "prééclampsie", anyOf: ["Pre-eclampsia"] },
  { query: "HELLP syndrome", anyOf: ["HELLP syndrome"] },
  { query: "syndrome HELLP", anyOf: ["HELLP syndrome"] },
  { query: "preterm labor", anyOf: ["Preterm labor"] },
  { query: "travail prématuré", anyOf: ["Preterm labor"] },
  { query: "rupture of membranes", anyOf: ["Premature rupture of membranes"] },
  { query: "rupture prématurée des membranes", anyOf: ["Premature rupture of membranes"] },
  { query: "postpartum hemorrhage", anyOf: ["Postpartum hemorrhage"] },
  { query: "hémorragie post-partum", anyOf: ["Postpartum hemorrhage"] },
  { query: "postpartum endometritis", anyOf: ["Endometritis following delivery"] },
  { query: "endométrite post-partum", anyOf: ["Endometritis following delivery"] },
  { query: "ovarian torsion", anyOf: ["Torsion of ovary"] },
  { query: "torsion ovarienne", anyOf: ["Torsion of ovary"] },
  { query: "ovarian cyst", anyOf: ["Ovarian cyst"] },
  { query: "kyste ovarien", anyOf: ["Ovarian cyst"] },
  { query: "pelvic inflammatory disease", anyOf: ["Female pelvic inflammatory disease"] },
  { query: "maladie pelvienne inflammatoire", anyOf: ["Female pelvic inflammatory disease"] },
  // No dedicated "tubo-ovarian abscess" phrase in FY2026; map to acute salpingo-oophoritis.
  { query: "tubo-ovarian abscess", anyOf: ["Acute salpingitis and oophoritis", "Salpingitis and oophoritis"] },
  { query: "abcès tubo-ovarien", anyOf: ["Acute salpingitis and oophoritis", "Salpingitis and oophoritis"] },
  { query: "Bartholin cyst", anyOf: ["Bartholin"] },
  { query: "kyste de Bartholin", anyOf: ["Bartholin"] },
  { query: "postmenopausal bleeding", anyOf: ["Postmenopausal bleeding"] },
  { query: "saignement postménopausique", anyOf: ["Postmenopausal bleeding"] },
  { query: "IUD complication", anyOf: ["intrauterine contraceptive device"] },
  { query: "complication DIU", anyOf: ["intrauterine contraceptive device"] },
  { query: "kidney stone", anyOf: ["Calculus of kidney", "Calculus of ureter"] },
  { query: "calcul du rein", anyOf: ["Calculus of kidney"] },
  { query: "pyelonephritis", anyOf: ["Acute pyelonephritis", "Acute tubulo-interstitial nephritis"] },
  { query: "pyélonéphrite", anyOf: ["Acute pyelonephritis", "Acute tubulo-interstitial nephritis"] },
  { query: "cystitis", anyOf: ["Cystitis"] },
  { query: "cystite", anyOf: ["Cystitis"] },
  { query: "hematuria", anyOf: ["Hematuria"] },
  { query: "hématurie", anyOf: ["Hematuria"] },
  { query: "urinary retention", anyOf: ["Retention of urine"] },
  { query: "rétention urinaire", anyOf: ["Retention of urine"] },
  { query: "testicular torsion", anyOf: ["Torsion of testis"] },
  { query: "torsion testiculaire", anyOf: ["Torsion of testis"] },
  { query: "epididymitis", anyOf: ["Epididymitis"] },
  { query: "épididymite", anyOf: ["Epididymitis"] },
  { query: "prostatitis", anyOf: ["Prostatitis"] },
  { query: "prostatite", anyOf: ["Prostatitis"] },
  { query: "urethritis", anyOf: ["Urethritis"] },
  { query: "urétrite", anyOf: ["Urethritis"] },
  { query: "priapism", anyOf: ["Priapism"] },
  { query: "priapisme", anyOf: ["Priapism"] },
  { query: "paraphimosis", anyOf: ["Paraphimosis"] },
  { query: "penile fracture", anyOf: ["Fracture of corpus cavernosum penis"] },

  // Psychiatric / behavioral (Phase 18). Official FY2026 phrases only.
  { query: "suicidal ideation", anyOf: ["Suicidal ideations"] },
  { query: "idées suicidaires", anyOf: ["Suicidal ideations"] },
  { query: "passive SI", anyOf: ["Suicidal ideations"] },
  { query: "SI passive", anyOf: ["Suicidal ideations"] },
  { query: "NSSI", anyOf: ["Nonsuicidal self-harm"] },
  { query: "non-suicidal self-injury", anyOf: ["Nonsuicidal self-harm"] },
  { query: "nonsuicidal self injury", anyOf: ["Nonsuicidal self-harm"] },
  { query: "automutilation non suicidaire", anyOf: ["Nonsuicidal self-harm"] },
  { query: "command hallucinations", anyOf: ["Auditory hallucinations", "Hallucinations"] },
  { query: "hallucinations imperatives", anyOf: ["Auditory hallucinations", "Hallucinations"] },
  { query: "postpartum psychosis", anyOf: ["Puerperal psychosis"] },
  { query: "psychose post-partum", anyOf: ["Puerperal psychosis"] },
  // Official FY2026 shorts use abbreviations (pt lv / hlth care prov). Avoid bare "AMA" → Amaurosis.
  { query: "AMA", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "against medical advice", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "contre avis médical", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "elopement", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "fugue", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "homicidal ideation", anyOf: ["Homicidal ideations"] },
  { query: "idées homicidaires", anyOf: ["Homicidal ideations"] },
  { query: "acute psychosis", anyOf: ["Unspecified psychosis not due to a substance or known physiol", "Unspecified psychosis"] },
  { query: "psychose aiguë", anyOf: ["Unspecified psychosis not due to a substance or known physiol", "Unspecified psychosis"] },
  { query: "catatonia", anyOf: ["Catatonic disorder due to known physiological condition", "Catatonic schizophrenia"] },
  { query: "catatonie", anyOf: ["Catatonic disorder due to known physiological condition", "Catatonic schizophrenia"] },
  { query: "refusal of treatment", anyOf: ["pt decision for unsp reasons", "pt decision for oth reasons", "bec pt decision"] },
  { query: "refus de traitement", anyOf: ["pt decision for unsp reasons", "pt decision for oth reasons", "bec pt decision"] },
  { query: "passive suicidal ideation", anyOf: ["Suicidal ideations"] },
  { query: "idées suicidaires passives", anyOf: ["Suicidal ideations"] },
  { query: "suicide attempt", anyOf: ["Suicide attempt"] },
  { query: "tentative de suicide", anyOf: ["Suicide attempt"] },
  { query: "intentional self harm", anyOf: ["Intentional self-harm"] },
  { query: "automutilation intentionnelle", anyOf: ["Intentional self-harm"] },
  { query: "self inflicted injury", anyOf: ["Intentional self-harm"] },
  { query: "blessure auto-infligée", anyOf: ["Intentional self-harm"] },
  { query: "self cutting", anyOf: ["Nonsuicidal self-harm", "Self-harm by cutting"] },
  { query: "automutilation par coupures", anyOf: ["Nonsuicidal self-harm", "Self-harm by cutting"] },
  { query: "overdose with suicidal intent", anyOf: ["intentional self-harm"] },
  { query: "surdosage avec intention suicidaire", anyOf: ["intentional self-harm"] },
  { query: "history of suicide attempt", anyOf: ["Personal history of suicidal behavior"] },
  { query: "antécédents de tentative de suicide", anyOf: ["Personal history of suicidal behavior"] },
  { query: "unspecified psychosis", anyOf: ["Unspecified psychosis"] },
  { query: "psychose non précisée", anyOf: ["Unspecified psychosis"] },
  { query: "first episode psychosis", anyOf: ["Brief psychotic disorder", "Unspecified psychosis"] },
  { query: "premier épisode psychotique", anyOf: ["Brief psychotic disorder", "Unspecified psychosis"] },
  { query: "hallucinations", anyOf: ["Hallucinations"] },
  { query: "auditory hallucinations", anyOf: ["Auditory hallucinations"] },
  { query: "hallucinations auditives", anyOf: ["Auditory hallucinations"] },
  { query: "delusions", anyOf: ["Delusional disorders"] },
  { query: "délire", anyOf: ["Delusional disorders"] },
  { query: "paranoia", anyOf: ["Delusional disorders", "Paranoid schizophrenia"] },
  { query: "paranoïa", anyOf: ["Delusional disorders", "Paranoid schizophrenia"] },
  { query: "schizophrenia", anyOf: ["Schizophrenia"] },
  { query: "schizophrénie", anyOf: ["Schizophrenia"] },
  { query: "substance induced psychosis", anyOf: ["psychotic disorder"] },
  { query: "psychose induite par substance", anyOf: ["psychotic disorder"] },
  { query: "mania", anyOf: ["Manic episode"] },
  { query: "manie", anyOf: ["Manic episode"] },
  { query: "manic episode", anyOf: ["Manic episode"] },
  { query: "épisode maniaque", anyOf: ["Manic episode"] },
  { query: "bipolar disorder", anyOf: ["Bipolar disorder"] },
  { query: "trouble bipolaire", anyOf: ["Bipolar disorder"] },
  { query: "severe depression", anyOf: ["Major depressive disorder"] },
  { query: "dépression sévère", anyOf: ["Major depressive disorder"] },
  { query: "major depressive disorder", anyOf: ["Major depressive disorder"] },
  { query: "trouble dépressif majeur", anyOf: ["Major depressive disorder"] },
  { query: "depression with psychotic features", anyOf: ["severe w psych features", "psych features"] },
  { query: "dépression avec symptômes psychotiques", anyOf: ["severe w psych features", "psych features"] },
  { query: "postpartum depression", anyOf: ["Postpartum depression"] },
  { query: "dépression post-partum", anyOf: ["Postpartum depression"] },
  { query: "panic attack", anyOf: ["Panic disorder"] },
  { query: "crise de panique", anyOf: ["Panic disorder"] },
  { query: "panic disorder", anyOf: ["Panic disorder"] },
  { query: "trouble panique", anyOf: ["Panic disorder"] },
  { query: "anxiety", anyOf: ["Anxiety disorder"] },
  { query: "anxiété", anyOf: ["Anxiety disorder"] },
  { query: "acute stress reaction", anyOf: ["Acute stress reaction"] },
  { query: "réaction au stress aigu", anyOf: ["Acute stress reaction"] },
  { query: "post traumatic stress disorder", anyOf: ["Post-traumatic stress disorder"] },
  { query: "état de stress post-traumatique", anyOf: ["Post-traumatic stress disorder"] },
  { query: "PTSD", anyOf: ["Post-traumatic stress disorder"] },
  { query: "ESPT", anyOf: ["Post-traumatic stress disorder"] },
  { query: "dissociation", anyOf: ["Dissociative"] },
  { query: "adjustment disorder", anyOf: ["Adjustment disorder"] },
  { query: "trouble adaptatif", anyOf: ["Adjustment disorder"] },
  { query: "grief reaction", anyOf: ["Prolonged grief disorder"] },
  { query: "réaction de deuil", anyOf: ["Prolonged grief disorder"] },
  { query: "delirium", anyOf: ["Delirium"] },
  { query: "délirium", anyOf: ["Delirium"] },
  { query: "acute confusion", anyOf: ["Disorientation"] },
  { query: "confusion aiguë", anyOf: ["Disorientation"] },
  { query: "altered mental status", anyOf: ["Altered mental status"] },
  { query: "altération de l'état mental", anyOf: ["Altered mental status"] },
  { query: "dementia with behavioral disturbance", anyOf: ["behavioral disturbance"] },
  { query: "démence avec perturbation comportementale", anyOf: ["behavioral disturbance"] },
  { query: "wandering", anyOf: ["Wandering in diseases classified elsewhere"] },
  { query: "errance", anyOf: ["Wandering in diseases classified elsewhere"] },
  { query: "malignant catatonia", anyOf: ["Catatonic disorder due to known physiological condition", "Catatonic schizophrenia"] },
  { query: "catatonie maligne", anyOf: ["Catatonic disorder due to known physiological condition", "Catatonic schizophrenia"] },
  { query: "agitation", anyOf: ["Restlessness and agitation"] },
  { query: "aggressive behavior", anyOf: ["Violent behavior"] },
  { query: "comportement agressif", anyOf: ["Violent behavior"] },
  { query: "violent behavior", anyOf: ["Violent behavior"] },
  { query: "comportement violent", anyOf: ["Violent behavior"] },
  { query: "behavioral crisis", anyOf: ["Other symptoms and signs involving emotional state"] },
  { query: "crise comportementale", anyOf: ["Other symptoms and signs involving emotional state"] },
  { query: "autism behavioral crisis", anyOf: ["Autistic disorder"] },
  { query: "crise comportementale autisme", anyOf: ["Autistic disorder"] },
  { query: "pediatric behavioral emergency", anyOf: ["Conduct disorder"] },
  { query: "urgence comportementale pédiatrique", anyOf: ["Conduct disorder"] },
  { query: "adolescent suicidal ideation", anyOf: ["Suicidal ideation"] },
  { query: "idées suicidaires adolescent", anyOf: ["Suicidal ideation"] },
  { query: "intellectual disability with behavioral disturbance", anyOf: ["intellectual disabilit"] },
  { query: "déficience intellectuelle avec perturbation comportementale", anyOf: ["intellectual disabilit"] },
  { query: "anorexia nervosa", anyOf: ["Anorexia nervosa"] },
  { query: "anorexie mentale", anyOf: ["Anorexia nervosa"] },
  { query: "bulimia nervosa", anyOf: ["Bulimia nervosa"] },
  { query: "boulimie", anyOf: ["Bulimia nervosa"] },
  { query: "binge eating disorder", anyOf: ["Binge eating disorder"] },
  { query: "hyperphagie boulimique", anyOf: ["Binge eating disorder"] },
  { query: "avoidant restrictive food intake disorder", anyOf: ["Avoidant/restrictive food intake disorder"] },
  { query: "trouble restrictif de l'alimentation", anyOf: ["Avoidant/restrictive food intake disorder"] },
  { query: "eating disorder", anyOf: ["Eating disorder"] },
  { query: "trouble alimentaire", anyOf: ["Eating disorder"] },
  { query: "informed refusal", anyOf: ["pt decision for unsp reasons", "pt decision for oth reasons", "bec pt decision"] },
  { query: "refus éclairé", anyOf: ["pt decision for unsp reasons", "pt decision for oth reasons", "bec pt decision"] },
  { query: "leaving against medical advice", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "départ contre avis médical", anyOf: ["pt lv bef seen by hlth care prov", "lv bef seen by hlth care"] },
  { query: "involuntary psychiatric evaluation", anyOf: ["Encntr for general psychiatric exam, requested by authority", "general psychiatric exam"] },
  { query: "évaluation psychiatrique involontaire", anyOf: ["Encntr for general psychiatric exam, requested by authority", "general psychiatric exam"] },
  { query: "emergency detention", anyOf: ["Encntr for general psychiatric exam, requested by authority", "general psychiatric exam"] },
  { query: "rétention d'urgence", anyOf: ["Encntr for general psychiatric exam, requested by authority", "general psychiatric exam"] },
  { query: "psychiatric observation", anyOf: ["Encntr for obs for oth suspected diseases and cond ruled out", "obs for oth suspected"] },
  { query: "observation psychiatrique", anyOf: ["Encntr for obs for oth suspected diseases and cond ruled out", "obs for oth suspected"] },

];

export function normalizeIcd10SearchQuery(q: string): string {
  return q
    .trim()
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/\s+/g, " ");
}

export function resolveIcd10ClinicalQueryExpansion(q: string): Icd10QueryExpansion | null {
  const key = normalizeIcd10SearchQuery(q);
  if (!key) return null;
  return (
    ICD10_CLINICAL_QUERY_EXPANSIONS.find((e) => normalizeIcd10SearchQuery(e.query) === key) ?? null
  );
}
