/**
 * Plain-language clinical synonyms for ICD-10-CM catalog search.
 * Does not invent codes — only expands queries to official description phrases.
 */

export type Icd10QueryExpansion = {
  /** Normalized lowercase query key (trimmed). */
  query: string;
  /** Additional description phrases OR'd into search (any match). */
  anyOf?: string[];
  /** Phrases that must all appear in short/long/searchText (AND). */
  allOf?: string[];
};

/** Exact-phrase expansions for common ED tendon/ligament searches. */
export const ICD10_CLINICAL_QUERY_EXPANSIONS: Icd10QueryExpansion[] = [
  // Spine/back emergency (Phase 9): official-description query expansion only.
  // Prefer exact official short-description phrases. Avoid broad tokens like "cervical"
  // or "fracture of" alone — they pull abbreviated S-code rows (e.g. "cervcal", "fx")
  // and extremity fractures ahead of the intended spine diagnoses.
  { query: "neck pain", anyOf: ["Cervicalgia", "cervicalgia"] },
  { query: "douleur cervicale", anyOf: ["Cervicalgia", "cervicalgia"] },
  { query: "cervical strain", anyOf: ["strain of muscle", "fascia and tendon at neck level"] },
  { query: "entorse cervicale", anyOf: ["strain of muscle", "fascia and tendon at neck level"] },
  { query: "thoracic strain", anyOf: ["sprain of ligaments of thoracic spine", "pain in thoracic spine"] },
  { query: "douleur thoracique rachidienne", anyOf: ["pain in thoracic spine"] },
  { query: "lumbar strain", anyOf: ["strain of muscle", "fascia and tendon of lower back"] },
  { query: "entorse lombaire", anyOf: ["strain of muscle", "fascia and tendon of lower back"] },
  { query: "low back pain", anyOf: ["low back pain", "lumbago"] },
  { query: "lombalgie", anyOf: ["low back pain", "lumbago"] },
  { query: "herniated disc", anyOf: ["disc disorder", "displacement", "intervertebral disc"] },
  { query: "hernie discale", anyOf: ["disc disorder", "displacement", "intervertebral disc"] },
  { query: "cervical disc herniation", anyOf: ["cervical disc", "Other cervical disc displacement", "disc disorders w radiculopathy, cervical"] },
  // Avoid bare "lumbar" — it steals vertebral fracture S32 rows ahead of M51 disc codes.
  { query: "lumbar disc herniation", anyOf: ["Other intervertebral disc displacement, lumbar region", "intervertebral disc displacement, lumbar", "disc disorders w radiculopathy, lumbar region"] },
  { query: "sciatica", anyOf: ["sciatica", "lumbago with sciatica"] },
  { query: "sciatique", anyOf: ["sciatica", "lumbago with sciatica"] },
  { query: "radiculopathy", anyOf: ["radiculopathy"] },
  { query: "radiculopathie", anyOf: ["radiculopathy"] },
  { query: "cervical radiculopathy", anyOf: ["radiculopathy, cervical"] },
  { query: "radiculopathie cervicale", anyOf: ["radiculopathy, cervical"] },
  { query: "thoracic radiculopathy", anyOf: ["radiculopathy, thoracic"] },
  { query: "lumbar radiculopathy", anyOf: ["radiculopathy, lumbar"] },
  { query: "radiculopathie lombaire", anyOf: ["radiculopathy, lumbar"] },
  { query: "spinal stenosis", anyOf: ["spinal stenosis"] },
  { query: "sténose rachidienne", anyOf: ["spinal stenosis"] },
  { query: "cervical myelopathy", anyOf: ["myelopathy"] },
  { query: "myélopathie cervicale", anyOf: ["myelopathy"] },
  { query: "thoracic myelopathy", anyOf: ["myelopathy"] },
  { query: "cauda equina", anyOf: ["cauda equina syndrome"] },
  { query: "cauda equina syndrome", anyOf: ["cauda equina syndrome"] },
  { query: "queue de cheval", anyOf: ["cauda equina syndrome"] },
  { query: "syndrome de la queue de cheval", anyOf: ["cauda equina syndrome"] },
  { query: "conus medullaris syndrome", anyOf: ["conus medullaris"] },
  { query: "syndrome du cône médullaire", anyOf: ["conus medullaris"] },
  { query: "spinal epidural abscess", anyOf: ["intraspinal abscess and granuloma", "extradural and subdural abscess"] },
  { query: "epidural abscess", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "abcès épidural", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "abcès épidural rachidien", anyOf: ["intraspinal abscess", "extradural and subdural abscess"] },
  { query: "vertebral osteomyelitis", anyOf: ["osteomyelitis of vertebra", "osteomyelitis"] },
  { query: "ostéomyélite vertébrale", anyOf: ["osteomyelitis of vertebra", "osteomyelitis"] },
  { query: "discitis", anyOf: ["discitis"] },
  { query: "discite", anyOf: ["discitis"] },
  { query: "spinal cord compression", anyOf: ["cord compression", "myelopathy"] },
  { query: "compression médullaire", anyOf: ["cord compression", "myelopathy"] },
  { query: "metastatic spinal cord compression", anyOf: ["cord compression", "secondary malignant"] },
  { query: "compression médullaire métastatique", anyOf: ["cord compression", "secondary malignant"] },
  { query: "vertebral compression fracture", anyOf: ["wedge compression fracture", "compression fracture"] },
  { query: "fracture vertébrale par compression", anyOf: ["wedge compression fracture", "compression fracture"] },
  // Prefer long-form "burst fracture" shortDescriptions (not abbreviated "burst fx").
  { query: "burst fracture", anyOf: ["burst fracture"] },
  { query: "fracture éclatement", anyOf: ["burst fracture"] },
  // Official text uses "cervical vertebra" / abbreviated "cervcal" / "lum vertebra" / "thor vertebra".
  { query: "cervical spine fracture", anyOf: ["cervical vertebra", "cervcal vertebra"] },
  { query: "fracture cervicale", anyOf: ["cervical vertebra", "cervcal vertebra"] },
  { query: "thoracic spine fracture", anyOf: ["thoracic vertebra", "thor vertebra"] },
  { query: "fracture thoracique", anyOf: ["thoracic vertebra", "thor vertebra"] },
  { query: "lumbar spine fracture", anyOf: ["lumbar vertebra", "lum vertebra"] },
  { query: "fracture lombaire", anyOf: ["lumbar vertebra", "lum vertebra"] },
  // Official short text includes "… spinal cord" (e.g. "Unsp injury at unsp level of cervical spinal cord").
  // Prefer phrases that appear in shortDescription so search certification sees "spinal cord".
  { query: "spinal cord injury", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord", "edema of thoracic spinal cord"] },
  { query: "lésion médullaire", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord", "edema of thoracic spinal cord"] },
  { query: "central cord syndrome", anyOf: ["central cord syndrome"] },
  { query: "syndrome centromédullaire", anyOf: ["central cord syndrome"] },
  { query: "anterior cord syndrome", anyOf: ["anterior cord syndrome"] },
  { query: "syndrome médullaire antérieur", anyOf: ["anterior cord syndrome"] },
  { query: "posterior cord syndrome", anyOf: ["posterior cord syndrome"] },
  { query: "Brown-Sequard syndrome", anyOf: ["brown-sequard syndrome"] },
  { query: "syndrome de Brown-Séquard", anyOf: ["brown-sequard syndrome"] },
  // No dedicated "neurogenic/spinal shock" ICD phrase — map to official shock + cord injury text.
  { query: "neurogenic shock", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "choc neurogène", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "spinal shock", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  { query: "choc spinal", anyOf: ["Traumatic shock", "Other shock", "Shock, unspecified"] },
  // SCIWORA is a clinical descriptor; search surfaces official cord-injury codes only.
  { query: "SCIWORA", anyOf: ["level of cervical spinal cord", "level of thoracic spinal cord", "level of lumbar spinal cord", "edema of cervical spinal cord"] },
  // Human bite / high-risk contaminated wound (Phase 8). These map only to official description text.
  { query: "human bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "morsure humaine", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "fight bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "clenched fist", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "knuckle bite", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "morsure du poing", anyOf: ["accidental bite by another person", "assault by human bite"] },
  { query: "contaminated wound", anyOf: ["open wound", "puncture wound"] },
  { query: "bat bite", anyOf: ["bitten by bat", "bat"] },
  { query: "farm wound", anyOf: ["open wound", "puncture wound"] },
  { query: "flexor tenosynovitis", anyOf: ["synovitis and tenosynovitis", "infective"] },
  { query: "bite cellulitis", anyOf: ["cellulitis"] },
  { query: "deep-space hand infection", anyOf: ["cellulitis of finger", "tenosynovitis"] },
  { query: "plaie contaminée", anyOf: ["open wound", "puncture wound"] },
  { query: "dirty wound", anyOf: ["open wound", "puncture wound"] },
  { query: "plaie sale", anyOf: ["open wound", "puncture wound"] },
  { query: "achilles tendon rupture", anyOf: ["achilles tendon", "injury of achilles"] },
  { query: "achilles laceration", anyOf: ["laceration of achilles", "achilles tendon"] },
  { query: "rotator cuff tear", anyOf: ["rotator cuff", "rotatr-cuff", "rotatr cuff"] },
  { query: "biceps tendon rupture", anyOf: ["biceps tendon", "long head of biceps"] },
  { query: "triceps tendon rupture", anyOf: ["triceps", "musc/fasc/tend triceps"] },
  { query: "quadriceps tendon rupture", anyOf: ["quadriceps musc/fasc/tend", "quadriceps"] },
  // Official FY2026 text uses quadriceps musc/fasc/tend for traumatic patellar-tendon-region injuries.
  { query: "patellar tendon rupture", anyOf: ["quadriceps musc/fasc/tend", "patellar tendinitis"] },
  { query: "hamstring tendon injury", anyOf: ["post grp at thi lev", "msl/fasc/tnd post grp"] },
  { query: "flexor tendon laceration", anyOf: ["laceration of flexor"] },
  { query: "extensor tendon laceration", anyOf: ["laceration of extensor"] },
  { query: "mallet finger", anyOf: ["mallet finger"] },
  { query: "acl tear", anyOf: ["anterior cruciate ligament"] },
  { query: "acl", anyOf: ["anterior cruciate ligament"] },
  { query: "pcl tear", anyOf: ["posterior cruciate ligament"] },
  { query: "pcl", anyOf: ["posterior cruciate ligament"] },
  { query: "mcl tear", anyOf: ["medial collateral ligament"] },
  { query: "mcl", anyOf: ["medial collateral ligament"] },
  { query: "lcl tear", anyOf: ["lateral collateral ligament"] },
  { query: "lcl", anyOf: ["lateral collateral ligament"] },
  { query: "high ankle sprain", anyOf: ["tibiofibular ligament"] },
  { query: "syndesmotic ligament injury", anyOf: ["tibiofibular ligament"] },
  { query: "syndesmosis", anyOf: ["tibiofibular ligament"] },
  { query: "thumb ucl tear", allOf: ["metacarpophalangeal joint of", "thumb"] },
  { query: "thumb ucl", allOf: ["metacarpophalangeal joint of", "thumb"] },
  { query: "skier's thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "skiers thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "gamekeeper's thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  { query: "gamekeepers thumb", allOf: ["sprain of metacarpophalangeal joint of", "thumb"] },
  // Official FY2026 order file does not name “scapholunate”; map to wrist ligament / carpal sprain families.
  {
    query: "scapholunate ligament injury",
    anyOf: ["sprain of carpal joint", "traumatic rupture of unsp ligament of right wrist", "traumatic rupture of unsp ligament of left wrist"],
  },
  { query: "elbow ucl injury", allOf: ["ulnar collateral ligament", "elbow"] },
  { query: "elbow ucl", allOf: ["ulnar collateral ligament", "elbow"] },
  { query: "crush injury", anyOf: ["crushing injury", "crushed"] },
  { query: "crushing injury", anyOf: ["crushing injury", "crushed"] },
  { query: "crushed hand", allOf: ["crushing injury", "hand"] },
  { query: "crushed finger", allOf: ["crushing injury", "finger"] },
  { query: "crushed foot", allOf: ["crushing injury", "foot"] },
  { query: "industrial crush injury", anyOf: ["crushing injury", "crushed"] },
  { query: "prolonged compression", anyOf: ["traumatic ischemia of muscle"] },
  { query: "degloving injury", anyOf: ["crushing injury"] },
  { query: "compartment syndrome after crush", anyOf: ["traumatic ischemia of muscle"] },
  { query: "rhabdomyolysis after crush", anyOf: ["traumatic ischemia of muscle"] },
  { query: "traumatic amputation", anyOf: ["traumatic amputation"] },
  { query: "partial amputation", anyOf: ["partial traumatic amputation"] },
  { query: "complete amputation", anyOf: ["complete traumatic amputation"] },
  // Prefer amputation-specific phrases (avoid bare “fngr”, which also hits fracture shorts).
  { query: "severed finger", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "severed toe",
    anyOf: [
      "traumatic amputation of right great toe",
      "traumatic amputation of left great toe",
      "traumatic amp of right great toe",
      "traumatic amp of left great toe",
    ],
  },
  { query: "finger cut off", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "thumb cut off",
    anyOf: [
      "MCP amputation of thmb",
      "MCP amputation of right thumb",
      "MCP amputation of left thumb",
      "traumatic amputation of right thumb",
      "traumatic amputation of left thumb",
      "traumatic amp of right thumb",
      "traumatic amp of left thumb",
    ],
  },
  {
    query: "toe cut off",
    anyOf: [
      "traumatic amputation of right great toe",
      "traumatic amputation of left great toe",
      "traumatic amp of right great toe",
      "traumatic amp of left great toe",
    ],
  },
  { query: "avulsed digit", anyOf: ["MCP amputation", "traumatic amputation of finger", "traumatic amp of finger"] },
  {
    query: "hand amputation",
    anyOf: [
      "traumatic amp of left hand at wrist",
      "traumatic amp of right hand at wrist",
      "traumatic amputation of left hand",
      "traumatic amputation of right hand",
      "hand at wrist level",
    ],
  },
  {
    query: "foot amputation",
    anyOf: [
      "traumatic amp of right foot",
      "traumatic amp of left foot",
      "traumatic amputation of right foot",
      "traumatic amputation of left foot",
      "foot at ankle level",
    ],
  },
  { query: "foreign body", anyOf: ["foreign body"] },
  { query: "retained foreign body", anyOf: ["with foreign body", "w fb", "w foreign body"] },
  { query: "foreign body eye", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "foreign body ear", anyOf: ["foreign body in right ear", "foreign body in left ear", "foreign body in ear"] },
  { query: "foreign body nose", anyOf: ["foreign body in nasal", "foreign body in nostril"] },
  {
    query: "foreign body hand",
    anyOf: [
      "foreign body of right hand",
      "foreign body of left hand",
      "foreign body of unsp hand",
      "superficial foreign body of right hand",
      "superficial foreign body of left hand",
      "with foreign body of right hand",
      "with foreign body of left hand",
    ],
  },
  {
    query: "foreign body foot",
    anyOf: [
      "foreign body, right foot",
      "foreign body, left foot",
      "foreign body, unspecified foot",
      "superficial foreign body, right foot",
      "superficial foreign body, left foot",
      "with foreign body of right foot",
      "with foreign body of left foot",
    ],
  },
  { query: "glass in skin", anyOf: ["superficial foreign body", "with foreign body"] },
  { query: "metal fragment", anyOf: ["with foreign body", "superficial foreign body"] },
  { query: "needle fragment", anyOf: ["with foreign body", "superficial foreign body"] },
  {
    query: "splinter in foot",
    anyOf: [
      "superficial foreign body, right foot",
      "superficial foreign body, left foot",
      "with foreign body of right foot",
      "with foreign body of left foot",
    ],
  },
  { query: "splinter", anyOf: ["superficial foreign body", "puncture wound with foreign body"] },
  { query: "fishhook", anyOf: ["puncture wound with foreign body"] },
  { query: "swallowed foreign body", anyOf: ["foreign body in esophagus", "foreign body in stomach"] },
  { query: "aspirated foreign body", anyOf: ["foreign body in pharynx", "foreign body in larynx", "foreign body in bronchus"] },
  // Burn / corrosion / inhalation / frostbite / electrical (Phase 5)
  { query: "burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "thermal burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "first-degree burn", anyOf: ["Burn of first degree", "Sunburn of first degree"] },
  { query: "first degree burn", anyOf: ["Burn of first degree", "Sunburn of first degree"] },
  { query: "second-degree burn", anyOf: ["Burn of second degree"] },
  { query: "second degree burn", anyOf: ["Burn of second degree"] },
  { query: "third-degree burn", anyOf: ["Burn of third degree"] },
  { query: "third degree burn", anyOf: ["Burn of third degree"] },
  { query: "superficial burn", anyOf: ["Burn of first degree", "Superficial frostbite"] },
  { query: "partial-thickness burn", anyOf: ["Burn of second degree"] },
  { query: "partial thickness burn", anyOf: ["Burn of second degree"] },
  { query: "full-thickness burn", anyOf: ["Burn of third degree"] },
  { query: "full thickness burn", anyOf: ["Burn of third degree"] },
  { query: "facial burn", anyOf: ["Burn of first degree of head, face, and neck", "Burn of second degree of head, face, and neck", "Burn of third degree of head, face, and neck", "head, face, and neck"] },
  { query: "hand burn", allOf: ["Burn of", "hand"] },
  { query: "foot burn", allOf: ["Burn of", "foot"] },
  { query: "genital burn", anyOf: ["genital region"] },
  { query: "circumferential burn", anyOf: ["Burn of", "Burn and corrosion"] },
  { query: "chemical burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "acid burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "alkali burn", anyOf: ["Corrosion of", "Corrosion"] },
  { query: "electrical burn", anyOf: ["Electrocution", "Effects of lightning"] },
  { query: "lightning injury", anyOf: ["Effects of lightning", "lightning"] },
  { query: "smoke inhalation", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract", "respiratory tract"] },
  { query: "inhalation injury", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract"] },
  { query: "airway burn", anyOf: ["Burn of respiratory tract", "Corrosion of respiratory tract"] },
  { query: "frostbite", anyOf: ["Frostbite", "Superficial frostbite"] },
  { query: "cold injury", anyOf: ["Frostbite", "Superficial frostbite"] },
  { query: "sunburn", anyOf: ["Sunburn"] },
  { query: "scald", anyOf: ["Burn of", "Burn of second degree"] },
  { query: "grease burn", anyOf: ["Burn of", "Burn of second degree"] },
  { query: "steam burn", anyOf: ["Burn of", "Burn of respiratory tract"] },
  // Penetrating trauma (Phase 6): descriptions use "open wound" and often omit mechanism terms.
  { query: "penetrating wound", anyOf: ["open wound", "puncture wound", "penetrating wound"] },
  { query: "penetrating trauma", anyOf: ["open wound", "puncture wound", "penetrating wound"] },
  { query: "gunshot wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "gunshot", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "firearm injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "firearm", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "bullet wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "bullet", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "shotgun injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "pellet wound", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "BB gun injury", anyOf: ["gunshot wound", "open wound", "puncture wound"] },
  { query: "stab wound", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "stab", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "knife wound", anyOf: ["stab wound", "open wound", "puncture wound"] },
  { query: "knife", anyOf: ["stab wound", "open wound", "puncture wound"] },
  // Official FY2026 short descriptions often abbreviate puncture/open-wound phrases (Pnctr, abd, etc.).
  { query: "puncture wound", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "impalement", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "through-and-through wound", anyOf: ["Pnctr", "penet", "open wound"] },
  { query: "retained projectile", anyOf: ["foreign body", "with foreign body", "w fb", "w/o fb"] },
  { query: "retained bullet", anyOf: ["foreign body", "with foreign body", "w fb"] },
  { query: "penetrating chest wound", anyOf: ["wl of thorax", "thorax w penet", "Pnctr w/o fb of r frnt wl of thorax", "opn wnd of thorax"] },
  { query: "penetrating abdominal wound", anyOf: ["abd wall", "penet perit cav", "opn wnd abd"] },
  { query: "penetrating neck wound", anyOf: ["unsp part of neck", "pharynx and cervical esophagus", "Pnctr w/o foreign body of unsp part of neck"] },
  { query: "penetrating head wound", anyOf: ["open wound of scalp", "laceration without foreign body of scalp", "Pnctr of scalp"] },
  { query: "penetrating hand wound", anyOf: ["Puncture wound with foreign body of right hand", "Puncture wound of right hand", "Pnctr of right hand", "opn wnd of right hand", "open wound of right hand"] },
  { query: "penetrating eye injury", anyOf: ["Penetrating wound w foreign body of", "Penetrating wound of eyeball", "eyeball"] },
  { query: "blessure par balle", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "plaie par balle", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "blessure par arme à feu", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "projectile retenu", anyOf: ["foreign body", "with foreign body", "w fb"] },
  { query: "plaie par arme blanche", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "coup de couteau", anyOf: ["Pnctr", "open wound", "Puncture wound"] },
  { query: "traumatisme pénétrant", anyOf: ["Pnctr", "open wound", "penet"] },
  { query: "plaie pénétrante", anyOf: ["Pnctr", "open wound", "penet"] },
  { query: "empalement", anyOf: ["Pnctr", "Puncture wound"] },
  { query: "blessure thoracique pénétrante", anyOf: ["wl of thorax", "thorax w penet", "opn wnd of thorax"] },
  { query: "blessure abdominale pénétrante", anyOf: ["abd wall", "penet perit cav", "opn wnd abd"] },
  { query: "blessure cervicale pénétrante", anyOf: ["unsp part of neck", "pharynx and cervical esophagus", "Pnctr w/o foreign body of unsp part of neck"] },
  { query: "blessure oculaire pénétrante", anyOf: ["Penetrating wound w foreign body of", "Penetrating wound of eyeball", "eyeball"] },
  // Blast injury / polytrauma (Phase 7): expansion text remains anchored to official descriptions.
  { query: "unspecified multiple injuries", anyOf: ["Unspecified multiple injuries"] },
  { query: "traumatic shock", anyOf: ["Traumatic shock"] },
  { query: "traumatic rupture ear drum", anyOf: ["Traumatic rupture of unspecified ear drum", "Traumatic rupture of ear drum", "ear drum"] },
  { query: "otitic barotrauma", anyOf: ["Otitic barotrauma"] },
  { query: "explosion of blasting material", anyOf: ["Explosion of blasting material"] },
  { query: "discharge of firework", anyOf: ["Discharge of firework"] },
  { query: "asphyxiation due to cave-in", anyOf: ["Asphyxiation due to cave-in"] },
  { query: "blessures multiples non précisées", anyOf: ["Unspecified multiple injuries"] },
  { query: "choc traumatique", anyOf: ["Traumatic shock"] },
  { query: "barotraumatisme otitique", anyOf: ["Otitic barotrauma"] },
  { query: "explosion de matériau de dynamitage", anyOf: ["Explosion of blasting material"] },
  { query: "décharge de feu d'artifice", anyOf: ["Discharge of firework"] },
  // Head / facial trauma (Phase 10): official FY2026 text never uses "hematoma" for
  // traumatic intracranial/skull findings — it uses "hemorrhage". Prefer the traumatic
  // phrase explicitly so spontaneous (I62.*) codes are never surfaced ahead of S06.*.
  { query: "head injury", anyOf: ["intracranial injury", "unspecified injury of head"] },
  { query: "traumatisme crânien", anyOf: ["intracranial injury", "unspecified injury of head"] },
  { query: "concussion", anyOf: ["Concussion"] },
  { query: "commotion cérébrale", anyOf: ["Concussion"] },
  { query: "mild tbi", anyOf: ["Concussion"] },
  { query: "mild traumatic brain injury", anyOf: ["Concussion"] },
  { query: "tcc léger", anyOf: ["Concussion"] },
  { query: "traumatisme crânien léger", anyOf: ["Concussion"] },
  { query: "epidural hematoma", anyOf: ["Epidural hemorrhage"] },
  { query: "hématome épidural", anyOf: ["Epidural hemorrhage"] },
  { query: "subdural hematoma", anyOf: ["Traumatic subdural hemorrhage"] },
  { query: "hématome sous-dural", anyOf: ["Traumatic subdural hemorrhage"] },
  { query: "hématome sous-dural traumatique", anyOf: ["Traumatic subdural hemorrhage"] },
  // Prefer the abbreviated shortDescription phrase ("Traum subrac hem") for ranking — the
  // unabbreviated "Traumatic subarachnoid hemorrhage" only appears in longDescription, so
  // without it the unrelated but unabbreviated "Other nontraumatic subarachnoid hemorrhage"
  // (I60.8) wins the shortDescription rank boost and outranks the traumatic S06.6 codes.
  { query: "traumatic sah", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "traumatic subarachnoid hemorrhage", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "hémorragie sous-arachnoïdienne traumatique", anyOf: ["Traum subrac hem", "Traumatic subarachnoid hemorrhage"] },
  { query: "skull fracture", anyOf: ["fracture of vault of skull", "fracture of base of skull"] },
  { query: "fracture du crâne", anyOf: ["fracture of vault of skull", "fracture of base of skull"] },
  { query: "basilar skull fracture", anyOf: ["fracture of base of skull"] },
  { query: "fracture de la base du crâne", anyOf: ["fracture of base of skull"] },
  { query: "nasal fracture", anyOf: ["fracture of nasal bones"] },
  { query: "fracture nasale", anyOf: ["fracture of nasal bones"] },
  { query: "orbital fracture", anyOf: ["fracture of orbital floor", "fracture of orbit"] },
  { query: "fracture orbitaire", anyOf: ["fracture of orbital floor", "fracture of orbit"] },
  // Official FY2026 text uses "malar" (not "zygomatic") for the malar/maxillary/zygoma family.
  { query: "zygomatic fracture", anyOf: ["Malar fracture"] },
  { query: "fracture zygomatique", anyOf: ["Malar fracture"] },
  { query: "maxillary fracture", anyOf: ["Malar fracture", "LeFort fracture"] },
  { query: "fracture maxillaire", anyOf: ["Malar fracture", "LeFort fracture"] },
  { query: "mandibular fracture", anyOf: ["fracture of mandible"] },
  { query: "fracture mandibulaire", anyOf: ["fracture of mandible"] },
  { query: "le fort fracture", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "lefort fracture", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "fracture de le fort", anyOf: ["LeFort fracture", "LeFort I fracture", "LeFort II fracture", "LeFort III fracture"] },
  { query: "dental trauma", anyOf: ["Fracture of tooth", "Dislocation of tooth"] },
  { query: "traumatisme dentaire", anyOf: ["Fracture of tooth", "Dislocation of tooth"] },
  { query: "tooth avulsion", anyOf: ["Dislocation of tooth"] },
  { query: "avulsion dentaire", anyOf: ["Dislocation of tooth"] },
  { query: "jaw dislocation", anyOf: ["Dislocation of jaw"] },
  { query: "luxation de la mâchoire", anyOf: ["Dislocation of jaw"] },
  // No dedicated "hematoma" code for auricular/septal contusion — map to the official contusion
  // text. Ear contusion is lateralized ("Contusion of right/left/unspecified ear"), so list each.
  {
    query: "auricular hematoma",
    anyOf: ["Contusion of right ear", "Contusion of left ear", "Contusion of unspecified ear"],
  },
  {
    query: "hématome auriculaire",
    anyOf: ["Contusion of right ear", "Contusion of left ear", "Contusion of unspecified ear"],
  },
  { query: "septal hematoma", anyOf: ["Contusion of nose"] },
  { query: "hématome septal", anyOf: ["Contusion of nose"] },
  // No traumatic-specific CSF leak code — G96.08 is the only non-spontaneous cranial CSF leak code.
  { query: "csf leak after trauma", anyOf: ["Other cranial cerebrospinal fluid leak"] },
  { query: "fuite de lcr post-traumatique", anyOf: ["Other cranial cerebrospinal fluid leak"] },
  // Eye emergencies (Phase 11). Official FY2026 text is used verbatim wherever possible —
  // "corneal abrasion", "corneal ulcer", "photokeratitis", "hyphema", "acute angle-closure
  // glaucoma", "retinal detachment", "vitreous hemorrhage", and "central retinal artery
  // occlusion" already appear literally in official descriptions and need no expansion for
  // the English query, but French queries and a few English terms not used verbatim by CMS
  // (e.g. "corneal foreign body" -> "foreign body in cornea") require explicit expansion.
  { query: "corneal abrasion", anyOf: ["corneal abrasion"] },
  { query: "abrasion cornéenne", anyOf: ["corneal abrasion"] },
  { query: "corneal foreign body", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "corps étranger cornéen", anyOf: ["foreign body in cornea", "foreign body on external eye"] },
  { query: "corneal ulcer", anyOf: ["corneal ulcer"] },
  { query: "ulcère cornéen", anyOf: ["corneal ulcer"] },
  { query: "photokeratitis", anyOf: ["Photokeratitis"] },
  { query: "photokératite", anyOf: ["Photokeratitis"] },
  { query: "chemical eye injury", anyOf: ["Corrosion of cornea and conjunctival sac", "Corrosion of unspecified eyelid and periocular area"] },
  { query: "brûlure chimique de l'oeil", anyOf: ["Corrosion of cornea and conjunctival sac", "Corrosion of unspecified eyelid and periocular area"] },
  { query: "open globe", anyOf: ["Ocular laceration and rupture", "prolapse or loss of intraocular tissue"] },
  { query: "globe oculaire ouvert", anyOf: ["Ocular laceration and rupture", "prolapse or loss of intraocular tissue"] },
  { query: "hyphema", anyOf: ["Hyphema"] },
  { query: "hyphéma", anyOf: ["Hyphema"] },
  { query: "acute angle-closure glaucoma", anyOf: ["Acute angle-closure glaucoma"] },
  { query: "glaucome aigu", anyOf: ["Acute angle-closure glaucoma"] },
  { query: "retinal detachment", anyOf: ["retinal detachment"] },
  { query: "décollement de la rétine", anyOf: ["retinal detachment"] },
  { query: "vitreous hemorrhage", anyOf: ["Vitreous hemorrhage"] },
  { query: "hémorragie du vitré", anyOf: ["Vitreous hemorrhage"] },
  { query: "central retinal artery occlusion", anyOf: ["Central retinal artery occlusion"] },
  { query: "occlusion de l'artère rétinienne", anyOf: ["Central retinal artery occlusion"] },
  { query: "orbital cellulitis", anyOf: ["Cellulitis of right orbit", "Cellulitis of left orbit", "Cellulitis of unspecified orbit"] },
  { query: "cellulite orbitaire", anyOf: ["Cellulitis of right orbit", "Cellulitis of left orbit", "Cellulitis of unspecified orbit"] },
  { query: "preseptal cellulitis", anyOf: ["Periorbital cellulitis"] },
  { query: "cellulite préseptale", anyOf: ["Periorbital cellulitis"] },
  { query: "uveitis", anyOf: ["iridocyclitis"] },
  { query: "uvéite", anyOf: ["iridocyclitis"] },
  { query: "scleritis", anyOf: ["scleritis"] },
  { query: "sclérite", anyOf: ["scleritis"] },
  {
    query: "eyelid laceration",
    anyOf: [
      "Laceration without foreign body of right eyelid",
      "Laceration without foreign body of left eyelid",
      "Laceration without foreign body of unspecified eyelid",
      "Laceration with foreign body of right eyelid",
      "Laceration with foreign body of left eyelid",
      "Laceration with foreign body of unspecified eyelid",
    ],
  },
  {
    query: "lacération de la paupière",
    anyOf: [
      "Laceration without foreign body of right eyelid",
      "Laceration without foreign body of left eyelid",
      "Laceration without foreign body of unspecified eyelid",
      "Laceration with foreign body of right eyelid",
      "Laceration with foreign body of left eyelid",
      "Laceration with foreign body of unspecified eyelid",
    ],
  },
  { query: "endophthalmitis", anyOf: ["endophthalmitis"] },
  { query: "endophtalmie", anyOf: ["endophthalmitis"] },
  { query: "eye trauma", anyOf: ["Injury of eye and orbit", "eyeball"] },
  { query: "traumatisme oculaire", anyOf: ["Injury of eye and orbit", "eyeball"] },
];

export function normalizeIcd10SearchQuery(q: string): string {
  return q
    .trim()
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/\s+/g, " ");
}

export function resolveIcd10ClinicalQueryExpansion(q: string): Icd10QueryExpansion | null {
  const key = normalizeIcd10SearchQuery(q);
  if (!key) return null;
  return (
    ICD10_CLINICAL_QUERY_EXPANSIONS.find((e) => normalizeIcd10SearchQuery(e.query) === key) ?? null
  );
}
