-- M1.3F.7 — pharmacy verification MAR audit actions (enum additions only)
ALTER TYPE "AuditAction" ADD VALUE 'PHARMACY_VERIFICATION_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'PHARMACY_VERIFICATION_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'PHARMACY_VERIFICATION_OVERRIDE';
