import type { DigitalCareApiOperationContract } from "./digital-care-api.contract";

export const DIGITAL_CARE_REST_V1_PREFIX = "/digital-care/v1" as const;

export interface DigitalCareRestOperationContract
  extends DigitalCareApiOperationContract {
  readonly transport: "rest";
  readonly method: "GET" | "POST" | "PATCH";
  readonly path: string;
}

export const DIGITAL_CARE_REST_V1_OPERATIONS = [
  {
    id: "portal.status.get",
    capability: "portal",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/portal`,
    requiredPermissions: ["portal.self.read", "portal.operational.read"],
    authorizationMode: "any",
  },
  {
    id: "communication.threads.list",
    capability: "communication",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/conversations`,
    requiredPermissions: ["communication.self.read", "communication.assigned.read"],
    authorizationMode: "any",
  },
  {
    id: "communication.messages.create",
    capability: "communication",
    transport: "rest",
    kind: "command",
    method: "POST",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/conversations/:threadId/messages`,
    requiredPermissions: ["communication.self.write", "communication.assigned.write"],
    authorizationMode: "any",
  },
  {
    id: "notifications.list",
    capability: "notifications",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/notifications`,
    requiredPermissions: ["notifications.self.read"],
    authorizationMode: "all",
  },
  {
    id: "telemedicine.sessions.list",
    capability: "telemedicine",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/telemedicine-sessions`,
    requiredPermissions: ["telemedicine.self.join", "telemedicine.assigned.manage"],
    authorizationMode: "any",
  },
  {
    id: "education.assignments.list",
    capability: "education",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/education`,
    requiredPermissions: ["education.self.read", "education.assigned.manage"],
    authorizationMode: "any",
  },
  {
    id: "questionnaires.list",
    capability: "questionnaires",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/questionnaires`,
    requiredPermissions: ["questionnaires.self.read", "questionnaires.assigned.manage"],
    authorizationMode: "any",
  },
  {
    id: "questionnaires.submit",
    capability: "questionnaires",
    transport: "rest",
    kind: "command",
    method: "POST",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/questionnaires/:questionnaireId/responses`,
    requiredPermissions: ["questionnaires.self.submit"],
    authorizationMode: "all",
  },
  {
    id: "monitoring.programs.list",
    capability: "monitoring",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/monitoring`,
    requiredPermissions: ["monitoring.self.read", "monitoring.assigned.read"],
    authorizationMode: "any",
  },
  {
    id: "consent.list",
    capability: "consent",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/consents`,
    requiredPermissions: ["consent.self.read", "consent.assigned.manage"],
    authorizationMode: "any",
  },
  {
    id: "consent.sign",
    capability: "consent",
    transport: "rest",
    kind: "command",
    method: "POST",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/consents/:consentId/signatures`,
    requiredPermissions: ["consent.self.sign", "proxy.patient.act"],
    authorizationMode: "any",
  },
  {
    id: "proxy.relationships.list",
    capability: "proxy",
    transport: "rest",
    kind: "query",
    method: "GET",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/proxies`,
    requiredPermissions: ["proxy.self.read", "proxy.patient.act"],
    authorizationMode: "any",
  },
  {
    id: "ai.assist",
    capability: "ai",
    transport: "rest",
    kind: "command",
    method: "POST",
    path: `${DIGITAL_CARE_REST_V1_PREFIX}/patients/:patientId/ai/assist`,
    requiredPermissions: ["ai.self.use", "ai.assigned.assist"],
    authorizationMode: "any",
  },
] as const satisfies readonly DigitalCareRestOperationContract[];
