import{BadRequestException,ForbiddenException,NotFoundException}from"@nestjs/common";import{GovernanceBootstrapService,GOVERNANCE_BOOTSTRAP_CAPABILITIES,GOVERNANCE_BOOTSTRAP_PERSONA}from"./governance-bootstrap.service";
const actor="11111111-1111-4111-8111-111111111111",target="22222222-2222-4222-8222-222222222222",sid="session-1";
function harness(o:any={}){const events:any[]=[];const principal={id:actor,isActive:o.principalActive??true,canCreateFacilities:o.canCreate??true,userRoles:o.superAdmin===false?[]:[{id:"role"}]};const targetRow=o.target===null?null:{isActive:o.targetActive??true,medoraStaffProfile:o.profile??null,userRoles:[]};const tx:any={$executeRawUnsafe:jest.fn(),user:{findUnique:jest.fn(async(a:any)=>a.select?.canCreateFacilities?principal:targetRow),findFirst:jest.fn(async()=>o.approver?{id:"approver"}:null)},authSession:{findFirst:jest.fn(async()=>o.session===false?null:{mfaVerifiedAt:Object.prototype.hasOwnProperty.call(o,"mfaAt")?o.mfaAt:new Date()})},auditLog:{findFirst:jest.fn(async()=>o.completed?{id:"done"}:null)},medoraStaffProfile:{create:jest.fn(async()=>({id:"profile"}))},platformCapability:{findMany:jest.fn(async()=>GOVERNANCE_BOOTSTRAP_CAPABILITIES.map((code,i)=>({id:`cap-${i}`,code,isActive:true})))},platformCapabilityGrant:{create:jest.fn()},medoraStaffLifecycleEvent:{create:jest.fn()}};const prisma:any={...tx,$transaction:jest.fn(async(cb:any)=>cb(tx))};const audit:any={log:jest.fn(async(_a:any,_e:any,input:any)=>{events.push(input.metadata);if(o.auditFail&&input.metadata.event==="PLATFORM_GOVERNANCE_BOOTSTRAP_COMPLETED")throw new Error("audit failed")})};return{service:new GovernanceBootstrapService(prisma,audit),tx,prisma,audit,events}}
const input={targetUserId:target,reason:"Establish independent governance",ticketReference:"SEC-105B"};
describe("D4SEC.1C.5B authoritative governance bootstrap",()=>{afterEach(()=>delete process.env.MFA_STEP_UP_MAX_AGE_SECONDS);
it.each([["incomplete principal",{superAdmin:false}],["role alone",{canCreate:false}],["canCreateFacilities alone",{superAdmin:false}],["inactive principal",{principalActive:false}]])("denies %s",async(_n,o)=>{const h=harness(o);await expect(h.service.bootstrap({userId:actor,sessionId:sid},input)).rejects.toBeInstanceOf(ForbiddenException);expect(h.tx.medoraStaffProfile.create).not.toHaveBeenCalled()});
it("does not consult email, facility roles, ordinary staff, or client authority claims",async()=>{const h=harness({superAdmin:false});await expect(h.service.bootstrap({userId:actor,sessionId:sid} as any,{...input,isBootstrap:true,mfaVerifiedAt:new Date(),email:"admin@medora"} as any)).rejects.toThrow();expect(JSON.stringify(h.tx.user.findUnique.mock.calls)).not.toContain("email")});
it.each([["invalid session",{session:false}],["missing MFA",{mfaAt:null}],["stale MFA",{mfaAt:new Date(Date.now()-301_000)}]])("denies %s",async(_n,o)=>{const h=harness(o);await expect(h.service.bootstrap({userId:actor,sessionId:sid},input)).rejects.toThrow("RECENT_SESSION_MFA_REQUIRED")});
it("binds session lookup to exact sid and user and ignores forged proof",async()=>{const h=harness({session:false});await expect(h.service.bootstrap({userId:actor,sessionId:"forged"} as any,{...input,mfaVerifiedAt:new Date()} as any)).rejects.toThrow();expect(h.tx.authSession.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"forged",userId:actor,revokedAt:null,expiresAt:expect.anything()})}))});
it("denies self bootstrap and emits safe denial",async()=>{const h=harness();await expect(h.service.bootstrap({userId:actor,sessionId:sid},{...input,targetUserId:actor})).rejects.toThrow("SELF_BOOTSTRAP_PROHIBITED");expect(JSON.stringify(h.events)).not.toMatch(/token|authorization|mfaVerifiedAt|secret/i)});
it.each([["inactive target",{targetActive:false},BadRequestException],["missing target",{target:null},NotFoundException],["conflicting profile",{profile:{id:"p",isActive:false}},BadRequestException]])("denies %s",async(_n,o,error)=>{const h=harness(o);await expect(h.service.bootstrap({userId:actor,sessionId:sid},input)).rejects.toBeInstanceOf(error)});
it("success assigns exact persona, exact grants, lifecycle and safe audits",async()=>{const h=harness();const result=await h.service.bootstrap({userId:actor,sessionId:sid},input);expect(result.persona).toBe(GOVERNANCE_BOOTSTRAP_PERSONA);expect(h.tx.platformCapabilityGrant.create).toHaveBeenCalledTimes(GOVERNANCE_BOOTSTRAP_CAPABILITIES.length);const codes=h.tx.platformCapability.findMany.mock.results.length&&GOVERNANCE_BOOTSTRAP_CAPABILITIES;expect(codes).not.toEqual(expect.arrayContaining(["STAFF_PROVISION","STAFF_GRANT_CAPABILITIES","STAFF_REVOKE_CAPABILITIES"]));expect(h.tx.medoraStaffLifecycleEvent.create).toHaveBeenCalledTimes(1);expect(h.events.map(e=>e.event)).toEqual(["PLATFORM_GOVERNANCE_BOOTSTRAP_STARTED","PLATFORM_GOVERNANCE_BOOTSTRAP_COMPLETED"]);expect(JSON.stringify(h.events)).not.toMatch(/password|token|authorization|mfaVerifiedAt|secret/i)});
it("fails protected bootstrap when completion audit fails",async()=>{const h=harness({auditFail:true});await expect(h.service.bootstrap({userId:actor,sessionId:sid},input)).rejects.toThrow("audit failed");expect(h.prisma.$transaction).toHaveBeenCalled()});
it.each([["historical completion",{completed:true},"GOVERNANCE_BOOTSTRAP_CLOSED"],["eligible approver",{approver:true},"INDEPENDENT_APPROVER_ALREADY_EXISTS"]])("closes for %s",async(_n,o,message)=>{const h=harness(o);await expect(h.service.bootstrap({userId:actor,sessionId:sid},input)).rejects.toThrow(message);expect(h.tx.medoraStaffProfile.create).not.toHaveBeenCalled()});
it("takes the global advisory transaction lock before predicate checks",async()=>{const h=harness();await h.service.bootstrap({userId:actor,sessionId:sid},input);expect(h.tx.$executeRawUnsafe).toHaveBeenCalledWith("SELECT pg_advisory_xact_lock($1)",0x1c5b);expect(h.tx.$executeRawUnsafe.mock.invocationCallOrder[0]).toBeLessThan(h.tx.user.findUnique.mock.invocationCallOrder[0])});
it("status is server derived and remains closed from history even without active approver",async()=>{const h=harness({completed:true,approver:false});await expect(h.service.status(actor)).resolves.toEqual(expect.objectContaining({available:false,closed:true}))});
});
