import { BadRequestException, Body, Controller, Delete, Get, Param, Patch, Post, Query, Req, UseGuards } from "@nestjs/common";
import { createFacilityDtoSchema, facilityBillingIdentityPatchDtoSchema, facilityBillingWorkflowPatchDtoSchema, setFacilityLanguageDtoSchema, updateFacilityServiceConfigDtoSchema, type SetFacilityLanguageDto } from "@medora/shared";
import { AdminFacilitiesService } from "../admin/admin-facilities.service";
import { AuthGuard } from "@nestjs/passport";
import { changePersonaSchema, classifyStaffSchema, governanceBootstrapSchema, grantCapabilitySchema, provisionStaffSchema, revokeCapabilitySchema, staffLifecycleSchema } from "./dto/platform-staff.dto";
import { GovernanceBootstrapService } from "./governance-bootstrap.service";
import { RequirePlatformCapabilities, RequirePlatformPrincipal } from "./platform-capabilities.decorator";
import { PlatformCapabilitiesGuard } from "./platform-capabilities.guard";
import type { MedoraStaffPersonaCode, PlatformCapabilityCode } from "./platform-capabilities";
import { PlatformStaffService } from "./platform-staff.service";
import { PLATFORM_CAPABILITY_CODES } from "./platform-capabilities";
import { PlatformOwnerControlService } from "./platform-owner-control.service";
@Controller("platform") @UseGuards(AuthGuard("jwt"),PlatformCapabilitiesGuard)
export class PlatformStaffController {
 constructor(private readonly staff:PlatformStaffService,private readonly facilities:AdminFacilitiesService,private readonly bootstrapService:GovernanceBootstrapService,private readonly owner:PlatformOwnerControlService){}
 private actor(req:any){return String(req.user?.userId??"");} private parse<T>(schema:{safeParse(v:unknown):any},body:unknown):T{const p=schema.safeParse(body);if(!p.success)throw new BadRequestException(p.error.issues[0]?.message??"Invalid request");return p.data;}
 @Get("context") @RequirePlatformCapabilities([...PLATFORM_CAPABILITY_CODES],{mode:"ANY"}) context(@Req()req:any){return this.staff.getWorkspaceContext(this.actor(req));}
 @Get("governance-bootstrap") @RequirePlatformPrincipal() bootstrapStatus(@Req()req:any){return this.bootstrapService.status(this.actor(req));}
 @Post("governance-bootstrap") @RequirePlatformPrincipal() bootstrap(@Req()req:any,@Body()body:unknown){const d=this.parse<{targetUserId:string;reason:string;ticketReference:string}>(governanceBootstrapSchema,body);return this.bootstrapService.bootstrap({userId:this.actor(req),sessionId:String(req.user?.sessionId??"")},d);}
 @Get("facilities") @RequirePlatformCapabilities(["FACILITY_CREATE","FACILITY_CONFIGURE","FACILITY_ACTIVATE","FACILITY_HEALTH_VIEW"],{mode:"ANY"}) listFacilities(){return this.staff.listPlatformFacilities();}
 @Get("facilities/:id") @RequirePlatformCapabilities(["FACILITY_CREATE","FACILITY_CONFIGURE","FACILITY_ACTIVATE","FACILITY_HEALTH_VIEW"],{mode:"ANY"}) facility(@Param("id")id:string){return this.staff.getPlatformFacility(id);}
 @Post("facilities") @RequirePlatformCapabilities(["FACILITY_CREATE"],{requireRecentMfa:true}) createFacility(@Req()req:any,@Body()body:unknown){return this.facilities.createForPlatformCapability(this.parse<any>(createFacilityDtoSchema,body),this.actor(req));}
 @Get("facilities/:id/configuration") @RequirePlatformCapabilities(["FACILITY_CONFIGURE"],{requireRecentMfa:true}) async facilityConfiguration(@Req()req:any,@Param("id")id:string){const a=this.actor(req);const [facility,billingIdentity,billingWorkflow,departments]=await Promise.all([this.staff.getPlatformFacility(id),this.facilities.getBillingIdentityForPlatform(a,id),this.facilities.getBillingWorkflowForPlatform(a,id),this.facilities.listDepartmentsForPlatform(a,id)]);return{facility,billingIdentity,billingWorkflow,departments:departments.items};}
 @Patch("facilities/:id/language") @RequirePlatformCapabilities(["FACILITY_CONFIGURE"],{requireRecentMfa:true}) language(@Req()req:any,@Param("id")id:string,@Body()body:unknown){const d=this.parse<SetFacilityLanguageDto>(setFacilityLanguageDtoSchema,body);return this.facilities.setLanguageForPlatform(id,d.defaultLanguage,this.actor(req));}
 @Patch("facilities/:id/service-config") @RequirePlatformCapabilities(["FACILITY_CONFIGURE"],{requireRecentMfa:true}) serviceConfig(@Req()req:any,@Param("id")id:string,@Body()body:unknown){return this.facilities.updateServiceConfigForPlatform(id,this.parse<any>(updateFacilityServiceConfigDtoSchema,body),this.actor(req));}
 @Patch("facilities/:id/billing-identity") @RequirePlatformCapabilities(["FACILITY_CONFIGURE"],{requireRecentMfa:true}) billingIdentity(@Req()req:any,@Param("id")id:string,@Body()body:unknown){return this.facilities.updateBillingIdentityForPlatform(this.actor(req),id,this.parse<any>(facilityBillingIdentityPatchDtoSchema,body));}
 @Patch("facilities/:id/billing-workflow") @RequirePlatformCapabilities(["FACILITY_CONFIGURE"],{requireRecentMfa:true}) billingWorkflow(@Req()req:any,@Param("id")id:string,@Body()body:unknown){return this.facilities.updateBillingWorkflowForPlatform(this.actor(req),id,this.parse<any>(facilityBillingWorkflowPatchDtoSchema,body));}
 @Get("staff") @RequirePlatformCapabilities(["STAFF_VIEW"],{requireRecentMfa:true}) async listStaff(@Req()req:any){return this.owner.filterProtectedUsers(this.actor(req),await this.staff.listStaff());}
 @Get("eligible-users") @RequirePlatformCapabilities(["STAFF_PROVISION"],{requireRecentMfa:true}) async eligible(@Req()req:any,@Query("q")q?:string){return this.owner.filterProtectedUsers(this.actor(req),await this.staff.listEligibleUsers(q));}
 @Get("security/users") @RequirePlatformCapabilities(["SECURITY_MFA_RECOVERY"],{requireRecentMfa:true}) async securityUsers(@Req()req:any,@Query("q")q?:string){return this.owner.filterProtectedUsers(this.actor(req),await this.staff.listSecurityUsers(q));}
 @Get("staff/:id") @RequirePlatformCapabilities(["STAFF_VIEW"],{requireRecentMfa:true}) async getStaff(@Req()req:any,@Param("id")id:string){await this.owner.assertTargetVisibleTo(this.actor(req),id);return this.staff.getStaff(id);}
 @Get("capabilities") @RequirePlatformCapabilities(["STAFF_VIEW","STAFF_GRANT_CAPABILITIES"],{mode:"ANY",requireRecentMfa:true}) listCapabilities(){return this.staff.listCapabilities();}
 @Post("staff/:id/classification") @RequirePlatformPrincipal() async classify(@Req()req:any,@Param("id")id:string,@Body()body:unknown){await this.owner.assertTargetVisibleTo(this.actor(req),id);const d=this.parse<{reason:string}>(classifyStaffSchema,body);return this.staff.classify(this.actor(req),id,d.reason);}
 @Post("staff/:id/provision") @RequirePlatformCapabilities(["STAFF_PROVISION"],{requireRecentMfa:true}) async provision(@Req()req:any,@Param("id")id:string,@Body()body:unknown){await this.owner.assertTargetVisibleTo(this.actor(req),id);const d=this.parse<{persona:MedoraStaffPersonaCode;reason:string;ticketReference?:string}>(provisionStaffSchema,body);return this.staff.provision(this.actor(req),id,d.persona,d.reason,d.ticketReference);}
 @Post("staff/:id/activate") @RequirePlatformPrincipal() async activate(@Req()req:any,@Param("id")id:string,@Body()body:unknown){await this.owner.assertTargetVisibleTo(this.actor(req),id);const d=this.parse<{reason:string;ticketReference?:string}>(staffLifecycleSchema,body);return this.staff.activate(this.actor(req),id,d.reason,d.ticketReference);}
 @Post("staff/:id/deactivate") @RequirePlatformCapabilities(["STAFF_PROVISION"],{requireRecentMfa:true}) async deactivate(@Req()req:any,@Param("id")id:string,@Body()body:unknown){await this.owner.assertTargetVisibleTo(this.actor(req),id);const d=this.parse<{reason:string;ticketReference?:string}>(staffLifecycleSchema,body);return this.staff.deactivate(this.actor(req),id,d.reason,d.ticketReference);}
 @Post("staff/:id/persona") @RequirePlatformPrincipal() async persona(@Req()req:any,@Param("id")id:string,@Body()body:unknown){await this.owner.assertTargetVisibleTo(this.actor(req),id);const d=this.parse<{persona:MedoraStaffPersonaCode;reason:string;ticketReference?:string}>(changePersonaSchema,body);return this.staff.changePersona(this.actor(req),id,d.persona,d.reason,d.ticketReference);}
 @Post("staff/:id/capabilities") @RequirePlatformCapabilities(["STAFF_GRANT_CAPABILITIES"],{requireRecentMfa:true}) async grant(@Req()req:any,@Param("id")id:string,@Body()body:unknown){const a=this.actor(req);await this.owner.assertTargetVisibleTo(a,id);const d=this.parse<{code:PlatformCapabilityCode;reason:string;ticketReference?:string}>(grantCapabilitySchema,body);return (await this.owner.isOwner(a))?this.owner.directGrantAsOwner(a,id,d.code,d.reason,d.ticketReference):this.staff.grant(a,id,d.code,d.reason,d.ticketReference);}
 @Delete("staff/:id/capabilities/:code") @RequirePlatformCapabilities(["STAFF_REVOKE_CAPABILITIES"],{requireRecentMfa:true}) async revoke(@Req()req:any,@Param("id")id:string,@Param("code")code:PlatformCapabilityCode,@Body()body:unknown){const a=this.actor(req);await this.owner.assertTargetVisibleTo(a,id);const d=this.parse<{reason:string}>(revokeCapabilitySchema,body);return this.staff.revoke(a,id,code,d.reason);}
}
