export const PLATFORM_CAPABILITY_CODES = [
  "FACILITY_CREATE", "FACILITY_CONFIGURE", "FACILITY_ACTIVATE", "FACILITY_HEALTH_VIEW",
  "STAFF_VIEW", "STAFF_PROVISION", "STAFF_GRANT_CAPABILITIES", "STAFF_REVOKE_CAPABILITIES", "PRIVILEGED_ACTION_APPROVE",
  "SECURITY_ACCESS_VIEW", "SECURITY_MFA_RECOVERY", "SECURITY_PRIVILEGED_ACTIONS", "SECURITY_AUDIT_VIEW",
  "COMPLIANCE_AUDIT_VIEW", "COMPLIANCE_ROI_MONITOR", "COMPLIANCE_EXPORT_MONITOR", "COMPLIANCE_CONTROLS_MANAGE",
  "BILLING_RCM_VIEW", "BILLING_RCM_MANAGE", "CATALOG_CONFIG_VIEW", "CATALOG_CONFIG_MANAGE",
  "SYSTEM_HEALTH_VIEW", "SYSTEM_BACKUP_READINESS_VIEW", "SYSTEM_GOLIVE_MONITOR", "AUDIT_EXPORT",
  // Phase 18E — explicit, owner-selectable Technology / IT care-workspace authority.
  // These are never implied by department identity. Runtime authority still comes from
  // an active PlatformCapabilityGrant so the platform owner decides exactly what each
  // corporate IT employee may see/use.
  "IT_CARE_PATIENT_RECORDS", "IT_CARE_ORDERS", "IT_CARE_EMERGENCY", "IT_CARE_URGENT_CARE",
  "IT_CARE_CLINIC", "IT_CARE_OBSERVATION", "IT_CARE_INPATIENT_HOSPITAL", "IT_CARE_LABORATORY",
  "IT_CARE_RADIOLOGY", "IT_CARE_PHARMACY", "IT_CARE_DIGITAL_CARE", "IT_CARE_PATIENT_PORTAL",
  "IT_CARE_SCHEDULING", "IT_CARE_TELEMEDICINE", "IT_CARE_AI", "IT_CARE_BILLING",
] as const;
export type PlatformCapabilityCode = typeof PLATFORM_CAPABILITY_CODES[number];

export const MEDORA_STAFF_PERSONAS = ["IMPLEMENTATION", "SUPPORT", "BILLING_OPERATIONS", "COMPLIANCE_SECURITY", "PLATFORM_OPERATIONS"] as const;
export type MedoraStaffPersonaCode = typeof MEDORA_STAFF_PERSONAS[number];

/** Managed configuration only; these constants are never consulted by runtime authorization. */
export const PERSONA_CAPABILITY_TEMPLATES: Readonly<Record<MedoraStaffPersonaCode, readonly PlatformCapabilityCode[]>> = {
  IMPLEMENTATION: ["CATALOG_CONFIG_VIEW", "CATALOG_CONFIG_MANAGE", "FACILITY_CONFIGURE", "FACILITY_HEALTH_VIEW", "SYSTEM_GOLIVE_MONITOR", "SYSTEM_HEALTH_VIEW"],
  SUPPORT: ["FACILITY_HEALTH_VIEW", "STAFF_VIEW", "SYSTEM_HEALTH_VIEW"],
  BILLING_OPERATIONS: ["BILLING_RCM_VIEW"],
  COMPLIANCE_SECURITY: ["COMPLIANCE_AUDIT_VIEW", "COMPLIANCE_EXPORT_MONITOR", "COMPLIANCE_ROI_MONITOR", "SECURITY_ACCESS_VIEW", "SECURITY_AUDIT_VIEW"],
  PLATFORM_OPERATIONS: ["FACILITY_CONFIGURE", "FACILITY_HEALTH_VIEW", "SYSTEM_BACKUP_READINESS_VIEW", "SYSTEM_GOLIVE_MONITOR", "SYSTEM_HEALTH_VIEW"],
};
