import{BadRequestException,Controller,Get,Query,Req,UseGuards}from"@nestjs/common";import{AuthGuard}from"@nestjs/passport";import{AuditAction}from"@prisma/client";import{PlatformCapabilitiesGuard}from"./platform-capabilities.guard";import{RequirePlatformCapabilities}from"./platform-capabilities.decorator";import{SystemHealthService}from"../admin/system-health.service";import{BackupReadinessService}from"../admin/backup-readiness.service";import{GoLiveReadinessService}from"../admin/go-live-readiness.service";import{AdminComplianceService}from"../admin/admin-compliance.service";import{AdminExportMonitoringService}from"../admin/admin-export-monitoring.service";import{AdminBillingGovernanceService}from"../admin/admin-billing-governance.service";import{AdminCatalogAuditService}from"../admin/admin-catalog-audit.service";import{RevenueCycleClaimsService}from"../billing/revenue-cycle-claims.service";import{RevenueCyclePaymentsService}from"../billing/revenue-cycle-payments.service";import{PrismaService}from"../prisma/prisma.service";import{AuditService}from"../common/services/audit.service";import{hardenPlatformGoLive,hardenPlatformSystemHealth}from"./platform-production-readiness";
function facility(id?:string){if(!id?.trim())throw new BadRequestException("Explicit facilityId is required for this facility-scoped projection");return id.trim()}function bounded(raw?:string){const n=Number(raw??50);return Number.isFinite(n)?Math.min(100,Math.max(1,Math.trunc(n))):50}function envBool(name:string){const raw=process.env[name]?.trim().toLowerCase();return raw==="true"||raw==="1"||raw==="yes"}function billingMode(){const production=process.env.NODE_ENV?.trim().toLowerCase()==="production";const autoExportEnabled=envBool("MEDORA_EXTERNAL_BILLING_AUTO_EXPORT_ENABLED");const vendorWebhookConfigured=Boolean(process.env.MEDORA_EXTERNAL_BILLING_VENDOR_WEBHOOK_URL?.trim());const outboundConfigured=autoExportEnabled&&vendorWebhookConfigured;return{mode:outboundConfigured?"outbound_enabled":"preview_only",production,autoExportEnabled,vendorWebhookConfigured,outboundConfigured,canTransmitExternally:outboundConfigured,reason:outboundConfigured?"external_billing_configured":autoExportEnabled&&!vendorWebhookConfigured?"vendor_webhook_missing":"external_billing_automation_disabled"}}
@Controller("platform/operations")@UseGuards(AuthGuard("jwt"),PlatformCapabilitiesGuard)
export class PlatformOperationsController{constructor(private health:SystemHealthService,private backup:BackupReadinessService,private goLive:GoLiveReadinessService,private compliance:AdminComplianceService,private exports:AdminExportMonitoringService,private billing:AdminBillingGovernanceService,private catalog:AdminCatalogAuditService,private claims:RevenueCycleClaimsService,private payments:RevenueCyclePaymentsService,private prisma:PrismaService,private audit:AuditService){}
@Get("system-health")@RequirePlatformCapabilities(["SYSTEM_HEALTH_VIEW"])async system(@Query("facilityId")id?:string){const fid=facility(id);const[system,backup]=await Promise.all([this.health.getSnapshot(fid),Promise.resolve(this.backup.getSnapshot(fid))]);return hardenPlatformSystemHealth(system,backup)}
@Get("backup-readiness")@RequirePlatformCapabilities(["SYSTEM_BACKUP_READINESS_VIEW"])backups(@Query("facilityId")id?:string){return this.backup.getSnapshot(facility(id))}
@Get("go-live")@RequirePlatformCapabilities(["SYSTEM_GOLIVE_MONITOR"])async live(@Query("facilityId")id?:string){const fid=facility(id);const[goLive,system,backup]=await Promise.all([this.goLive.getSnapshot(fid),this.health.getSnapshot(fid),Promise.resolve(this.backup.getSnapshot(fid))]);return hardenPlatformGoLive(goLive,system,backup)}
@Get("compliance")@RequirePlatformCapabilities(["COMPLIANCE_CONTROLS_MANAGE","COMPLIANCE_AUDIT_VIEW"],{mode:"ANY"})controls(@Query("facilityId")id?:string){return this.compliance.getDashboard(facility(id))}
@Get("exports")@RequirePlatformCapabilities(["COMPLIANCE_EXPORT_MONITOR"])exportStatus(@Query("facilityId")id?:string){return this.exports.getExportMonitoring(facility(id),{filter:"all"})}
@Get("billing-mode")@RequirePlatformCapabilities(["BILLING_RCM_VIEW"])billingEnvironment(){return billingMode()}
@Get("billing")@RequirePlatformCapabilities(["BILLING_RCM_VIEW"])async billingStatus(@Req()req:any,@Query("facilityId")id?:string){const summary=await this.billing.getSummary({facilityId:facility(id)},{userId:req.user?.userId});return{mode:billingMode(),summary}}
@Get("claims")@RequirePlatformCapabilities(["BILLING_RCM_VIEW"])claimsStatus(@Query("facilityId")id?:string,@Query("limit")limit?:string){return this.claims.listRevenueCycleClaims({facilityId:facility(id),queue:"ALL",limit:bounded(limit)})}
@Get("payments")@RequirePlatformCapabilities(["BILLING_RCM_VIEW"])paymentsStatus(@Query("facilityId")id?:string,@Query("limit")limit?:string){return this.payments.listRevenueCyclePayments({facilityId:facility(id),queue:"ALL",limit:bounded(limit)})}
@Get("catalog-audit")@RequirePlatformCapabilities(["CATALOG_CONFIG_VIEW"])catalogStatus(@Query("facilityId")id?:string){return this.catalog.getDashboard(facility(id))}
@Get("roi")@RequirePlatformCapabilities(["COMPLIANCE_ROI_MONITOR"])
async roi(@Req()req:any){const[byStatus,byFacility]=await Promise.all([this.prisma.chartRoiRequest.groupBy({by:["status"],_count:{_all:true}}),this.prisma.chartRoiRequest.groupBy({by:["facilityId","status"],_count:{_all:true}})]);await this.audit.log(AuditAction.VIEW,"ROI_MONITORING_SUMMARY",{userId:req.user?.userId,entityId:"aggregate",metadata:{aggregate:true,rowCountByStatus:byStatus.length,rowCountByFacilityBucket:byFacility.length}});return{byStatus:byStatus.map(x=>({status:x.status,count:x._count._all})),byFacility:byFacility.map(x=>({facilityId:x.facilityId,status:x.status,count:x._count._all}))}}
}
