export const PLATFORM_CAPABILITY_CODES = [
  "FACILITY_CREATE", "FACILITY_CONFIGURE", "FACILITY_ACTIVATE", "FACILITY_HEALTH_VIEW",
  "STAFF_VIEW", "STAFF_PROVISION", "STAFF_GRANT_CAPABILITIES", "STAFF_REVOKE_CAPABILITIES",
  "SECURITY_ACCESS_VIEW", "SECURITY_MFA_RECOVERY", "SECURITY_PRIVILEGED_ACTIONS", "SECURITY_AUDIT_VIEW",
  "COMPLIANCE_AUDIT_VIEW", "COMPLIANCE_ROI_MONITOR", "COMPLIANCE_EXPORT_MONITOR", "COMPLIANCE_CONTROLS_MANAGE",
  "BILLING_RCM_VIEW", "BILLING_RCM_MANAGE", "CATALOG_CONFIG_VIEW", "CATALOG_CONFIG_MANAGE",
  "SYSTEM_HEALTH_VIEW", "SYSTEM_BACKUP_READINESS_VIEW", "SYSTEM_GOLIVE_MONITOR", "AUDIT_EXPORT",
] as const;
export type PlatformCapabilityCode = typeof PLATFORM_CAPABILITY_CODES[number];
