import { BadRequestException, Body, Controller, Get, NotFoundException, Param, Post, Query, Req, UseGuards } from "@nestjs/common";
import { AuthGuard } from "@nestjs/passport";import { PlatformCapabilitiesGuard } from "./platform-capabilities.guard";import { RequirePlatformCapabilities } from "./platform-capabilities.decorator";import { createPrivilegedActionSchema,decisionSchema,listPrivilegedActionsSchema } from "./dto/privileged-action.dto";import { PrivilegedActionService } from "./privileged-action.service";import { PlatformOwnerControlService } from "./platform-owner-control.service";
@Controller("platform/privileged-action-requests") @UseGuards(AuthGuard("jwt"),PlatformCapabilitiesGuard)
export class PrivilegedActionController{
 constructor(private readonly actions:PrivilegedActionService,private readonly owner:PlatformOwnerControlService){} private actor(req:any){return{userId:String(req.user?.userId??""),sessionId:String(req.user?.sessionId??"")};} private parse(s:any,v:unknown){const p=s.safeParse(v);if(!p.success)throw new BadRequestException(p.error.issues[0]?.message??"Invalid request");return p.data;}
 private async visible(actorId:string,id:string){const r:any=await this.actions.one(actorId,id);if(!(await this.owner.isOwner(actorId))&&((r.targetUserId&&await this.owner.isOwner(r.targetUserId))||await this.owner.isOwner(r.requesterUserId)))throw new NotFoundException("Privileged action request not found");return r;}
 @Post() @RequirePlatformCapabilities(["STAFF_PROVISION","STAFF_GRANT_CAPABILITIES","FACILITY_ACTIVATE","SECURITY_MFA_RECOVERY"],{mode:"ANY",requireRecentMfa:true}) async create(@Req()req:any,@Body()body:unknown){const a=this.actor(req),d:any=this.parse(createPrivilegedActionSchema,body);if(d.targetUserId)await this.owner.assertTargetVisibleTo(a.userId,d.targetUserId);return this.actions.create(a,d);}
 @Get() @RequirePlatformCapabilities(["STAFF_VIEW","FACILITY_ACTIVATE","SECURITY_MFA_RECOVERY","PRIVILEGED_ACTION_APPROVE"],{mode:"ANY",requireRecentMfa:true}) async list(@Req()req:any,@Query()query:unknown){const a=this.actor(req),q:any=this.parse(listPrivilegedActionsSchema,query),rows:any[]=await this.actions.list(a.userId,q.status,q.take);if(await this.owner.isOwner(a.userId))return rows;const out=[];for(const r of rows){if(r.targetUserId&&await this.owner.isOwner(r.targetUserId))continue;if(await this.owner.isOwner(r.requesterUserId))continue;out.push(r);}return out;}
 @Get(":id") @RequirePlatformCapabilities(["STAFF_VIEW","FACILITY_ACTIVATE","SECURITY_MFA_RECOVERY","PRIVILEGED_ACTION_APPROVE"],{mode:"ANY",requireRecentMfa:true}) async one(@Req()req:any,@Param("id")id:string){return this.visible(this.actor(req).userId,id);}
 @Post(":id/approve") @RequirePlatformCapabilities(["PRIVILEGED_ACTION_APPROVE"],{requireRecentMfa:true}) async approve(@Req()req:any,@Param("id")id:string){const a=this.actor(req);await this.visible(a.userId,id);return this.actions.approve(a,id);}
 @Post(":id/reject") @RequirePlatformCapabilities(["PRIVILEGED_ACTION_APPROVE"],{requireRecentMfa:true}) async reject(@Req()req:any,@Param("id")id:string,@Body()body:unknown){const a=this.actor(req);await this.visible(a.userId,id);return this.actions.reject(a,id,this.parse(decisionSchema,body).reason);}
 @Post(":id/cancel") @RequirePlatformCapabilities(["STAFF_PROVISION","STAFF_GRANT_CAPABILITIES","FACILITY_ACTIVATE","SECURITY_MFA_RECOVERY"],{mode:"ANY"}) async cancel(@Req()req:any,@Param("id")id:string,@Body()body:unknown){const a=this.actor(req);await this.visible(a.userId,id);return this.actions.cancel(a,id,this.parse(decisionSchema,body).reason);}
 @Post(":id/execute") @RequirePlatformCapabilities(["STAFF_PROVISION","STAFF_GRANT_CAPABILITIES","FACILITY_ACTIVATE","SECURITY_MFA_RECOVERY"],{mode:"ANY",requireRecentMfa:true}) async execute(@Req()req:any,@Param("id")id:string){const a=this.actor(req);await this.visible(a.userId,id);return this.actions.execute(a,id);}
}
