import { PlatformStaffService } from "./platform-staff.service";
import { PERSONA_CAPABILITY_TEMPLATES } from "./platform-capabilities";

const actorId="11111111-1111-4111-8111-111111111111",targetId="22222222-2222-4222-8222-222222222222";
function harness({principal=false,capability=true,actorActive=true,targetActive=true,existing=null as any}={}){
 const codes=[...PERSONA_CAPABILITY_TEMPLATES.SUPPORT];
 const tx:any={medoraStaffProfile:{create:jest.fn().mockResolvedValue({id:"profile",userId:targetId,persona:"SUPPORT",isActive:true})},platformCapability:{findMany:jest.fn().mockResolvedValue(codes.map((code,i)=>({id:`cap-${i}`,code,riskLevel:"HIGH"})))},platformCapabilityGrant:{findMany:jest.fn().mockResolvedValue([]),create:jest.fn().mockImplementation(({data})=>Promise.resolve({id:`grant-${data.capabilityId}` })),update:jest.fn()},medoraStaffLifecycleEvent:{create:jest.fn().mockResolvedValue({id:"event"})},auditLog:{create:jest.fn().mockResolvedValue({id:"audit"})}};
 const prisma:any={user:{findUnique:jest.fn().mockImplementation((args:any)=>{if(args.select?.canCreateFacilities)return Promise.resolve(principal?{id:actorId,isActive:actorActive,canCreateFacilities:true,userRoles:[{id:"root"}]}:{id:actorId,isActive:actorActive,canCreateFacilities:false,userRoles:[]});if(args.where.id===actorId)return Promise.resolve({isActive:actorActive,medoraStaffProfile:{isActive:actorActive},platformCapabilityGrants:capability?[{capability:{code:"STAFF_PROVISION"}}]:[]});return Promise.resolve(targetActive?{isActive:true}:{isActive:false})})},medoraStaffProfile:{findUnique:jest.fn().mockResolvedValue(existing)},$transaction:jest.fn().mockImplementation((fn:any)=>fn(tx)),privilegedActionRequest:{create:jest.fn()}};
 const audit:any={log:jest.fn().mockImplementation((_a:any,_e:any,input:any)=>input.tx.auditLog.create({data:{metadata:input.metadata}}))};
 return{service:new PlatformStaffService(prisma,audit),prisma,tx,audit,codes};
}
describe("D4SEC.1C.5C single-administrator staff provisioning",()=>{
 it.each([{name:"Platform Principal",options:{principal:true,capability:false}},{name:"STAFF_PROVISION holder",options:{principal:false,capability:true}}])("$name provisions directly and atomically",async({options})=>{const h=harness(options);const result=await h.service.provision(actorId,targetId,"SUPPORT","New support employee","SEC-42");expect(result).toEqual(expect.objectContaining({id:"profile",persona:"SUPPORT"}));expect(h.prisma.$transaction).toHaveBeenCalledTimes(1);expect(h.tx.medoraStaffProfile.create).toHaveBeenCalledWith({data:expect.objectContaining({userId:targetId,persona:"SUPPORT",classifiedByUserId:actorId})});expect(h.tx.platformCapabilityGrant.create).toHaveBeenCalledTimes(h.codes.length);expect(h.tx.medoraStaffLifecycleEvent.create).toHaveBeenCalledWith({data:expect.objectContaining({staffProfileId:"profile",actorUserId:actorId,eventType:"PROVISION",reason:"New support employee",ticketReference:"SEC-42"})});expect(h.audit.log).toHaveBeenCalledTimes(1);expect(h.audit.log.mock.calls[0][2].metadata).toEqual(expect.objectContaining({event:"STAFF_PROVISIONED",targetUserId:targetId,newPersona:"SUPPORT",capabilitiesAdded:h.codes.sort(),reason:"New support employee",ticketReference:"SEC-42",result:"SUCCESS"}));expect(h.prisma.privilegedActionRequest.create).not.toHaveBeenCalled()});
 it("fails closed without STAFF_PROVISION",async()=>{const h=harness({capability:false});await expect(h.service.provision(actorId,targetId,"SUPPORT","reason")).rejects.toThrow("Required platform capability missing");expect(h.prisma.$transaction).not.toHaveBeenCalled()});
 it("rejects inactive administrators",async()=>{const h=harness({actorActive:false});await expect(h.service.provision(actorId,targetId,"SUPPORT","reason")).rejects.toThrow("Required platform capability missing")});
 it("rejects inactive targets and duplicate profiles",async()=>{const inactive=harness({targetActive:false});await expect(inactive.service.provision(actorId,targetId,"SUPPORT","reason")).rejects.toThrow("STAFF_TARGET_INACTIVE");const duplicate=harness({existing:{id:"existing",persona:"SUPPORT",isActive:true}});await expect(duplicate.service.provision(actorId,targetId,"SUPPORT","reason")).rejects.toThrow("STAFF_ALREADY_PROVISIONED")});
 it("rolls back the profile when critical audit evidence fails",async()=>{const h=harness();h.audit.log.mockRejectedValue(new Error("AUDIT_WRITE_FAILED"));await expect(h.service.provision(actorId,targetId,"SUPPORT","reason")).rejects.toThrow("AUDIT_WRITE_FAILED");expect(h.prisma.$transaction).toHaveBeenCalledTimes(1)});
});
