/**
 * Phase 1 clinical templates and dropdown options (static, French).
 * Lightweight config for faster documentation; no admin template builder.
 *
 * Deferred for later: backend-seeded reference data, admin UI to edit templates,
 * full template engine (variables, conditional sections), facility-specific lists.
 */

/** Common visit reasons for dropdown / quick select (motif de visite). */
export const COMMON_VISIT_REASONS = [
  "Fièvre",
  "Toux / infection respiratoire",
  "Douleur abdominale",
  "Diarrhée / gastro-entérite",
  "Plaie / traumatisme",
  "Maux de tête",
  "Douleur thoracique",
  "Contrôle / suivi",
  "Vaccination",
  "Renouvellement ordonnance",
  "Pansement / soins plaie",
  "Examen de santé",
  "Autre",
] as const;

/** Common diagnoses for dropdown (code + French label). CIM-10–style codes. */
export const COMMON_DIAGNOSES: Array<{ code: string; label: string }> = [
  { code: "J06.9", label: "Infection aiguë des voies respiratoires, sans précision" },
  { code: "J00", label: "Rhinopharyngite aiguë [rhume banal]" },
  { code: "J02.9", label: "Pharyngite aiguë, sans précision" },
  { code: "J03.9", label: "Amygdalite aiguë, sans précision" },
  { code: "K59.1", label: "Diarrhée fonctionnelle" },
  { code: "A09", label: "Diarrhée et gastro-entérite d'origine présumée infectieuse" },
  { code: "R50.9", label: "Fièvre, sans précision" },
  { code: "R10.4", label: "Douleurs abdominales, autres et sans précision" },
  { code: "R51", label: "Céphalée" },
  { code: "I10", label: "Hypertension essentielle (primitive)" },
  { code: "E11.9", label: "Diabète sucré de type 2, sans complication" },
  { code: "B34.9", label: "Infection virale, sans précision" },
  { code: "L08.9", label: "Infection locale de la peau et du tissu sous-cutané, sans précision" },
  { code: "S01.9", label: "Plaie ouverte de la tête, partie non précisée" },
  { code: "W54.0XXA", label: "Morsure de chien, rencontre initiale" },
  { code: "W55.01XA", label: "Morsure de chat, rencontre initiale" },
  { code: "W50.3XXA", label: "Morsure humaine accidentelle, rencontre initiale" },
  { code: "W55.81XA", label: "Morsure par autre mammifère, rencontre initiale" },
  { code: "S61.459A", label: "Morsure ouverte du doigt, non précisé, rencontre initiale" },
  { code: "S52.531A", label: "Fracture de Colles du radius droit, fermée, rencontre initiale" },
  { code: "S72.001A", label: "Fracture du col du fémur droit, fermée, rencontre initiale" },
  { code: "S02.3XXA", label: "Fracture du plancher orbitaire, fermée, rencontre initiale" },
  { code: "S32.010A", label: "Fracture-compression L1, fermée, rencontre initiale" },
  { code: "S82.201B", label: "Fracture ouverte du tibia droit, rencontre initiale" },
  { code: "S42.001A", label: "Fracture de la clavicule droite, fermée, rencontre initiale" },
  { code: "S22.32XA", label: "Fracture d'une côte droite, fermée, rencontre initiale" },
  { code: "S62.351A", label: "Fracture métacarpienne main droite, fermée, rencontre initiale" },
  { code: "S82.66XA", label: "Fracture malléolaire latérale droite, fermée, rencontre initiale" },
  { code: "M84.351A", label: "Fracture de stress de la hanche droite, rencontre initiale" },
  { code: "S52.121A", label: "Fracture en bois vert du radius droit, fermée, rencontre initiale" },
  { code: "S43.001A", label: "Luxation antérieure de l'épaule droite, rencontre initiale" },
  { code: "S53.031A", label: "Poignet de bonne (coude droit), rencontre initiale" },
  { code: "S73.001A", label: "Luxation de la hanche droite, rencontre initiale" },
  { code: "S83.001A", label: "Luxation de la rotule droite, rencontre initiale" },
  { code: "S03.0XXA", label: "Luxation de la mâchoire, rencontre initiale" },
  { code: "S93.401A", label: "Entorse de la cheville droite, rencontre initiale" },
  { code: "S63.501A", label: "Entorse du poignet droit, rencontre initiale" },
  { code: "S83.90XA", label: "Entorse du genou droit, rencontre initiale" },
  { code: "S16.1XXA", label: "Élongation musculaire au niveau du cou, rencontre initiale" },
  { code: "S39.012A", label: "Élongation des muscles du bas du dos, rencontre initiale" },
  { code: "S43.401A", label: "Entorse de l'épaule droite, rencontre initiale" },
  { code: "S76.311A", label: "Élongation des ischio-jambiers droits, rencontre initiale" },
  { code: "S46.011A", label: "Lésion tendineuse de la coiffe des rotateurs droite, rencontre initiale" },
  { code: "S86.011A", label: "Lésion du tendon d'Achille droit, rencontre initiale" },
  { code: "S66.321A", label: "Lacération du tendon extenseur du doigt droit, rencontre initiale" },
  { code: "S76.111A", label: "Lésion du tendon du quadriceps droit, rencontre initiale" },
  { code: "S83.511A", label: "Entorse du LCA du genou droit, rencontre initiale" },
  { code: "S83.411A", label: "Entorse du LCM du genou droit, rencontre initiale" },
  { code: "S93.431A", label: "Entorse de la syndesmose (cheville droite), rencontre initiale" },
  { code: "S63.641A", label: "Entorse LCU du pouce droit (pouce du skieur), rencontre initiale" },
  { code: "S67.21XA", label: "Écrasement de la main droite, rencontre initiale" },
  { code: "S68.110A", label: "Amputation traumatique du doigt (index droit), rencontre initiale" },
  { code: "S98.111A", label: "Amputation traumatique du gros orteil droit, rencontre initiale" },
  { code: "T15.00XA", label: "Corps étranger de la cornée, rencontre initiale" },
  { code: "S61.441A", label: "Plaie avec corps étranger de la main droite, rencontre initiale" },
  { code: "T20.10XA", label: "Brûlure du premier degré de la tête, du visage et du cou, partie non précisée, rencontre initiale" },
  { code: "T23.201A", label: "Brûlure du deuxième degré de la main non précisée, rencontre initiale" },
  { code: "T27.0XXA", label: "Brûlure du larynx et de la trachée, rencontre initiale" },
  { code: "T75.4XXA", label: "Électrocution, rencontre initiale" },
  { code: "T33.011A", label: "Gelure superficielle du doigt, rencontre initiale" },
  { code: "L55.9", label: "Coup de soleil, sans précision" },
  { code: "S21.301A", label: "Plaie pénétrante de la paroi antérieure du thorax, rencontre initiale" },
  { code: "S31.601A", label: "Plaie pénétrante de la paroi abdominale, rencontre initiale" },
  { code: "S61.239A", label: "Plaie punctiforme d'un doigt, sans corps étranger, rencontre initiale" },
  { code: "S05.50XA", label: "Plaie pénétrante de l'œil, sans corps étranger, rencontre initiale" },
  { code: "S91.339A", label: "Plaie punctiforme du pied, sans corps étranger, rencontre initiale" },
  { code: "S11.93XA", label: "Plaie ouverte du cou, rencontre initiale" },
  { code: "Z23", label: "Besoin de vaccination contre une maladie bactérienne" },
  { code: "Z00.0", label: "Examen médical général de suivi" },
];

/** Quick-insert snippets for nursing / general consultation notes (Notes de consultation). */
export const COMMON_NOTE_SNIPPETS = [
  "Patient vu en consultation. Pas d'alerte.",
  "Constantes dans les normes. Pas de fièvre.",
  "Pansement effectué. Plaie propre.",
  "Conseils hygiéno-diététiques donnés.",
  "Patient orienté vers médecin / spécialiste.",
  "Ordonnance expliquée au patient.",
  "Rendez-vous de suivi fixé.",
  "Refus de soins noté.",
  "Traduction / accompagnant assuré.",
  "Patient non présent au rendez-vous.",
];

/** Quick-insert snippets for clinician impression (Impression clinique). */
export const PROVIDER_IMPRESSION_SNIPPETS = [
  "Examen clinique rassurant.",
  "Pas de signe de gravité.",
  "Diagnostic de présomption : infection virale banale.",
  "Symptomatologie en faveur d'une origine infectieuse.",
  "Bilan à compléter selon évolution.",
  "Patient stable. Pas d'orientation hospitalière.",
  "Contexte fébrile / douleur maîtrisé.",
  "Examen cardiopulmonaire sans particularité.",
  "Abdomen souple, non douloureux.",
];

/** Quick-insert snippets for treatment plan (Plan de traitement). */
export const PROVIDER_PLAN_SNIPPETS = [
  "Traitement symptomatique. Repos. Hydratation.",
  "Antibiothérapie si pas d'amélioration sous 48–72 h.",
  "Contrôle des constantes à domicile.",
  "Reconsulter si aggravation (fièvre persistante, difficultés respiratoires).",
  "Suivi en soins primaires.",
  "Examens complémentaires demandés (NFS, CRP si besoin).",
  "Éducation du patient sur signes d'alerte.",
  "Arrêt de travail / arrêt scolaire si indiqué.",
];
