/**
 * Phase 1 clinical templates and dropdown options (static, French).
 * Lightweight config for faster documentation; no admin template builder.
 *
 * Deferred for later: backend-seeded reference data, admin UI to edit templates,
 * full template engine (variables, conditional sections), facility-specific lists.
 */

/** Common visit reasons for dropdown / quick select (motif de visite). */
export const COMMON_VISIT_REASONS = [
  "Fièvre",
  "Toux / infection respiratoire",
  "Douleur abdominale",
  "Diarrhée / gastro-entérite",
  "Plaie / traumatisme",
  "Maux de tête",
  "Douleur thoracique",
  "Contrôle / suivi",
  "Vaccination",
  "Renouvellement ordonnance",
  "Pansement / soins plaie",
  "Examen de santé",
  "Autre",
] as const;

/** Common diagnoses for dropdown (code + French label). CIM-10–style codes. */
export const COMMON_DIAGNOSES: Array<{ code: string; label: string }> = [
  { code: "J06.9", label: "Infection aiguë des voies respiratoires, sans précision" },
  { code: "J00", label: "Rhinopharyngite aiguë [rhume banal]" },
  { code: "J02.9", label: "Pharyngite aiguë, sans précision" },
  { code: "J03.9", label: "Amygdalite aiguë, sans précision" },
  { code: "K59.1", label: "Diarrhée fonctionnelle" },
  { code: "A09", label: "Diarrhée et gastro-entérite d'origine présumée infectieuse" },
  { code: "R50.9", label: "Fièvre, sans précision" },
  { code: "R10.4", label: "Douleurs abdominales, autres et sans précision" },
  { code: "R51", label: "Céphalée" },
  { code: "I10", label: "Hypertension essentielle (primitive)" },
  { code: "E11.9", label: "Diabète sucré de type 2, sans complication" },
  { code: "B34.9", label: "Infection virale, sans précision" },
  { code: "L08.9", label: "Infection locale de la peau et du tissu sous-cutané, sans précision" },
  { code: "T07.XXXA", label: "Blessures multiples, sans précision, rencontre initiale" },
  { code: "T79.4XXA", label: "Choc traumatique, rencontre initiale" },
  { code: "S09.20XA", label: "Rupture traumatique du tympan, sans précision, rencontre initiale" },
  { code: "T70.0XXA", label: "Barotraumatisme otitique, rencontre initiale" },
  { code: "W40.0XXA", label: "Explosion de matériel de dynamitage, rencontre initiale" },
  { code: "W39.XXXA", label: "Décharge de feu d'artifice, rencontre initiale" },
  { code: "T71.21XA", label: "Asphyxie due à un ensevelissement, rencontre initiale" },
  { code: "S01.9", label: "Plaie ouverte de la tête, partie non précisée" },
  { code: "W54.0XXA", label: "Morsure de chien, rencontre initiale" },
  { code: "W55.01XA", label: "Morsure de chat, rencontre initiale" },
  { code: "W50.3XXA", label: "Morsure humaine accidentelle, rencontre initiale" },
  { code: "Y04.1XXA", label: "Agression par morsure humaine, rencontre initiale" },
  { code: "W55.81XA", label: "Morsure par autre mammifère, rencontre initiale" },
  { code: "S61.459A", label: "Morsure ouverte du doigt / fight bite, rencontre initiale" },
  { code: "L03.119", label: "Cellulite de membre supérieur, sans précision" },
  { code: "L03.90", label: "Cellulite, sans précision" },
  { code: "L03.115", label: "Cellulite du membre inférieur droit" },
  { code: "L02.91", label: "Abcès cutané, sans précision" },
  { code: "L03.011", label: "Cellulite du doigt droit (panaris / paronychie)" },
  { code: "L05.01", label: "Kyste pilonidal avec abcès" },
  { code: "T81.41XA", label: "Infection du site opératoire, rencontre initiale" },
  { code: "T81.31XA", label: "Déhiscence de plaie opératoire, rencontre initiale" },
  { code: "M72.6", label: "Fasciite nécrosante" },
  { code: "M65.141", label: "Ténosynovite infectieuse des fléchisseurs, main droite" },
  { code: "M71.10", label: "Bursite infectieuse, site non précisé" },
  { code: "E11.621", label: "Diabète de type 2 avec ulcère du pied" },
  { code: "A46", label: "Érysipèle" },
  { code: "L73.2", label: "Hidrosadénite suppurée" },
  { code: "S52.531A", label: "Fracture de Colles du radius droit, fermée, rencontre initiale" },
  { code: "S72.001A", label: "Fracture du col du fémur droit, fermée, rencontre initiale" },
  { code: "S02.3XXA", label: "Fracture du plancher orbitaire, fermée, rencontre initiale" },
  { code: "S06.0X0A", label: "Commotion cérébrale (traumatisme crânien léger), rencontre initiale" },
  { code: "S06.4X0A", label: "Hématome épidural traumatique, rencontre initiale" },
  { code: "S06.5X0A", label: "Hématome sous-dural traumatique, rencontre initiale" },
  { code: "S02.0XXA", label: "Fracture du crâne (voûte), fermée, rencontre initiale" },
  { code: "S02.101A", label: "Fracture de la base du crâne, côté droit, rencontre initiale" },
  { code: "S02.2XXA", label: "Fracture des os du nez, fermée, rencontre initiale" },
  { code: "S02.40XA", label: "Fracture faciale (malaire / zygomatique), fermée, rencontre initiale" },
  { code: "S02.600A", label: "Fracture de la mandibule, fermée, rencontre initiale" },
  { code: "S02.411A", label: "Fracture de Le Fort I (maxillaire), fermée, rencontre initiale" },
  { code: "S02.5XXA", label: "Fracture dentaire traumatique, rencontre initiale" },
  { code: "S03.2XXA", label: "Luxation dentaire (dent avulsée), rencontre initiale" },
  { code: "S32.010A", label: "Fracture-compression L1, fermée, rencontre initiale" },
  { code: "S82.201B", label: "Fracture ouverte du tibia droit, rencontre initiale" },
  { code: "S42.001A", label: "Fracture de la clavicule droite, fermée, rencontre initiale" },
  { code: "S22.32XA", label: "Fracture d'une côte droite, fermée, rencontre initiale" },
  { code: "S62.351A", label: "Fracture métacarpienne main droite, fermée, rencontre initiale" },
  { code: "S82.66XA", label: "Fracture malléolaire latérale droite, fermée, rencontre initiale" },
  { code: "M84.351A", label: "Fracture de stress de la hanche droite, rencontre initiale" },
  { code: "S52.121A", label: "Fracture en bois vert du radius droit, fermée, rencontre initiale" },
  { code: "S43.001A", label: "Luxation antérieure de l'épaule droite, rencontre initiale" },
  { code: "S53.031A", label: "Poignet de bonne (coude droit), rencontre initiale" },
  { code: "S73.001A", label: "Luxation de la hanche droite, rencontre initiale" },
  { code: "S83.001A", label: "Luxation de la rotule droite, rencontre initiale" },
  { code: "S03.0XXA", label: "Luxation de la mâchoire, rencontre initiale" },
  { code: "S93.401A", label: "Entorse de la cheville droite, rencontre initiale" },
  { code: "S63.501A", label: "Entorse du poignet droit, rencontre initiale" },
  { code: "S83.90XA", label: "Entorse du genou droit, rencontre initiale" },
  { code: "S16.1XXA", label: "Élongation musculaire au niveau du cou, rencontre initiale" },
  { code: "S39.012A", label: "Élongation des muscles du bas du dos, rencontre initiale" },
  { code: "S43.401A", label: "Entorse de l'épaule droite, rencontre initiale" },
  { code: "S76.311A", label: "Élongation des ischio-jambiers droits, rencontre initiale" },
  { code: "S46.011A", label: "Lésion tendineuse de la coiffe des rotateurs droite, rencontre initiale" },
  { code: "S86.011A", label: "Lésion du tendon d'Achille droit, rencontre initiale" },
  { code: "S66.321A", label: "Lacération du tendon extenseur du doigt droit, rencontre initiale" },
  { code: "S76.111A", label: "Lésion du tendon du quadriceps droit, rencontre initiale" },
  { code: "S83.511A", label: "Entorse du LCA du genou droit, rencontre initiale" },
  { code: "S83.411A", label: "Entorse du LCM du genou droit, rencontre initiale" },
  { code: "S93.431A", label: "Entorse de la syndesmose (cheville droite), rencontre initiale" },
  { code: "S63.641A", label: "Entorse LCU du pouce droit (pouce du skieur), rencontre initiale" },
  { code: "S67.21XA", label: "Écrasement de la main droite, rencontre initiale" },
  { code: "S68.110A", label: "Amputation traumatique du doigt (index droit), rencontre initiale" },
  { code: "S98.111A", label: "Amputation traumatique du gros orteil droit, rencontre initiale" },
  { code: "T15.00XA", label: "Corps étranger de la cornée, rencontre initiale" },
  { code: "S61.441A", label: "Plaie avec corps étranger de la main droite, rencontre initiale" },
  { code: "T20.10XA", label: "Brûlure du premier degré de la tête, du visage et du cou, partie non précisée, rencontre initiale" },
  { code: "T23.201A", label: "Brûlure du deuxième degré de la main non précisée, rencontre initiale" },
  { code: "T27.0XXA", label: "Brûlure du larynx et de la trachée, rencontre initiale" },
  { code: "T75.4XXA", label: "Électrocution, rencontre initiale" },
  { code: "T33.011A", label: "Gelure superficielle du doigt, rencontre initiale" },
  { code: "L55.9", label: "Coup de soleil, sans précision" },
  { code: "S21.301A", label: "Plaie pénétrante de la paroi antérieure du thorax, rencontre initiale" },
  { code: "S31.601A", label: "Plaie pénétrante de la paroi abdominale, rencontre initiale" },
  { code: "S61.239A", label: "Plaie punctiforme d'un doigt, sans corps étranger, rencontre initiale" },
  { code: "S05.50XA", label: "Plaie pénétrante de l'œil, sans corps étranger, rencontre initiale" },
  { code: "S05.00XA", label: "Abrasion cornéenne et lésion conjonctivale, sans corps étranger, rencontre initiale" },
  { code: "H16.001", label: "Ulcère cornéen non précisé, œil droit" },
  { code: "T26.60XA", label: "Brûlure chimique de la cornée et du sac conjonctival, rencontre initiale" },
  { code: "H16.139", label: "Photokératite (coup de soleil oculaire), œil non précisé" },
  { code: "S05.20XA", label: "Plaie oculaire ouverte avec perte de tissu intraoculaire (globe ouvert), rencontre initiale" },
  { code: "H21.00", label: "Hyphéma, œil non précisé" },
  { code: "H40.219", label: "Glaucome aigu par fermeture de l'angle, œil non précisé" },
  { code: "H33.001", label: "Décollement de la rétine avec déchirure rétinienne, œil droit" },
  { code: "H43.10", label: "Hémorragie du vitré, œil non précisé" },
  { code: "H34.11", label: "Occlusion de l'artère centrale de la rétine, œil droit" },
  { code: "H05.011", label: "Cellulite orbitaire droite" },
  { code: "L03.213", label: "Cellulite préseptale (périorbitaire)" },
  { code: "H20.00", label: "Iridocyclite (uvéite antérieure) aiguë, sans précision" },
  { code: "H15.001", label: "Sclérite non précisée, œil droit" },
  { code: "S91.339A", label: "Plaie punctiforme du pied, sans corps étranger, rencontre initiale" },
  { code: "S11.93XA", label: "Plaie ouverte du cou, rencontre initiale" },
  { code: "M54.5", label: "Lombalgie" },
  { code: "M54.2", label: "Cervicalgie" },
  { code: "S23.3XXA", label: "Entorse des ligaments du rachis thoracique, rencontre initiale" },
  { code: "M54.12", label: "Radiculopathie cervicale" },
  { code: "M54.16", label: "Radiculopathie lombaire" },
  { code: "M54.3", label: "Sciatique" },
  { code: "M51.26", label: "Hernie discale lombaire (déplacement discal)" },
  { code: "G83.4", label: "Syndrome de la queue de cheval" },
  { code: "G06.1", label: "Abcès et granulome intrarachidiens" },
  { code: "S12.000A", label: "Fracture de la première vertèbre cervicale, rencontre initiale" },
  { code: "S22.000A", label: "Fracture-compression d’une vertèbre thoracique, rencontre initiale" },
  { code: "S32.000A", label: "Fracture d’une vertèbre lombaire, rencontre initiale" },
  { code: "S14.109A", label: "Lésion médullaire cervicale non précisée, rencontre initiale" },
  { code: "S14.121A", label: "Syndrome centromédullaire en C1, rencontre initiale" },
  { code: "Z23", label: "Besoin de vaccination contre une maladie bactérienne" },
  { code: "Z00.0", label: "Examen médical général de suivi" },
  { code: "H60.339", label: "Otite externe infectieuse (oreille du baigneur), oreille non précisée" },
  { code: "H60.20", label: "Otite externe maligne (nécrosante), oreille non précisée" },
  { code: "H66.90", label: "Otite moyenne, sans précision" },
  { code: "H70.90", label: "Mastoïdite, sans précision" },
  { code: "H72.90", label: "Perforation de la membrane tympanique, sans précision" },
  { code: "H91.20", label: "Surdité soudaine idiopathique, oreille non précisée" },
  { code: "H81.10", label: "Vertige positionnel paroxystique bénin, oreille non précisée" },
  { code: "H81.20", label: "Névrite vestibulaire, oreille non précisée" },
  { code: "H83.01", label: "Labyrinthite, oreille droite" },
  { code: "G51.0", label: "Paralysie de Bell" },
  { code: "R04.0", label: "Épistaxis" },
  { code: "T17.1XXA", label: "Corps étranger dans la narine, rencontre initiale" },
  { code: "J36", label: "Abcès périamygdalien" },
  { code: "J39.0", label: "Abcès rétropharyngé et parapharyngé" },
  { code: "K12.2", label: "Cellulite et abcès de la bouche (angine de Ludwig)" },
  { code: "J05.10", label: "Épiglottite aiguë, sans obstruction" },
  { code: "K11.20", label: "Sialadénite, sans précision" },
  // Phase 14 — dermatologie (voir aussi L73.2 hidrosadénite suppurée ci-dessus)
  { code: "L23.9", label: "Dermatite de contact allergique, sans précision" },
  { code: "L24.9", label: "Dermatite de contact irritative, sans précision" },
  { code: "L20.9", label: "Dermatite atopique, sans précision" },
  { code: "L50.9", label: "Urticaire, sans précision" },
  { code: "L40.9", label: "Psoriasis, sans précision" },
  { code: "L01.00", label: "Impétigo, sans précision" },
  { code: "L73.9", label: "Folliculite, sans précision" },
  { code: "B00.9", label: "Infection herpétique (herpès simplex), sans précision" },
  { code: "B02.9", label: "Zona sans complication" },
  { code: "L42", label: "Pityriasis rosé" },
  { code: "B35.4", label: "Teigne du corps (tinea corporis)" },
  { code: "B35.0", label: "Teigne du cuir chevelu (tinea capitis)" },
  { code: "B35.6", label: "Intertrigo inguinal dermatophytique (tinea cruris)" },
  { code: "B35.3", label: "Pied d'athlète (tinea pedis)" },
  { code: "B86", label: "Gale (scabiose)" },
  { code: "B08.1", label: "Molluscum contagiosum" },
  { code: "B09", label: "Éruption virale, sans précision" },
  { code: "L51.9", label: "Érythème polymorphe, sans précision" },
  { code: "L27.0", label: "Éruption cutanée généralisée d'origine médicamenteuse" },
  { code: "L51.1", label: "Syndrome de Stevens-Johnson" },
  { code: "L51.2", label: "Nécrolyse épidermique toxique (syndrome de Lyell)" },
  { code: "D72.12", label: "Syndrome DRESS (réaction médicamenteuse avec éosinophilie)" },
  { code: "L95.9", label: "Vascularite cutanée, sans précision" },
  { code: "D48.5", label: "Lésion cutanée pigmentée suspecte (comportement incertain)" },
  // Phase 15 — urgences environnementales / exposition
  { code: "T67.5XXA", label: "Épuisement par la chaleur, sans précision, rencontre initiale" },
  { code: "T67.01XA", label: "Coup de chaleur et insolation, rencontre initiale" },
  { code: "T67.02XA", label: "Coup de chaleur d'effort, rencontre initiale" },
  { code: "T68.XXXA", label: "Hypothermie, rencontre initiale" },
  { code: "T33.90XA", label: "Gelure superficielle de siège non précisé, rencontre initiale" },
  { code: "T69.1XXA", label: "Engelures, rencontre initiale" },
  { code: "T69.029A", label: "Pied d'immersion, pied non précisé, rencontre initiale" },
  { code: "T75.1XXA", label: "Effets d'une noyade et d'une submersion non mortelle, rencontre initiale" },
  // T75.4XXA électrocution already present in burn/electrical quick picks — do not duplicate.
  { code: "T75.00XA", label: "Effets de la foudre, sans précision, rencontre initiale" },
  { code: "T70.20XA", label: "Effets de la haute altitude, sans précision, rencontre initiale" },
  { code: "T70.29XA", label: "Autres effets de la haute altitude, rencontre initiale" },
  { code: "T70.3XXA", label: "Maladie des caissons (maladie de décompression), rencontre initiale" },
  { code: "T70.8XXA", label: "Autres effets de la pression de l'air et de l'eau, rencontre initiale" },
  { code: "T66.XXXA", label: "Maladie des rayons, sans précision, rencontre initiale" },
  // Phase 16 — toxicologie / envenimation
  { code: "T39.1X1A", label: "Intoxication par dérivés du 4-aminophénol (paracétamol), accidentelle, rencontre initiale" },
  { code: "T39.091A", label: "Intoxication par salicylates, accidentelle, rencontre initiale" },
  { code: "T40.2X1A", label: "Intoxication par autres opioïdes, accidentelle, rencontre initiale" },
  { code: "T42.4X1A", label: "Intoxication par benzodiazépines, accidentelle, rencontre initiale" },
  { code: "F10.129", label: "Intoxication alcoolique avec trouble de l'usage de l'alcool, sans précision" },
  { code: "F10.239", label: "Sevrage alcoolique avec trouble de l'usage de l'alcool, sans précision" },
  { code: "F14.129", label: "Intoxication à la cocaïne avec trouble de l'usage, sans précision" },
  { code: "F15.129", label: "Intoxication aux stimulants avec trouble de l'usage, sans précision" },
  { code: "G90.81", label: "Syndrome sérotoninergique" },
  { code: "G21.0", label: "Syndrome malin des neuroleptiques" },
  { code: "T60.0X1A", label: "Effet toxique des insecticides organophosphorés et carbamates, accidentel, rencontre initiale" },
  { code: "T44.7X1A", label: "Intoxication par bêta-bloquants, accidentelle, rencontre initiale" },
  { code: "T46.1X1A", label: "Intoxication par inhibiteurs calciques, accidentelle, rencontre initiale" },
  { code: "T46.0X1A", label: "Intoxication par glucosides cardiotoniques et médicaments d'action similaire, accidentelle, rencontre initiale" },
  { code: "T56.891A", label: "Effet toxique d'autres métaux (dont lithium), accidentel, rencontre initiale" },
  { code: "T58.91XA", label: "Effet toxique du monoxyde de carbone de source non précisée, accidentel, rencontre initiale" },
  { code: "T54.91XA", label: "Effet toxique de substance corrosive non précisée, accidentel, rencontre initiale" },
  { code: "T50.901A", label: "Intoxication par substances médicamenteuses non précisées, accidentelle, rencontre initiale" },
  { code: "T50.902A", label: "Intoxication par substances médicamenteuses non précisées, automutilation intentionnelle, rencontre initiale" },
  { code: "T63.001A", label: "Effet toxique du venin de serpent non précisé, accidentel, rencontre initiale" },
  // Phase 17 — OB/GYN / urologie (Part 40 quick picks)
  { code: "O02.81", label: "Grossesse de localisation inconnue" },
  { code: "O20.0", label: "Menace d'avortement" },
  { code: "O20.9", label: "Hémorragie du début de grossesse, sans précision" },
  { code: "O03.9", label: "Avortement spontané, sans précision" },
  { code: "O00.90", label: "Grossesse ectopique, sans précision" },
  { code: "O21.9", label: "Vomissements excessifs en début de grossesse, sans précision" },
  { code: "O26.899", label: "Autre affection liée à la grossesse, sans précision" },
  { code: "O44.10", label: "Placenta praevia sans saignement, premier trimestre" },
  { code: "O47.0", label: "Fausse couche de travail avant 37 semaines d'aménorrhée" },
  { code: "O60.10", label: "Travail prématuré, premier trimestre" },
  { code: "O42.9", label: "Rupture prématurée des membranes, sans précision" },
  { code: "O14.00", label: "Prééclampsie modérée, premier trimestre" },
  { code: "O72.1", label: "Hémorragie post-partum immédiate" },
  { code: "O86.12", label: "Endométrite après accouchement" },
  { code: "O90.3", label: "Hypertension post-partum" },
  { code: "N83.202", label: "Kyste ovarien non précisé, côté gauche" },
  { code: "N83.511", label: "Torsion de l'ovaire et du ligament large" },
  { code: "N73.9", label: "Maladie pelvienne inflammatoire de la femme, sans précision" },
  { code: "N70.03", label: "Salpingite et ovarite aiguës (abcès tubo-ovarien)" },
  { code: "N72", label: "Inflammation chronique du col de l'utérus" },
  { code: "N76.0", label: "Vaginite aiguë" },
  { code: "N75.0", label: "Kyste de la glande de Bartholin" },
  { code: "N92.0", label: "Menstruations abondantes et fréquentes" },
  { code: "N95.0", label: "Hémorragie postménopausique" },
  { code: "T83.32XA", label: "Déplacement de dispositif intra-utérin contraceptif, rencontre initiale" },
  { code: "N20.0", label: "Calcul du rein" },
  { code: "N13.2", label: "Hydronéphrose avec obstruction par calcul rénal et urétéral" },
  { code: "N30.00", label: "Cystite aiguë sans lésion organique, sans hématurie" },
  { code: "N10", label: "Néphrite tubulo-interstitielle aiguë" },
  { code: "N13.6", label: "Pyélo-urérite obstructive" },
  { code: "R31.9", label: "Hématurie, sans précision" },
  { code: "R33.9", label: "Rétention urinaire, sans précision" },
  { code: "T83.511A", label: "Obstruction mécanique de sonde urinaire, rencontre initiale" },
  { code: "N45.1", label: "Épididymite" },
  { code: "N44.00", label: "Torsion du testicule" },
  { code: "N41.9", label: "Prostatite, sans précision" },
  { code: "N34.1", label: "Urétrite non spécifiée" },
  { code: "N48.33", label: "Priapisme, dû à des médicaments" },
  { code: "N47.2", label: "Paraphimosis" },
  { code: "S39.840A", label: "Fracture du corps caverneux du pénis, rencontre initiale" },
  // Phase 18 — psychiatrie / santé comportementale (Part 37 quick picks)
  { code: "R45.851", label: "Idées suicidaires" },
  { code: "T14.91XA", label: "Lésion auto-infligée volontairement, rencontre initiale" },
  { code: "Z91.52", label: "Automutilation intentionnelle, rencontre initiale" },
  { code: "R45.850", label: "Idées homicidaires" },
  { code: "F29", label: "Psychose non organique, sans précision" },
  { code: "R44.1", label: "Hallucinations visuelles" },
  { code: "F31.9", label: "Trouble bipolaire, épisode actuel non précisé, sans précision" },
  { code: "F32.9", label: "Épisode dépressif majeur, épisode unique, sans précision" },
  { code: "F41.0", label: "Trouble panique (crises)" },
  { code: "F43.10", label: "Réaction aiguë au stress" },
  { code: "F05", label: "Délirium non superposé à une démence" },
  { code: "F03.91", label: "Démence non précisée, avec perturbation comportementale" },
  { code: "F06.1", label: "Catatonie associée à un autre trouble mental" },
  { code: "R45.1", label: "Agitation et agressivité" },
  { code: "F19.959", label: "Trouble psychotique induit par les drogues, sans précision" },
  { code: "F10.231", label: "Syndrome de sevrage alcoolique avec délirium" },
  { code: "F53.0", label: "Psychose puerpérale" },
  { code: "F50.01", label: "Anorexie mentale, type restrictif" },
  { code: "F84.0", label: "Trouble du spectre de l'autisme" },
  { code: "Z53.20", label: "Procédure et traitement non effectués en raison du refus du patient" },
];

/** Quick-insert snippets for nursing / general consultation notes (Notes de consultation). */
export const COMMON_NOTE_SNIPPETS = [
  "Patient vu en consultation. Pas d'alerte.",
  "Constantes dans les normes. Pas de fièvre.",
  "Pansement effectué. Plaie propre.",
  "Conseils hygiéno-diététiques donnés.",
  "Patient orienté vers médecin / spécialiste.",
  "Ordonnance expliquée au patient.",
  "Rendez-vous de suivi fixé.",
  "Refus de soins noté.",
  "Traduction / accompagnant assuré.",
  "Patient non présent au rendez-vous.",
];

/** Quick-insert snippets for clinician impression (Impression clinique). */
export const PROVIDER_IMPRESSION_SNIPPETS = [
  "Examen clinique rassurant.",
  "Pas de signe de gravité.",
  "Diagnostic de présomption : infection virale banale.",
  "Symptomatologie en faveur d'une origine infectieuse.",
  "Bilan à compléter selon évolution.",
  "Patient stable. Pas d'orientation hospitalière.",
  "Contexte fébrile / douleur maîtrisé.",
  "Examen cardiopulmonaire sans particularité.",
  "Abdomen souple, non douloureux.",
];

/** Quick-insert snippets for treatment plan (Plan de traitement). */
export const PROVIDER_PLAN_SNIPPETS = [
  "Traitement symptomatique. Repos. Hydratation.",
  "Antibiothérapie si pas d'amélioration sous 48–72 h.",
  "Contrôle des constantes à domicile.",
  "Reconsulter si aggravation (fièvre persistante, difficultés respiratoires).",
  "Suivi en soins primaires.",
  "Examens complémentaires demandés (NFS, CRP si besoin).",
  "Éducation du patient sur signes d'alerte.",
  "Arrêt de travail / arrêt scolaire si indiqué.",
];
