-- MEDUI.AUTH.ROLE.3 — expand DepartmentCode enum with hospital-grade clinical departments.
-- Legacy values (PRIMARY_CARE, LAB, RAD, PHARM, INPATIENT) are retained for existing rows and assignments.

ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'EMERGENCY';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'ICU';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'MEDSURG';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'OBSERVATION';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'OBGYN';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'PEDIATRICS';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'BEHAVIORAL_HEALTH';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'TELEMETRY';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'LABORATORY';
ALTER TYPE "DepartmentCode" ADD VALUE IF NOT EXISTS 'RADIOLOGY';
