"use client";
import { useCallback,useEffect,useState } from "react";
import { useFacilityAndRoles } from "@/hooks/useFacilityAndRoles";
import { closeDigitalCareStaffThread,fetchDigitalCareStaffThread,fetchDigitalCareStaffThreads,replyDigitalCareStaffThread,fetchDigitalCareStaffResults,releaseDigitalCareResult,revokeDigitalCareResult,type DigitalCareStaffThread,type DigitalCareStaffThreadSummary,type DigitalCareStaffResult } from "@/lib/digitalCareStaffMessagingApi";
export default function DigitalCareProviderWorkspace(){
 const {facilityId,roles,ready}=useFacilityAndRoles(); const canUse=roles.includes("PROVIDER")||roles.includes("RN");
 const [tab,setTab]=useState<"messages"|"results">("messages"); const [threads,setThreads]=useState<DigitalCareStaffThreadSummary[]>([]); const [selected,setSelected]=useState<DigitalCareStaffThread|null>(null); const [results,setResults]=useState<DigitalCareStaffResult[]>([]); const [reply,setReply]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const refresh=useCallback(async()=>{if(!facilityId||!canUse)return;setBusy(true);setError(null);try{const [t,r]=await Promise.all([fetchDigitalCareStaffThreads(facilityId),fetchDigitalCareStaffResults(facilityId)]);setThreads(t);setResults(r);}catch(e){setError(e instanceof Error?e.message:"Unable to load Digital Care workspace.");}finally{setBusy(false);}},[facilityId,canUse]);
 useEffect(()=>{if(ready&&canUse&&facilityId)void refresh();},[ready,canUse,facilityId,refresh]);
 async function open(t:DigitalCareStaffThreadSummary){if(!facilityId)return;setBusy(true);try{setSelected(await fetchDigitalCareStaffThread(facilityId,t.id));}finally{setBusy(false)}}
 async function send(){if(!facilityId||!selected||!reply.trim())return;setBusy(true);try{await replyDigitalCareStaffThread(facilityId,selected.id,reply.trim());setReply("");setSelected(await fetchDigitalCareStaffThread(facilityId,selected.id));await refresh();}finally{setBusy(false)}}
 async function close(){if(!facilityId||!selected||!window.confirm("Close this patient conversation?"))return;setBusy(true);try{await closeDigitalCareStaffThread(facilityId,selected.id);setSelected(await fetchDigitalCareStaffThread(facilityId,selected.id));await refresh();}finally{setBusy(false)}}
 async function toggleResult(r:DigitalCareStaffResult){if(!facilityId)return;const action=r.released?"remove this result from the patient portal":"release this verified result to the patient";if(!window.confirm(`Are you sure you want to ${action}?`))return;setBusy(true);setError(null);try{if(r.released)await revokeDigitalCareResult(facilityId,r.id);else await releaseDigitalCareResult(facilityId,r.id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to update result release.");}finally{setBusy(false)}}
 if(!ready)return <main style={{padding:24}}>Loading…</main>; if(!canUse)return <main style={{padding:24}}><h1>Digital Care</h1><p>This workspace requires PROVIDER or RN role.</p></main>;
 return <main style={{padding:24,maxWidth:1440,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:16}}><div><h1 style={{margin:0}}>Digital Care</h1><p style={{color:"#64748b"}}>Secure patient communication and governed release of verified diagnostic results for the active facility.</p></div><button onClick={()=>void refresh()} disabled={busy}>Refresh</button></div>
 {error?<div role="alert" style={{padding:12,background:"#fee2e2",color:"#991b1b",borderRadius:8,margin:"12px 0"}}>{error}</div>:null}
 <div style={{display:"flex",gap:8,margin:"18px 0"}}><button onClick={()=>setTab("messages")} style={{fontWeight:tab==="messages"?800:500}}>Patient Conversations</button><button onClick={()=>setTab("results")} style={{fontWeight:tab==="results"?800:500}}>Results / Release to Patient ({results.filter(r=>!r.released).length})</button></div>
 {tab==="results"?<section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:12,overflow:"hidden"}}><div style={{padding:16,borderBottom:"1px solid #e2e8f0"}}><strong>Verified diagnostic results</strong><div style={{fontSize:13,color:"#64748b",marginTop:4}}>Verification does not automatically expose a result. Release is an explicit, audited patient-communication action.</div></div>{results.length===0?<p style={{padding:16,color:"#64748b"}}>No verified lab or imaging results are available.</p>:results.map(r=><div key={r.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:16,padding:16,borderBottom:"1px solid #f1f5f9",alignItems:"center"}}><div><div style={{display:"flex",gap:8,alignItems:"center"}}><strong>{r.title}</strong>{r.criticalValue?<span style={{fontSize:11,fontWeight:800,color:"#991b1b"}}>CRITICAL</span>:null}<span style={{fontSize:11,fontWeight:800,color:r.released?"#166534":"#92400e"}}>{r.released?"RELEASED":"NOT RELEASED"}</span></div><div style={{fontSize:12,color:"#64748b",marginTop:4}}>Patient: {r.patientId} • {r.kind==="LAB_TEST"?"Lab":"Imaging"} • Verified {new Date(r.verifiedAt).toLocaleString()}</div>{r.resultText?<div style={{marginTop:7,whiteSpace:"pre-wrap"}}>{r.resultText}</div>:null}</div><button disabled={busy} onClick={()=>void toggleResult(r)} style={{padding:"9px 12px",background:r.released?"white":"#087E8B",color:r.released?"#991b1b":"white",border:"1px solid #cbd5e1",borderRadius:8,fontWeight:800}}>{r.released?"Revoke patient access":"Release to patient"}</button></div>)}</section>:
 <div style={{display:"grid",gridTemplateColumns:"minmax(300px,.85fr) minmax(460px,1.6fr)",gap:18}}><section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:12}}>{threads.length===0?<p style={{padding:16,color:"#64748b"}}>No patient conversations.</p>:threads.map(t=><button key={t.id} onClick={()=>void open(t)} style={{display:"block",width:"100%",textAlign:"left",padding:14,border:0,borderBottom:"1px solid #f1f5f9",background:selected?.id===t.id?"#ecfeff":"white"}}><strong>{t.subject}</strong><div style={{fontSize:12,color:"#64748b"}}>Patient: {t.patientId} • {t.status}</div></button>)}</section><section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:12,minHeight:400}}>{!selected?<p style={{padding:20,color:"#64748b"}}>Select a patient conversation.</p>:<><div style={{padding:16,borderBottom:"1px solid #e2e8f0"}}><strong>{selected.subject}</strong>{selected.status==="OPEN"?<button onClick={()=>void close()} style={{float:"right"}}>Close</button>:null}</div><div style={{padding:16,maxHeight:430,overflowY:"auto"}}>{selected.messages.map(m=><div key={m.id} style={{margin:"8px 0",textAlign:m.senderType==="STAFF"?"right":"left"}}><span style={{display:"inline-block",maxWidth:"76%",padding:"9px 11px",borderRadius:10,background:m.senderType==="STAFF"?"#dbeafe":"#f8fafc"}}>{m.body}</span></div>)}</div>{selected.status==="OPEN"?<div style={{padding:16,borderTop:"1px solid #e2e8f0"}}><textarea value={reply} onChange={e=>setReply(e.target.value)} maxLength={4000} rows={4} style={{width:"100%",boxSizing:"border-box"}}/><button onClick={()=>void send()} disabled={busy||!reply.trim()} style={{marginTop:8}}>Send reply</button></div>:null}</>}</section></div>}
 </main>;
}
