"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useFacilityAndRoles } from "@/hooks/useFacilityAndRoles";
import { createIntegration, fetchIntegrationFacilities, fetchIntegrationPermissions, fetchIntegrations, setIntegrationEnabled, type IntegrationFacilityOption, type IntegrationPermissionOption, type IntegrationRow } from "@/lib/adminIntegrationsApi";

const initial = { displayName:"", partnerName:"", organizationType:"LABORATORY", jurisdiction:"US", organizationRegistrationId:"", website:"", addressLine1:"", addressLine2:"", city:"", stateProvinceRegion:"", postalCode:"", country:"US", primaryContactFirstName:"", primaryContactLastName:"", primaryContactJobTitle:"", primaryContactDepartment:"", primaryContactEmail:"", primaryContactPhone:"", primaryContactExtension:"", primaryContactMobile:"", technicalContactSameAsPrimary:true, technicalContactName:"", technicalContactJobTitle:"", technicalContactEmail:"", technicalContactPhone:"", technicalContactExtension:"", environment:"SANDBOX", protocol:"FHIR_R4", direction:"INBOUND", facilityIds:[] as string[], permissionCodes:[] as string[] };
const fieldStyle = { display:"grid", gap:5, fontWeight:600 } as const;
const gridStyle = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))", gap:16 } as const;
const labels: Record<string,string> = { LABORATORY:"Laboratory", HOSPITAL:"Hospital", CLINIC:"Clinic", PHARMACY:"Pharmacy", IMAGING_RADIOLOGY:"Imaging / radiology", GOVERNMENT:"Government", RCM_BILLING:"RCM / billing", HIE:"Health information exchange", OTHER:"Other", INBOUND:"Inbound to Medora", OUTBOUND:"Outbound from Medora", BIDIRECTIONAL:"Bidirectional", SANDBOX:"Sandbox / Test", PRODUCTION:"Production", "read":"Read", "search-type":"Search" };
const Input = ({label, optional, ...props}: {label:string; optional?:boolean} & React.InputHTMLAttributes<HTMLInputElement>) => <label style={fieldStyle}>{label} {optional && <small style={{fontWeight:400}}>(optional)</small>}<input {...props} style={{padding:9,border:"1px solid #aaa",borderRadius:5}}/></label>;

export default function IntegrationsPage() {
  const { ready, canCreateFacilities } = useFacilityAndRoles();
  const [rows,setRows]=useState<IntegrationRow[]>([]), [facilities,setFacilities]=useState<IntegrationFacilityOption[]>([]), [permissions,setPermissions]=useState<IntegrationPermissionOption[]>([]); const [open,setOpen]=useState(false), [step,setStep]=useState(1), [form,setForm]=useState(initial), [error,setError]=useState("");
  async function load(){ const [r,p,f]=await Promise.all([fetchIntegrations(),fetchIntegrationPermissions(),fetchIntegrationFacilities()]); setRows(r);setPermissions(p);setFacilities(f); }
  useEffect(()=>{if(ready&&canCreateFacilities) void load().catch(e=>setError(e.message));},[ready,canCreateFacilities]);
  if(!ready)return <main style={{padding:24}}>Loading…</main>; if(!canCreateFacilities)return <main style={{padding:24}}><h1>Access denied</h1><p>Platform integration administration is required.</p></main>;
  const set=(key:keyof typeof initial,value:string|boolean)=>setForm(f=>({...f,[key]:value}));
  const toggle=(key:"facilityIds"|"permissionCodes",value:string)=>setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value]}));
  function validateStep(){ const required:Record<number,(keyof typeof initial)[]>={1:["displayName","partnerName","organizationType","jurisdiction","addressLine1","city","country"],2:["primaryContactFirstName","primaryContactLastName","primaryContactJobTitle","primaryContactEmail","primaryContactPhone"],3:["protocol","direction","environment"],4:["facilityIds"],5:["permissionCodes"]}; const missing=(required[step]??[]).find(k=>Array.isArray(form[k])?!(form[k] as string[]).length:!String(form[k]).trim()); if(missing){setError(`Complete the required ${String(missing).replace(/([A-Z])/g," $1").toLowerCase()} field.`);return false;} if(step===2&&!form.technicalContactSameAsPrimary&&(!form.technicalContactName||!form.technicalContactEmail||!form.technicalContactPhone)){setError("Complete the required technical contact fields.");return false;} if(step===5&&!permissions.length){setError("No grantable FHIR permissions are available in this deployment.");return false;} setError("");return true; }
  async function save(e:FormEvent){e.preventDefault();if(!validateStep())return;try{await createIntegration(form);setOpen(false);setStep(1);setForm(initial);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to save integration");}}
  const facilityName=(id:string)=>facilities.find(f=>f.id===id)?.name??id; const permissionName=(code:string)=>{const p=permissions.find(x=>x.code===code);return p?`${p.resourceType} — ${labels[p.interaction]??p.interaction}`:code;};
  return <main style={{padding:24,maxWidth:1050,margin:"auto"}}><Link href="/app/admin">← Administration</Link><header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1>Integrations</h1><p>Manage external organizations and their non-secret interoperability access.</p></div><button onClick={()=>{setOpen(true);setError("");}}>+ Add Integration</button></header>{error&&<p role="alert" style={{color:"#991b1b",background:"#fee2e2",padding:12,borderRadius:6}}>{error}</p>}
  <section><h2>Connected Systems</h2>{rows.length===0?<p>No integrations configured.</p>:rows.map(r=><article key={r.id} style={{border:"1px solid #ddd",padding:16,marginBottom:10,borderRadius:8,opacity:r.status==="DISABLED"?.55:1}}><strong>{r.displayName}</strong> — {r.status}<div>{r.partnerName} · FHIR R4 · {labels[r.environment]??r.environment} · {r.facilities.length} facilities</div><button onClick={async()=>{await setIntegrationEnabled(r.id,r.status==="DISABLED");await load();}}>{r.status==="DISABLED"?"Enable":"Disable"}</button></article>)}</section>
  {open&&<form onSubmit={save} style={{border:"1px solid #94a3b8",boxShadow:"0 8px 24px #0001",borderRadius:10,padding:24,marginTop:24}}><p style={{color:"#475569"}}>Step {step} of 6</p><h2>{["Organization","Contacts","Connection","Facility Access","Permissions","Review"][step-1]}</h2>
  {step===1&&<div style={gridStyle}><Input label="Integration display name" required value={form.displayName} onChange={e=>set("displayName",e.target.value)}/><Input label="Legal organization name" required value={form.partnerName} onChange={e=>set("partnerName",e.target.value)}/><label style={fieldStyle}>Organization type<select value={form.organizationType} onChange={e=>set("organizationType",e.target.value)}>{Object.keys(labels).slice(0,9).map(x=><option value={x} key={x}>{labels[x]}</option>)}</select></label><label style={fieldStyle}>Jurisdiction / country<select value={form.jurisdiction} onChange={e=>{const value=e.target.value;set("jurisdiction",value);if(value!=="OTHER")set("country",value);}}><option value="US">United States</option><option value="DO">Dominican Republic</option><option value="HT">Haiti</option><option value="OTHER">Other</option></select></label><Input label="Registration ID" optional value={form.organizationRegistrationId} onChange={e=>set("organizationRegistrationId",e.target.value)}/><Input label="Website" optional type="url" value={form.website} onChange={e=>set("website",e.target.value)}/><Input label="Address line 1" required value={form.addressLine1} onChange={e=>set("addressLine1",e.target.value)}/><Input label="Address line 2" optional value={form.addressLine2} onChange={e=>set("addressLine2",e.target.value)}/><Input label="City" required value={form.city} onChange={e=>set("city",e.target.value)}/><Input label="State / Province / Region" optional value={form.stateProvinceRegion} onChange={e=>set("stateProvinceRegion",e.target.value)}/><Input label="Postal code" optional value={form.postalCode} onChange={e=>set("postalCode",e.target.value)}/><Input label="Country code" required maxLength={2} value={form.country} onChange={e=>set("country",e.target.value.toUpperCase())}/></div>}
  {step===2&&<div><h3>Primary responsible contact</h3><div style={gridStyle}><Input label="First name" required value={form.primaryContactFirstName} onChange={e=>set("primaryContactFirstName",e.target.value)}/><Input label="Last name" required value={form.primaryContactLastName} onChange={e=>set("primaryContactLastName",e.target.value)}/><Input label="Job title / role" required value={form.primaryContactJobTitle} onChange={e=>set("primaryContactJobTitle",e.target.value)}/><Input label="Department" optional value={form.primaryContactDepartment} onChange={e=>set("primaryContactDepartment",e.target.value)}/><Input label="Business email" required type="email" value={form.primaryContactEmail} onChange={e=>set("primaryContactEmail",e.target.value)}/><Input label="Business telephone" required type="tel" value={form.primaryContactPhone} onChange={e=>set("primaryContactPhone",e.target.value)}/><Input label="Extension" optional value={form.primaryContactExtension} onChange={e=>set("primaryContactExtension",e.target.value)}/><Input label="Mobile" optional type="tel" value={form.primaryContactMobile} onChange={e=>set("primaryContactMobile",e.target.value)}/></div><h3>Technical contact</h3><label><input type="checkbox" checked={form.technicalContactSameAsPrimary} onChange={e=>set("technicalContactSameAsPrimary",e.target.checked)}/> Same as primary contact</label>{!form.technicalContactSameAsPrimary&&<div style={{...gridStyle,marginTop:12}}><Input label="Name" required value={form.technicalContactName} onChange={e=>set("technicalContactName",e.target.value)}/><Input label="Job title" optional value={form.technicalContactJobTitle} onChange={e=>set("technicalContactJobTitle",e.target.value)}/><Input label="Email" required type="email" value={form.technicalContactEmail} onChange={e=>set("technicalContactEmail",e.target.value)}/><Input label="Telephone" required type="tel" value={form.technicalContactPhone} onChange={e=>set("technicalContactPhone",e.target.value)}/><Input label="Extension" optional value={form.technicalContactExtension} onChange={e=>set("technicalContactExtension",e.target.value)}/></div>}</div>}
  {step===3&&<div style={gridStyle}><fieldset><legend>Protocol</legend><label><input type="radio" checked readOnly/> FHIR R4</label><br/><label style={{color:"#64748b"}}><input type="radio" disabled/> HL7 v2 — Planned (not available)</label></fieldset><fieldset><legend>Direction</legend>{["INBOUND","OUTBOUND","BIDIRECTIONAL"].map(x=><label key={x}><input type="radio" checked={form.direction===x} onChange={()=>set("direction",x)}/>{labels[x]}<br/></label>)}</fieldset><fieldset><legend>Environment</legend>{["SANDBOX","PRODUCTION"].map(x=><label key={x}><input type="radio" checked={form.environment===x} onChange={()=>set("environment",x)}/>{labels[x]}<br/></label>)}</fieldset></div>}
  {step===4&&<div><p>Select one or more Medora facilities. Access is independently verified by the server.</p>{facilities.length===0?<p role="status">No authorized active facilities are available. Contact a platform administrator.</p>:facilities.map(f=><label key={f.id} style={{display:"block",padding:10,borderBottom:"1px solid #eee"}}><input type="checkbox" checked={form.facilityIds.includes(f.id)} onChange={()=>toggle("facilityIds",f.id)}/> <strong>{f.name}</strong> <span style={{color:"#64748b"}}>— {[f.billingCity,f.billingStateProvince,f.country].filter(Boolean).join(", ")} · {f.code}</span></label>)}</div>}
  {step===5&&<div><p>Only implemented, tested capabilities supplied by Medora&apos;s FHIR capability registry can be granted.</p>{permissions.length===0?<p role="status">No grantable FHIR permissions are available in this deployment. Enable approved interoperability capabilities before onboarding.</p>:permissions.map(p=><label key={p.code} style={{display:"block",padding:8}}><input type="checkbox" checked={form.permissionCodes.includes(p.code)} onChange={()=>toggle("permissionCodes",p.code)}/> {p.resourceType} — {labels[p.interaction]??p.interaction}</label>)}</div>}
  {step===6&&<div><h3>Organization</h3><p><strong>{form.displayName}</strong><br/>{form.partnerName} · {labels[form.organizationType]} · {form.jurisdiction}<br/>{form.addressLine1}{form.addressLine2&&`, ${form.addressLine2}`}, {form.city}{form.stateProvinceRegion&&`, ${form.stateProvinceRegion}`} {form.postalCode}, {form.country}{form.website&&<><br/>{form.website}</>}</p><h3>Primary Responsible Contact</h3><p>{form.primaryContactFirstName} {form.primaryContactLastName} · {form.primaryContactJobTitle}{form.primaryContactDepartment&&` · ${form.primaryContactDepartment}`}<br/>{form.primaryContactEmail} · {form.primaryContactPhone}{form.primaryContactExtension&&` ext. ${form.primaryContactExtension}`}</p><h3>Technical Contact</h3><p>{form.technicalContactSameAsPrimary?`${form.primaryContactFirstName} ${form.primaryContactLastName} (same as primary)`:form.technicalContactName}<br/>{form.technicalContactSameAsPrimary?form.primaryContactEmail:form.technicalContactEmail} · {form.technicalContactSameAsPrimary?form.primaryContactPhone:form.technicalContactPhone}</p><h3>Connection</h3><p>FHIR R4 · {labels[form.direction]} · {labels[form.environment]}</p><h3>Authorized Medora Facilities</h3><ul>{form.facilityIds.map(id=><li key={id}>{facilityName(id)}</li>)}</ul><h3>Granted Permissions</h3><ul>{form.permissionCodes.map(code=><li key={code}>{permissionName(code)}</li>)}</ul><h3>Provisioning</h3><p><strong>Pending provisioning</strong></p><details><summary>Technical payload</summary><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify({...form,provisioningState:"PENDING_PROVISIONING"},null,2)}</pre></details></div>}
  <div style={{marginTop:20,display:"flex",gap:8}}><button type="button" onClick={()=>setOpen(false)}>Cancel</button>{step>1&&<button type="button" onClick={()=>{setError("");setStep(step-1);}}>Back</button>}{step<6?<button type="button" onClick={()=>{if(validateStep())setStep(step+1);}}>Next</button>:<button type="submit">Save integration</button>}</div></form>}</main>;
}
