"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useFacilityAndRoles } from "@/hooks/useFacilityAndRoles";
import { createIntegration, fetchIntegrationPermissions, fetchIntegrations, setIntegrationEnabled, type IntegrationPermissionOption, type IntegrationRow } from "@/lib/adminIntegrationsApi";
import { fetchAdminFacilities, type AdminFacilityRow } from "@/lib/adminUsersApi";

const initial = { displayName: "", partnerName: "", organizationType: "LABORATORY", jurisdiction: "US", environment: "SANDBOX", protocol: "FHIR_R4", direction: "INBOUND", technicalContactName: "", technicalContactEmail: "", technicalContactPhone: "", facilityIds: [] as string[], permissionCodes: [] as string[] };
export default function IntegrationsPage() {
  const { ready, canCreateFacilities, facilityId } = useFacilityAndRoles();
  const [rows, setRows] = useState<IntegrationRow[]>([]); const [facilities, setFacilities] = useState<AdminFacilityRow[]>([]); const [permissions, setPermissions] = useState<IntegrationPermissionOption[]>([]); const [open, setOpen] = useState(false); const [step, setStep] = useState(1); const [form, setForm] = useState(initial); const [error, setError] = useState("");
  async function load() { const [r, p, f] = await Promise.all([fetchIntegrations(), fetchIntegrationPermissions(), fetchAdminFacilities(facilityId || undefined, { includeInactive: false })]); setRows(r); setPermissions(p); setFacilities(f); }
  useEffect(() => { if (ready && canCreateFacilities) void load().catch((e) => setError(e.message)); }, [ready, canCreateFacilities, facilityId]);
  if (!ready) return <main style={{ padding: 24 }}>Loading…</main>;
  if (!canCreateFacilities) return <main style={{ padding: 24 }}><h1>Access denied</h1><p>Platform integration administration is required.</p></main>;
  async function save(e: FormEvent) { e.preventDefault(); setError(""); try { await createIntegration(form); setOpen(false); setStep(1); setForm(initial); await load(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to save integration"); } }
  const toggle = (key: "facilityIds" | "permissionCodes", value: string) => setForm((f) => ({ ...f, [key]: f[key].includes(value) ? f[key].filter((x) => x !== value) : [...f[key], value] }));
  return <main style={{ padding: 24, maxWidth: 1000 }}><Link href="/app/admin">← Administration</Link><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h1>Integrations</h1><p>Connected systems and non-secret interoperability configuration.</p></div><button onClick={() => setOpen(true)}>+ Add Integration</button></div>{error && <p role="alert" style={{ color: "#b91c1c" }}>{error}</p>}
    <section><h2>Connected Systems</h2>{rows.length === 0 ? <p>No integrations configured.</p> : rows.map((r) => <article key={r.id} style={{ border: "1px solid #ddd", padding: 16, marginBottom: 10, borderRadius: 8, opacity: r.status === "DISABLED" ? .55 : 1 }}><strong>{r.displayName}</strong> — {r.status}<div>{r.partnerName} · {r.protocol} · {r.environment} · {r.facilities.length} facilities</div><button onClick={async () => { await setIntegrationEnabled(r.id, r.status === "DISABLED"); await load(); }}>{r.status === "DISABLED" ? "Enable" : "Disable"}</button></article>)}</section>
    {open && <form onSubmit={save} style={{ border: "2px solid #111", borderRadius: 8, padding: 20 }}><h2>Add Integration — Step {step} of 6</h2>
      {step === 1 && <div><label>Integration display name <input required value={form.displayName} onChange={(e) => setForm({...form, displayName:e.target.value})}/></label><br/><label>Partner/legal organization <input required value={form.partnerName} onChange={(e) => setForm({...form, partnerName:e.target.value})}/></label><br/><label>Organization type <select value={form.organizationType} onChange={(e)=>setForm({...form,organizationType:e.target.value})}>{["LABORATORY","HOSPITAL","CLINIC","PHARMACY","IMAGING_RADIOLOGY","GOVERNMENT","RCM_BILLING","HIE","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><br/><label>Jurisdiction <select value={form.jurisdiction} onChange={(e)=>setForm({...form,jurisdiction:e.target.value})}><option value="US">United States</option><option value="DO">Dominican Republic</option><option value="HT">Haiti</option><option value="OTHER">Other</option></select></label><br/><label>Environment <select value={form.environment} onChange={(e)=>setForm({...form,environment:e.target.value})}><option value="SANDBOX">Sandbox/Test</option><option value="PRODUCTION">Production</option></select></label></div>}
      {step === 2 && <div><label><input type="radio" checked readOnly/> FHIR R4</label><br/><label><input type="radio" disabled/> HL7 v2 (planned for P0.4)</label></div>}
      {step === 3 && <div>{["INBOUND","OUTBOUND","BIDIRECTIONAL"].map(x=><label key={x}><input type="radio" checked={form.direction===x} onChange={()=>setForm({...form,direction:x})}/>{x}<br/></label>)}</div>}
      {step === 4 && <div><p>No facility access is granted by default.</p>{facilities.map(f=><label key={f.id}><input type="checkbox" checked={form.facilityIds.includes(f.id)} onChange={()=>toggle("facilityIds",f.id)}/>{f.name}<br/></label>)}</div>}
      {step === 5 && <div><p>Only live, tested FHIR read capabilities can be granted.</p>{permissions.map(p=><label key={p.code}><input type="checkbox" checked={form.permissionCodes.includes(p.code)} onChange={()=>toggle("permissionCodes",p.code)}/>{p.resourceType} — {p.interaction}<br/></label>)}</div>}
      {step === 6 && <div><h3>Review</h3><pre style={{ whiteSpace:"pre-wrap" }}>{JSON.stringify({...form, provisioningState:"PENDING_PROVISIONING"},null,2)}</pre><p>No credential or secret will be generated in P0.3A.</p></div>}
      <div style={{ marginTop:16, display:"flex", gap:8 }}><button type="button" onClick={()=>setOpen(false)}>Cancel</button>{step>1&&<button type="button" onClick={()=>setStep(step-1)}>Back</button>}{step<6?<button type="button" onClick={()=>setStep(step+1)}>Next</button>:<button type="submit">Save configuration</button>}</div></form>}
  </main>;
}
