/**
 * EDOC.TEST.1 — minimal valid payloads for high-risk legal coverage suites.
 */
import {
  BLOOD_PRODUCT_COMPLETION_CARD_ID,
  BLOOD_PRODUCT_INITIATION_CARD_ID,
  BLOOD_PRODUCT_PRE_ASSESSMENT_CARD_ID,
  BLOOD_PRODUCT_REACTION_CARD_ID,
  BLOOD_PRODUCT_REASSESSMENT_CARD_ID,
  BLOOD_PRODUCT_VERIFICATION_CARD_ID,
  EDOC7_BLOOD_PRODUCT_DOCUMENTATION_CARD_IDS,
  MASSIVE_TRANSFUSION_PROTOCOL_EVENT_CARD_ID,
} from "@medora/shared";
import {
  EDOC8_HIGH_ALERT_INFUSION_DOCUMENTATION_CARD_IDS,
  HIGH_ALERT_INFUSION_COMPLETION_CARD_ID,
  HIGH_ALERT_INFUSION_HOLD_CARD_ID,
  HIGH_ALERT_INFUSION_INITIATION_CARD_ID,
  HIGH_ALERT_INFUSION_REASSESSMENT_CARD_ID,
  HIGH_ALERT_INFUSION_TITRATION_CARD_ID,
  HIGH_ALERT_INFUSION_VERIFICATION_CARD_ID,
  HIGH_ALERT_MEDICATION_TYPE_VALUES,
} from "@medora/shared";
import {
  EDOC6_RESTRAINT_DOCUMENTATION_CARD_IDS,
  RESTRAINT_DISCONTINUATION_CARD_ID,
  RESTRAINT_FACE_TO_FACE_CARD_ID,
  RESTRAINT_INITIATION_CARD_ID,
  RESTRAINT_REASSESSMENT_CARD_ID,
  RESTRAINT_RENEWAL_CARD_ID,
} from "@medora/shared";
import {
  EDOC10_PROCEDURAL_SEDATION_DOCUMENTATION_CARD_IDS,
  SEDATION_DISCHARGE_READINESS_CARD_ID,
  SEDATION_INITIATION_CARD_ID,
  SEDATION_MONITORING_CARD_ID,
  SEDATION_PRE_ASSESSMENT_CARD_ID,
  SEDATION_REASSESSMENT_CARD_ID,
  SEDATION_RECOVERY_MONITORING_CARD_ID,
  SEDATION_RECOVERY_SCORE_CARD_ID,
  SEDATION_TIMEOUT_CARD_ID,
  calculateSedationRecoveryScore,
} from "@medora/shared";
import {
  CENTRAL_LINE_ASSESSMENT_CARD_ID,
  CHEST_TUBE_MONITORING_CARD_ID,
  EDOC17_DEVICE_LINE_TUBE_DRAIN_MONITORING_CARD_IDS,
  ENDOTRACHEAL_TUBE_MONITORING_CARD_ID,
  EXTERNAL_URINARY_DEVICE_MONITORING_CARD_ID,
  FOLEY_CATHETER_MONITORING_CARD_ID,
  NG_OG_TUBE_MONITORING_CARD_ID,
  PERIPHERAL_IV_ASSESSMENT_CARD_ID,
  PICC_MIDLINE_ASSESSMENT_CARD_ID,
  SURGICAL_DRAIN_MONITORING_CARD_ID,
  TRACHEOSTOMY_MONITORING_CARD_ID,
} from "@medora/shared";

export const EDOC_TEST1_ISO = "2026-05-28T12:00:00.000Z";

const RECOVERY_SCORE_COMPONENTS = {
  activity: "MOVES_4_EXTREMITIES" as const,
  respiration: "DEEP_BREATH_COUGH" as const,
  circulation: "BP_WITHIN_20_PERCENT" as const,
  consciousness: "FULLY_AWAKE" as const,
  oxygenSaturation: "MAINTAINS_GREATER_92_ROOM_AIR" as const,
};

const RECOVERY_TOTAL = calculateSedationRecoveryScore(RECOVERY_SCORE_COMPONENTS);

export type EdocTest1LegalCoverageFixture = {
  cardId: string;
  category: string;
  payload: Record<string, unknown>;
  summaryEnKeys?: string[];
  htmlContains?: string[];
};

export const EDOC_TEST1_BLOOD_PRODUCT_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: BLOOD_PRODUCT_VERIFICATION_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      verificationTime: EDOC_TEST1_ISO,
      productType: "PRBC",
      unitIdentifier: "UNIT-BP-VERIFY",
      unitVolumeMl: 250,
      patientIdentityVerified: true,
      bloodTypeVerified: true,
      crossmatchVerified: true,
      expirationVerified: true,
      consentVerified: true,
      specialRequirements: "NONE",
    },
    summaryEnKeys: ["Unit ID", "Product"],
    htmlContains: ["UNIT-BP-VERIFY", "BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: BLOOD_PRODUCT_PRE_ASSESSMENT_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      productType: "PRBC",
      unitIdentifier: "UNIT-BP-PRE",
      unitVolumeMl: 350,
      baselineTemperature: "37.0",
      baselineHeartRate: 78,
      baselineRespRate: 16,
      baselineBloodPressure: "119/77",
      baselineSpo2: 98,
      patientIdentityVerified: true,
      consentVerified: true,
      symptomsPresent: false,
      symptomChecklist: [],
    },
    summaryEnKeys: ["Product"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: BLOOD_PRODUCT_INITIATION_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      startTime: EDOC_TEST1_ISO,
      productType: "PRBC",
      unitIdentifier: "UNIT-BP-INIT",
      unitVolumeMl: 250,
      baselineTemperature: "37.0",
      baselineHeartRate: 80,
      baselineRespRate: 16,
      baselineBloodPressure: "120/80",
      baselineSpo2: 98,
      preMedicationAdministered: false,
      providerOrderVerified: true,
      consentVerified: true,
      administrationStarted: true,
    },
    summaryEnKeys: ["Start time"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: BLOOD_PRODUCT_REASSESSMENT_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      temperature: "37.1",
      heartRate: 84,
      respRate: 16,
      bloodPressure: "118/76",
      spo2: 97,
      symptomsPresent: false,
      symptomChecklist: [],
      providerNotified: false,
      continuedAdministration: true,
    },
    summaryEnKeys: ["Symptoms present"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: BLOOD_PRODUCT_REACTION_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      reactionTime: EDOC_TEST1_ISO,
      reactionType: "FEBRILE_NON_HEMOLYTIC",
      symptoms: ["FEVER", "CHILLS"],
      providerNotified: true,
      interventionRequired: true,
      transfusionStopped: true,
      bloodBankNotified: true,
      reactionWorkupStarted: true,
    },
    summaryEnKeys: ["Reaction type"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: BLOOD_PRODUCT_COMPLETION_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      completionTime: EDOC_TEST1_ISO,
      endTime: EDOC_TEST1_ISO,
      productType: "PLATELETS",
      unitIdentifier: "UNIT-BP-DONE",
      volumeInfusedMl: 250,
      postTemperature: "37.0",
      postHeartRate: 82,
      postRespRate: 16,
      postBloodPressure: "118/76",
      postSpo2: 97,
      reactionObserved: false,
      transfusionCompleted: true,
      providerNotified: false,
    },
    summaryEnKeys: ["Reaction observed"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION"],
  },
  {
    cardId: MASSIVE_TRANSFUSION_PROTOCOL_EVENT_CARD_ID,
    category: "BLOOD_PRODUCT_DOCUMENTATION",
    payload: {
      eventTime: EDOC_TEST1_ISO,
      eventType: "ACTIVATED",
      initiatedBy: "provider-1",
      reason: "Hemorrhagic shock",
    },
    summaryEnKeys: ["MTP status"],
    htmlContains: ["BLOOD_PRODUCT_DOCUMENTATION", "Activated"],
  },
];

export const EDOC_TEST1_HIGH_ALERT_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: HIGH_ALERT_INFUSION_VERIFICATION_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      verificationTime: EDOC_TEST1_ISO,
      medicationType: "HEPARIN",
      medicationName: "Heparin protocol",
      concentration: "25k/500",
      orderedRate: "18 u/kg/hr",
      orderedDose: "1200 u/hr",
      weightBasedCalculationVerified: true,
      pumpProgrammingVerified: true,
      lineTracingVerified: true,
      patientVerified: true,
      providerOrderVerified: true,
      independentDoubleCheckPerformed: true,
    },
    summaryEnKeys: ["Medication"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION", "Heparin protocol"],
  },
  {
    cardId: HIGH_ALERT_INFUSION_INITIATION_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      startTime: EDOC_TEST1_ISO,
      medicationType: "INSULIN",
      medicationName: "Insulin drip",
      orderedRate: "2 u/hr",
      programmedRate: "2 u/hr",
      route: "IV",
      baselineHeartRate: 80,
      baselineBloodPressure: "120/80",
      baselineRespRate: 16,
      baselineSpo2: 98,
      providerOrderVerified: true,
      administrationStarted: true,
    },
    summaryEnKeys: ["Programmed rate"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION"],
  },
  {
    cardId: HIGH_ALERT_INFUSION_TITRATION_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      titrationTime: EDOC_TEST1_ISO,
      medicationType: "VASOPRESSOR",
      previousRate: "5 mcg/min",
      newRate: "10 mcg/min",
      reasonForChange: "CLINICAL_RESPONSE",
      providerAware: true,
      secondCheckerRequired: false,
    },
    summaryEnKeys: ["Titration"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION"],
  },
  {
    cardId: HIGH_ALERT_INFUSION_REASSESSMENT_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      heartRate: 82,
      bloodPressure: "118/76",
      respRate: 16,
      spo2: 98,
      adverseEffectsPresent: false,
      providerNotified: false,
      continuedInfusion: true,
    },
    summaryEnKeys: ["Assessment time"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION"],
  },
  {
    cardId: HIGH_ALERT_INFUSION_HOLD_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      holdTime: EDOC_TEST1_ISO,
      reason: "ADVERSE_EVENT",
      providerNotified: true,
      restartPlanned: true,
    },
    summaryEnKeys: ["Hold time"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION"],
  },
  {
    cardId: HIGH_ALERT_INFUSION_COMPLETION_CARD_ID,
    category: "HIGH_ALERT_INFUSION_DOCUMENTATION",
    payload: {
      completionTime: EDOC_TEST1_ISO,
      medicationType: "SEDATIVE",
      finalRate: "4 mg/hr",
      completedAsOrdered: true,
      adverseEventOccurred: false,
      providerNotified: false,
    },
    summaryEnKeys: ["Final rate"],
    htmlContains: ["HIGH_ALERT_INFUSION_DOCUMENTATION"],
  },
];

export const EDOC_TEST1_RESTRAINT_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: RESTRAINT_INITIATION_CARD_ID,
    category: "RESTRAINT_DOCUMENTATION",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      restraintType: "BEHAVIORAL",
      reasonForRestraint: "VIOLENT_BEHAVIOR",
      alternativesAttempted: ["VERBAL_DEESCALATION"],
      continuedNeed: true,
      injuryPresent: false,
      circulationAssessment: "NORMAL",
      mentalStatusAssessment: "Agitated.",
      physicianOrderVerified: true,
      orderingProviderId: "provider-1",
    },
    summaryEnKeys: ["Type"],
    htmlContains: ["RESTRAINT_DOCUMENTATION", "Behavioral"],
  },
  {
    cardId: RESTRAINT_FACE_TO_FACE_CARD_ID,
    category: "RESTRAINT_DOCUMENTATION",
    payload: {
      evaluationTime: EDOC_TEST1_ISO,
      behaviorAssessment: "Aggressive toward staff.",
      dangerToSelf: true,
      dangerToOthers: true,
      continuedNeedForRestraint: true,
      medicalConditionAssessment: "Stable vitals.",
      behavioralConditionAssessment: "Ongoing aggression.",
      providerEvaluatorId: "provider-2",
    },
    summaryEnKeys: ["Evaluator"],
    htmlContains: ["RESTRAINT_DOCUMENTATION"],
  },
  {
    cardId: RESTRAINT_REASSESSMENT_CARD_ID,
    category: "RESTRAINT_DOCUMENTATION",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      airway: "NORMAL",
      circulation: "NORMAL",
      skinIntegrity: "NORMAL",
      nutritionNeedsMet: true,
      hydrationNeedsMet: true,
      eliminationNeedsMet: true,
      rangeOfMotionPerformed: true,
      continuedNeed: true,
      patientResponse: "Calmer.",
    },
    summaryEnKeys: ["Airway"],
    htmlContains: ["RESTRAINT_DOCUMENTATION"],
  },
  {
    cardId: RESTRAINT_RENEWAL_CARD_ID,
    category: "RESTRAINT_DOCUMENTATION",
    payload: {
      renewalTime: EDOC_TEST1_ISO,
      orderingProviderId: "provider-1",
      continuedNeed: true,
      renewalReason: "Continued danger to staff.",
    },
    summaryEnKeys: ["Renewal"],
    htmlContains: ["RESTRAINT_DOCUMENTATION"],
  },
  {
    cardId: RESTRAINT_DISCONTINUATION_CARD_ID,
    category: "RESTRAINT_DOCUMENTATION",
    payload: {
      discontinuedTime: EDOC_TEST1_ISO,
      criteriaMet: ["CALM", "FOLLOWS_COMMANDS"],
      conditionAtDiscontinuation: "Calm and cooperative.",
    },
    summaryEnKeys: ["Criteria met"],
    htmlContains: ["RESTRAINT_DOCUMENTATION"],
  },
];

export const EDOC_TEST1_SEDATION_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: SEDATION_PRE_ASSESSMENT_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      assessedAt: EDOC_TEST1_ISO,
      procedurePlanned: "Shoulder reduction",
      providerResponsible: "Dr Smith",
      consentVerified: true,
      allergiesReviewed: true,
      npoStatus: "NPO_CONFIRMED",
      asaClass: "ASA_II",
      mallampatiScore: "CLASS_II",
      airwayAssessment: "NORMAL",
      baselineHeartRate: 80,
      baselineRespRate: 16,
      baselineBloodPressure: "120/80",
      baselineSpo2: 98,
    },
    summaryEnKeys: ["Heart rate"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
  {
    cardId: SEDATION_TIMEOUT_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      timeoutTime: EDOC_TEST1_ISO,
      correctPatientConfirmed: true,
      correctProcedureConfirmed: true,
      correctSiteConfirmed: true,
      providerPresent: true,
      rnPresent: true,
      monitoringEquipmentAvailable: true,
      suctionAvailable: true,
      oxygenAvailable: true,
      airwayEquipmentAvailable: true,
      reversalAgentsAvailable: true,
      emergencyEquipmentAvailable: true,
      consentVerified: true,
      plannedSedationLevel: "MODERATE",
    },
    summaryEnKeys: ["Timeout"],
    htmlContains: ["PROCEDURE_MONITORING", "Moderate"],
  },
  {
    cardId: SEDATION_INITIATION_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      startTime: EDOC_TEST1_ISO,
      sedationLevelTarget: "MODERATE",
      oxygenDeliveryMethod: "NASAL_CANNULA",
      monitoringStarted: true,
      cardiacMonitorApplied: true,
      pulseOximetryApplied: true,
      etco2MonitoringApplied: false,
      bloodPressureMonitoringApplied: true,
      ivAccessConfirmed: true,
      baselineHeartRate: 80,
      baselineRespRate: 16,
      baselineBloodPressure: "120/80",
      baselineSpo2: 98,
      medicationAdministrationDocumentedInMar: true,
    },
    summaryEnKeys: ["Target level"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
  {
    cardId: SEDATION_MONITORING_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      monitoringTime: EDOC_TEST1_ISO,
      heartRate: 78,
      respRate: 14,
      bloodPressure: "118/76",
      spo2: 99,
      oxygenDeliveryMethod: "NASAL_CANNULA",
      sedationLevel: "DROWSY_RESPONDS_TO_VOICE",
      airwayStatus: "PATENT",
      interventionRequired: false,
      adverseEventObserved: false,
      providerNotified: false,
    },
    summaryEnKeys: ["Heart rate"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
  {
    cardId: SEDATION_REASSESSMENT_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      reassessmentTime: EDOC_TEST1_ISO,
      patientCondition: "STABLE",
      airwayStable: true,
      hemodynamicallyStable: true,
      painControlled: true,
      nauseaVomitingPresent: false,
      providerNotified: false,
      continuedMonitoringRequired: true,
    },
    summaryEnKeys: ["Condition"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
  {
    cardId: SEDATION_RECOVERY_SCORE_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      scoredAt: EDOC_TEST1_ISO,
      ...RECOVERY_SCORE_COMPONENTS,
      totalScore: RECOVERY_TOTAL,
      meetsRecoveryCriteria: true,
    },
    summaryEnKeys: ["Total score"],
    htmlContains: ["PROCEDURE_MONITORING", String(RECOVERY_TOTAL)],
  },
  {
    cardId: SEDATION_RECOVERY_MONITORING_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      monitoringTime: EDOC_TEST1_ISO,
      heartRate: 76,
      respRate: 14,
      bloodPressure: "116/74",
      spo2: 99,
      airwayStatus: "PATENT",
      levelOfConsciousness: "AWAKE",
      nauseaVomitingPresent: false,
    },
    summaryEnKeys: ["Heart rate"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
  {
    cardId: SEDATION_DISCHARGE_READINESS_CARD_ID,
    category: "PROCEDURE_MONITORING",
    payload: {
      assessedAt: EDOC_TEST1_ISO,
      recoveryScoreReviewed: true,
      vitalSignsStable: true,
      airwayStable: true,
      mentalStatusAtBaseline: true,
      painControlled: true,
      nauseaControlled: true,
      responsibleAdultPresent: false,
      dischargeInstructionsReviewed: true,
      providerApprovedDischarge: true,
      patientOrRepresentativeUnderstandsInstructions: true,
      notes: "Patient leaving with EMS escort.",
    },
    summaryEnKeys: ["Provider approved"],
    htmlContains: ["PROCEDURE_MONITORING"],
  },
];

export const EDOC_TEST1_DEVICE_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: PERIPHERAL_IV_ASSESSMENT_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      siteLocation: "Left forearm",
      gauge: "20G",
      status: "PATENT",
      bloodReturnPresent: "YES",
      flushesWithoutResistance: "YES",
      dressingStatus: "CLEAN_DRY_INTACT",
      painPresent: "NO",
      swellingPresent: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Status"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING", "Left forearm"],
  },
  {
    cardId: CENTRAL_LINE_ASSESSMENT_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      lineType: "CVC",
      siteStatus: "NORMAL",
      dressingStatus: "CLEAN_DRY_INTACT",
      securementIntact: "YES",
      infectionConcern: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Line type"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: PICC_MIDLINE_ASSESSMENT_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      deviceType: "PICC",
      siteStatus: "NORMAL",
      bloodReturnPresent: "YES",
      flushesWithoutResistance: "YES",
      infectionConcern: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Site status"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: FOLEY_CATHETER_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      indicationPresent: "YES",
      catheterSecure: "YES",
      urineFlowPresent: "YES",
      urineAppearance: "YELLOW",
      catheterCareCompleted: "YES",
      obstructionConcern: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Appearance"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: EXTERNAL_URINARY_DEVICE_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      deviceType: "PUREWICK",
      deviceIntact: "YES",
      skinIntegrity: "INTACT",
      functioningProperly: "YES",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Skin integrity"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: NG_OG_TUBE_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      tubeType: "NG",
      placementVerified: "YES",
      markingAtNares: "22 cm",
      suctionActive: "NO",
      drainagePresent: "YES",
      drainageAppearance: "CLEAR",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Tube type"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING", "Tube type", "NG"],
  },
  {
    cardId: CHEST_TUBE_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      tubeLocation: "LEFT",
      suctionActive: "YES",
      waterSealPresent: "YES",
      airLeakPresent: "NO",
      drainageAmount: 50,
      drainageAppearance: "SEROSANGUINOUS",
      tubeSecure: "YES",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Drainage amount"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: SURGICAL_DRAIN_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      drainType: "JP",
      drainageAmount: 30,
      drainageAppearance: "SEROUS",
      drainCompressed: "YES",
      siteStatus: "NORMAL",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Drain type"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: ENDOTRACHEAL_TUBE_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      tubePosition: 22,
      positionUnit: "CM",
      securementIntact: "YES",
      oralCareCompleted: "YES",
      airwayPatent: "YES",
      displacementConcern: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Position"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
  {
    cardId: TRACHEOSTOMY_MONITORING_CARD_ID,
    category: "DEVICE_LINE_TUBE_DRAIN_MONITORING",
    payload: {
      assessmentTime: EDOC_TEST1_ISO,
      trachType: "CUFFED",
      siteStatus: "NORMAL",
      innerCannulaChecked: "YES",
      airwayPatent: "YES",
      dislodgementConcern: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Site status"],
    htmlContains: ["DEVICE_LINE_TUBE_DRAIN_MONITORING"],
  },
];

export const EDOC23B_ISO = "2026-05-28T14:00:00.000Z";

export const EDOC23B_FOUNDATION_COMPLETION_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  {
    cardId: "flow_cpr_record",
    category: "FLOWSHEETS",
    payload: {
      eventStartTime: EDOC23B_ISO,
      eventType: "CODE_BLUE",
      initialRhythm: "VFIB",
      compressionsStarted: "YES",
      airwaySupported: "YES",
      defibrillationPerformed: "YES",
      medicationReferenceDocumented: "YES",
      roscAchieved: "YES",
      patientDisposition: "TRANSFERRED_ICU",
      providerPresent: "YES",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Event type"],
    htmlContains: ["FLOWSHEETS"],
  },
  {
    cardId: "flow_thrombolytic_mi",
    category: "FLOWSHEETS",
    payload: {
      administrationTime: EDOC23B_ISO,
      indication: "STEMI",
      agent: "TENECTEPLASE",
      doseVerified: "YES",
      contraindicationChecklistReviewed: "YES",
      providerOrderVerified: "YES",
      cardiologyNotified: "YES",
      ecgReviewed: "YES",
      bloodPressureWithinParameters: "YES",
      medicationAdministered: "YES",
      administrationHeld: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Medication administered"],
    htmlContains: ["FLOWSHEETS"],
  },
  {
    cardId: "flow_observation_monitoring",
    category: "FLOWSHEETS",
    payload: {
      monitoringTime: EDOC23B_ISO,
      observationReason: "ED_OBSERVATION",
      patientStatus: "STABLE",
      vitalSignsReviewed: "YES",
      painReviewed: "YES",
      safetyReviewed: "YES",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Patient status"],
    htmlContains: ["FLOWSHEETS"],
  },
  {
    cardId: "score_ciwa_ar",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      nauseaVomiting: 0,
      tremor: 0,
      paroxysmalSweats: 0,
      anxiety: 0,
      agitation: 0,
      tactileDisturbances: 0,
      auditoryDisturbances: 0,
      visualDisturbances: 0,
      headache: 0,
      orientationClouding: 0,
      totalScore: 0,
      severity: "MINIMAL",
      providerNotified: "NO",
    },
    summaryEnKeys: ["CIWA-Ar"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_cows",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      restingPulse: 0,
      sweating: 0,
      restlessness: 0,
      pupilSize: 0,
      boneJointAches: 0,
      runnyNoseTearing: 0,
      giUpset: 0,
      tremor: 0,
      yawning: 0,
      anxietyIrritability: 0,
      goosefleshSkin: 0,
      totalScore: 0,
      severity: "MILD",
      providerNotified: "NO",
    },
    summaryEnKeys: ["COWS"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_cssrs",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      wishToBeDead: "NO",
      suicidalThoughts: "NO",
      methodThoughts: "NO",
      intentWithoutPlan: "NO",
      intentWithPlan: "NO",
      suicidalBehavior: "NO",
      riskLevel: "LOW",
      providerNotified: "NO",
      safetyPrecautionsInitiated: "NO",
    },
    summaryEnKeys: ["Risk level"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_phq9",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      littleInterest: 0,
      feelingDown: 0,
      sleepTrouble: 0,
      fatigue: 0,
      appetite: 0,
      feelingBad: 0,
      concentration: 0,
      psychomotor: 0,
      suicidalIdeation: 0,
      totalScore: 0,
      severity: "NONE_MINIMAL",
      suicidalIdeationItemPositive: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["PHQ-9"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_gad7",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      feelingNervous: 0,
      cantStopWorrying: 0,
      worryingTooMuch: 0,
      troubleRelaxing: 0,
      restlessness: 0,
      irritability: 0,
      afraidSomethingAwful: 0,
      totalScore: 0,
      severity: "MINIMAL",
      providerNotified: "NO",
    },
    summaryEnKeys: ["GAD-7"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_rts",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      gcsScore: 15,
      systolicBpCategory: "GT_89",
      respiratoryRateCategory: "10_29",
      totalScore: 7.86,
      riskFlag: "LOW",
      providerNotified: "NO",
    },
    summaryEnKeys: ["RTS"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_heart",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      history: 0,
      ecg: 0,
      age: 0,
      riskFactors: 0,
      troponin: 0,
      totalScore: 0,
      riskLevel: "LOW",
      providerNotified: "NO",
    },
    summaryEnKeys: ["HEART score"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_wells_pe",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      clinicalSignsDvt: "NO",
      peMostLikely: "NO",
      heartRateOver100: "NO",
      immobilizationOrSurgery: "NO",
      previousDvtPe: "NO",
      hemoptysis: "NO",
      malignancy: "NO",
      totalScore: 0,
      riskLevel: "PE_UNLIKELY",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Wells PE score"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_perc",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      ageUnder50: "YES",
      heartRateUnder100: "YES",
      oxygenSaturationAtLeast95: "YES",
      noHemoptysis: "YES",
      noEstrogenUse: "YES",
      noPriorDvtPe: "YES",
      noUnilateralLegSwelling: "YES",
      noRecentSurgeryTrauma: "YES",
      percNegative: "YES",
      providerNotified: "NO",
    },
    summaryEnKeys: ["PERC negative"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_geneva",
    category: "SCORES_AND_SCREENS",
    payload: {
      assessmentTime: EDOC23B_ISO,
      ageOver65: "NO",
      previousDvtPe: "NO",
      surgeryOrFractureRecent: "NO",
      activeMalignancy: "NO",
      unilateralLowerLimbPain: "NO",
      hemoptysis: "NO",
      heartRateCategory: "LESS_75",
      painOnPalpationAndEdema: "NO",
      totalScore: 0,
      riskLevel: "LOW",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Geneva score"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_abuse",
    category: "SCORES_AND_SCREENS",
    payload: {
      screenTime: EDOC23B_ISO,
      screenPerformed: "YES",
      patientFeelsUnsafe: "NO",
      physicalAbuseConcern: "NO",
      emotionalAbuseConcern: "NO",
      sexualAbuseConcern: "NO",
      neglectConcern: "NO",
      resourcesOffered: "NO",
      mandatoryReportConsidered: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Screen performed"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_human_trafficking",
    category: "SCORES_AND_SCREENS",
    payload: {
      screenTime: EDOC23B_ISO,
      screenPerformed: "YES",
      unableToSpeakFreely: "NO",
      identificationControlledByOther: "NO",
      fearfulOrCoerced: "NO",
      workLivingControlConcern: "NO",
      physicalSafetyConcern: "NO",
      resourcesOffered: "NO",
      mandatoryReportConsidered: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Screen performed"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
  {
    cardId: "score_sdoh",
    category: "SCORES_AND_SCREENS",
    payload: {
      screenTime: EDOC23B_ISO,
      foodInsecurity: "NO",
      housingInstability: "NO",
      transportationNeed: "NO",
      utilityNeed: "NO",
      medicationAffordabilityConcern: "NO",
      interpersonalSafetyConcern: "NO",
      resourcesOffered: "NO",
      caseManagementReferral: "NO",
      providerNotified: "NO",
    },
    summaryEnKeys: ["Need identified"],
    htmlContains: ["SCORES_AND_SCREENS"],
  },
];

export const EDOC_TEST1_ALL_HIGH_RISK_FIXTURES: EdocTest1LegalCoverageFixture[] = [
  ...EDOC_TEST1_BLOOD_PRODUCT_FIXTURES,
  ...EDOC_TEST1_HIGH_ALERT_FIXTURES,
  ...EDOC_TEST1_RESTRAINT_FIXTURES,
  ...EDOC_TEST1_SEDATION_FIXTURES,
  ...EDOC_TEST1_DEVICE_FIXTURES,
];

export {
  EDOC7_BLOOD_PRODUCT_DOCUMENTATION_CARD_IDS,
  EDOC8_HIGH_ALERT_INFUSION_DOCUMENTATION_CARD_IDS,
  EDOC6_RESTRAINT_DOCUMENTATION_CARD_IDS,
  EDOC10_PROCEDURAL_SEDATION_DOCUMENTATION_CARD_IDS,
  EDOC17_DEVICE_LINE_TUBE_DRAIN_MONITORING_CARD_IDS,
  HIGH_ALERT_MEDICATION_TYPE_VALUES,
};
