/**
 * EDOC.TEST.2 — universal runtime coverage payloads (all AVAILABLE cards).
 * Generated by scripts/build-clinical-documentation-runtime-coverage.mjs — re-run after registry changes.
 */
import {
  CLINICAL_DOCUMENTATION_CARDS,
  getClinicalDocumentationCardById,
  summarizeClinicalDocumentationPayload,
  validatePayloadForCard,
} from "@medora/shared";
import {
  EDOC_TEST1_ALL_HIGH_RISK_FIXTURES,
  EDOC23B_FOUNDATION_COMPLETION_FIXTURES,
} from "./clinical-documentation-legal-coverage.fixtures";

export const EDOC_RUNTIME_COVERAGE_ISO = "2026-05-28T12:00:00.000Z";

export type EdocRuntimeCoverageFixture = {
  cardId: string;
  category: string;
  payload: Record<string, unknown>;
};

/** Cards not covered by EDOC.TEST.1 (36) or EDOC.23B (16) legal fixtures. */
export const RUNTIME_COVERAGE_SUPPLEMENTAL_PAYLOADS: EdocRuntimeCoverageFixture[] = [
  {
    cardId: "adult_nonverbal_pain_assessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "facialExpression": 1,
      "activity": 1,
      "guarding": 0,
      "physiology": 0,
      "respiratory": 0,
      "totalScore": 2,
      "providerNotified": false
    },
  },
  {
    cardId: "agitation_violence_risk_assessment",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "agitationLevel": "MILD",
      "violenceRisk": "LOW",
      "verbalThreats": false,
      "physicalAggression": false,
      "propertyDestruction": false,
      "weaponConcern": false,
      "securityNotified": false,
      "providerNotified": false
    },
  },
  {
    cardId: "antibiotic_timing_reference",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "antibioticsDocumentedInMar": "YES",
      "firstAntibioticTime": "2026-05-28T14:00:00.000Z",
      "antibioticNameReferenced": "Ceftriaxone",
      "providerNotified": "NO",
      "delayOrVariancePresent": "NO"
    },
  },
  {
    cardId: "arrhythmia_event",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "eventType": "SVT",
      "durationMinutes": 12,
      "patientSymptomatic": "YES",
      "bloodPressureAffected": "NO",
      "interventionRequired": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "behavioral_escalation_event",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "reason": "AGITATION_ESCALATED",
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z",
      "securityNotified": false,
      "familyNotified": false,
      "intervention": "DE_ESCALATION",
      "restraintDocumentationReferenced": false
    },
  },
  {
    cardId: "behavioral_observation",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "observationTime": "2026-05-28T14:00:00.000Z",
      "behavior": "CALM",
      "cooperative": true,
      "threatToSelf": false,
      "threatToOthers": false,
      "redirectionEffective": true,
      "deEscalationUsed": false,
      "providerNotified": false
    },
  },
  {
    cardId: "belongings_altered_patient",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T12:00:00.000Z",
      "patientCondition": "UNCONSCIOUS",
      "belongingsInventoriedByTwoStaff": true,
      "bagIdentifier": "BAG-ALT",
      "valuablesPresent": false,
      "securityNotified": true,
      "familyNotified": false
    },
  },
  {
    cardId: "belongings_inventory",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T12:00:00.000Z",
      "patientAbleToParticipate": true,
      "clothingItems": [
        "Coat"
      ],
      "personalItems": [],
      "assistiveDevices": [],
      "medicationsBroughtFromHome": false,
      "belongingsKeptWithPatient": true,
      "belongingsBagged": false
    },
  },
  {
    cardId: "belongings_release_representative",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "releasedAt": "2026-05-28T12:00:00.000Z",
      "bagIdentifier": "BAG-REL",
      "recipientName": "Family member",
      "recipientRelationship": "SPOUSE",
      "recipientIdChecked": true,
      "patientAuthorizedRelease": true,
      "releaseReason": "DISCHARGE_PLANNING"
    },
  },
  {
    cardId: "belongings_return_patient",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "returnedAt": "2026-05-28T12:00:00.000Z",
      "bagIdentifier": "BAG-RET",
      "patientReceived": true,
      "patientUnableToSign": false,
      "discrepancyReported": false
    },
  },
  {
    cardId: "belongings_secured_bagged",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "securedAt": "2026-05-28T12:00:00.000Z",
      "bagIdentifier": "BAG-001",
      "sealedByUserAcknowledged": true,
      "patientLabelApplied": true,
      "storageLocation": "WITH_PATIENT",
      "witnessRequired": false
    },
  },
  {
    cardId: "belongings_transfer_security",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "transferredAt": "2026-05-28T12:00:00.000Z",
      "bagIdentifier": "BAG-SEC",
      "transferredByUserAcknowledged": true,
      "receivedBySecurityName": "Security Desk",
      "storageLocation": "SECURITY"
    },
  },
  {
    cardId: "blood_culture_documentation",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "culturesCollected": "YES",
      "collectionTime": "2026-05-28T14:00:00.000Z",
      "numberOfSets": 2,
      "collectedBeforeAntibiotics": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "braden_risk_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "sensoryPerception": 4,
      "moisture": 4,
      "activity": 4,
      "mobility": 4,
      "nutrition": 4,
      "frictionShear": 3,
      "totalScore": 23,
      "riskLevel": "MINIMAL",
      "preventionPlanReviewed": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "cardiac_escalation_event",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T15:00:00.000Z",
      "escalationReason": "STEMI_ALERT",
      "providerNotified": "YES",
      "providerNotificationTime": "2026-05-28T15:00:00.000Z",
      "responseReceived": "YES"
    },
  },
  {
    cardId: "caregiver_education_session",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "educationTime": "2026-05-28T14:00:00.000Z",
      "caregiverPresent": "YES",
      "caregiverRelationship": "SPOUSE",
      "educationTopic": "MEDICATIONS",
      "teachBackCompleted": "YES",
      "understandingDemonstrated": "YES"
    },
  },
  {
    cardId: "chest_pain_reassessment",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "painScore": 4,
      "painImproved": "YES",
      "painResolved": "NO",
      "radiationPresent": "NO",
      "shortnessOfBreath": "NO",
      "diaphoresis": "NO",
      "repeatECGPerformed": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "chronic_pain_assessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "baselinePainScore": 5,
      "currentPainScore": 6,
      "painManagementPlanPresent": true,
      "opioidTherapyReported": true,
      "painInterferesWithSleep": true,
      "painInterferesWithMobility": true,
      "painInterferesWithADLs": false,
      "providerManagingPainKnown": true
    },
  },
  {
    cardId: "continuous_cardiac_monitoring",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "monitorType": "ICU_MONITOR",
      "rhythm": "VTACH",
      "heartRate": 180,
      "ectopyPresent": "YES",
      "alarmEventsPresent": "YES",
      "patientSymptomatic": "YES",
      "providerNotified": "YES",
      "notes": "Patient diaphoretic and pale."
    },
  },
  {
    cardId: "crrt_monitoring_reference",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "crrtStatus": "IN_PROGRESS",
      "accessStatus": "PATENT",
      "filterConcern": "NO",
      "hemodynamicInstability": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "daily_weight_edema_monitoring",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "weightKg": 85.2,
      "previousWeightKg": 82,
      "weightChangeKg": 3.2,
      "edemaPresent": "YES",
      "edemaLocation": "GENERALIZED",
      "edemaSeverity": "THREE_PLUS",
      "fluidOverloadConcern": "YES",
      "providerNotified": "YES",
      "notes": "Patient reports increased swelling over 48 hours."
    },
  },
  {
    cardId: "dialysis_access_assessment",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "accessType": "TUNNELED_CATHETER",
      "accessLocation": "LEFT_CHEST",
      "thrillPresent": "NOT_APPLICABLE",
      "bruitPresent": "NOT_APPLICABLE",
      "siteStatus": "NORMAL",
      "dressingStatus": "CLEAN_DRY_INTACT",
      "infectionConcern": "NO",
      "bleedingConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "discharge_instruction_review",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "instructionsReviewed": "YES",
      "warningSignsReviewed": "YES",
      "activityRestrictionsReviewed": "YES",
      "dietInstructionsReviewed": "YES",
      "followUpReviewed": "YES",
      "teachBackCompleted": "YES",
      "understandingDemonstrated": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "disease_specific_education",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "educationTime": "2026-05-28T14:00:00.000Z",
      "condition": "DIABETES",
      "educationProvided": "YES",
      "teachBackCompleted": "YES",
      "understandingDemonstrated": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "ecg_12_lead_documentation",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "ecgTime": "2026-05-28T14:00:00.000Z",
      "reason": "CHEST_PAIN",
      "performed": "YES",
      "transmittedToProvider": "YES",
      "providerReviewed": "YES",
      "criticalFindingPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "edoc_basic_structured_v1",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "items": [
        {
          "key": "Pain",
          "value": "secret clinical text"
        }
      ]
    },
  },
  {
    cardId: "education_refusal_or_inability",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "reason": "PATIENT_REFUSED",
      "additionalAttemptsPlanned": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "elopement_monitoring",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "monitoringTime": "2026-05-28T14:00:00.000Z",
      "patientLocationConfirmed": true,
      "patientInAssignedArea": true,
      "doorExitRiskObserved": false,
      "redirectionRequired": false,
      "securityNotified": false,
      "providerNotified": false
    },
  },
  {
    cardId: "elopement_risk_assessment",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "riskLevel": "LOW",
      "confusedOrDisoriented": false,
      "attemptedToLeave": false,
      "verbalizedIntentToLeave": false,
      "requiresSecureArea": false,
      "providerNotified": false,
      "familyNotified": false
    },
  },
  {
    cardId: "environmental_safety_check",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "checkTime": "2026-05-28T14:00:00.000Z",
      "roomClearedOfHazards": true,
      "ligatureRiskChecked": true,
      "sharpsRemoved": true,
      "cordsSecured": true,
      "belongingsSecured": true,
      "bathroomChecked": true,
      "staffAwareOfPrecautions": true,
      "issuesFound": false,
      "providerNotified": false
    },
  },
  {
    cardId: "equipment_education",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "educationTime": "2026-05-28T14:00:00.000Z",
      "equipmentType": "OXYGEN",
      "demonstrationProvided": "YES",
      "returnDemonstrationCompleted": "YES",
      "understandingDemonstrated": "YES"
    },
  },
  {
    cardId: "fall_escalation_event",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "eventTime": "2026-05-28T15:00:00.000Z",
      "reason": "RECURRENT_FALLS",
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T15:00:00.000Z",
      "responseReceived": true,
      "additionalInterventionsOrdered": true
    },
  },
  {
    cardId: "fall_event_documentation",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "witnessed": "YES",
      "location": "Patient room",
      "headStrikeSuspected": true,
      "lossOfConsciousness": false,
      "injuryObserved": true,
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z",
      "familyNotified": true,
      "rapidResponseActivated": false,
      "notes": "Patient found on floor near bed."
    },
  },
  {
    cardId: "fall_risk_reassessment",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "previousRiskLevel": "MODERATE",
      "currentRiskLevel": "MODERATE",
      "changeDetected": false,
      "providerNotified": false
    },
  },
  {
    cardId: "fluid_restriction_monitoring",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "fluidRestrictionOrdered": "YES",
      "restrictionAmountMlPerDay": 1500,
      "patientEducationProvided": "YES",
      "complianceConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "fluid_resuscitation_monitoring",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "fluidBolusOrderedOrStarted": "YES",
      "fluidType": "NORMAL_SALINE",
      "volumeMl": 1000,
      "thirtyMlPerKgTargetConsidered": "YES",
      "bloodPressureResponse": "IMPROVED",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "follow_up_review",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "followUpDiscussed": "YES",
      "appointmentNeeded": "NO",
      "appointmentScheduled": "UNKNOWN",
      "specialistFollowUpNeeded": "NO",
      "transportationConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "frequent_neuro_reassessment",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "frequency": "Q1H",
      "neuroStatus": "UNCHANGED",
      "providerNotified": false
    },
  },
  {
    cardId: "glasgow_coma_scale",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "eye": 4,
      "verbal": 5,
      "motor": 6,
      "totalScore": 15,
      "severityBand": "MILD",
      "providerNotified": true
    },
  },
  {
    cardId: "glasgow_coma_scale_assessment",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "eyeOpening": 4,
      "verbalResponse": 5,
      "motorResponse": 6,
      "calculatedTotal": 15,
      "severity": "MILD",
      "providerNotified": false
    },
  },
  {
    cardId: "head_to_toe_assessment",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "neuro": "WDL",
      "respiratory": "WDL",
      "cardiac": "WDL",
      "gastrointestinal": "WDL",
      "genitourinary": "WDL",
      "skin": "WDL",
      "musculoskeletal": "WDL",
      "psychosocial": "WDL",
      "abnormalFindingsPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "hemodialysis_monitoring_reference",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "dialysisStatus": "COMPLETED",
      "estimatedFluidRemovedMl": 1500,
      "bloodPressureConcern": "NO",
      "crampingReported": "NO",
      "accessIssueObserved": "NO",
      "dialysisNurseNotified": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "io_blood_product_intake",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T16:00:00.000Z",
      "amount": 350,
      "unit": "ML",
      "productType": "PRBC",
      "transfusionRecordLinked": false,
      "reactionSuspected": false
    },
  },
  {
    cardId: "io_drain_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "amount": 50,
      "unit": "ML",
      "drainType": "JP",
      "appearance": "SEROSANGUINOUS"
    },
  },
  {
    cardId: "io_emesis_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "occurrenceCount": 2,
      "appearance": "BILIOUS",
      "amount": 100,
      "unit": "ML"
    },
  },
  {
    cardId: "io_fluid_intake",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "amount": 500,
      "unit": "ML",
      "route": "IV",
      "fluidType": "Normal saline"
    },
  },
  {
    cardId: "io_intake_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "summaryStartTime": "2026-05-28T12:00:00.000Z",
      "summaryEndTime": "2026-05-28T14:00:00.000Z",
      "totalIntakeMl": 1200,
      "totalOutputMl": 800,
      "netBalanceMl": 400,
      "includesEstimatedValues": false,
      "reviewedByNurse": true,
      "providerNotified": false
    },
  },
  {
    cardId: "io_iv_intake",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "amount": 1000,
      "unit": "ML",
      "fluidType": "LR",
      "infusionRelated": true
    },
  },
  {
    cardId: "io_ng_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "amount": 75,
      "unit": "ML",
      "appearance": "BILIOUS",
      "suctionType": "LOW_INTERMITTENT"
    },
  },
  {
    cardId: "io_po_intake",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "amount": 240,
      "unit": "ML",
      "substance": "water",
      "tolerated": "YES",
      "nausea": false,
      "vomiting": false
    },
  },
  {
    cardId: "io_stool_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T14:00:00.000Z",
      "occurrenceCount": 1,
      "consistency": "FORMED"
    },
  },
  {
    cardId: "io_urine_output",
    category: "INTAKE_OUTPUT",
    payload: {
      "recordedAt": "2026-05-28T15:00:00.000Z",
      "amount": 400,
      "unit": "ML",
      "method": "FOLEY"
    },
  },
  {
    cardId: "lactate_monitoring",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "lactateValue": 2.5,
      "lactateUnit": "MMOL_L",
      "lactateResultAvailable": "YES",
      "repeatLactateNeeded": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "learning_barrier_assessment",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "barrierPresent": "NO",
      "barrierType": "NONE",
      "interpreterNeeded": "NO",
      "caregiverInvolved": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "masd_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "source": "INCONTINENCE",
      "severity": "MILD",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "medication_education_review",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "medicationsReviewed": "YES",
      "highRiskMedicationIncluded": "NO",
      "sideEffectsReviewed": "YES",
      "adherenceDiscussed": "YES",
      "teachBackCompleted": "YES",
      "understandingDemonstrated": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "mobility_ambulation_assessment",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "mobilityLevel": "STANDBY_ASSIST",
      "ambulationDistance": 40,
      "distanceUnit": "FEET",
      "assistiveDevice": "WALKER",
      "gaitStability": "STABLE",
      "toleratedActivity": true,
      "providerNotified": false
    },
  },
  {
    cardId: "morse_fall_risk_assessment",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "historyOfFalling": "NO",
      "secondaryDiagnosis": "NO",
      "ambulatoryAid": "NONE",
      "ivTherapy": "NO",
      "gait": "WEAK",
      "mentalStatus": "ORIENTED",
      "calculatedScore": 10,
      "riskLevel": "LOW",
      "providerNotified": false
    },
  },
  {
    cardId: "motor_strength_assessment",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "lue": 5,
      "rue": 4,
      "lle": 5,
      "rle": 5,
      "pronatorDrift": "NONE",
      "providerNotified": false
    },
  },
  {
    cardId: "near_fall_event",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "location": "Bathroom",
      "assistedToSafety": true,
      "injuryObserved": false,
      "providerNotified": true,
      "familyNotified": false
    },
  },
  {
    cardId: "nebulizer_reassessment",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "reassessmentTime": "2026-05-28T14:00:00.000Z",
      "treatmentMedicationReferenced": "ALBUTEROL",
      "treatmentDocumentedInMar": true,
      "respiratoryRate": 20,
      "spo2": 95,
      "breathSoundsAfter": "CLEAR",
      "workOfBreathingAfter": "NORMAL",
      "patientReportsImprovement": true,
      "adverseEffectObserved": false,
      "providerNotified": false
    },
  },
  {
    cardId: "neuro_checks",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "levelOfConsciousness": "LETHARGIC",
      "orientation": "X2",
      "speech": "SLURRED",
      "sensation": "DECREASED",
      "facialDroop": "LEFT",
      "seizureActivityObserved": false,
      "providerNotified": true,
      "notes": "New left facial droop noted."
    },
  },
  {
    cardId: "neuro_escalation_event",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:30:00.000Z",
      "reason": "NIHSS_WORSENING",
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:31:00.000Z",
      "responseReceived": true,
      "rapidResponseActivated": false,
      "strokeAlertActivated": true
    },
  },
  {
    cardId: "neurological_escalation_event",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "newDeficit": true,
      "mentalStatusDecline": false,
      "gcsDrop": false,
      "pupilChange": false,
      "strokeSymptoms": true,
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z"
    },
  },
  {
    cardId: "neurological_initial_assessment",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "orientationPerson": true,
      "orientationPlace": true,
      "orientationTime": true,
      "orientationSituation": true,
      "speechStatus": "SLURRED",
      "facialSymmetry": "DROOP_LEFT",
      "leftArmStrength": "2/5",
      "rightArmStrength": "5/5",
      "leftLegStrength": "3/5",
      "rightLegStrength": "5/5",
      "sensationStatus": "DECREASED",
      "leftPupilSizeMm": 4,
      "rightPupilSizeMm": 2,
      "leftPupilReaction": "SLUGGISH",
      "rightPupilReaction": "BRISK",
      "notes": "Left-sided weakness."
    },
  },
  {
    cardId: "neurological_post_thrombolytic_monitoring",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "administrationTime": "2026-05-28T14:00:00.000Z",
      "monitoringInterval": "15_MIN",
      "neuroStatus": "STABLE",
      "systolicBp": 130,
      "diastolicBp": 85,
      "bleedingSigns": false,
      "neurologicalWorsening": false,
      "providerNotified": false
    },
  },
  {
    cardId: "neurological_reassessment",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "mentalStatus": "ALERT",
      "orientationChanged": false,
      "motorChanged": false,
      "sensoryChanged": false,
      "speechChanged": false,
      "priorSpeechStatus": "CLEAR",
      "speechStatus": "CLEAR",
      "pupilChanged": false,
      "leftPupilSizeMm": 3,
      "rightPupilSizeMm": 3,
      "leftPupilReaction": "BRISK",
      "rightPupilReaction": "BRISK",
      "newDeficit": false,
      "newUnilateralWeakness": false,
      "providerNotified": false
    },
  },
  {
    cardId: "nihss_assessment",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "levelOfConsciousness": 2,
      "locQuestions": 1,
      "locCommands": 1,
      "bestGaze": 1,
      "visualFields": 1,
      "facialPalsy": 2,
      "motorArmLeft": 3,
      "motorArmRight": 2,
      "motorLegLeft": 2,
      "motorLegRight": 1,
      "limbAtaxia": 1,
      "sensory": 1,
      "bestLanguage": 2,
      "dysarthria": 1,
      "extinctionInattention": 1,
      "calculatedTotal": 22,
      "severity": "SEVERE",
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z",
      "notes": "Left-sided weakness worsening."
    },
  },
  {
    cardId: "nihss_reassessment",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "levelOfConsciousness": 0,
      "locQuestions": 1,
      "locCommands": 0,
      "bestGaze": 0,
      "visualFields": 0,
      "facialPalsy": 1,
      "motorArmLeft": 2,
      "motorArmRight": 0,
      "motorLegLeft": 1,
      "motorLegRight": 0,
      "limbAtaxia": 0,
      "sensory": 0,
      "bestLanguage": 0,
      "dysarthria": 0,
      "extinctionInattention": 0,
      "totalScore": 5,
      "previousScore": 3,
      "scoreChange": 2,
      "worseningDetected": true,
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z"
    },
  },
  {
    cardId: "nursing_admission_assessment",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "admissionSource": "ED",
      "admissionReason": "Chest pain observation",
      "baselineMentalStatus": "ALERT_ORIENTED",
      "baselineMobility": "INDEPENDENT",
      "fallRiskReviewed": "YES",
      "skinAssessmentCompleted": "YES",
      "painAssessmentCompleted": "YES",
      "belongingsReviewed": "YES",
      "homeMedicationsReviewed": "YES",
      "allergiesReviewed": "YES",
      "advanceDirectivesReviewed": "UNKNOWN",
      "infectionScreeningCompleted": "YES",
      "educationNeedsIdentified": "NO",
      "interpreterNeeded": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_care_plan_initiation",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "initiatedAt": "2026-05-28T14:00:00.000Z",
      "primaryNursingProblem": "FALL_RISK",
      "goal": "NO_FALLS",
      "interventionsPlanned": [
        "SAFETY_PRECAUTIONS",
        "EDUCATION"
      ],
      "patientParticipated": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_care_plan_update",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "updatedAt": "2026-05-28T14:00:00.000Z",
      "problemAddressed": "Fall risk",
      "goalStatus": "IN_PROGRESS",
      "interventionStatus": "CONTINUED",
      "patientProgress": "IMPROVED",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_discharge_readiness_review",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "vitalSignsStable": "YES",
      "painControlled": "YES",
      "mobilitySafe": "YES",
      "educationCompleted": "YES",
      "medicationsReviewed": "YES",
      "followUpReviewed": "YES",
      "transportationConfirmed": "YES",
      "responsibleAdultPresent": "NOT_APPLICABLE",
      "barriersPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_handoff_shift_report",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "handoffTime": "2026-05-28T14:00:00.000Z",
      "handoffType": "SHIFT_CHANGE",
      "receivingRole": "RN",
      "highRiskConcernsPresent": "NO",
      "openTasksReviewed": "YES",
      "medicationConcernsReviewed": "YES",
      "fallRiskReviewed": "YES",
      "linesTubesDrainsReviewed": "YES",
      "pendingLabsImagingReviewed": "YES",
      "familyCommunicationNeeds": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_patient_goals_outcomes",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "goalType": "MOBILITY",
      "goalDescription": "Ambulate with walker",
      "outcomeStatus": "IN_PROGRESS",
      "barrierPresent": "NO"
    },
  },
  {
    cardId: "nursing_problem_list",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "problem": "PAIN",
      "status": "MONITORING",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "nursing_shift_assessment",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "shift": "DAY",
      "mentalStatus": "ALERT_ORIENTED",
      "respiratoryStatus": "STABLE",
      "cardiacStatus": "STABLE",
      "giStatus": "NORMAL",
      "guStatus": "NORMAL",
      "skinStatus": "INTACT",
      "mobilityStatus": "INDEPENDENT",
      "painStatus": "NO_PAIN",
      "safetyStatus": "STANDARD",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "obs_ambulation_trial",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "assistanceLevel": "ONE_PERSON",
      "distance": 100,
      "distanceUnit": "FEET",
      "gaitSteady": true,
      "dizziness": false,
      "shortnessOfBreath": false,
      "pain": false,
      "oxygenDesaturation": false,
      "result": "PARTIAL"
    },
  },
  {
    cardId: "obs_boarding",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "boardingReason": "ED capacity",
      "location": "Hall B",
      "safetyCheckCompleted": true,
      "comfortMeasuresOffered": true,
      "nutritionOffered": false,
      "toiletingOffered": true,
      "providerUpdated": false
    },
  },
  {
    cardId: "obs_discharge_readiness",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "instructionsReviewed": true,
      "medicationsReviewed": true,
      "followUpReviewed": true,
      "returnPrecautionsReviewed": true,
      "transportationConfirmed": true,
      "patientVerbalizedUnderstanding": true,
      "barriersIdentified": false
    },
  },
  {
    cardId: "obs_po_challenge",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "startTime": "2026-05-28T14:00:00.000Z",
      "substance": "Jello",
      "amount": "1 cup",
      "tolerated": "YES",
      "nausea": false,
      "vomiting": false,
      "abdominalPain": false,
      "result": "PASSED",
      "notes": "Patient tolerated well — should not appear in audit"
    },
  },
  {
    cardId: "obs_reassessment",
    category: "OBSERVATION_DOCUMENTATION",
    payload: {
      "reassessmentTime": "2026-05-28T14:00:00.000Z",
      "patientCondition": "IMPROVED",
      "vitalsReviewed": true,
      "pendingResults": false,
      "providerNotified": true,
      "painScore": 3
    },
  },
  {
    cardId: "one_to_one_observation_check",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "checkTime": "2026-05-28T14:00:00.000Z",
      "observerRole": "SITTER",
      "patientVisible": true,
      "patientSafe": true,
      "behaviorObserved": "CALM",
      "needsAddressed": true,
      "handoffCompleted": false,
      "providerNotified": false
    },
  },
  {
    cardId: "ostomy_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "ostomyType": "COLOSTOMY",
      "stomaAppearance": "PINK",
      "outputPresent": "YES",
      "skinIntact": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "oxygen_therapy_initiation",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "startedAt": "2026-05-28T14:00:00.000Z",
      "oxygenDevice": "NASAL_CANNULA",
      "flowRate": 2,
      "flowUnit": "LPM",
      "spo2Before": 88,
      "spo2After": 94,
      "reason": "HYPOXIA",
      "providerOrderVerified": true,
      "patientTolerated": true
    },
  },
  {
    cardId: "oxygen_titration",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "titrationTime": "2026-05-28T14:00:00.000Z",
      "previousDevice": "NASAL_CANNULA",
      "newDevice": "SIMPLE_MASK",
      "newFlowRate": 6,
      "flowUnit": "LPM",
      "spo2Before": 90,
      "spo2After": 96,
      "reason": "SPO2_LOW",
      "providerNotified": false,
      "patientTolerated": true
    },
  },
  {
    cardId: "pacemaker_monitoring",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "pacedRhythmObserved": "YES",
      "capturePresent": "YES",
      "patientStable": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "pain_escalation_event",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "reason": "UNCONTROLLED_PAIN",
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z",
      "responseReceived": true,
      "additionalInterventionOrdered": true
    },
  },
  {
    cardId: "pain_initial_assessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "painScale": "NUMERIC",
      "painScore": 9,
      "painLocation": "CHEST",
      "painQuality": "PRESSURE",
      "painDuration": "NEW",
      "painRadiation": "PRESENT",
      "painRadiationDescription": "Left arm",
      "functionalImpact": "SEVERE",
      "providerNotified": true,
      "notes": "Patient clutching chest."
    },
  },
  {
    cardId: "pain_post_intervention_reassessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "interventionType": "MEDICATION",
      "painScoreBefore": 8,
      "painScoreAfter": 4,
      "response": "IMPROVED",
      "providerNotified": false
    },
  },
  {
    cardId: "pain_reassessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "painScale": "NUMERIC",
      "painScore": 3,
      "previousPainScore": 6,
      "painImproved": true,
      "functionalImpact": "MILD",
      "providerNotified": false
    },
  },
  {
    cardId: "patient_education_session",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "educationTime": "2026-05-28T14:00:00.000Z",
      "topic": "OTHER",
      "audience": "PATIENT",
      "interpreterUsed": "NO",
      "educationProvided": "YES",
      "understandingDemonstrated": "PARTIAL",
      "providerNotified": "YES",
      "notes": "Patient asked repeated questions about wound care supplies."
    },
  },
  {
    cardId: "pediatric_pain_assessment",
    category: "PAIN_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "face": 1,
      "legs": 1,
      "activity": 1,
      "cry": 0,
      "consolability": 1,
      "totalScore": 4,
      "providerNotified": false
    },
  },
  {
    cardId: "peritoneal_dialysis_monitoring_reference",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "pdStatus": "COMPLETED",
      "effluentAppearance": "CLEAR",
      "abdominalPain": "NO",
      "exitSiteConcern": "NO",
      "exchangeCompleted": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "post_fall_assessment",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "assessmentTime": "2026-05-28T14:30:00.000Z",
      "painPresent": true,
      "injuryIdentified": false,
      "neurologicStatus": "BASELINE",
      "mobilityStatus": "BASELINE",
      "vitalSignsObtained": true,
      "providerEvaluated": true,
      "imagingOrdered": false
    },
  },
  {
    cardId: "post_thrombolytic_monitoring",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T15:00:00.000Z",
      "therapy": "TNK",
      "bloodPressure": "130/82",
      "heartRate": 84,
      "neuroStatusStable": true,
      "bleedingObserved": false,
      "headachePresent": false,
      "bpWithinParameters": "YES",
      "neuroChangePresent": "NO",
      "bleedingConcern": "NO",
      "providerNotified": false
    },
  },
  {
    cardId: "pressure_injury_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "location": "SACRUM",
      "stage": "STAGE_2",
      "drainagePresent": "NO",
      "infectionConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "pressure_injury_reassessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "existingPressureInjuryLocation": "Sacrum",
      "status": "IMPROVED",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "proc_lumbar_puncture",
    category: "PROCEDURE_MONITORING",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "postProcedurePosition": "SUPINE",
      "neuroStatus": "BASELINE",
      "headachePresent": "NO",
      "backPainPresent": "NO",
      "bleedingPresent": "NO",
      "csfLeakConcern": "NO",
      "nauseaVomitingPresent": "NO",
      "vitalSignsStable": "YES",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "proc_timeout",
    category: "PROCEDURE_MONITORING",
    payload: {
      "timeoutTime": "2026-05-28T14:00:00.000Z",
      "procedureType": "CENTRAL_LINE",
      "patientIdentityConfirmed": "YES",
      "procedureConfirmed": "YES",
      "siteConfirmed": "YES",
      "consentVerified": "YES",
      "allergiesReviewed": "YES",
      "anticoagulationReviewed": "NOT_APPLICABLE",
      "imagingReviewed": "NOT_APPLICABLE",
      "labsReviewed": "NOT_APPLICABLE",
      "equipmentAvailable": "YES",
      "bloodProductsAvailable": "NOT_APPLICABLE",
      "participantsPresent": "YES",
      "providerPresent": "YES",
      "nursePresent": "YES",
      "timeoutCompleted": "YES",
      "procedureHeld": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "pupillary_assessment",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "leftPupilSize": 3,
      "rightPupilSize": 4,
      "leftReaction": "BRISK",
      "rightReaction": "SLUGGISH",
      "anisocoriaPresent": true,
      "providerNotified": true
    },
  },
  {
    cardId: "qsofa_assessment",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "respiratoryRateHigh": "YES",
      "alteredMentation": "YES",
      "systolicBpLow": "NO",
      "score": 2,
      "qsofaPositive": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "qtc_monitoring",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "qtcValue": 420,
      "highRiskMedicationPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "renal_escalation_event",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "reason": "FLUID_OVERLOAD",
      "providerNotified": "YES",
      "providerNotificationTime": "2026-05-28T14:05:00.000Z",
      "nephrologyNotified": "YES",
      "responseReceived": "NO",
      "rapidResponseActivated": "NO"
    },
  },
  {
    cardId: "renal_intake_output_review",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "reviewPeriod": "SHIFT",
      "totalIntakeMl": 2000,
      "totalOutputMl": 1500,
      "netBalanceMl": 500,
      "fluidBalanceConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "renal_medication_safety_review",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "reviewTime": "2026-05-28T14:00:00.000Z",
      "renalFunctionConcern": "NO",
      "nephrotoxicMedicationConcern": "YES",
      "doseAdjustmentConcern": "NO",
      "contrastExposureConcern": "NO",
      "pharmacyNotified": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "resp_assessment",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "respiratoryRate": 20,
      "spo2": 95,
      "oxygenDevice": "NASAL_CANNULA",
      "oxygenFlowRate": 2,
      "workOfBreathing": "NORMAL",
      "breathSounds": "CLEAR",
      "breathSoundsLocation": "BILATERAL",
      "cough": "NONE",
      "sputumPresent": false,
      "accessoryMuscleUse": false,
      "retractions": false,
      "cyanosis": false,
      "patientPosition": "SEMI_FOWLER",
      "providerNotified": false
    },
  },
  {
    cardId: "resp_cpap_bipap",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "monitoringTime": "2026-05-28T14:00:00.000Z",
      "mode": "CPAP",
      "deviceSettingSummary": "CPAP 8",
      "respiratoryRate": 18,
      "spo2": 96,
      "maskFit": "GOOD",
      "skinIntegrity": "INTACT",
      "patientTolerance": "TOLERATING",
      "providerNotified": false
    },
  },
  {
    cardId: "resp_peak_flow",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "measuredAt": "2026-05-28T14:00:00.000Z",
      "preTreatmentPeakFlow": 220,
      "postTreatmentPeakFlow": 310,
      "personalBestKnown": false,
      "effortQuality": "GOOD",
      "providerNotified": false
    },
  },
  {
    cardId: "resp_ventilator",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "observationTime": "2026-05-28T14:00:00.000Z",
      "ventilatorMode": "AC",
      "fio2Percent": 60,
      "peep": 8,
      "respiratoryRateObserved": 16,
      "spo2": 97,
      "airwaySecured": true,
      "alarmObserved": true,
      "alarmDescription": "High peak pressure",
      "rtNotified": true,
      "providerNotified": true,
      "notes": "RT at bedside within 5 min."
    },
  },
  {
    cardId: "respiratory_distress_reassessment",
    category: "RESPIRATORY_DOCUMENTATION",
    payload: {
      "reassessmentTime": "2026-05-28T14:00:00.000Z",
      "respiratoryRate": 32,
      "spo2": 86,
      "workOfBreathing": "SEVERE_DISTRESS",
      "oxygenDevice": "NON_REBREATHER",
      "oxygenFlowRate": 15,
      "accessoryMuscleUse": true,
      "retractions": true,
      "mentalStatus": "ANXIOUS",
      "interventionPerformed": "OXYGEN_INCREASED",
      "providerNotified": true,
      "rapidResponseActivated": false
    },
  },
  {
    cardId: "rhythm_strip_documentation",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "rhythm": "SINUS_RHYTHM",
      "rate": 78,
      "stripReviewedByClinician": "YES",
      "interpretation": "NORMAL",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "safety_precautions_documentation",
    category: "FALL_RISK_AND_SAFETY",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "bedAlarmActive": true,
      "chairAlarmActive": false,
      "nonSlipFootwearApplied": true,
      "callLightWithinReach": true,
      "bedInLowestPosition": true,
      "sideRailsAppropriate": true,
      "assistiveDeviceAvailable": true,
      "fallRiskBandApplied": true,
      "familyEducated": true,
      "patientEducated": true
    },
  },
  {
    cardId: "seizure_event_documentation",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "witnessed": true,
      "startTime": "2026-05-28T14:00:00.000Z",
      "endTime": "2026-05-28T14:03:00.000Z",
      "durationMinutes": 3,
      "seizureType": "FOCAL",
      "auraPresent": false,
      "incontinence": false,
      "injury": false,
      "postictalState": "MILD",
      "benzodiazepineAdministered": false,
      "rescueMedicationGiven": false,
      "providerNotified": true,
      "providerNotificationTime": "2026-05-28T14:05:00.000Z"
    },
  },
  {
    cardId: "sepsis_bundle_tracking",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "bundleStartTime": "2026-05-28T14:00:00.000Z",
      "bundleType": "THREE_HOUR",
      "lactateOrderedOrResulted": "YES",
      "bloodCulturesBeforeAntibiotics": "YES",
      "antibioticsDocumentedInMar": "YES",
      "fluidsOrderedOrStarted": "YES",
      "vasopressorsOrderedOrStarted": "NOT_APPLICABLE",
      "providerNotified": "YES",
      "bundleVariancePresent": "NO"
    },
  },
  {
    cardId: "sepsis_escalation_event",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "eventTime": "2026-05-28T14:00:00.000Z",
      "reason": "LACTATE_ELEVATED",
      "providerNotified": "YES",
      "providerNotificationTime": "2026-05-28T14:00:00.000Z",
      "responseReceived": "YES",
      "rapidResponseActivated": "NO"
    },
  },
  {
    cardId: "sepsis_screening",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "screeningTime": "2026-05-28T14:00:00.000Z",
      "suspectedInfection": "YES",
      "temperatureAbnormal": "YES",
      "heartRateAbnormal": "YES",
      "respiratoryRateAbnormal": "NO",
      "wbcAbnormalOrUnknown": "NO",
      "alteredMentalStatus": "NO",
      "hypotensionPresent": "NO",
      "lactateConcern": "NO",
      "screenPositive": "YES",
      "providerNotified": "YES",
      "providerNotificationTime": "2026-05-28T14:00:00.000Z"
    },
  },
  {
    cardId: "septic_shock_reassessment",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "reassessmentTime": "2026-05-28T14:00:00.000Z",
      "hypotensionPersistent": "YES",
      "lactateFourOrGreater": "YES",
      "vasopressorsStartedOrOrdered": "YES",
      "mentalStatusChanged": "NO",
      "urineOutputConcern": "YES",
      "providerAtBedside": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "sirs_assessment",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "temperatureCriteriaMet": "YES",
      "heartRateCriteriaMet": "YES",
      "respiratoryCriteriaMet": "NO",
      "wbcCriteriaMet": "NO",
      "criteriaCount": 2,
      "sirsPositive": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "skin_integrity_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "skinStatus": "INTACT",
      "pressureInjuryPresent": "NO",
      "woundPresent": "NO",
      "skinTearPresent": "NO",
      "masdPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "skin_tear_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "tearCategory": "CATEGORY_1",
      "bleedingPresent": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "stemi_alert_event",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "activationTime": "2026-05-28T14:00:00.000Z",
      "activationReason": "STEMI",
      "cathLabActivated": "YES",
      "providerAtBedside": "YES",
      "cardiologyNotified": "YES",
      "transferRequired": "NO"
    },
  },
  {
    cardId: "stroke_abcd2",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "age60OrOlder": true,
      "bloodPressureElevated": true,
      "clinicalFeature": "UNILATERAL_WEAKNESS",
      "duration": "GREATER_EQUAL_60_MIN",
      "diabetes": false,
      "totalScore": 6
    },
  },
  {
    cardId: "stroke_alert_event",
    category: "NEUROLOGICAL_DOCUMENTATION",
    payload: {
      "lastKnownWell": "2026-05-28T12:00:00.000Z",
      "symptomOnsetTime": "2026-05-28T13:00:00.000Z",
      "strokeAlertActivated": true,
      "activationTime": "2026-05-28T13:30:00.000Z",
      "provider": "Dr Dupont",
      "neurologyNotified": true,
      "ctOrdered": true,
      "thrombolyticCandidate": true
    },
  },
  {
    cardId: "stroke_cincinnati",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "facialDroop": "NORMAL",
      "armDrift": "NORMAL",
      "speech": "NORMAL",
      "result": "NEGATIVE",
      "providerNotified": false
    },
  },
  {
    cardId: "stroke_neuro_checks",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "levelOfConsciousness": "Alert",
      "orientation": "x4",
      "pupils": "PERRLA",
      "gripLeft": "Strong",
      "gripRight": "Strong",
      "motorLeft": "5/5",
      "motorRight": "5/5",
      "sensation": "Intact",
      "speech": "Clear",
      "changesFromPrior": "NO",
      "providerNotified": false
    },
  },
  {
    cardId: "stroke_nihss",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "levelOfConsciousness": 0,
      "locQuestions": 1,
      "locCommands": 0,
      "bestGaze": 0,
      "visualFields": 0,
      "facialPalsy": 1,
      "motorArmLeft": 2,
      "motorArmRight": 0,
      "motorLegLeft": 1,
      "motorLegRight": 0,
      "limbAtaxia": 0,
      "sensory": 0,
      "bestLanguage": 0,
      "dysarthria": 0,
      "extinctionInattention": 0,
      "totalScore": 5
    },
  },
  {
    cardId: "stroke_swallow_screen",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "screenedAt": "2026-05-28T14:00:00.000Z",
      "alertEnoughForScreen": true,
      "facialDroopOrWeakness": false,
      "speechDifficulty": false,
      "coughOrWetVoice": false,
      "failedWaterTrial": false,
      "result": "PASSED",
      "npoRecommended": false,
      "providerNotified": true
    },
  },
  {
    cardId: "stroke_timeline",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "lastKnownWellTime": "2026-05-28T12:00:00.000Z",
      "arrivalTime": "2026-05-28T14:00:00.000Z",
      "ctCompletedTime": "2026-05-28T14:00:00.000Z",
      "thrombolyticDecisionTime": "2026-05-28T14:00:00.000Z"
    },
  },
  {
    cardId: "stroke_tnk",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "administrationTime": "2026-05-28T14:00:00.000Z",
      "lastKnownWellTime": "2026-05-28T12:00:00.000Z",
      "nihssScore": 8,
      "patientWeightKg": 70,
      "doseMg": 50,
      "doseVerified": "YES",
      "ctHeadReviewed": "YES",
      "contraindicationChecklistReviewed": "YES",
      "providerOrderVerified": "YES",
      "neurologyConsulted": "NOT_APPLICABLE",
      "bloodPressureWithinParameters": "YES",
      "anticoagulantUseReviewed": "YES",
      "bleedingRiskReviewed": "YES",
      "patientFamilyEducationProvided": "NOT_APPLICABLE",
      "medicationAdministered": "YES",
      "administrationHeld": "NO",
      "providerNotified": "NO",
      "notes": "Patient tolerated well.",
      "holdReason": "BP_OUT_OF_RANGE"
    },
  },
  {
    cardId: "stroke_tpa",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "administrationTime": "2026-05-28T14:00:00.000Z",
      "lastKnownWellTime": "2026-05-28T12:00:00.000Z",
      "nihssScore": 10,
      "patientWeightKg": 80,
      "totalDoseMg": 72,
      "bolusDoseMg": 7.2,
      "infusionDoseMg": 64.8,
      "bolusTime": "2026-05-28T14:00:00.000Z",
      "infusionStartTime": "2026-05-28T14:05:00.000Z",
      "doseVerified": "YES",
      "ctHeadReviewed": "YES",
      "contraindicationChecklistReviewed": "YES",
      "providerOrderVerified": "YES",
      "neurologyConsulted": "NOT_APPLICABLE",
      "bloodPressureWithinParameters": "YES",
      "anticoagulantUseReviewed": "YES",
      "bleedingRiskReviewed": "YES",
      "medicationAdministered": "YES",
      "infusionInterrupted": "NO",
      "administrationHeld": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "stroke_van_assessment",
    category: "STROKE_DOCUMENTATION",
    payload: {
      "assessedAt": "2026-05-28T14:00:00.000Z",
      "armWeaknessPresent": false,
      "visualDisturbance": false,
      "aphasia": false,
      "neglect": false,
      "result": "NEGATIVE",
      "providerNotified": false
    },
  },
  {
    cardId: "suicide_precautions_documentation",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "documentationTime": "2026-05-28T14:00:00.000Z",
      "precautionLevel": "STANDARD",
      "patientChangedIntoSafeAttire": true,
      "belongingsRemovedOrSecured": true,
      "roomSafetyCompleted": true,
      "ligatureRiskReduced": true,
      "sharpsRemoved": true,
      "providerNotified": false,
      "familyNotified": false
    },
  },
  {
    cardId: "suicide_risk_monitoring",
    category: "BEHAVIORAL_HEALTH_DOCUMENTATION",
    payload: {
      "monitoringTime": "2026-05-28T14:00:00.000Z",
      "riskLevel": "HIGH",
      "currentSuicidalIdeation": "ACTIVE",
      "planReported": "YES",
      "intentReported": "YES",
      "meansAccessConcern": "YES",
      "observationLevel": "ONE_TO_ONE",
      "providerNotified": true,
      "notes": "Patient expressed detailed suicidal plan."
    },
  },
  {
    cardId: "surgical_wound_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "incisionType": "SUTURES",
      "approximation": "WELL_APPROXIMATED",
      "drainage": "SEROUS",
      "infectionConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "suspected_infection_assessment",
    category: "SEPSIS_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "suspectedSource": "URINARY",
      "infectionSignsPresent": "YES",
      "culturesConsidered": "YES",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "systems_assessment",
    category: "NURSING_ADMISSION_AND_CARE_PLAN",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "system": "RESPIRATORY",
      "status": "IMPROVED",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "teach_back_verification",
    category: "PATIENT_EDUCATION_AND_DISCHARGE_TEACHING",
    payload: {
      "verificationTime": "2026-05-28T14:00:00.000Z",
      "topicReviewed": "DISCHARGE",
      "teachBackSuccessful": "YES",
      "additionalEducationRequired": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "telemetry_reassessment",
    category: "CARDIAC_MONITORING_DOCUMENTATION",
    payload: {
      "assessmentTime": "2026-05-28T12:00:00.000Z",
      "currentRhythm": "SINUS_RHYTHM",
      "heartRate": 80,
      "bloodPressure": "120/80",
      "symptomatic": "NO",
      "chestPain": "NO",
      "palpitations": "NO",
      "shortnessOfBreath": "NO",
      "changeFromPrevious": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "traumatic_wound_assessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "woundType": "LACERATION",
      "drainage": "NONE",
      "infectionConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "urine_output_concern",
    category: "DIALYSIS_RENAL_FLUID_MANAGEMENT",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "concernType": "OLIGURIA",
      "urineOutputMl": 200,
      "timePeriodHours": 8,
      "foleyPresent": "YES",
      "bladderScanPerformed": "NOT_APPLICABLE",
      "providerNotified": "YES"
    },
  },
  {
    cardId: "valuables_inventory",
    category: "BELONGINGS_VALUABLES_DOCUMENTATION",
    payload: {
      "documentedAt": "2026-05-28T12:00:00.000Z",
      "cashPresent": false,
      "jewelryPresent": false,
      "electronicsPresent": false,
      "walletOrPursePresent": false,
      "keysPresent": false,
      "identificationPresent": false,
      "patientDeclinedValuablesInventory": false,
      "valuablesSecured": false
    },
  },
  {
    cardId: "wound_photo_reference",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "documentedAt": "2026-05-28T14:00:00.000Z",
      "photoObtained": "YES",
      "photoReferenceId": "IMG-SECRET-REF",
      "patientConsentVerified": "YES",
      "providerNotified": "NO",
      "notes": "Detailed wound description narrative."
    },
  },
  {
    cardId: "wound_reassessment",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "assessmentTime": "2026-05-28T14:00:00.000Z",
      "status": "IMPROVED",
      "drainageChanged": "NO",
      "infectionConcern": "NO",
      "providerNotified": "NO"
    },
  },
  {
    cardId: "wound_treatment_documentation",
    category: "SKIN_WOUND_PRESSURE_INJURY",
    payload: {
      "treatmentTime": "2026-05-28T14:00:00.000Z",
      "treatmentType": "DRESSING_CHANGE",
      "tolerated": "YES",
      "providerNotified": "NO"
    },
  }
];

export function getClinicalDocumentationRuntimeCoverageFixtures(): EdocRuntimeCoverageFixture[] {
  const map = new Map<string, EdocRuntimeCoverageFixture>();
  for (const f of [
    ...EDOC_TEST1_ALL_HIGH_RISK_FIXTURES,
    ...EDOC23B_FOUNDATION_COMPLETION_FIXTURES,
    ...RUNTIME_COVERAGE_SUPPLEMENTAL_PAYLOADS,
  ]) {
    map.set(f.cardId, f);
  }

  const available = CLINICAL_DOCUMENTATION_CARDS.filter((c) => c.implementationStatus === "AVAILABLE");
  const fixtures: EdocRuntimeCoverageFixture[] = [];

  for (const card of available) {
    const fixture = map.get(card.id);
    if (!fixture) {
      throw new Error(`Missing runtime coverage fixture for AVAILABLE card "${card.id}"`);
    }
    const validation = validatePayloadForCard(card.id, fixture.payload);
    if (!validation.ok) {
      throw new Error(
        `Invalid runtime coverage payload for "${card.id}": ${validation.ok ? "" : validation.message}`
      );
    }
    const summary = summarizeClinicalDocumentationPayload(card.id, fixture.payload, "en");
    if (summary.length === 0) {
      throw new Error(`Empty EN summary for runtime coverage payload "${card.id}"`);
    }
    if (!getClinicalDocumentationCardById(card.id)) {
      throw new Error(`Registry missing card "${card.id}"`);
    }
    fixtures.push(fixture);
  }

  return fixtures.sort((a, b) => a.cardId.localeCompare(b.cardId));
}

/** Throws if fixture map is incomplete or any payload fails validation. */
export function assertRuntimeCoverageFixtureIntegrity(): void {
  getClinicalDocumentationRuntimeCoverageFixtures();
}
