export const en={
"common.retry":"Retry","common.pending":"Pending","common.approved":"Approved","common.rejected":"Rejected","common.cancelled":"Cancelled","common.expired":"Expired","common.executed":"Executed","common.failed":"Failed","common.approve":"Approve","common.reject":"Reject","common.cancel":"Cancel","common.language":"Language","common.unknownError":"The platform service could not complete this request.",
"navigation.admin":"Platform Admin","navigation.facilities":"Facilities","navigation.staff":"Medora Staff","navigation.security":"Security","navigation.compliance":"Compliance","navigation.billing":"Billing / RCM","navigation.catalog":"Catalog / Configuration","navigation.system":"System Operations","navigation.return":"Return to care workspace","navigation.aria":"Platform Admin navigation",
"platform.workspace":"Platform workspace","platform.enterprise":"Enterprise operations","platform.authorityVerified":"Authority verified","platform.principal":"Platform principal","platform.loadError":"Unable to load this platform data",
"staff.title":"Medora Staff","staff.subtitle":"Authoritative staff personas, lifecycle, and capability administration.","staff.request":"Request provisioning","staff.createRequest":"Create privileged request","staff.governanceTitle":"Platform Governance Setup","staff.governanceDetail":"No independent privileged-action approver is currently configured. Complete the one-time governance bootstrap to establish a second authorized Medora platform administrator.","staff.bootstrap":"Complete governance bootstrap","staff.target":"Eligible target","staff.persona":"Persona","staff.reason":"Reason","staff.ticket":"Ticket/reference","staff.confirm":"I confirm this creates one independent approver with only the capabilities shown.","staff.exactCapabilities":"Exact bootstrap capabilities",
"security.title":"Security","security.subtitle":"Dual-controlled actions and enterprise audit.","error.SELF_APPROVAL_PROHIBITED":"You cannot approve your own privileged-action request.","error.RECENT_SESSION_MFA_REQUIRED":"Recent session-bound MFA verification is required.","error.GOVERNANCE_BOOTSTRAP_CLOSED":"Initial governance setup is already closed.",
"facilities.title":"Facilities","compliance.title":"Compliance","billing.title":"Billing / RCM","catalog.title":"Catalog / Configuration","system.title":"System Operations",
"persona.IMPLEMENTATION":"Implementation","persona.SUPPORT":"Support","persona.BILLING_OPERATIONS":"Billing Operations","persona.COMPLIANCE_SECURITY":"Compliance / Security","persona.PLATFORM_OPERATIONS":"Platform Operations",
"operation.STAFF_PROVISION":"Staff provisioning","operation.STAFF_GRANT_CAPABILITY":"Staff capability grant","operation.FACILITY_ACTIVATION_CHANGE":"Facility activation change","operation.SECURITY_MFA_RESET":"MFA reset",
"capability.PRIVILEGED_ACTION_APPROVE":"Approve privileged actions","capability.COMPLIANCE_AUDIT_VIEW":"View compliance audit","capability.COMPLIANCE_EXPORT_MONITOR":"Monitor compliance exports","capability.COMPLIANCE_ROI_MONITOR":"Monitor release of information","capability.SECURITY_ACCESS_VIEW":"View security access","capability.SECURITY_AUDIT_VIEW":"View security audit"
} as const;export type MessageKey=keyof typeof en;
export const fr:Record<MessageKey,string>={
"common.retry":"Réessayer","common.pending":"En attente","common.approved":"Approuvée","common.rejected":"Rejetée","common.cancelled":"Annulée","common.expired":"Expirée","common.executed":"Exécutée","common.failed":"Échouée","common.approve":"Approuver","common.reject":"Rejeter","common.cancel":"Annuler","common.language":"Langue","common.unknownError":"Le service de plateforme n’a pas pu traiter cette demande.",
"navigation.admin":"Administration de la plateforme","navigation.facilities":"Établissements","navigation.staff":"Personnel Medora","navigation.security":"Sécurité","navigation.compliance":"Conformité","navigation.billing":"Facturation / RCM","navigation.catalog":"Catalogue / Configuration","navigation.system":"Opérations système","navigation.return":"Retour à l’espace de soins","navigation.aria":"Navigation de l’administration de la plateforme",
"platform.workspace":"Espace de la plateforme","platform.enterprise":"Opérations d’entreprise","platform.authorityVerified":"Autorité vérifiée","platform.principal":"Responsable principal de plateforme","platform.loadError":"Impossible de charger ces données de plateforme",
"staff.title":"Personnel Medora","staff.subtitle":"Personas, cycle de vie et capacités du personnel faisant autorité.","staff.request":"Demander le provisionnement","staff.createRequest":"Créer une demande d’action privilégiée","staff.governanceTitle":"Configuration de la gouvernance de plateforme","staff.governanceDetail":"Aucun approbateur indépendant d’actions privilégiées n’est configuré. Effectuez l’amorçage unique pour établir un second administrateur autorisé de la plateforme Medora.","staff.bootstrap":"Terminer l’amorçage de gouvernance","staff.target":"Utilisateur cible admissible","staff.persona":"Persona","staff.reason":"Motif","staff.ticket":"Ticket/référence","staff.confirm":"Je confirme la création d’un approbateur indépendant doté uniquement des capacités affichées.","staff.exactCapabilities":"Capacités exactes d’amorçage",
"security.title":"Sécurité","security.subtitle":"Actions à double contrôle et audit d’entreprise.","error.SELF_APPROVAL_PROHIBITED":"Vous ne pouvez pas approuver votre propre demande d’action privilégiée.","error.RECENT_SESSION_MFA_REQUIRED":"Une vérification MFA récente liée à la session est requise.","error.GOVERNANCE_BOOTSTRAP_CLOSED":"La configuration initiale de gouvernance est déjà close.",
"facilities.title":"Établissements","compliance.title":"Conformité","billing.title":"Facturation / RCM","catalog.title":"Catalogue / Configuration","system.title":"Opérations système",
"persona.IMPLEMENTATION":"Implémentation","persona.SUPPORT":"Assistance","persona.BILLING_OPERATIONS":"Opérations de facturation","persona.COMPLIANCE_SECURITY":"Conformité / Sécurité","persona.PLATFORM_OPERATIONS":"Opérations de plateforme",
"operation.STAFF_PROVISION":"Provisionnement du personnel","operation.STAFF_GRANT_CAPABILITY":"Attribution de capacité au personnel","operation.FACILITY_ACTIVATION_CHANGE":"Modification de l’activation d’un établissement","operation.SECURITY_MFA_RESET":"Réinitialisation MFA",
"capability.PRIVILEGED_ACTION_APPROVE":"Approuver les actions privilégiées","capability.COMPLIANCE_AUDIT_VIEW":"Consulter l’audit de conformité","capability.COMPLIANCE_EXPORT_MONITOR":"Surveiller les exportations de conformité","capability.COMPLIANCE_ROI_MONITOR":"Surveiller la communication des renseignements","capability.SECURITY_ACCESS_VIEW":"Consulter les accès de sécurité","capability.SECURITY_AUDIT_VIEW":"Consulter l’audit de sécurité"};export const messages={en,fr} as const;
