export const INTEGRATION_AUDIT_EVENTS = {
  CREATED: "INTEGRATION_CREATED", UPDATED: "INTEGRATION_UPDATED", DISABLED: "INTEGRATION_DISABLED", ENABLED: "INTEGRATION_ENABLED",
  FACILITY_GRANTED: "INTEGRATION_FACILITY_GRANTED", FACILITY_REVOKED: "INTEGRATION_FACILITY_REVOKED", PERMISSION_GRANTED: "INTEGRATION_PERMISSION_GRANTED", PERMISSION_REVOKED: "INTEGRATION_PERMISSION_REVOKED",
  ENVIRONMENT_CHANGED: "INTEGRATION_ENVIRONMENT_CHANGED", JURISDICTION_CHANGED: "INTEGRATION_JURISDICTION_CHANGED", CONNECTION_TEST_REQUESTED: "INTEGRATION_CONNECTION_TEST_REQUESTED", PROVISIONING_STATE_CHANGED: "INTEGRATION_PROVISIONING_STATE_CHANGED",
  CREDENTIAL_CREATED: "INTEGRATION_CREDENTIAL_CREATED", CREDENTIAL_ROTATED: "INTEGRATION_CREDENTIAL_ROTATED", CREDENTIAL_REVOKED: "INTEGRATION_CREDENTIAL_REVOKED",
} as const;
