-- M1.3F.4 — controlled-substance MAR audit actions (additive enum values only)

ALTER TYPE "AuditAction" ADD VALUE 'MEDICATION_WITNESS_VERIFICATION_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'MEDICATION_WASTE_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE 'MEDICATION_WASTE_WITNESSED';
ALTER TYPE "AuditAction" ADD VALUE 'CONTROLLED_SUBSTANCE_OVERRIDE';
