import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";
export type ForeignBodyRegion="eye"|"ear_nose"|"mouth_pharynx"|"skin_soft_tissue"|"hand_finger"|"foot_toe"|"ingested"|"aspirated"|"unspecified";
export type ForeignBodyDepth="superficial"|"deep"|"cavity"|"ingested"|"aspirated"|"unknown";
export type ForeignBodyMaterial="glass"|"metal"|"wood"|"splinter"|"fishhook"|"needle"|"organic";
export type ForeignBodyDispositionRecommendationId="discharge"|"observation"|"admission"|"transfer"|"ophthalmology"|"ent"|"gi"|"airway"|"hand_surgery";
export type ForeignBodyDispositionRecommendation={id:ForeignBodyDispositionRecommendationId;rationale:string};
export type ForeignBodyDiagnosisInput={code?:string;displayName?:string};
export type ForeignBodyContext={regions:ForeignBodyRegion[];depth:ForeignBodyDepth;materials:ForeignBodyMaterial[];dischargeFamilyId:string|null;dispositionRecommendations:ForeignBodyDispositionRecommendation[]};
const n=(s="")=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
export function resolveForeignBodyContextFromDiagnosis(input:ForeignBodyDiagnosisInput):ForeignBodyContext { const code=(input.code??"").replace(/\s/g,"").toUpperCase(),t=n(`${input.displayName??""} ${code}`); let regions:ForeignBodyRegion[]=[];
if(code.startsWith("T15")||code.startsWith("S05.5")||/eye|ocular|oeil|cornea|eyeball/.test(t))regions=["eye"];
else if(code.startsWith("T16")||code.startsWith("T17.0")||code.startsWith("T17.1")||/ear|nose|nasal|oreille|nez/.test(t))regions=["ear_nose"];
else if(code.startsWith("T17")||/aspirat|airway|respiratory|inhal|bronch|lung|trachea|larynx/.test(t))regions=["aspirated"];
else if(code.startsWith("T18")||/ingest|swallow|esophag|stomach|intestin|degluti/.test(t))regions=["ingested"];
else if(code.startsWith("T19")||/urethra|bladder|uterus|vagina|genital/.test(t))regions=["unspecified"];
else if(/mouth|pharynx|bouche/.test(t))regions=["mouth_pharynx"];
else if((code.startsWith("S60")||code.startsWith("S61"))&&/foreign body|corps etranger|splinter|glass|metal|w fb/.test(t))regions=["hand_finger"];
else if((code.startsWith("S90")||code.startsWith("S91"))&&/foreign body|corps etranger|splinter|glass|metal|w fb/.test(t))regions=["foot_toe"];
else if(/foreign body|corps etranger|retained fragment|echarde|superficial fb/.test(t))regions=["skin_soft_tissue"];
const FrenchMaterial: Partial<Record<ForeignBodyMaterial, string>> = { wood:"bois",splinter:"echarde",fishhook:"hamecon",needle:"aiguille",organic:"organique" };
const materials:ForeignBodyMaterial[]=(["glass","metal","wood","splinter","fishhook","needle","organic"] as const).filter(m=>t.includes(m)||(FrenchMaterial[m] !== undefined && t.includes(FrenchMaterial[m]!)));
const depth:ForeignBodyDepth=regions.includes("ingested")?"ingested":regions.includes("aspirated")?"aspirated":/deep|profound|retained|cavity/.test(t)?"deep":regions.length?"superficial":"unknown";
if(!regions.length&&materials.includes("fishhook"))regions=["hand_finger"];
if(!regions.length&&materials.length)regions=["skin_soft_tissue"];
const dischargeFamilyId=!regions.length?null:code.startsWith("T19")?"trauma_foreign_body_generic":materials.includes("fishhook")?"trauma_foreign_body_fishhook":regions.includes("eye")?"trauma_foreign_body_eye":regions.includes("ear_nose")?"trauma_foreign_body_ear_nose":regions.includes("ingested")?"trauma_foreign_body_ingested":regions.includes("aspirated")?"trauma_foreign_body_aspirated":regions.includes("hand_finger")?"trauma_foreign_body_hand_finger":regions.includes("foot_toe")?"trauma_foreign_body_foot_toe":/retained|fragment/.test(t)?"trauma_foreign_body_retained_fragment":regions.includes("skin_soft_tissue")?"trauma_foreign_body_skin_soft_tissue":"trauma_foreign_body_generic";
return{regions,depth,materials,dischargeFamilyId,dispositionRecommendations:computeForeignBodyDispositionRecommendations(regions,depth,materials)};}
export function computeForeignBodyDispositionRecommendations(regions:readonly ForeignBodyRegion[],depth:ForeignBodyDepth,materials:readonly ForeignBodyMaterial[]):ForeignBodyDispositionRecommendation[]{const r:ForeignBodyDispositionRecommendation[]=[];if(regions.includes("eye"))r.push({id:"ophthalmology",rationale:"Ocular foreign body requires prompt eye examination and specialist care when embedded or high velocity."});if(regions.includes("ear_nose")||regions.includes("mouth_pharynx"))r.push({id:"ent",rationale:"Deep ear, nasal, or pharyngeal foreign body may require specialist removal."});if(regions.includes("ingested"))r.push({id:"gi",rationale:"Ingested foreign body disposition depends on object type, location, and symptoms."},{id:"observation",rationale:"Observation supports symptom and passage monitoring when appropriate."});if(regions.includes("aspirated"))r.push({id:"airway",rationale:"Suspected aspirated foreign body needs urgent airway-capable evaluation."},{id:"transfer",rationale:"Transfer is appropriate when bronchoscopy or airway support is unavailable."});if(regions.includes("hand_finger")||materials.includes("fishhook"))r.push({id:"hand_surgery",rationale:"Complex hand foreign body or fishhook injury may need specialty removal."});if(!r.length)r.push({id:"discharge",rationale:"Superficial foreign body fully removed with reassuring examination may be discharged with wound precautions."});return [...new Map(r.map(x=>[x.id,x])).values()];}
export function adaptForeignBodyComplaintIntel(intel:ProviderDocumentationComplaintIntelligence,context:Pick<ForeignBodyContext,"regions">):ProviderDocumentationComplaintIntelligence{return intel;}
