/** ME.2T Track C — shared chart-ready sore throat complaint intelligence builder. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

export function buildSoreThroatComplaintIntel(st: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      st("hpiSoreThroatBeganToday"),
      st("hpiPainfulSwallowing"),
      st("hpiDysphagia"),
      st("hpiMuffledVoice"),
      st("hpiDrooling"),
      st("hpiFever"),
      st("hpiTonsillarPain"),
      st("hpiAssociatedUri"),
      st("hpiNeckSwelling"),
      st("hpiSickContacts"),
      st("hpiRecentAntibiotics"),
      st("hpiStridor"),
    ],
    rosImportantPositives: [
      st("rosSoreThroat"),
      st("rosOdynophagia"),
      st("rosDysphagia"),
      st("rosFever"),
      st("rosNeckPain"),
      st("rosNeckSwelling"),
      st("rosVoiceChange"),
      st("rosDrooling"),
      st("rosUriSymptoms"),
    ],
    rosImportantNegatives: [st("rosDeniesDrooling"), st("rosDeniesShortnessOfBreath")],
    rosRedFlags: [
      st("rfDrooling"),
      st("rfMuffledVoice"),
      st("rfSevereUnilateralThroatPain"),
      st("rfNeckSwelling"),
      st("rfStridor"),
    ],
    physicalExam: {
      heent: [
        st("examTonsillarErythema"),
        st("examTonsillarExudates"),
        st("examUvulaMidline"),
        st("examUvularDeviation"),
        st("examPeritonsillarFullness"),
        st("examHoarseVoice"),
        st("examCervicalLymphadenopathy"),
        st("examAirwayPatent"),
      ],
      general: [st("examWellAppearing"), st("examToxicAppearing")],
    },
    mdmWorkingAssessment: [
      st("waSuspectedPharyngitis"),
      st("waConcernForPeritonsillarAbscess"),
      st("waConcernForAirwayCompromise"),
    ],
    mdmDifferentialSynthesis: [
      st("diffViralPharyngitis"),
      st("diffStreptococcalPharyngitis"),
      st("diffTonsillitis"),
      st("diffPeritonsillarAbscess"),
      st("diffRetropharyngealAbscess"),
      st("diffEpiglottitis"),
      st("diffUvulitis"),
      st("diffInfectiousMononucleosis"),
      st("diffDeepNeckSpaceInfection"),
      st("diffLudwigAngina"),
      st("diffDentalInfection"),
      st("diffOralAbscess"),
      st("diffViralUri"),
      st("diffCovidPharyngitis"),
      st("diffInfluenzaPharyngitis"),
      st("diffAirwayCompromise"),
      st("diffSepsis"),
    ],
    mdmDataReviewed: [
      st("mdmRapidStrepReviewed"),
      st("mdmThroatCultureReviewed"),
      st("mdmMonospotReviewed"),
      st("mdmCbcReviewed"),
      st("mdmPriorEntRecordsReviewed"),
      st("mdmCtNeckReviewed"),
      st("mdmSpecialistConsultationReviewed"),
    ],
    mdmRiskStratification: [
      st("riskLowSuspicionDeepNeckInfection"),
      st("riskModerateSuspicionPeritonsillarAbscess"),
      st("riskHighSuspicionAirwayCompromise"),
    ],
    mdmClinicalRationale: [
      st("reasoningMostConsistentWithViralPharyngitis"),
      st("reasoningLowSuspicionPeritonsillarAbscess"),
      st("reasoningLowSuspicionEpiglottitis"),
    ],
    clinicalImpression: [
      st("impViralPharyngitis"),
      st("impStreptococcalPharyngitis"),
      st("impTonsillitis"),
      st("impPeritonsillarAbscess"),
    ],
    mdmPlanSummary: [
      st("planSupportiveCareDiscussed"),
      st("planAntibioticsPrescribed"),
      st("planSteroidsPrescribed"),
      st("planIvFluidsAdministered"),
      st("planEntFollowUpRecommended"),
      st("planReturnPrecautionsDiscussed"),
    ],
    mdmAdmitObserveDischarge: [st("dispObservation"), st("dispAdmission"), st("dispDischarge")],
    reassessment: [
      st("reassessThroatPainImproved"),
      st("reassessToleratingOralIntake"),
      st("reassessAirwayStable"),
    ],
    followUpDisposition: [
      st("dispReturnAirwaySymptoms"),
      st("dispUrgentEntFollowUp"),
      st("dispReturnWorseningNeckSwelling"),
      st("dispReturnInabilityToSwallow"),
    ],
  });
}
