/** ME.2W-R Track C — chart-ready neuro / stroke / weakness complaint intelligence builders. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

export function buildStrokeSymptomsComplaintIntel(st: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      st("hpiLastKnownWell"),
      st("hpiSuddenOnset"),
      st("hpiGradualOnset"),
      st("hpiSymptomsWokeFromSleep"),
      st("hpiSymptomDuration"),
      st("hpiUnilateralWeakness"),
      st("hpiFacialDroopNoticed"),
      st("hpiSlurredSpeech"),
      st("hpiAphasia"),
      st("hpiNumbnessTingling"),
      st("hpiGaitDifficulty"),
      st("hpiVisionChangePresent"),
      st("hpiVisionChangeAbsent"),
      st("hpiConfusion"),
      st("hpiHeadachePresent"),
      st("hpiDeniesHeadache"),
      st("hpiDeniesTrauma"),
      st("hpiDeniesSeizure"),
      st("hpiAnticoagulantUse"),
      st("hpiPriorStrokeOrTia"),
      st("hpiWitnessedSymptoms"),
      st("hpiFamilyReportedSymptoms"),
      st("hpiEmsReport"),
      st("hpiSymptomsImproving"),
      st("hpiSymptomsUnchanged"),
      st("hpiStrokeAlertActivated"),
      st("hpiAtrialFibrillationHistory"),
      st("hpiHypertensionHistory"),
      st("hpiDiabetesHistory"),
    ],
    rosImportantPositives: [
      st("rosWeakness"),
      st("rosNumbness"),
      st("rosSpeechDifficulty"),
      st("rosFacialDroop"),
      st("rosVisionChange"),
      st("rosConfusion"),
      st("rosHeadache"),
      st("rosDizziness"),
      st("rosGaitDifficulty"),
      st("rosSeizure"),
    ],
    rosImportantNegatives: [
      st("rosDeniesChestPain"),
      st("rosDeniesShortnessOfBreath"),
      st("rosDeniesFever"),
      st("rosDeniesSeizure"),
      st("rosDeniesTrauma"),
      st("rosDeniesSyncope"),
      st("rosDeniesNeckStiffness"),
    ],
    rosRedFlags: [
      st("rfAcuteFocalDeficit"),
      st("rfWorseningNeurologicSymptoms"),
      st("rfSevereHeadache"),
      st("rfAlteredMentalStatus"),
      st("rfSeizure"),
      st("rfInabilityToAmbulate"),
    ],
    physicalExam: {
      neuroPsych: [
        st("examAlertAndOriented"),
        st("examConfused"),
        st("examFollowsCommands"),
        st("examSpeechClear"),
        st("examSlurredSpeech"),
        st("examAphasiaPresent"),
        st("examFacialSymmetryPreserved"),
        st("examFacialDroopPresent"),
        st("examGripStrengthSymmetric"),
        st("examDecreasedLeftGripStrength"),
        st("examUnilateralWeakness"),
        st("examArmDriftPresent"),
        st("examLegDriftPresent"),
        st("examSensationIntact"),
        st("examDecreasedSensation"),
        st("examNoFocalNeurologicDeficit"),
        st("examNihssScore"),
        st("examGaitSteady"),
        st("examAtaxicGait"),
        st("examPupilsEqualReactive"),
        st("examEomIntact"),
      ],
      cardiovascular: [st("examRegularRhythm"), st("examTachycardic"), st("examIrregularRhythm")],
      general: [st("examNoAcuteDistress")],
    },
    mdmWorkingAssessment: [
      st("waSuspectedStroke"),
      st("waSuspectedTia"),
      st("waFocalNeurologicDeficit"),
      st("waLowSuspicionAcuteStroke"),
      st("waNeurologicSymptomsUnclearEtiology"),
    ],
    mdmDifferentialSynthesis: [
      st("diffIschemicStroke"),
      st("diffIntracranialHemorrhage"),
      st("diffLargeVesselOcclusion"),
      st("diffTia"),
      st("diffSeizure"),
      st("diffMigraine"),
      st("diffBellPalsy"),
      st("diffPeripheralNeuropathy"),
      st("diffVertigo"),
      st("diffDehydration"),
      st("diffElectrolyteAbnormality"),
      st("diffMedicationEffect"),
      st("diffHypoglycemia"),
      st("diffSepsis"),
      st("diffMeningitis"),
      st("diffEncephalitis"),
      st("diffIntracranialMass"),
      st("diffToxicIngestion"),
      st("diffSpinalCordCompression"),
    ],
    mdmDataReviewed: [
      st("mdmGlucoseReviewed"),
      st("mdmCtHeadReviewed"),
      st("mdmCtaHeadNeckReviewed"),
      st("mdmMriBrainReviewed"),
      st("mdmEcgReviewed"),
      st("mdmCbcReviewed"),
      st("mdmCmpReviewed"),
      st("mdmTroponinReviewed"),
      st("mdmCoagulationStudiesReviewed"),
    ],
    mdmRiskStratification: [
      st("riskSymptomsResolvedLow"),
      st("riskReassuringNeuroExamLow"),
      st("riskPersistentSymptomsModerate"),
      st("riskObservationRequiredModerate"),
      st("riskConcernAcuteStrokeHigh"),
      st("riskConcernHemorrhageHigh"),
      st("riskLargeVesselOcclusionHigh"),
      st("riskAdmissionRecommendedHigh"),
      st("riskTransferRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      st("reasoningLastKnownWellGuidesStrokePathway"),
      st("reasoningCtObtainedForHemorrhage"),
      st("reasoningCtaObtainedForLvo"),
      st("reasoningGlucoseCheckedForNeuroSymptoms"),
      st("reasoningLowSuspicionStrokeAfterEvaluation"),
      st("reasoningLowSuspicionMeningitis"),
      st("reasoningAdmissionForNeurologicEvaluation"),
    ],
    clinicalImpression: [
      st("impAcuteIschemicStroke"),
      st("impTransientIschemicAttack"),
      st("impFocalNeurologicDeficit"),
      st("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      st("planStrokeAlertActivated"),
      st("planCtHeadObtained"),
      st("planCtaHeadNeckObtained"),
      st("planGlucoseChecked"),
      st("planEcgObtained"),
      st("planLabsObtained"),
      st("planNeurologyConsulted"),
      st("planIvFluidsAdministered"),
      st("planAspirinAdministered"),
      st("planAdmissionArranged"),
      st("planTransferArranged"),
    ],
    reassessment: [
      st("reassessSymptomsImproved"),
      st("reassessSymptomsUnchanged"),
      st("reassessSymptomsResolved"),
      st("reassessNeuroExamUnchanged"),
      st("reassessNoNeurologicDeterioration"),
      st("reassessHemodynamicallyStable"),
      st("reassessRepeatNihss"),
      st("reassessAdmittedForFurtherEvaluation"),
    ],
    followUpDisposition: [
      st("dispAdmittedStrokeEvaluation"),
      st("dispAdmittedNeurologicMonitoring"),
      st("dispTransferredHigherLevelCare"),
      st("dispDischargedStrictReturnPrecautions"),
      st("dispNeurologyFollowUpArranged"),
      st("dispPcpFollowUpArranged"),
      st("dispReturnWeaknessNumbnessSpeech"),
    ],
    mdmAdmitObserveDischarge: [st("dispObservationInEd")],
  });
}

export function buildWeaknessComplaintIntel(wk: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      wk("hpiGeneralizedWeakness"),
      wk("hpiFocalWeakness"),
      wk("hpiAcuteOnset"),
      wk("hpiGradualOnset"),
      wk("hpiSymptomDuration"),
      wk("hpiUnilateralWeakness"),
      wk("hpiFacialDroop"),
      wk("hpiSlurredSpeech"),
      wk("hpiAphasia"),
      wk("hpiNumbnessTingling"),
      wk("hpiGaitDifficulty"),
      wk("hpiConfusion"),
      wk("hpiDizziness"),
      wk("hpiHeadachePresent"),
      wk("hpiDeniesHeadache"),
      wk("hpiDeniesTrauma"),
      wk("hpiDeniesSeizure"),
      wk("hpiSeizureActivity"),
      wk("hpiFever"),
      wk("hpiPoorOralIntake"),
      wk("hpiRecentIllness"),
      wk("hpiMedicationChange"),
      wk("hpiAnticoagulantUse"),
      wk("hpiPriorStrokeOrTia"),
      wk("hpiBaselineFunctionalStatus"),
      wk("hpiWitnessedSymptoms"),
      wk("hpiFamilyReportedSymptoms"),
      wk("hpiEmsReport"),
      wk("hpiCaregiverPresent"),
    ],
    rosImportantPositives: [
      wk("rosWeakness"),
      wk("rosNumbness"),
      wk("rosSpeechDifficulty"),
      wk("rosConfusion"),
      wk("rosHeadache"),
      wk("rosDizziness"),
      wk("rosGaitDifficulty"),
      wk("rosVisionChange"),
      wk("rosSeizure"),
      wk("rosFever"),
      wk("rosChestPain"),
      wk("rosShortnessOfBreath"),
    ],
    rosImportantNegatives: [
      wk("rosDeniesFocalDeficit"),
      wk("rosDeniesChestPain"),
      wk("rosDeniesShortnessOfBreath"),
      wk("rosDeniesSyncope"),
      wk("rosDeniesFever"),
      wk("rosDeniesTrauma"),
      wk("rosDeniesNeckStiffness"),
    ],
    rosRedFlags: [
      wk("rfAcuteFocalDeficit"),
      wk("rfWorseningNeurologicSymptoms"),
      wk("rfAlteredMentalStatus"),
      wk("rfInabilityToAmbulate"),
      wk("rfSeizure"),
      wk("rfStrokeConcern"),
      wk("rfSepsisConcern"),
    ],
    physicalExam: {
      neuroPsych: [
        wk("examAlertAndOriented"),
        wk("examConfused"),
        wk("examFollowsCommands"),
        wk("examSpeechClear"),
        wk("examSlurredSpeech"),
        wk("examFacialDroopPresent"),
        wk("examUnilateralWeakness"),
        wk("examNoFocalNeurologicDeficit"),
        wk("examGripStrengthSymmetric"),
        wk("examDecreasedLeftGripStrength"),
        wk("examArmDriftPresent"),
        wk("examGaitSteady"),
        wk("examAtaxicGait"),
      ],
      general: [wk("examNoAcuteDistress")],
      cardiovascular: [wk("examTachycardic")],
      heent: [wk("examDryMucousMembranes")],
    },
    mdmWorkingAssessment: [
      wk("waGeneralizedWeakness"),
      wk("waFocalNeurologicDeficit"),
      wk("waAlteredMentalStatus"),
      wk("waParesthesia"),
      wk("waLowSuspicionStroke"),
      wk("waNeurologicSymptomsUnclearEtiology"),
    ],
    mdmDifferentialSynthesis: [
      wk("diffIschemicStroke"),
      wk("diffTia"),
      wk("diffHypoglycemia"),
      wk("diffElectrolyteAbnormality"),
      wk("diffSepsis"),
      wk("diffDehydration"),
      wk("diffAnemia"),
      wk("diffMedicationEffect"),
      wk("diffPeripheralNeuropathy"),
      wk("diffSpinalCordCompression"),
      wk("diffMeningitis"),
      wk("diffSeizure"),
      wk("diffToxicIngestion"),
    ],
    mdmDataReviewed: [
      wk("mdmGlucoseReviewed"),
      wk("mdmCtHeadReviewed"),
      wk("mdmEcgReviewed"),
      wk("mdmCbcReviewed"),
      wk("mdmCmpReviewed"),
      wk("mdmTroponinReviewed"),
    ],
    mdmRiskStratification: [
      wk("riskMildWeaknessLow"),
      wk("riskReassuringNeuroExamLow"),
      wk("riskSymptomsResolvedLow"),
      wk("riskPersistentWeaknessModerate"),
      wk("riskObservationRequiredModerate"),
      wk("riskStrokeConcernHigh"),
      wk("riskSepsisConcernHigh"),
      wk("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      wk("reasoningGlucoseCheckedForWeakness"),
      wk("reasoningLowSuspicionStroke"),
      wk("reasoningInfectionEvaluation"),
      wk("reasoningAdmissionForNeurologicEvaluation"),
      wk("reasoningSafeForOutpatientManagement"),
    ],
    clinicalImpression: [
      wk("impGeneralizedWeakness"),
      wk("impFocalNeurologicDeficit"),
      wk("impDehydration"),
      wk("impViralIllness"),
      wk("impParesthesia"),
    ],
    mdmPlanSummary: [
      wk("planGlucoseChecked"),
      wk("planCtHeadObtained"),
      wk("planEcgObtained"),
      wk("planLabsObtained"),
      wk("planIvFluidsAdministered"),
      wk("planNeurologyConsulted"),
      wk("planAdmissionArranged"),
    ],
    reassessment: [
      wk("reassessWeaknessImproved"),
      wk("reassessWeaknessUnchanged"),
      wk("reassessAmbulationImproved"),
      wk("reassessNeuroExamUnchanged"),
      wk("reassessNoNeurologicDeterioration"),
      wk("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      wk("dispAdmittedWeaknessEvaluation"),
      wk("dispDischargedHome"),
      wk("dispNeurologyFollowUpArranged"),
      wk("dispPcpFollowUpArranged"),
      wk("dispReturnWeaknessNumbnessSpeech"),
    ],
    mdmAdmitObserveDischarge: [wk("dispObservationInEd")],
  });
}

export function buildAlteredMentalStatusComplaintV1Intel(ams: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      ams("hpiBaselineMentalStatus"),
      ams("hpiOnsetTime"),
      ams("hpiLastKnownWell"),
      ams("hpiSuddenOnset"),
      ams("hpiGradualOnset"),
      ams("hpiConfusion"),
      ams("hpiWeakness"),
      ams("hpiSpeechDifficulty"),
      ams("hpiSeizureActivity"),
      ams("hpiHeadachePresent"),
      ams("hpiDeniesHeadache"),
      ams("hpiVisionChangePresent"),
      ams("hpiVisionChangeAbsent"),
      ams("hpiFever"),
      ams("hpiTrauma"),
      ams("hpiSubstanceUse"),
      ams("hpiMedicationChange"),
      ams("hpiAnticoagulantUse"),
      ams("hpiPriorStrokeOrTia"),
      ams("hpiDeniesNeckStiffness"),
      ams("hpiFamilyReportedSymptoms"),
      ams("hpiEmsReport"),
      ams("hpiCaregiverPresent"),
    ],
    rosImportantPositives: [
      ams("rosConfusion"),
      ams("rosWeakness"),
      ams("rosSpeechDifficulty"),
      ams("rosHeadache"),
      ams("rosFever"),
      ams("rosDizziness"),
      ams("rosSeizure"),
      ams("rosGaitDifficulty"),
    ],
    rosImportantNegatives: [
      ams("rosDeniesTrauma"),
      ams("rosDeniesChestPain"),
      ams("rosDeniesShortnessOfBreath"),
      ams("rosDeniesSeizure"),
      ams("rosDeniesNeckStiffness"),
      ams("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      ams("rfAcuteFocalDeficit"),
      ams("rfWorseningNeurologicSymptoms"),
      ams("rfSevereHeadache"),
      ams("rfAlteredMentalStatus"),
      ams("rfSeizure"),
    ],
    physicalExam: {
      neuroPsych: [
        ams("examAlertAndOriented"),
        ams("examConfused"),
        ams("examDisoriented"),
        ams("examFollowsCommands"),
        ams("examSpeechClear"),
        ams("examSlurredSpeech"),
        ams("examNoFocalNeurologicDeficit"),
        ams("examFocalDeficitPresent"),
      ],
      general: [ams("examFebrile"), ams("examAfebrile")],
    },
    mdmWorkingAssessment: [
      ams("waAlteredMentalStatus"),
      ams("waSuspectedStroke"),
      ams("waLowSuspicionMeningitis"),
      ams("waMetabolicEncephalopathyConcern"),
      ams("waLowSuspicionAcuteStroke"),
    ],
    mdmDifferentialSynthesis: [
      ams("diffIschemicStroke"),
      ams("diffIntracranialHemorrhage"),
      ams("diffHypoglycemia"),
      ams("diffSepsis"),
      ams("diffMeningitis"),
      ams("diffEncephalitis"),
      ams("diffToxicIngestion"),
      ams("diffElectrolyteAbnormality"),
      ams("diffMedicationEffect"),
      ams("diffDehydration"),
      ams("diffSeizure"),
      ams("diffPsychiatricCause"),
    ],
    mdmDataReviewed: [
      ams("mdmGlucoseReviewed"),
      ams("mdmCtHeadReviewed"),
      ams("mdmCbcReviewed"),
      ams("mdmCmpReviewed"),
      ams("mdmEcgReviewed"),
    ],
    mdmRiskStratification: [
      ams("riskImprovedMentalStatusLow"),
      ams("riskReassuringNeuroExamLow"),
      ams("riskPersistentAlterationModerate"),
      ams("riskObservationRequiredModerate"),
      ams("riskConcernStrokeHigh"),
      ams("riskSepsisConcernHigh"),
      ams("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      ams("reasoningGlucoseChecked"),
      ams("reasoningCtObtainedForHemorrhage"),
      ams("reasoningLowSuspicionMeningitis"),
      ams("reasoningAdmissionForFurtherEvaluation"),
    ],
    clinicalImpression: [
      ams("impAlteredMentalStatus"),
      ams("impMetabolicEncephalopathy"),
      ams("impAcuteInfection"),
      ams("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      ams("planGlucoseChecked"),
      ams("planCtHeadObtained"),
      ams("planLabsObtained"),
      ams("planIvFluidsAdministered"),
      ams("planAdmissionArranged"),
      ams("planNeurologyConsulted"),
    ],
    reassessment: [
      ams("reassessMentalStatusImproved"),
      ams("reassessMentalStatusUnchanged"),
      ams("reassessNoNeurologicDeterioration"),
      ams("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      ams("dispAdmittedForEvaluation"),
      ams("dispDischargedHome"),
      ams("dispReturnConfusionWeaknessFever"),
    ],
    mdmAdmitObserveDischarge: [ams("dispObservationInEd")],
  });
}

export function buildFocalWeaknessComplaintV1Intel(fw: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      fw("hpiOnsetTime"),
      fw("hpiLastKnownWell"),
      fw("hpiSuddenOnset"),
      fw("hpiGradualOnset"),
      fw("hpiSymptomDuration"),
      fw("hpiUnilateralWeakness"),
      fw("hpiFacialDroopNoticed"),
      fw("hpiSlurredSpeech"),
      fw("hpiAphasia"),
      fw("hpiVisionChangePresent"),
      fw("hpiVisionChangeAbsent"),
      fw("hpiNumbnessTingling"),
      fw("hpiHeadachePresent"),
      fw("hpiDeniesHeadache"),
      fw("hpiDeniesTrauma"),
      fw("hpiSeizureActivity"),
      fw("hpiAnticoagulantUse"),
      fw("hpiPriorStrokeOrTia"),
      fw("hpiFamilyReportedSymptoms"),
      fw("hpiEmsReport"),
    ],
    rosImportantPositives: [
      fw("rosWeakness"),
      fw("rosNumbness"),
      fw("rosSpeechDifficulty"),
      fw("rosFacialDroop"),
      fw("rosVisionChange"),
      fw("rosHeadache"),
      fw("rosConfusion"),
    ],
    rosImportantNegatives: [
      fw("rosDeniesTrauma"),
      fw("rosDeniesChestPain"),
      fw("rosDeniesSeizure"),
      fw("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      fw("rfAcuteFocalDeficit"),
      fw("rfWorseningNeurologicSymptoms"),
      fw("rfSpeechDeficit"),
      fw("rfStrokeConcern"),
    ],
    physicalExam: {
      neuroPsych: [
        fw("examUnilateralWeakness"),
        fw("examFacialDroopPresent"),
        fw("examSlurredSpeech"),
        fw("examAphasiaPresent"),
        fw("examArmDriftPresent"),
        fw("examLegDriftPresent"),
        fw("examNoFocalNeurologicDeficit"),
        fw("examGripStrengthSymmetric"),
        fw("examDecreasedLeftGripStrength"),
        fw("examSensationIntact"),
        fw("examDecreasedSensation"),
        fw("examNihssScore"),
      ],
    },
    mdmWorkingAssessment: [
      fw("waFocalNeurologicDeficit"),
      fw("waSuspectedStroke"),
      fw("waSuspectedTia"),
      fw("waLowSuspicionAcuteStroke"),
    ],
    mdmDifferentialSynthesis: [
      fw("diffIschemicStroke"),
      fw("diffTia"),
      fw("diffIntracranialHemorrhage"),
      fw("diffLargeVesselOcclusion"),
      fw("diffBellPalsy"),
      fw("diffMigraine"),
      fw("diffSeizure"),
      fw("diffHypoglycemia"),
      fw("diffSpinalCordCompression"),
      fw("diffPeripheralNeuropathy"),
      fw("diffMedicationEffect"),
    ],
    mdmDataReviewed: [
      fw("mdmGlucoseReviewed"),
      fw("mdmCtHeadReviewed"),
      fw("mdmCtaHeadNeckReviewed"),
      fw("mdmMriBrainReviewed"),
      fw("mdmEcgReviewed"),
    ],
    mdmRiskStratification: [
      fw("riskSymptomsResolvedLow"),
      fw("riskReassuringNeuroExamLow"),
      fw("riskPersistentDeficitModerate"),
      fw("riskStrokeConcernHigh"),
      fw("riskLargeVesselOcclusionHigh"),
      fw("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      fw("reasoningLastKnownWellGuidesStrokePathway"),
      fw("reasoningCtaObtainedForLvo"),
      fw("reasoningLowSuspicionStrokeAfterEvaluation"),
      fw("reasoningAdmissionForNeurologicEvaluation"),
    ],
    clinicalImpression: [
      fw("impFocalNeurologicDeficit"),
      fw("impAcuteIschemicStroke"),
      fw("impTransientIschemicAttack"),
      fw("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      fw("planCtHeadObtained"),
      fw("planCtaHeadNeckObtained"),
      fw("planNeurologyConsulted"),
      fw("planAdmissionArranged"),
      fw("planGlucoseChecked"),
    ],
    reassessment: [
      fw("reassessWeaknessImproved"),
      fw("reassessWeaknessUnchanged"),
      fw("reassessNeuroExamUnchanged"),
      fw("reassessNoNeurologicDeterioration"),
    ],
    followUpDisposition: [
      fw("dispAdmittedStrokeEvaluation"),
      fw("dispNeurologyFollowUpArranged"),
      fw("dispReturnWeaknessNumbnessSpeech"),
    ],
    mdmAdmitObserveDischarge: [fw("dispObservationInEd")],
  });
}

export function buildNumbnessTinglingComplaintV1Intel(nt: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      nt("hpiDistributionOnset"),
      nt("hpiSuddenOnset"),
      nt("hpiGradualOnset"),
      nt("hpiSymptomDuration"),
      nt("hpiUnilateralSymptoms"),
      nt("hpiBilateralSymptoms"),
      nt("hpiWeaknessAssociated"),
      nt("hpiSpeechDifficulty"),
      nt("hpiVisionChangePresent"),
      nt("hpiVisionChangeAbsent"),
      nt("hpiNeckBackPain"),
      nt("hpiDeniesWeakness"),
      nt("hpiDeniesTrauma"),
      nt("hpiPriorStrokeOrTia"),
    ],
    rosImportantPositives: [
      nt("rosNumbness"),
      nt("rosTingling"),
      nt("rosWeakness"),
      nt("rosSpeechDifficulty"),
      nt("rosConfusion"),
      nt("rosGaitDifficulty"),
    ],
    rosImportantNegatives: [
      nt("rosDeniesSpeechChange"),
      nt("rosDeniesChestPain"),
      nt("rosDeniesShortnessOfBreath"),
      nt("rosDeniesTrauma"),
      nt("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      nt("rfAcuteFocalDeficit"),
      nt("rfWorseningNeurologicSymptoms"),
      nt("rfWeaknessConcern"),
      nt("rfStrokeConcern"),
    ],
    physicalExam: {
      neuroPsych: [
        nt("examSensationIntact"),
        nt("examDecreasedSensation"),
        nt("examUnilateralWeakness"),
        nt("examNoFocalNeurologicDeficit"),
        nt("examGripStrengthSymmetric"),
        nt("examDecreasedLeftGripStrength"),
        nt("examGaitSteady"),
        nt("examAtaxicGait"),
      ],
    },
    mdmWorkingAssessment: [
      nt("waParesthesia"),
      nt("waFocalNeurologicDeficit"),
      nt("waLowSuspicionStroke"),
      nt("waNeurologicSymptomsUnclearEtiology"),
    ],
    mdmDifferentialSynthesis: [
      nt("diffPeripheralNeuropathy"),
      nt("diffRadiculopathy"),
      nt("diffIschemicStroke"),
      nt("diffTia"),
      nt("diffHypoglycemia"),
      nt("diffElectrolyteAbnormality"),
      nt("diffMedicationEffect"),
      nt("diffMigraine"),
      nt("diffSeizure"),
      nt("diffSpinalCordCompression"),
    ],
    mdmDataReviewed: [
      nt("mdmGlucoseReviewed"),
      nt("mdmCtHeadReviewed"),
      nt("mdmCbcReviewed"),
      nt("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      nt("riskLocalizedSymptomsLow"),
      nt("riskReassuringNeuroExamLow"),
      nt("riskPersistentSymptomsModerate"),
      nt("riskStrokeConcernHigh"),
    ],
    mdmClinicalRationale: [
      nt("reasoningGlucoseChecked"),
      nt("reasoningLowSuspicionStroke"),
      nt("reasoningOutpatientFollowUpAppropriate"),
    ],
    clinicalImpression: [
      nt("impParesthesia"),
      nt("impPeripheralNeuropathy"),
      nt("impRadiculopathy"),
      nt("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      nt("planGlucoseChecked"),
      nt("planCtHeadObtained"),
      nt("planNeurologyFollowUpArranged"),
    ],
    reassessment: [
      nt("reassessSymptomsImproved"),
      nt("reassessSymptomsUnchanged"),
      nt("reassessNoProgressiveWeakness"),
    ],
    followUpDisposition: [
      nt("dispDischargedHome"),
      nt("dispNeurologyFollowUpArranged"),
      nt("dispReturnWeaknessNumbnessSpeech"),
    ],
    mdmAdmitObserveDischarge: [nt("dispObservationInEd")],
  });
}

export function buildGaitInstabilityFallsNeuroComplaintV1Intel(gi: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      gi("hpiOnsetFrequency"),
      gi("hpiBaselineMobility"),
      gi("hpiAssistiveDevices"),
      gi("hpiDizziness"),
      gi("hpiWeakness"),
      gi("hpiNumbness"),
      gi("hpiConfusion"),
      gi("hpiSyncope"),
      gi("hpiFallInjury"),
      gi("hpiDeniesSyncope"),
      gi("hpiFamilyReportedSymptoms"),
    ],
    rosImportantPositives: [
      gi("rosGaitInstability"),
      gi("rosFalls"),
      gi("rosDizziness"),
      gi("rosWeakness"),
      gi("rosConfusion"),
      gi("rosSeizure"),
    ],
    rosImportantNegatives: [
      gi("rosDeniesSyncope"),
      gi("rosDeniesChestPain"),
      gi("rosDeniesShortnessOfBreath"),
      gi("rosDeniesTrauma"),
    ],
    rosRedFlags: [
      gi("rfRecurrentFalls"),
      gi("rfInjuryFromFall"),
      gi("rfAcuteFocalDeficit"),
      gi("rfInabilityToAmbulate"),
      gi("rfStrokeConcern"),
    ],
    physicalExam: {
      neuroPsych: [
        gi("examAtaxicGait"),
        gi("examGaitSteady"),
        gi("examUnilateralWeakness"),
        gi("examNoFocalNeurologicDeficit"),
        gi("examFollowsCommands"),
        gi("examConfused"),
      ],
    },
    mdmWorkingAssessment: [
      gi("waGaitInstability"),
      gi("waGeneralizedWeakness"),
      gi("waAlteredMentalStatus"),
      gi("waLowSuspicionStroke"),
    ],
    mdmDifferentialSynthesis: [
      gi("diffVestibularDisorder"),
      gi("diffIschemicStroke"),
      gi("diffDehydration"),
      gi("diffElectrolyteAbnormality"),
      gi("diffCardiacArrhythmia"),
      gi("diffMedicationEffect"),
      gi("diffTrauma"),
      gi("diffSeizure"),
      gi("diffHypoglycemia"),
    ],
    mdmDataReviewed: [
      gi("mdmGlucoseReviewed"),
      gi("mdmEcgReviewed"),
      gi("mdmCtHeadReviewed"),
      gi("mdmCbcReviewed"),
      gi("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      gi("riskSingleFallLow"),
      gi("riskReassuringNeuroExamLow"),
      gi("riskRecurrentFallsModerate"),
      gi("riskObservationRequiredModerate"),
      gi("riskStrokeConcernHigh"),
      gi("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      gi("reasoningFallRiskAddressed"),
      gi("reasoningEcgForSyncopeConcern"),
      gi("reasoningAdmissionIfUnableToAmbulateSafely"),
    ],
    clinicalImpression: [
      gi("impGaitInstability"),
      gi("impFall"),
      gi("impDehydration"),
      gi("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      gi("planGlucoseChecked"),
      gi("planEcgObtained"),
      gi("planIvFluidsAdministered"),
      gi("planPhysicalTherapyConsulted"),
      gi("planAdmissionArranged"),
    ],
    reassessment: [
      gi("reassessGaitImproved"),
      gi("reassessMobilityUnchanged"),
      gi("reassessFallRiskAddressed"),
      gi("reassessNoNeurologicDeterioration"),
    ],
    followUpDisposition: [
      gi("dispAdmittedForFallEvaluation"),
      gi("dispDischargedHome"),
      gi("dispReturnRecurrentFallsWeakness"),
    ],
    mdmAdmitObserveDischarge: [gi("dispObservationInEd")],
  });
}

export function buildBackPainNeuroRedFlagsComplaintV1Intel(bp: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      bp("hpiBackPainWithWeakness"),
      bp("hpiSaddleAnesthesia"),
      bp("hpiBowelBladderSymptoms"),
      bp("hpiFever"),
      bp("hpiTrauma"),
      bp("hpiIvDrugUse"),
      bp("hpiCancerHistory"),
      bp("hpiAnticoagulantUse"),
      bp("hpiNumbnessTingling"),
      bp("hpiGaitDifficulty"),
    ],
    rosImportantPositives: [
      bp("rosBackPain"),
      bp("rosWeakness"),
      bp("rosNumbness"),
      bp("rosBowelBladderSymptoms"),
      bp("rosFever"),
      bp("rosGaitDifficulty"),
    ],
    rosImportantNegatives: [bp("rosDeniesFever"), bp("rosDeniesTrauma")],
    rosRedFlags: [
      bp("rfBowelBladderSymptoms"),
      bp("rfProgressiveWeakness"),
      bp("rfSaddleAnesthesia"),
      bp("rfAcuteFocalDeficit"),
      bp("rfInabilityToAmbulate"),
    ],
    physicalExam: {
      neuroPsych: [
        bp("examDecreasedSensation"),
        bp("examUnilateralWeakness"),
        bp("examReflexChanges"),
        bp("examGaitDifficulty"),
        bp("examNoFocalNeurologicDeficit"),
      ],
      musculoskeletal: [bp("examMidlineTenderness"), bp("examParaspinalTenderness")],
    },
    mdmWorkingAssessment: [
      bp("waBackPainWithNeuroDeficit"),
      bp("waCaudaEquinaConcern"),
      bp("waSpinalInfectionConcern"),
    ],
    mdmDifferentialSynthesis: [
      bp("diffRadiculopathy"),
      bp("diffCaudaEquinaSyndrome"),
      bp("diffSpinalCordCompression"),
      bp("diffEpiduralAbscess"),
      bp("diffVertebralFracture"),
      bp("diffEpiduralHematoma"),
      bp("diffMalignancy"),
    ],
    mdmDataReviewed: [
      bp("mdmMriSpineReviewed"),
      bp("mdmCtSpineReviewed"),
      bp("mdmCbcReviewed"),
      bp("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      bp("riskLocalizedBackPainLow"),
      bp("riskRadiculopathyModerate"),
      bp("riskCaudaEquinaHigh"),
      bp("riskSpinalInfectionHigh"),
      bp("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      bp("reasoningMriForCordCompression"),
      bp("reasoningNeurosurgeryConsultForCaudaEquina"),
      bp("reasoningAdmissionForNeuroMonitoring"),
    ],
    clinicalImpression: [
      bp("impRadiculopathy"),
      bp("impCaudaEquinaSyndrome"),
      bp("impSpinalCordCompression"),
      bp("impNeurologicSymptoms"),
    ],
    mdmPlanSummary: [
      bp("planMriSpineObtained"),
      bp("planNeurosurgeryConsulted"),
      bp("planAdmissionArranged"),
    ],
    reassessment: [
      bp("reassessWeaknessUnchanged"),
      bp("reassessBowelBladderUnchanged"),
      bp("reassessPainControlled"),
      bp("reassessNoNeurologicDeterioration"),
    ],
    followUpDisposition: [
      bp("dispAdmittedForNeurosurgicalEvaluation"),
      bp("dispReturnWorseningWeaknessUrinaryRetention"),
    ],
    mdmAdmitObserveDischarge: [bp("dispObservationInEd")],
  });
}

export const NEURO_STROKE_WEAKNESS_TEMPLATE_IDS = [
  "stroke_symptoms",
  "weakness",
  "altered_mental_status_complaint_v1",
  "focal_weakness_complaint_v1",
  "numbness_tingling_complaint_v1",
  "gait_instability_falls_neuro_complaint_v1",
  "back_pain_neuro_red_flags_complaint_v1",
] as const;
