/** ME.2G-R Track C — chart-ready adult fever complaint intelligence builder. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

function feverHpi(fv: (key: string) => string): string[] {
  return [
    fv("hpiFeverBeganToday"),
    fv("hpiFeverBeganThisMorning"),
    fv("hpiFeverBeganOvernight"),
    fv("hpiFeverForSeveralDays"),
    fv("hpiIntermittentFever"),
    fv("hpiRecurrentFever"),
    fv("hpiWorseningFever"),
    fv("hpiSymptomsImproving"),
    fv("hpiReportedHighFeverAtHome"),
    fv("hpiSubjectiveFever"),
    fv("hpiChills"),
    fv("hpiRigors"),
    fv("hpiFeverImprovedWithAntipyretic"),
    fv("hpiFeverNotImprovingWithAntipyretic"),
    fv("hpiCough"),
    fv("hpiSoreThroat"),
    fv("hpiNasalCongestion"),
    fv("hpiBodyAches"),
    fv("hpiHeadache"),
    fv("hpiNeckPain"),
    fv("hpiAbdominalPain"),
    fv("hpiVomiting"),
    fv("hpiDiarrhea"),
    fv("hpiUrinarySymptoms"),
    fv("hpiRash"),
    fv("hpiWoundRedness"),
    fv("hpiDecreasedOralIntake"),
    fv("hpiGeneralizedWeakness"),
    fv("hpiSickContacts"),
    fv("hpiRecentTravel"),
    fv("hpiRecentAntibioticUse"),
    fv("hpiImmunocompromisedHistory"),
    fv("hpiRecentSurgery"),
    fv("hpiIndwellingCatheter"),
    fv("hpiKnownInfectionExposure"),
    fv("hpiDeniesChestPain"),
    fv("hpiDeniesShortnessOfBreath"),
    fv("hpiDeniesAbdominalPain"),
    fv("hpiDeniesVomiting"),
    fv("hpiDeniesDiarrhea"),
    fv("hpiDeniesUrinarySymptoms"),
    fv("hpiDeniesRash"),
    fv("hpiDeniesNeckStiffness"),
    fv("hpiDeniesConfusion"),
  ];
}

function feverRos(fv: (key: string) => string) {
  return {
    rosImportantPositives: [
      fv("rosFever"),
      fv("rosChills"),
      fv("rosBodyAches"),
      fv("rosFatigue"),
      fv("rosHeadache"),
      fv("rosCough"),
      fv("rosSoreThroat"),
      fv("rosAbdominalPain"),
      fv("rosVomiting"),
      fv("rosDiarrhea"),
      fv("rosUrinarySymptoms"),
      fv("rosRash"),
      fv("rosWeakness"),
    ],
    rosImportantNegatives: [
      fv("rosDeniesChestPain"),
      fv("rosDeniesShortnessOfBreath"),
      fv("rosDeniesNeckStiffness"),
      fv("rosDeniesConfusion"),
      fv("rosDeniesSyncope"),
      fv("rosDeniesSevereAbdominalPain"),
    ],
    rosRedFlags: [
      fv("rfAlteredMentalStatus"),
      fv("rfHypotension"),
      fv("rfPersistentHighFever"),
      fv("rfRigors"),
      fv("rfSevereHeadache"),
      fv("rfNeckStiffness"),
      fv("rfRespiratoryDistress"),
      fv("rfDehydrationConcern"),
      fv("rfImmunocompromisedFever"),
      fv("rfSepsisConcern"),
    ],
  };
}

function feverExam(fv: (key: string) => string) {
  return {
    general: [
      fv("examWellAppearing"),
      fv("examMildlyIllAppearing"),
      fv("examUncomfortableAppearing"),
      fv("examToxicAppearing"),
      fv("examNonToxicAppearing"),
      fv("examDiaphoretic"),
      fv("examAppearsDehydrated"),
      fv("examFebrile"),
      fv("examAfebrileInEd"),
      fv("examTachycardic"),
      fv("examHemodynamicallyStable"),
    ],
    heent: [
      fv("examPharyngealErythema"),
      fv("examTonsillarExudates"),
      fv("examNeckSupple"),
      fv("examNoMeningismus"),
      fv("examDryMucousMembranes"),
      fv("examMoistMucousMembranes"),
      fv("examCapillaryRefillNormal"),
      fv("examCapillaryRefillDelayed"),
    ],
    respiratory: [
      fv("examLungsClearBilaterally"),
      fv("examWheezingPresent"),
      fv("examCracklesPresent"),
      fv("examNoRespiratoryDistress"),
    ],
    abdomen: [
      fv("examAbdomenSoft"),
      fv("examNonTenderAbdomen"),
      fv("examMildAbdominalTenderness"),
      fv("examNoGuarding"),
      fv("examNoReboundTenderness"),
    ],
    skin: [
      fv("examNoRash"),
      fv("examRashPresent"),
      fv("examErythemaPresent"),
      fv("examWoundRednessPresent"),
      fv("examCellulitisPresent"),
    ],
    neuroPsych: [
      fv("examAlertAndOriented"),
      fv("examNoFocalNeurologicDeficit"),
      fv("examAgeAppropriateBehavior"),
    ],
  };
}

function feverMdmGoldStandard(fv: (key: string) => string) {
  return {
    mdmWorkingAssessment: [
      fv("waSuspectedViralSyndrome"),
      fv("waFeverUnclearSource"),
      fv("waSuspectedUpperRespiratoryInfection"),
      fv("waSuspectedUrinaryTractInfection"),
      fv("waSuspectedPneumonia"),
      fv("waSuspectedCellulitis"),
      fv("waLowSuspicionSepsis"),
      fv("waConcernForSepsis"),
    ],
    mdmDifferentialSynthesis: [
      fv("diffViralSyndrome"),
      fv("diffUpperRespiratoryInfection"),
      fv("diffInfluenza"),
      fv("diffCovid19"),
      fv("diffUrinaryTractInfection"),
      fv("diffGastroenteritis"),
      fv("diffPneumonia"),
      fv("diffPyelonephritis"),
      fv("diffCellulitis"),
      fv("diffMeningitis"),
      fv("diffBacteremia"),
      fv("diffIntraAbdominalInfection"),
      fv("diffSepsis"),
      fv("diffSepticShock"),
      fv("diffPneumoniaWithHypoxia"),
      fv("diffNeutropenicFever"),
      fv("diffEndocarditis"),
      fv("diffAppendicitis"),
      fv("diffSeriousBacterialInfection"),
    ],
    mdmDataReviewed: [
      fv("mdmCbcReviewed"),
      fv("mdmCmpReviewed"),
      fv("mdmUrinalysisReviewed"),
      fv("mdmRespiratoryViralTestingReviewed"),
      fv("mdmInfluenzaTestingReviewed"),
      fv("mdmCovidTestingReviewed"),
      fv("mdmBloodCulturesReviewed"),
      fv("mdmLactateReviewed"),
      fv("mdmChestXrayReviewed"),
      fv("mdmCtImagingReviewed"),
    ],
    mdmRiskStratification: [
      fv("riskWellAppearingReassuringExamLow"),
      fv("riskNoEvidenceSepsisLow"),
      fv("riskToleratingOralIntakeLow"),
      fv("riskStableOutpatientManagementLow"),
      fv("riskIvFluidsAdministeredModerate"),
      fv("riskAntipyreticTherapyAdministeredModerate"),
      fv("riskObservationRequiredModerate"),
      fv("riskAdditionalTestingRequiredModerate"),
      fv("riskSepsisConcernHigh"),
      fv("riskHypotensionPresentHigh"),
      fv("riskAlteredMentalStatusHigh"),
      fv("riskImmunocompromisedFeverHigh"),
      fv("riskAdmissionRecommendedHigh"),
      fv("riskSpecialtyConsultationObtainedHigh"),
    ],
    mdmClinicalRationale: [
      fv("reasoningSymptomsMostConsistentViralSyndrome"),
      fv("reasoningNoEvidenceSepsis"),
      fv("reasoningLowSuspicionMeningitis"),
      fv("reasoningLowSuspicionPneumonia"),
      fv("reasoningNoFocalBacterialSourceIdentified"),
      fv("reasoningFeverSourceRemainsUnclear"),
      fv("reasoningOutpatientManagementAppropriateAfterReassessment"),
    ],
    clinicalImpression: [
      fv("impFever"),
      fv("impViralSyndrome"),
      fv("impUpperRespiratoryInfection"),
      fv("impInfluenzaLikeIllness"),
      fv("impUrinaryTractInfection"),
      fv("impPneumonia"),
      fv("impCellulitis"),
      fv("impFeverUnclearSource"),
    ],
    mdmPlanSummary: [
      fv("planAntipyreticTherapyAdministered"),
      fv("planOralHydrationEncouraged"),
      fv("planIvFluidsAdministered"),
      fv("planAntibioticsPrescribed"),
      fv("planSupportiveCareDiscussed"),
      fv("planPcpFollowUpRecommended"),
      fv("planReturnPrecautionsDiscussed"),
      fv("planEdReturnAdvisedWorseningSymptoms"),
      fv("planAdmissionRecommended"),
    ],
  };
}

function feverReassessment(fv: (key: string) => string) {
  return {
    reassessment: [
      fv("reassessFeverImprovedAfterTreatment"),
      fv("reassessSymptomsImprovedAfterTreatment"),
      fv("reassessHeartRateImproved"),
      fv("reassessHydrationStatusImproved"),
      fv("reassessToleratingOralIntake"),
      fv("reassessRemainsHemodynamicallyStable"),
      fv("reassessRepeatExaminationStable"),
      fv("reassessNoClinicalDeteriorationObserved"),
    ],
    followUpDisposition: [
      fv("dispReturnWorseningFeverConfusionDehydration"),
      fv("dispPcpFollowUpRecommended"),
      fv("dispReturnPrecautionsDiscussed"),
      fv("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  };
}

export function buildFeverComplaintV1Intel(fv: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: feverHpi(fv),
    ...feverRos(fv),
    physicalExam: feverExam(fv),
    ...feverMdmGoldStandard(fv),
    mdmAdmitObserveDischarge: [fv("dispObservation"), fv("dispAdmission"), fv("dispDischarge")],
    ...feverReassessment(fv),
  });
}
