/** ME.2Z-R Track C — chart-ready renal / metabolic / endocrine complaint intelligence builders. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

const hyperglycemia = (key: string) => `providerDocumentationComplaintIntel.hyperglycemiaComplaintV1.${key}`;
const hypoglycemia = (key: string) => `providerDocumentationComplaintIntel.hypoglycemiaComplaintV1.${key}`;
const diabetesSickDay = (key: string) => `providerDocumentationComplaintIntel.diabetesSickDayComplaintV1.${key}`;
const insulinMedicationIssue = (key: string) => `providerDocumentationComplaintIntel.insulinMedicationIssueComplaintV1.${key}`;
const polyuriaPolydipsia = (key: string) => `providerDocumentationComplaintIntel.polyuriaPolydipsiaComplaintV1.${key}`;
const dehydrationMetabolic = (key: string) => `providerDocumentationComplaintIntel.dehydrationMetabolicComplaintV1.${key}`;
const electrolyteAbnormality = (key: string) => `providerDocumentationComplaintIntel.electrolyteAbnormalityComplaintV1.${key}`;
const thyroidSymptoms = (key: string) => `providerDocumentationComplaintIntel.thyroidSymptomsComplaintV1.${key}`;
const generalizedWeaknessMetabolic = (key: string) => `providerDocumentationComplaintIntel.generalizedWeaknessMetabolicComplaintV1.${key}`;
const renalFailureSymptoms = (key: string) => `providerDocumentationComplaintIntel.renalFailureSymptomsComplaintV1.${key}`;

export function buildHyperglycemiaComplaintV1Intel(hyperglycemiaFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      hyperglycemiaFn("hpiBloodGlucoseElevatedAtHome"),
      hyperglycemiaFn("hpiGlucoseMeterReadingOver400"),
      hyperglycemiaFn("hpiSymptomsBeganToday"),
      hyperglycemiaFn("hpiSymptomsSeveralDays"),
      hyperglycemiaFn("hpiPolyuria"),
      hyperglycemiaFn("hpiPolydipsia"),
      hyperglycemiaFn("hpiIncreasedThirstAndUrination"),
      hyperglycemiaFn("hpiNausea"),
      hyperglycemiaFn("hpiVomiting"),
      hyperglycemiaFn("hpiAbdominalPain"),
      hyperglycemiaFn("hpiConfusion"),
      hyperglycemiaFn("hpiDeniesConfusion"),
      hyperglycemiaFn("hpiMissedInsulinDose"),
      hyperglycemiaFn("hpiMedicationNonadherence"),
      hyperglycemiaFn("hpiRecentIllnessInfection"),
      hyperglycemiaFn("hpiPriorDiabetesHistory"),
      hyperglycemiaFn("hpiType1Diabetes"),
      hyperglycemiaFn("hpiType2Diabetes"),
      hyperglycemiaFn("hpiSymptomsImproving"),
      hyperglycemiaFn("hpiSymptomsWorsening"),
    ],
    rosImportantPositives: [
      hyperglycemiaFn("rosHyperglycemia"),
      hyperglycemiaFn("rosPolyuria"),
      hyperglycemiaFn("rosPolydipsia"),
      hyperglycemiaFn("rosNausea"),
      hyperglycemiaFn("rosAbdominalPain"),
    ],
    rosImportantNegatives: [
      hyperglycemiaFn("rosDeniesConfusion"),
      hyperglycemiaFn("rosDeniesChestPain"),
      hyperglycemiaFn("rosDeniesFever"),
      hyperglycemiaFn("rosDeniesShortnessOfBreath"),
    ],
    rosRedFlags: [
      hyperglycemiaFn("rfAlteredMentalStatus"),
      hyperglycemiaFn("rfPersistentVomiting"),
      hyperglycemiaFn("rfKussmaulBreathing"),
      hyperglycemiaFn("rfSevereDehydration"),
    ],
    physicalExam: {
      general: [
        hyperglycemiaFn("examNoAcuteDistress"),
        hyperglycemiaFn("examWellAppearing"),
        hyperglycemiaFn("examAppearsDehydrated"),
        hyperglycemiaFn("examDiaphoretic"),
      ],
      abdomen: [
        hyperglycemiaFn("examDryMucousMembranes"),
        hyperglycemiaFn("examNoKussmaulRespirations"),
        hyperglycemiaFn("examTachycardic"),
        hyperglycemiaFn("examAbdominalSoftNonTender"),
        hyperglycemiaFn("examAlteredMentalStatus"),
        hyperglycemiaFn("examFruityBreathOdor"),
      ],
    },
    mdmWorkingAssessment: [
      hyperglycemiaFn("waHyperglycemiaPresentation"),
      hyperglycemiaFn("waSuspectedDka"),
      hyperglycemiaFn("waSuspectedHhs"),
      hyperglycemiaFn("waLowSuspicionDka"),
      hyperglycemiaFn("waMedicationNonadherenceLikely"),
    ],
    mdmDifferentialSynthesis: [
      hyperglycemiaFn("diffDka"),
      hyperglycemiaFn("diffHhs"),
      hyperglycemiaFn("diffSepsis"),
      hyperglycemiaFn("diffAcuteKidneyInjury"),
      hyperglycemiaFn("diffHyperglycemia"),
      hyperglycemiaFn("diffInfection"),
      hyperglycemiaFn("diffMedicationNonadherence"),
      hyperglycemiaFn("diffNewOnsetDiabetes"),
      hyperglycemiaFn("diffDehydration"),
    ],
    mdmDataReviewed: [
      hyperglycemiaFn("mdmGlucoseReviewed"),
      hyperglycemiaFn("mdmCmpReviewed"),
      hyperglycemiaFn("mdmBetaHydroxybutyrateReviewed"),
      hyperglycemiaFn("mdmVenousBloodGasReviewed"),
      hyperglycemiaFn("mdmCbcReviewed"),
      hyperglycemiaFn("mdmUrinalysisReviewed"),
    ],
    mdmRiskStratification: [
      hyperglycemiaFn("riskMildHyperglycemiaLow"),
      hyperglycemiaFn("riskStableVitalsLow"),
      hyperglycemiaFn("riskModerateHyperglycemiaModerate"),
      hyperglycemiaFn("riskSuspectedDkaModerate"),
      hyperglycemiaFn("riskDkaOrHhsHigh"),
      hyperglycemiaFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      hyperglycemiaFn("reasoningGlucoseAndKetonesForDkaEvaluation"),
      hyperglycemiaFn("reasoningIvFluidsAndInsulinForDka"),
      hyperglycemiaFn("reasoningLowSuspicionDkaAfterEvaluation"),
      hyperglycemiaFn("reasoningOutpatientDiabetesManagementAppropriate"),
      hyperglycemiaFn("reasoningAdmissionForGlycemicControl"),
    ],
    clinicalImpression: [
      hyperglycemiaFn("impHyperglycemia"),
      hyperglycemiaFn("impDiabeticKetoacidosis"),
      hyperglycemiaFn("impHyperosmolarHyperglycemicState"),
      hyperglycemiaFn("impType2DiabetesUncontrolled"),
      hyperglycemiaFn("impHyperglycemiaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      hyperglycemiaFn("planIvFluidsAdministered"),
      hyperglycemiaFn("planInsulinGiven"),
      hyperglycemiaFn("planElectrolyteReplacement"),
      hyperglycemiaFn("planGlucoseMonitoring"),
      hyperglycemiaFn("planEndocrinologyConsulted"),
      hyperglycemiaFn("planAdmissionArranged"),
    ],
    reassessment: [
      hyperglycemiaFn("reassessGlucoseImproved"),
      hyperglycemiaFn("reassessGlucoseUnchanged"),
      hyperglycemiaFn("reassessHydrationImproved"),
      hyperglycemiaFn("reassessMentalStatusStable"),
      hyperglycemiaFn("reassessToleratingOralIntake"),
    ],
    followUpDisposition: [
      hyperglycemiaFn("dispDischargedHome"),
      hyperglycemiaFn("dispEndocrinologyFollowUpArranged"),
      hyperglycemiaFn("dispPcpFollowUpArranged"),
      hyperglycemiaFn("dispReturnConfusionVomitingWeaknessChestPain"),
      hyperglycemiaFn("dispAdmittedForGlycemicManagement"),
    ],
    mdmAdmitObserveDischarge: [
      hyperglycemiaFn("dispObservationInEd"),
      hyperglycemiaFn("dispAdmissionArranged"),
    ],
  });
}

export function buildHypoglycemiaComplaintV1Intel(hypoglycemiaFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      hypoglycemiaFn("hpiHypoglycemicEpisodeToday"),
      hypoglycemiaFn("hpiBloodGlucoseLowAtHome"),
      hypoglycemiaFn("hpiSymptomsAfterInsulinDose"),
      hypoglycemiaFn("hpiSkippedMealBeforeEpisode"),
      hypoglycemiaFn("hpiDizzinessWeakness"),
      hypoglycemiaFn("hpiDiaphoresis"),
      hypoglycemiaFn("hpiConfusion"),
      hypoglycemiaFn("hpiSeizureActivity"),
      hypoglycemiaFn("hpiDeniesSyncope"),
      hypoglycemiaFn("hpiSyncopeReported"),
      hypoglycemiaFn("hpiRecurrentEpisodes"),
      hypoglycemiaFn("hpiInsulinUse"),
      hypoglycemiaFn("hpiSulfonylureaUse"),
      hypoglycemiaFn("hpiRenalDiseaseHistory"),
      hypoglycemiaFn("hpiAlcoholUse"),
      hypoglycemiaFn("hpiSymptomsResolvedAfterGlucose"),
      hypoglycemiaFn("hpiSymptomsPersist"),
    ],
    rosImportantPositives: [
      hypoglycemiaFn("rosHypoglycemia"),
      hypoglycemiaFn("rosDizziness"),
      hypoglycemiaFn("rosWeakness"),
      hypoglycemiaFn("rosDiaphoresis"),
      hypoglycemiaFn("rosConfusion"),
    ],
    rosImportantNegatives: [
      hypoglycemiaFn("rosDeniesChestPain"),
      hypoglycemiaFn("rosDeniesSyncope"),
      hypoglycemiaFn("rosDeniesFever"),
      hypoglycemiaFn("rosDeniesSeizure"),
    ],
    rosRedFlags: [
      hypoglycemiaFn("rfRecurrentHypoglycemia"),
      hypoglycemiaFn("rfAlteredMentalStatus"),
      hypoglycemiaFn("rfSeizureActivity"),
      hypoglycemiaFn("rfLossOfConsciousness"),
    ],
    physicalExam: {
      general: [
        hypoglycemiaFn("examNoAcuteDistress"),
        hypoglycemiaFn("examDiaphoretic"),
        hypoglycemiaFn("examPale"),
        hypoglycemiaFn("examWellAppearingAfterTreatment"),
      ],
      neuroPsych: [
        hypoglycemiaFn("examAlertOriented"),
        hypoglycemiaFn("examConfused"),
        hypoglycemiaFn("examSlurredSpeech"),
        hypoglycemiaFn("examNormalGait"),
        hypoglycemiaFn("examNoFocalNeurologicDeficit"),
        hypoglycemiaFn("examGlucoseImprovedAfterTreatment"),
      ],
    },
    mdmWorkingAssessment: [
      hypoglycemiaFn("waHypoglycemiaPresentation"),
      hypoglycemiaFn("waSevereHypoglycemiaResolved"),
      hypoglycemiaFn("waRecurrentHypoglycemiaConcern"),
      hypoglycemiaFn("waMedicationEffectLikely"),
      hypoglycemiaFn("waLowSuspicionSepsis"),
    ],
    mdmDifferentialSynthesis: [
      hypoglycemiaFn("diffSevereHypoglycemia"),
      hypoglycemiaFn("diffSepsis"),
      hypoglycemiaFn("diffAdrenalCrisis"),
      hypoglycemiaFn("diffMedicationEffect"),
      hypoglycemiaFn("diffDecreasedOralIntake"),
      hypoglycemiaFn("diffRenalInsufficiency"),
      hypoglycemiaFn("diffAlcoholRelated"),
      hypoglycemiaFn("diffInsulinoma"),
    ],
    mdmDataReviewed: [
      hypoglycemiaFn("mdmGlucoseReviewed"),
      hypoglycemiaFn("mdmCmpReviewed"),
      hypoglycemiaFn("mdmCbcReviewed"),
      hypoglycemiaFn("mdmEcgReviewed"),
      hypoglycemiaFn("mdmCortisolReviewed"),
    ],
    mdmRiskStratification: [
      hypoglycemiaFn("riskSingleResolvedEpisodeLow"),
      hypoglycemiaFn("riskStableAfterTreatmentLow"),
      hypoglycemiaFn("riskRecurrentEpisodesModerate"),
      hypoglycemiaFn("riskPersistentAlteredMsModerate"),
      hypoglycemiaFn("riskSevereHypoglycemiaHigh"),
      hypoglycemiaFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      hypoglycemiaFn("reasoningOralGlucoseForHypoglycemia"),
      hypoglycemiaFn("reasoningMedicationReconciliationForRecurrentHypoglycemia"),
      hypoglycemiaFn("reasoningLowSuspicionSepsisAfterEvaluation"),
      hypoglycemiaFn("reasoningOutpatientEndocrineFollowUpAppropriate"),
      hypoglycemiaFn("reasoningAdmissionForRecurrentSevereHypoglycemia"),
    ],
    clinicalImpression: [
      hypoglycemiaFn("impHypoglycemia"),
      hypoglycemiaFn("impSevereHypoglycemia"),
      hypoglycemiaFn("impMedicationInducedHypoglycemia"),
      hypoglycemiaFn("impHypoglycemiaResolved"),
      hypoglycemiaFn("impRecurrentHypoglycemia"),
    ],
    mdmPlanSummary: [
      hypoglycemiaFn("planOralGlucoseGiven"),
      hypoglycemiaFn("planIvDextroseGiven"),
      hypoglycemiaFn("planGlucoseMonitoring"),
      hypoglycemiaFn("planMedicationAdjustment"),
      hypoglycemiaFn("planEndocrinologyFollowUpArranged"),
      hypoglycemiaFn("planAdmissionArranged"),
    ],
    reassessment: [
      hypoglycemiaFn("reassessGlucoseNormalized"),
      hypoglycemiaFn("reassessMentalStatusImproved"),
      hypoglycemiaFn("reassessToleratingOralIntake"),
      hypoglycemiaFn("reassessNoRecurrentHypoglycemia"),
      hypoglycemiaFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      hypoglycemiaFn("dispDischargedHome"),
      hypoglycemiaFn("dispEndocrinologyFollowUpArranged"),
      hypoglycemiaFn("dispReturnRecurrentHypoglycemiaConfusion"),
      hypoglycemiaFn("dispReturnChestPainSyncopeWeakness"),
      hypoglycemiaFn("dispAdmittedForHypoglycemiaMonitoring"),
    ],
    mdmAdmitObserveDischarge: [
      hypoglycemiaFn("dispObservationInEd"),
      hypoglycemiaFn("dispAdmissionArranged"),
    ],
  });
}

export function buildDiabetesSickDayComplaintV1Intel(diabetesSickDayFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      diabetesSickDayFn("hpiIllnessSymptomsSeveralDays"),
      diabetesSickDayFn("hpiFeverCoughUriSymptoms"),
      diabetesSickDayFn("hpiVomitingDiarrhea"),
      diabetesSickDayFn("hpiPoorOralIntake"),
      diabetesSickDayFn("hpiBloodGlucoseElevatedAtHome"),
      diabetesSickDayFn("hpiMissedInsulinDose"),
      diabetesSickDayFn("hpiMedicationNonadherence"),
      diabetesSickDayFn("hpiUnableToKeepFluidsDown"),
      diabetesSickDayFn("hpiPolyuriaPolydipsia"),
      diabetesSickDayFn("hpiConfusion"),
      diabetesSickDayFn("hpiDeniesConfusion"),
      diabetesSickDayFn("hpiType1Diabetes"),
      diabetesSickDayFn("hpiType2Diabetes"),
      diabetesSickDayFn("hpiPriorDkaHistory"),
      diabetesSickDayFn("hpiSymptomsWorsening"),
      diabetesSickDayFn("hpiSymptomsImproving"),
    ],
    rosImportantPositives: [
      diabetesSickDayFn("rosFever"),
      diabetesSickDayFn("rosVomiting"),
      diabetesSickDayFn("rosDiarrhea"),
      diabetesSickDayFn("rosPoorIntake"),
      diabetesSickDayFn("rosHyperglycemia"),
    ],
    rosImportantNegatives: [
      diabetesSickDayFn("rosDeniesConfusion"),
      diabetesSickDayFn("rosDeniesChestPain"),
      diabetesSickDayFn("rosDeniesShortnessOfBreath"),
      diabetesSickDayFn("rosDeniesAbdominalPain"),
    ],
    rosRedFlags: [
      diabetesSickDayFn("rfPersistentVomiting"),
      diabetesSickDayFn("rfAlteredMentalStatus"),
      diabetesSickDayFn("rfSevereDehydration"),
      diabetesSickDayFn("rfKussmaulBreathing"),
    ],
    physicalExam: {
      general: [
        diabetesSickDayFn("examNoAcuteDistress"),
        diabetesSickDayFn("examIllAppearing"),
        diabetesSickDayFn("examAppearsDehydrated"),
        diabetesSickDayFn("examFebrile"),
      ],
      abdomen: [
        diabetesSickDayFn("examDryMucousMembranes"),
        diabetesSickDayFn("examTachycardic"),
        diabetesSickDayFn("examNoKussmaulRespirations"),
        diabetesSickDayFn("examAbdominalSoftNonTender"),
        diabetesSickDayFn("examAlteredMentalStatus"),
      ],
    },
    mdmWorkingAssessment: [
      diabetesSickDayFn("waDiabetesSickDayPresentation"),
      diabetesSickDayFn("waSuspectedDka"),
      diabetesSickDayFn("waSuspectedHhs"),
      diabetesSickDayFn("waLowSuspicionDka"),
      diabetesSickDayFn("waViralIllnessTriggerLikely"),
    ],
    mdmDifferentialSynthesis: [
      diabetesSickDayFn("diffDka"),
      diabetesSickDayFn("diffHhs"),
      diabetesSickDayFn("diffSepsis"),
      diabetesSickDayFn("diffDehydration"),
      diabetesSickDayFn("diffViralIllness"),
      diabetesSickDayFn("diffMedicationNonadherence"),
      diabetesSickDayFn("diffGastroenteritis"),
      diabetesSickDayFn("diffUrinaryTractInfection"),
    ],
    mdmDataReviewed: [
      diabetesSickDayFn("mdmGlucoseReviewed"),
      diabetesSickDayFn("mdmCmpReviewed"),
      diabetesSickDayFn("mdmBetaHydroxybutyrateReviewed"),
      diabetesSickDayFn("mdmCbcReviewed"),
      diabetesSickDayFn("mdmUrinalysisReviewed"),
    ],
    mdmRiskStratification: [
      diabetesSickDayFn("riskMildIllnessLow"),
      diabetesSickDayFn("riskStableGlucoseLow"),
      diabetesSickDayFn("riskModerateDehydrationModerate"),
      diabetesSickDayFn("riskSuspectedDkaModerate"),
      diabetesSickDayFn("riskDkaOrHhsHigh"),
      diabetesSickDayFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      diabetesSickDayFn("reasoningSickDayManagementForDiabetes"),
      diabetesSickDayFn("reasoningKetonesForDkaEvaluation"),
      diabetesSickDayFn("reasoningLowSuspicionDkaAfterEvaluation"),
      diabetesSickDayFn("reasoningIvFluidsForDehydration"),
      diabetesSickDayFn("reasoningAdmissionForGlycemicControl"),
    ],
    clinicalImpression: [
      diabetesSickDayFn("impDiabetesSickDay"),
      diabetesSickDayFn("impDiabeticKetoacidosis"),
      diabetesSickDayFn("impViralIllnessWithHyperglycemia"),
      diabetesSickDayFn("impDehydration"),
      diabetesSickDayFn("impHyperglycemiaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      diabetesSickDayFn("planIvFluidsAdministered"),
      diabetesSickDayFn("planInsulinAdjustment"),
      diabetesSickDayFn("planAntiemeticGiven"),
      diabetesSickDayFn("planGlucoseMonitoring"),
      diabetesSickDayFn("planEndocrinologyFollowUpArranged"),
      diabetesSickDayFn("planAdmissionArranged"),
    ],
    reassessment: [
      diabetesSickDayFn("reassessToleratingOralIntake"),
      diabetesSickDayFn("reassessGlucoseImproved"),
      diabetesSickDayFn("reassessHydrationImproved"),
      diabetesSickDayFn("reassessVomitingResolved"),
      diabetesSickDayFn("reassessMentalStatusStable"),
    ],
    followUpDisposition: [
      diabetesSickDayFn("dispDischargedHome"),
      diabetesSickDayFn("dispEndocrinologyFollowUpArranged"),
      diabetesSickDayFn("dispReturnConfusionVomitingWeaknessChestPain"),
      diabetesSickDayFn("dispAdmittedForGlycemicManagement"),
    ],
    mdmAdmitObserveDischarge: [
      diabetesSickDayFn("dispObservationInEd"),
      diabetesSickDayFn("dispAdmissionArranged"),
    ],
  });
}

export function buildInsulinMedicationIssueComplaintV1Intel(insulinMedicationIssueFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      insulinMedicationIssueFn("hpiMissedInsulinDose"),
      insulinMedicationIssueFn("hpiDosingConfusion"),
      insulinMedicationIssueFn("hpiMedicationAccessCostIssue"),
      insulinMedicationIssueFn("hpiInsulinStorageConcern"),
      insulinMedicationIssueFn("hpiBloodGlucoseElevatedAtHome"),
      insulinMedicationIssueFn("hpiHypoglycemicEpisode"),
      insulinMedicationIssueFn("hpiPoorOralIntake"),
      insulinMedicationIssueFn("hpiRecentMedicationChange"),
      insulinMedicationIssueFn("hpiType1Diabetes"),
      insulinMedicationIssueFn("hpiType2Diabetes"),
      insulinMedicationIssueFn("hpiCaregiverAssistsWithInsulin"),
      insulinMedicationIssueFn("hpiSymptomsImproving"),
      insulinMedicationIssueFn("hpiSymptomsWorsening"),
    ],
    rosImportantPositives: [
      insulinMedicationIssueFn("rosHyperglycemia"),
      insulinMedicationIssueFn("rosHypoglycemia"),
      insulinMedicationIssueFn("rosPoorIntake"),
      insulinMedicationIssueFn("rosPolyuria"),
    ],
    rosImportantNegatives: [
      insulinMedicationIssueFn("rosDeniesConfusion"),
      insulinMedicationIssueFn("rosDeniesChestPain"),
      insulinMedicationIssueFn("rosDeniesSyncope"),
      insulinMedicationIssueFn("rosDeniesFever"),
    ],
    rosRedFlags: [
      insulinMedicationIssueFn("rfPersistentHyperglycemia"),
      insulinMedicationIssueFn("rfRecurrentHypoglycemia"),
      insulinMedicationIssueFn("rfAlteredMentalStatus"),
      insulinMedicationIssueFn("rfUnableToObtainMedication"),
    ],
    physicalExam: {
      general: [
        insulinMedicationIssueFn("examNoAcuteDistress"),
        insulinMedicationIssueFn("examWellAppearing"),
        insulinMedicationIssueFn("examAppearsDehydrated"),
      ],
      abdomen: [
        insulinMedicationIssueFn("examDryMucousMembranes"),
        insulinMedicationIssueFn("examInjectionSiteWithoutErythema"),
        insulinMedicationIssueFn("examTachycardic"),
        insulinMedicationIssueFn("examAlertOriented"),
      ],
    },
    mdmWorkingAssessment: [
      insulinMedicationIssueFn("waInsulinMedicationIssuePresentation"),
      insulinMedicationIssueFn("waMedicationAccessBarrier"),
      insulinMedicationIssueFn("waHyperglycemiaFromNonadherence"),
      insulinMedicationIssueFn("waLowSuspicionDka"),
      insulinMedicationIssueFn("waHypoglycemiaRiskFromDosingError"),
    ],
    mdmDifferentialSynthesis: [
      insulinMedicationIssueFn("diffDka"),
      insulinMedicationIssueFn("diffHhs"),
      insulinMedicationIssueFn("diffSevereHypoglycemia"),
      insulinMedicationIssueFn("diffMedicationNonadherence"),
      insulinMedicationIssueFn("diffMedicationAccessIssue"),
      insulinMedicationIssueFn("diffDosingError"),
      insulinMedicationIssueFn("diffInfection"),
    ],
    mdmDataReviewed: [
      insulinMedicationIssueFn("mdmGlucoseReviewed"),
      insulinMedicationIssueFn("mdmCmpReviewed"),
      insulinMedicationIssueFn("mdmBetaHydroxybutyrateReviewed"),
      insulinMedicationIssueFn("mdmCbcReviewed"),
    ],
    mdmRiskStratification: [
      insulinMedicationIssueFn("riskStableGlucoseLow"),
      insulinMedicationIssueFn("riskMedicationEducationNeedModerate"),
      insulinMedicationIssueFn("riskHyperglycemiaModerate"),
      insulinMedicationIssueFn("riskDkaConcernHigh"),
      insulinMedicationIssueFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      insulinMedicationIssueFn("reasoningMedicationReconciliationForInsulinIssue"),
      insulinMedicationIssueFn("reasoningPharmacyResourcesForAccessBarrier"),
      insulinMedicationIssueFn("reasoningLowSuspicionDkaAfterEvaluation"),
      insulinMedicationIssueFn("reasoningDiabetesEducationProvided"),
      insulinMedicationIssueFn("reasoningAdmissionForGlycemicInstability"),
    ],
    clinicalImpression: [
      insulinMedicationIssueFn("impInsulinMedicationIssue"),
      insulinMedicationIssueFn("impMedicationNonadherence"),
      insulinMedicationIssueFn("impHyperglycemia"),
      insulinMedicationIssueFn("impHypoglycemia"),
      insulinMedicationIssueFn("impDiabetesManagementBarrier"),
    ],
    mdmPlanSummary: [
      insulinMedicationIssueFn("planMedicationReconciliation"),
      insulinMedicationIssueFn("planInsulinPrescriptionRefilled"),
      insulinMedicationIssueFn("planDiabetesEducationProvided"),
      insulinMedicationIssueFn("planGlucoseMonitoring"),
      insulinMedicationIssueFn("planEndocrinologyFollowUpArranged"),
      insulinMedicationIssueFn("planAdmissionArranged"),
    ],
    reassessment: [
      insulinMedicationIssueFn("reassessGlucoseStable"),
      insulinMedicationIssueFn("reassessPatientDemonstratesCorrectDosing"),
      insulinMedicationIssueFn("reassessToleratingOralIntake"),
      insulinMedicationIssueFn("reassessNoHypoglycemia"),
    ],
    followUpDisposition: [
      insulinMedicationIssueFn("dispDischargedHome"),
      insulinMedicationIssueFn("dispEndocrinologyFollowUpArranged"),
      insulinMedicationIssueFn("dispReturnConfusionVomitingWeaknessChestPain"),
      insulinMedicationIssueFn("dispAdmittedForGlycemicManagement"),
    ],
    mdmAdmitObserveDischarge: [
      insulinMedicationIssueFn("dispObservationInEd"),
      insulinMedicationIssueFn("dispAdmissionArranged"),
    ],
  });
}

export function buildPolyuriaPolydipsiaComplaintV1Intel(polyuriaPolydipsiaFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      polyuriaPolydipsiaFn("hpiIncreasedThirstAndUrination"),
      polyuriaPolydipsiaFn("hpiPolyuriaSeveralWeeks"),
      polyuriaPolydipsiaFn("hpiNocturia"),
      polyuriaPolydipsiaFn("hpiWeightLoss"),
      polyuriaPolydipsiaFn("hpiFatigue"),
      polyuriaPolydipsiaFn("hpiNausea"),
      polyuriaPolydipsiaFn("hpiVomiting"),
      polyuriaPolydipsiaFn("hpiDeniesFever"),
      polyuriaPolydipsiaFn("hpiDeniesDysuria"),
      polyuriaPolydipsiaFn("hpiPriorDiabetesHistory"),
      polyuriaPolydipsiaFn("hpiNewOnsetSymptoms"),
      polyuriaPolydipsiaFn("hpiBloodGlucoseElevatedAtHome"),
      polyuriaPolydipsiaFn("hpiSymptomsWorsening"),
    ],
    rosImportantPositives: [
      polyuriaPolydipsiaFn("rosPolyuria"),
      polyuriaPolydipsiaFn("rosPolydipsia"),
      polyuriaPolydipsiaFn("rosWeightLoss"),
      polyuriaPolydipsiaFn("rosFatigue"),
      polyuriaPolydipsiaFn("rosNocturia"),
    ],
    rosImportantNegatives: [
      polyuriaPolydipsiaFn("rosDeniesConfusion"),
      polyuriaPolydipsiaFn("rosDeniesDysuria"),
      polyuriaPolydipsiaFn("rosDeniesFever"),
      polyuriaPolydipsiaFn("rosDeniesAbdominalPain"),
    ],
    rosRedFlags: [
      polyuriaPolydipsiaFn("rfAlteredMentalStatus"),
      polyuriaPolydipsiaFn("rfRapidWeightLoss"),
      polyuriaPolydipsiaFn("rfSevereDehydration"),
      polyuriaPolydipsiaFn("rfPersistentVomiting"),
    ],
    physicalExam: {
      general: [
        polyuriaPolydipsiaFn("examNoAcuteDistress"),
        polyuriaPolydipsiaFn("examWellAppearing"),
        polyuriaPolydipsiaFn("examAppearsDehydrated"),
      ],
      abdomen: [
        polyuriaPolydipsiaFn("examDryMucousMembranes"),
        polyuriaPolydipsiaFn("examTachycardic"),
        polyuriaPolydipsiaFn("examAbdominalSoftNonTender"),
        polyuriaPolydipsiaFn("examAlertOriented"),
      ],
    },
    mdmWorkingAssessment: [
      polyuriaPolydipsiaFn("waPolyuriaPolydipsiaPresentation"),
      polyuriaPolydipsiaFn("waNewOnsetDiabetesConcern"),
      polyuriaPolydipsiaFn("waSuspectedDka"),
      polyuriaPolydipsiaFn("waLowSuspicionDka"),
      polyuriaPolydipsiaFn("waUncontrolledDiabetesLikely"),
    ],
    mdmDifferentialSynthesis: [
      polyuriaPolydipsiaFn("diffDka"),
      polyuriaPolydipsiaFn("diffHhs"),
      polyuriaPolydipsiaFn("diffNewOnsetDiabetes"),
      polyuriaPolydipsiaFn("diffUncontrolledDiabetes"),
      polyuriaPolydipsiaFn("diffDiabetesInsipidus"),
      polyuriaPolydipsiaFn("diffUrinaryTractInfection"),
      polyuriaPolydipsiaFn("diffDehydration"),
      polyuriaPolydipsiaFn("diffHypercalcemia"),
    ],
    mdmDataReviewed: [
      polyuriaPolydipsiaFn("mdmGlucoseReviewed"),
      polyuriaPolydipsiaFn("mdmCmpReviewed"),
      polyuriaPolydipsiaFn("mdmBetaHydroxybutyrateReviewed"),
      polyuriaPolydipsiaFn("mdmUrinalysisReviewed"),
      polyuriaPolydipsiaFn("mdmHemoglobinA1cReviewed"),
    ],
    mdmRiskStratification: [
      polyuriaPolydipsiaFn("riskStablePresentationLow"),
      polyuriaPolydipsiaFn("riskNewOnsetDiabetesModerate"),
      polyuriaPolydipsiaFn("riskHyperglycemiaModerate"),
      polyuriaPolydipsiaFn("riskSuspectedDkaHigh"),
      polyuriaPolydipsiaFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      polyuriaPolydipsiaFn("reasoningGlucoseForDiabetesEvaluation"),
      polyuriaPolydipsiaFn("reasoningUrinalysisForInfectionOrGlucosuria"),
      polyuriaPolydipsiaFn("reasoningLowSuspicionDkaAfterEvaluation"),
      polyuriaPolydipsiaFn("reasoningEndocrineFollowUpForNewDiabetes"),
    ],
    clinicalImpression: [
      polyuriaPolydipsiaFn("impPolyuriaAndPolydipsia"),
      polyuriaPolydipsiaFn("impNewOnsetDiabetesMellitus"),
      polyuriaPolydipsiaFn("impUncontrolledDiabetes"),
      polyuriaPolydipsiaFn("impDiabeticKetoacidosis"),
      polyuriaPolydipsiaFn("impPolyuriaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      polyuriaPolydipsiaFn("planIvFluidsAdministered"),
      polyuriaPolydipsiaFn("planInsulinStarted"),
      polyuriaPolydipsiaFn("planGlucoseMonitoring"),
      polyuriaPolydipsiaFn("planEndocrinologyFollowUpArranged"),
      polyuriaPolydipsiaFn("planAdmissionArranged"),
    ],
    reassessment: [
      polyuriaPolydipsiaFn("reassessHydrationImproved"),
      polyuriaPolydipsiaFn("reassessGlucoseImproved"),
      polyuriaPolydipsiaFn("reassessPolyuriaImproved"),
      polyuriaPolydipsiaFn("reassessToleratingOralIntake"),
    ],
    followUpDisposition: [
      polyuriaPolydipsiaFn("dispDischargedHome"),
      polyuriaPolydipsiaFn("dispEndocrinologyFollowUpArranged"),
      polyuriaPolydipsiaFn("dispReturnConfusionVomitingWeaknessChestPain"),
      polyuriaPolydipsiaFn("dispAdmittedForGlycemicManagement"),
    ],
    mdmAdmitObserveDischarge: [
      polyuriaPolydipsiaFn("dispObservationInEd"),
      polyuriaPolydipsiaFn("dispAdmissionArranged"),
    ],
  });
}

export function buildDehydrationMetabolicComplaintV1Intel(dehydrationMetabolicFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      dehydrationMetabolicFn("hpiPoorOralIntake"),
      dehydrationMetabolicFn("hpiVomitingDiarrhea"),
      dehydrationMetabolicFn("hpiDecreasedUrineOutput"),
      dehydrationMetabolicFn("hpiDizzinessWeakness"),
      dehydrationMetabolicFn("hpiHeatExposure"),
      dehydrationMetabolicFn("hpiConfusion"),
      dehydrationMetabolicFn("hpiDeniesConfusion"),
      dehydrationMetabolicFn("hpiDiabetesHistory"),
      dehydrationMetabolicFn("hpiSymptomsSeveralDays"),
      dehydrationMetabolicFn("hpiSymptomsBeganToday"),
      dehydrationMetabolicFn("hpiUnableToKeepFluidsDown"),
      dehydrationMetabolicFn("hpiSymptomsWorsening"),
    ],
    rosImportantPositives: [
      dehydrationMetabolicFn("rosDehydration"),
      dehydrationMetabolicFn("rosVomiting"),
      dehydrationMetabolicFn("rosDiarrhea"),
      dehydrationMetabolicFn("rosDizziness"),
      dehydrationMetabolicFn("rosWeakness"),
    ],
    rosImportantNegatives: [
      dehydrationMetabolicFn("rosDeniesChestPain"),
      dehydrationMetabolicFn("rosDeniesFever"),
      dehydrationMetabolicFn("rosDeniesAbdominalPain"),
      dehydrationMetabolicFn("rosDeniesAlteredMentalStatus"),
    ],
    rosRedFlags: [
      dehydrationMetabolicFn("rfSevereDehydration"),
      dehydrationMetabolicFn("rfAlteredMentalStatus"),
      dehydrationMetabolicFn("rfHypotension"),
      dehydrationMetabolicFn("rfInabilityToTolerateOralIntake"),
    ],
    physicalExam: {
      general: [
        dehydrationMetabolicFn("examNoAcuteDistress"),
        dehydrationMetabolicFn("examIllAppearing"),
        dehydrationMetabolicFn("examAppearsDehydrated"),
        dehydrationMetabolicFn("examTachycardic"),
      ],
      abdomen: [
        dehydrationMetabolicFn("examDryMucousMembranes"),
        dehydrationMetabolicFn("examPoorSkinTurgor"),
        dehydrationMetabolicFn("examDelayedCapillaryRefill"),
        dehydrationMetabolicFn("examHypotensive"),
        dehydrationMetabolicFn("examAlertOriented"),
      ],
    },
    mdmWorkingAssessment: [
      dehydrationMetabolicFn("waDehydrationMetabolicPresentation"),
      dehydrationMetabolicFn("waMildDehydration"),
      dehydrationMetabolicFn("waModerateDehydration"),
      dehydrationMetabolicFn("waSuspectedDka"),
      dehydrationMetabolicFn("waLowSuspicionSepsis"),
    ],
    mdmDifferentialSynthesis: [
      dehydrationMetabolicFn("diffDehydration"),
      dehydrationMetabolicFn("diffDka"),
      dehydrationMetabolicFn("diffHhs"),
      dehydrationMetabolicFn("diffSepsis"),
      dehydrationMetabolicFn("diffAcuteKidneyInjury"),
      dehydrationMetabolicFn("diffHyperkalemia"),
      dehydrationMetabolicFn("diffAdrenalCrisis"),
      dehydrationMetabolicFn("diffGastroenteritis"),
      dehydrationMetabolicFn("diffElectrolyteAbnormality"),
    ],
    mdmDataReviewed: [
      dehydrationMetabolicFn("mdmGlucoseReviewed"),
      dehydrationMetabolicFn("mdmCmpReviewed"),
      dehydrationMetabolicFn("mdmBetaHydroxybutyrateReviewed"),
      dehydrationMetabolicFn("mdmCbcReviewed"),
      dehydrationMetabolicFn("mdmEcgReviewed"),
    ],
    mdmRiskStratification: [
      dehydrationMetabolicFn("riskMildDehydrationLow"),
      dehydrationMetabolicFn("riskToleratingOralIntakeLow"),
      dehydrationMetabolicFn("riskModerateDehydrationModerate"),
      dehydrationMetabolicFn("riskMetabolicDerangementModerate"),
      dehydrationMetabolicFn("riskSevereDehydrationHigh"),
      dehydrationMetabolicFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      dehydrationMetabolicFn("reasoningIvFluidsForDehydration"),
      dehydrationMetabolicFn("reasoningGlucoseAndElectrolytesForMetabolicEvaluation"),
      dehydrationMetabolicFn("reasoningLowSuspicionDkaAfterEvaluation"),
      dehydrationMetabolicFn("reasoningLowSuspicionSepsisAfterEvaluation"),
      dehydrationMetabolicFn("reasoningAdmissionForSevereDehydration"),
    ],
    clinicalImpression: [
      dehydrationMetabolicFn("impDehydration"),
      dehydrationMetabolicFn("impMildDehydration"),
      dehydrationMetabolicFn("impModerateDehydration"),
      dehydrationMetabolicFn("impDiabeticKetoacidosis"),
      dehydrationMetabolicFn("impDehydrationUnclearEtiology"),
    ],
    mdmPlanSummary: [
      dehydrationMetabolicFn("planIvFluidsAdministered"),
      dehydrationMetabolicFn("planElectrolyteReplacement"),
      dehydrationMetabolicFn("planGlucoseMonitoring"),
      dehydrationMetabolicFn("planAntiemeticGiven"),
      dehydrationMetabolicFn("planAdmissionArranged"),
    ],
    reassessment: [
      dehydrationMetabolicFn("reassessHydrationImproved"),
      dehydrationMetabolicFn("reassessToleratingOralIntake"),
      dehydrationMetabolicFn("reassessHeartRateImproved"),
      dehydrationMetabolicFn("reassessMentalStatusStable"),
    ],
    followUpDisposition: [
      dehydrationMetabolicFn("dispDischargedHome"),
      dehydrationMetabolicFn("dispReturnConfusionVomitingWeaknessChestPain"),
      dehydrationMetabolicFn("dispReturnInabilityToKeepFluidsDown"),
      dehydrationMetabolicFn("dispAdmittedForIvFluids"),
    ],
    mdmAdmitObserveDischarge: [
      dehydrationMetabolicFn("dispObservationInEd"),
      dehydrationMetabolicFn("dispAdmissionArranged"),
    ],
  });
}

export function buildElectrolyteAbnormalityComplaintV1Intel(electrolyteAbnormalityFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      electrolyteAbnormalityFn("hpiWeaknessFatigue"),
      electrolyteAbnormalityFn("hpiMuscleCramps"),
      electrolyteAbnormalityFn("hpiPalpitations"),
      electrolyteAbnormalityFn("hpiDizzinessSyncope"),
      electrolyteAbnormalityFn("hpiVomitingDiarrhea"),
      electrolyteAbnormalityFn("hpiDiureticUse"),
      electrolyteAbnormalityFn("hpiRenalDiseaseDialysisHistory"),
      electrolyteAbnormalityFn("hpiRecentPoorOralIntake"),
      electrolyteAbnormalityFn("hpiChestPain"),
      electrolyteAbnormalityFn("hpiDeniesChestPain"),
      electrolyteAbnormalityFn("hpiSymptomsSeveralDays"),
      electrolyteAbnormalityFn("hpiSymptomsBeganToday"),
    ],
    rosImportantPositives: [
      electrolyteAbnormalityFn("rosWeakness"),
      electrolyteAbnormalityFn("rosPalpitations"),
      electrolyteAbnormalityFn("rosDizziness"),
      electrolyteAbnormalityFn("rosNausea"),
      electrolyteAbnormalityFn("rosMuscleCramps"),
    ],
    rosImportantNegatives: [
      electrolyteAbnormalityFn("rosDeniesChestPain"),
      electrolyteAbnormalityFn("rosDeniesSyncope"),
      electrolyteAbnormalityFn("rosDeniesFever"),
      electrolyteAbnormalityFn("rosDeniesShortnessOfBreath"),
    ],
    rosRedFlags: [
      electrolyteAbnormalityFn("rfSyncope"),
      electrolyteAbnormalityFn("rfSevereWeakness"),
      electrolyteAbnormalityFn("rfPalpitationsWithDizziness"),
      electrolyteAbnormalityFn("rfAlteredMentalStatus"),
    ],
    physicalExam: {
      general: [
        electrolyteAbnormalityFn("examNoAcuteDistress"),
        electrolyteAbnormalityFn("examWeakAppearing"),
        electrolyteAbnormalityFn("examAppearsDehydrated"),
      ],
      cardiovascular: [
        electrolyteAbnormalityFn("examTachycardic"),
        electrolyteAbnormalityFn("examIrregularRhythm"),
        electrolyteAbnormalityFn("examRegularRateAndRhythm"),
        electrolyteAbnormalityFn("examLungsClear"),
      ],
      neuroPsych: [
        electrolyteAbnormalityFn("examMuscleWeakness"),
        electrolyteAbnormalityFn("examNormalStrength"),
        electrolyteAbnormalityFn("examAlertOriented"),
        electrolyteAbnormalityFn("examNoFocalNeurologicDeficit"),
      ],
    },
    mdmWorkingAssessment: [
      electrolyteAbnormalityFn("waElectrolyteAbnormalityPresentation"),
      electrolyteAbnormalityFn("waHyperkalemiaConcern"),
      electrolyteAbnormalityFn("waHypokalemiaConcern"),
      electrolyteAbnormalityFn("waRenalFailureContributing"),
      electrolyteAbnormalityFn("waLowSuspicionAcuteCoronarySyndrome"),
    ],
    mdmDifferentialSynthesis: [
      electrolyteAbnormalityFn("diffHyperkalemia"),
      electrolyteAbnormalityFn("diffAcuteKidneyInjury"),
      electrolyteAbnormalityFn("diffAdrenalCrisis"),
      electrolyteAbnormalityFn("diffHypokalemia"),
      electrolyteAbnormalityFn("diffHyponatremia"),
      electrolyteAbnormalityFn("diffRenalFailure"),
      electrolyteAbnormalityFn("diffMedicationEffect"),
      electrolyteAbnormalityFn("diffGiLosses"),
    ],
    mdmDataReviewed: [
      electrolyteAbnormalityFn("mdmCmpReviewed"),
      electrolyteAbnormalityFn("mdmEcgReviewed"),
      electrolyteAbnormalityFn("mdmRenalUltrasoundReviewed"),
      electrolyteAbnormalityFn("mdmCbcReviewed"),
      electrolyteAbnormalityFn("mdmMagnesiumReviewed"),
    ],
    mdmRiskStratification: [
      electrolyteAbnormalityFn("riskMildElectrolyteAbnormalityLow"),
      electrolyteAbnormalityFn("riskStableEcgLow"),
      electrolyteAbnormalityFn("riskModerateElectrolyteDerangementModerate"),
      electrolyteAbnormalityFn("riskHyperkalemiaWithEcgChangesHigh"),
      electrolyteAbnormalityFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      electrolyteAbnormalityFn("reasoningEcgForHyperkalemiaEvaluation"),
      electrolyteAbnormalityFn("reasoningElectrolyteReplacementForDerangement"),
      electrolyteAbnormalityFn("reasoningRenalFunctionForElectrolyteWorkup"),
      electrolyteAbnormalityFn("reasoningAdmissionForSevereHyperkalemia"),
    ],
    clinicalImpression: [
      electrolyteAbnormalityFn("impElectrolyteAbnormality"),
      electrolyteAbnormalityFn("impHyperkalemia"),
      electrolyteAbnormalityFn("impHypokalemia"),
      electrolyteAbnormalityFn("impHyponatremia"),
      electrolyteAbnormalityFn("impElectrolyteDerangementUnclearEtiology"),
    ],
    mdmPlanSummary: [
      electrolyteAbnormalityFn("planElectrolyteReplacement"),
      electrolyteAbnormalityFn("planIvFluidsAdministered"),
      electrolyteAbnormalityFn("planEcgObtained"),
      electrolyteAbnormalityFn("planNephrologyConsulted"),
      electrolyteAbnormalityFn("planAdmissionArranged"),
    ],
    reassessment: [
      electrolyteAbnormalityFn("reassessWeaknessImproved"),
      electrolyteAbnormalityFn("reassessRepeatElectrolytesImproved"),
      electrolyteAbnormalityFn("reassessEcgNormalized"),
      electrolyteAbnormalityFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      electrolyteAbnormalityFn("dispDischargedHome"),
      electrolyteAbnormalityFn("dispNephrologyFollowUpArranged"),
      electrolyteAbnormalityFn("dispReturnPalpitationsWeaknessChestPain"),
      electrolyteAbnormalityFn("dispAdmittedForElectrolyteManagement"),
    ],
    mdmAdmitObserveDischarge: [
      electrolyteAbnormalityFn("dispObservationInEd"),
      electrolyteAbnormalityFn("dispAdmissionArranged"),
    ],
  });
}

export function buildThyroidSymptomsComplaintV1Intel(thyroidSymptomsFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      thyroidSymptomsFn("hpiPalpitations"),
      thyroidSymptomsFn("hpiWeightLoss"),
      thyroidSymptomsFn("hpiWeightGain"),
      thyroidSymptomsFn("hpiHeatIntolerance"),
      thyroidSymptomsFn("hpiColdIntolerance"),
      thyroidSymptomsFn("hpiFatigue"),
      thyroidSymptomsFn("hpiTremor"),
      thyroidSymptomsFn("hpiNeckSwelling"),
      thyroidSymptomsFn("hpiPriorThyroidDisease"),
      thyroidSymptomsFn("hpiThyroidMedicationNonadherence"),
      thyroidSymptomsFn("hpiSymptomsSeveralWeeks"),
      thyroidSymptomsFn("hpiSymptomsBeganToday"),
      thyroidSymptomsFn("hpiDeniesChestPain"),
    ],
    rosImportantPositives: [
      thyroidSymptomsFn("rosPalpitations"),
      thyroidSymptomsFn("rosWeightChange"),
      thyroidSymptomsFn("rosFatigue"),
      thyroidSymptomsFn("rosHeatIntolerance"),
      thyroidSymptomsFn("rosColdIntolerance"),
    ],
    rosImportantNegatives: [
      thyroidSymptomsFn("rosDeniesChestPain"),
      thyroidSymptomsFn("rosDeniesSyncope"),
      thyroidSymptomsFn("rosDeniesFever"),
      thyroidSymptomsFn("rosDeniesShortnessOfBreath"),
    ],
    rosRedFlags: [
      thyroidSymptomsFn("rfSeverePalpitations"),
      thyroidSymptomsFn("rfAlteredMentalStatus"),
      thyroidSymptomsFn("rfFeverWithThyroidSymptoms"),
      thyroidSymptomsFn("rfHypotension"),
    ],
    physicalExam: {
      general: [
        thyroidSymptomsFn("examNoAcuteDistress"),
        thyroidSymptomsFn("examAnxiousAppearing"),
        thyroidSymptomsFn("examFatiguedAppearing"),
        thyroidSymptomsFn("examDiaphoretic"),
      ],
      abdomen: [
        thyroidSymptomsFn("examThyroidEnlargement"),
        thyroidSymptomsFn("examTremorPresent"),
        thyroidSymptomsFn("examTachycardic"),
        thyroidSymptomsFn("examWarmMoistSkin"),
        thyroidSymptomsFn("examDelayedRelaxationReflexes"),
      ],
    },
    mdmWorkingAssessment: [
      thyroidSymptomsFn("waThyroidSymptomsPresentation"),
      thyroidSymptomsFn("waHyperthyroidismConcern"),
      thyroidSymptomsFn("waHypothyroidismConcern"),
      thyroidSymptomsFn("waLowSuspicionThyroidStorm"),
      thyroidSymptomsFn("waLowSuspicionMyxedemaComa"),
    ],
    mdmDifferentialSynthesis: [
      thyroidSymptomsFn("diffThyroidStorm"),
      thyroidSymptomsFn("diffMyxedemaComa"),
      thyroidSymptomsFn("diffSepsis"),
      thyroidSymptomsFn("diffHyperthyroidism"),
      thyroidSymptomsFn("diffHypothyroidism"),
      thyroidSymptomsFn("diffAnxiety"),
      thyroidSymptomsFn("diffAtrialFibrillation"),
      thyroidSymptomsFn("diffMedicationEffect"),
    ],
    mdmDataReviewed: [
      thyroidSymptomsFn("mdmTshReviewed"),
      thyroidSymptomsFn("mdmFreeT4Reviewed"),
      thyroidSymptomsFn("mdmEcgReviewed"),
      thyroidSymptomsFn("mdmCbcReviewed"),
      thyroidSymptomsFn("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      thyroidSymptomsFn("riskStableThyroidSymptomsLow"),
      thyroidSymptomsFn("riskMildThyroidDysfunctionLow"),
      thyroidSymptomsFn("riskModerateThyroidDysfunctionModerate"),
      thyroidSymptomsFn("riskThyroidStormHigh"),
      thyroidSymptomsFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      thyroidSymptomsFn("reasoningThyroidLabsForDysfunctionEvaluation"),
      thyroidSymptomsFn("reasoningEcgForTachycardiaEvaluation"),
      thyroidSymptomsFn("reasoningLowSuspicionThyroidStormAfterEvaluation"),
      thyroidSymptomsFn("reasoningEndocrinologyFollowUpForThyroidDisease"),
      thyroidSymptomsFn("reasoningAdmissionForThyroidStorm"),
    ],
    clinicalImpression: [
      thyroidSymptomsFn("impThyroidDysfunction"),
      thyroidSymptomsFn("impHyperthyroidism"),
      thyroidSymptomsFn("impHypothyroidism"),
      thyroidSymptomsFn("impThyroidStorm"),
      thyroidSymptomsFn("impThyroidSymptomsUnclearEtiology"),
    ],
    mdmPlanSummary: [
      thyroidSymptomsFn("planThyroidMedicationAdjustment"),
      thyroidSymptomsFn("planBetaBlockerGiven"),
      thyroidSymptomsFn("planEcgObtained"),
      thyroidSymptomsFn("planEndocrinologyConsulted"),
      thyroidSymptomsFn("planAdmissionArranged"),
    ],
    reassessment: [
      thyroidSymptomsFn("reassessPalpitationsImproved"),
      thyroidSymptomsFn("reassessHeartRateImproved"),
      thyroidSymptomsFn("reassessTremorImproved"),
      thyroidSymptomsFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      thyroidSymptomsFn("dispDischargedHome"),
      thyroidSymptomsFn("dispEndocrinologyFollowUpArranged"),
      thyroidSymptomsFn("dispReturnPalpitationsChestPainConfusion"),
      thyroidSymptomsFn("dispAdmittedForThyroidManagement"),
    ],
    mdmAdmitObserveDischarge: [
      thyroidSymptomsFn("dispObservationInEd"),
      thyroidSymptomsFn("dispAdmissionArranged"),
    ],
  });
}

export function buildGeneralizedWeaknessMetabolicComplaintV1Intel(
  generalizedWeaknessMetabolicFn: (key: string) => string
): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      generalizedWeaknessMetabolicFn("hpiGeneralizedWeaknessOnset"),
      generalizedWeaknessMetabolicFn("hpiProgressiveWeakness"),
      generalizedWeaknessMetabolicFn("hpiDifficultyAmbulating"),
      generalizedWeaknessMetabolicFn("hpiDeniesFocalWeakness"),
      generalizedWeaknessMetabolicFn("hpiPoorOralIntake"),
      generalizedWeaknessMetabolicFn("hpiVomitingDiarrhea"),
      generalizedWeaknessMetabolicFn("hpiBloodGlucoseElevatedAtHome"),
      generalizedWeaknessMetabolicFn("hpiHypoglycemicEpisode"),
      generalizedWeaknessMetabolicFn("hpiDiabetesHistory"),
      generalizedWeaknessMetabolicFn("hpiRenalDiseaseHistory"),
      generalizedWeaknessMetabolicFn("hpiRecentMedicationChange"),
      generalizedWeaknessMetabolicFn("hpiSymptomsSeveralDays"),
    ],
    rosImportantPositives: [
      generalizedWeaknessMetabolicFn("rosWeakness"),
      generalizedWeaknessMetabolicFn("rosFatigue"),
      generalizedWeaknessMetabolicFn("rosDizziness"),
      generalizedWeaknessMetabolicFn("rosNausea"),
      generalizedWeaknessMetabolicFn("rosDecreasedOralIntake"),
    ],
    rosImportantNegatives: [
      generalizedWeaknessMetabolicFn("rosDeniesFocalWeakness"),
      generalizedWeaknessMetabolicFn("rosDeniesChestPain"),
      generalizedWeaknessMetabolicFn("rosDeniesSyncope"),
      generalizedWeaknessMetabolicFn("rosDeniesFever"),
    ],
    rosRedFlags: [
      generalizedWeaknessMetabolicFn("rfInabilityToAmbulate"),
      generalizedWeaknessMetabolicFn("rfAlteredMentalStatus"),
      generalizedWeaknessMetabolicFn("rfSevereDehydration"),
      generalizedWeaknessMetabolicFn("rfRecurrentHypoglycemia"),
    ],
    physicalExam: {
      general: [
        generalizedWeaknessMetabolicFn("examNoAcuteDistress"),
        generalizedWeaknessMetabolicFn("examFatiguedAppearing"),
        generalizedWeaknessMetabolicFn("examAppearsDehydrated"),
        generalizedWeaknessMetabolicFn("examWellAppearing"),
      ],
      neuroPsych: [
        generalizedWeaknessMetabolicFn("examGlobalWeakness"),
        generalizedWeaknessMetabolicFn("examNormalStrength"),
        generalizedWeaknessMetabolicFn("examNoFocalNeurologicDeficit"),
        generalizedWeaknessMetabolicFn("examAlertOriented"),
      ],
      abdomen: [
        generalizedWeaknessMetabolicFn("examDryMucousMembranes"),
        generalizedWeaknessMetabolicFn("examTachycardic"),
      ],
    },
    mdmWorkingAssessment: [
      generalizedWeaknessMetabolicFn("waGeneralizedWeaknessMetabolicPresentation"),
      generalizedWeaknessMetabolicFn("waMetabolicDerangementConcern"),
      generalizedWeaknessMetabolicFn("waLowSuspicionStroke"),
      generalizedWeaknessMetabolicFn("waDehydrationContributing"),
      generalizedWeaknessMetabolicFn("waElectrolyteAbnormalityConcern"),
    ],
    mdmDifferentialSynthesis: [
      generalizedWeaknessMetabolicFn("diffDka"),
      generalizedWeaknessMetabolicFn("diffHhs"),
      generalizedWeaknessMetabolicFn("diffSevereHypoglycemia"),
      generalizedWeaknessMetabolicFn("diffHyperkalemia"),
      generalizedWeaknessMetabolicFn("diffAcuteKidneyInjury"),
      generalizedWeaknessMetabolicFn("diffSepsis"),
      generalizedWeaknessMetabolicFn("diffAdrenalCrisis"),
      generalizedWeaknessMetabolicFn("diffDehydration"),
      generalizedWeaknessMetabolicFn("diffAnemia"),
      generalizedWeaknessMetabolicFn("diffElectrolyteAbnormality"),
    ],
    mdmDataReviewed: [
      generalizedWeaknessMetabolicFn("mdmGlucoseReviewed"),
      generalizedWeaknessMetabolicFn("mdmCmpReviewed"),
      generalizedWeaknessMetabolicFn("mdmCbcReviewed"),
      generalizedWeaknessMetabolicFn("mdmEcgReviewed"),
      generalizedWeaknessMetabolicFn("mdmBetaHydroxybutyrateReviewed"),
    ],
    mdmRiskStratification: [
      generalizedWeaknessMetabolicFn("riskMildWeaknessLow"),
      generalizedWeaknessMetabolicFn("riskStableVitalsLow"),
      generalizedWeaknessMetabolicFn("riskModerateWeaknessModerate"),
      generalizedWeaknessMetabolicFn("riskMetabolicDerangementHigh"),
      generalizedWeaknessMetabolicFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      generalizedWeaknessMetabolicFn("reasoningMetabolicLabsForWeaknessEvaluation"),
      generalizedWeaknessMetabolicFn("reasoningLowSuspicionStrokeAfterEvaluation"),
      generalizedWeaknessMetabolicFn("reasoningIvFluidsForDehydration"),
      generalizedWeaknessMetabolicFn("reasoningAdmissionForMetabolicInstability"),
    ],
    clinicalImpression: [
      generalizedWeaknessMetabolicFn("impGeneralizedWeakness"),
      generalizedWeaknessMetabolicFn("impMetabolicDerangement"),
      generalizedWeaknessMetabolicFn("impDehydration"),
      generalizedWeaknessMetabolicFn("impElectrolyteAbnormality"),
      generalizedWeaknessMetabolicFn("impWeaknessUnclearEtiology"),
    ],
    mdmPlanSummary: [
      generalizedWeaknessMetabolicFn("planIvFluidsAdministered"),
      generalizedWeaknessMetabolicFn("planElectrolyteReplacement"),
      generalizedWeaknessMetabolicFn("planGlucoseMonitoring"),
      generalizedWeaknessMetabolicFn("planEndocrinologyFollowUpArranged"),
      generalizedWeaknessMetabolicFn("planAdmissionArranged"),
    ],
    reassessment: [
      generalizedWeaknessMetabolicFn("reassessWeaknessImproved"),
      generalizedWeaknessMetabolicFn("reassessAmbulationImproved"),
      generalizedWeaknessMetabolicFn("reassessHydrationImproved"),
      generalizedWeaknessMetabolicFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      generalizedWeaknessMetabolicFn("dispDischargedHome"),
      generalizedWeaknessMetabolicFn("dispEndocrinologyFollowUpArranged"),
      generalizedWeaknessMetabolicFn("dispReturnConfusionVomitingWeaknessChestPain"),
      generalizedWeaknessMetabolicFn("dispAdmittedForMetabolicEvaluation"),
    ],
    mdmAdmitObserveDischarge: [
      generalizedWeaknessMetabolicFn("dispObservationInEd"),
      generalizedWeaknessMetabolicFn("dispAdmissionArranged"),
    ],
  });
}

export function buildRenalFailureSymptomsComplaintV1Intel(renalFailureSymptomsFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      renalFailureSymptomsFn("hpiDecreasedUrineOutput"),
      renalFailureSymptomsFn("hpiEdemaLowerExtremities"),
      renalFailureSymptomsFn("hpiShortnessOfBreath"),
      renalFailureSymptomsFn("hpiNauseaVomiting"),
      renalFailureSymptomsFn("hpiFatigueWeakness"),
      renalFailureSymptomsFn("hpiCreatinineIncreasedFromBaseline"),
      renalFailureSymptomsFn("hpiDialysisHistory"),
      renalFailureSymptomsFn("hpiMissedDialysisSession"),
      renalFailureSymptomsFn("hpiMedicationChanges"),
      renalFailureSymptomsFn("hpiDeniesChestPain"),
      renalFailureSymptomsFn("hpiSymptomsSeveralDays"),
      renalFailureSymptomsFn("hpiSymptomsWorsening"),
    ],
    rosImportantPositives: [
      renalFailureSymptomsFn("rosEdema"),
      renalFailureSymptomsFn("rosDyspnea"),
      renalFailureSymptomsFn("rosNausea"),
      renalFailureSymptomsFn("rosFatigue"),
      renalFailureSymptomsFn("rosDecreasedUrineOutput"),
    ],
    rosImportantNegatives: [
      renalFailureSymptomsFn("rosDeniesChestPain"),
      renalFailureSymptomsFn("rosDeniesFever"),
      renalFailureSymptomsFn("rosDeniesHematuria"),
      renalFailureSymptomsFn("rosDeniesFlankPain"),
    ],
    rosRedFlags: [
      renalFailureSymptomsFn("rfVolumeOverload"),
      renalFailureSymptomsFn("rfAlteredMentalStatus"),
      renalFailureSymptomsFn("rfSevereHyperkalemiaConcern"),
      renalFailureSymptomsFn("rfUremicSymptoms"),
    ],
    physicalExam: {
      general: [
        renalFailureSymptomsFn("examNoAcuteDistress"),
        renalFailureSymptomsFn("examMildRespiratoryDistress"),
        renalFailureSymptomsFn("examIllAppearing"),
        renalFailureSymptomsFn("examVolumeOverloaded"),
      ],
      cardiovascular: [
        renalFailureSymptomsFn("examDialysisAccessPresent"),
        renalFailureSymptomsFn("examPeripheralEdema"),
        renalFailureSymptomsFn("examJugularVenousDistension"),
        renalFailureSymptomsFn("examLungsClear"),
        renalFailureSymptomsFn("examCracklesAtLungBases"),
      ],
    },
    mdmWorkingAssessment: [
      renalFailureSymptomsFn("waRenalFailureSymptomsPresentation"),
      renalFailureSymptomsFn("waAcuteKidneyInjuryConcern"),
      renalFailureSymptomsFn("waChronicKidneyDiseaseExacerbation"),
      renalFailureSymptomsFn("waVolumeOverloadConcern"),
      renalFailureSymptomsFn("waHyperkalemiaConcern"),
    ],
    mdmDifferentialSynthesis: [
      renalFailureSymptomsFn("diffAcuteKidneyInjury"),
      renalFailureSymptomsFn("diffHyperkalemia"),
      renalFailureSymptomsFn("diffSepsis"),
      renalFailureSymptomsFn("diffChronicKidneyDisease"),
      renalFailureSymptomsFn("diffVolumeOverload"),
      renalFailureSymptomsFn("diffUremia"),
      renalFailureSymptomsFn("diffMedicationInducedNephrotoxicity"),
      renalFailureSymptomsFn("diffObstructiveUropathy"),
    ],
    mdmDataReviewed: [
      renalFailureSymptomsFn("mdmCmpReviewed"),
      renalFailureSymptomsFn("mdmRenalUltrasoundReviewed"),
      renalFailureSymptomsFn("mdmEcgReviewed"),
      renalFailureSymptomsFn("mdmUrinalysisReviewed"),
      renalFailureSymptomsFn("mdmCbcReviewed"),
    ],
    mdmRiskStratification: [
      renalFailureSymptomsFn("riskStableRenalFunctionLow"),
      renalFailureSymptomsFn("riskMildVolumeOverloadLow"),
      renalFailureSymptomsFn("riskModerateAkiModerate"),
      renalFailureSymptomsFn("riskHyperkalemiaHigh"),
      renalFailureSymptomsFn("riskDialysisRequiredHigh"),
      renalFailureSymptomsFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      renalFailureSymptomsFn("reasoningRenalFunctionForAkiEvaluation"),
      renalFailureSymptomsFn("reasoningEcgForHyperkalemiaEvaluation"),
      renalFailureSymptomsFn("reasoningDialysisForVolumeOrUremia"),
      renalFailureSymptomsFn("reasoningNephrologyConsultForAki"),
      renalFailureSymptomsFn("reasoningAdmissionForRenalFailure"),
    ],
    clinicalImpression: [
      renalFailureSymptomsFn("impAcuteKidneyInjury"),
      renalFailureSymptomsFn("impChronicKidneyDisease"),
      renalFailureSymptomsFn("impVolumeOverload"),
      renalFailureSymptomsFn("impHyperkalemia"),
      renalFailureSymptomsFn("impRenalFailureUnclearEtiology"),
    ],
    mdmPlanSummary: [
      renalFailureSymptomsFn("planIvDiureticGiven"),
      renalFailureSymptomsFn("planDialysisArranged"),
      renalFailureSymptomsFn("planElectrolyteReplacement"),
      renalFailureSymptomsFn("planNephrologyConsulted"),
      renalFailureSymptomsFn("planAdmissionArranged"),
    ],
    reassessment: [
      renalFailureSymptomsFn("reassessUrineOutputImproved"),
      renalFailureSymptomsFn("reassessEdemaImproved"),
      renalFailureSymptomsFn("reassessDyspneaImproved"),
      renalFailureSymptomsFn("reassessPotassiumImproved"),
    ],
    followUpDisposition: [
      renalFailureSymptomsFn("dispDischargedHome"),
      renalFailureSymptomsFn("dispNephrologyFollowUpArranged"),
      renalFailureSymptomsFn("dispReturnConfusionVomitingWeaknessChestPain"),
      renalFailureSymptomsFn("dispAdmittedForRenalManagement"),
    ],
    mdmAdmitObserveDischarge: [
      renalFailureSymptomsFn("dispObservationInEd"),
      renalFailureSymptomsFn("dispAdmissionArranged"),
    ],
  });
}

export const RENAL_METABOLIC_ENDOCRINE_TEMPLATE_IDS = [
  "hyperglycemia_complaint_v1",
  "hypoglycemia_complaint_v1",
  "diabetes_sick_day_complaint_v1",
  "insulin_medication_issue_complaint_v1",
  "polyuria_polydipsia_complaint_v1",
  "dehydration_metabolic_complaint_v1",
  "electrolyte_abnormality_complaint_v1",
  "thyroid_symptoms_complaint_v1",
  "generalized_weakness_metabolic_complaint_v1",
  "renal_failure_symptoms_complaint_v1",
  "nausea_vomiting_metabolic_complaint_v1",
] as const;
