/** ME.2Y-R Track C — chart-ready cardiac non-chest-pain complaint intelligence builders. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

const palpitations = (key: string) => `providerDocumentationComplaintIntel.palpitationsComplaintV1.${key}`;
const hypertension = (key: string) => `providerDocumentationComplaintIntel.hypertensionComplaintV1.${key}`;
const legSwellingDvt = (key: string) => `providerDocumentationComplaintIntel.legSwellingDvtComplaintV1.${key}`;
const chfSymptoms = (key: string) => `providerDocumentationComplaintIntel.chfSymptomsComplaintV1.${key}`;
const afibRapidRate = (key: string) => `providerDocumentationComplaintIntel.afibRapidRateComplaintV1.${key}`;
const generalizedWeaknessCardiacEquivalent = (key: string) => `providerDocumentationComplaintIntel.generalizedWeaknessCardiacEquivalentComplaintV1.${key}`;
const exertionalDyspnea = (key: string) => `providerDocumentationComplaintIntel.exertionalDyspneaComplaintV1.${key}`;
const edemaVolumeOverload = (key: string) => `providerDocumentationComplaintIntel.edemaVolumeOverloadComplaintV1.${key}`;

export function buildPalpitationsComplaintV1Intel(palpitationsFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      palpitationsFn("hpiPalpitationsBeganToday"),
      palpitationsFn("hpiPalpitationsBeganOvernight"),
      palpitationsFn("hpiIntermittentRacingHeartbeat"),
      palpitationsFn("hpiContinuousPalpitations"),
      palpitationsFn("hpiSuddenOnsetPalpitations"),
      palpitationsFn("hpiGradualOnsetPalpitations"),
      palpitationsFn("hpiExertionalTrigger"),
      palpitationsFn("hpiPalpitationsAtRest"),
      palpitationsFn("hpiAssociatedChestPain"),
      palpitationsFn("hpiAssociatedShortnessOfBreath"),
      palpitationsFn("hpiAssociatedDizziness"),
      palpitationsFn("hpiDeniesSyncope"),
      palpitationsFn("hpiSyncopeReported"),
      palpitationsFn("hpiHeartRate128OnArrival"),
      palpitationsFn("hpiPriorPalpitationsHistory"),
      palpitationsFn("hpiThyroidDiseaseHistory"),
      palpitationsFn("hpiStimulantUse"),
      palpitationsFn("hpiCaffeineUse"),
      palpitationsFn("hpiAnticoagulantUse"),
      palpitationsFn("hpiCardiacHistory"),
      palpitationsFn("hpiAnxietySymptoms"),
      palpitationsFn("hpiSymptomsImproving"),
      palpitationsFn("hpiSymptomsUnchanged"),
    ],
    rosImportantPositives: [
      palpitationsFn("rosPalpitations"),
      palpitationsFn("rosChestPain"),
      palpitationsFn("rosShortnessOfBreath"),
      palpitationsFn("rosDizziness"),
      palpitationsFn("rosAnxiety"),
    ],
    rosImportantNegatives: [
      palpitationsFn("rosDeniesSyncope"),
      palpitationsFn("rosDeniesChestPain"),
      palpitationsFn("rosDeniesFever"),
      palpitationsFn("rosDeniesShortnessOfBreath"),
    ],
    rosRedFlags: [
      palpitationsFn("rfSyncopeEvent"),
      palpitationsFn("rfChestPainConcern"),
      palpitationsFn("rfHemodynamicInstability"),
      palpitationsFn("rfUncontrolledTachycardia"),
    ],
    physicalExam: {
      general: [
        palpitationsFn("examNoAcuteDistress"),
        palpitationsFn("examWellAppearing"),
        palpitationsFn("examDiaphoretic"),
        palpitationsFn("examAnxiousAppearing"),
      ],
      cardiovascular: [
        palpitationsFn("examRegularRateAndRhythm"),
        palpitationsFn("examIrregularRhythm"),
        palpitationsFn("examTachycardic"),
        palpitationsFn("examBradycardic"),
        palpitationsFn("examLungsClear"),
        palpitationsFn("examPeripheralEdemaPresent"),
      ],
    },
    mdmWorkingAssessment: [
      palpitationsFn("waPalpitationsPresentation"),
      palpitationsFn("waSuspectedArrhythmia"),
      palpitationsFn("waBenignPalpitationsLikely"),
      palpitationsFn("waLowSuspicionAcs"),
      palpitationsFn("waConcernForUnstableArrhythmia"),
    ],
    mdmDifferentialSynthesis: [
      palpitationsFn("diffAcuteCoronarySyndrome"),
      palpitationsFn("diffPulmonaryEmbolism"),
      palpitationsFn("diffHeartFailureExacerbation"),
      palpitationsFn("diffUnstableArrhythmia"),
      palpitationsFn("diffVentricularTachycardia"),
      palpitationsFn("diffHypertensiveEmergency"),
      palpitationsFn("diffBenignPalpitations"),
      palpitationsFn("diffPrematureAtrialContractions"),
      palpitationsFn("diffPrematureVentricularContractions"),
      palpitationsFn("diffAtrialFibrillation"),
      palpitationsFn("diffSupraventricularTachycardia"),
      palpitationsFn("diffAnxietyPanic"),
      palpitationsFn("diffThyrotoxicosis"),
    ],
    mdmDataReviewed: [
      palpitationsFn("mdmEcgReviewed"),
      palpitationsFn("mdmTroponinReviewed"),
      palpitationsFn("mdmCbcReviewed"),
      palpitationsFn("mdmCmpReviewed"),
      palpitationsFn("mdmThyroidFunctionReviewed"),
      palpitationsFn("mdmContinuousMonitorReviewed"),
    ],
    mdmRiskStratification: [
      palpitationsFn("riskBenignFeaturesLow"),
      palpitationsFn("riskStableVitalsLow"),
      palpitationsFn("riskPersistentSymptomsModerate"),
      palpitationsFn("riskObservationRequiredModerate"),
      palpitationsFn("riskUnstableArrhythmiaHigh"),
      palpitationsFn("riskAcsConcernHigh"),
      palpitationsFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      palpitationsFn("reasoningEcgForRhythmEvaluation"),
      palpitationsFn("reasoningTroponinForAcsEvaluation"),
      palpitationsFn("reasoningLowSuspicionAcsAfterEvaluation"),
      palpitationsFn("reasoningSafeForOutpatientManagement"),
      palpitationsFn("reasoningAdmissionForRhythmMonitoring"),
    ],
    clinicalImpression: [
      palpitationsFn("impPalpitations"),
      palpitationsFn("impBenignPalpitations"),
      palpitationsFn("impAtrialFibrillation"),
      palpitationsFn("impSupraventricularTachycardia"),
      palpitationsFn("impArrhythmiaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      palpitationsFn("planEcgObtained"),
      palpitationsFn("planTroponinOrdered"),
      palpitationsFn("planRateControlMedicationGiven"),
      palpitationsFn("planCardiologyConsulted"),
      palpitationsFn("planContinuousMonitoring"),
      palpitationsFn("planIvFluidsAdministered"),
      palpitationsFn("planAdmissionArranged"),
    ],
    reassessment: [
      palpitationsFn("reassessPalpitationsImproved"),
      palpitationsFn("reassessPalpitationsUnchanged"),
      palpitationsFn("reassessPalpitationsResolved"),
      palpitationsFn("reassessRhythmStable"),
      palpitationsFn("reassessHemodynamicallyStable"),
      palpitationsFn("reassessSymptomsAfterTreatment"),
    ],
    followUpDisposition: [
      palpitationsFn("dispDischargedHome"),
      palpitationsFn("dispCardiologyFollowUpArranged"),
      palpitationsFn("dispPcpFollowUpArranged"),
      palpitationsFn("dispReturnChestPainSobSyncopePalpitations"),
      palpitationsFn("dispAdmittedForRhythmMonitoring"),
    ],
    mdmAdmitObserveDischarge: [
      palpitationsFn("dispObservationInEd"),
      palpitationsFn("dispAdmissionArranged"),
    ],
  });
}

export function buildHypertensionComplaintV1Intel(hypertensionFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      hypertensionFn("hpiElevatedBpOnArrival"),
      hypertensionFn("hpiBpTrendAtHome"),
      hypertensionFn("hpiAsymptomaticElevatedBp"),
      hypertensionFn("hpiHeadachePresent"),
      hypertensionFn("hpiDeniesHeadache"),
      hypertensionFn("hpiVisionChanges"),
      hypertensionFn("hpiDeniesVisionChanges"),
      hypertensionFn("hpiChestPainPresent"),
      hypertensionFn("hpiDeniesChestPain"),
      hypertensionFn("hpiShortnessOfBreath"),
      hypertensionFn("hpiDeniesShortnessOfBreath"),
      hypertensionFn("hpiMedicationNonadherence"),
      hypertensionFn("hpiRecentMedicationChange"),
      hypertensionFn("hpiPainOrAnxietyTrigger"),
      hypertensionFn("hpiPriorHypertensionHistory"),
      hypertensionFn("hpiRenalDiseaseHistory"),
      hypertensionFn("hpiPregnancyStatus"),
      hypertensionFn("hpiCocaineUse"),
      hypertensionFn("hpiSymptomsImproving"),
      hypertensionFn("hpiSymptomsUnchanged"),
    ],
    rosImportantPositives: [
      hypertensionFn("rosElevatedBpConcern"),
      hypertensionFn("rosHeadache"),
      hypertensionFn("rosChestPain"),
      hypertensionFn("rosShortnessOfBreath"),
      hypertensionFn("rosVisionChanges"),
    ],
    rosImportantNegatives: [
      hypertensionFn("rosDeniesNeuroDeficit"),
      hypertensionFn("rosDeniesChestPain"),
      hypertensionFn("rosDeniesShortnessOfBreath"),
      hypertensionFn("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      hypertensionFn("rfHypertensiveEmergencyConcern"),
      hypertensionFn("rfAlteredMentalStatus"),
      hypertensionFn("rfChestPainConcern"),
      hypertensionFn("rfAcutePulmonaryEdema"),
    ],
    physicalExam: {
      general: [
        hypertensionFn("examNoAcuteDistress"),
        hypertensionFn("examWellAppearing"),
        hypertensionFn("examDiaphoretic"),
        hypertensionFn("examConfused"),
      ],
      cardiovascular: [
        hypertensionFn("examElevatedBloodPressure"),
        hypertensionFn("examRegularRateAndRhythm"),
        hypertensionFn("examTachycardic"),
        hypertensionFn("examLungsClear"),
        hypertensionFn("examPeripheralEdemaPresent"),
        hypertensionFn("examNeuroScreenIntact"),
      ],
    },
    mdmWorkingAssessment: [
      hypertensionFn("waElevatedBpPresentation"),
      hypertensionFn("waAsymptomaticHypertension"),
      hypertensionFn("waHypertensiveUrgencyConcern"),
      hypertensionFn("waHypertensiveEmergencyConcern"),
      hypertensionFn("waLowSuspicionEndOrganDamage"),
    ],
    mdmDifferentialSynthesis: [
      hypertensionFn("diffAcuteCoronarySyndrome"),
      hypertensionFn("diffPulmonaryEmbolism"),
      hypertensionFn("diffHeartFailureExacerbation"),
      hypertensionFn("diffUnstableArrhythmia"),
      hypertensionFn("diffVentricularTachycardia"),
      hypertensionFn("diffHypertensiveEmergency"),
      hypertensionFn("diffHypertensiveUrgency"),
      hypertensionFn("diffAsymptomaticElevatedBp"),
      hypertensionFn("diffPainAnxietyNonadherence"),
      hypertensionFn("diffRenalEndocrineContributors"),
      hypertensionFn("diffMedicationNonadherence"),
    ],
    mdmDataReviewed: [
      hypertensionFn("mdmEcgReviewed"),
      hypertensionFn("mdmCbcReviewed"),
      hypertensionFn("mdmCmpReviewed"),
      hypertensionFn("mdmTroponinReviewed"),
      hypertensionFn("mdmUrinalysisReviewed"),
      hypertensionFn("mdmChestXrayReviewed"),
    ],
    mdmRiskStratification: [
      hypertensionFn("riskAsymptomaticLow"),
      hypertensionFn("riskStableVitalsLow"),
      hypertensionFn("riskSymptomaticModerate"),
      hypertensionFn("riskEndOrganConcernModerate"),
      hypertensionFn("riskHypertensiveEmergencyHigh"),
      hypertensionFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      hypertensionFn("reasoningEndOrganScreeningForSymptomaticBp"),
      hypertensionFn("reasoningMedicationReconciliationForElevatedBp"),
      hypertensionFn("reasoningLowSuspicionEmergencyAfterEvaluation"),
      hypertensionFn("reasoningOutpatientBpManagementAppropriate"),
      hypertensionFn("reasoningAdmissionForBpControl"),
    ],
    clinicalImpression: [
      hypertensionFn("impElevatedBloodPressure"),
      hypertensionFn("impHypertensiveUrgency"),
      hypertensionFn("impHypertensiveEmergency"),
      hypertensionFn("impAsymptomaticHypertension"),
    ],
    mdmPlanSummary: [
      hypertensionFn("planAntihypertensiveMedicationGiven"),
      hypertensionFn("planOralAntihypertensivePrescribed"),
      hypertensionFn("planLabsObtained"),
      hypertensionFn("planEcgObtained"),
      hypertensionFn("planPcpFollowUpArranged"),
      hypertensionFn("planAdmissionArranged"),
    ],
    reassessment: [
      hypertensionFn("reassessBpImproved"),
      hypertensionFn("reassessBpUnchanged"),
      hypertensionFn("reassessSymptomsImproved"),
      hypertensionFn("reassessHemodynamicallyStable"),
      hypertensionFn("reassessNoNeuroDeficit"),
    ],
    followUpDisposition: [
      hypertensionFn("dispDischargedHome"),
      hypertensionFn("dispPcpFollowUpArranged"),
      hypertensionFn("dispReturnHeadacheVisionChestPain"),
      hypertensionFn("dispAdmittedForBpManagement"),
    ],
    mdmAdmitObserveDischarge: [
      hypertensionFn("dispObservationInEd"),
      hypertensionFn("dispAdmissionArranged"),
    ],
  });
}

export function buildLegSwellingDvtComplaintV1Intel(legSwellingDvtFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      legSwellingDvtFn("hpiUnilateralLegSwelling"),
      legSwellingDvtFn("hpiBilateralLegSwelling"),
      legSwellingDvtFn("hpiLegPainPresent"),
      legSwellingDvtFn("hpiLegRednessWarmth"),
      legSwellingDvtFn("hpiRecentImmobilization"),
      legSwellingDvtFn("hpiRecentTravel"),
      legSwellingDvtFn("hpiRecentSurgery"),
      legSwellingDvtFn("hpiTraumaToLeg"),
      legSwellingDvtFn("hpiChestPainPresent"),
      legSwellingDvtFn("hpiDeniesChestPain"),
      legSwellingDvtFn("hpiShortnessOfBreath"),
      legSwellingDvtFn("hpiDeniesShortnessOfBreath"),
      legSwellingDvtFn("hpiHemoptysis"),
      legSwellingDvtFn("hpiDeniesHemoptysis"),
      legSwellingDvtFn("hpiPriorDvtHistory"),
      legSwellingDvtFn("hpiAnticoagulantUse"),
      legSwellingDvtFn("hpiCancerHistory"),
      legSwellingDvtFn("hpiSymptomsSeveralDays"),
      legSwellingDvtFn("hpiSuddenOnsetSwelling"),
    ],
    rosImportantPositives: [
      legSwellingDvtFn("rosLegSwelling"),
      legSwellingDvtFn("rosLegPain"),
      legSwellingDvtFn("rosShortnessOfBreath"),
      legSwellingDvtFn("rosChestPain"),
      legSwellingDvtFn("rosLegRedness"),
    ],
    rosImportantNegatives: [
      legSwellingDvtFn("rosDeniesHemoptysis"),
      legSwellingDvtFn("rosDeniesChestPain"),
      legSwellingDvtFn("rosDeniesFever"),
      legSwellingDvtFn("rosDeniesTrauma"),
    ],
    rosRedFlags: [
      legSwellingDvtFn("rfPeConcern"),
      legSwellingDvtFn("rfUnilateralWarmthRedness"),
      legSwellingDvtFn("rfRapidlyProgressiveSwelling"),
      legSwellingDvtFn("rfCalfPainAtRest"),
    ],
    physicalExam: {
      general: [
        legSwellingDvtFn("examNoAcuteDistress"),
        legSwellingDvtFn("examWellAppearing"),
        legSwellingDvtFn("examMildRespiratoryDistress"),
      ],
      cardiovascular: [
        legSwellingDvtFn("examUnilateralLowerExtremityEdema"),
        legSwellingDvtFn("examBilateralLowerExtremityEdema"),
        legSwellingDvtFn("examCalfTenderness"),
        legSwellingDvtFn("examWarmErythematousLeg"),
        legSwellingDvtFn("examPulsesIntact"),
        legSwellingDvtFn("examLungsClear"),
      ],
    },
    mdmWorkingAssessment: [
      legSwellingDvtFn("waLegSwellingPresentation"),
      legSwellingDvtFn("waSuspectedDvt"),
      legSwellingDvtFn("waSuspectedCellulitis"),
      legSwellingDvtFn("waLowSuspicionPe"),
      legSwellingDvtFn("waConcernForPe"),
    ],
    mdmDifferentialSynthesis: [
      legSwellingDvtFn("diffAcuteCoronarySyndrome"),
      legSwellingDvtFn("diffPulmonaryEmbolism"),
      legSwellingDvtFn("diffHeartFailureExacerbation"),
      legSwellingDvtFn("diffUnstableArrhythmia"),
      legSwellingDvtFn("diffVentricularTachycardia"),
      legSwellingDvtFn("diffHypertensiveEmergency"),
      legSwellingDvtFn("diffDvt"),
      legSwellingDvtFn("diffCellulitis"),
      legSwellingDvtFn("diffChf"),
      legSwellingDvtFn("diffVenousInsufficiency"),
      legSwellingDvtFn("diffBakerCyst"),
      legSwellingDvtFn("diffLymphedema"),
    ],
    mdmDataReviewed: [
      legSwellingDvtFn("mdmLowerExtremityUltrasoundReviewed"),
      legSwellingDvtFn("mdmDimerReviewed"),
      legSwellingDvtFn("mdmCbcReviewed"),
      legSwellingDvtFn("mdmCmpReviewed"),
      legSwellingDvtFn("mdmChestXrayReviewed"),
    ],
    mdmRiskStratification: [
      legSwellingDvtFn("riskLocalizedSwellingLow"),
      legSwellingDvtFn("riskLowWellsScoreLow"),
      legSwellingDvtFn("riskModeratePeRiskModerate"),
      legSwellingDvtFn("riskHighPeRiskHigh"),
      legSwellingDvtFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      legSwellingDvtFn("reasoningUltrasoundForSuspectedDvt"),
      legSwellingDvtFn("reasoningDimerForPeRiskStratification"),
      legSwellingDvtFn("reasoningLowSuspicionPeAfterEvaluation"),
      legSwellingDvtFn("reasoningAnticoagulationForConfirmedDvt"),
    ],
    clinicalImpression: [
      legSwellingDvtFn("impLegSwelling"),
      legSwellingDvtFn("impDeepVeinThrombosis"),
      legSwellingDvtFn("impCellulitis"),
      legSwellingDvtFn("impVenousInsufficiency"),
    ],
    mdmPlanSummary: [
      legSwellingDvtFn("planLowerExtremityUltrasoundOrdered"),
      legSwellingDvtFn("planDimerOrdered"),
      legSwellingDvtFn("planAnticoagulationStarted"),
      legSwellingDvtFn("planAntibioticsPrescribed"),
      legSwellingDvtFn("planAdmissionArranged"),
    ],
    reassessment: [
      legSwellingDvtFn("reassessSwellingUnchanged"),
      legSwellingDvtFn("reassessPainImproved"),
      legSwellingDvtFn("reassessHemodynamicallyStable"),
      legSwellingDvtFn("reassessNoRespiratoryDistress"),
    ],
    followUpDisposition: [
      legSwellingDvtFn("dispDischargedHome"),
      legSwellingDvtFn("dispVascularFollowUpArranged"),
      legSwellingDvtFn("dispReturnSobChestPainWorseningSwelling"),
      legSwellingDvtFn("dispAdmittedForAnticoagulation"),
    ],
    mdmAdmitObserveDischarge: [
      legSwellingDvtFn("dispObservationInEd"),
      legSwellingDvtFn("dispAdmissionArranged"),
    ],
  });
}

export function buildChfSymptomsComplaintV1Intel(chfSymptomsFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      chfSymptomsFn("hpiWorseningDyspnea"),
      chfSymptomsFn("hpiOrthopnea"),
      chfSymptomsFn("hpiParoxysmalNocturnalDyspnea"),
      chfSymptomsFn("hpiLowerExtremityEdema"),
      chfSymptomsFn("hpiWeightGain"),
      chfSymptomsFn("hpiMedicationNonadherence"),
      chfSymptomsFn("hpiHomeOxygenUse"),
      chfSymptomsFn("hpiChestPainPresent"),
      chfSymptomsFn("hpiDeniesChestPain"),
      chfSymptomsFn("hpiProductiveCough"),
      chfSymptomsFn("hpiDeniesFever"),
      chfSymptomsFn("hpiPriorHeartFailureHistory"),
      chfSymptomsFn("hpiRecentDietaryIndiscretion"),
      chfSymptomsFn("hpiSymptomsSeveralDays"),
      chfSymptomsFn("hpiSuddenWorseningToday"),
    ],
    rosImportantPositives: [
      chfSymptomsFn("rosShortnessOfBreath"),
      chfSymptomsFn("rosEdema"),
      chfSymptomsFn("rosOrthopnea"),
      chfSymptomsFn("rosFatigue"),
      chfSymptomsFn("rosCough"),
    ],
    rosImportantNegatives: [
      chfSymptomsFn("rosDeniesChestPain"),
      chfSymptomsFn("rosDeniesFever"),
      chfSymptomsFn("rosDeniesHemoptysis"),
      chfSymptomsFn("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      chfSymptomsFn("rfRespiratoryDistress"),
      chfSymptomsFn("rfHypoxiaConcern"),
      chfSymptomsFn("rfAcutePulmonaryEdema"),
      chfSymptomsFn("rfHemodynamicInstability"),
    ],
    physicalExam: {
      general: [
        chfSymptomsFn("examNoAcuteDistress"),
        chfSymptomsFn("examMildRespiratoryDistress"),
        chfSymptomsFn("examModerateRespiratoryDistress"),
      ],
      cardiovascular: [
        chfSymptomsFn("examBilateralLowerExtremityEdema"),
        chfSymptomsFn("examJugularVenousDistension"),
        chfSymptomsFn("examCracklesAtLungBases"),
        chfSymptomsFn("examLungsClear"),
        chfSymptomsFn("examTachycardic"),
        chfSymptomsFn("examRegularRateAndRhythm"),
      ],
    },
    mdmWorkingAssessment: [
      chfSymptomsFn("waChfExacerbationConcern"),
      chfSymptomsFn("waVolumeOverloadPresentation"),
      chfSymptomsFn("waLowSuspicionAcs"),
      chfSymptomsFn("waLowSuspicionPe"),
      chfSymptomsFn("waDyspneaUnclearEtiology"),
    ],
    mdmDifferentialSynthesis: [
      chfSymptomsFn("diffAcuteCoronarySyndrome"),
      chfSymptomsFn("diffPulmonaryEmbolism"),
      chfSymptomsFn("diffHeartFailureExacerbation"),
      chfSymptomsFn("diffUnstableArrhythmia"),
      chfSymptomsFn("diffVentricularTachycardia"),
      chfSymptomsFn("diffHypertensiveEmergency"),
      chfSymptomsFn("diffChf"),
      chfSymptomsFn("diffAcs"),
      chfSymptomsFn("diffPe"),
      chfSymptomsFn("diffPneumonia"),
      chfSymptomsFn("diffCopdAsthma"),
      chfSymptomsFn("diffRenalFailure"),
    ],
    mdmDataReviewed: [
      chfSymptomsFn("mdmBnpReviewed"),
      chfSymptomsFn("mdmTroponinReviewed"),
      chfSymptomsFn("mdmChestXrayReviewed"),
      chfSymptomsFn("mdmEcgReviewed"),
      chfSymptomsFn("mdmCbcReviewed"),
      chfSymptomsFn("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      chfSymptomsFn("riskStableOutpatientLow"),
      chfSymptomsFn("riskMildVolumeOverloadLow"),
      chfSymptomsFn("riskModerateRespiratoryDistressModerate"),
      chfSymptomsFn("riskObservationRequiredModerate"),
      chfSymptomsFn("riskAcutePulmonaryEdemaHigh"),
      chfSymptomsFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      chfSymptomsFn("reasoningBnpForVolumeStatus"),
      chfSymptomsFn("reasoningDiuresisForVolumeOverload"),
      chfSymptomsFn("reasoningLowSuspicionAcsAfterEvaluation"),
      chfSymptomsFn("reasoningAdmissionForDecompensatedHeartFailure"),
    ],
    clinicalImpression: [
      chfSymptomsFn("impHeartFailureExacerbation"),
      chfSymptomsFn("impAcuteDecompensatedHeartFailure"),
      chfSymptomsFn("impVolumeOverload"),
      chfSymptomsFn("impDyspneaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      chfSymptomsFn("planDiureticGiven"),
      chfSymptomsFn("planSupplementalOxygenAdministered"),
      chfSymptomsFn("planBnpOrdered"),
      chfSymptomsFn("planChestXrayObtained"),
      chfSymptomsFn("planCardiologyConsulted"),
      chfSymptomsFn("planAdmissionArranged"),
    ],
    reassessment: [
      chfSymptomsFn("reassessDyspneaImproved"),
      chfSymptomsFn("reassessDyspneaUnchanged"),
      chfSymptomsFn("reassessOxygenRequirementDecreased"),
      chfSymptomsFn("reassessHemodynamicallyStable"),
      chfSymptomsFn("reassessEdemaUnchanged"),
    ],
    followUpDisposition: [
      chfSymptomsFn("dispDischargedHome"),
      chfSymptomsFn("dispCardiologyFollowUpArranged"),
      chfSymptomsFn("dispReturnWorseningBreathingChestPain"),
      chfSymptomsFn("dispAdmittedForHeartFailureManagement"),
    ],
    mdmAdmitObserveDischarge: [
      chfSymptomsFn("dispObservationInEd"),
      chfSymptomsFn("dispAdmissionArranged"),
    ],
  });
}

export function buildAfibRapidRateComplaintV1Intel(afibRapidRateFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      afibRapidRateFn("hpiPalpitationsOnset"),
      afibRapidRateFn("hpiIrregularRapidHeartbeat"),
      afibRapidRateFn("hpiHeartRate128OnArrival"),
      afibRapidRateFn("hpiChestPainPresent"),
      afibRapidRateFn("hpiDeniesChestPain"),
      afibRapidRateFn("hpiShortnessOfBreath"),
      afibRapidRateFn("hpiDeniesShortnessOfBreath"),
      afibRapidRateFn("hpiDizziness"),
      afibRapidRateFn("hpiDeniesSyncope"),
      afibRapidRateFn("hpiSyncopeReported"),
      afibRapidRateFn("hpiPriorAfibHistory"),
      afibRapidRateFn("hpiAnticoagulantUse"),
      afibRapidRateFn("hpiRateControlMedicationUse"),
      afibRapidRateFn("hpiRecentIllness"),
      afibRapidRateFn("hpiAlcoholUse"),
      afibRapidRateFn("hpiSymptomsImproving"),
    ],
    rosImportantPositives: [
      afibRapidRateFn("rosPalpitations"),
      afibRapidRateFn("rosChestPain"),
      afibRapidRateFn("rosShortnessOfBreath"),
      afibRapidRateFn("rosDizziness"),
      afibRapidRateFn("rosFatigue"),
    ],
    rosImportantNegatives: [
      afibRapidRateFn("rosDeniesSyncope"),
      afibRapidRateFn("rosDeniesChestPain"),
      afibRapidRateFn("rosDeniesFever"),
    ],
    rosRedFlags: [
      afibRapidRateFn("rfHypotensionConcern"),
      afibRapidRateFn("rfSyncopeEvent"),
      afibRapidRateFn("rfChestPainConcern"),
      afibRapidRateFn("rfUncontrolledTachycardia"),
    ],
    physicalExam: {
      general: [
        afibRapidRateFn("examNoAcuteDistress"),
        afibRapidRateFn("examDiaphoretic"),
        afibRapidRateFn("examLightheadedAppearing"),
      ],
      cardiovascular: [
        afibRapidRateFn("examIrregularRhythm"),
        afibRapidRateFn("examTachycardic"),
        afibRapidRateFn("examIrregularlyIrregularRhythm"),
        afibRapidRateFn("examLungsClear"),
        afibRapidRateFn("examPeripheralPulsesPresent"),
      ],
    },
    mdmWorkingAssessment: [
      afibRapidRateFn("waAtrialFibrillationRapidVentricularResponse"),
      afibRapidRateFn("waTachyarrhythmiaPresentation"),
      afibRapidRateFn("waLowSuspicionAcs"),
      afibRapidRateFn("waConcernForHemodynamicInstability"),
    ],
    mdmDifferentialSynthesis: [
      afibRapidRateFn("diffAcuteCoronarySyndrome"),
      afibRapidRateFn("diffPulmonaryEmbolism"),
      afibRapidRateFn("diffHeartFailureExacerbation"),
      afibRapidRateFn("diffUnstableArrhythmia"),
      afibRapidRateFn("diffVentricularTachycardia"),
      afibRapidRateFn("diffHypertensiveEmergency"),
      afibRapidRateFn("diffAfibFlutter"),
      afibRapidRateFn("diffSupraventricularTachycardia"),
      afibRapidRateFn("diffAcs"),
      afibRapidRateFn("diffPe"),
      afibRapidRateFn("diffThyrotoxicosis"),
      afibRapidRateFn("diffInfectionDehydration"),
    ],
    mdmDataReviewed: [
      afibRapidRateFn("mdmEcgReviewed"),
      afibRapidRateFn("mdmTroponinReviewed"),
      afibRapidRateFn("mdmCbcReviewed"),
      afibRapidRateFn("mdmCmpReviewed"),
      afibRapidRateFn("mdmThyroidFunctionReviewed"),
    ],
    mdmRiskStratification: [
      afibRapidRateFn("riskStableAfibLow"),
      afibRapidRateFn("riskRateControlledLow"),
      afibRapidRateFn("riskPersistentTachycardiaModerate"),
      afibRapidRateFn("riskHemodynamicInstabilityHigh"),
      afibRapidRateFn("riskAcsConcernHigh"),
      afibRapidRateFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      afibRapidRateFn("reasoningRateControlForAfibRvr"),
      afibRapidRateFn("reasoningAnticoagulationForAfibRisk"),
      afibRapidRateFn("reasoningTroponinForAcsEvaluation"),
      afibRapidRateFn("reasoningAdmissionForRateControl"),
    ],
    clinicalImpression: [
      afibRapidRateFn("impAtrialFibrillation"),
      afibRapidRateFn("impAtrialFibrillationRvr"),
      afibRapidRateFn("impTachyarrhythmia"),
      afibRapidRateFn("impPalpitationsUnclearEtiology"),
    ],
    mdmPlanSummary: [
      afibRapidRateFn("planRateControlMedicationGiven"),
      afibRapidRateFn("planEcgObtained"),
      afibRapidRateFn("planTroponinOrdered"),
      afibRapidRateFn("planCardiologyConsulted"),
      afibRapidRateFn("planAnticoagulationContinued"),
      afibRapidRateFn("planAdmissionArranged"),
    ],
    reassessment: [
      afibRapidRateFn("reassessHeartRateImproved"),
      afibRapidRateFn("reassessHeartRateUnchanged"),
      afibRapidRateFn("reassessPalpitationsImproved"),
      afibRapidRateFn("reassessHemodynamicallyStable"),
      afibRapidRateFn("reassessSymptomsAfterRateControl"),
    ],
    followUpDisposition: [
      afibRapidRateFn("dispDischargedHome"),
      afibRapidRateFn("dispCardiologyFollowUpArranged"),
      afibRapidRateFn("dispReturnChestPainSobSyncope"),
      afibRapidRateFn("dispAdmittedForRateControl"),
    ],
    mdmAdmitObserveDischarge: [
      afibRapidRateFn("dispObservationInEd"),
      afibRapidRateFn("dispAdmissionArranged"),
    ],
  });
}

export function buildGeneralizedWeaknessCardiacEquivalentComplaintV1Intel(generalizedWeaknessCardiacEquivalentFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      generalizedWeaknessCardiacEquivalentFn("hpiGeneralizedWeaknessOnset"),
      generalizedWeaknessCardiacEquivalentFn("hpiExertionalWeakness"),
      generalizedWeaknessCardiacEquivalentFn("hpiWeaknessAtRest"),
      generalizedWeaknessCardiacEquivalentFn("hpiFunctionalDecline"),
      generalizedWeaknessCardiacEquivalentFn("hpiAssociatedChestDiscomfort"),
      generalizedWeaknessCardiacEquivalentFn("hpiDeniesChestPain"),
      generalizedWeaknessCardiacEquivalentFn("hpiAssociatedShortnessOfBreath"),
      generalizedWeaknessCardiacEquivalentFn("hpiAssociatedPalpitations"),
      generalizedWeaknessCardiacEquivalentFn("hpiDeniesFocalWeakness"),
      generalizedWeaknessCardiacEquivalentFn("hpiDeniesSyncope"),
      generalizedWeaknessCardiacEquivalentFn("hpiPriorCardiacHistory"),
      generalizedWeaknessCardiacEquivalentFn("hpiDiabetesHistory"),
      generalizedWeaknessCardiacEquivalentFn("hpiRecentIllness"),
      generalizedWeaknessCardiacEquivalentFn("hpiPoorOralIntake"),
      generalizedWeaknessCardiacEquivalentFn("hpiSymptomsSeveralDays"),
    ],
    rosImportantPositives: [
      generalizedWeaknessCardiacEquivalentFn("rosWeakness"),
      generalizedWeaknessCardiacEquivalentFn("rosFatigue"),
      generalizedWeaknessCardiacEquivalentFn("rosShortnessOfBreath"),
      generalizedWeaknessCardiacEquivalentFn("rosPalpitations"),
      generalizedWeaknessCardiacEquivalentFn("rosDizziness"),
    ],
    rosImportantNegatives: [
      generalizedWeaknessCardiacEquivalentFn("rosDeniesFocalWeakness"),
      generalizedWeaknessCardiacEquivalentFn("rosDeniesChestPain"),
      generalizedWeaknessCardiacEquivalentFn("rosDeniesSyncope"),
      generalizedWeaknessCardiacEquivalentFn("rosDeniesFever"),
    ],
    rosRedFlags: [
      generalizedWeaknessCardiacEquivalentFn("rfSyncopeConcern"),
      generalizedWeaknessCardiacEquivalentFn("rfAlteredMentalStatus"),
      generalizedWeaknessCardiacEquivalentFn("rfChestPainConcern"),
      generalizedWeaknessCardiacEquivalentFn("rfHemodynamicInstability"),
    ],
    physicalExam: {
      general: [
        generalizedWeaknessCardiacEquivalentFn("examNoAcuteDistress"),
        generalizedWeaknessCardiacEquivalentFn("examFatiguedAppearing"),
        generalizedWeaknessCardiacEquivalentFn("examWellAppearing"),
      ],
      cardiovascular: [
        generalizedWeaknessCardiacEquivalentFn("examRegularRateAndRhythm"),
        generalizedWeaknessCardiacEquivalentFn("examTachycardic"),
        generalizedWeaknessCardiacEquivalentFn("examIrregularRhythm"),
        generalizedWeaknessCardiacEquivalentFn("examLungsClear"),
        generalizedWeaknessCardiacEquivalentFn("examDryMucousMembranes"),
      ],
    },
    mdmWorkingAssessment: [
      generalizedWeaknessCardiacEquivalentFn("waGeneralizedWeaknessPresentation"),
      generalizedWeaknessCardiacEquivalentFn("waCardiacIschemiaEquivalentConcern"),
      generalizedWeaknessCardiacEquivalentFn("waLowSuspicionStroke"),
      generalizedWeaknessCardiacEquivalentFn("waArrhythmiaConcern"),
    ],
    mdmDifferentialSynthesis: [
      generalizedWeaknessCardiacEquivalentFn("diffAcuteCoronarySyndrome"),
      generalizedWeaknessCardiacEquivalentFn("diffPulmonaryEmbolism"),
      generalizedWeaknessCardiacEquivalentFn("diffHeartFailureExacerbation"),
      generalizedWeaknessCardiacEquivalentFn("diffUnstableArrhythmia"),
      generalizedWeaknessCardiacEquivalentFn("diffVentricularTachycardia"),
      generalizedWeaknessCardiacEquivalentFn("diffHypertensiveEmergency"),
      generalizedWeaknessCardiacEquivalentFn("diffCardiacIschemiaEquivalent"),
      generalizedWeaknessCardiacEquivalentFn("diffArrhythmia"),
      generalizedWeaknessCardiacEquivalentFn("diffAnemia"),
      generalizedWeaknessCardiacEquivalentFn("diffDehydration"),
      generalizedWeaknessCardiacEquivalentFn("diffInfection"),
      generalizedWeaknessCardiacEquivalentFn("diffNeurologicCause"),
    ],
    mdmDataReviewed: [
      generalizedWeaknessCardiacEquivalentFn("mdmEcgReviewed"),
      generalizedWeaknessCardiacEquivalentFn("mdmTroponinReviewed"),
      generalizedWeaknessCardiacEquivalentFn("mdmCbcReviewed"),
      generalizedWeaknessCardiacEquivalentFn("mdmCmpReviewed"),
      generalizedWeaknessCardiacEquivalentFn("mdmGlucoseReviewed"),
    ],
    mdmRiskStratification: [
      generalizedWeaknessCardiacEquivalentFn("riskMildWeaknessLow"),
      generalizedWeaknessCardiacEquivalentFn("riskStableVitalsLow"),
      generalizedWeaknessCardiacEquivalentFn("riskPersistentWeaknessModerate"),
      generalizedWeaknessCardiacEquivalentFn("riskCardiacEquivalentHigh"),
      generalizedWeaknessCardiacEquivalentFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      generalizedWeaknessCardiacEquivalentFn("reasoningEcgTroponinForCardiacEquivalent"),
      generalizedWeaknessCardiacEquivalentFn("reasoningLowSuspicionNeurologicCause"),
      generalizedWeaknessCardiacEquivalentFn("reasoningIvFluidsForDehydration"),
      generalizedWeaknessCardiacEquivalentFn("reasoningAdmissionForCardiacEvaluation"),
    ],
    clinicalImpression: [
      generalizedWeaknessCardiacEquivalentFn("impGeneralizedWeakness"),
      generalizedWeaknessCardiacEquivalentFn("impCardiacIschemiaEquivalent"),
      generalizedWeaknessCardiacEquivalentFn("impDehydration"),
      generalizedWeaknessCardiacEquivalentFn("impWeaknessUnclearEtiology"),
    ],
    mdmPlanSummary: [
      generalizedWeaknessCardiacEquivalentFn("planEcgObtained"),
      generalizedWeaknessCardiacEquivalentFn("planTroponinOrdered"),
      generalizedWeaknessCardiacEquivalentFn("planGlucoseChecked"),
      generalizedWeaknessCardiacEquivalentFn("planIvFluidsAdministered"),
      generalizedWeaknessCardiacEquivalentFn("planCardiologyConsulted"),
      generalizedWeaknessCardiacEquivalentFn("planAdmissionArranged"),
    ],
    reassessment: [
      generalizedWeaknessCardiacEquivalentFn("reassessWeaknessImproved"),
      generalizedWeaknessCardiacEquivalentFn("reassessWeaknessUnchanged"),
      generalizedWeaknessCardiacEquivalentFn("reassessAmbulationImproved"),
      generalizedWeaknessCardiacEquivalentFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      generalizedWeaknessCardiacEquivalentFn("dispDischargedHome"),
      generalizedWeaknessCardiacEquivalentFn("dispCardiologyFollowUpArranged"),
      generalizedWeaknessCardiacEquivalentFn("dispReturnChestPainWeaknessSyncope"),
      generalizedWeaknessCardiacEquivalentFn("dispAdmittedForEvaluation"),
    ],
    mdmAdmitObserveDischarge: [
      generalizedWeaknessCardiacEquivalentFn("dispObservationInEd"),
      generalizedWeaknessCardiacEquivalentFn("dispAdmissionArranged"),
    ],
  });
}

export function buildExertionalDyspneaComplaintV1Intel(exertionalDyspneaFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      exertionalDyspneaFn("hpiExertionalDyspneaOnset"),
      exertionalDyspneaFn("hpiReducedExerciseTolerance"),
      exertionalDyspneaFn("hpiDyspneaClimbingStairs"),
      exertionalDyspneaFn("hpiDyspneaWalkingShortDistance"),
      exertionalDyspneaFn("hpiOrthopnea"),
      exertionalDyspneaFn("hpiParoxysmalNocturnalDyspnea"),
      exertionalDyspneaFn("hpiChestPainWithExertion"),
      exertionalDyspneaFn("hpiDeniesChestPain"),
      exertionalDyspneaFn("hpiCough"),
      exertionalDyspneaFn("hpiWheezing"),
      exertionalDyspneaFn("hpiLegSwelling"),
      exertionalDyspneaFn("hpiPriorHeartFailureHistory"),
      exertionalDyspneaFn("hpiPriorCopdHistory"),
      exertionalDyspneaFn("hpiRecentImmobilization"),
      exertionalDyspneaFn("hpiSymptomsProgressive"),
    ],
    rosImportantPositives: [
      exertionalDyspneaFn("rosExertionalDyspnea"),
      exertionalDyspneaFn("rosChestPain"),
      exertionalDyspneaFn("rosEdema"),
      exertionalDyspneaFn("rosCough"),
      exertionalDyspneaFn("rosOrthopnea"),
    ],
    rosImportantNegatives: [
      exertionalDyspneaFn("rosDeniesRestDyspnea"),
      exertionalDyspneaFn("rosDeniesHemoptysis"),
      exertionalDyspneaFn("rosDeniesFever"),
      exertionalDyspneaFn("rosDeniesSyncope"),
    ],
    rosRedFlags: [
      exertionalDyspneaFn("rfRestDyspnea"),
      exertionalDyspneaFn("rfHypoxiaConcern"),
      exertionalDyspneaFn("rfChestPainAtRest"),
      exertionalDyspneaFn("rfSyncopeWithExertion"),
    ],
    physicalExam: {
      general: [
        exertionalDyspneaFn("examNoAcuteDistress"),
        exertionalDyspneaFn("examMildRespiratoryDistress"),
        exertionalDyspneaFn("examWellAppearing"),
      ],
      cardiovascular: [
        exertionalDyspneaFn("examNormalRespiratoryEffortAtRest"),
        exertionalDyspneaFn("examIncreasedWorkOfBreathing"),
        exertionalDyspneaFn("examCracklesAtLungBases"),
        exertionalDyspneaFn("examLungsClear"),
        exertionalDyspneaFn("examBilateralLowerExtremityEdema"),
        exertionalDyspneaFn("examTachycardic"),
      ],
    },
    mdmWorkingAssessment: [
      exertionalDyspneaFn("waExertionalDyspneaPresentation"),
      exertionalDyspneaFn("waHeartFailureConcern"),
      exertionalDyspneaFn("waLowSuspicionPe"),
      exertionalDyspneaFn("waLowSuspicionAcs"),
    ],
    mdmDifferentialSynthesis: [
      exertionalDyspneaFn("diffAcuteCoronarySyndrome"),
      exertionalDyspneaFn("diffPulmonaryEmbolism"),
      exertionalDyspneaFn("diffHeartFailureExacerbation"),
      exertionalDyspneaFn("diffUnstableArrhythmia"),
      exertionalDyspneaFn("diffVentricularTachycardia"),
      exertionalDyspneaFn("diffHypertensiveEmergency"),
      exertionalDyspneaFn("diffChf"),
      exertionalDyspneaFn("diffAcs"),
      exertionalDyspneaFn("diffPe"),
      exertionalDyspneaFn("diffCopdAsthma"),
      exertionalDyspneaFn("diffPneumonia"),
      exertionalDyspneaFn("diffAnemia"),
    ],
    mdmDataReviewed: [
      exertionalDyspneaFn("mdmChestXrayReviewed"),
      exertionalDyspneaFn("mdmEcgReviewed"),
      exertionalDyspneaFn("mdmBnpReviewed"),
      exertionalDyspneaFn("mdmTroponinReviewed"),
      exertionalDyspneaFn("mdmDimerReviewed"),
      exertionalDyspneaFn("mdmCbcReviewed"),
    ],
    mdmRiskStratification: [
      exertionalDyspneaFn("riskStableExertionalDyspneaLow"),
      exertionalDyspneaFn("riskNormalOxygenationLow"),
      exertionalDyspneaFn("riskProgressiveSymptomsModerate"),
      exertionalDyspneaFn("riskRestDyspneaHigh"),
      exertionalDyspneaFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      exertionalDyspneaFn("reasoningBnpForHeartFailureEvaluation"),
      exertionalDyspneaFn("reasoningLowSuspicionPeAfterEvaluation"),
      exertionalDyspneaFn("reasoningOutpatientCardiologyFollowUp"),
      exertionalDyspneaFn("reasoningAdmissionForDecompensation"),
    ],
    clinicalImpression: [
      exertionalDyspneaFn("impExertionalDyspnea"),
      exertionalDyspneaFn("impHeartFailureExacerbation"),
      exertionalDyspneaFn("impDeconditioning"),
      exertionalDyspneaFn("impDyspneaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      exertionalDyspneaFn("planChestXrayObtained"),
      exertionalDyspneaFn("planEcgObtained"),
      exertionalDyspneaFn("planBnpOrdered"),
      exertionalDyspneaFn("planCardiologyFollowUpArranged"),
      exertionalDyspneaFn("planAdmissionArranged"),
    ],
    reassessment: [
      exertionalDyspneaFn("reassessDyspneaImproved"),
      exertionalDyspneaFn("reassessDyspneaUnchanged"),
      exertionalDyspneaFn("reassessOxygenSaturationStable"),
      exertionalDyspneaFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      exertionalDyspneaFn("dispDischargedHome"),
      exertionalDyspneaFn("dispCardiologyFollowUpArranged"),
      exertionalDyspneaFn("dispReturnWorseningBreathingChestPain"),
      exertionalDyspneaFn("dispAdmittedForEvaluation"),
    ],
    mdmAdmitObserveDischarge: [
      exertionalDyspneaFn("dispObservationInEd"),
      exertionalDyspneaFn("dispAdmissionArranged"),
    ],
  });
}

export function buildEdemaVolumeOverloadComplaintV1Intel(edemaVolumeOverloadFn: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      edemaVolumeOverloadFn("hpiPeripheralEdemaOnset"),
      edemaVolumeOverloadFn("hpiBilateralLegSwelling"),
      edemaVolumeOverloadFn("hpiRapidWeightGain"),
      edemaVolumeOverloadFn("hpiAssociatedDyspnea"),
      edemaVolumeOverloadFn("hpiOrthopnea"),
      edemaVolumeOverloadFn("hpiDecreasedUrineOutput"),
      edemaVolumeOverloadFn("hpiMedicationNonadherence"),
      edemaVolumeOverloadFn("hpiDietaryIndiscretion"),
      edemaVolumeOverloadFn("hpiPriorHeartFailureHistory"),
      edemaVolumeOverloadFn("hpiRenalDiseaseHistory"),
      edemaVolumeOverloadFn("hpiLiverDiseaseHistory"),
      edemaVolumeOverloadFn("hpiUnilateralLegSwelling"),
      edemaVolumeOverloadFn("hpiDeniesChestPain"),
      edemaVolumeOverloadFn("hpiSymptomsSeveralDays"),
      edemaVolumeOverloadFn("hpiSuddenWorseningToday"),
    ],
    rosImportantPositives: [
      edemaVolumeOverloadFn("rosEdema"),
      edemaVolumeOverloadFn("rosDyspnea"),
      edemaVolumeOverloadFn("rosWeightGain"),
      edemaVolumeOverloadFn("rosOrthopnea"),
      edemaVolumeOverloadFn("rosFatigue"),
    ],
    rosImportantNegatives: [
      edemaVolumeOverloadFn("rosDeniesUnilateralWarmth"),
      edemaVolumeOverloadFn("rosDeniesChestPain"),
      edemaVolumeOverloadFn("rosDeniesFever"),
      edemaVolumeOverloadFn("rosDeniesHemoptysis"),
    ],
    rosRedFlags: [
      edemaVolumeOverloadFn("rfRapidWeightGain"),
      edemaVolumeOverloadFn("rfSevereDyspnea"),
      edemaVolumeOverloadFn("rfAcutePulmonaryEdema"),
      edemaVolumeOverloadFn("rfUnilateralLegWarmth"),
    ],
    physicalExam: {
      general: [
        edemaVolumeOverloadFn("examNoAcuteDistress"),
        edemaVolumeOverloadFn("examMildRespiratoryDistress"),
        edemaVolumeOverloadFn("examWellAppearing"),
      ],
      cardiovascular: [
        edemaVolumeOverloadFn("examPittingEdemaLowerExtremities"),
        edemaVolumeOverloadFn("examBilateralLowerExtremityEdema"),
        edemaVolumeOverloadFn("examJugularVenousDistension"),
        edemaVolumeOverloadFn("examCracklesAtLungBases"),
        edemaVolumeOverloadFn("examLungsClear"),
        edemaVolumeOverloadFn("examAscitesPresent"),
      ],
    },
    mdmWorkingAssessment: [
      edemaVolumeOverloadFn("waVolumeOverloadPresentation"),
      edemaVolumeOverloadFn("waHeartFailureConcern"),
      edemaVolumeOverloadFn("waRenalFailureConcern"),
      edemaVolumeOverloadFn("waLowSuspicionDvt"),
    ],
    mdmDifferentialSynthesis: [
      edemaVolumeOverloadFn("diffAcuteCoronarySyndrome"),
      edemaVolumeOverloadFn("diffPulmonaryEmbolism"),
      edemaVolumeOverloadFn("diffHeartFailureExacerbation"),
      edemaVolumeOverloadFn("diffUnstableArrhythmia"),
      edemaVolumeOverloadFn("diffVentricularTachycardia"),
      edemaVolumeOverloadFn("diffHypertensiveEmergency"),
      edemaVolumeOverloadFn("diffChf"),
      edemaVolumeOverloadFn("diffRenalDisease"),
      edemaVolumeOverloadFn("diffLiverDisease"),
      edemaVolumeOverloadFn("diffVenousInsufficiency"),
      edemaVolumeOverloadFn("diffMedicationRelated"),
      edemaVolumeOverloadFn("diffDvt"),
    ],
    mdmDataReviewed: [
      edemaVolumeOverloadFn("mdmBnpReviewed"),
      edemaVolumeOverloadFn("mdmCmpReviewed"),
      edemaVolumeOverloadFn("mdmChestXrayReviewed"),
      edemaVolumeOverloadFn("mdmLowerExtremityUltrasoundReviewed"),
      edemaVolumeOverloadFn("mdmUrinalysisReviewed"),
    ],
    mdmRiskStratification: [
      edemaVolumeOverloadFn("riskMildEdemaLow"),
      edemaVolumeOverloadFn("riskStableVolumeStatusLow"),
      edemaVolumeOverloadFn("riskModerateVolumeOverloadModerate"),
      edemaVolumeOverloadFn("riskAcutePulmonaryEdemaHigh"),
      edemaVolumeOverloadFn("riskAdmissionRecommendedHigh"),
    ],
    mdmClinicalRationale: [
      edemaVolumeOverloadFn("reasoningDiureticForVolumeOverload"),
      edemaVolumeOverloadFn("reasoningRenalFunctionForEdemaWorkup"),
      edemaVolumeOverloadFn("reasoningUltrasoundForUnilateralEdema"),
      edemaVolumeOverloadFn("reasoningAdmissionForDecompensatedHeartFailure"),
    ],
    clinicalImpression: [
      edemaVolumeOverloadFn("impPeripheralEdema"),
      edemaVolumeOverloadFn("impVolumeOverload"),
      edemaVolumeOverloadFn("impHeartFailureExacerbation"),
      edemaVolumeOverloadFn("impEdemaUnclearEtiology"),
    ],
    mdmPlanSummary: [
      edemaVolumeOverloadFn("planDiureticGiven"),
      edemaVolumeOverloadFn("planBnpOrdered"),
      edemaVolumeOverloadFn("planChestXrayObtained"),
      edemaVolumeOverloadFn("planLowerExtremityUltrasoundOrdered"),
      edemaVolumeOverloadFn("planAdmissionArranged"),
    ],
    reassessment: [
      edemaVolumeOverloadFn("reassessEdemaUnchanged"),
      edemaVolumeOverloadFn("reassessDyspneaImproved"),
      edemaVolumeOverloadFn("reassessWeightTrendStable"),
      edemaVolumeOverloadFn("reassessHemodynamicallyStable"),
    ],
    followUpDisposition: [
      edemaVolumeOverloadFn("dispDischargedHome"),
      edemaVolumeOverloadFn("dispCardiologyFollowUpArranged"),
      edemaVolumeOverloadFn("dispReturnSobChestPainRapidSwelling"),
      edemaVolumeOverloadFn("dispAdmittedForVolumeManagement"),
    ],
    mdmAdmitObserveDischarge: [
      edemaVolumeOverloadFn("dispObservationInEd"),
      edemaVolumeOverloadFn("dispAdmissionArranged"),
    ],
  });
}

export const CARDIAC_NON_CHEST_PAIN_TEMPLATE_IDS = [
  "palpitations_complaint_v1",
  "hypertension_complaint_v1",
  "leg_swelling_dvt_complaint_v1",
  "chf_symptoms_complaint_v1",
  "afib_rapid_rate_complaint_v1",
  "generalized_weakness_cardiac_equivalent_complaint_v1",
  "near_syncope_complaint_v1",
  "exertional_dyspnea_complaint_v1",
  "edema_volume_overload_complaint_v1",
] as const;
