/** ME.2V-R Track C — chart-ready pediatric legacy chief complaint intelligence builders. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

function sharedPediatricDisposition(p: (key: string) => string) {
  return {
    followUpDisposition: [
      p("dispReturnPrecautionsDiscussed"),
      p("dispPediatricianFollowUpRecommended"),
      p("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  };
}

export function buildPediatricFeverComplaintIntel(pf: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      pf("hpiCaregiverPresent"),
      pf("hpiFeverBeganToday"),
      pf("hpiFeverBeganYesterday"),
      pf("hpiFeverForSeveralDays"),
      pf("hpiReportedTmaxAtHome"),
      pf("hpiIntermittentFever"),
      pf("hpiAntipyreticGivenAtHome"),
      pf("hpiFeverImprovedWithAntipyretic"),
      pf("hpiUpToDateImmunizations"),
      pf("hpiImmunizationsNotUpToDate"),
      pf("hpiSickContactsAtHome"),
      pf("hpiDaycareExposure"),
      pf("hpiDecreasedOralIntake"),
      pf("hpiStillDrinkingFluids"),
      pf("hpiDecreasedWetDiapers"),
      pf("hpiStillMakingWetDiapers"),
      pf("hpiDecreasedActivity"),
      pf("hpiNormalActivityLevel"),
      pf("hpiCough"),
      pf("hpiCongestion"),
      pf("hpiVomiting"),
      pf("hpiDiarrhea"),
      pf("hpiRash"),
      pf("hpiEarPain"),
      pf("hpiDeniesNeckStiffness"),
      pf("hpiDeniesDifficultyBreathing"),
      pf("hpiDeniesLethargy"),
    ],
    rosImportantPositives: [
      pf("rosFever"),
      pf("rosDecreasedAppetite"),
      pf("rosDecreasedUrineOutput"),
      pf("rosCough"),
      pf("rosCongestion"),
      pf("rosVomiting"),
      pf("rosDiarrhea"),
      pf("rosRash"),
      pf("rosEarPain"),
    ],
    rosImportantNegatives: [
      pf("rosDeniesNeckStiffness"),
      pf("rosDeniesDifficultyBreathing"),
      pf("rosDeniesPersistentVomiting"),
      pf("rosDeniesLethargy"),
      pf("rosDeniesSeizureActivity"),
      pf("rosDeniesRash"),
    ],
    rosRedFlags: [
      pf("rfToxicAppearingChild"),
      pf("rfLethargy"),
      pf("rfRespiratoryDistress"),
      pf("rfDehydrationConcern"),
      pf("rfMeningitisConcern"),
      pf("rfSepsisConcern"),
      pf("rfFeverInYoungInfant"),
      pf("rfImmunocompromisedChild"),
    ],
    physicalExam: {
      general: [
        pf("examNonToxicAppearing"),
        pf("examToxicAppearing"),
        pf("examInteractiveWithCaregiver"),
        pf("examConsolable"),
        pf("examFebrile"),
        pf("examAfebrileInEd"),
      ],
      heent: [
        pf("examMoistMucousMembranes"),
        pf("examDryMucousMembranes"),
        pf("examCapillaryRefillNormal"),
        pf("examCapillaryRefillDelayed"),
        pf("examNoMeningismus"),
        pf("examPharyngealErythema"),
      ],
      respiratory: [pf("examNoRespiratoryDistress"), pf("examLungsClear"), pf("examWheezingPresent")],
      abdomen: [pf("examAbdomenSoft"), pf("examNonTenderAbdomen")],
      skin: [pf("examRashPresent"), pf("examNoRash")],
      neuroPsych: [pf("examAgeAppropriateBehavior"), pf("examAlertAndInteractive")],
    },
    mdmWorkingAssessment: [
      pf("waSuspectedViralSyndrome"),
      pf("waFeverUnclearSource"),
      pf("waSuspectedUrinaryTractInfection"),
      pf("waSuspectedPneumonia"),
      pf("waLowSuspicionSepsis"),
      pf("waConcernForSepsis"),
    ],
    mdmDifferentialSynthesis: [
      pf("diffViralSyndrome"),
      pf("diffUri"),
      pf("diffOtitisMedia"),
      pf("diffPneumonia"),
      pf("diffUti"),
      pf("diffGastroenteritis"),
      pf("diffMeningitis"),
      pf("diffSepsis"),
      pf("diffCellulitis"),
      pf("diffKawasakiDisease"),
      pf("diffMisc"),
      pf("diffDehydration"),
      pf("diffFeverWithoutSource"),
    ],
    mdmDataReviewed: [
      pf("mdmCbcReviewed"),
      pf("mdmUrinalysisReviewed"),
      pf("mdmRespiratoryViralTestingReviewed"),
      pf("mdmBloodCulturesReviewed"),
      pf("mdmChestXrayReviewed"),
    ],
    mdmRiskStratification: [
      pf("riskWellAppearingNonToxicLow"),
      pf("riskToleratingOralIntakeLow"),
      pf("riskDehydrationConcernModerate"),
      pf("riskSepsisConcernHigh"),
      pf("riskMeningitisConcernHigh"),
    ],
    mdmClinicalRationale: [
      pf("reasoningMostConsistentWithViralIllness"),
      pf("reasoningLowSuspicionMeningitis"),
      pf("reasoningLowSuspicionSepsis"),
      pf("reasoningHydrationStatusAcceptable"),
      pf("reasoningWeightBasedDosingUsed"),
    ],
    clinicalImpression: [
      pf("impFever"),
      pf("impViralSyndrome"),
      pf("impUpperRespiratoryInfection"),
      pf("impFeverUnclearSource"),
    ],
    mdmPlanSummary: [
      pf("planAntipyreticTherapyAdministered"),
      pf("planOralHydrationEncouraged"),
      pf("planIvFluidsAdministered"),
      pf("planReturnPrecautionsDiscussed"),
      pf("planPediatricianFollowUpRecommended"),
    ],
    mdmAdmitObserveDischarge: [pf("dispObservation"), pf("dispAdmission"), pf("dispDischarge")],
    ...sharedPediatricDisposition(pf),
    reassessment: [
      pf("reassessFeverImprovedAfterTreatment"),
      pf("reassessRemainsNonToxicAppearing"),
      pf("reassessToleratingOralIntake"),
      pf("reassessHydrationStatusImproved"),
      pf("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      pf("dispReturnLethargyBreathingDehydrationFever"),
      pf("dispReturnPrecautionsDiscussed"),
      pf("dispPediatricianFollowUpRecommended"),
      pf("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}

export function buildPediatricSeizureComplaintIntel(pz: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      pz("hpiCaregiverPresent"),
      pz("hpiWitnessedSeizure"),
      pz("hpiSeizureLastedLessThanFiveMinutes"),
      pz("hpiSeizureLastedMoreThanFiveMinutes"),
      pz("hpiGeneralizedTonicClonicActivity"),
      pz("hpiFocalSeizureActivity"),
      pz("hpiReturnedToBaselineAfterEvent"),
      pz("hpiPostIctalSleepiness"),
      pz("hpiPostIctalConfusion"),
      pz("hpiFirstTimeSeizure"),
      pz("hpiPriorSeizureHistory"),
      pz("hpiFeverWithSeizure"),
      pz("hpiHeadTraumaBeforeEvent"),
      pz("hpiPossibleToxinExposure"),
      pz("hpiMissedAntiepilepticDoses"),
      pz("hpiDeniesFever"),
      pz("hpiDeniesHeadTrauma"),
    ],
    rosImportantPositives: [
      pz("rosSeizureActivity"),
      pz("rosPostIctalConfusion"),
      pz("rosFever"),
      pz("rosHeadache"),
      pz("rosVomiting"),
      pz("rosWeakness"),
    ],
    rosImportantNegatives: [
      pz("rosDeniesPersistentAlteredMentalStatus"),
      pz("rosDeniesFocalWeakness"),
      pz("rosDeniesNeckStiffness"),
      pz("rosDeniesRash"),
    ],
    rosRedFlags: [
      pz("rfStatusEpilepticusConcern"),
      pz("rfPersistentAlteredMentalStatus"),
      pz("rfFocalNeurologicDeficit"),
      pz("rfMeningismus"),
      pz("rfRepeatedSeizures"),
      pz("rfHypoglycemiaConcern"),
    ],
    physicalExam: {
      general: [pz("examNonToxicAppearing"), pz("examLethargic"), pz("examPostIctalState")],
      heent: [pz("examNoMeningismus"), pz("examNoPapilledema")],
      neuroPsych: [
        pz("examAlertAndInteractive"),
        pz("examAgeAppropriateBehavior"),
        pz("examNoFocalNeurologicDeficit"),
        pz("examSpeechNormal"),
        pz("examMovesAllExtremities"),
      ],
      skin: [pz("examNoRash"), pz("examPetechialRashPresent")],
    },
    mdmWorkingAssessment: [
      pz("waSuspectedFebrileSeizure"),
      pz("waSuspectedFirstTimeSeizure"),
      pz("waLowSuspicionIntracranialPathology"),
      pz("waConcernForStatusEpilepticus"),
    ],
    mdmDifferentialSynthesis: [
      pz("diffFebrileSeizure"),
      pz("diffStatusEpilepticus"),
      pz("diffHypoglycemia"),
      pz("diffIntracranialPathology"),
      pz("diffMeningitis"),
      pz("diffElectrolyteAbnormality"),
      pz("diffToxicIngestion"),
      pz("diffEpilepsyBreakthrough"),
    ],
    mdmDataReviewed: [
      pz("mdmGlucoseReviewed"),
      pz("mdmElectrolytesReviewed"),
      pz("mdmCtHeadReviewed"),
      pz("mdmEegReviewed"),
      pz("mdmToxicologyScreenReviewed"),
    ],
    mdmRiskStratification: [
      pz("riskReturnedToBaselineLow"),
      pz("riskBriefSimpleFebrileSeizureLow"),
      pz("riskProlongedPostIctalStateModerate"),
      pz("riskStatusEpilepticusHigh"),
      pz("riskIntracranialPathologyHigh"),
    ],
    mdmClinicalRationale: [
      pz("reasoningMostConsistentWithFebrileSeizure"),
      pz("reasoningLowSuspicionMeningitis"),
      pz("reasoningLowSuspicionIntracranialMass"),
      pz("reasoningNoOngoingSeizureActivity"),
    ],
    clinicalImpression: [pz("impSeizure"), pz("impFebrileSeizure"), pz("impFirstTimeSeizure")],
    mdmPlanSummary: [
      pz("planAntipyreticTherapyAdministered"),
      pz("planAntiepilepticLoadingAdministered"),
      pz("planObservationRecommended"),
      pz("planNeurologyFollowUpRecommended"),
      pz("planReturnPrecautionsDiscussed"),
    ],
    mdmAdmitObserveDischarge: [pz("dispObservation"), pz("dispAdmission"), pz("dispDischarge")],
    ...sharedPediatricDisposition(pz),
    reassessment: [
      pz("reassessReturnedToBaseline"),
      pz("reassessNoFurtherSeizureActivity"),
      pz("reassessToleratingOralIntake"),
      pz("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      pz("dispReturnRecurrentSeizuresAlteredMentalStatus"),
      pz("dispReturnPrecautionsDiscussed"),
      pz("dispPediatricianFollowUpRecommended"),
      pz("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}

export function buildPediatricRashComplaintIntel(pr: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      pr("hpiCaregiverPresent"),
      pr("hpiRashBeganToday"),
      pr("hpiRashSpreading"),
      pr("hpiDiffuseBlanchingRash"),
      pr("hpiLocalizedRash"),
      pr("hpiItching"),
      pr("hpiPainfulRash"),
      pr("hpiFever"),
      pr("hpiFacialSwelling"),
      pr("hpiLipSwelling"),
      pr("hpiDifficultyBreathing"),
      pr("hpiRecentAntibioticUse"),
      pr("hpiSickContactsAtHome"),
      pr("hpiDeniesDifficultySwallowing"),
      pr("hpiDeniesShortnessOfBreath"),
    ],
    rosImportantPositives: [
      pr("rosRash"),
      pr("rosItching"),
      pr("rosFever"),
      pr("rosSwelling"),
      pr("rosPain"),
    ],
    rosImportantNegatives: [
      pr("rosDeniesFacialSwelling"),
      pr("rosDeniesLipSwelling"),
      pr("rosDeniesDifficultyBreathing"),
      pr("rosDeniesMucosalInvolvement"),
    ],
    rosRedFlags: [
      pr("rfPurpuraNonBlanching"),
      pr("rfMucosalInvolvement"),
      pr("rfAirwaySwelling"),
      pr("rfHighFeverWithRash"),
      pr("rfToxicAppearingChild"),
      pr("rfRapidRashProgression"),
    ],
    physicalExam: {
      general: [pr("examWellAppearing"), pr("examNonToxicAppearing"), pr("examToxicAppearing")],
      skin: [
        pr("examMaculopapularRash"),
        pr("examUrticarialRash"),
        pr("examPetechiae"),
        pr("examPurpura"),
        pr("examBlanchingErythema"),
        pr("examWarmErythematousPlaque"),
        pr("examFluctuantAbscess"),
      ],
      heent: [pr("examNoOropharyngealErythema"), pr("examConjunctivalInjection")],
      respiratory: [pr("examNoRespiratoryDistress"), pr("examStridorAbsent")],
    },
    mdmWorkingAssessment: [
      pr("waSuspectedViralExanthem"),
      pr("waSuspectedAllergicReaction"),
      pr("waSuspectedCellulitis"),
      pr("waLowSuspicionAnaphylaxis"),
    ],
    mdmDifferentialSynthesis: [
      pr("diffViralExanthem"),
      pr("diffAllergicReaction"),
      pr("diffAnaphylaxis"),
      pr("diffStevensJohnsonSyndrome"),
      pr("diffToxicEpidermalNecrolysis"),
      pr("diffMeningococcemia"),
      pr("diffKawasakiDisease"),
      pr("diffCellulitis"),
      pr("diffAbscess"),
      pr("diffSepsis"),
    ],
    mdmDataReviewed: [
      pr("mdmCbcReviewed"),
      pr("mdmBloodCulturesReviewed"),
      pr("mdmCmpReviewed"),
    ],
    mdmRiskStratification: [
      pr("riskBenignAppearingRashLow"),
      pr("riskLocalizedCellulitisModerate"),
      pr("riskSystemicIllnessWithRashHigh"),
      pr("riskAnaphylaxisHigh"),
    ],
    mdmClinicalRationale: [
      pr("reasoningMostConsistentWithViralExanthem"),
      pr("reasoningLowSuspicionMeningococcemia"),
      pr("reasoningLowSuspicionAnaphylaxis"),
      pr("reasoningNoMucosalInvolvement"),
    ],
    clinicalImpression: [pr("impViralExanthem"), pr("impAllergicRash"), pr("impCellulitis")],
    mdmPlanSummary: [
      pr("planAntihistaminePrescribed"),
      pr("planTopicalTherapyRecommended"),
      pr("planAntibioticsPrescribed"),
      pr("planReturnPrecautionsDiscussed"),
      pr("planPediatricianFollowUpRecommended"),
    ],
    mdmAdmitObserveDischarge: [pr("dispObservation"), pr("dispAdmission"), pr("dispDischarge")],
    ...sharedPediatricDisposition(pr),
    reassessment: [
      pr("reassessRashImproved"),
      pr("reassessNoWorseningSwelling"),
      pr("reassessToleratingOralIntake"),
      pr("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      pr("dispReturnWorseningRashFeverBreathingDifficulty"),
      pr("dispReturnPrecautionsDiscussed"),
      pr("dispPediatricianFollowUpRecommended"),
      pr("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}

export function buildPediatricDehydrationComplaintIntel(pd: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      pd("hpiCaregiverPresent"),
      pd("hpiDecreasedOralIntake"),
      pd("hpiRefusingFluids"),
      pd("hpiToleratingSomeFluids"),
      pd("hpiVomiting"),
      pd("hpiDiarrhea"),
      pd("hpiFever"),
      pd("hpiDecreasedWetDiapers"),
      pd("hpiStillMakingWetDiapers"),
      pd("hpiDecreasedActivity"),
      pd("hpiConcernForDehydration"),
      pd("hpiSickContactsAtHome"),
      pd("hpiDeniesBloodyStool"),
      pd("hpiDeniesSevereAbdominalPain"),
    ],
    rosImportantPositives: [
      pd("rosVomiting"),
      pd("rosDiarrhea"),
      pd("rosDecreasedUrineOutput"),
      pd("rosFever"),
      pd("rosLethargy"),
    ],
    rosImportantNegatives: [
      pd("rosDeniesBloodInStool"),
      pd("rosDeniesSevereAbdominalPain"),
      pd("rosDeniesShortnessOfBreath"),
    ],
    rosRedFlags: [
      pd("rfSevereDehydration"),
      pd("rfAlteredMentalStatus"),
      pd("rfHypotensionConcern"),
      pd("rfInabilityToTolerateOralIntake"),
      pd("rfBiliousVomiting"),
    ],
    physicalExam: {
      general: [pd("examWellAppearing"), pd("examIllAppearing"), pd("examAppearsDehydrated")],
      heent: [pd("examDryMucousMembranes"), pd("examMoistMucousMembranes"), pd("examTackyMucousMembranes")],
      skin: [pd("examPoorSkinTurgor"), pd("examNormalSkinTurgor"), pd("examDelayedCapillaryRefill")],
      abdomen: [pd("examAbdomenSoft"), pd("examMildDiffuseTenderness")],
      neuroPsych: [pd("examAlertAndInteractive"), pd("examLethargic")],
    },
    mdmWorkingAssessment: [
      pd("waMildDehydration"),
      pd("waModerateDehydration"),
      pd("waSuspectedViralGastroenteritis"),
      pd("waLowSuspicionSepsis"),
    ],
    mdmDifferentialSynthesis: [
      pd("diffViralGastroenteritis"),
      pd("diffDehydration"),
      pd("diffSevereDehydration"),
      pd("diffHypoglycemia"),
      pd("diffElectrolyteAbnormality"),
      pd("diffSepsis"),
      pd("diffShock"),
      pd("diffAppendicitis"),
    ],
    mdmDataReviewed: [
      pd("mdmGlucoseReviewed"),
      pd("mdmElectrolytesReviewed"),
      pd("mdmCbcReviewed"),
      pd("mdmUrinalysisReviewed"),
    ],
    mdmRiskStratification: [
      pd("riskMildDehydrationLow"),
      pd("riskModerateDehydrationModerate"),
      pd("riskSevereDehydrationHigh"),
      pd("riskSepsisConcernHigh"),
    ],
    mdmClinicalRationale: [
      pd("reasoningMostConsistentWithViralGastroenteritis"),
      pd("reasoningLowSuspicionSurgicalAbdomen"),
      pd("reasoningLowSuspicionSepsis"),
      pd("reasoningHydrationImprovedWithTreatment"),
    ],
    clinicalImpression: [pd("impDehydration"), pd("impViralGastroenteritis"), pd("impMildDehydration")],
    mdmPlanSummary: [
      pd("planOralRehydrationDiscussed"),
      pd("planIvFluidsAdministered"),
      pd("planAntiemeticsAdministered"),
      pd("planReturnPrecautionsDiscussed"),
      pd("planPediatricianFollowUpRecommended"),
    ],
    mdmAdmitObserveDischarge: [pd("dispObservation"), pd("dispAdmission"), pd("dispDischarge")],
    ...sharedPediatricDisposition(pd),
    reassessment: [
      pd("reassessToleratingOralIntake"),
      pd("reassessHydrationImproved"),
      pd("reassessSymptomsImprovedAfterTreatment"),
      pd("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      pd("dispReturnPersistentVomitingNoUrineOutput"),
      pd("dispReturnPrecautionsDiscussed"),
      pd("dispPediatricianFollowUpRecommended"),
      pd("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}

export function buildPediatricCroupComplaintIntel(pc: (key: string) => string): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      pc("hpiCaregiverPresent"),
      pc("hpiBarkyCough"),
      pc("hpiHoarseVoice"),
      pc("hpiInspiratoryStridorAtRest"),
      pc("hpiStridorWithAgitation"),
      pc("hpiSymptomsWorseAtNight"),
      pc("hpiLowGradeFever"),
      pc("hpiNasalCongestion"),
      pc("hpiDecreasedOralIntake"),
      pc("hpiStillDrinkingFluids"),
      pc("hpiDeniesDrooling"),
      pc("hpiDeniesTripodPositioning"),
    ],
    rosImportantPositives: [
      pc("rosCough"),
      pc("rosStridor"),
      pc("rosHoarseness"),
      pc("rosFever"),
      pc("rosNasalCongestion"),
    ],
    rosImportantNegatives: [
      pc("rosDeniesDrooling"),
      pc("rosDeniesDifficultySwallowing"),
      pc("rosDeniesTripodPositioning"),
    ],
    rosRedFlags: [
      pc("rfStridorAtRest"),
      pc("rfRespiratoryDistress"),
      pc("rfHypoxia"),
      pc("rfDrooling"),
      pc("rfToxicAppearingChild"),
    ],
    physicalExam: {
      general: [pc("examNonToxicAppearing"), pc("examMildRespiratoryDistress"), pc("examModerateRespiratoryDistress")],
      heent: [pc("examHoarseCry"), pc("examNoDrooling"), pc("examOropharynxWithoutExudate")],
      respiratory: [
        pc("examInspiratoryStridor"),
        pc("examBarkyCoughOnExam"),
        pc("examMildSubcostalRetractions"),
        pc("examLungsClear"),
        pc("examNoWheezing"),
      ],
      skin: [pc("examNoRash")],
    },
    mdmWorkingAssessment: [
      pc("waSuspectedCroup"),
      pc("waMildCroup"),
      pc("waModerateCroup"),
      pc("waLowSuspicionEpiglottitis"),
    ],
    mdmDifferentialSynthesis: [
      pc("diffCroup"),
      pc("diffSevereCroup"),
      pc("diffEpiglottitis"),
      pc("diffBacterialTracheitis"),
      pc("diffForeignBodyAspiration"),
      pc("diffRespiratoryFailure"),
      pc("diffPneumonia"),
    ],
    mdmDataReviewed: [pc("mdmChestXrayReviewed"), pc("mdmRespiratoryViralTestingReviewed"), pc("mdmPulseOximetryReviewed")],
    mdmRiskStratification: [
      pc("riskMildCroupLow"),
      pc("riskModerateCroupModerate"),
      pc("riskSevereCroupHigh"),
      pc("riskEpiglottitisHigh"),
    ],
    mdmClinicalRationale: [
      pc("reasoningMostConsistentWithCroup"),
      pc("reasoningLowSuspicionEpiglottitis"),
      pc("reasoningNoDroolingOrToxicAppearance"),
      pc("reasoningRespondingToBronchodilatorSteroidTherapy"),
    ],
    clinicalImpression: [pc("impCroup"), pc("impViralUpperAirwayObstruction"), pc("impLaryngotracheitis")],
    mdmPlanSummary: [
      pc("planDexamethasoneAdministered"),
      pc("planNebulizedEpinephrineAdministered"),
      pc("planHumidifiedAirSupport"),
      pc("planReturnPrecautionsDiscussed"),
      pc("planPediatricianFollowUpRecommended"),
    ],
    mdmAdmitObserveDischarge: [pc("dispObservation"), pc("dispAdmission"), pc("dispDischarge")],
    ...sharedPediatricDisposition(pc),
    reassessment: [
      pc("reassessStridorImproved"),
      pc("reassessWorkOfBreathingImproved"),
      pc("reassessToleratingOralIntake"),
      pc("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      pc("dispReturnWorseningStridorRespiratoryDistress"),
      pc("dispReturnPrecautionsDiscussed"),
      pc("dispPediatricianFollowUpRecommended"),
      pc("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}

export function buildPediatricRsvLikeIllnessComplaintIntel(
  prsv: (key: string) => string
): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      prsv("hpiCaregiverPresent"),
      prsv("hpiCough"),
      prsv("hpiNasalCongestion"),
      prsv("hpiIncreasedWorkOfBreathing"),
      prsv("hpiWheezing"),
      prsv("hpiLowGradeFever"),
      prsv("hpiDecreasedFeeding"),
      prsv("hpiStillTakingSomeFeeds"),
      prsv("hpiDecreasedWetDiapers"),
      prsv("hpiApneaEpisodesReported"),
      prsv("hpiSickContactsAtHome"),
      prsv("hpiPrematurityHistory"),
      prsv("hpiDeniesCyanosis"),
    ],
    rosImportantPositives: [
      prsv("rosCough"),
      prsv("rosCongestion"),
      prsv("rosWheezing"),
      prsv("rosFever"),
      prsv("rosDecreasedFeeding"),
    ],
    rosImportantNegatives: [
      prsv("rosDeniesCyanosis"),
      prsv("rosDeniesSevereRespiratoryDistress"),
      prsv("rosDeniesApnea"),
    ],
    rosRedFlags: [
      prsv("rfRespiratoryDistress"),
      prsv("rfHypoxia"),
      prsv("rfApnea"),
      prsv("rfDehydrationConcern"),
      prsv("rfToxicAppearingChild"),
    ],
    physicalExam: {
      general: [prsv("examNonToxicAppearing"), prsv("examMildRespiratoryDistress"), prsv("examModerateRespiratoryDistress")],
      respiratory: [
        prsv("examWheezing"),
        prsv("examIncreasedWorkOfBreathing"),
        prsv("examSubcostalRetractions"),
        prsv("examLungsClear"),
        prsv("examProlongedExpiratoryPhase"),
      ],
      heent: [prsv("examNasalCongestion"), prsv("examMoistMucousMembranes"), prsv("examDryMucousMembranes")],
      skin: [prsv("examNoCyanosis")],
    },
    mdmWorkingAssessment: [
      prsv("waSuspectedBronchiolitis"),
      prsv("waSuspectedViralRespiratoryIllness"),
      prsv("waLowSuspicionBacterialPneumonia"),
      prsv("waConcernForRespiratoryFailure"),
    ],
    mdmDifferentialSynthesis: [
      prsv("diffBronchiolitis"),
      prsv("diffPneumonia"),
      prsv("diffViralUpperRespiratoryInfection"),
      prsv("diffAsthmaExacerbation"),
      prsv("diffApneaOfInfancy"),
      prsv("diffRespiratoryFailure"),
      prsv("diffDehydration"),
    ],
    mdmDataReviewed: [
      prsv("mdmChestXrayReviewed"),
      prsv("mdmRespiratoryViralTestingReviewed"),
      prsv("mdmPulseOximetryReviewed"),
    ],
    mdmRiskStratification: [
      prsv("riskMildBronchiolitisLow"),
      prsv("riskModerateBronchiolitisModerate"),
      prsv("riskRespiratoryFailureHigh"),
      prsv("riskApneaHigh"),
    ],
    mdmClinicalRationale: [
      prsv("reasoningMostConsistentWithBronchiolitis"),
      prsv("reasoningLowSuspicionBacterialPneumonia"),
      prsv("reasoningOxygenRequirementAssessed"),
      prsv("reasoningHydrationStatusAcceptable"),
    ],
    clinicalImpression: [prsv("impBronchiolitis"), prsv("impViralRespiratoryIllness"), prsv("impRsvLikeIllness")],
    mdmPlanSummary: [
      prsv("planSupplementalOxygenAdministered"),
      prsv("planBronchodilatorTrialAdministered"),
      prsv("planNasalSuctioningPerformed"),
      prsv("planOralHydrationEncouraged"),
      prsv("planReturnPrecautionsDiscussed"),
    ],
    mdmAdmitObserveDischarge: [prsv("dispObservation"), prsv("dispAdmission"), prsv("dispDischarge")],
    ...sharedPediatricDisposition(prsv),
    reassessment: [
      prsv("reassessWorkOfBreathingImproved"),
      prsv("reassessOxygenRequirementDecreased"),
      prsv("reassessToleratingFeeds"),
      prsv("reassessCaregiverComfortableWithPlan"),
    ],
    followUpDisposition: [
      prsv("dispReturnWorseningBreathingPoorFeedingApnea"),
      prsv("dispReturnPrecautionsDiscussed"),
      prsv("dispPediatricianFollowUpRecommended"),
      prsv("dispEdReturnAdvisedWorseningSymptoms"),
    ],
  });
}
