/** ME.2X-R Track C — chart-ready psychiatric / behavioral complaint intelligence builder. */
import type { ProviderDocumentationComplaintIntelligence } from "./providerDocumentationComplaintIntelligence";

const intel = (bundle: ProviderDocumentationComplaintIntelligence): ProviderDocumentationComplaintIntelligence => bundle;

export const PSYCH_BEHAVIORAL_TEMPLATE_IDS = ["psychiatric_behavioral"] as const;

export function buildPsychiatricBehavioralComplaintIntel(
  psychFn: (key: string) => string
): ProviderDocumentationComplaintIntelligence {
  return intel({
    hpi: [
      psychFn("hpiReportsSuicidalThoughts"),
      psychFn("hpiDeniesCurrentSuicidalPlan"),
      psychFn("hpiReportsHomicidalThoughts"),
      psychFn("hpiDeniesHomicidalThoughts"),
      psychFn("hpiReportsHallucinations"),
      psychFn("hpiDeniesHallucinations"),
      psychFn("hpiCommandHallucinations"),
      psychFn("hpiParanoia"),
      psychFn("hpiAgitation"),
      psychFn("hpiAnxietySymptoms"),
      psychFn("hpiDepressiveSymptoms"),
      psychFn("hpiManicSymptoms"),
      psychFn("hpiSubstanceUse"),
      psychFn("hpiMedicationNonadherence"),
      psychFn("hpiRecentStressor"),
      psychFn("hpiPriorPsychiatricHistory"),
      psychFn("hpiPriorSuicideAttempt"),
      psychFn("hpiAccessToWeapons"),
      psychFn("hpiDeniesAccessToWeapons"),
      psychFn("hpiIntentionalIngestion"),
      psychFn("hpiDeniesIngestion"),
      psychFn("hpiCollateralHistorianPresent"),
      psychFn("hpiEmsReport"),
      psychFn("hpiUnableToContractForSafety"),
      psychFn("hpiInsomnia"),
      psychFn("hpiPanicAttackSymptoms"),
    ],
    rosImportantPositives: [
      psychFn("rosAnxiety"),
      psychFn("rosDepression"),
      psychFn("rosHallucinations"),
      psychFn("rosSuicidalThoughts"),
      psychFn("rosHomicidalThoughts"),
      psychFn("rosInsomnia"),
      psychFn("rosSubstanceUse"),
      psychFn("rosAgitation"),
      psychFn("rosParanoia"),
    ],
    rosImportantNegatives: [
      psychFn("rosDeniesSuicidalIdeation"),
      psychFn("rosDeniesHomicidalIdeation"),
      psychFn("rosDeniesHallucinations"),
      psychFn("rosDeniesIngestion"),
      psychFn("rosDeniesTrauma"),
      psychFn("rosDeniesChestPain"),
      psychFn("rosDeniesFever"),
    ],
    rosRedFlags: [
      psychFn("rfActiveSuicidalIdeation"),
      psychFn("rfHomicidalIdeation"),
      psychFn("rfCommandHallucinations"),
      psychFn("rfSevereAgitation"),
      psychFn("rfIntoxicationConcern"),
      psychFn("rfOverdoseIngestionConcern"),
      psychFn("rfUnableToContractForSafety"),
      psychFn("rfUnsafeDischargeEnvironment"),
    ],
    physicalExam: {
      general: [
        psychFn("examWellAppearing"),
        psychFn("examNoAcuteMedicalDistress"),
        psychFn("examIllAppearing"),
        psychFn("examDisheveledAppearance"),
        psychFn("examAppearsAgitated"),
      ],
      neuroPsych: [
        psychFn("examAlertAndOriented"),
        psychFn("examCalmAndCooperative"),
        psychFn("examAgitated"),
        psychFn("examTearful"),
        psychFn("examAnxious"),
        psychFn("examDepressedAffect"),
        psychFn("examPressuredSpeech"),
        psychFn("examSpeechClear"),
        psychFn("examDisorganizedThoughtProcess"),
        psychFn("examHallucinationsNoted"),
        psychFn("examNoAuditoryHallucinations"),
        psychFn("examNoFocalNeurologicDeficit"),
        psychFn("examNormalGait"),
        psychFn("examThoughtsCoherent"),
        psychFn("examSuicidalIdeationOnExam"),
        psychFn("examHomicidalIdeationOnExam"),
      ],
    },
    mdmWorkingAssessment: [
      psychFn("waAcutePsychiatricCrisis"),
      psychFn("waSuicidalIdeation"),
      psychFn("waHomicidalIdeation"),
      psychFn("waPsychosis"),
      psychFn("waBehavioralDisturbance"),
      psychFn("waSubstanceIntoxication"),
      psychFn("waLowSuspicionMedicalDelirium"),
    ],
    mdmDifferentialSynthesis: [
      psychFn("diffImminentSuicideRisk"),
      psychFn("diffHomicidalRisk"),
      psychFn("diffAcutePsychosisUnsafeBehavior"),
      psychFn("diffOverdoseToxicIngestion"),
      psychFn("diffDelirium"),
      psychFn("diffAlcoholWithdrawalSeizureRisk"),
      psychFn("diffSerotoninSyndrome"),
      psychFn("diffNeurolepticMalignantSyndrome"),
      psychFn("diffHypoglycemia"),
      psychFn("diffSepsis"),
      psychFn("diffSuicidalIdeation"),
      psychFn("diffHomicidalIdeation"),
      psychFn("diffPsychosis"),
      psychFn("diffMajorDepression"),
      psychFn("diffAnxietyPanicReaction"),
      psychFn("diffSubstanceIntoxication"),
      psychFn("diffSubstanceWithdrawal"),
      psychFn("diffMania"),
      psychFn("diffMedicationNonadherence"),
    ],
    mdmDataReviewed: [
      psychFn("mdmUrineDrugScreenReviewed"),
      psychFn("mdmEthanolLevelReviewed"),
      psychFn("mdmAcetaminophenLevelReviewed"),
      psychFn("mdmSalicylateLevelReviewed"),
      psychFn("mdmEcgReviewed"),
      psychFn("mdmCbcReviewed"),
      psychFn("mdmCmpReviewed"),
      psychFn("mdmPregnancyTestReviewed"),
      psychFn("mdmGlucoseReviewed"),
      psychFn("mdmCtHeadReviewed"),
    ],
    mdmRiskStratification: [
      psychFn("riskLowSuicideRiskContractForSafety"),
      psychFn("riskStableCooperativeLow"),
      psychFn("riskModeratePsychiatricDistress"),
      psychFn("riskObservationRequiredModerate"),
      psychFn("riskHighSuicideRiskHigh"),
      psychFn("riskHomicidalRiskHigh"),
      psychFn("riskAcutePsychosisHigh"),
      psychFn("riskMedicalClearanceRequiredModerate"),
    ],
    mdmClinicalRationale: [
      psychFn("reasoningSymptomsMostConsistentWithMajorDepression"),
      psychFn("reasoningLowSuspicionMedicalDelirium"),
      psychFn("reasoningLowSuspicionOverdose"),
      psychFn("reasoningMedicalClearanceObtained"),
      psychFn("reasoningSafetyPrecautionsAppropriate"),
      psychFn("reasoningPsychiatricConsultationAppropriate"),
    ],
    clinicalImpression: [
      psychFn("impMajorDepressiveEpisode"),
      psychFn("impAcutePsychosis"),
      psychFn("impSubstanceIntoxication"),
      psychFn("impBehavioralCrisis"),
      psychFn("impAnxietyPanicReaction"),
      psychFn("impMania"),
    ],
    mdmPlanSummary: [
      psychFn("planSuicidePrecautionsInitiated"),
      psychFn("planBehavioralHealthConsulted"),
      psychFn("planMedicationsAdministered"),
      psychFn("planLabsObtained"),
      psychFn("planMedicalClearanceObtained"),
      psychFn("planObservationInEd"),
      psychFn("planPsychiatricAdmissionArranged"),
      psychFn("planVoluntaryAdmissionOffered"),
    ],
    reassessment: [
      psychFn("reassessCalmAndCooperative"),
      psychFn("reassessAgitationImproved"),
      psychFn("reassessRemainsOnSuicidePrecautions"),
      psychFn("reassessSafetyContractMaintained"),
      psychFn("reassessMedicalClearanceObtained"),
      psychFn("reassessToleratingOralIntake"),
    ],
    followUpDisposition: [
      psychFn("dispPsychiatricAdmissionArranged"),
      psychFn("dispPsychiatricTransferArranged"),
      psychFn("dispDischargedWithSafetyPlan"),
      psychFn("dispCrisisResourcesProvided"),
      psychFn("dispReturnPsychiatricRedFlags"),
      psychFn("dispInvoluntaryHoldInitiated"),
    ],
    mdmAdmitObserveDischarge: [
      psychFn("dispObservationInEd"),
      psychFn("dispPsychiatricAdmission"),
      psychFn("dispDischargeHomeWithSafetyPlan"),
    ],
  });
}
